Repository magma/magma, pull requests merged in 2020-07, with the labels that each got.

#1992 [DOC]Redirect to magma.github.io
  index.html
Labels: component: docs

#2028 [NMS] Plug EventTable into top level components
  nms/app/fbcnms-projects/magmalte/app/components/DashboardKPIs.js
  nms/app/fbcnms-projects/magmalte/app/components/lte/LteDashboard.js
  nms/app/fbcnms-projects/magmalte/app/views/equipment/EnodebDetailMain.js
  nms/app/fbcnms-projects/magmalte/app/views/equipment/GatewayDetailMain.js
  nms/app/fbcnms-projects/magmalte/app/views/events/EventsTable.js
  nms/app/fbcnms-projects/magmalte/app/views/subscriber/SubscriberDetail.js
Labels: CLA Signed

#2070 [ci] Re-enable docusaurus job
  .circleci/config.yml
Labels: component: ci

#2075 [DOC]Remove all refs to facebookincubator.github.io
  README.md
  cwf/gateway/integ_tests/README.md
  docs/docusaurus/siteConfig.js
  docs/docusaurus/versioned_docs/version-1.0.0/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.0.0/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.0.1/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.0.1/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.1.0/faq/magma_faq.md
  docs/docusaurus/versioned_docs/version-1.1.0/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.1.0/lte/enodebd.md
  docs/readmes/faq/magma_faq.md
  docs/readmes/lte/config_agw.md
  docs/readmes/lte/enodebd.md
  orc8r/cloud/deploy/terraform/README.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/online-upgrade/README.md
  orc8r/cloud/helm/orc8r/README.md
  orc8r/gateway/go/services/magmad/README.md
Labels: component: docs

#2069 [CI]Run xwfm-test on master
  .circleci/config.yml
Labels: component: ci

#2101 [NMS] Removed subscriber table from eNodeB
  nms/app/fbcnms-projects/magmalte/app/views/equipment/EnodebDetailMain.js
Labels: component: nms

#2121 [orc8r][mesh] Move core plugin impls to orchestrator service
  orc8r/cloud/configs/orchestrator.yml
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/go/plugin/test_utils.go
  orc8r/cloud/go/services/directoryd/directoryd/main.go
  orc8r/cloud/go/services/directoryd/test_init/test_service_init.go
  orc8r/cloud/go/services/metricsd/const.go
  orc8r/cloud/go/services/metricsd/metricsd/main.go
  orc8r/cloud/go/services/metricsd/test_init/test_service_init.go
  orc8r/cloud/go/services/orchestrator/const.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/orchestrator/servicers/exporter_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/exporter_servicer_test.go
  orc8r/cloud/go/services/orchestrator/servicers/gaugeconverter.go
  orc8r/cloud/go/services/orchestrator/servicers/gaugeconverter_test.go
  orc8r/cloud/go/services/orchestrator/servicers/indexer_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/indexer_servicer_test.go
  orc8r/cloud/go/services/orchestrator/servicers/provider_servicer.go
  orc8r/cloud/go/services/orchestrator/test_init/test_service_init.go
  orc8r/cloud/go/services/state/indexer/index/index_test.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_test.go
  orc8r/cloud/go/services/state/indexer/remote_indexer.go
  orc8r/cloud/go/services/streamer/providers/providers_test.go
  orc8r/cloud/go/services/streamer/streamer/main.go
  orc8r/cloud/go/services/streamer/test_init/test_service_init.go
Labels: component: orc8r

#2119 Magma Network Dashboard and dialog screen refactoring/styling
  nms/app/fbcnms-projects/magmalte/app/components/FormField.js
  nms/app/fbcnms-projects/magmalte/app/components/KPIGrid.js
  nms/app/fbcnms-projects/magmalte/app/components/layout/CardTitleRow.js
  nms/app/fbcnms-projects/magmalte/app/theme/default.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkDashboard.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkEdit.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkEpc.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkInfo.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkKPIs.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkRanConfig.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkRanFddConfig.js
  nms/app/fbcnms-projects/magmalte/app/views/network/NetworkRanTddConfig.js
  nms/app/yarn.lock
Labels: component: nms

#2143 [agw][dev] Disable dev_tools.py DNS caching
  lte/gateway/dev_tools.py
Labels: component: agw

#2150 [SessionD] Add symlink to architecture diagram for SessionD README
  lte/gateway/c/session_manager/SessionD_Architecture.png
Labels: component: agw
