Repository magma/magma, pull requests merged in 2020-09, with the labels that each got.

#2532 [NMS] Fix gateway json editor
  nms/app/packages/magmalte/app/components/context/GatewayContext.js
  nms/app/packages/magmalte/app/state/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js
Labels: component: nms

#2606 [NMS] Fix rerendering of EquipmentDashboard upon state update
  nms/app/packages/magmalte/app/components/context/NetworkContext.js
  nms/app/packages/magmalte/app/components/layout/SectionLinks.js
  nms/app/packages/magmalte/app/components/layout/useSections.js
  nms/app/packages/magmalte/app/components/lte/LteSections.js
  nms/app/packages/magmalte/app/components/lte/__tests__/useLteContext-test.js
  nms/app/packages/magmalte/app/components/main/Index.js
Labels: component: nms

#2573 [orc8r][release] Add v1.2 orc8r upgrade docs
  docs/docusaurus/core/Footer.js
  docs/docusaurus/create_docusaurus_website.sh
  docs/docusaurus/sidebars.json
  docs/docusaurus/siteConfig.js
  docs/docusaurus/static/img/magma_logo.png
  docs/readmes/assets/proposals/p002_scaled_prometheus_pipeline/currentMetricsPipeline.png
  docs/readmes/assets/proposals/p002_scaled_prometheus_pipeline/image.png
  docs/readmes/assets/proposals/p002_scaled_prometheus_pipeline/proposedMetricsPipeline.png
  docs/readmes/basics/prerequisites.md
  docs/readmes/orc8r/deploy_build.md
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/upgrade_1_1.md
  docs/readmes/orc8r/upgrade_1_2.md
  docs/readmes/proposals/p001_vpn_config_from_api.md
  docs/readmes/proposals/p002_scaled_prometheus_pipeline.md
  docs/readmes/proposals/p003_qos_enforcement.md
  orc8r/tools/docker/publish.sh
Labels: accept2ship, component: orc8r

#2627 Agw installation bump ovs to 2.8.9 + new patch + Vlan fix
  lte/gateway/deploy/roles/ovs_prepare/tasks/main.yml
  lte/gateway/deploy/roles/ovs_prepare/vars/all.yaml
Labels: component: agw

#2632 [orc8r][policydb] Fix policydb streamer nil dereference
  lte/cloud/go/services/policydb/obsidian/models/conversion.go
  lte/cloud/go/services/policydb/streamer/providers_test.go
Labels: accept2ship, component: orc8r

#2636 [orc8r][deploy] Fix syntax error in app tf module
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
Labels: accept2ship, component: orc8r

#2635 [orc8r][subscriberdb] Fix subscriberdb not streaming apn_resource
  lte/cloud/go/services/lte/servicers/provider_servicer_test.go
  lte/cloud/go/services/subscriberdb/streamer/providers.go
  lte/cloud/go/services/subscriberdb/streamer/providers_test.go
Labels: accept2ship, component: orc8r

#2687 Add reboot button
  nms/app/packages/magmalte/app/state/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailMain.js
Labels: component: nms

#2491 [pipelined] fix gy rules activation during redirection
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: accept2ship

#2493 [AGW] Add Fua Service Restriction proposal
  docs/proposals/fua-restrict-feature/fua-restrict-feature.md
Labels: accept2ship

#2483 [SessionD] Clean up LocalEnforcer
  cwf/gateway/go.mod
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/gateway/c/session_manager/test/Consts.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: SessionD, accept2ship, component: agw

#2666 [FEG] Add support of FUA-Restrict to Feg and MockOCS
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/multi_sessioneproxy_test.go
  feg/cloud/go/protos/mock_core.pb.go
  feg/gateway/services/session_proxy/credit_control/gy/definitions.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client_test.go
  feg/gateway/services/session_proxy/servicers/credits.go
  feg/gateway/services/testcore/ocs/main.go
  feg/gateway/services/testcore/ocs/mock_ocs/ccr_handler.go
  feg/gateway/services/testcore/ocs/mock_ocs/mock.go
  feg/gateway/services/testcore/ocs/mock_ocs/mock_driven_ocs_test.go
  feg/gateway/services/testcore/ocs/mock_ocs/ocs.go
  feg/protos/mock_core.proto
  lte/cloud/go/protos/session_manager.pb.go
  lte/protos/session_manager.proto
Labels: accept2ship

#2702 [orc8r][policydb] Fix policydb streamer bug for dangling QoS profiles
  lte/cloud/go/services/policydb/streamer/providers.go
  lte/cloud/go/services/policydb/streamer/providers_test.go
Labels: accept2ship

#2688 Remove unrelated network types from Magma NMS
  nms/app/packages/magmalte/app/components/devices/DevicesAgentFields.js
  nms/app/packages/magmalte/app/components/devices/DevicesAgents.js
  nms/app/packages/magmalte/app/components/devices/DevicesEditAgentDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesEditManagedDeviceDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesManagedDeviceRow.js
  nms/app/packages/magmalte/app/components/devices/DevicesMetricsDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesNewAgentDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesSections.js
  nms/app/packages/magmalte/app/components/devices/DevicesState.js
  nms/app/packages/magmalte/app/components/devices/DevicesStatusTable.js
  nms/app/packages/magmalte/app/components/devices/DevicesUtils.js
  nms/app/packages/magmalte/app/components/devices/__tests__/DevicesAgents-test.js
  nms/app/packages/magmalte/app/components/devices/__tests__/DevicesStatusTable-test.js
  nms/app/packages/magmalte/app/components/devices/__tests__/DevicesUtils-test.js
  nms/app/packages/magmalte/app/components/devices/test/DevicesMock.js
  nms/app/packages/magmalte/app/components/layout/__tests__/useSections-test.js
  nms/app/packages/magmalte/app/components/layout/useSections.js
  nms/app/packages/magmalte/app/components/rhino/MultiMetrics.js
  nms/app/packages/magmalte/app/components/rhino/RhinoMetrics.js
  nms/app/packages/magmalte/app/components/rhino/RhinoSections.js
  nms/app/packages/magmalte/app/components/rhino/RhinoUtils.js
  nms/app/packages/magmalte/app/components/wifi/WifiConfig.js
  nms/app/packages/magmalte/app/components/wifi/WifiDeviceDetails.js
  nms/app/packages/magmalte/app/components/wifi/WifiDeviceDialog.js
  nms/app/packages/magmalte/app/components/wifi/WifiDeviceFields.js
  nms/app/packages/magmalte/app/components/wifi/WifiDeviceHardwareFields.js
  nms/app/packages/magmalte/app/components/wifi/WifiMap.js
  nms/app/packages/magmalte/app/components/wifi/WifiMapFeatureDetail.js
  nms/app/packages/magmalte/app/components/wifi/WifiMapLayers.js
  nms/app/packages/magmalte/app/components/wifi/WifiMapMarker.js
  nms/app/packages/magmalte/app/components/wifi/WifiMapMarkerIcon.js
  nms/app/packages/magmalte/app/components/wifi/WifiMapMarkerPopup.js
  nms/app/packages/magmalte/app/components/wifi/WifiMeshDialog.js
  nms/app/packages/magmalte/app/components/wifi/WifiMeshRow.js
  nms/app/packages/magmalte/app/components/wifi/WifiMeshesDevicesTable.js
  nms/app/packages/magmalte/app/components/wifi/WifiMetrics.js
  nms/app/packages/magmalte/app/components/wifi/WifiNetworkConfig.js
  nms/app/packages/magmalte/app/components/wifi/WifiSections.js
  nms/app/packages/magmalte/app/components/wifi/WifiSelectConnType.js
  nms/app/packages/magmalte/app/components/wifi/WifiSelectMesh.js
  nms/app/packages/magmalte/app/components/wifi/WifiUtils.js
  nms/app/packages/magmalte/app/components/wifi/__tests__/WifiDeviceDialog-test.js
  nms/app/packages/magmalte/app/components/wifi/__tests__/WifiUtils-test.js
  nms/app/packages/magmalte/app/components/wifi/test/GatewayMock.js
Labels: component: nms

#2683 [SessionD][PipelineD] Add IP addr to deactivate flows
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/test/Consts.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/protos/pipelined.proto
Labels: SessionD, component: agw

#2739 [SessionD] Add `find_session` function to `SessionStore` for easier searching
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/MemoryStoreClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/RedisStoreClient.cpp
  lte/gateway/c/session_manager/RedisStoreClient.h
  lte/gateway/c/session_manager/ServiceAction.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/StoreClient.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
  lte/gateway/c/session_manager/test/test_store_client.cpp
Labels: SessionD, component: agw

#2735 [feg] addition of Requested Service Unit AVP to feg and sessiond
  feg/gateway/services/session_proxy/credit_control/gy/definitions.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client_test.go
  feg/gateway/services/session_proxy/servicers/credits.go
  feg/gateway/services/testcore/ocs/mock_ocs/ccr_handler.go
  feg/gateway/services/testcore/ocs/mock_ocs/mock_driven_ocs_test.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/SessionCredit.cpp
  lte/gateway/c/session_manager/SessionCredit.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/StoreClient.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_credit.cpp
  lte/protos/session_manager.proto
Labels: SessionD, component: feg

#2773 [Sessiond] Add LocalEnforcer final state activation/canceling test + minor fix
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: accept2ship

#2804 Support non-grpc logging
  lte/gateway/c/session_manager/GrpcMagmaUtils.cpp
  orc8r/gateway/c/common/logging/magma_logging.h
Labels: accept2ship

#2822 [SessionD] Add format_session_manager as make command
  lte/gateway/Makefile
Labels: SessionD, accept2ship

#2730 [orc8r][service_registry] Implement service registry service for orc8r service mesh
  cwf/cloud/go/go.sum
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.sum
  devmand/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  feg/gateway/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/docker/controller/supervisord.conf
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/services/service_registry/client_api.go
  orc8r/cloud/go/services/service_registry/doc.go
  orc8r/cloud/go/services/service_registry/service_registry/main.go
  orc8r/cloud/go/services/service_registry/servicers/docker_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/docker_servicer_test.go
  orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer_test.go
  wifi/cloud/go/go.sum
Labels: component: orc8r

#2574 [lte][cwf][orc8r] Split relay_enabled flag to separate support for hss and gx_gy
  cwf/cloud/go/services/cwf/servicers/builder_servicer.go
  cwf/cloud/go/services/cwf/servicers/builder_servicer_test.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/defaults.go
  lte/cloud/go/services/lte/obsidian/models/network_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/cloud/go/tools/migrations/m013_relay_split/main.go
  lte/cloud/go/tools/migrations/m013_relay_split/types/new.go
  lte/cloud/go/tools/migrations/m013_relay_split/types/old.go
Labels: breaking change

#2823 [FeG][SessionD] Add access timezone information to requests to policy component
  cwf/gateway/configs/sessiond.yml
  cwf/gateway/go.sum
  feg/gateway/services/session_proxy/credit_control/gx/definitions.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client_test.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/services/session_proxy/servicers/policy.go
  feg/gateway/services/session_proxy/servicers/session_controller_test.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/configs/sessiond.yml
  lte/protos/session_manager.proto
Labels: SessionD, component: agw, component: feg

#2741 [NMS] Gateway logs autorefresh
  nms/app/packages/magmalte/app/components/AutorefreshCheckbox.js
  nms/app/packages/magmalte/app/views/equipment/GatewayLogs.js
  nms/app/packages/magmalte/app/views/events/EventsTable.js
Labels: component: nms

#2889 [SessionD] Lookup Session IP in SessionContext if it exists
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: SessionD, component: agw

#2833 Add ipv6 proto definitions for AGW
  cwf/gateway/integ_tests/static_rules.go
  feg/gateway/policydb/flow_parser.go
  feg/gateway/policydb/flow_parser_test.go
  lte/cloud/go/protos/pipelined.pb.go
  lte/cloud/go/protos/policydb.pb.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go
  lte/cloud/go/services/policydb/obsidian/models/conversion.go
  lte/cloud/go/services/policydb/obsidian/models/flow_match_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/ip_address_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/policydb/obsidian/models/validate.go
  lte/cloud/go/services/policydb/streamer/providers_test.go
  lte/cloud/go/tools/migrations/m013_policy_ipv6/main.go
  lte/cloud/go/tools/migrations/m013_policy_ipv6/types/new.go
  lte/cloud/go/tools/migrations/m013_policy_ipv6/types/old.go
  lte/gateway/c/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/oai/tasks/grpc_service/SpgwServiceImpl.cpp
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/test_dpi.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_internal_pkt_ipfix_export.py
  lte/gateway/python/magma/pipelined/tests/test_redirect.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
  lte/gateway/python/magma/pipelined/tests/test_rule_mappers.py
  lte/gateway/python/scripts/pipelined_cli.py
  lte/gateway/python/scripts/policydb_cli.py
  lte/protos/pipelined.proto
  lte/protos/policydb.proto
  orc8r/gateway/c/common/datastore/CMakeLists.txt
Labels: breaking change

#2753 [Pipelined] Add support for static rules activation in gy app
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/test_gy.py
Labels: accept2ship

#2757 [CWF] Add Integration test case for FUA Restrict
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/static_rules.go
Labels: accept2ship

#2872 [MME] Apn correction support
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_apn_selection.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_apn_selection.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/configs/mme.yml
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_esm_information_apn_correction.py
  lte/gateway/python/integ_tests/s1aptests/test_standalone_pdn_conn_req_with_apn_correction.py
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
Labels: accept2ship

#2918 [NMS] Update MagmaApiBindings in NMS
  nms/app/.flowconfig
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/devices/DevicesAgentFields.js
  nms/app/packages/magmalte/app/components/devices/DevicesAgents.js
  nms/app/packages/magmalte/app/components/devices/DevicesEditAgentDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesEditManagedDeviceDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesManagedDeviceRow.js
  nms/app/packages/magmalte/app/components/devices/DevicesMetricsDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesNewAgentDialog.js
  nms/app/packages/magmalte/app/components/devices/DevicesSections.js
  nms/app/packages/magmalte/app/components/devices/DevicesState.js
  nms/app/packages/magmalte/app/components/devices/DevicesStatusTable.js
  nms/app/packages/magmalte/app/components/devices/DevicesUtils.js
  nms/app/packages/magmalte/app/components/devices/__tests__/DevicesAgents-test.js
  nms/app/packages/magmalte/app/components/devices/__tests__/DevicesStatusTable-test.js
  nms/app/packages/magmalte/app/components/devices/__tests__/DevicesUtils-test.js
  nms/app/packages/magmalte/app/components/devices/test/DevicesMock.js
  nms/app/packages/magmalte/app/components/feg/FEGGatewayDialog.js
  nms/app/packages/magmalte/app/components/layout/__tests__/useSections-test.js
  nms/app/packages/magmalte/app/components/layout/useSections.js
  nms/app/packages/magmalte/app/components/network/PoliciesConfig.js
  nms/app/packages/magmalte/app/components/network/PolicyQosFields.js
  nms/app/packages/magmalte/app/components/network/PolicyRuleEditDialog.js
  nms/app/packages/magmalte/app/views/network/NetworkEpc.js
  nms/app/packages/magmalte/app/views/network/__tests__/NetworkTest.js
  nms/app/packages/magmalte/server/network/routes.js
Labels: component: nms

#2926 [NMS] Add support to disable dhcp service at gateway level
  nms/app/packages/magmalte/app/state/lte/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/GatewayConfigTest.js
Labels: component: nms

#2540 [5G: MVC][SessionD] SessionD-Pipelined Set message and SMF-UPF Proto
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/upf-demo-struct.h
  lte/protos/pipelined.proto
Labels: 5G: MVC, component: agw, type: enhancement

#2544 [SessionD] 5G Session state manager and Enforcer code
  lte/gateway/c/session_manager/AmfServiceClient.cpp
  lte/gateway/c/session_manager/AmfServiceClient.h
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.h
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: 5G: MVC, component: agw, type: enhancement

#2555 [5G: MVC][SessionD]Landing object server file for set message of AMF
  lte/gateway/c/session_manager/SessionManagerServer.cpp
  lte/gateway/c/session_manager/SessionManagerServer.h
Labels: 5G: MVC, component: agw, type: enhancement

#2584 [5G: MVC][SessionD] Rulestore and SessionState changes of 5g initial commit
  lte/gateway/Makefile
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/RuleStore.cpp
  lte/gateway/c/session_manager/RuleStore.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/configs/sessiond.yml
Labels: 5G: MVC, component: agw, type: enhancement

#2944 [SessionD] Resolve CWF integration test failure by ensuring we do not run 5G components outside of 5G use cases
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: 5G: MVC, SessionD, bug-fix, component: agw

#2948 [orc8r] Increase the buckets in nginx
  orc8r/cloud/docker/nginx/templates/nginx.conf.j2
Labels: component: orc8r

#2973 [FeG] Fix timezone AVP algorithm
  feg/gateway/services/session_proxy/credit_control/gx/gx_client.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client_test.go
Labels: accept2ship

#2936 [orc8r][service registry] Update registry library to use service registry service when in k8s/docker mode
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/pkg/registry/registry.go
  fbinternal/cloud/go/services/download/servicers/server_lib.go
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/go/obsidian/reverse_proxy/reverse_proxy.go
  orc8r/cloud/go/service/middleware/unary/identity_decorator.go
  orc8r/cloud/go/services/certifier/servicers/certifier.go
  orc8r/cloud/go/services/configurator/mconfig/registry.go
  orc8r/cloud/go/services/metricsd/registry.go
  orc8r/cloud/go/services/metricsd/servicers/servicer.go
  orc8r/cloud/go/services/service_registry/doc.go
  orc8r/cloud/go/services/service_registry/service_registry/main.go
  orc8r/cloud/go/services/service_registry/servicers/docker_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/docker_servicer_test.go
  orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer_test.go
  orc8r/cloud/go/services/state/indexer/registry.go
  orc8r/cloud/go/services/streamer/providers/registry.go
  orc8r/cloud/go/tools/service303_cli/main.go
  orc8r/gateway/go/service_registry/registry.go
  orc8r/lib/go/registry/client/client_api.go
  orc8r/lib/go/registry/global_registry.go
  orc8r/lib/go/registry/registry.go
  orc8r/lib/go/service/middleware/unary/client_identity.go
Labels: component: orc8r

#2977 [lte] Add make precommit commands for Gateway C++
  lte/gateway/Makefile
Labels: accept2ship, easy
