Repository magma/magma, pull requests merged in 2020-10, with the labels that each got.

#3007 [xwfm][ci] Update xwfm tests to report status to slack channels
  .circleci/config.yml
Labels: component: ci

#3017 [NMS] Fix the error displayed when network information is edited.
  nms/app/packages/magmalte/app/components/admin/CWFNetworkDialog.js
  nms/app/packages/magmalte/app/components/admin/EditNetworkDialog.js
  nms/app/packages/magmalte/app/components/admin/FEGNetworkDialog.js
Labels: component: nms

#3011 [NMS] Add e2e test to verify add/edit of feg_lte network
  nms/app/package.json
  nms/app/packages/magmalte/Dockerfile
  nms/app/packages/magmalte/app/e2e/LoginUtils.js
  nms/app/packages/magmalte/app/e2e/NetworkUtils.js
  nms/app/packages/magmalte/app/e2e/__tests__/App-test.js
  nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js
  nms/app/packages/magmalte/config/webpack.config.js
  nms/app/packages/magmalte/docker-compose-e2e.yml
  nms/app/packages/magmalte/docker-compose.yml
  nms/app/packages/magmalte/e2e_test_setup.sh
  nms/app/packages/magmalte/mock/db.json
  nms/app/packages/magmalte/package.json
  nms/app/packages/magmalte/scripts/mockServer.js
  nms/app/packages/magmalte/server/app.js
  nms/app/yarn.lock
Labels: component: nms

#3078 [orc8r][indexers] Fix broken indexer manager CLI
  orc8r/cloud/go/tools/indexers/cmd/root.go
Labels: accept2ship, component: orc8r

#2905 [orc8r] [configs] Fix misleading error when config is set to false
  orc8r/gateway/python/magma/configuration/service_configs.py
Labels: bug-fix

#2966 [orc8r][subscriberdb] Add IP-indexed subscriber lookup
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/services/subscriberdb/client_api.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/subscriberdb/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/protos/subscriberdb.proto
  lte/cloud/go/services/subscriberdb/protos/validate.go
  lte/cloud/go/services/subscriberdb/servicers/indexer_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/indexer_servicer_test.go
  lte/cloud/go/services/subscriberdb/servicers/lookup.go
  lte/cloud/go/services/subscriberdb/servicers/lookup_test.go
  lte/cloud/go/services/subscriberdb/state/extract.go
  lte/cloud/go/services/subscriberdb/storage/ip_lookup.go
  lte/cloud/go/services/subscriberdb/storage/ip_lookup_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/cloud/helm/lte-orc8r/values.yaml
  lte/gateway/python/scripts/mobility_cli.py
Labels: accept2ship, apply-v1.3, breaking change, component: orc8r

#3079 [smsd] Add AGW SMS relay service
  cwf/k8s/cwf_operator/go.mod
  feg/gateway/go.sum
  lte/cloud/go/services/smsd/servicers/models/conversion.go
  lte/gateway/c/oai/lib/sms_orc8r_client/SMSOrc8rClient.cpp
  lte/gateway/configs/magmad.yml
  lte/gateway/configs/service_registry.yml
  lte/gateway/configs/smsd.yml
  lte/gateway/python/magma/smsd/__init__.py
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/smsd/relay.py
  lte/gateway/python/setup.py
  lte/protos/sms_orc8r.proto
  orc8r/tools/ansible/roles/test_certs/tasks/main.yml
Labels: apply-v1.3

#3020 [lte][agw] Adding gtp statistics collector to pipelined
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/magma/pipelined/gtp_stats_collector.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/metrics.py
  lte/gateway/python/magma/subscriberdb/tests/metrics_tests.py
Labels: apply-v1.3

#3093 [orc8r][lte] Fix misreported apn_resource
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
Labels: accept2ship, apply-v1.2, apply-v1.3, component: orc8r

#3058 [lte][orc8r] Fix 3009 which prevented add of multi apn_resource
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
Labels: DONOTLAND, apply-v1.2

#3095 [lte][agw] Filling fields param with default hashmap on UpdateRecord gRPC call
  lte/gateway/c/oai/lib/directoryd/GatewayDirectorydClient.cpp
Labels: apply-v1.1

#3096 [bug_fix] [agw] Check for valid EMM context before handling T3489 timer
  lte/gateway/c/oai/tasks/nas/esm/esm_data_context.c
  lte/gateway/c/oai/tasks/nas/esm/esm_information.c
Labels: apply-v1.1, apply-v1.3

#3098 [backport-v1.1] [agw] [mme] Add eDRX stub from PR#2888 to v1.1
  lte/gateway/c/oai/lib/3gpp/3gpp_24.008.h
  lte/gateway/c/oai/lib/3gpp/3gpp_24.008_gmm_ies.c
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachRequest.c
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachRequest.h
Labels: backported-v1.1

#3097 [backport-v1.1] [bug_fix] [agw] Check for non-null EMM context at T3489 timer expiry
  lte/gateway/c/oai/tasks/nas/esm/esm_data_context.c
  lte/gateway/c/oai/tasks/nas/esm/esm_information.c
Labels: backported-v1.1

#3094 [lte][agw] Backport c5d1929 to reject multiple sessions per APN and IPv6 only sessions
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_apn_selection.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_apn_selection.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/oai/tasks/nas/esm/esm_data.h
  lte/gateway/c/oai/tasks/nas/esm/esm_proc.h
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/integ_tests/common/subscriber_db_client.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ipv4v6_pdn_type.py
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
Labels: backported-v1.1

#2997 [backport-v1.1][agw] [subscriberdb] Start subscriberdb rpc servicer if there are sub…
  lte/gateway/python/magma/subscriberdb/main.py
Labels: backported-v1.1

#3107 [SessionD] Add 'IMSI' prefix to user_name received from SessionProxy for ASR
  lte/gateway/c/session_manager/SessionProxyResponderHandler.cpp
  lte/gateway/c/session_manager/test/Consts.h
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
Labels: apply-v1.3

#2998 [backport-v1.2] build: avoid git-cherry-pick ovs build script
  lte/gateway/deploy/roles/ovs_prepare/tasks/main.yml
  lte/gateway/release/build-ovs.sh
Labels: backported-v1.2

#3112 [lte][agw] Adding default polling_interval for gtp_stats param to pipelined
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/main.py
Labels: apply-v1.3

#3113 [SessionD] Do not report credit that is in final state
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: apply-v1.3

#3080 [CWF][obsidian] Update CWF HA pairs to have complete pair state in model
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers_test.go
  cwf/cloud/go/services/cwf/obsidian/models/carrier_wifi_ha_pair_state_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/conversion.go
  cwf/cloud/go/services/cwf/obsidian/models/cwf_ha_pair_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/mutable_cwf_ha_pair_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/swagger.v1.yml
Labels: apply-v1.3, component: orc8r

#3118 AGW: SPGW: enable ovs multi tunnel feature
  lte/gateway/configs/spgw.yml
Labels: accept2ship, apply-v1.3

#3126 Fix MagmaApiBindings
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
Labels: component: nms

#2884 [agw][stateless] Remove systemd dependency check for stateless services
  lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.h
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/deploy/roles/magma/files/config_stateless_agw.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_mme.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_mobilityd.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_pipelined.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_sessiond.sh
  lte/gateway/deploy/roles/magma/files/systemd/sctpd.service
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_ip_blocks_mobilityd_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_mobilityd_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_multiple_service_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_implicit_detach_timer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_mobile_reachability_timer_with_mme_restart.py
  lte/gateway/release/build-magma.sh
Labels: apply-v1.3, breaking change, component: agw

#3117 Fix wrong service name on lte service_registry
  lte/gateway/configs/service_registry.yml
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/scripts/session_manager_cli.py
Labels: apply-v1.3

#3132 [v1.3] Update orc8r terraform modules for 1.3 release
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: apply-v1.3

#3101 [CWF][Helm] Update cwf gateway helm charts to fully support HA deployments
  cwf/gateway/docker/.env
  cwf/gateway/docker/.prod_env
  cwf/gateway/docker/docker-compose.yml
  cwf/gateway/helm/cwf-kubevirt/Chart.yaml
  cwf/gateway/helm/cwf-kubevirt/templates/bin/_env.tpl
  cwf/gateway/helm/cwf-kubevirt/templates/bin/_install_gateway.sh.tpl
  cwf/gateway/helm/cwf-kubevirt/templates/bin/_sessiond.yml.tpl
  cwf/gateway/helm/cwf-kubevirt/templates/configmap-env.yaml
  cwf/gateway/helm/cwf-kubevirt/values.yaml
  cwf/gateway/helm/cwf-virtlet/Chart.yaml
  cwf/gateway/helm/cwf-virtlet/templates/bin/_env.tpl
  cwf/gateway/helm/cwf-virtlet/templates/bin/_install_gateway.sh.tpl
  cwf/gateway/helm/cwf-virtlet/templates/bin/_sessiond.yml.tpl
  cwf/gateway/helm/cwf-virtlet/templates/configmap-env.yaml
  cwf/gateway/helm/cwf-virtlet/values.yaml
  cwf/k8s/cwf_operator/README.md
Labels: apply-v1.3

#3137 [orc8r][lte][bugfix] Fix buggy apn_resource bulk update
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  orc8r/cloud/go/obsidian/tests/unit_test_utils.go
Labels: accept2ship, apply-v1.2, apply-v1.3, component: orc8r

#3142 [orc8r][tf] Set portEnd for controller service to 9121 in Helm values
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
Labels: apply-v1.3

#3111 [orc8r][agw] Add default GW support for static SGi MGMT IP
  docs/readmes/howtos/ue_ip_address_management.md
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
  lte/protos/mconfig/mconfigs.proto
Labels: apply-v1.3

#3131 [nms][cwag] Add CWAG HA status to NMS CWAG page
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/cwf/CWFGateways.js
  nms/app/packages/magmalte/app/components/cwf/__tests__/CWFGateways-test.js
Labels: apply-v1.3

#3160 [lte][agw] Fix IMSI prefix handling and cli service
  lte/gateway/c/oai/tasks/grpc_service/proto_msg_to_itti_msg.cpp
  lte/gateway/python/scripts/sms_cli.py
Labels: apply-v1.3

#3141 [LTE][AGW][Installation] Adding a new check for linux Headers
  lte/gateway/deploy/agw_install.sh
Labels: apply-v1.3

#3163 [lte][agw] Replace unsigned arithmetic in condition statements
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachAccept.c
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachReject.c
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachRequest.c
  lte/gateway/c/oai/tasks/nas/emm/msg/AuthenticationFailure.c
  lte/gateway/c/oai/tasks/nas/emm/msg/CsServiceNotification.c
  lte/gateway/c/oai/tasks/nas/emm/msg/EmmInformation.c
  lte/gateway/c/oai/tasks/nas/emm/msg/GutiReallocationCommand.c
  lte/gateway/c/oai/tasks/nas/emm/msg/SecurityModeCommand.c
  lte/gateway/c/oai/tasks/nas/emm/msg/SecurityModeComplete.c
  lte/gateway/c/oai/tasks/nas/emm/msg/TrackingAreaUpdateAccept.c
  lte/gateway/c/oai/tasks/nas/emm/msg/TrackingAreaUpdateRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextAccept.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ActivateDefaultEpsBearerContextAccept.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ActivateDefaultEpsBearerContextReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ActivateDefaultEpsBearerContextRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/BearerResourceAllocationReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/BearerResourceAllocationRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/BearerResourceModificationReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/BearerResourceModificationRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/DeactivateEpsBearerContextAccept.c
  lte/gateway/c/oai/tasks/nas/esm/msg/DeactivateEpsBearerContextRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/EsmInformationResponse.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ModifyEpsBearerContextAccept.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ModifyEpsBearerContextReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/ModifyEpsBearerContextRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/PdnConnectivityReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/PdnConnectivityRequest.c
  lte/gateway/c/oai/tasks/nas/esm/msg/PdnDisconnectReject.c
  lte/gateway/c/oai/tasks/nas/esm/msg/PdnDisconnectRequest.c
Labels: apply-v1.1, apply-v1.2, apply-v1.3

#3164 Fix pipelined gy deactivation
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: apply-v1.3

#3175 [sms] Update smsd message type consts for decoding uplink reports.
  lte/cloud/go/sms_ll/sms_cp.go
Labels: apply-v1.3

#3168 [lte][agw] Bug fix for bstring function
  lte/gateway/c/oai/lib/bstr/bstrlib.c
  lte/gateway/c/oai/tasks/sms_orc8r/sms_orc8r_service_handler.c
Labels: apply-v1.3

#3037 [pipelined]Add IPv4 IPv6 UE RPC Handling
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/app/packet_builder.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/app/table_isolation.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_invalid_subscriber.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_ipv6_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_two_policies.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_two_subscribers.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_redirect.RedirectTest.test_ipv4_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_redirect.RedirectTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/scripts/pipelined_cli.py
  lte/protos/session_manager.proto
Labels: DONOTLAND

#3216 [orc8r][lte] Fix bug updating gw with both enb and apn_resource
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  orc8r/cloud/go/services/configurator/types.go
Labels: accept2ship, apply-v1.2, apply-v1.3, component: orc8r

#3218 [CI] [lte-integ-tests] Remove flaky stateless AGW tests from sanity test suite
  lte/gateway/python/integ_tests/defs.mk
Labels: component: ci

#2436 [pipelined]GTP functionality support in pipelined
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/start_pipelined.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_detach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_discard_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_install_internal_pkt_fwd_flow.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_resume_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_traffic.GTPTrafficTest.test_traffic_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_traffic.py
  lte/gateway/python/magma/pipelined/tests/test_service_manager.py
  lte/gateway/python/magma/pipelined/utils.py
Labels: 5G: MVC, component: agw, type: enhancement

#3229 [lte][agw] Using enb_id to identify s1_setup event as enb_name is optional param
  lte/gateway/c/oai/tasks/mme_app/mme_events.cpp
Labels: apply-v1.3

#3075 [cwf] Fix reauth tests to wait and check for a conditional
  cwf/gateway/integ_tests/gx_qos_enforcement_test.go
  cwf/gateway/integ_tests/gx_reauth_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/gy_reauth_test.go
  cwf/gateway/integ_tests/omni_rules_test.go
  cwf/gateway/integ_tests/test_runner.go
Labels: product: CWF

#3214 [lte][orc8r][agw] SMS bug fix for sms report decoding
  lte/cloud/go/sms_ll/sms_cp.go
  lte/cloud/go/sms_ll/sms_ll.go
  lte/cloud/go/sms_ll/sms_ll_test.go
  lte/cloud/go/sms_ll/sms_rp.go
  lte/gateway/python/magma/smsd/relay.py
Labels: apply-v1.3

#3256 Update MagmaApiBindings
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
Labels: component: nms

#3258 [backport v1.3][lte][agw] Bug fix for handling activate default reject message (#3147)
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
Labels: backported-v1.3

#3173 [NMS] Refactor policy dialogs and add tests
  nms/app/packages/magmalte/app/components/context/PolicyContext.js
  nms/app/packages/magmalte/app/components/lte/LteContext.js
  nms/app/packages/magmalte/app/e2e/__tests__/App-test.js
  nms/app/packages/magmalte/app/e2e/__tests__/Policy-test.js
  nms/app/packages/magmalte/app/state/PolicyState.js
  nms/app/packages/magmalte/app/views/network/__tests__/NetworkTest.js
  nms/app/packages/magmalte/app/views/traffic/ApnOverview.js
  nms/app/packages/magmalte/app/views/traffic/PolicyApp.js
  nms/app/packages/magmalte/app/views/traffic/PolicyEdit.js
  nms/app/packages/magmalte/app/views/traffic/PolicyFlows.js
  nms/app/packages/magmalte/app/views/traffic/PolicyInfo.js
  nms/app/packages/magmalte/app/views/traffic/PolicyOverview.js
  nms/app/packages/magmalte/app/views/traffic/PolicyQos.js
  nms/app/packages/magmalte/app/views/traffic/PolicyRedirect.js
  nms/app/packages/magmalte/app/views/traffic/PolicyStyles.js
  nms/app/packages/magmalte/app/views/traffic/PolicySubscribers.js
  nms/app/packages/magmalte/app/views/traffic/PolicyTracking.js
  nms/app/packages/magmalte/app/views/traffic/TrafficOverview.js
  nms/app/packages/magmalte/app/views/traffic/__tests__/PolicyAddEditTest.js
  nms/app/packages/magmalte/app/views/traffic/__tests__/TrafficOverviewTest.js
  nms/app/packages/magmalte/mock/db.json
  nms/app/packages/magmalte/scripts/mockServer.js
Labels: component: nms

#3100 [lte][agw] Extending eNB config for managed and externally managed setups
  lte/cloud/go/plugin/plugin.go
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/protos/s1ap_service.pb.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/const.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  lte/cloud/go/services/lte/obsidian/models/enodeb_config_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/enodeb_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/unmanaged_enodeb_configuration_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/validate.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/cloud/go/tools/migrations/m014_enodeb_config/main.go
  lte/gateway/c/oai/include/s1ap_state.h
  lte/gateway/c/oai/include/s1ap_types.h
  lte/gateway/c/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/oai/tasks/grpc_service/S1apServiceImpl.cpp
  lte/gateway/c/oai/tasks/grpc_service/S1apServiceImpl.h
  lte/gateway/c/oai/tasks/grpc_service/grpc_service.cpp
  lte/gateway/configs/service_registry.yml
  lte/gateway/python/magma/enodebd/device_config/configuration_util.py
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/main.py
  lte/gateway/python/magma/enodebd/s1ap_client.py
  lte/protos/mconfig/mconfigs.proto
  lte/protos/s1ap_service.proto
Labels: apply-v1.3, breaking change

#3165 [NMS] Adding predefined alerts for CWF, FWA, FEG networks
  nms/app/packages/magmalte/alerts/cwfAlerts.js
  nms/app/packages/magmalte/alerts/fegAlerts.js
  nms/app/packages/magmalte/alerts/lteAlerts.js
  nms/app/packages/magmalte/alerts/sync.js
  nms/app/packages/magmalte/app/components/admin/Alerts.js
Labels: component: nms

#3328 [orc8r][metrics] Refactor orchestrator's metrics exporter to not fatal locally
  lte/cloud/configs/smsd.yml
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/orchestrator/servicers/grpc_exporter_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/grpc_exporter_servicer_test.go
  orc8r/cloud/go/services/orchestrator/servicers/mocks/EdgeHubClient.go
  orc8r/cloud/go/services/orchestrator/servicers/mocks/EdgeHubServer.go
  orc8r/lib/go/registry/registry.go
Labels: accept2ship, component: orc8r

#3360 [orc8r][state] Don't panic on non-validateable reported state
  orc8r/cloud/go/services/state/types/types.go
Labels: accept2ship, bug-fix, component: orc8r

#3364 [orc8r][test] Default to logging statements in postgres_test
  orc8r/cloud/docker/docker-compose.override.yml
Labels: accept2ship, component: orc8r

#3363 [orc8r][indexers] Fix double-logging of reindexer error
  orc8r/cloud/go/serde/registry.go
  orc8r/cloud/go/services/state/indexer/reindex/queue_sql.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer.go
Labels: accept2ship, component: orc8r

#3293 [NMS] Adding placeholders for policy qos profiles and rating
  nms/app/packages/magmalte/app/e2e/__tests__/Policy-test.js
  nms/app/packages/magmalte/app/views/traffic/PolicyOverview.js
  nms/app/packages/magmalte/app/views/traffic/TrafficOverview.js
  nms/app/packages/magmalte/app/views/traffic/__tests__/PolicyAddEditTest.js
  nms/app/packages/magmalte/app/views/traffic/__tests__/TrafficOverviewTest.js
Labels: component: nms

#3377 AGW: Update uplink bridge flow to avoid NORMAL action
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTestVlan.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Test.testFlowSnapshotMatch.snapshot
Labels: apply-v1.3

#3406 [agw][mme] Fix the logic for checking zero eNB IP addr
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
Labels: type: bug

#3417 Updating directoryd report location to be done until UE registered state
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: apply-v1.3

#3409 [bug fix][lte][agw] Fix for sending MBR after receiving erab setup rsp and activate default bearer accept
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
Labels: apply-v1.3

#3381 [SessionD] Add pdp_end_time to update criteria to ensure it is persisted
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
Labels: SessionD, bug-fix, component: agw

#3425 [orc8r][serdes] Fix broken mconfig for shared network types
  orc8r/cloud/go/serde/registry.go
  orc8r/cloud/go/services/configurator/types.go
Labels: accept2ship, bug-fix, component: orc8r

#3407 [SessionD] Add first_usage and last_usage in SessionCredit
  lte/gateway/c/session_manager/SessionCredit.cpp
  lte/gateway/c/session_manager/SessionCredit.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/test/test_session_credit.cpp
Labels: SessionD

#3420 [SessionD] Add fields to terminate event
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionEvents.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/test/test_session_state.cpp
Labels: SessionD

#3419 [NMS] Double test timeout for NMS e2e tests
  nms/app/packages/magmalte/app/e2e/__tests__/App-test.js
  nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js
  nms/app/packages/magmalte/app/e2e/__tests__/Policy-test.js
  nms/app/packages/magmalte/e2e_test_setup.sh
Labels: component: nms

#3424 [lte][agw] Handle out of order E-RAB set up response for dedicated bearers
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr.h
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
Labels: apply-v1.3

#3457 [lte][agw] Add IMSI prefix for RPC calls to orc8r
  lte/gateway/python/magma/smsd/relay.py
Labels: apply-v1.3

#3458 [orc8r] Adding TAC to unmanaged eNB configs
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/unmanaged_enodeb_configuration_swaggergen.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
Labels: apply-v1.3

#3459 AGW: MME: GTP_APP: Fix array realloc size.
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
Labels: apply-v1.3

#3463 [orc8r][mesh][serdes] Convert remaining serdes to non-registry pattern
  cwf/cloud/go/serdes/serdes.go
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  fbinternal/cloud/go/plugin/plugin.go
  fbinternal/cloud/go/serdes/serdes.go
  fbinternal/cloud/go/services/testcontroller/defs.go
  fbinternal/cloud/go/services/testcontroller/e2e_client_api.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers_test.go
  fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
  fbinternal/cloud/go/services/testcontroller/testcontroller/main.go
  feg/cloud/go/serdes/serdes.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  feg/cloud/go/services/feg_relay/utils/get_all_gateways.go
  feg/cloud/go/services/health/servicers/health_test.go
  lte/cloud/go/serdes/serdes.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/blobstore/storage.go
  orc8r/cloud/go/plugin/plugin.go
  orc8r/cloud/go/plugin/plugin_test.go
  orc8r/cloud/go/pluginimpl/plugin.go
  orc8r/cloud/go/serde/doc.go
  orc8r/cloud/go/serde/registry.go
  orc8r/cloud/go/serde/registry_internal_test.go
  orc8r/cloud/go/serdes/serdes.go
  orc8r/cloud/go/service/middleware/unary/identity_decorator_test.go
  orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
  orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper_test.go
  orc8r/cloud/go/services/configurator/test_utils/utils.go
  orc8r/cloud/go/services/device/client_api.go
  orc8r/cloud/go/services/device/client_api_test.go
  orc8r/cloud/go/services/device/protos/device_helper.go
  orc8r/cloud/go/services/device/protos/validate.go
  orc8r/cloud/go/services/device/servicers/device.go
  orc8r/cloud/go/services/device/servicers/proto_validation.go
  orc8r/cloud/go/services/directoryd/client_api_test.go
  orc8r/cloud/go/services/metricsd/servicers/servicer_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handler_factory.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handler_factory_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/state/client_api_test.go
  wifi/cloud/go/serdes/serdes.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers_test.go
Labels: accept2ship, component: orc8r

#3376 [NMS] Add support for unmanaged eNodeBs
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/lte/EnodebUtils.js
  nms/app/packages/magmalte/app/state/README.md
  nms/app/packages/magmalte/app/state/lte/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebConfigTest.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebDetailMainTest.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EquipmentEnodebTest.js
Labels: component: nms

#3382 AGW: pipelined: QoS: TC: Fix APN AMBR
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_meter_impl.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: apply-v1.3

#2914 [agw] [stateless] Add python script to create override config for stateless services
  lte/gateway/deploy/roles/magma/files/systemd/sctpd.service
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/scripts/config_stateless_agw.py
  lte/gateway/python/setup.py
  lte/gateway/release/build-magma.sh
Labels: breaking change

#3440 [teravm] opensource teravm driver script
  ci-scripts/teravm/README.md
  ci-scripts/teravm/fabfile.py
  ci-scripts/teravm/fabfile_teravm_conf.json
Labels: component: ci

#3484 [FeG] Add ChargingCharacteristics to S6A proto and propagate message to MM
  feg/cloud/go/protos/s6a_proxy.pb.go
  feg/gateway/services/s6a_proxy/servicers/s6a_definitions.go
  feg/gateway/services/s6a_proxy/servicers/ul.go
  feg/protos/s6a_proxy.proto
Labels: component: feg

#3500 [MME] Handle charging char in mme
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/oai/common/common_types.h
  lte/gateway/c/oai/include/mme_app_ue_context.h
  lte/gateway/c/oai/include/s11_messages_types.h
  lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/oai/lib/s6a_proxy/proto_msg_to_itti_msg.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/protos/oai/spgw_state.proto
  lte/protos/session_manager.proto
Labels: component: agw

#3529 [sessiond] add some missing tests for ipv6
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: component: agw

#3508 [agw] [stateless mme] Fix memory leaks in stateless MME
  lte/gateway/c/oai/common/itti_free_defined_msg.c
  lte/gateway/c/oai/tasks/grpc_service/S1apServiceImpl.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/esm/esm_data_context.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c
  lte/gateway/c/oai/tasks/sgw/pgw_procedures.c
  lte/gateway/c/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.h
Labels: component: agw

#3462 [agw] [stateless MME] Fix for failing stateless AGW integration tests
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/deploy/roles/magma/files/config_stateless_agw.sh
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw

#3552 [agw][mme] [teravm] Start SGS and SMS Grpc listeners only when services are enabled
  lte/gateway/c/oai/tasks/grpc_service/grpc_service.cpp
Labels: TeraVM, apply-v1.3, component: agw

#3553 [agw][stateless MME] Turn-off 5G GTP app for pipelined
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw

#3536 [SessionD] Add charging characteristics in SessionD events + fix a few fields
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionEvents.h
Labels: SessionD, component: agw
