Repository magma/magma, pull requests merged in 2020-11, with the labels that each got.

#3572 AGW: handle missing "router_ip" option in DHCP response.
  lte/gateway/python/magma/mobilityd/dhcp_client.py
  lte/gateway/python/magma/mobilityd/tests/test_uplink_gw.py
  lte/gateway/python/magma/mobilityd/uplink_gw.py
Labels: apply-v1.3

#3537 [orc8r][mesh][service reg] Update service registry to reuse conns to service registry service
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/templates/controller.deployment.yaml
  orc8r/lib/go/registry/registry.go
Labels: component: orc8r

#2897 [orc8r] OCN WS#2 5G Orchestration MVC Source code
  cn/deploy/docker/amf_dockerfile
  cn/deploy/docker/smf_dockerfile
  cn/deploy/docker/upf_dockerfile
  cn/deploy/helm/Chart.yaml
  cn/deploy/helm/templates/amfchart.yaml
  cn/deploy/helm/templates/efkchart.yaml
  cn/deploy/helm/templates/monitoring.coreos.com_alertmanagers.yaml
  cn/deploy/helm/templates/monitoring.coreos.com_podmonitors.yaml
  cn/deploy/helm/templates/monitoring.coreos.com_prometheuses.yaml
  cn/deploy/helm/templates/monitoring.coreos.com_prometheusrules.yaml
  cn/deploy/helm/templates/monitoring.coreos.com_servicemonitors.yaml
  cn/deploy/helm/templates/monitoring.coreos.com_thanosrulers.yaml
  cn/deploy/helm/templates/smfchart.yaml
  cn/deploy/helm/templates/upfchart.yaml
  cn/deploy/helm/values.yaml
  cn/deploy/scripts/README.txt
  cn/deploy/scripts/script.sh
Labels: 5G: MVC

#3534 [nms] Update eNodeb docs and metrics to use datapath gtp stats
  docs/readmes/assets/nms/disable_dhcp_gw.png
  docs/readmes/assets/nms/register_unmanaged_enb.png
  docs/readmes/lte/enodebd.md
  lte/cloud/go/services/lte/obsidian/models/defaults.go
  lte/cloud/go/services/lte/obsidian/models/enodeb_state_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/gateway/python/magma/enodebd/enodeb_status.py
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/__tests__/KPI-test.js
  nms/app/packages/magmalte/app/components/lte/LteMetrics.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js
  nms/app/packages/magmalte/app/views/equipment/EquipmentEnodeb.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailEnodebs.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebConfigTest.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebDetailMainTest.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EquipmentEnodebTest.js
  nms/app/packages/magmalte/app/views/network/__tests__/NetworkTest.js
  nms/app/packages/magmalte/grafana/dashboards/Dashboards.js
Labels: apply-v1.3

#3533 [pipelined]Fix Restart Setup Instabilities
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/python/magma/pipelined/app/base.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/ue_mac.py
  lte/gateway/python/magma/pipelined/internal_ip_allocator.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
Labels: apply-v1.3

#3584 [sessiond] remove ipfix on lte
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: SessionD, component: agw

#3583 [SessionD][PipelineD] Add msisdn to pipelined activate flows
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/ServiceAction.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/protos/pipelined.proto
Labels: component: agw

#3460 [lte][agw] Adding state recovery process to health service
  lte/gateway/configs/health.yml
  lte/gateway/configs/magmad.yml
  lte/gateway/configs/service_registry.yml
  lte/gateway/python/magma/health/main.py
  lte/gateway/python/magma/health/state_recovery.py
  lte/gateway/python/scripts/state_cli.py
  lte/gateway/python/setup.py
Labels: apply-v1.3, component: agw

#3607 [lte][agw] Fixing service_restarts_map update on state recovery job
  lte/gateway/python/magma/health/state_recovery.py
Labels: apply-v1.3, component: agw

#3613 [orc8r][lte] Add support for header enrichment
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/gateway_cellular_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go
  lte/cloud/go/services/policydb/obsidian/models/conversion.go
  lte/cloud/go/services/policydb/obsidian/models/policy_rule_config_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/policy_rule_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/policydb/streamer/providers_test.go
  lte/protos/mconfig/mconfigs.proto
Labels: accept2ship, component: orc8r

#3600 [SubscriberDB] Add MSISDN from SubscriberDB to ULA sent to MME
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
Labels: component: agw

#3615 [orc8r][dev] Fix dev_setup error log when no operators
  orc8r/cloud/go/services/accessd/client_api.go
Labels: accept2ship, component: orc8r

#3633 [orc8r][mesh] Remove reliance on env vars in controller image
  fbinternal/cloud/go/plugin/plugin.go
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/go/orc8r/const.go
  orc8r/cloud/go/pluginimpl/plugin.go
  orc8r/cloud/go/service/hostname.go
  orc8r/cloud/go/services/dispatcher/dispatcher/main.go
  orc8r/cloud/go/services/metricsd/collection/gatherer.go
  orc8r/cloud/go/services/metricsd/collection/gatherer_test.go
  orc8r/cloud/go/services/metricsd/metricsd/main.go
  orc8r/cloud/helm/orc8r/templates/controller.deployment.yaml
  orc8r/lib/go/registry/global_registry.go
Labels: accept2ship, component: orc8r

#3627 [lte][agw] Fix eNB clear_stats metrics
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/stats_manager.py
Labels: apply-v1.3, component: agw

#3563 [mme] use random number to generate tmsi
  lte/gateway/c/oai/oai_mme/oai_mme.c
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
Labels: TeraVM, component: agw

#3647 [pipelined] Fix Tunnel ID Proto Field Type
  lte/cloud/go/protos/pipelined.pb.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/test_tunnel_id_mapper.py
  lte/gateway/python/magma/pipelined/tunnel_id_store.py
  lte/protos/pipelined.proto
  lte/protos/session_manager.proto
Labels: component: agw

#3657 AGW: deploy: fix install script interpreter
  docs/docusaurus/versioned_docs/version-1.3.0/lte/setup_deb.md
  lte/gateway/deploy/agw_install.sh
Labels: apply-v1.3

#3614 AGW: Envoy: plugin envoy proxy
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/he.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/bridge_util.py
  lte/gateway/python/magma/pipelined/envoy_client.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/start_pipelined.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/envoy-tests/envoy-service.sh
  lte/gateway/python/magma/pipelined/tests/envoy-tests/envoy.yaml
  lte/gateway/python/magma/pipelined/tests/envoy-tests/http-serve.py
  lte/gateway/python/magma/pipelined/tests/script/sim-ue/README.md
  lte/gateway/python/magma/pipelined/tests/script/sim-ue/bridge.sh
  lte/gateway/python/magma/pipelined/tests/script/sim-ue/sim-ue.sh
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_default_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_add.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_add2.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_del.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_del2.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_inout.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
  lte/gateway/python/magma/pipelined/tests/test_li_mirror.py
  lte/gateway/python/magma/pipelined/tests/test_service_manager.py
  lte/gateway/python/magma/pipelined/tests/test_ue_passthrough.py
Labels: component: agw

#3145 [docker][aggregated logging] Add log aggregation support for docker gateways
  cwf/gateway/docker/.env
  cwf/gateway/docker/.prod_env
  cwf/gateway/docker/docker-compose-dpi.override.yml
  cwf/gateway/docker/docker-compose.yml
  cwf/gateway/helm/cwf-kubevirt/Chart.yaml
  cwf/gateway/helm/cwf-kubevirt/templates/bin/_control_proxy.yml.tpl
  cwf/gateway/helm/cwf-kubevirt/templates/bin/_env.tpl
  cwf/gateway/helm/cwf-kubevirt/values.yaml
  cwf/gateway/helm/cwf-virtlet/Chart.yaml
  cwf/gateway/helm/cwf-virtlet/templates/bin/_control_proxy.yml.tpl
  cwf/gateway/helm/cwf-virtlet/templates/bin/_env.tpl
  cwf/gateway/helm/cwf-virtlet/values.yaml
  feg/gateway/docker/.env
  feg/gateway/docker/.prod_env
  feg/gateway/docker/docker-compose.yml
  feg/gateway/helm/feg-kubevirt/Chart.yaml
  feg/gateway/helm/feg-kubevirt/templates/bin/_control_proxy.yml.tpl
  feg/gateway/helm/feg-kubevirt/templates/bin/_env.tpl
  feg/gateway/helm/feg-kubevirt/values.yaml
  feg/gateway/helm/feg-virtlet/Chart.yaml
  feg/gateway/helm/feg-virtlet/templates/bin/_control_proxy.yml.tpl
  feg/gateway/helm/feg-virtlet/templates/bin/_env.tpl
  feg/gateway/helm/feg-virtlet/values.yaml
  orc8r/gateway/configs/templates/td-agent-bit.conf.template
Labels: apply-v1.3

#3659 [agw][MME] Add retries in sctpd_init call from MME
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
Labels: apply-v1.3, component: agw

#3646 Rsarwad pthread condition variable
  lte/gateway/c/oai/lib/openflow/controller/ControllerMain.cpp
  lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
  lte/gateway/c/oai/lib/openflow/controller/OpenflowController.h
Labels: apply-v1.3, component: agw

#3628 Update Vagrant LTE VM box with envoy/go
  lte/gateway/Vagrantfile
  lte/gateway/deploy/magma_dev.yml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/envoy/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/magma/vars/all.yaml
Labels: component: agw

#3608 [SessionD] Add operation state callback to SessionD
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/OperationalStatesHandler.cpp
  lte/gateway/c/session_manager/OperationalStatesHandler.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw

#3622 [lte][agw] Moving mobilityd ipv6 related service configs to mconfig
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/mobilityd.yml
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ip_allocator_pool.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  lte/gateway/python/magma/mobilityd/tests/rpc_servicer_tests.py
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw

#3495 Initial envoy controller code
  feg/cloud/go/protos/envoy_controller.pb.go
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/gateway/registry/local_registry.go
  feg/gateway/services/envoy_controller/control_plane/control_plane.go
  feg/gateway/services/envoy_controller/control_plane/mocks/EnvoyController.go
  feg/gateway/services/envoy_controller/main.go
  feg/gateway/services/envoy_controller/servicers/envoy_controller.go
  feg/gateway/services/envoy_controller/servicers/envoy_controller_test.go
  feg/protos/envoy_controller.proto
  feg/protos/mconfig/mconfigs.proto
  lte/gateway/configs/service_registry.yml
  lte/gateway/deploy/magma_dev.yml
  lte/gateway/deploy/magma_test.yml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/files/configure_envoy_namespace.sh
  lte/gateway/deploy/roles/magma/files/envoy.yaml
  lte/gateway/deploy/roles/magma/files/systemd/magma_envoy.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_envoy_controller.service
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, component: feg

#3634 [Stateless_MME] [Bug_Fix] Fixed Stateless test for mme restart after multi ue attach
  lte/gateway/c/oai/include/s1ap_state.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_converter.cpp
Labels: component: agw

#3686 [orc8r][helm] Bump Helm chart version
  orc8r/cloud/helm/orc8r/Chart.yaml
Labels: accept2ship, bug-fix, component: orc8r

#3712 [lte][agw] Fix IPv6 unit tests
  lte/gateway/c/oai/test/openflow/test_gtp_app.cpp
Labels: component: agw

#3680 [SessionD] Allow credits with 0 GSU to be initialized / received
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
Labels: component: agw

#3704 [CWFIntegTest] Light refactor on Gy enforcement tests
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/gateway/integ_tests/assertions.go
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_reauth_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/gy_reauth_test.go
  cwf/gateway/integ_tests/test_runner.go
Labels: component: feg

#3699 [NMS] Handle newly migrated enodeb configurations
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebConfigTest.js
Labels: apply-v1.3, component: nms

#3711 [PolicyDB] Only send SetSessionRules request if there are updates
  lte/gateway/python/magma/policydb/streamer_callback.py
Labels: component: agw

#3725 [SessionD] Consolidate CreditUpdates and SessionTerminate common context fields into CommonSessionContext
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/SessionState.cpp
  lte/protos/session_manager.proto
Labels: component: agw

#3723 [lte][agw] Add support for device properties IE
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachRequest.c
  lte/gateway/c/oai/tasks/nas/emm/msg/AttachRequest.h
Labels: apply-v1.3, component: agw

#3729 [sessiond] new suspended state
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/EnumToString.h
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/test_charging_grant.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: SessionD, component: agw

#3587 [orc8r][mesh] Hoist orc8r services into top level containers
  .circleci/config.yml
  circleci/modules.yml
  docs/readmes/basics/quick_start_guide.md
  modules.yml
  orc8r/cloud/docker/Dockerfile
  orc8r/cloud/docker/build.py
  orc8r/cloud/docker/compose-all.env
  orc8r/cloud/docker/controller/create_test_controller_certs
  orc8r/cloud/docker/docker-compose.cwf.yml
  orc8r/cloud/docker/docker-compose.fbinternal.yml
  orc8r/cloud/docker/docker-compose.feg.yml
  orc8r/cloud/docker/docker-compose.lte.yml
  orc8r/cloud/docker/docker-compose.override.yml
  orc8r/cloud/docker/docker-compose.wifi.yml
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/docker/run.py
  orc8r/cloud/docker/run.sh
Labels: component: orc8r

#3366 UPF-SMF response handling, active state change handling, SMF-AMF state change notification
  lte/cloud/go/protos/pipelined.pb.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/oai/tasks/grpc_service/AmfServiceImpl.h
  lte/gateway/c/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/oai/tasks/grpc_service/grpc_service.cpp
  lte/gateway/c/session_manager/AmfServiceClient.cpp
  lte/gateway/c/session_manager/AmfServiceClient.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/configs/service_registry.yml
  lte/protos/pipelined.proto
  lte/protos/session_manager.proto
Labels: 5G: MVC, SessionD, component: agw

#3670 [FIX][AGW]Fix post install sctpd
  lte/gateway/deploy/agw_post_install.sh
Labels: component: agw

#3648 [pipelined]Remove CWF GY Redirect IP Requirement
  lte/gateway/python/magma/pipelined/app/gy.py
Labels: component: agw

#3645 [SessionD] No longer lookup IP address from DirectoryD for CWF
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/gateway/integ_tests/gy_enforcement_test.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
Labels: component: agw

#3719 [Enhancement] [Sanity_Testing] Added subset of pending test cases to sanity
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw

#2403 [agw] [S1ap test] Add test case for sctpd restart
  lte/gateway/deploy/roles/magma_test/files/update_package.sh
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_sctpd_restart.py
Labels: component: agw

#3745 [SessionD] Store usage updates for failed UpdateSession call and rollback credit changes
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: bug-fix, component: agw

#3710 [backport 1.3] AGW: Fix deactivate_flow_for_rule args
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
Labels: apply-v1.3

#3786 [orc8r] Fix nil pointer during Enodeb object validation
  lte/cloud/go/services/lte/obsidian/models/validate.go
Labels: apply-v1.3, component: orc8r

#3752 [lte][agw] Adding DNS configs for IPv6
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/validate.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw

#3813 Revert change of magma_dev vagrant box version made in "[lte] Add tshark to vm image (#3766)"
  lte/gateway/Vagrantfile
Labels: component: agw

#3818 [lte][agw] Fix T3489 handling
  lte/gateway/c/oai/tasks/nas/esm/esm_information.c
  lte/gateway/python/integ_tests/s1aptests/test_attach_esm_information_timerexpiration.py
Labels: apply-v1.3, component: agw

#3751 Modified code to get number active PDNs and removed unwanted parameters
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/oai/tasks/nas/esm/PdnDisconnect.c
  lte/gateway/c/oai/tasks/nas/esm/esmData.h
  lte/gateway/c/oai/tasks/nas/esm/esm_data.h
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/protos/oai/nas_state.proto
Labels: component: agw

#3043 [CI][Jenkins] Pipeline Improvements
  ci-scripts/JenkinsFile-GitLab
Labels: component: agw

#3605 Added code to handle 3422 timer while mme restarts
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/gateway/c/oai/lib/hashtable/hashtable.c
  lte/gateway/c/oai/lib/hashtable/hashtable.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/nas_state_converter.h
  lte/protos/oai/nas_state.proto
Labels: apply-v1.3, component: agw
