Repository magma/magma, pull requests merged in 2020-12, with the labels that each got.

#3855 Bump agw to 1.3.2
  lte/gateway/release/build-magma.sh
Labels: apply-v1.3

#3761 [SessionD] Only send update events for actually updated sessions
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/EnumToString.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionEvents.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: component: agw

#3805 PDU Session Release support code
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
Labels: 5G: MVC, component: agw, type: enhancement

#3769 [orc8r][testcontroller] Updating enodebd_test with updated enb_config field
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers_test.go
  fbinternal/cloud/go/services/testcontroller/obsidian/models/enodebd_test_config_swaggergen.go
  fbinternal/cloud/go/services/testcontroller/obsidian/models/swagger.v1.yml
  fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
Labels: component: orc8r

#3828 [orc8r][docs] Add readme for how to interact with Magma docs
  docs/README.md
Labels: accept2ship, component: orc8r

#3619 [docker][mme] Adding missing clang-format to dockerfile
  lte/gateway/c/sctpd/CMakeLists.txt
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw

#3878 [lte][agw] Add condition for context not found in delete session response
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: apply-v1.3, component: agw

#3872 [SessionD] Allow validity timer to trigger a CCR-U even in final unit action ena…
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/test/test_charging_grant.cpp
Labels: component: agw

#3897 [orc8r][subscriberdb] Add subscriber_state endpoint
  lte/cloud/go/lte/const.go
  lte/cloud/go/serdes/serdes.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go
  lte/cloud/go/services/subscriberdb/obsidian/models/subscriber_state_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/subscriberdb/obsidian/models/untyped_subscriber_state_swaggergen.go
Labels: accept2ship, component: orc8r

#3889 [SessionD] Always process rule uninstall over install
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: component: agw

#3901 [feg] bump grpc module to 1.4.3
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/testcore/hss/client_api_test.go
Labels: component: agw, component: feg

#3682 [agw][stateless MME] Stateless test cases for Idle mode
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_idle_mode_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_service_req_ul_udp_data_with_mme_restart.py
Labels: component: agw

#3816 [agw][lte] Ipv6 dedicated bearer support
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/oai/lib/pcef/PCEFClient.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_secondary_pdn_spgw_initiated_ded_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_secondary_pdn_with_ded_bearer.py
Labels: component: agw

#3914 [lte][agw] Temporarily enable ASAN in release builds as well
  lte/gateway/c/oai/CMakeLists.txt
Labels: component: agw

#3925 [agw][lte][bug fix] Bug fix for test_attach_detach_ICS_Failure.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_ICS_Failure.py
Labels: component: agw

#3928 [AGW] Ensures mobilityd starts after OVS to be sure dhcp0 iface created
  lte/gateway/deploy/roles/magma/files/systemd/magma_mobilityd.service
Labels: apply-v1.3

#3929 [orc8r][subscriberdb] Fix rest api access to subscriber_state
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  lte/cloud/helm/lte-orc8r/values.yaml
Labels: accept2ship, bug-fix, component: orc8r

#3876 [feg] initial commit for s8_proxy
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/gtp/enriched_message/message.go
  feg/gateway/gtp/gtp_client.go
  feg/gateway/gtp/gtp_client_test.go
  feg/gateway/gtp/gw.go
  feg/gateway/registry/local_registry.go
  feg/gateway/services/s8_proxy/client_api.go
  feg/gateway/services/s8_proxy/s8_proxy/main.go
  feg/gateway/services/s8_proxy/servicers/config.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/ds.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversion.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/protos/s8_proxy.proto
Labels: component: agw, component: feg

#2707 Rel15_s1ap
  lte/gateway/Vagrantfile
  lte/gateway/c/oai/common/itti_free_defined_msg.c
  lte/gateway/c/oai/include/TrackingAreaIdentity.h
  lte/gateway/c/oai/include/mme_app_messages_types.h
  lte/gateway/c/oai/lib/3gpp/3gpp_36.413.h
  lte/gateway/c/oai/lib/gtpv2-c/nwgtpv2c-0.11/src/NwGtpv2c.c
  lte/gateway/c/oai/lib/itti/CMakeLists.txt
  lte/gateway/c/oai/lib/message_utils/ie_to_bytes.c
  lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/oai/tasks/gtpv1-u/CMakeLists.txt
  lte/gateway/c/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.h
  lte/gateway/c/oai/tasks/nas/emm/Authentication.c
  lte/gateway/c/oai/tasks/nas/emm/emm_data_ctx.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/oai/tasks/nas/ies/TrackingAreaIdentity.c
  lte/gateway/c/oai/tasks/nas/ies/TrackingAreaIdentityList.c
  lte/gateway/c/oai/tasks/nas/ies/TrackingAreaIdentityList.h
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/oai/tasks/s11/s11_ie_formatter.c
  lte/gateway/c/oai/tasks/s1ap/CMakeLists.txt
  lte/gateway/c/oai/tasks/s1ap/messages/asn1/r15/s1ap-15.6.0.asn1
  lte/gateway/c/oai/tasks/s1ap/s1ap_common.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_common.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_decoder.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_decoder.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_encoder.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_encoder.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_ta.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_ta.h
  lte/gateway/c/oai/tasks/s6a/CMakeLists.txt
  lte/gateway/c/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/oai/tasks/sctp/CMakeLists.txt
  lte/gateway/c/oai/tasks/sgw/CMakeLists.txt
  lte/gateway/c/oai/tasks/sgw/pgw_procedures.c
  lte/gateway/c/oai/tasks/udp/CMakeLists.txt
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/release/build-magma.sh
Labels: component: agw

#3875 [SessionD] Use IMSI+SessionID to schedule rule installs/removals
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/Utilities.cpp
  lte/gateway/c/session_manager/Utilities.h
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
Labels: component: agw

#3717 [AGW] [Logging] Added return value checks for better logging for stateless MME
  lte/gateway/c/oai/common/common_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_manager.cpp
Labels: component: agw

#3965 AGW: mobilityD: dhcp: use DHCP ip address in case missing opt 3
  lte/gateway/python/magma/mobilityd/dhcp_client.py
Labels: apply-v1.3

#3975 [lte][agw] Fix SPGW state converter parsing for bstring to string data
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/python/magma/mobilityd/ip_address_man.py
Labels: component: agw

#3982 [orc8r] Reenable docusaurus publish
  .circleci/config.yml
Labels: accept2ship, component: docs

#3981 [orc8r] Fix run.py basic bug
  orc8r/cloud/docker/run.py
Labels: accept2ship, bug-fix, component: orc8r

#4005 [CWFIntegTest] Simplify CWF Integration Test to reduce flake
  cwf/gateway/docker/docker-compose.override.yml
  cwf/gateway/fabfile.py
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/gateway/integ_tests/gateway.mconfig
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_reauth_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/omni_rules_test.go
  cwf/gateway/integ_tests/rule_manager.go
  cwf/gateway/integ_tests/test_runner.go
Labels: component: agw, component: feg

#4023 [CWF IntegTest] Use stateless PipelineD in CWF IntegTest
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/pipelined.yml
  cwf/gateway/integ_tests/test_runner.go
Labels: CWF-Integ-Test

#3968 Rsarwad handle 3485 timer
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/gateway/c/oai/include/spgw_state.h
  lte/gateway/c/oai/include/spgw_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/esm_data.h
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.h
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/nas_state_converter.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.h
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.h
  lte/gateway/c/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_manager.h
  lte/protos/oai/nas_state.proto
  lte/protos/oai/spgw_state.proto
Labels: component: agw

#4033 [SessionD] Migrate tests/leftover to use bundled fields
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/RestartHandler.cpp
  lte/gateway/c/session_manager/SessionReporter.cpp
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: component: agw

#4017 Rsarwad handle 3495 timer
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.h
Labels: component: agw

#4060 [docs] Fix gh-pages docs
  .circleci/config.yml
  docs/docusaurus/siteConfig.js
Labels: accept2ship, component: docs

#4036 [CWF Integration Tests] Improve flakiness on CWF Integration Tests
  cwf/gateway/integ_tests/assertions.go
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_enforcement_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/gy_reauth_test.go
  cwf/gateway/integ_tests/rule_manager.go
Labels: component: agw

#3838 [show-tech] Core dumps analysis role
  show-tech/constants.yml
  show-tech/roles/cores/files/handle_cores.py
  show-tech/roles/cores/tasks/main.yml
  show-tech/show-tech.yml
Labels: DevOps/PE

#3991 [lte][agw] Stateless mme test case for mixed UE state
  lte/gateway/python/integ_tests/s1aptests/test_stateless_multi_ue_mixedstate_mme_restart.py
Labels: component: agw

#4067 [lte][agw] Fix segfault due to missing security context
  lte/gateway/c/oai/tasks/nas/api/network/nas_message.c
Labels: apply-v1.3, component: agw

#4071 [lte][agw] Adding retry backoff to sctpd connection establishment
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
Labels: apply-v1.3, component: agw

#4081 [orc8r][ci] Publish orc8r_base image for top-level controller services
  .circleci/config.yml
Labels: accept2ship, component: ci, component: orc8r

#4076 [orc8r][docs] Fix minor indexer doc issues
  orc8r/cloud/go/services/state/indexer/doc.go
Labels: accept2ship, component: orc8r

#4078 [ci] Clean up CircleCI config schema validation
  .circleci/config.yml
Labels: accept2ship, component: ci

#4087 [CI] Ignore out-of-order warning in traffic tests
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
Labels: component: agw

#4069 [lte][agw][bug fix]Bug fix found during testing stateless TCs in unregistered mode
  lte/gateway/c/oai/common/state_converter.cpp
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
Labels: component: agw

#4085 [agw][mobilityd] Clean all the mobilityd Redis keys when sctpd restarts
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: component: agw

#4098 [lte][agw] Fix for stateless pco crash
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: apply-v1.3, component: agw

#3590 Adding testcase to validate the behavior of ICS timer with mme restart
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_ics_timer_expiry_with_mme_restart.py
Labels: component: agw

#3995 [NMS] Add grafana and metrics explorer to Feg Network.
  nms/app/packages/magmalte/app/components/feg/FEGMetrics.js
  nms/app/packages/magmalte/app/components/feg/FEGSections.js
  nms/app/packages/magmalte/app/components/layout/__tests__/useSections-test.js
  nms/app/packages/magmalte/app/views/metrics/Explorer.js
  nms/app/packages/magmalte/server/apicontroller/routes.js
Labels: component: nms

#4104 [CI][AGW][S1ap-tester] Remove flaky test and timer tests in sanity test suite
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw

#4105 [cwag_integ_test] Increased traffic to avoid spurious results
  cwf/gateway/integ_tests/multi_sessioneproxy_test.go
Labels: CWF-Integ-Test, component: agw, component: feg

#4034 [CI][cwag]Fix cwag vagrant deploy on libvirt
  cwf/gateway/Vagrantfile
  cwf/gateway/fabfile.py
Labels: CWF-Integ-Test, component: agw, component: cwf

#4119 [AGW][pipelined] Kill dhclient for eth0 in non-NAT configuration
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: apply-v1.3

#4126 [orc8r] Revert to controller-only local orc8r
  orc8r/cloud/docker/build.py
  orc8r/cloud/docker/docker-compose.cwf.yml
  orc8r/cloud/docker/docker-compose.fbinternal.yml
  orc8r/cloud/docker/docker-compose.feg.yml
  orc8r/cloud/docker/docker-compose.lte.yml
  orc8r/cloud/docker/docker-compose.override.yml
  orc8r/cloud/docker/docker-compose.wifi.yml
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/docker/run.py
Labels: accept2ship, component: orc8r

#4106 As part of mme restart, added code to handle timers when UE is not registered to network
  lte/gateway/c/oai/include/s1ap_messages_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/nas_state_converter.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: component: agw

#4132 [sessind] Delay rule removal when suspended credit is received at init
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: SessionD, component: agw

#4144 Set proper hostname for vagrant box vms in libvirt
  orc8r/tools/packer/magma-dev-libvirt.json
  orc8r/tools/packer/magma-test-libvirt.json
  orc8r/tools/packer/magma-trfserver-libvirt.json
Labels: component: agw, component: cwag

#4136 [orc8r][lib] Fix initflag to not bork unit test output
  orc8r/lib/go/initflag/initflag.go
Labels: component: agw, component: cwag, component: orc8r

#3604 Added testcase to validate 3422 timer while mme restarts
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_nw_initiated_detach_with_mme_restart.py
Labels: component: agw

#3969 [show-tech] installing ansible community and updating README.md
  docs/readmes/debugging_tools/show-tech/developer_guide.md
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/ovs_deploy/tasks/main.yml
  show-tech/constants.yml
  show-tech/roles/install_ansible_modules/tasks/main.yml
Labels: DevOps/PE

#4153 Provided fix not to log multiple times invalid imsi and not able to fetch UE context for an invalid imsi
  lte/gateway/c/oai/lib/itti/intertask_interface.c
Labels: component: agw, component: cwag

#4154 [xwfm][ci] fix dockercomopse to use logrouter
  .circleci/config.yml
  xwf/docker/docker-compose.yml
Labels: component: agw

#3780 [lte][agw] MME HA task and grpc service addition
  lte/cloud/go/protos/ha_service.pb.go
  lte/gateway/c/oai/include/ha_messages_def.h
  lte/gateway/c/oai/include/ha_messages_types.h
  lte/gateway/c/oai/include/messages_def.h
  lte/gateway/c/oai/include/messages_types.h
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/include/s1ap_messages_types.h
  lte/gateway/c/oai/include/tasks_def.h
  lte/gateway/c/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/oai/oai_mme/oai_mme.c
  lte/gateway/c/oai/tasks/CMakeLists.txt
  lte/gateway/c/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/oai/tasks/grpc_service/HaServiceImpl.cpp
  lte/gateway/c/oai/tasks/grpc_service/HaServiceImpl.h
  lte/gateway/c/oai/tasks/grpc_service/grpc_service.cpp
  lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/oai/tasks/ha/CMakeLists.txt
  lte/gateway/c/oai/tasks/ha/HaClient.cpp
  lte/gateway/c/oai/tasks/ha/HaClient.h
  lte/gateway/c/oai/tasks/ha/ha_defs.h
  lte/gateway/c/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/oai/tasks/ha/ha_task.c
  lte/gateway/c/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_ha.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_ha.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/configs/mme.yml
  lte/gateway/configs/service_registry.yml
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_idle_active_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_mixed_idle_active_multiue.py
  lte/gateway/python/scripts/ha_cli.py
  lte/gateway/python/setup.py
  lte/protos/ha_service.proto
Labels: component: agw, component: cwag

#4152 [dispatcher][k8s] Expose http server port on dispatcher pod
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/templates/dispatcher.deployment.yaml
Labels: component: agw

#4156 [orc8r][cloud][lib][docker] Fix intra cloud magic cert SN set logic
  orc8r/cloud/go/service/middleware/unary/identity_decorator.go
  orc8r/lib/go/registry/registry.go
  orc8r/lib/go/service/middleware/unary/client_identity.go
Labels: component: orc8r

#2873 [Docs] APN correction proposal
  docs/readmes/proposals/p008_apn_correction.md
Labels: component: agw, component: cwag

#4157 [Orc8r] Fix the helm repo locations
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/artifactory.tf
Labels: component: agw, component: orc8r

#4161 [lte][agw] Fix for gtp app error while deleting dedicated bearer
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: component: agw

#4131 [lte][agw] Auto rewrite eNB gtp-u private IP address with the eNB sctp public peer IP address
  lte/cloud/go/protos/oai/s1ap_state.pb.go
  lte/cloud/go/protos/sctpd.pb.go
  lte/gateway/c/oai/common/itti_free_defined_msg.c
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/include/s1ap_types.h
  lte/gateway/c/oai/include/sctp_messages_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/oai/tasks/sctp/sctp_itti_messaging.c
  lte/gateway/c/oai/tasks/sctp/sctp_itti_messaging.h
  lte/gateway/c/oai/tasks/sctp/sctpd_uplink_server.cpp
  lte/gateway/c/sctpd/sctp_connection.cpp
  lte/gateway/c/sctpd/sctp_connection.h
  lte/gateway/c/sctpd/sctpd_event_handler.cpp
  lte/gateway/c/sctpd/sctpd_event_handler.h
  lte/gateway/c/sctpd/util.cpp
  lte/gateway/c/sctpd/util.h
  lte/gateway/configs/mme.yml
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/protos/oai/s1ap_state.proto
  lte/protos/sctpd.proto
Labels: component: agw, component: cwag

#4140 Added code to handle timer for unregistered UE and imsi is not known
  lte/gateway/c/oai/include/s1ap_messages_def.h
  lte/gateway/c/oai/include/s1ap_messages_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: component: agw, component: cwag

#4121 [AGW][pipelined] Fix non-NAT iface reconfiguration
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: apply-v1.3, component: agw, component: cwag

#4164 [FeG][Orc8r] Add charging characteristics filter for Virtual APN
  fbinternal/cloud/go/go.sum
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  feg/cloud/go/services/feg/obsidian/models/virtual_apn_rule_swaggergen.go
  feg/cloud/go/services/feg/servicers/builder_servicer_test.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/nh_router.go
  feg/gateway/go.sum
  feg/gateway/services/session_proxy/credit_control/definitions.go
  feg/gateway/services/session_proxy/credit_control/gx/definitions.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client_test.go
  feg/gateway/services/session_proxy/credit_control/gx/model_conversion.go
  feg/gateway/services/session_proxy/credit_control/gy/definitions.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client_test.go
  feg/gateway/services/session_proxy/credit_control/gy/model_conversion.go
  feg/gateway/services/session_proxy/credit_control/virtual_apn_rules.go
  feg/gateway/services/session_proxy/servicers/credits.go
  feg/gateway/services/session_proxy/servicers/policy.go
  feg/gateway/services/testcore/ocs/mock_ocs/mock_driven_ocs_test.go
  feg/protos/mconfig/mconfigs.proto
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/SessionState.cpp
  lte/protos/session_manager.proto
  orc8r/cloud/go/services/metricsd/prometheus/handlers/promo_handlers_test.go
Labels: component: agw, component: cwag, component: feg

#4168 [agw][lte] Reflect cloud streamed config for relative capacity in mme template
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, component: cwag

#4167 [lte][agw] Print IMEI information in mme log
  lte/gateway/c/oai/common/conversions.h
  lte/gateway/c/oai/tasks/nas/emm/msg/emm_msg.c
Labels: component: agw, component: cwag

#4176 [agw] [Sctpd] [bug-fix v1.3] Re-add PartOf dependency between MME and sctpd
  lte/gateway/deploy/roles/magma/files/systemd/sctpd.service
  lte/gateway/python/integ_tests/defs.mk
Labels: breaking change, component: agw, component: cwag

#4179 [agw][sctpd] [bug fix v1.3] Restart Sctpd with MME
  lte/gateway/deploy/roles/magma/files/systemd/sctpd.service
  lte/gateway/python/integ_tests/defs.mk
Labels: breaking change, component: agw, component: cwag

#4150 Reduce cwf build by changing build determinator
  .circleci/config.yml
Labels: component: agw, component: cwag

#4180 [magma][circleci] cwag_deploy and xwfm_deploy will run after code changes only
  .circleci/config.yml
Labels: component: agw

#4096 [lte][agw] Changing py code to support 3.8 as well
  lte/gateway/python/Makefile
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/store/base.py
  lte/gateway/python/magma/subscriberdb/store/cached_store.py
  lte/gateway/python/magma/subscriberdb/store/sqlite.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/base_application_tests.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/common.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/s6a_application_tests.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/s6a_relay_tests.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/server_tests.py
  lte/gateway/python/magma/subscriberdb/tests/store/onready_test.py
  lte/gateway/python/patches/aioeventlet.py38.patch
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile
  orc8r/gateway/python/python.mk
  orc8r/gateway/python/setup.py
Labels: component: agw, component: cwag

#4177 [docker] optimization in git clone using --depth
  cwf/gateway/docker/python/Dockerfile
  lte/gateway/docker/deploy/Dockerfile
Labels: component: agw, component: cwag

#4148 Update vagrant box images with proper hostname in libvirt
  lte/gateway/Vagrantfile
Labels: component: agw

#3998 [MME] fix incorrect formatting of time/timezone in EMM-info packet
  lte/gateway/c/oai/include/state_converter.h
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_send.c
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: bug-fix, component: agw

#4165 [NMS] Fixing the health value for unmanaged eNodeBs
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebDetailMainTest.js
Labels: component: agw, component: cwag

#4186 [pipelined]Fix NIL Delete in QOS Restart Recovery
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, component: cwag

#3778 [agw][stateless][magmad] Add RPC call for stateless configuration in Magmad
  lte/gateway/configs/magmad.yml
  lte/gateway/python/scripts/config_stateless_agw.py
  orc8r/gateway/go/services/magmad/service/magmad.go
  orc8r/gateway/go/services/sync_rpc/service/sync_rpc_broker_test.go
  orc8r/gateway/python/magma/common/stateless_agw.py
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
  orc8r/gateway/python/scripts/magmad_cli.py
  orc8r/lib/go/protos/magmad.pb.go
  orc8r/protos/magmad.proto
Labels: component: agw, component: cwag

#4172 Fix Pipelined Flaky Restart Recovery
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/openflow/messages.py
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/test_inout.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
  lte/gateway/python/magma/pipelined/tests/test_li_mirror.py
  lte/gateway/python/magma/pipelined/tests/test_ue_passthrough.py
Labels: component: agw, component: cwag

#4193 [pipelined]Remove extra unit test verification
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
Labels: component: agw, component: cwag

#4196 [lte][ansible-galaxy] ignore errors on dev env
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, component: cwag

#4198 [UESIM] Prevent nil dereference in UE sim proto conversion
  cwf/gateway/integ_tests/multi_sessioneproxy_test.go
  cwf/gateway/services/uesim/servicers/uesim.go
Labels: component: agw, component: cwag

#4191 [orc8r][nginx] Fix feg relay routing due to incorrectly formatted gRPC host header
  orc8r/cloud/docker/nginx/templates/nginx.conf.j2
Labels: component: agw, component: cwag

#4175 [sessind] add teid to pipelined api
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/ServiceAction.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/test/Consts.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/c/session_manager/test/test_store_client.cpp
  lte/gateway/c/session_manager/test/test_stored_state.cpp
  lte/protos/session_manager.proto
Labels: CWF-Integ-Test, component: agw, component: cwag, component: cwf

#4159 [Doc] Add APN correction doc
  docs/docusaurus/sidebars.json
  docs/readmes/lte/config_apn.md
Labels: component: agw

#4187 [v1.3][CI] Bump the package version for AGW to 1.3.3 and corresponding Sctpd req…
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag

#4197 [CWF IntegTest] Attempt to stabilize flakiest tests
  cwf/gateway/integ_tests/assertions.go
  cwf/gateway/integ_tests/auth_test.go
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_restart_test.go
  cwf/gateway/integ_tests/gx_reauth_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/gy_reauth_test.go
  cwf/gateway/integ_tests/idle_timer_test.go
  cwf/gateway/integ_tests/omni_rules_test.go
  feg/gateway/services/testcore/mock_driver/mock_driver.go
Labels: CWF-Integ-Test, component: agw, component: cwag

#4200 [pipelined]Fix XWF inout controller init
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw, component: cwag

#4202 AGW: gracefully handle missing uplink port
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: component: agw, component: cwag

#4053 [Magma] [FAQ] Updating magma Git FAQ
  docs/readmes/faq/magma_faq.md
Labels: component: agw, component: cwag

#4204 [pipelined]Fix InOut Controller Restart Failure
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw, component: cwag

#4206 [pipelined]Fix Pipelined Unit test failure
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
Labels: component: agw, component: cwag

#4201 [teravm] Overwrite config files during apt install
  ci-scripts/teravm/fabfile.py
Labels: component: agw, component: cwag

#4208 Fix/Refactor pipelined stateless restart
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/openflow/messages.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout.InOutTestXWF.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/test_inout.py
  lte/protos/pipelined.proto
Labels: component: agw, component: cwag

#4216 [agw][mme] Make ctime call thread safe
  lte/gateway/c/oai/common/log.c
Labels: apply-v1.3, component: agw, component: cwag

#4160 [NMS] Upgrade NMS packages
  nms/app/flow-typed/npm/copy-to-clipboard_vx.x.x.js
  nms/app/package.json
  nms/app/packages/magmalte/app/components/ClipboardLink.js
  nms/app/packages/magmalte/app/components/admin/Admin.js
  nms/app/packages/magmalte/app/components/admin/Networks.js
  nms/app/packages/magmalte/app/components/master/Index.js
  nms/app/packages/magmalte/app/components/wifi/WifiMeshRow.js
  nms/app/packages/magmalte/app/e2e/NetworkUtils.js
  nms/app/packages/magmalte/app/e2e/__tests__/Apn-test.js
  nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberOverview.js
  nms/app/packages/magmalte/package.json
  nms/app/yarn.lock
Labels: component: agw, component: cwag
