Repository magma/magma, pull requests merged in 2021-05, with the labels that each got.

#6602 [orc8r][obsidian] Fix nondeterministic tests
  orc8r/cloud/go/obsidian/reverse_proxy/reverse_proxy_test.go
Labels: size/S

#6606 [MME] Unmask SIGSEGV so it is dealt by the default handler
  lte/gateway/c/oai/lib/itti/signals.c
  lte/gateway/c/oai/test/itti/test_itti.cpp
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/XS

#6609 Fix pipelined cli script bad import
  lte/gateway/python/scripts/pipelined_cli.py
Labels: component: agw, component: cwag, size/XS

#6458 Add retry logic to cwag build/deploy
  .circleci/config.yml
Labels: size/S

#6557 Include OVS RYU Patch into Build Script
  lte/gateway/deploy/roles/magma/files/nx_actions_3.5.py
  lte/gateway/release/build-magma.sh
Labels: apply-v1.5, component: agw

#6638 Add TEID to PolicyBearer binding response
  lte/cloud/go/protos/session_manager.pb.go
  lte/protos/session_manager.proto
Labels: component: agw

#6547 [CODEOWNERS] Point CWF ownership to magma/approvers-cwf
  CODEOWNERS
Labels: size/XS

#6546 [CODEOWNERS] Point NMS ownership to magma/approvers-nms
  CODEOWNERS
Labels: size/XS

#4158 Intitial LI Agent code
  .circleci/config.yml
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/Makefile
  lte/gateway/c/li_agent/CMakeLists.txt
  lte/gateway/c/li_agent/DirectorydClient.cpp
  lte/gateway/c/li_agent/DirectorydClient.h
  lte/gateway/c/li_agent/InterfaceMonitor.cpp
  lte/gateway/c/li_agent/InterfaceMonitor.h
  lte/gateway/c/li_agent/PDUGenerator.cpp
  lte/gateway/c/li_agent/PDUGenerator.h
  lte/gateway/c/li_agent/ProxyConnector.cpp
  lte/gateway/c/li_agent/ProxyConnector.h
  lte/gateway/c/li_agent/main.cpp
  lte/gateway/c/li_agent/test/CMakeLists.txt
  lte/gateway/c/li_agent/test/Consts.h
  lte/gateway/c/li_agent/test/LIAgentdMocks.h
  lte/gateway/c/li_agent/test/test_pdu_generator.cpp
  lte/gateway/configs/liagentd.yml
  lte/gateway/configs/service_registry.yml
  lte/gateway/deploy/agw_ovs_user_space.sh
  lte/gateway/deploy/roles/magma/files/magma_ifaces_gtp
  lte/gateway/deploy/roles/magma/files/systemd/magma_liagentd.service
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/ovs_deploy/tasks/main.yml
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, component: cwag, size/XXL

#6689 [feg] Replaced golang.org/x/net/context with context
  feg/gateway/registry/registry_test.go
  feg/gateway/services/aaa/aaa_server/aaa_aka_auth_test.go
  feg/gateway/services/aaa/client/client_api.go
  feg/gateway/services/aaa/servicers/accounting.go
  feg/gateway/services/aaa/servicers/authenticator.go
  feg/gateway/services/aaa/servicers/responders.go
  feg/gateway/services/aaa/session_manager/client_api.go
  feg/gateway/services/aaa/test/mock_pipelined/services.go
  feg/gateway/services/aaa/test/mock_sessiond/services.go
  feg/gateway/services/aaa/test/pipelined/main.go
  feg/gateway/services/csfb/servicers/csfb.go
  feg/gateway/services/csfb/servicers/test/csfb_sctp_integration_test.go
  feg/gateway/services/csfb/servicers/test/csfb_test.go
  feg/gateway/services/eap/eap_router/eap_router_test.go
  feg/gateway/services/eap/eap_router/main.go
  feg/gateway/services/eap/eap_router/sample_eap_client/grpc_client.go
  feg/gateway/services/eap/providers/aka/provider/client_api.go
  feg/gateway/services/eap/providers/aka/servicers/handlers/aka_identity_test.go
  feg/gateway/services/eap/providers/aka/servicers/rpc.go
  feg/gateway/services/eap/providers/sim/provider/client_api.go
  feg/gateway/services/eap/providers/sim/servicers/handlers/sim_start_test.go
  feg/gateway/services/eap/providers/sim/servicers/rpc.go
  feg/gateway/services/eap/test/services.go
  feg/gateway/services/envoy_controller/servicers/envoy_controller.go
  feg/gateway/services/envoy_controller/servicers/envoy_controller_test.go
  feg/gateway/services/feg_hello/servicers/hello.go
  feg/gateway/services/gateway_health/health_manager/health_manager_test.go
  feg/gateway/services/hlr_proxy/client_api.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy_test.go
  feg/gateway/services/session_proxy/credit_control/asr.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client_test.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client_test.go
  feg/gateway/services/session_proxy/credit_control/gy/handlers.go
  feg/gateway/services/session_proxy/servicers/multiple_session_controller.go
  feg/gateway/services/session_proxy/servicers/session_controller.go
  feg/gateway/services/session_proxy/servicers/session_controller_test.go
  feg/gateway/services/swx_proxy/client_api.go
  feg/gateway/services/swx_proxy/servicers/multiple_swx_proxy.go
  feg/gateway/services/swx_proxy/servicers/rt.go
  feg/gateway/services/swx_proxy/servicers/swx_proxy.go
  feg/gateway/services/testcore/hss/client_api.go
  feg/gateway/services/testcore/hss/servicers/hss.go
  feg/gateway/services/testcore/ocs/mock_ocs/ocs.go
Labels: component: feg, size/L

#6688 [feg] s8_proxy refactor echo request/response
  feg/gateway/gtp/gtp_client.go
  feg/gateway/gtp/gtp_client_test.go
  feg/gateway/gtp/gw.go
  feg/gateway/gtp/handlers.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
Labels: size/L

#6690 <feat:>[SessionD]: Store teids from PolicyBearerBindingRequest
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_stored_state.cpp
Labels: component: agw, size/M

#6660 [CODEOWNERS] Update all non-CI related directories to point to teams
  CODEOWNERS
Labels: size/S

#6701 Rename *-approvers to approvers-* for feg and orc8r
  CODEOWNERS
Labels: size/XS

#6548 Update AGW hardware requirements
  docs/readmes/basics/prerequisites.md
Labels: size/S

#6698 devex: Add PR HelloBot
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto-comment.yml
  docs/readmes/contributing/contribute_workflow.md
Labels: size/S

#6477 [AGW][OAI][MME] Tech Debt 2021-April: reduce compilation warnings for MME compilation
  lte/gateway/c/connection_tracker/main.cpp
  lte/gateway/c/li_agent/main.cpp
  lte/gateway/c/oai/common/glogwrapper/glog_logging.cpp
  lte/gateway/c/oai/include/state_converter.h
  lte/gateway/c/oai/lib/itti/intertask_interface.c
  lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.cpp
  lte/gateway/c/oai/lib/sms_orc8r_client/itti_msg_to_proto_msg.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas5g/include/M5GCommonDefs.h
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GAuthenticationResponseParameter.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GEAPMessage.cpp
  lte/gateway/c/oai/tasks/ngap/ngap_state_manager.cpp
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.h
  lte/gateway/c/sctpd/sctpd.cpp
  lte/gateway/c/session_manager/SessionCredit.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
  orc8r/gateway/c/common/config/ServiceConfigLoader.cpp
  orc8r/gateway/c/common/datastore/RedisMap.hpp
  orc8r/gateway/c/common/logging/magma_logging.h
  orc8r/gateway/c/common/logging/magma_logging_init.h
  orc8r/gateway/c/common/service303/MagmaService.cpp
Labels: component: agw, size/L, tech-debt

#6418 [LTE][timers] Migrate service303 timer to ZMQ loop
  lte/gateway/c/oai/include/service303.h
  lte/gateway/c/oai/tasks/service303/service303_task.c
Labels: component: agw, size/M

#6696 docs: docusaurus: Fix sidebar links
  docs/docusaurus/sidebars.json
Labels: apply-v1.5, size/XS

#6611 AGW: deploy: post install script cleanups
  lte/gateway/deploy/agw_install_ubuntu.sh
  lte/gateway/deploy/agw_ovs_user_space.sh
  lte/gateway/deploy/agw_post_install_ubuntu.sh
  lte/gateway/deploy/agw_pre_check_ubuntu.sh
Labels: component: agw

#6680 [docs] Adding AGW 1.5 upgrade docs
  docs/docusaurus/sidebars.json
  docs/docusaurus/versioned_docs/version-1.5.0/lte/upgrade_1_5.md
  docs/docusaurus/versioned_sidebars/version-1.5.0-sidebars.json
  docs/readmes/lte/upgrade_1_5.md
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, size/M

#6256 [proposal] Add proposal for NMS E2E/Regression Testing
  docs/readmes/proposals/p016_nms_regression_testing.md
Labels: size/L

#6725 <:fix>[CWFIntegrationTest] Fix nil dereference in ASR tests
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
Labels: component: agw, component: cwag, size/S

#6310 [AGW][MME][OAI][CI] Performs a complete image build during master morning checks
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/generateHtmlReport-OAI-pipeline.py
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw, size/L

#6744 <:refactor> Refactor RuleToProcess to clean up the PipelineD interface
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
Labels: component: agw, size/L

#6749 Fixed broken link for Bare Metal Ansible README.md
  orc8r/cloud/deploy/bare-metal-ansible/README.md
Labels: size/XS

#6479 [MME][OAI][DOCKER] a bit of cleanup in MME docker files [Tech-Debt 2021 April]
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw, size/M, tech-debt

#6697 [lte][agw] Support nonconsecutive PLMNS
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_send.c
Labels: apply-v1.3, apply-v1.4, apply-v1.5, component: agw, size/L

#6768 devex: Try fix PR HelloBot
  .github/auto-comment.yml
  .github/workflows/pr_bot.yml
Labels: size/M

#6746 AGW: pipelined: fix pylinter issue related asyncio sleep.
  lte/gateway/python/magma/pipelined/ifaces.py
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, size/XS

#6772 AGW: python: fix eventlet dependency
  lte/gateway/python/setup.py
Labels: apply-v1.5, component: agw, size/XS

#6773 devex: Improve PR bot message
  .github/workflows/pr_bot.yml
Labels: size/S

#6775 devex: Fix PR bot syntax error
  .github/workflows/pr_bot.yml
Labels: size/XS

#6748 AGW: deploy: ubuntu: Delete cloned magma repo after installation.
  docs/readmes/lte/deploy_install_ubuntu.md
  lte/gateway/deploy/agw_install_ubuntu.sh
  lte/gateway/deploy/agw_post_install_ubuntu.sh
Labels: component: agw, size/M

#6770 format: Commit leftover formatting from li-agent
  lte/gateway/c/li_agent/PDUGenerator.cpp
  lte/gateway/c/li_agent/test/test_pdu_generator.cpp
Labels: component: agw, size/XS

#6467 [Pylint] Add back redirectd/pkt_tester/monitord/smsd/health service to pylint test
  lte/gateway/python/magma/health/health_service.py
  lte/gateway/python/magma/health/state_recovery.py
  lte/gateway/python/magma/monitord/cpe_monitoring.py
  lte/gateway/python/magma/monitord/icmp_monitoring.py
  lte/gateway/python/magma/monitord/main.py
  lte/gateway/python/magma/redirectd/redirect_server.py
  lte/gateway/python/magma/redirectd/tests/test_redirect.py
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/smsd/relay.py
  lte/gateway/python/magma/tests/pylint_tests.py
Labels: component: agw, size/L

#4767 [lte][agw] Support to test pco option ipcp
  lte/gateway/c/oai/tasks/sgw/pgw_pco.c
  lte/gateway/c/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_pco_ipcp.py
Labels: component: agw, component: cwag, size/L

#6767 [feg] Basic accounting proto for integration with third party accounting/billing/contract systems
  feg/cloud/go/protos/basic_acct.pb.go
  feg/protos/basic_acct.proto
Labels: size/XL

#6777 [lte][agw] Propagate TEID for dedicated bearers back to sessiond
  lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/pgw_handlers.h
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
Labels: component: agw, size/M

#6637 [agw][lte][bug fix] Fix for issue 6325
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c
  lte/gateway/python/integ_tests/s1aptests/test_attach_complete_after_ics_timer_expiry.py
Labels: component: agw, size/L

#6780 devex: Incorporate PR bot feedback
  .github/workflows/pr_bot.yml
Labels: size/S

#5685 Support for flowdl in classifier for gtp tunnel #5505
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_add_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_delete_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_discard_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_resume_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_traffic.py
  lte/gateway/python/magma/pipelined/utils.py
  lte/protos/pipelined.proto
Labels: component: agw

#6407 [agw][lte] ovs flow verification for multi pdn and dedicated bearer TCs
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_dedicated_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_activate_deactivate_multiple_dedicated.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_activation_reject.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_activation_timer_expiry.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_activation_invalid_imsi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_activation_invalid_lbi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_deactivation_invalid_ebi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_deactivation_invalid_imsi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_deactivation_invalid_lbi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_deactivation_timer_expiry.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_looped.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_qci_0.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_maxbearers_twopdns.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_dedicated.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_nw_triggered_delete_last_pdn.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_nw_triggered_delete_secondary_pdn.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_disconnect_dedicated_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_disconnect_invalid_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_invalid_apn.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_looped.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_no_disconnect.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_with_dedicated_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_with_dedicated_bearer_deactivate.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_with_dedicated_bearer_looped.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_with_dedicated_bearer_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_secondary_pdn_with_pcscf_address.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_two_pdns_with_tcptraffic.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_secondary_pdn_spgw_initiated_ded_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_secondary_pdn_reject_multiple_sessions_not_allowed_per_apn.py
  lte/gateway/python/integ_tests/s1aptests/test_secondary_pdn_reject_unknown_pdn_type.py
Labels: component: agw, size/XXL

#6691 [fuji] Add details to 1.5 upgrade guide
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/docusaurus/versioned_docs/version-1.5.0/orc8r/upgrade_1_5.md
  docs/readmes/orc8r/upgrade_1_5.md
Labels: apply-v1.5, size/XL

#6769 refactor: Clean up process_rules_to_install to prepare for separating out default and dedicated bearer policies
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: component: agw, size/L

#6782 devex: Fix PR bot line-break
  .github/workflows/pr_bot.yml
Labels: size/XS

#6803 [AGW]Bump redis-collection
  orc8r/gateway/python/setup.py
Labels: component: agw, component: cwag, size/XS

#6695 AGW: Non-NAT: configure SGi as a router
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/arp.py
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_mtr_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_stray_arp_drop.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_ue_to_uplink_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_uplink_to_ue_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTestRouterIP.test_uplink_to_ue_arp_router_mode.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTestVlan.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Test.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
Labels: component: agw, size/L

#6814 refactor: Clean up process_rules_to_install to prepare for separating
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
Labels: component: agw, size/XL

#6752 [5G: MVC][component: agw][type: enhancement] Magma-5G merge issue fixes
  lte/gateway/c/oai/oai_mme/oai_mme.c
  lte/gateway/c/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_state_manager.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_fsm.cpp
  lte/gateway/c/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/oai/tasks/nas5g/include/AmfMessage.h
  lte/gateway/c/oai/tasks/nas5g/include/M5GAuthenticationRequest.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GABBA.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GAuthenticationParameterAUTN.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GAuthenticationParameterRAND.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GQOSRules.h
  lte/gateway/c/oai/tasks/nas5g/src/AmfMessage.cpp
  lte/gateway/c/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentAccept.cpp
  lte/gateway/c/oai/tasks/nas5g/src/SmfMessage.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GABBA.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GAuthenticationParameterAUTN.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GAuthenticationParameterRAND.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GPDUAddress.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GPDUSessionType.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GQOSRules.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
  lte/gateway/c/oai/tasks/ngap/CMakeLists.txt
  lte/gateway/c/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_ta.c
Labels: component: agw, size/XL

#6840 [backport v1.4] AGW: pipelined: QoS: Fix max bandwidth calculation.
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py
Labels: component: agw, component: cwag, size/M

#6843 [lte][agw] Change AGW ubuntu install script to not perform shallow clone of repository
  lte/gateway/deploy/agw_install_ubuntu.sh
Labels: apply-v1.5, component: agw, size/XS

#6712 Modified script to get default interface device for sgw_s8_user_plane
  lte/gateway/configs/spgw.yml
  lte/gateway/python/scripts/generate_oai_config.py
  orc8r/gateway/python/magma/common/misc_utils.py
Labels: apply-v1.5, component: agw, size/M

#6830 [mme] Modify directoryd api to include fields
  lte/gateway/c/oai/lib/directoryd/GatewayDirectorydClient.cpp
  lte/gateway/c/oai/lib/directoryd/GatewayDirectorydClient.h
  lte/gateway/c/oai/lib/directoryd/directoryd.cpp
  lte/gateway/c/oai/lib/directoryd/directoryd.h
Labels: component: agw, size/M

#6867 upgrade: Upgrade python sdk version from 1.0.0 to 1.1.0
  orc8r/gateway/python/setup.py
Labels: size/XS

#6800 [lte][agw] Updating deletion of s1ap imsi map entry when UE context is deleted
  lte/gateway/c/oai/lib/hashtable/hashtable.h
  lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/scripts/state_cli.py
Labels: apply-v1.4, apply-v1.5, component: agw, size/L

#6866 feat: [Sentry][Python] Add service name to events
  lte/gateway/python/magma/enodebd/main.py
  lte/gateway/python/magma/health/main.py
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/monitord/main.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/policydb/main.py
  lte/gateway/python/magma/redirectd/main.py
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/subscriberdb/main.py
  orc8r/gateway/python/magma/common/sentry.py
  orc8r/gateway/python/magma/common/service.py
  orc8r/gateway/python/magma/ctraced/main.py
  orc8r/gateway/python/magma/directoryd/main.py
  orc8r/gateway/python/magma/eventd/main.py
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/state/main.py
Labels: component: agw, size/L

#6815 AGW: ubuntu: python: Fix linter issue related loop arg
  orc8r/gateway/python/magma/common/cert_validity.py
Labels: apply-v1.5, size/XS

#6874 [CI]Fix code analysis mem leak
  .github/workflows/codeql-analysis.yml
Labels: size/XS

#6834 [lte] [agw] Add unit test for attach request decoding
  lte/gateway/c/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/oai/test/mme_app_task/test_mme_app_emm_decode.cpp
Labels: component: agw, size/M

#6864 feat: [Sentry][SessionD] Add hwid tag and move to a separate file
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/SentryWrappers.cpp
  lte/gateway/c/session_manager/SentryWrappers.h
  lte/gateway/c/session_manager/SessionProxyResponderHandler.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, size/L

#6808 [lte][agw] Accept eNB-initiated Reset from eNBs without UEs associated
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw, size/S

#6314 [orc8r][nprobe] Support IRI records export over tcp/tls
  cwf/cloud/go/go.mod
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.mod
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  lte/cloud/configs/nprobe.yml
  lte/cloud/go/go.mod
  lte/cloud/go/go.sum
  lte/cloud/go/services/nprobe/config.go
  lte/cloud/go/services/nprobe/exporter/exporter.go
  lte/cloud/go/services/nprobe/nprobe/main.go
  lte/cloud/go/services/nprobe/nprobe_manager/nprobe_manager.go
  orc8r/cloud/go/services/eventd/eventd_client/eventd_client.go
Labels: component: agw, component: cwag, ready2merge, size/L

#6880 doc: Add a bit more documentation to the bearer related proto fields
  lte/cloud/go/protos/session_manager.pb.go
  lte/cloud/go/protos/spgw_service.pb.go
  lte/protos/session_manager.proto
  lte/protos/spgw_service.proto
Labels: component: agw, component: cwag, size/M

#5217 [AGW][MME] GTP APP Offload Pipelined
  .gitignore
  lte/gateway/c/oai/include/sgw_config.h
  lte/gateway/c/oai/lib/CMakeLists.txt
  lte/gateway/c/oai/lib/pipelined_client/CMakeLists.txt
  lte/gateway/c/oai/lib/pipelined_client/PipelinedClientAPI.cpp
  lte/gateway/c/oai/lib/pipelined_client/PipelinedClientAPI.h
  lte/gateway/c/oai/lib/pipelined_client/PipelinedServiceClient.cpp
  lte/gateway/c/oai/lib/pipelined_client/PipelinedServiceClient.h
  lte/gateway/c/oai/lib/pipelined_client/proto_converters.cpp
  lte/gateway/c/oai/lib/pipelined_client/proto_converters.h
  lte/gateway/c/oai/tasks/gtpv1-u/CMakeLists.txt
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_libgtpnl.c
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.h
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_upf.c
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_upf.h
  lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u.h
  lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u_task.c
  lte/gateway/c/oai/tasks/sgw/sgw_config.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/test/CMakeLists.txt
  lte/gateway/c/oai/test/pipelined_client/CMakeLists.txt
  lte/gateway/c/oai/test/pipelined_client/test_pipelined_client.cpp
  lte/gateway/c/oai/test/pipelined_client/utility_protobuf.h
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/scripts/generate_oai_config.py
  lte/gateway/python/scripts/helpers/pg_set_session_msg.py
  lte/gateway/python/scripts/pipelined_cli.py
  orc8r/gateway/c/common/async_grpc/CMakeLists.txt
Labels: component: agw, size/XXL

#6882 git: Ignore build/lib not lib in gitignore
  .gitignore
Labels: size/XS

#6868 [DevExp] Make a '/rebase' comment able to rebase a PR
  .github/workflows/rebase.yml
Labels: component: agw, component: cwag, size/S

#6890 [ci][dco] Automatically comment PR when failing DCO check
  .github/workflows/dco-check.yml
Labels: size/S

#6863 feat: [Sentry][MME] add snowflake as hwid tag
  lte/gateway/c/oai/common/sentry_wrapper.cpp
Labels: component: agw, size/S

#6891 prevent nil dereference in cwf integration test
  cwf/gateway/integ_tests/omni_rules_test.go
Labels: component: agw, component: cwag, size/XS

#6883 fix: mobilitydclient no return value warning
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.h
  lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.cpp
  lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.h
Labels: component: agw, size/M

#6835 feat: [SessionD] Delay activation for policies with dedicated bearers
  lte/gateway/c/session_manager/AAAClient.cpp
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_data.py
Labels: component: agw, size/XXL

#6771 save OVS Flow TEID to register in pipelined #6596
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_multi_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows_ipv6.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_add_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_discard_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_resume_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_traffic.GTPTrafficTest.test_traffic_flows.snapshot
Labels: component: agw, size/L

#6895 ci: Add Magma-specific guidelines to DCO helptext
  .github/workflows/dco-check.yml
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
  feg/gateway/go.sum
Labels: component: cwag, size/XS

#6900 orc8r: Fix insync checkin
  orc8r/cloud/go/obsidian/swagger/v1/client/subscribers/post_lte_network_id_subscribers_v2_parameters.go
  orc8r/cloud/go/obsidian/swagger/v1/client/subscribers/post_lte_network_id_subscribers_v2_responses.go
  orc8r/cloud/go/obsidian/swagger/v1/client/subscribers/subscribers_client.go
  orc8r/cloud/go/obsidian/swagger/v1/models/mutable_subscribers.go
Labels: size/L

#6875 [lte][agw] Fixing state version and hash validation for MME UE state
  lte/gateway/c/oai/common/redis_utils/redis_client.cpp
  lte/gateway/c/oai/common/redis_utils/redis_client.h
  lte/gateway/c/oai/include/state_manager.h
Labels: component: agw, size/M

#6905 Fix CWF Integ Test IMSI prepend bug
  cwf/gateway/integ_tests/test_runner.go
Labels: component: cwag, size/XS

#6842 [AGW][UPGRADE]Make sure apt-transport-https gnupg2 are installed
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, size/XS

#6901 [feg] Simplify basic acct session
  feg/cloud/go/protos/basic_acct.pb.go
  feg/protos/basic_acct.proto
Labels: size/L

#6914 feg: cwf: Fix feg_lte missing serdes
  cwf/cloud/go/serdes/serdes.go
  feg/cloud/go/serdes/serdes.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers_test.go
Labels: apply-v1.5, component: cwag, component: cwf, component: feg, size/M

#6918 governance: Add docs/ codeowners
  CODEOWNERS
Labels: size/XS

#6912 clean: clean up unused functions and param types in SessionCredit
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/MeteringReporter.cpp
  lte/gateway/c/session_manager/MeteringReporter.h
  lte/gateway/c/session_manager/SessionCredit.cpp
  lte/gateway/c/session_manager/SessionCredit.h
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/test_charging_grant.cpp
  lte/gateway/c/session_manager/test/test_session_credit.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
Labels: component: agw, size/L

#6442 [NMS] Improve NMS docs
  docs/docusaurus/sidebars.json
  docs/readmes/assets/nms/grafana_homepage.png
  docs/readmes/assets/nms/grafana_query.png
  docs/readmes/assets/nms/grafana_variables.png
  docs/readmes/assets/nms/userguide/admin/admin.png
  docs/readmes/assets/nms/userguide/admin/audit_log1.png
  docs/readmes/assets/nms/userguide/admin/audit_log2.png
  docs/readmes/assets/nms/userguide/admin/audit_log3.png
  docs/readmes/assets/nms/userguide/admin/network.png
  docs/readmes/assets/nms/userguide/admin/users.png
  docs/readmes/assets/nms/userguide/app_sidebar.png
  docs/readmes/assets/nms/userguide/federation/adding_feg_lte_network1.png
  docs/readmes/assets/nms/userguide/federation/adding_feg_network1.png
  docs/readmes/assets/nms/userguide/federation/adding_feg_network2.png
  docs/readmes/assets/nms/userguide/federation/feg.png
  docs/readmes/assets/nms/userguide/federation/feg_alarms1.png
  docs/readmes/assets/nms/userguide/federation/feg_association.png
  docs/readmes/assets/nms/userguide/federation/feg_configure1.png
  docs/readmes/assets/nms/userguide/federation/feg_metrics1.png
  docs/readmes/assets/nms/userguide/federation/feg_overview1.png
  docs/readmes/assets/nms/userguide/federation/omnipresent1.png
  docs/readmes/nms/admin.md
  docs/readmes/nms/federation.md
  docs/readmes/nms/overview.md
Labels: apply-v1.5

#6920 [lte][agw] Fixing netmask parsing for Ipv6 address
  orc8r/gateway/python/magma/common/misc_utils.py
Labels: apply-v1.5, size/XS

#6412 [Sentry][Native] Update version 0.4.8 -> 0.4.9
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  third_party/build/bin/sentry-native-build.sh
Labels: component: agw, size/XS

#6898 refactor: remove bearer scheduling for create session
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/configs/sessiond.yml
Labels: component: agw, component: cwag, size/L

#6919 [Orc8r] Fix orc8r upgrade/install docs for 1.5
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/upgrade_1_5.md
Labels: size/XS

#6921 AGW: aioeventlet: Increment package iteration.
  third_party/build/bin/aioeventlet_build.sh
Labels: size/XS

#6897 [feg] Basic FeG accounting service
  feg/cloud/configs/base_acct.yml
  feg/cloud/configs/service_registry.yml
  feg/cloud/go/services/basic_acct/basic_acct/main.go
  feg/cloud/go/services/basic_acct/definitions.go
  feg/cloud/go/services/basic_acct/servicers/accounting_service_test.go
  feg/cloud/go/services/basic_acct/servicers/connection.go
  feg/cloud/go/services/basic_acct/servicers/participants.go
  feg/cloud/go/services/basic_acct/servicers/service.go
  feg/cloud/go/services/basic_acct/tests/protos/test_acct_pb.go
  feg/cloud/go/services/basic_acct/tests/setup.go
  feg/cloud/helm/feg-orc8r/templates/base_acct.pdb.yaml
  feg/cloud/helm/feg-orc8r/templates/base_acct.service.yaml
Labels: component: agw, component: cwag, component: feg, ready2merge, size/XXL

#6361 Add log forwarding to fluentd configuration to Federation gateway deployment
  .circleci/config.yml
  feg/gateway/docker/docker-compose.yml
  orc8r/gateway/configs/templates/td-agent-bit.conf.template
  orc8r/tools/docker/install_gateway.sh
Labels: size/M

#6893 Add sentry release github action
  .github/workflows/sentry-release.yml
Labels: size/S

#6931 Migrate CI CODEOWNERS to approvers-ci
  CODEOWNERS
Labels: size/S

#6932 Migrate CI CODEOWNERS to approvers-ci - missed a few the first time :(
  CODEOWNERS
Labels: size/XS

#6930 Annotate RuleRecord in session_manager.proto and move some comments
  lte/cloud/go/protos/session_manager.pb.go
  lte/protos/session_manager.proto
Labels: component: agw, size/L

#6933 Set the first 8 characters of commit hash as release version for sentry
  .github/workflows/sentry-release.yml
Labels: size/XS

#6861 Modified code to update sgw_c_teid to directoryd for multi pdns
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_handlers.c
Labels: component: agw, size/M

#6913 [codeowners] Add @magma/repo-magma-maintain to go.mod & go.sum
  CODEOWNERS
Labels: ready2merge, size/XS

#6929 [feg] switch base_acct to use external augmented-networks protos package
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  feg/cloud/go/services/basic_acct/servicers/accounting_service_test.go
  feg/cloud/go/services/basic_acct/servicers/connection.go
  feg/cloud/go/services/basic_acct/servicers/service.go
  feg/cloud/go/services/basic_acct/tests/protos/test_acct_pb.go
  lte/cloud/go/go.sum
Labels: component: agw, component: cwag, size/XL

#6935 refactor: Cleanup ChargingGrant output parameter types
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/test/test_charging_grant.cpp
Labels: component: agw, size/L

#6934 doc: Add basic C++ conventions
  docs/readmes/contributing/contribute_conventions.md
Labels: size/S

#6464 [NMS] Remove summation of duplicate attach req
  nms/app/packages/magmalte/alerts/lteAlerts.js
Labels: size/XS

#6940 [DevExp] update design proposal template
  docs/readmes/proposals/TEMPLATE.md
Labels: size/M

#6871 [nms] Update @fbcnms/alarms to 0.2.3
  nms/app/flow-typed/npm/@material-ui/icons_v4.x.x.js
  nms/app/packages/magmalte/app/components/EventAlertChart.js
  nms/app/packages/magmalte/app/components/context/RefreshContext.js
  nms/app/packages/magmalte/app/components/feg/FEGSections.js
  nms/app/packages/magmalte/app/components/lte/LteSections.js
  nms/app/packages/magmalte/app/state/AlarmsApiUtil.js
  nms/app/packages/magmalte/app/state/TraceState.js
  nms/app/packages/magmalte/app/state/lte/EquipmentState.js
  nms/app/packages/magmalte/app/state/lte/SubscriberState.js
  nms/app/packages/magmalte/app/views/alarms/Alarms.js
  nms/app/packages/magmalte/app/views/alarms/AlarmsDashboard.js
  nms/app/packages/magmalte/app/views/alarms/AlertRules.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberTable.js
  nms/app/packages/magmalte/package.json
  nms/app/yarn.lock
Labels: size/XL

#6927 AGW: package: fix commit-hash recording.
  lte/gateway/release/magma-postinst
Labels: component: agw, size/XS

#6872 [ci][githubActions][slack] Add slack notifications to failing github actions job
  .github/workflows/codeql-analysis.yml
Labels: component: ci, ready2merge, size/S

#6774 [ready2merge][orc8r][helm] Promote script for helm charts
  orc8r/tools/helm/promote.sh
Labels: component: orc8r, ready2merge, size/M, workstream: devops

#6605 [Documentation] Updated minimum RAM requirements
  docs/Magma FWA Product Specifications v1.0.pdf
  docs/docusaurus/versioned_docs/version-1.5.0/basics/prerequisites.md
Labels: ready2merge

#6959 Fix gcc warnings in common
  orc8r/gateway/c/common/test/test_service303.cpp
Labels: size/S

#6958 Add sentry transation tag to OperationalStatesHandler
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, size/XS

#6941 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#6960 Fix default log level to be INFO when there is no configuration
  orc8r/gateway/python/magma/common/service.py
Labels: size/L

#6964 [feg] bump go gtp version to 0.7.24
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
Labels: size/XS

#6761 [CI][OAI][AGW] Adding details in Build HTML report
  ci-scripts/generateHtmlReport-OAI-pipeline.py
Labels: size/L

#6789 Modified code to handle paging request for both roaming and non-roaming UEs
  lte/gateway/c/oai/common/itti_free_defined_msg.c
  lte/gateway/c/oai/include/s11_messages_types.h
  lte/gateway/c/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_ip_imsi.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_ip_imsi.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_pdn_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_pdn_context.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_state.cpp
  lte/gateway/c/oai/tasks/sgw/sgw_paging.c
  lte/gateway/c/oai/tasks/sgw/sgw_paging.h
Labels: component: agw, size/L

#6943 [codeowners] add auto-generated swagger files to @magma/repo-magma-maintain approval list
  CODEOWNERS
Labels: ready2merge, size/XS

#6881 [MME] Add libprotobuf-mutator to dockerfile for test
  .devcontainer/Dockerfile
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, size/S

#6980 Fix Pipelined Enf Stats IPv6 Removal
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
Labels: component: agw, size/S

#6922 [feg] Add 'accounting enabled' flag to AAA accounting service configs
  feg/cloud/go/services/controller/protos/feg_config.pb.go
  feg/cloud/go/services/controller/protos/feg_config.proto
  feg/cloud/go/services/feg/obsidian/models/aaa_server_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/defaults.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/obsidian/swagger/v1/models/aaa_server.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: size/L

#6983 Rever sentry dep version to 1.0.0
  orc8r/gateway/python/setup.py
Labels: size/XS

#6953 fix for skipping Identity procedure for suci based registration
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
Labels: component: agw, size/M

#6967 pipelined: add qos root stats
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
Labels: component: agw, size/S

#6966 [Cloud] Documentation changes for Cloudstrapper
  experimental/cloudstrapper/README.md
Labels: size/M

#6988 [feg] reverting protos at PR 6694
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/protos/s8_proxy.proto
Labels: size/L

#6989 Add protos changes to C++ unit tests determinator
  .circleci/config.yml
Labels: size/XS

#6986 improve error log that's seen on mobilityd start
  lte/gateway/python/magma/mobilityd/main.py
Labels: component: agw, size/M

#6991 [feg] Added protos for Create Bearer Request on S8_proxy and OAI
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/protos/s8_proxy.proto
  lte/gateway/c/oai/lib/s8_proxy/CMakeLists.txt
Labels: component: agw, size/XL

#6844 Output enforced rules in dp_probe
  docs/docusaurus/versioned_docs/version-1.5.0/lte/debug_dp_probe.md
  docs/readmes/lte/debug_dp_probe.md
  lte/gateway/python/scripts/dp_probe_cli.py
Labels: component: agw, size/L

#6996 [feg] Update base accounting octets In/Out counters to uint64
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  feg/cloud/go/protos/basic_acct.pb.go
  feg/cloud/go/services/basic_acct/servicers/accounting_service_test.go
  feg/gateway/services/aaa/servicers/accounting.go
  feg/protos/basic_acct.proto
  lte/cloud/go/go.sum
Labels: component: agw, component: cwag, ready2merge, size/L

#6997 Fix OVS conntrack sampling
  lte/gateway/python/magma/pipelined/app/conntrack.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_conntrack.ConntrackTest.test_conntrack.snapshot
Labels: apply-v1.5, component: agw, size/XS

#6995 Fix ubuntu IPFIX RYU Patch
  lte/gateway/release/build-magma.sh
Labels: apply-v1.5, component: agw, size/XS

#6925 [feg] Issue 6870 fix
  feg/cloud/go/services/feg/obsidian/models/mutable_federation_gateway_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/obsidian/swagger/v1/models/mutable_federation_gateway.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: size/S

#6961 [MagmaD] Improve error message for when a dynamic service is not registered
  orc8r/gateway/python/magma/magmad/service_manager.py
Labels: size/M

#6928 [or8r][directoryd] Add a TeidHwId mapping to directoryd
  orc8r/cloud/go/services/directoryd/client_api.go
  orc8r/cloud/go/services/directoryd/client_api_test.go
  orc8r/cloud/go/services/directoryd/servicers/servicer.go
  orc8r/cloud/go/services/directoryd/storage/storage.go
  orc8r/cloud/go/services/directoryd/storage/storage_blobstore.go
  orc8r/cloud/go/services/directoryd/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/directoryd/storage/storage_integ_test.go
  orc8r/cloud/go/services/directoryd/types/types.go
  orc8r/cloud/go/services/orchestrator/servicers/indexer_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/indexer_servicer_test.go
  orc8r/lib/go/protos/directoryd.pb.go
  orc8r/lib/go/protos/directoryd_helper.go
  orc8r/protos/directoryd.proto
Labels: size/XL

#6998 Enable Conntrack Packet IPFIX sampling
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/python/magma/pipelined/app/ipfix.py
Labels: apply-v1.5, component: agw, size/S

#7009 Fix S1 test default rule verificaton
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: apply-v1.5, component: agw, size/XS

#5954 Added code to send Activate Default/Dedicated Bearer Request in DL nas message
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_activation_timer_expiry.py
Labels: component: agw, size/M

#7010 Revert "Fix S1 test default rule verificaton"
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/XS

#7011 Revert "Enable Conntrack Packet IPFIX sampling"
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/python/magma/pipelined/app/ipfix.py
Labels: component: agw, size/S

#7015 [magmad] add s8_proxy as service maintained by magmad at feg
  feg/gateway/configs/magmad.yml
Labels: size/XS

#7014 [feg] Add gy CLI tool option to pass RatingGroup => ServiceIdentifier mapping
  feg/gateway/tools/gy_client_cli/main.go
Labels: size/M

#7013 [lte][agw] Fix the check for all flow rule but the default ones
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_asr.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_rar_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_he.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_setsessionrules_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_he_policy.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_ovs.py
Labels: component: agw, size/M

#3970 Added testcase to validate 3485 timer for both default and dedicated bearer
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_dedicated_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_default_bearer_with_mme_restart.py
Labels: component: agw, component: cwag, ready2merge, size/L

#5424 Flat rate ovs stats
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/c/session_manager/test/test_stored_state.cpp
  lte/gateway/c/session_manager/test/test_usage_monitor.cpp
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
Labels: component: agw, size/XL

#7019 OVS: GTP patches to implement segmentation offload.
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0001-of-match-expand-NXM_NX_TUN_FLAGS-to-include-all-tunn.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0002-userspace-IPFIX-Add-tunnel-type-GTP.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0003-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0004-ovs-Add-support-to-set-GTP-header-fields.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0005-OVS-gtp-echo-handling.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0006-ovs-test-add-gtp-marker-test.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0007-datapath-Fixes-for-4.9-kernel.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0008-ovs-datapath-enable-kernel-5.6.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0009-AGW-OVS-handle-gtp-tunnel-type.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0010-native-tnl-routing-tunnel-lookup-with-pkt-mark.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0011-fixes-for-2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0012-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0013-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0014-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0015-GTP-Extension-header-support-in-ovs2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0016-ODP-action-Fix-L3-port-to-L3-port-traffic.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0017-datapath-GTP-cleanup.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0018-datapath-gtp-add-segmentation-offloads.patch
Labels: size/XXL

#7016 docs: Document REST API resources
  orc8r/cloud/go/obsidian/swagger/v1/README.md
Labels: size/S

#7027 [AGW][DEV]Add https-transport to fetch Releases file throught https
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/XS

#6978 [AGW] Fix service restart status on the gateway
  orc8r/gateway/python/magma/magmad/metrics.py
Labels: size/L

#7030 [orc8r] Remove dead metrics profile code
  orc8r/cloud/go/services/metricsd/profile.go
Labels: component: orc8r, size/M

#7017 docs: add details for instructions in the onboarding docs
  docs/readmes/basics/prerequisites.md
  docs/readmes/basics/quick_start_guide.md
  docs/readmes/contributing/contribute_onboarding.md
  docs/readmes/contributing/contribute_workflow.md
Labels: size/M

#6977 [agw][bug fix] Fix for mme crash observed in test_3495_timer_for_default_bearer_with_mme_restart.py TC
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_procedures.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.h
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_default_bearer_with_mme_restart.py
  lte/protos/oai/nas_state.proto
Labels: component: agw, size/XL
