Repository magma/magma, pull requests merged in 2021-03, with the labels that each got.

#5199 AGW: pipelined: qos: skip filter for APN ambr queue
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_meter_impl.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: apply-v1.4, component: agw

#5228 AGW: pipelined: Refactor QoS TC implementation.
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/qos/tc_ops.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_cmd.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: apply-v1.4, component: agw

#5225 [pipelined]Add rpc call future timeout
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw

#5224 [AGW] Add a sigup handler that dumps tracebacks for all python services
  orc8r/gateway/python/magma/common/service.py
Labels: apply-v1.4

#5092 Added code to create SGW_S8 task
  lte/gateway/c/oai/common/log.c
  lte/gateway/c/oai/common/log.h
  lte/gateway/c/oai/include/tasks_def.h
  lte/gateway/c/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/oai/oai_mme/oai_mme.c
  lte/gateway/c/oai/tasks/CMakeLists.txt
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/sgw_s8/CMakeLists.txt
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_defs.h
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_task.c
Labels: component: agw

#5252 [EASY][AGW][Format] Add additional formats for sctp
  lte/gateway/c/sctpd/sctp_assoc.cpp
  lte/gateway/c/sctpd/sctp_assoc.h
  lte/gateway/c/sctpd/sctp_connection.cpp
  lte/gateway/c/sctpd/sctp_connection.h
  lte/gateway/c/sctpd/sctp_desc.cpp
  lte/gateway/c/sctpd/sctp_desc.h
  lte/gateway/c/sctpd/sctpd.cpp
  lte/gateway/c/sctpd/sctpd_downlink_impl.cpp
  lte/gateway/c/sctpd/sctpd_downlink_impl.h
  lte/gateway/c/sctpd/sctpd_event_handler.cpp
  lte/gateway/c/sctpd/sctpd_event_handler.h
  lte/gateway/c/sctpd/sctpd_uplink_client.cpp
  lte/gateway/c/sctpd/sctpd_uplink_client.h
  lte/gateway/c/sctpd/test/test_event_handler.cpp
  lte/gateway/c/sctpd/test/test_sctp_desc.cpp
  lte/gateway/c/sctpd/util.cpp
Labels: component: agw

#5251 Fixed the compilation issue occurring in OAI build
  lte/gateway/c/oai/oai_mme/oai_mme.c
Labels: component: agw

#5255 pipelined: classifier test failure #5239
  lte/gateway/python/magma/pipelined/app/classifier.py
Labels: component: agw

#5240 AGW: pipelined: use pyroute2 to manage TC queue and filters
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/bridge_util.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_cmd.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
  lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py
  lte/gateway/python/setup.py
Labels: apply-v1.4, component: agw

#5262 [MME][Memory] Enable UBSAN for debug builds and resolve unaligned memory access issues
  lte/gateway/c/oai/CMakeLists.txt
  lte/gateway/c/oai/common/async_system.c
  lte/gateway/c/oai/common/common_defs.h
  lte/gateway/c/oai/common/conversions.h
  lte/gateway/c/oai/common/log.c
  lte/gateway/c/oai/common/shared_ts_log.c
  lte/gateway/c/oai/lib/itti/intertask_interface.c
  lte/gateway/c/oai/lib/itti/intertask_interface.h
  lte/gateway/c/oai/lib/itti/itti_types.h
  lte/gateway/c/oai/lib/itti/memory_pools.c
  lte/gateway/c/oai/lib/message_utils/bytes_to_ie.c
  lte/gateway/c/oai/lib/secu/nas_stream_eia1.c
  lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/oai/tasks/ha/ha_task.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/nas/api/network/nas_message.c
  lte/gateway/c/oai/tasks/s11/s11_ie_formatter.c
  lte/gateway/c/oai/tasks/s11/s11_tasks.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/oai/tasks/service303/service303_task.c
  lte/gateway/c/oai/tasks/sgs/sgs_task.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/oai/tasks/sms_orc8r/sms_orc8r_task.c
  lte/gateway/c/oai/tasks/udp/udp_primitives_server.c
Labels: component: agw

#4765 [Converged-MME] Timers issue resolution.
  lte/gateway/c/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_timer.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_timer_management.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_timer_management.h
Labels: component: agw

#5190 [lte][ha] Add gateway pool API update route
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw

#5231 [Orc8r] Adding restricted_plmn_ids and service_area_tac mapping to network EPC configs
  feg/cloud/go/services/feg/obsidian/models/plmn_config_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/tac_list_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/tac_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/network_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/plmn_config_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/tac_list_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/tac_swaggergen.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw

#5250 [CI][OAI] Fix when the PR title contains a # character.
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw, component: ci

#5264 [agw][lte] Adding checks for health service enable and disable on S1AP wrapper
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_corrupt_stateless_mme.py
  lte/gateway/python/integ_tests/s1aptests/test_modify_mme_config_for_sanity.py
  lte/gateway/python/integ_tests/s1aptests/test_restore_mme_config_after_sanity.py
Labels: component: agw

#5034 [helm][tf] provide default grafana volumes
  docs/readmes/orc8r/upgrade_1_4.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/helm/orc8r/Chart.lock
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/templates/user-grafana.deployment.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/values.yaml
Labels: apply-v1.4

#5277 [CWFIntegTest] Disable QosRestart tests since they are failing + filed an issue to fix
  cwf/gateway/integ_tests/gx_qos_restart_test.go
  cwf/gateway/integ_tests/stateless_test.go
Labels: component: cwag

#5241 Merge Swagger Lib into Swagger Obsidian Service
  orc8r/cloud/Makefile
  orc8r/cloud/go/Makefile
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/obsidian/swagger/poll.go
  orc8r/cloud/go/obsidian/swagger/poll_test.go
  orc8r/cloud/go/obsidian/swagger/spec/combine.go
  orc8r/cloud/go/obsidian/swagger/spec/combine_test.go
  orc8r/cloud/go/obsidian/swagger/spec/testdata/common/common.yml
  orc8r/cloud/go/obsidian/swagger/spec/testdata/configs/base.yml
  orc8r/cloud/go/obsidian/swagger/spec/testdata/configs/cycle1.yml
  orc8r/cloud/go/obsidian/swagger/spec/testdata/configs/cycle2.yml
  orc8r/cloud/go/obsidian/swagger/spec/testdata/configs/importer.yml
  orc8r/cloud/go/obsidian/swagger/spec/testdata/configs/importer2.yml
  orc8r/cloud/go/obsidian/swagger/spec/testdata/out.yml.golden
  orc8r/cloud/go/swagger/spec.go
  orc8r/cloud/go/tools/combine_swagger/combine/combine_test.go
  orc8r/cloud/go/tools/combine_swagger/main.go
Labels: component: agw, component: cwag

#5282 [Orc8r] Add changes to pass restricted plmn IDs and service area maps to mconfig
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw

#5281 [lte][helm] Fix formatting for smsd k8s service
  lte/cloud/helm/lte-orc8r/Chart.lock
  lte/cloud/helm/lte-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/lte-orc8r-0.2.0.tgz
  lte/cloud/helm/lte-orc8r/templates/smsd.service.yaml
Labels: component: agw

#5280 AGW: pipelined: introduce locking to avoid exception on TC queue removal.
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_cmd.py
  lte/gateway/python/magma/pipelined/qos/utils.py
Labels: apply-v1.4, component: agw

#5247 [lte][agw] Adding write-through cache to RedisFlatDict, removing few locking on read mobilityd functions
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ip_descriptor_map.py
  lte/gateway/python/magma/mobilityd/mobility_store.py
  lte/gateway/python/magma/mobilityd/uplink_gw.py
  orc8r/gateway/python/magma/common/redis/containers.py
Labels: apply-v1.4, component: agw

#4757 [ctraced][nms] Add NMS support for call trace command passthrough
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/admin/AddNetworkDialog.js
  nms/app/packages/magmalte/app/e2e/NetworkUtils.js
  nms/app/packages/magmalte/app/e2e/__tests__/FegLte-test.js
  nms/app/packages/magmalte/app/theme/default.js
  nms/app/packages/magmalte/app/views/tracing/TraceStartDialog.js
Labels: apply-v1.4, component: agw, component: cwag

#5233 [docs] Update minikube docs
  docs/readmes/orc8r/development/minikube_deployment.md
  orc8r/cloud/helm/orc8r/examples/minikube_values.yml
Labels: apply-v1.4

#5290 [SessionD] Sync ue_traffic metrics counter value with persisted usage value on service restart
  lte/gateway/c/session_manager/MeteringReporter.cpp
  lte/gateway/c/session_manager/MeteringReporter.h
  lte/gateway/c/session_manager/SessionCredit.h
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: apply-v1.4, component: agw

#5293 [pipelined]Fix unit test stats verification
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
Labels: component: agw

#5279 [AGW][MME] Reset num_ues_checked while cleaning up UE state for each eNB
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp
Labels: apply-v1.4, component: agw

#5297 [lte][agw] Fixed free for _esm_information_t3489_handler
  lte/gateway/c/oai/tasks/nas/esm/esm_information.c
  lte/gateway/python/integ_tests/s1aptests/test_attach_esm_info_timerexpiration_max_retries.py
Labels: apply-v1.4, component: agw

#5294 [pipelined]Add rpc failure for uninitialized controllers
  lte/gateway/python/magma/pipelined/app/base.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: apply-v1.4, component: agw

#5307 [MME][ZMQ] Protect against multiple threads using the same context
  lte/gateway/c/oai/lib/itti/intertask_interface.c
  lte/gateway/c/oai/lib/itti/intertask_interface.h
Labels: apply-v1.3, apply-v1.4, component: agw

#5127 [orc8r][configurator] Update configurator to allow for paginated entity loads
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/analytics/calculations/state.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/rating_groups_handlers.go
  lte/cloud/go/services/policydb/streamer/providers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/streamer/providers.go
  lte/cloud/go/tools/migrations/m010_default_apns/main.go
  orc8r/cloud/configs/configurator.yml
  orc8r/cloud/go/services/configurator/client_api.go
  orc8r/cloud/go/services/configurator/client_api_test.go
  orc8r/cloud/go/services/configurator/configurator/main.go
  orc8r/cloud/go/services/configurator/doc.go
  orc8r/cloud/go/services/configurator/storage/sql.go
  orc8r/cloud/go/services/configurator/storage/sql_entity_load_helpers.go
  orc8r/cloud/go/services/configurator/storage/sql_integ_test.go
  orc8r/cloud/go/services/configurator/storage/sql_test.go
  orc8r/cloud/go/services/configurator/storage/storage.go
  orc8r/cloud/go/services/configurator/storage/storage.pb.go
  orc8r/cloud/go/services/configurator/storage/storage.proto
  orc8r/cloud/go/services/configurator/test_init/test_service_init.go
  orc8r/cloud/go/services/configurator/types.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
Labels: component: agw, component: cwag

#5306 [AGW][SessionD] Remove per-session counters on session termination
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/MeteringReporter.cpp
  lte/gateway/c/session_manager/MeteringReporter.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStore.cpp
  orc8r/gateway/c/common/service303/MetricsHelpers.cpp
  orc8r/gateway/c/common/service303/MetricsHelpers.h
  orc8r/gateway/c/common/service303/MetricsRegistry.h
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.h
Labels: apply-v1.4, component: agw

#5011 [feg] s8_proxy fix TEIDs on Create Session and add DeleteSession to s8_cli and made s8 stateless
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
  feg/gateway/go.sum
  feg/gateway/gtp/enriched_message/message.go
  feg/gateway/gtp/gtp_client.go
  feg/gateway/gtp/gtp_client_test.go
  feg/gateway/gtp/session_manager.go
  feg/gateway/services/s8_proxy/client_api.go
  feg/gateway/services/s8_proxy/client_api_test.go
  feg/gateway/services/s8_proxy/servicers/config.go
  feg/gateway/services/s8_proxy/servicers/config_test.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/ds.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/gateway/services/s8_proxy/test_init/test_service_init.go
  feg/gateway/tools/s8_cli/main.go
  feg/gateway/tools/s8_cli/s8_client.go
  feg/protos/s8_proxy.proto
Labels: component: feg

#5308 [SessionD] Reject all new sessions while PipelineD is setting up
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: apply-v1.4, component: agw

#4927 [AGW] Bump ovs from 2.8.9 to 2.8.10
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
  lte/gateway/deploy/roles/ovs_prepare/vars/all.yaml
  lte/gateway/release/build-magma.sh
  lte/gateway/release/build-ovs.sh
Labels: component: agw

#5210 [subscriberdb] Add GRPC printing to log
  docs/readmes/lte/dev_notes.md
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
Labels: component: agw

#5339 MME: GTP-APP: introduce pgw port and ip in tunnel events.
  lte/gateway/c/oai/lib/openflow/controller/ControllerEvents.cpp
  lte/gateway/c/oai/lib/openflow/controller/ControllerEvents.h
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
Labels: component: agw

#2588 [agw][lte] New integ tests for set session interface
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_activate_deactivate_multiple_dedicated.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_rar_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_activation_reject.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_setsessionrules_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers_failure.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers_looped.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers_mt_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
  lte/gateway/python/integ_tests/s1aptests/test_dedicated_bearer_activation_idle_mode.py
  lte/gateway/python/integ_tests/s1aptests/test_dedicated_bearer_activation_idle_mode_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_dedicated_bearer_activation_idle_mode_paging_timer_expiry.py
Labels: component: agw

#5304 [Docs] Minor doc changes in orc8r_install doc
  docs/readmes/orc8r/deploy_install.md
Labels: apply-v1.4

#5344 [lte][agw] Fixing state CLI parsing of SPGW ue state, SPGW state and S1AP state
  lte/gateway/python/scripts/state_cli.py
Labels: apply-v1.4, component: agw

#5346 [SubscriberDB] Fix subscriberdb crash + some format leftovers on master
  lte/gateway/c/oai/lib/openflow/controller/ControllerEvents.cpp
  lte/gateway/c/oai/lib/openflow/controller/ControllerEvents.h
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
Labels: component: agw

#5336 pipelined: classifier test failure #5239 extension review comments fix
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_multi_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
Labels: component: agw

#5212 [subscriberdb] implement purgeUE
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
Labels: component: agw

#4773 [Converged-MME][LTE] ts6_1_timer edit
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_sgsap_location_update.c
Labels: component: agw, component: cwag

#5347 [v1.4][tf] Update variables.tf to be aligned with v1.4 docs
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: component: agw, component: cwag

#5355 [lte][agw] Scptd modifications to avoid burst after mme recovery
  lte/gateway/c/sctpd/sctp_connection.cpp
  lte/gateway/c/sctpd/sctp_connection.h
  lte/gateway/c/sctpd/sctpd_event_handler.cpp
  lte/gateway/c/sctpd/sctpd_event_handler.h
  lte/gateway/c/sctpd/sctpd_uplink_client.cpp
  lte/gateway/c/sctpd/sctpd_uplink_client.h
Labels: apply-v1.4, component: agw

#5373 [lte][agw] Adding sync of cache on RedisFlatDict init function
  orc8r/gateway/python/magma/common/redis/containers.py
Labels: apply-v1.4, component: agw

#5371 [AGW][MME] Remove IMSI SPGW state only when tunnel list is empty
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/python/integ_tests/s1aptests/test_secondary_pdn_with_dedicated_bearer_multiple_services_restart.py
Labels: apply-v1.4, component: agw

#5320 [orc8r] Add LTE federated parameters to LTE mconfig and Federated Mapping definition
  cwf/cloud/go/services/cwf/obsidian/models/federated_mode_map_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/mode_map_item_swaggergen.go
  fbinternal/cloud/go/go.mod
  feg/cloud/go/go.mod
  feg/cloud/go/services/feg/obsidian/models/conversion.go
  feg/cloud/go/services/feg/obsidian/models/defaults.go
  feg/cloud/go/services/feg/obsidian/models/federated_mode_map_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/federated_network_configs_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/mode_map_item_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  lte/cloud/go/go.mod
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, component: cwag, component: feg, component: orc8r

#5379 [pipelined]Move rule info storage to Flat Redis Dicts
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
Labels: apply-v1.4, component: agw

#4786 [Converged-MME]ts8_timer edit
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_status.c
Labels: component: agw, component: cwag

#4635 [CI][Jenkins] Use fabric to trigger LTE integration tests
  lte/gateway/fabfile.py
Labels: component: agw, component: cwag

#5391 [MME] fix fall-through of S1AP_INVALID_MME_UE_S1AP_ID handling
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: apply-v1.4, component: agw, source:clang-tidy

#5395 [PipelineD][UnitTests] Fix pipelined redis tests round by mocking redis
  lte/gateway/python/magma/pipelined/tests/test_rule_mappers.py
  lte/gateway/python/magma/pipelined/tests/test_service_manager.py
Labels: apply-v1.4, component: agw

#4928 [DOCKER][MME] configuring MME to run stateful in OAI deployment
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw

#5398 [SessionD] Address some clang-tidy warnings
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/RedisStoreClient.cpp
  lte/gateway/c/session_manager/RuleStore.cpp
  lte/gateway/c/session_manager/SessionID.cpp
  lte/gateway/c/session_manager/SessionID.h
  lte/gateway/c/session_manager/SessionManagerServer.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw

#5338 Adding sgw_s8 task during initialization of main task
  lte/gateway/c/oai/oai_mme/oai_mme.c
Labels: component: agw

#5349 [orc8r] Document and clean up Orc8r e2e security
  docs/docusaurus/sidebars.json
  docs/readmes/assets/orc8r/orc8r_proxying.png
  docs/readmes/orc8r/architecture_security.md
  docs/readmes/orc8r/dev_minikube_deployment.md
  docs/readmes/orc8r/dev_security.md
  docs/readmes/orc8r/dev_testing_tips.md
  lte/cloud/configs/ha.yml
  orc8r/cloud/docker/nginx/templates/nginx.conf.j2
  orc8r/cloud/go/obsidian/access/rest_middleware.go
  orc8r/cloud/go/service/middleware/unary/identity_decorator.go
  orc8r/cloud/go/service/middleware/unary/identity_decorator_bypass.go
  orc8r/cloud/go/service/middleware/unary/registered_gw_enforcer.go
  orc8r/cloud/go/services/accessd/protos/access.proto
  orc8r/cloud/go/services/bootstrapper/bootstrapper/main.go
  orc8r/cloud/go/services/bootstrapper/const.go
  orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
  orc8r/cloud/go/services/orchestrator/servicers/indexer_servicer.go
  orc8r/cloud/go/tools/accessc/handlers/common.go
  orc8r/gateway/go/services/bootstrapper/service/bootstrapper.go
  orc8r/gateway/python/scripts/checkin_cli.py
  orc8r/gateway/python/scripts/show_gateway_info.py
  orc8r/tools/scripts/consolidate_protos.sh
Labels: component: agw

#4787 [Converged-MME]ts9_timer edit
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
Labels: component: agw, component: cwag

#5381 [lte][orc8r] Add subscriber API endpoint for paginated loads
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/obsidian/models/next_page_token_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/paginated_subscribers_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  lte/cloud/helm/lte-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/values.yaml
  orc8r/cloud/go/models/swagger-common.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw

#5426 [lte][agw] Removed unsafe mme_nas state sync to db
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_statistics.c
  lte/gateway/c/oai/tasks/service303/service303_mme_stats.c
Labels: apply-v1.4, component: agw

#5232 [cloud] [agw] AGW AMI deployment for Cloudstrapper
  experimental/cloudstrapper/README.md
  experimental/cloudstrapper/playbooks/agw-configure.yaml
  experimental/cloudstrapper/playbooks/agw-provision.yaml
  experimental/cloudstrapper/playbooks/ami-configure.yaml
  experimental/cloudstrapper/playbooks/ami-init.yaml
  experimental/cloudstrapper/playbooks/build-provision.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/attach-interfaces.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/provision-instances.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/provision-networks.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewayCupertinoAgwA.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewayMenloParkAgwA.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewayMenloParkAgwB.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewaySanRamonAgwA.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewaySanRamonAgwB.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewayTokyoAgwA.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varGatewayTokyoAgwB.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varSiteCupertino.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varSiteMenloPark.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varSiteSanRamon.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/vars/varSiteTokyo.yaml
  experimental/cloudstrapper/playbooks/roles/agw-platform/files/control_proxy.j2
  experimental/cloudstrapper/playbooks/roles/agw-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/agw-platform/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/ami-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/agw-devops.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/cleanup.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/orc8r-devops.yaml
  experimental/cloudstrapper/playbooks/roles/build-platform/tasks/build-magma.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/files/ansible-env.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/files/debian-latest-ansible.bash
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/files/inventory
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/tasks/agw-setup.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/tasks/ansible-setup.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/tasks/magma-setup.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw-1.4/vars/main.yml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
  experimental/cloudstrapper/playbooks/roles/vars/cluster.yaml
Labels: v1.5

#4772 [lte][agw] Disable smsd AGW service by default
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/smsd/relay.py
Labels: apply-v1.4, component: agw, component: cwag

#5433 [pipelined]Fix Init for non Redis Setups
  lte/gateway/python/magma/pipelined/ipv6_prefix_store.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tunnel_id_store.py
Labels: apply-v1.4, component: agw

#5434 AGW: pipelined: Set direction for inbound traffic,
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout.InOutTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout.InOutTestLTE.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout.InOutTestXWF.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout_non_nat.InOutTestNonNATBasicFlows.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_li_mirror.LIMirrorTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_ue_passthrough.UEMacAddressTest.test_passthrough_rules.snapshot
  lte/gateway/python/magma/pipelined/tests/test_ue_passthrough.py
Labels: component: agw

#4835 [Converged-MME]ts10_timer and ts13_timer edit.
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_sgs_detach.c
Labels: component: agw, component: cwag

#5368 [PipelineD][SessionD] Cleanup flows for non-existent sessions
  lte/cloud/go/protos/pipelined.pb.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/EnumToString.h
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/protos/pipelined.proto
  lte/protos/session_manager.proto
Labels: component: agw

#5443 Revert "[PipelineD][SessionD] Cleanup flows for non-existent sessions"
  lte/cloud/go/protos/pipelined.pb.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/EnumToString.h
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/protos/pipelined.proto
  lte/protos/session_manager.proto
Labels: component: agw

#5445 [orc8r] reverse condition to check network type on lte mconfig builder
  feg/cloud/go/services/feg/obsidian/models/feg_network_id_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/feg_network_id_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw

#5416 [AGW] [MME] Adding IP_ALLOCATION_RESPONSE to handle ip allocation process on SPGW…
  lte/gateway/c/oai/include/ip_forward_messages_def.h
  lte/gateway/c/oai/include/ip_forward_messages_types.h
  lte/gateway/c/oai/include/spgw_types.h
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.h
  lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/oai/tasks/sgw/sgw_task.c
Labels: apply-v1.4, component: agw

#5400 [orc8r] Create standalone specs at build time
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/Makefile
  orc8r/cloud/go/models/swagger-common.yml
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/obsidian/swagger/handlers/handlers.go
  orc8r/cloud/go/obsidian/swagger/handlers/handlers_test.go
  orc8r/cloud/go/obsidian/swagger/poll.go
  orc8r/cloud/go/obsidian/swagger/poll_test.go
  orc8r/cloud/go/obsidian/swagger/protos/swagger.pb.go
  orc8r/cloud/go/obsidian/swagger/protos/swagger.proto
  orc8r/cloud/go/obsidian/swagger/remote_spec.go
  orc8r/cloud/go/obsidian/swagger/spec/combine.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/tools/combine_swagger/combine/combine_test.go
  orc8r/cloud/go/tools/combine_swagger/generate/generate.go
  orc8r/cloud/go/tools/combine_swagger/generate/generate_test.go
  orc8r/cloud/go/tools/combine_swagger/main.go
  orc8r/cloud/go/tools/combine_swagger/testdata/common/common.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/base.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/cycle1.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/cycle2.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/importer.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/importer2.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/monolithic.yml.golden
  orc8r/cloud/go/tools/combine_swagger/testdata/standalone.yml.golden
  orc8r/cloud/go/tools/swaggergen/generate/generate.go
  wifi/cloud/go/go.sum
Labels: component: agw, component: cwag

#5456 [AGW][MME] Send ITTI message from PCEF create session callback
  lte/gateway/c/oai/include/gx_messages_def.h
  lte/gateway/c/oai/include/gx_messages_types.h
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/oai/lib/pcef/PCEFClient.cpp
  lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/pgw_handlers.h
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/oai/tasks/sgw/spgw_state.cpp
Labels: apply-v1.4, component: agw

#5303 [Bug_Fix] [MME_Crash] [Mobile_Reachability_Timer] Fixed MME crash during sanity while handling mobile reachability timer expiry
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw

#5464 [AGW] [MME][v1.4] Fix ICS timer argument to mme_app_resume_timers
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw, component: cwag

#5462 [SessionD] Add a DirectoryDClient base class
  lte/gateway/c/session_manager/DirectorydClient.cpp
  lte/gateway/c/session_manager/DirectorydClient.h
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/RestartHandler.cpp
  lte/gateway/c/session_manager/RestartHandler.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
Labels: component: agw

#5476 [lte][agw] Fix for bug introduced in Rel 15 on failed erab list
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: apply-v1.4, component: agw

#5465 [SessionD] Add a EventDClient base class with virtual methods
  lte/gateway/c/session_manager/AAAClient.h
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/SessionEvents.cpp
  lte/gateway/c/session_manager/SessionEvents.h
  lte/gateway/c/session_manager/SessionReporter.h
  lte/gateway/c/session_manager/SpgwServiceClient.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  orc8r/gateway/c/common/eventd/EventdClient.cpp
  orc8r/gateway/c/common/eventd/EventdClient.h
Labels: component: agw

#5358 [AGW] Remove -Werror compiler flag everywhere, add -Wextra
  lte/gateway/c/connection_tracker/CMakeLists.txt
  lte/gateway/c/oai/CMakeLists.txt
  lte/gateway/c/session_manager/CMakeLists.txt
Labels: component: agw

#5493 AGW: pipelined: skip old tests.
  lte/gateway/python/magma/pipelined/tests/old_tests/test_controller.py
  lte/gateway/python/magma/pipelined/tests/old_tests/test_inout.py
Labels: component: agw

#5491 AGW: pipelined: fix vsctl warning: target type "testing_br" is possibly erroneous
  lte/gateway/python/magma/pipelined/bridge_util.py
Labels: component: agw

#5495 AGW: pipelined: uplink-br0: avoid resetting SGi ip address
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/bridge_util.py
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
Labels: apply-v1.4, component: agw

#5492 AGW: Fix memory size for focal VM.
  lte/gateway/Vagrantfile
Labels: component: agw

#5460 [1.4] AGW: fix pyroute2 dependency.
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile
Labels: apply-v1.4, component: agw, component: cwag

#5459 AGW: fix pyroute2 dependency.
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile
Labels: component: agw

#5404 [CI] Enable GCC Warning Annotations on GH Pull Requests
  .github/workflows/gcc-problems.yml
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/session_manager/AAAClient.cpp
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw

#5489 [CMake] Ensure compile_commands.json generation
  lte/gateway/Makefile
  lte/gateway/c/oai/CMakeLists.txt
  lte/gateway/c/sctpd/CMakeLists.txt
Labels: component: agw

#4798 [AGW][S1ap tests] Split mandatory S1ap tests into precommit and extended
  lte/gateway/python/integ_tests/Makefile
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_enb_partial_reset.py
Labels: component: agw, component: cwag

#5482 [SessionD] Clean up SessionD unit tests by looking at ASAN outputs
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/SessionManagerServer.cpp
  lte/gateway/c/session_manager/SessionManagerServer.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/test_cloud_reporter.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_metering_reporter.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_store_client.cpp
  orc8r/gateway/c/common/async_grpc/GRPCReceiver.cpp
  orc8r/gateway/c/common/async_grpc/GRPCReceiver.h
Labels: component: agw

#5376 [magmad] Add GRPC logging capabilities to magmad
  docs/readmes/lte/dev_notes.md
  feg/gateway/configs/magmad.yml
  lte/gateway/configs/magmad.yml
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
Labels: component: agw

#5502 [Non-Functional] Remove accidentally committed GCC warnings
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/session_manager/AAAClient.cpp
Labels: component: agw

#5520 v1.4 to point to stretch-1.4.0
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
Labels: component: agw, component: cwag

#5519 [AGW][Baremetal Install]Master to point to stretch-1.4.0
  lte/gateway/deploy/agw_install.sh
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
Labels: component: agw

#5530 Save commit hash and add to env var
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma-postinst
Labels: component: agw

#5534 [SessionD] Modify SessionD unit tests for better stability
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
Labels: component: agw

#5533 AGW: qos: fix ovs meter implementation.
  lte/gateway/python/magma/pipelined/qos/qos_meter_impl.py
Labels: component: agw

#5536 [agw][mme][easy] Remove unused S1AP ITTI log msgs and gcc warning on fn return type
  lte/gateway/c/oai/common/itti_free_defined_msg.c
  lte/gateway/c/oai/common/log.c
  lte/gateway/c/oai/common/log.h
  lte/gateway/c/oai/include/s1ap_messages_def.h
  lte/gateway/c/oai/tasks/s1ap/CMakeLists.txt
Labels: component: agw

#5537 Temporarily disable CWF qos
  cwf/gateway/configs/pipelined.yml
  cwf/gateway/integ_tests/gx_qos_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_restart_test.go
  cwf/gateway/integ_tests/pipelined.yml
Labels: component: cwag

#5540 [AGW]Force-overwrite in baremetal install (fix syslog overwritten pro…
  lte/gateway/deploy/roles/ovs_deploy/tasks/main.yml
Labels: component: agw, component: cwag

#4766 [MME][Ubuntu18] fixes for build oai-mme in RelWithDebInfo
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/c/oai/common/pid_file.c
  lte/gateway/c/oai/tasks/udp/udp_primitives_server.c
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw, component: cwag

#5541 [pipelined]Remove UE controller check to unblock CI
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw

#5559 [CI] Remove -Wextra from default flags, enable env use
  .github/workflows/gcc-problems.yml
  lte/gateway/Makefile
  lte/gateway/c/connection_tracker/CMakeLists.txt
  lte/gateway/c/oai/CMakeLists.txt
  lte/gateway/c/session_manager/CMakeLists.txt
Labels: component: agw

#5565 Add Connection Tracking Service (#2318)
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/Makefile
  lte/gateway/c/connection_tracker/CMakeLists.txt
  lte/gateway/c/connection_tracker/EventTracker.cpp
  lte/gateway/c/connection_tracker/EventTracker.h
  lte/gateway/c/connection_tracker/PacketGenerator.cpp
  lte/gateway/c/connection_tracker/PacketGenerator.h
  lte/gateway/c/connection_tracker/main.cpp
  lte/gateway/configs/connectiond.yml
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/service_registry.yml
  lte/gateway/deploy/roles/magma/files/systemd/magma_connectiond.service
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/app/conntrack.py
  lte/gateway/python/magma/pipelined/tests/test_conntrack.py
  lte/gateway/release/build-magma.sh
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, component: cwag

#5552 [mme] Add federated map to mme.config and template
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw

#5058 [feg] enable S8_proxy on docker-compose
  feg/gateway/docker/docker-compose.yml
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/tools/s8_cli/main.go
  feg/gateway/tools/s8_cli/main_test.go
Labels: component: feg

#5585 [mme] fix generate_oai_config.py
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw

#5562 [session_manager] Add missing headers and linking for GPR_ASSERT
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/SessionManagerServer.cpp
Labels: component: agw

#5560 Fixup missing includes detected by new docker build env
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/EnumToString.h
Labels: component: agw

#5561 [Coverage] Add BUILD_TESTS flags for code coverage output
  lte/gateway/c/connection_tracker/CMakeLists.txt
  lte/gateway/c/session_manager/CMakeLists.txt
Labels: component: agw

#5275 Add Pipelined Classifier IPv6 support #4556
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/ng_manager/session_state_manager_util.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows_ipv6.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_detach_tunnel_flows_ipv6.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_discard_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_discard_tunnel_flows_ipv6.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_resume_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_resume_tunnel_flows_ipv6.snapshot
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_traffic.py
Labels: component: agw

#5566 [agw] Attach Optional Sentry Error Handling
  lte/gateway/configs/control_proxy.yml
  lte/gateway/python/magma/enodebd/main.py
  lte/gateway/python/magma/health/main.py
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/monitord/main.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/policydb/main.py
  lte/gateway/python/magma/redirectd/main.py
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/setup.py
  orc8r/gateway/configs/control_proxy.yml
  orc8r/gateway/python/magma/common/sentry.py
  orc8r/gateway/python/magma/ctraced/main.py
  orc8r/gateway/python/magma/directoryd/main.py
  orc8r/gateway/python/magma/eventd/main.py
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/state/main.py
  orc8r/gateway/python/setup.py
Labels: component: agw

#5503 [docs] [orc8r] Add docs for module-module dependencies
  cwf/cloud/go/services/cwf/obsidian/models/swagger.v1.yml
  docs/docusaurus/sidebars.json
  docs/readmes/assets/orc8r/gen_construct_dependencies.excalidraw
  docs/readmes/assets/orc8r/gen_construct_dependencies.png
  docs/readmes/orc8r/dev_dependencies.md
  lte/cloud/go/services/policydb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/smsd/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
Labels: component: agw, component: cwag

#5575 [SessionD] Activate all rules with PolicyRule definitions
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/c/session_manager/AAAClient.cpp
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/RuleStore.cpp
  lte/gateway/c/session_manager/RuleStore.h
  lte/gateway/c/session_manager/ServiceAction.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/protos/pipelined.proto
Labels: component: agw

#5619 AGW: ubuntu: VM: virtual box clock skew fix
  lte/gateway/Vagrantfile
Labels: component: agw

#5354 [MME] Run Clang-Tidy on master, push results to Spreadsheet
  .circleci/config.yml
  lte/gateway/Makefile
Labels: component: agw

#5623 [Converged-MME]CZMQ and mme-app exit bugfix.
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
Labels: component: agw

#5618 [cloud] [orc8r] Building artifacts for Cloudstrapper
  experimental/cloudstrapper/playbooks/build-configure.yaml
  experimental/cloudstrapper/playbooks/roles/build-platform/tasks/publish-helm.yaml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
Labels: v1.5

#5545 [AGW] Install script using shell in bash
  lte/gateway/deploy/agw_install.sh
Labels: component: agw

#5591 [CI] Add a suite of useful GCC Warning flags
  .github/workflows/gcc-problems.yml
Labels: component: agw

#5529 [CI] Enable c/c++ codecov support
  .circleci/config.yml
  lte/gateway/Makefile
Labels: component: agw

#5626 [lte][agw] Revert ICS message criticality to reject
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: apply-v1.4, component: agw

#5631 [Orc8r] Swagger changes for Restricted IMEIs
  feg/cloud/go/services/feg/obsidian/models/imei_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/plmn_config_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/imei_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/network_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/plmn_config_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw

#5509 [MME] Add a basic spgw-task state_conversion test
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/gateway/c/oai/include/gtpv1u_types.h
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/oai/test/CMakeLists.txt
  lte/gateway/c/oai/test/spgw_task/CMakeLists.txt
  lte/gateway/c/oai/test/spgw_task/state_creators.cpp
  lte/gateway/c/oai/test/spgw_task/state_creators.h
  lte/gateway/c/oai/test/spgw_task/test_spgw_state_converter.cpp
  lte/protos/oai/spgw_state.proto
Labels: component: agw

#5637 [agw][mme] Read back ULR response timer from Redis
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
Labels: apply-v1.4, component: agw

#4803 [Converged-MME]ue_context_modification_timer edit.
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.h
Labels: component: agw

#5414 [AGW][common][sctpd] Add back unit tests in sctpd and magma_common and move some OAI tests to magma_common
  lte/cloud/go/protos/sctpd.pb.go
  lte/gateway/Makefile
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/oai/test/CMakeLists.txt
  lte/gateway/c/oai/test/service303/CMakeLists.txt
  lte/gateway/c/oai/test/service303/Service303Client.cpp
  lte/gateway/c/oai/test/service303/Service303Client.h
  lte/gateway/c/oai/test/service_registry/CMakeLists.txt
  lte/gateway/c/sctpd/test/CMakeLists.txt
  lte/gateway/c/sctpd/test/test_event_handler.cpp
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/protos/sctpd.proto
  orc8r/gateway/c/common/service303/MagmaService.cpp
  orc8r/gateway/c/common/service303/MetricsHelpers.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/test/CMakeLists.txt
  orc8r/gateway/c/common/test/test_magma_service.cpp
  orc8r/gateway/c/common/test/test_metrics.cpp
  orc8r/gateway/c/common/test/test_service303.cpp
  orc8r/gateway/c/common/test/test_service_registry.cpp
  orc8r/gateway/c/common/test/test_yaml_utils.cpp
Labels: component: agw

#5327 [MME] fix hashtable.c potentially undersized key structure
  lte/gateway/c/oai/lib/hashtable/hashtable.c
Labels: component: agw, source:clang-tidy

#5328 [MME] fix hashtable_uint64.c potentially undersized key structure
  lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c
Labels: component: agw, source:clang-tidy

#5329 [MME] Correct mis-sized allocation of grpc_service_data_t
  lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c
Labels: component: agw, source:clang-tidy

#5335 [MME] Fix null pointer dereference in TLVDecoder.c
  lte/gateway/c/oai/common/TLVDecoder.c
Labels: component: agw, source:clang-tidy

#4564 [docs] Update guidance for Docker memory allocation
  docs/readmes/assets/docker-config.png
  docs/readmes/basics/prerequisites.md
Labels: component: agw, component: cwag

#5226 [MME] IWYU applied to test/openflow subdir
  lte/gateway/c/oai/test/openflow/test_gtp_app.cpp
  lte/gateway/c/oai/test/openflow/test_imsi_encoder.cpp
  lte/gateway/c/oai/test/openflow/test_openflow_controller.cpp
Labels: component: agw

#5624 [pipelined]Remove static rule processing from
  feg/gateway/services/aaa/test/pipelined/main.go
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_gy.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
  lte/protos/pipelined.proto
Labels: component: agw

#4256 AGW: s1-integ-test: validate HE envoy config.
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_he.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_he_policy.py
  lte/gateway/python/magma/pipelined/app/he.py
Labels: component: agw, component: cwag

#5646 AGW: mobilityD: handle missing gw config.
  lte/gateway/python/magma/mobilityd/uplink_gw.py
Labels: apply-v1.4, component: agw

#5360 Enable Clang Warning CircleCI analysis for MME
  .circleci/config.yml
  lte/gateway/Makefile
Labels: component: agw

#4804 [Converged-MME]paging_response_timer edit.
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
Labels: component: agw

#5595 AGW: ubuntu: Setup GTP interface files
  lte/gateway/deploy/roles/magma/files/magma_ifaces_gtp
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw

#5596 AGW: ubuntu: Fix resolv.conf link
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw

#5598 AGW: ubuntu: python: patch asyncio
  lte/gateway/deploy/roles/magma/files/patches/aioeventlet.py38.patch
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw

#5599 AGW: ubuntu: ansible: change interface names
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw

#5620 AGW: package: GTP: fix oai-gtp package version.
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
  lte/gateway/release/build-magma.sh
Labels: component: agw

#5597 AGW: ubuntu: dev-vm: fix multipath conf
  lte/gateway/deploy/roles/dev_common/files/patches/multipath-conf.patch
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw

#5650 AGW: fix OVS dependencies for ubuntu package
  lte/gateway/fabfile.py
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma.lockfile
Labels: component: agw

#5647 AGW: package: fix rsyslog config conflict.
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma-postinst
Labels: component: agw

#5678 AGW: python: fix aioeventlet patching
  cwf/gateway/docker/python/Dockerfile
  orc8r/gateway/python/python.mk
Labels: component: cwag

#5680 [AGW]Bump Vagrant VM to 1.1.20210323
  lte/gateway/Vagrantfile
Labels: component: agw

#5438 [MME][DOCKER] Adding support for RHEL8
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  lte/gateway/c/oai/patches/CMake-warnings-not-errors.patch
  lte/gateway/c/oai/patches/czmq-strncat.patch
  lte/gateway/c/oai/patches/folly-gflagslib-fix.patch
  lte/gateway/c/oai/patches/libzmq-strncpy.patch
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/README.md
Labels: component: agw

#5671 [lte][agw] Add missing parts for picking plmn restriction from gateway.mconfig
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/deploy/roles/magma/files/update_mme_config_for_sanity.sh
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw

#5305 Verify Monitoring/Connectiond rules are supported #4560
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_install_internal_conntrack_flow.snapshot
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_traffic.py
Labels: component: agw

#5698 [LTE][integtests] run timeout in the foreground for it to receive CTRL+C
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw
