Repository magma/magma, pull requests merged in 2021-10, with the labels that each got.

#9394 fix(agw): remove fluentbit registry using ansible(hotfix)
  orc8r/tools/ansible/roles/fluent_bit/tasks/main.yml
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, size/S

#9393 fix(feg): Fix for PLMN ID filter issue when IDs with identical prefixes can overwrite each other
  feg/gateway/plmn_filter/plmn_filter.go
  feg/gateway/services/aaa/aaa_server/aaa_aka_auth_test.go
  feg/gateway/services/eap/providers/aka/servicers/service.go
Labels: component: feg

#9390 chore: refactor circleci config for sentry upload so we can add more …
  .circleci/config.yml
Labels: size/M

#9088 feat(agw): add sctp up/downstream sock to mme service config
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/sctp/sctp_defs.h
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/core/oai/tasks/sctp/sctpd_downlink_client.cpp
  lte/gateway/c/core/oai/tasks/sctp/sctpd_uplink_server.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_config.cpp
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw

#9386 fix: Update AGW lte-test step
  .github/workflows/agw-workflow.yml
  lte/ignore-this-file-used-to-trigger-GHA
Labels: component: ci

#9400 ci: points agw-workflow to existing devcontainer image
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/L

#9404 chore: Clean up test file
  lte/ignore-this-file-used-to-trigger-GHA
Labels: size/XS, devops-migration

#9391 fix(ci): Fix issue #8165 Aggregate PR comment on check failure
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/dco-check.yml
  .github/workflows/python-workflow.yml
  .github/workflows/semantic-pr.yml
Labels: component: ci

#9401 fix(ci): packaging agw for ubuntu
  lte/gateway/fabfile.py
Labels: component: agw

#9409 fix(agw): Fix default logging level
  lte/gateway/configs/directoryd.yml
  lte/gateway/configs/state.yml
Labels: component: agw, apply-v1.6

#9399 ci: adds golang support to our devcontainer (e.g. codespaces)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: size/XS

#9416 fix(mme): Replace RETURNerror with RETURNok in timer handlers
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_location_update.c
Labels: component: agw, apply-v1.5, apply-v1.6

#9408 fix(ci): fix name in check PR UI
  .github/workflows/autolabel-pullrequests.yml
Labels: component: ci, size/XS

#9418 fix(mme): Fix default bearer timer expiry handler
  lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
Labels: size/S

#9436 fix(mme): Backport PR9416 for zmq timer handler return fixes
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_location_update.c
Labels: size/M

#9438 fix(agw): backport-v1.6: Fix default logging level (#9409)
  lte/gateway/configs/directoryd.yml
  lte/gateway/configs/state.yml
Labels: size/XS

#9437 docs: update VSCode+Bazel doc to apply to both Remote SSH and devcont…
  experimental/bazel-base/VSCodeBazel.md
Labels: size/XS

#9435 chore: add a new sentry native project
  .circleci/config.yml
Labels: component: ci

#9395 chore(mme): Adding unit test for ULA failure
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/L

#9283 feat(pipelined): Add IPv6 GTP support to OVS
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0001-of-match-expand-NXM_NX_TUN_FLAGS-to-include-all-tunn.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0002-userspace-IPFIX-Add-tunnel-type-GTP.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0003-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0004-ovs-Add-support-to-set-GTP-header-fields.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0005-OVS-gtp-echo-handling.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0006-ovs-test-add-gtp-marker-test.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0007-native-tnl-routing-tunnel-lookup-with-pkt-mark.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0008-fixes-for-2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0009-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0010-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0011-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0012-GTP-Extension-header-support-in-ovs2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0013-ODP-action-Fix-L3-port-to-L3-port-traffic.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0014-datapath-GTP-cleanup.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0015-GTP-handle-seq-number-in-HDR.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0016-datapath-gtp-add-segmentation-offloads.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0017-net-Fix-zero-copy-head-len-calculation.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0018-gtp-Fix-for-sequence-number-length-calculation.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0019-AGW-OVS-handle-gtp-tunnel-type.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0020-datapath-fix-gso-length.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0021-datapath-update-version.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0022-Add-GTP-IPv6-support.patch
Labels: component: agw

#9431 ci: updates session_manager to usexisting devcontainer image
  .github/workflows/agw-workflow.yml
Labels: component: ci

#9439 feat(mme): Add Libfluid TunnelIPv6Dst support
  third_party/build/bin/libfluid_build.sh
  third_party/build/patches/libfluid/libfluid_msg_patches/0001-Add-TunnelIPv4Dst-support.patch
  third_party/build/patches/libfluid/libfluid_msg_patches/0002-Add-support-for-setting-OVS-reg8.patch
  third_party/build/patches/libfluid/libfluid_msg_patches/0003-Add-Reg-field-match-support.patch
  third_party/build/patches/libfluid/libfluid_msg_patches/0004-Add-TunnelIPv6Dst-support.patch
Labels: component: ci, size/L

#9459 ci: bumps devcontainer registry image
  .devcontainer/devcontainer.json
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci

#9377 fix(amf): encoding and decoding functions for MaxSuppPktFilterIe
  lte/gateway/c/core/oai/tasks/nas5g/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GPDUSessionEstablishmentRequest.h
  lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GMaxNumOfSupportedPacketFilters.h
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentRequest.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GMaxNumOfSupportedPacketFilters.cpp
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
Labels: component: agw, product: 5g sa

#9457 fix(mme): migrate to unique_ptr to release allocation on exception
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
Labels: component: agw, size/S

#8449 docs: adding HIL sanity badges
  README.md
  docs/readmes/lte/hil_tests.md
Labels: component: docs

#9463 fix(mme): Bump Libfluid version
  third_party/build/bin/libfluid_build.sh
Labels: component: ci

#9413 chore(agw): cherry-pick Fix python formatting (#9379)
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
Labels: size/L

#9328 feat(s8_proxy): add multiple bearers on Create Bearer request and Delete
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/db.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mb.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/protos/s8_proxy.proto
Labels: component: feg, size/L

#9465 fix(agw): backport-v1.6: restore SGi bridge flows to keep connectivit…
  lte/gateway/deploy/roles/magma/files/magma-bridge-reset.sh
  lte/gateway/deploy/roles/magma/files/ovs-kmod-upgrade.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
  lte/gateway/python/scripts/config_stateless_agw.py
  lte/gateway/release/build-magma.sh
Labels: size/L

#9466 fix(ci): Force destroy locked magma-dev vm
  circleci/fabfile.py
Labels: component: ci, size/XS

#9471 chore(agw): update magma package dependency
  lte/gateway/release/build-magma.sh
Labels: component: ci, size/S

#9444 fix(pipelined): ipv6 neighbor discovery handling.
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/ipv6_solicitation.py
Labels: component: agw

#9475 fix(mme): remove memory leak on migrated esm ebr timer
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c
Labels: component: agw, size/S

#9099 feat(agw): [Non_Sanity] Added missing test case to defs.mk and updated non-sanity
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw

#9485 fix(mme): bug fix for proto_to_guti_table conversion
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c
Labels: component: agw

#9441 feat: add system level bazelrcs to make building easier in various sy…
  .bazelignore
  .bazelrc
  .devcontainer/Dockerfile
  experimental/bazel-base/Dockerfile
  experimental/bazel-base/bazelrcs/devcontainer.bazelrc
  experimental/bazel-base/bazelrcs/docker.bazelrc
  experimental/bazel-base/bazelrcs/vm.bazelrc
  experimental/bazel-base/docker-compose.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  vscode-workspaces/workspace.magma-vm-workspace.code-workspace
Labels: component: agw

#9492 feat(ci): migrate lte integ test to github actions
  .github/workflows/lte-integ-test.yml
Labels: component: ci

#9491 chore: update devcontainer image to sha-6c9b920
  .devcontainer/devcontainer.json
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci

#9976 docs: Add setup and dev guide on VSCode+Magma
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/assets/contributing/sessiond-breakpoint-code.png
  docs/readmes/assets/contributing/sessiond-gdb-list.png
  docs/readmes/assets/contributing/sessiond-start-debug.png
  docs/readmes/assets/contributing/sessiond-unit-test-codelens.png
  docs/readmes/contributing/contribute_onboarding.md
  docs/readmes/contributing/contribute_vscode.md
  experimental/bazel-base/VSCodeBazel.md
  experimental/bazel-base/VSCodeSetup.md
Labels: component: docs

#9967 fix(agw): Compensate for eNB firmware param inversion
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
Labels: component: agw

#9161 feat(orc8r): SubscriberDB Extensions - Updation to Swagger API doc, callback functions, subscriberDB service.
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/load.go
  lte/cloud/go/services/subscriberdb/load_test.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go
  lte/cloud/go/services/subscriberdb/obsidian/models/core_network_types_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/mutable_subscriber_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/subscriber_config_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/subscriber_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb_cache/worker_test.go
  lte/gateway/python/scripts/subscriber_cli.py
  lte/protos/subscriberdb.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: agw, component: nms

#9982 fix(agw): Cherry-pick: Compensate for eNB firmware param inversion (#9967)
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
Labels: size/M

#9968 fix(mme): Handle failed teid update by deactivating default bearer
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
Labels: component: agw, size/M

#9980 docs: add mark jen and remove karthik from id mapping doc
  docs/readmes/contributing/contribute_id_mappings.md
Labels: component: docs

#9988 fix(mme): Backport PR 9968
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
Labels: size/M

#9879 chore(orc8r): added makefile
  orc8r/cloud/docker/Makefile
Labels: component: orc8r

#9929 fix(orc8r): Allow statically assigned IPv6 address.
  lte/cloud/go/services/lte/servicers/provider_servicer_test.go
  lte/cloud/go/services/subscriberdb/load.go
  lte/cloud/go/services/subscriberdb/obsidian/models/subscriber_static_ips_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/subscriberdb/streamer/providers.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r

#9867 fix(orc8r): change sgi_management_iface_ipv6_addr type of CIDR
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r

#9644 chore: update the python precommit script to use an image hosted in G…
  lte/gateway/docker/python-precommit/README.md
  lte/gateway/python/precommit.py
Labels: component: agw, component: ci, size/M
