Repository magma/magma, pull requests merged in 2021-07, with the labels that each got.

#7853 Remove stats display from mme thread
  lte/gateway/c/core/oai/common/mme_default_values.h
  lte/gateway/c/core/oai/include/mme_app_desc.h
  lte/gateway/c/core/oai/include/mme_app_statistics.h
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_statistics.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/L

#7873 test: [ci][dco] Fix DCO check
  .github/workflows/dco-check.yml
Labels: size/S

#7875 test: [ci][dco] Replace GHA dco check
  .github/workflows/dco-check.yml
Labels: size/S

#7877 test: [ci][dco] Rollback dco gha job change
  .github/workflows/dco-check.yml
Labels: size/S

#7732 build(mme): fix perm error in AGW docker build appliance
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, size/XS

#7847 Add debug logging to the service303 thread
  lte/gateway/c/core/oai/common/log.c
  lte/gateway/c/core/oai/common/log.h
  lte/gateway/c/core/oai/include/service303.h
  lte/gateway/c/core/oai/include/service303_messages_types.h
  lte/gateway/c/core/oai/lib/message_utils/service303_message_utils.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/service303/service303.cpp
  lte/gateway/c/core/oai/tasks/service303/service303_mme_stats.c
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
Labels: component: agw, size/M

#7872 docs: Add Orc8r v1.6 upgrade docs
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/upgrade_1_6.md
  docs/readmes/orc8r/upgrade_intro.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
Labels: component: cwag, size/L

#7813 docs: add slack/github id mappings for all magma maintainers
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_id_mappings.md
Labels: size/M

#7883 chore: add a link to GitHub to Slack ID mappings in PR message
  .github/workflows/pr_bot.yml
Labels: size/XS

#7809 Periodic Registration fixes and timer changes
  lte/gateway/c/oai/common/conversions.c
  lte/gateway/c/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_defs.h
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_timer_management.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_timer_management.h
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/oai/tasks/amf/amf_cn.cpp
  lte/gateway/c/oai/tasks/amf/amf_data.cpp
  lte/gateway/c/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/oai/tasks/nas5g/include/M5GSecurityModeCommand.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GMMCause.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GNASKeySetIdentifier.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf_handlers.c
Labels: component: agw, size/XXL

#7887 [AGW]Bump master to 1.6 installation
  lte/gateway/deploy/agw_install_ubuntu.sh
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, size/S

#7890 [AGW]Make sure we don't install 1.6.0 on debian
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, component: cwag, size/XS

#7885 feat(agw): enable GTP-U echo response.
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
Labels: component: agw, size/XS

#7892 fix(agw): v1.6 AGW should not make sub_sync request
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
Labels: component: agw, component: cwag, size/M

#7836 [feg] feg add commit info on docker image envars
  .circleci/config.yml
  feg/gateway/docker/build.py
  feg/gateway/docker/go/Dockerfile
  feg/gateway/docker/python/Dockerfile
  feg/gateway/docker/tools/get_version_info.sh
  orc8r/gateway/python/scripts/show_gateway_info.py
Labels: size/L

#7889 test: Fix ami marketplace pipeline
  .circleci/config.yml
  experimental/cloudstrapper/playbooks/ami-configure.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw/tasks/agw-setup.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw/tasks/magma-setup.yaml
Labels: size/S

#7893 [Orc8r] Fix the certifier service to register the prometheus gauge
  orc8r/cloud/configs/certifier.yml
  orc8r/cloud/go/services/certifier/analytics/analytics.go
  orc8r/cloud/go/services/certifier/analytics/calculations/lifespan.go
Labels: apply-v1.6, size/M

#7901 [lte][agw] Fix itti message construction with correct apn size
  lte/gateway/c/core/oai/lib/s6a_proxy/proto_msg_to_itti_msg.cpp
Labels: apply-v1.5, apply-v1.6, component: agw, size/S

#7888 feat(agw): ovs: Simplify GTP echo configuration.
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0001-of-match-expand-NXM_NX_TUN_FLAGS-to-include-all-tunn.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0002-userspace-IPFIX-Add-tunnel-type-GTP.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0003-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0004-ovs-Add-support-to-set-GTP-header-fields.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0005-OVS-gtp-echo-handling.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0006-ovs-test-add-gtp-marker-test.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0007-datapath-Fixes-for-4.9-kernel.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0008-ovs-datapath-enable-kernel-5.6.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0009-AGW-OVS-handle-gtp-tunnel-type.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0010-native-tnl-routing-tunnel-lookup-with-pkt-mark.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0011-fixes-for-2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0012-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0013-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0014-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0015-GTP-Extension-header-support-in-ovs2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0016-ODP-action-Fix-L3-port-to-L3-port-traffic.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0017-datapath-GTP-cleanup.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0018-GTP-handle-seq-number-in-HDR.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0019-datapath-gtp-add-segmentation-offloads.patch
Labels: component: agw, size/L

#7833 fix(mme) removed a few compilation warnings
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_reset.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: component: agw, size/M

#7884 fix(ci): master sentry release version to be 1.7.0
  .circleci/config.yml
Labels: size/XS

#7903 [bug fix][lte][agw] Removed Fatal from emergency attach handling
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_cn.c
Labels: apply-v1.5, apply-v1.6, component: agw, size/XS

#7715 ci(agw): Filter lte/gateway/c code coverage
  .circleci/config.yml
  lte/gateway/Makefile
Labels: component: agw, size/S

#7911 refactor: remove snake case naming from test methods
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
Labels: component: agw, ready2merge, size/M

#7906 fix(enodebd): Add workaround logic for stale msg name in dictionary
  lte/gateway/python/magma/enodebd/data_models/transform_for_magma.py
  lte/gateway/python/magma/enodebd/tr069/spyne_mods.py
Labels: component: agw, ready2merge, size/S

#7641 [NMS]Federation Network: Network page - Displaying Network information
  nms/app/packages/magmalte/app/components/context/FEGNetworkContext.js
  nms/app/packages/magmalte/app/components/feg/FEGContext.js
  nms/app/packages/magmalte/app/components/feg/FEGSections.js
  nms/app/packages/magmalte/app/components/layout/__tests__/useSections-test.js
  nms/app/packages/magmalte/app/components/main/Index.js
  nms/app/packages/magmalte/app/state/feg/NetworkState.js
  nms/app/packages/magmalte/app/views/network/FEGNetworkDashboard.js
  nms/app/packages/magmalte/app/views/network/FEGNetworkInfo.js
  nms/app/packages/magmalte/app/views/network/__tests__/NetworkTest.js
Labels: size/L

#7894 Variable Poll Stats Interval
  cwf/gateway/configs/sessiond.yml
  cwf/gateway/integ_tests/sessiond.yml
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/configs/sessiond.yml
  lte/gateway/configs/sessiond.yml_prod
Labels: component: agw, component: cwag, size/S

#7878 docs: add 1.6 AGW upgrade docs
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/lte/deploy_install.md
  docs/readmes/lte/deploy_install_ubuntu.md
  docs/readmes/lte/upgrade_1_6.md
Labels: size/L

#7918 test(agw): New s1sim TC to test GUTI attach with mtmsi value 0
  lte/gateway/python/integ_tests/s1aptests/test_guti_attach_with_zero_mtmsi.py
Labels: component: agw, size/L

#7925 [docs] Minor updates in 1.6 docs
  docs/readmes/basics/prerequisites.md
  docs/readmes/orc8r/deploy_build.md
Labels: size/S

#7927 [lte][agw] Add service area restriction documentation
  docs/readmes/lte/access_service_restrictions.md
Labels: size/L

#7928 docs: Tidy up docs before v1.6 cut
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/basics/prerequisites.md
  docs/readmes/feg/debug_cli.md
  docs/readmes/feg/deploy_configure.md
  docs/readmes/lte/configure_sentry.md
  docs/readmes/lte/ha_setup.md
  docs/readmes/nms/deploy_setup.md
  docs/readmes/nms/metrics.md
  docs/readmes/orc8r/configure_thanos.md
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/deploy_orcl.md
  docs/readmes/orc8r/deploy_terraform_options.md
  docs/readmes/orc8r/dev_build.md
  docs/readmes/orc8r/dev_minikube.md
  docs/readmes/orc8r/hold_terraform_state_on_s3.md
  docs/readmes/orc8r/override_values_of_terraform_files.md
Labels: size/L

#7356 Support UPF Paging request#7220
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/MobilitydClient.cpp
  lte/gateway/c/session_manager/MobilitydClient.h
  lte/gateway/c/session_manager/SessionManagerServer.cpp
  lte/gateway/c/session_manager/SessionManagerServer.h
  lte/gateway/c/session_manager/UpfMsgManageHandler.cpp
  lte/gateway/c/session_manager/UpfMsgManageHandler.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/protos/session_manager.proto
Labels: component: agw, product: 5g sa, ready2merge, size/L

#7920 Pull Stats Model Config
  cwf/gateway/configs/sessiond.yml
  cwf/gateway/integ_tests/sessiond.yml
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/configs/sessiond.yml
  lte/gateway/configs/sessiond.yml_prod
Labels: component: agw, component: cwag, size/M

#7815 refactor(sessiond): move events and update report callback into LocalEnforcer from LocalSessionManagerHandler
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
Labels: component: agw, size/L

#7810 Create subscriberdb_cache logic to register per subscriber digests
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/const.go
  lte/cloud/go/services/subscriberdb/digest.go
  lte/cloud/go/services/subscriberdb/digest_test.go
  lte/cloud/go/services/subscriberdb/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/protos/subscriberdb.proto
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/storage/digest.go
  lte/cloud/go/services/subscriberdb/storage/digest_test.go
  lte/cloud/go/services/subscriberdb/storage/per_sub_digest.go
  lte/cloud/go/services/subscriberdb/storage/per_sub_digest_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/subscriberdb_cache/main.go
  lte/cloud/go/services/subscriberdb_cache/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/worker.go
  lte/cloud/go/services/subscriberdb_cache/worker_test.go
  lte/protos/subscriberdb.proto
Labels: component: agw, size/XXL

#7642 [NMS] Full Network page: Including Servicing Access Gateway Table
  nms/app/packages/magmalte/app/components/GatewayUtils.js
  nms/app/packages/magmalte/app/views/network/FEGNetworkDashboard.js
  nms/app/packages/magmalte/app/views/network/FEGServicingAccessGatewayTable.js
  nms/app/packages/magmalte/app/views/network/__tests__/FEGServicingAccessGatewayTableTest.js
Labels: size/L

#7929 docs(agw): Adding Ubuntu AGW migration guide
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/lte/upgrade_debian_to_ubuntu.md
Labels: size/M

#7921 refactor(pipelined): Enforcement Rule Removal Sessiond<->Pipelined
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
Labels: component: agw, size/XS

#7915 [orc8r] add swagger per service health status
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.sum
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers_test.go
  feg/cloud/go/services/feg/obsidian/models/conversion.go
  feg/cloud/go/services/feg/obsidian/models/federation_gateway_health_status_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/service_status_health_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  feg/gateway/go.mod
  feg/gateway/go.sum
  orc8r/cloud/go/obsidian/swagger/v1/models/federation_gateway_health_status.go
  orc8r/cloud/go/obsidian/swagger/v1/models/service_status_health.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/test/go.mod
  orc8r/cloud/test/go.sum
Labels: component: agw, component: cwag, size/L

#7700 [NMS] Equipment dashboard: Federation Gateway Check in chart
  nms/app/packages/magmalte/app/components/feg/FEGSections.js
  nms/app/packages/magmalte/app/components/layout/__tests__/useSections-test.js
  nms/app/packages/magmalte/app/views/equipment/FEGEquipmentDashboard.js
  nms/app/packages/magmalte/app/views/equipment/FEGEquipmentGateway.js
Labels: size/L

#7868 [mme] refactor: Change many func signatures to void, Fatal on unimpl
  lte/gateway/c/core/oai/include/service303.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_common_ies.c
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_sm_ies.c
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.h
  lte/gateway/c/core/oai/lib/mobility_client/MobilityServiceClient.cpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityServiceClient.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h
  lte/gateway/c/core/oai/tasks/nas/ies/AdditionalUpdateType.c
  lte/gateway/c/core/oai/tasks/nas/ies/EpsBearerIdentity.c
  lte/gateway/c/core/oai/tasks/nas/ies/EpsBearerIdentity.h
  lte/gateway/c/core/oai/tasks/nas/ies/MessageType.c
  lte/gateway/c/core/oai/tasks/nas/ies/MobileStationClassmark3.c
  lte/gateway/c/core/oai/tasks/nas/ies/ProcedureTransactionIdentity.c
  lte/gateway/c/core/oai/tasks/nas/ies/ProtocolDiscriminator.c
  lte/gateway/c/core/oai/tasks/nas/ies/SecurityHeaderType.c
  lte/gateway/c/core/oai/tasks/nas/ies/TrafficFlowAggregateDescription.c
  lte/gateway/c/core/oai/tasks/nas/ies/TransactionIdentifier.c
  lte/gateway/c/core/oai/tasks/nas/ies/TransactionIdentifier.h
  lte/gateway/c/core/oai/tasks/sgw/mobilityd_ue_ip_address_alloc.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_ue_ip_address_alloc.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/udp/udp_primitives_server.c
  lte/gateway/c/session_manager/SentryWrappers.cpp
Labels: component: agw, size/L

#7949 docs(ci): Document semantic commit requirement
  .github/PULL_REQUEST_TEMPLATE.md
  .github/semantic.yml
  docs/readmes/contributing/contribute_commit_msg.md
  docs/readmes/contributing/contribute_workflow.md
Labels: size/L

#7895 refactor(sessiond): refactor local create session request handling logic
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/SentryWrappers.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: component: agw, component: cwag, size/L

#7950 fix(ci): point mme_test job determinator to check c/core not c/oai
  .circleci/config.yml
Labels: size/XS

#7886 feat(orc8r): Create SyncSubscribers logic for subscriberdb servicer
  lte/cloud/configs/subscriberdb.yml
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/config.go
  lte/cloud/go/services/subscriberdb/digest.go
  lte/cloud/go/services/subscriberdb/digest_test.go
  lte/cloud/go/services/subscriberdb/load.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/worker.go
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
  lte/protos/subscriberdb.proto
Labels: component: agw, component: orc8r, size/XL

#7952 fix(mme): Stop timer in right service303 thread
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
Labels: apply-v1.6, component: agw, size/XS

#7916 fix(mme): Fix for handling unknown GUTI attach
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.h
  lte/gateway/c/core/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
Labels: component: agw, size/L

#7905 refactor: [ci] dco pr comment job
  .github/workflows/dco-check.yml
  .github/workflows/dco-comment-pr.yml
Labels: size/M

#7975 refactor(sessiond): Fix threading issues in sessiond
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, size/S

#7980 fix(mme): add config flag to control GTP-U echo
  lte/gateway/c/core/oai/include/sgw_config.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
Labels: component: agw, size/S

#7664 feat: make `subscriberdb_sync_interval` a network-wide orc8r-pushed config item
  feg/cloud/go/services/feg/obsidian/models/subscriberdb_sync_interval_swaggergen.go
  lte/cloud/configs/lte.yml
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/config.go
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/defaults.go
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/network_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/subscriberdb_sync_interval_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/cloud/go/services/lte/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb/config.go
  lte/cloud/go/services/subscriberdb/const.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/go/obsidian/swagger/v1/models/gateway_epc_configs.go
  orc8r/cloud/go/obsidian/swagger/v1/models/network_epc_configs.go
  orc8r/cloud/go/obsidian/swagger/v1/models/subscriberdb_sync_interval.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/lib/go/service/config/service_config.go
Labels: component: agw, component: cwag, ready2merge, size/XL

#7986 fix(orc8r): [tracing] Context propagation for all modules
  fbinternal/cloud/go/services/testcontroller/e2e_client_api.go
  fbinternal/cloud/go/services/testcontroller/node_client_api.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/node_handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/node_handlers_test.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers_test.go
  fbinternal/cloud/go/services/vpnservice/client_api.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/feg_connection.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/feg_discovery.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/gw_to_feg_relay.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/relay_test.go
  feg/cloud/go/services/health/client_api.go
  feg/cloud/go/services/health/client_api_test.go
  feg/cloud/go/services/health/reporter/network_health_reporter.go
  feg/cloud/go/tools/health_cli/main.go
  lte/cloud/go/services/ha/servicers/servicer.go
  lte/cloud/go/services/ha/servicers/servicer_test.go
  lte/cloud/go/services/lte/client_api.go
  lte/cloud/go/services/lte/servicers/indexer_servicer.go
  lte/cloud/go/services/lte/servicers/indexer_servicer_test.go
  lte/cloud/go/services/subscriberdb/client_api.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/servicers/indexer_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/indexer_servicer_test.go
Labels: component: agw, size/L

#7334 feat(agw): SMF is to handle PDU Session Release request from AMF#7216
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: component: agw, product: 5g sa, size/L

#7904 test(sessiond): Write Unit Test for Polling Pipelined
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/StatsPoller.cpp
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/gateway/c/session_manager/test/test_polling_pipelined.cpp
Labels: component: agw, ready2merge, size/L

#7762 refactor: [ci] Put all helm dependency checks into one check
  .github/workflows/helm-chart-dependency-check.yml
Labels: size/M

#7996 fix(ci): add feg services and alphabetize semantics.yml
  .github/semantic.yml
Labels: size/M

#7843 docs(agw): Update troubleshooting agw unable to checkin
  docs/docusaurus/versioned_docs/version-1.5.0/howtos/troubleshooting/agw_unable_to_checkin.md
  docs/readmes/howtos/troubleshooting/agw_unable_to_checkin.md
Labels: ready2merge, size/M

#7998 fix(cloud): Upgrading Cloudstrapper for v1.6
  experimental/cloudstrapper/playbooks/roles/build-platform/vars/main.yaml
Labels: size/XS

#7999 fix(agw): Add 10.0.2.3 in resolv conf for Virtualbox VMs
  lte/gateway/deploy/roles/dev_common/files/magma_resolv.conf
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/XS

#7941 fix(mme): Fix for mme crash observed in test_3495_timer_for_defa…
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_procedures.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.h
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_default_bearer_with_mme_restart.py
  lte/protos/oai/nas_state.proto
Labels: component: agw, component: cwag, size/XL

#7926 fix(mme): Rsarwad fix guti stale entries (#7721)
  lte/gateway/c/oai/include/mme_app_ue_context.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/ServiceRequestHdl.c
  lte/gateway/c/oai/tasks/nas/emm/TrackingAreaUpdate.c
Labels: component: agw, component: cwag, size/L

#7947 test(agw): Adding s1sim TC to test GUTI attach with mtmsi value 0 (#7918)
  lte/gateway/python/integ_tests/s1aptests/test_guti_attach_with_zero_mtmsi.py
Labels: component: agw, component: cwag, size/L

#7985 fix(mme): [S1 handover] fix bugs in security context for HandoverRequest Msg
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw, ready2merge, size/M

#8002 fix(feg): (s8_proxy) bump gtp-go to 0.7.26
  .github/semantic.yml
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  docs/docusaurus/versioned_docs/version-1.5.0/howtos/inbound_roaming.md
  docs/readmes/howtos/inbound_roaming.md
  feg/gateway/go.mod
  feg/gateway/go.sum
Labels: component: cwag, size/XS

#7987 fix(mme): fix compilation warning
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
Labels: component: agw, size/XS

#7463 feat(agw): Handling UE_SERVICE_REQUEST_ON_PAGING (Idle state to Active state) in SMF
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.h
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: component: agw, product: 5g sa, size/L

#7880 test(agw): New s1ap testcases to test concurrent pdn sessions
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_concurrent_secondary_pdn_reject.py
  lte/gateway/python/integ_tests/s1aptests/test_concurrent_secondary_pdns.py
Labels: component: agw, size/L

#8007 Handle attach with unknown GUTI
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/EmmCommon.c
  lte/gateway/c/oai/tasks/nas/emm/EmmCommon.h
  lte/gateway/c/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/oai/tasks/nas/emm/emm_data_ctx.c
Labels: component: agw, component: cwag, size/L

#8004 fix(ci): update the bot msg to include Semantic Pull Request check
  .github/workflows/pr_bot.yml
Labels: size/XS

#7960 refactor(ci): Rotate versions in helm test repo
  .github/workflows/publish-helmcharts-to-artifactory.yml
  ci-scripts/helm_repo_rotation.py
Labels: size/L

#7997 fix(pipelined): avoid cleaning up uplink-br0 in stateless mode.
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: component: agw, size/XS

#7962 feat(agw): enable GTP-U echo response
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/XS

#7855 refactor(feg): (s8_proxy) split createBearerRequest into request and response
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
  feg/cloud/go/services/feg_relay/servicers/create_bearer_pgw.go
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/gtp/session_manager.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/gw_s8_client_api.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_feg_relay/mock_feg_relay.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cb.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/gateway/services/s8_proxy/servicers/tft_proto_conversion.go
  feg/protos/s8_proxy.proto
Labels: component: agw, component: cwag, size/XL

#7946 perf(agw): set proportional memory limit to the total
  lte/gateway/deploy/roles/magma/files/systemd/magma_mme.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_sessiond.service
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, size/XS

#6372 refactor: Add cloud GitHub Actions Workflow
  .github/workflows/cloud-workflow.yml
  .github/workflows/unit-test-workflow.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/run_deployer.bash
Labels: devops-migration, size/L

#7841 feat(agw): Add commands and logs in show-tech playbook
  docs/docusaurus/versioned_docs/version-1.4.0/debugging_tools/show_tech.md
  docs/docusaurus/versioned_docs/version-1.5.0/lte/debug_show_tech.md
  docs/readmes/lte/debug_show_tech.md
  show-tech/constants.yml
Labels: ready2merge, size/S

#6515 feat(orc8r): add terraform support of nprobe service
  lte/cloud/configs/nprobe.yml
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/nprobe/config.go
  lte/cloud/go/services/nprobe/encoding/asn1.go
  lte/cloud/go/services/nprobe/encoding/asn1_test.go
  lte/cloud/go/services/nprobe/encoding/const.go
  lte/cloud/go/services/nprobe/encoding/record.go
  lte/cloud/go/services/nprobe/encoding/record_test.go
  lte/cloud/go/services/nprobe/encoding/testdata/gen_time_encoded.golden
  lte/cloud/go/services/nprobe/encoding/testdata/payload_asn1.golden
  lte/cloud/go/services/nprobe/encoding/testdata/record_encoded.golden
  lte/cloud/go/services/nprobe/encoding/utils.go
  lte/cloud/go/services/nprobe/exporter/exporter.go
  lte/cloud/go/services/nprobe/nprobe/main.go
  lte/cloud/go/services/nprobe/nprobe_manager/nprobe_manager.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_destination_details_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_task_details_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/swagger.v1.yml
  lte/cloud/helm/lte-orc8r/templates/nprobe.deployment.yaml
  lte/cloud/helm/lte-orc8r/templates/nprobe.pdb.yaml
  lte/cloud/helm/lte-orc8r/templates/nprobe.service.yaml
  lte/cloud/helm/lte-orc8r/values.yaml
  orc8r/cloud/go/obsidian/swagger/v1/models/network_probe_destination_details.go
  orc8r/cloud/go/obsidian/swagger/v1/models/network_probe_task_details.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, ready2merge, size/XL

#8025 fix(mme): Make stats collection and display configurable
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/include/service303.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw

#7993 refactor(sessiond): Remove atomic field
  lte/gateway/c/session_manager/StatsPoller.cpp
  lte/gateway/c/session_manager/StatsPoller.h
Labels: component: agw, size/S

#7966 fix(agw): swap python package json-pointer with jsonpointer
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile.ubuntu
  lte/gateway/release/pydep
  orc8r/gateway/python/setup.py
Labels: component: agw, size/M

#7786 feat(mme): N11 interface changes and session_manager.proto
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/core/oai/include/amf_service_handler.h
  lte/gateway/c/core/oai/include/n11_messages_def.h
  lte/gateway/c/core/oai/include/n11_messages_types.h
  lte/gateway/c/core/oai/lib/n11/CMakeLists.txt
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.h
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/test/CMakeLists.txt
  lte/gateway/c/core/oai/test/n11/CMakeLists.txt
  lte/gateway/c/core/oai/test/n11/test_n11.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/protos/session_manager.proto
Labels: component: agw, product: 5g sa, size/XXL

#8041 fix: Fix secret for slack channel
  .github/workflows/cloud-workflow.yml
Labels: devops-migration

#6370 refactor: Add feg GitHub Actions Workflow
  .github/workflows/feg-workflow.yml
  .github/workflows/unit-test-workflow.yml
Labels: devops-migration, size/L

#8006 docs(agw): Fix incorrect command for AGW upgrade script
  docs/docusaurus/versioned_docs/version-1.5.0/lte/upgrade_1_5.md
  docs/docusaurus/versioned_docs/version-1.6.0/lte/upgrade_1_5.md
  docs/docusaurus/versioned_docs/version-1.6.0/lte/upgrade_1_6.md
  docs/readmes/lte/upgrade_1_5.md
  docs/readmes/lte/upgrade_1_6.md
Labels: size/S

#8029 fix(agw): Fixed memory leaks during execution of s1ap sanity test suite
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
Labels: apply-v1.5, apply-v1.6, component: agw

#8045 [component: agw]: Periodic Registration fixes
  lte/gateway/c/oai/common/amf_default_values.h
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/oai/tasks/amf/amf_config.c
  lte/gateway/c/oai/tasks/amf/amf_fsm.cpp
  lte/gateway/c/oai/tasks/amf/amf_fsm.h
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.h
  lte/gateway/c/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GSRegistrationResult.h
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GSRegistrationResult.cpp
  lte/gateway/c/oai/test/ngap/test_ngap.cpp
Labels: component: agw

#8046 fix(mme): Send UE ctx release cmd to the source eNB after S1 Handover
  lte/gateway/c/core/oai/include/s1ap_types.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw

#8117 fix: Fix slack color on success
  .github/workflows/cloud-workflow.yml
  .github/workflows/feg-workflow.yml
Labels: devops-migration

#6371 refactor: Add cwf GitHub Actions Workflow
  .github/workflows/cwf-operator.yml
  .github/workflows/unit-test-workflow.yml
Labels: devops-migration, size/L

#7628 feat(ci): enable python formatting checks for all python files
  .github/workflows/python-formatting-check.yml
Labels: size/XS

#7979 test: [ci] Add PR comment on python format check failure
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/python-formatting-check.yml
Labels: size/M

#7719 refactor(agw): move sync interval randomization from agw to orc8r
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/subscriberdb/main.py
Labels: component: agw, size/M

#7851 perf(pipelined): Avoid service reatart on bridge reconfigure
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, size/S

#7983 fix(agw): Process subscriber data before digest data
  lte/gateway/python/magma/subscriberdb/client.py
Labels: apply-v1.6, component: agw, component: cwag, size/XS

#8136 fix(agw): set mim memory limit for lower memory AGW setup.
  lte/gateway/deploy/roles/magma/files/systemd/magma_mme.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_sessiond.service
Labels: component: agw

#8011 refactor(sessiond): remove unused includes and flatten directory
  feg/gateway/go.sum
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/ObjectMap.h
  lte/gateway/c/session_manager/PolicyLoader.cpp
  lte/gateway/c/session_manager/PolicyLoader.h
  lte/gateway/c/session_manager/RedisMap.hpp
  lte/gateway/c/session_manager/RedisStoreClient.cpp
  lte/gateway/c/session_manager/SentryWrappers.cpp
  lte/gateway/c/session_manager/Serializers.cpp
  lte/gateway/c/session_manager/Serializers.h
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/StatsPoller.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/datastore/CMakeLists.txt
  lte/gateway/c/session_manager/policydb/CMakeLists.txt
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw

#8141 fix(agw): stop/start swap during provisioning to prevent error
  lte/gateway/Vagrantfile
Labels: component: agw

#8144 fix(agw): Added code to correct the grpc encoding format of msisdn within ue_context
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/protos/oai/mme_nas_state.proto
Labels: component: agw

#7192 refactor: [helm][docker][orc8r][REGISTRY] Map code to new registry for helm & Docker
  cwf/gateway/docker/.env
  cwf/gateway/docker/.prod_env
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.custom
  feg/gateway/docker/.env
  feg/gateway/docker/.prod_env
  orc8r/cloud/deploy/terraform/orc8r-aws/eks.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/artifactory.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/online-upgrade/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/gateway/python/magma/magmad/upgrade/docker_upgrader.py
  orc8r/tools/ansible/roles/docker/tasks/main.yml
Labels: component: ci, component: cwag, ready2merge, size/L

#7923 feat(agw): Adapt subscriberdb agw client to make SyncSubscribers calls
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/store/base.py
  lte/gateway/python/magma/subscriberdb/store/cached_store.py
  lte/gateway/python/magma/subscriberdb/store/onready.py
  lte/gateway/python/magma/subscriberdb/store/sqlite.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
  lte/gateway/python/magma/subscriberdb/tests/store/cached_store_tests.py
  lte/gateway/python/magma/subscriberdb/tests/store/onready_test.py
  lte/gateway/python/magma/subscriberdb/tests/store/store_tests.py
Labels: component: agw, size/XL

#8153 fix(enodebd): Fixing clear_stats function traversal of stats dictionary
  lte/gateway/python/magma/enodebd/stats_manager.py
  lte/gateway/python/magma/enodebd/tests/stats_manager_tests.py
Labels: component: agw

#8142 fix(agw): fix warning message on ansible when provisioning magma due to `atom-box` format
  lte/gateway/deploy/hosts
Labels: component: agw

#8160 fix: Fix cwf integ test
  cwf/gateway/docker/.env
  feg/gateway/docker/.env
Labels: component: agw, component: cwag

#8154 fix(mme): Extended pr7912 that added lbi to OAI CUPS path
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include/NwGtpv2c.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include/NwGtpv2cPrivate.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/src/NwGtpv2c.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/core/oai/tasks/s11/s11_mme_session_manager.c
Labels: component: agw

#8163 fix: [ci] Reverting changes to make integ test passes
  cwf/gateway/docker/.env
  feg/gateway/docker/.env
Labels: component: agw, component: cwag

#8169 fix(agw): on AGW reboot bring up SGi interface.
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: component: agw

#8122 refactor(mme): Change many func signatures to void, Fatal on unimpl
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_common_ies.c
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_sm_ies.c
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.h
  lte/gateway/c/core/oai/lib/mobility_client/MobilityServiceClient.cpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityServiceClient.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h
  lte/gateway/c/core/oai/tasks/nas/ies/AdditionalUpdateType.c
  lte/gateway/c/core/oai/tasks/nas/ies/EpsBearerIdentity.c
  lte/gateway/c/core/oai/tasks/nas/ies/EpsBearerIdentity.h
  lte/gateway/c/core/oai/tasks/nas/ies/MessageType.c
  lte/gateway/c/core/oai/tasks/nas/ies/MobileStationClassmark3.c
  lte/gateway/c/core/oai/tasks/nas/ies/ProcedureTransactionIdentity.c
  lte/gateway/c/core/oai/tasks/nas/ies/ProtocolDiscriminator.c
  lte/gateway/c/core/oai/tasks/nas/ies/SecurityHeaderType.c
  lte/gateway/c/core/oai/tasks/nas/ies/TrafficFlowAggregateDescription.c
  lte/gateway/c/core/oai/tasks/nas/ies/TransactionIdentifier.c
  lte/gateway/c/core/oai/tasks/nas/ies/TransactionIdentifier.h
  lte/gateway/c/core/oai/tasks/sgw/mobilityd_ue_ip_address_alloc.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_ue_ip_address_alloc.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/udp/udp_primitives_server.c
  lte/gateway/c/core/oai/test/mobility_client/test_mobility_client.cpp
Labels: component: agw

#7402 refactor: Add cwag GitHub Actions Workflow
  .github/workflows/cwag-workflow.yml
Labels: devops-migration, size/L

#8000 refactor(agw): remove leftover dependency lists and doc refs for Debian
  .circleci/config.yml
  docs/readmes/howtos/README_package.md
  lte/gateway/python/setup.py
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma.lockfile.debian
  orc8r/gateway/python/setup.py
Labels: component: agw, ready2merge, size/XXL

#8132 refactor: [ci] Refactor semantic PR check
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/pr_bot.yml
  .github/workflows/semantic-pr.yml
Labels: component: ci

#8044 feat(orc8r): Implement logic for caching subscriber protos
  lte/cloud/configs/subscriberdb.yml
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/config.go
  lte/cloud/go/services/subscriberdb/load.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/storage/digest.go
  lte/cloud/go/services/subscriberdb/storage/per_sub_digest.go
  lte/cloud/go/services/subscriberdb/storage/subscribers.go
  lte/cloud/go/services/subscriberdb/storage/subscribers_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/subscriberdb_cache/main.go
  lte/cloud/go/services/subscriberdb_cache/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/worker.go
  lte/cloud/go/services/subscriberdb_cache/worker_test.go
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
  lte/protos/subscriberdb.proto
  orc8r/cloud/go/services/configurator/storage/sql_entity_load_helpers.go
  orc8r/cloud/go/sqorc/builder.go
Labels: component: agw, component: orc8r

#8205 feat(pipelined): Use future for poll stats retrieval
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
Labels: component: agw

#8191 docs(orc8r): Add docusaurus documentation on the subscriber digests pattern
  docs/docusaurus/sidebars.json
  docs/readmes/assets/orc8r/subscriber_digests_architecture.png
  docs/readmes/orc8r/dev_sub_digests.md
Labels: component: docs

#8192 refactor(orc8r): [orc8r][ci] Add git status output to slack failing notification
  .github/workflows/cloud-workflow.yml
Labels: component: ci, ready2merge

#8143 feat(mme): use sentry_config sent down as mme config
  lte/gateway/c/core/oai/common/sentry_wrapper.cpp
  lte/gateway/c/core/oai/common/sentry_wrapper.h
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw

#8232 fix: Revert deletion of lockfile still used in integration tests
  lte/gateway/release/magma.lockfile.debian
Labels: component: agw, size/XXL

#8051 feat(subscriberdb): Support for new 5G authentication vectors
  lte/cloud/go/protos/subscriberauth.pb.go
  lte/gateway/python/magma/subscriberdb/crypto/lte.py
  lte/gateway/python/magma/subscriberdb/crypto/milenage.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/metrics.py
  lte/gateway/python/magma/subscriberdb/processor.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/tests/crypto/milenage_tests.py
  lte/gateway/python/magma/subscriberdb/tests/processor_tests.py
  lte/protos/subscriberauth.proto
Labels: component: agw, product: 5g sa, type: feature

#8228 fix: Add docker retry in cwag-deploy
  .github/workflows/cwag-workflow.yml
Labels: devops-migration

#8238 chore(ci): Fix mismatched periods in PR comments
  .github/workflows/comment-pr-on-check-failure.yml
Labels: size/XS

#7804 feat(nms): Equipment dashboard Federation Gateway Table
  nms/app/packages/magmalte/app/components/GatewayUtils.js
  nms/app/packages/magmalte/app/components/context/FEGGatewayContext.js
  nms/app/packages/magmalte/app/components/context/RefreshContext.js
  nms/app/packages/magmalte/app/components/feg/FEGContext.js
  nms/app/packages/magmalte/app/state/feg/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/FEGEquipmentGateway.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayTable.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/FEGEquipmentGatewayTest.js
  nms/app/packages/magmalte/app/views/network/FEGServicingAccessGatewayTable.js
Labels: size/XXL

#8227 docs: Add CWF related testing docs
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_ci_checks.md
  docs/readmes/contributing/contribute_id_mappings.md
  docs/readmes/cwf/deploy_build.md
  docs/readmes/cwf/dev_testing.md
  docs/readmes/lte/dev_unit_testing.md
Labels: size/L

#8247 docs: Add testing instructions for orc8r/gateway/go
  docs/readmes/contributing/contribute_ci_checks.md
  docs/readmes/lte/dev_unit_testing.md
Labels: size/S

#8229 fix(mobilityd): Fixing mconfig reload of IP block allocation
  lte/gateway/python/magma/mobilityd/ip_allocator_pool.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/main.py
Labels: component: agw, size/M

#8145 chore(orc8r): bump docker-compose to 1.29.1 on ansible role and other install scripts
  cwf/gateway/helm/cwf-kubevirt/templates/bin/_install_gateway.sh.tpl
  cwf/gateway/helm/cwf-virtlet/templates/bin/_install_gateway.sh.tpl
  feg/gateway/helm/feg-kubevirt/templates/bin/_install_gateway.sh.tpl
  feg/gateway/helm/feg-virtlet/templates/bin/_install_gateway.sh.tpl
  orc8r/tools/ansible/roles/docker/defaults/main.yml
  orc8r/tools/docker/install_gateway.sh
Labels: component: cwag

#8239 chore(ci): Store SwaggerHub account info to sops
  secrets/ci.yaml
Labels: size/S

#8237 chore: [ci] Get rid of xwfm test as github action runner are too small
  .github/workflows/cwag-workflow.yml
Labels: size/M

#8250 chore(docs): Add link to current proposal process
  docs/docusaurus/versioned_docs/version-1.5.0/proposals/p014_proposal_process.md
  docs/readmes/proposals/p014_proposal_process.md
Labels: size/XS

#8231 ci(orc8r): Connect Docusaurus to SwaggerHub API
  .github/workflows/cloud-workflow.yml
  docs/docusaurus/sidebars.json
  docs/readmes/assets/orc8r/swaggerhub-rest-api.png
  docs/readmes/orc8r/architecture_overview.md
  docs/readmes/orc8r/dev_rest_api.md
  docs/readmes/orc8r/dev_sub_digests.md
Labels: component: ci, size/M

#8248 docs: add instructions for using Orc8r-based Sentry config.
  docs/readmes/lte/configure_sentry.md
Labels: size/XS

#8254 docs: Fix formatting on CI table
  docs/docusaurus/i18n/en.json
  docs/readmes/contributing/contribute_ci_checks.md
Labels: size/XS

#8235 feat(pipelined): Pipelined side for polling shards
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_cookie_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_deny_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_pull_stats.PullStatsTest.test_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
  lte/gateway/python/scripts/pipelined_cli.py
  lte/protos/pipelined.proto
Labels: component: agw, size/XL

#8252 docs(ci): Add note for new semantic commit requirement
  .github/workflows/comment-pr-on-check-failure.yml
Labels: size/XS

#8259 fix(orc8r): Fix swaggergen for type conversions using generated types
  cwf/cloud/go/go.sum
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  feg/gateway/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/tools/swaggergen/generate/rewrite.go
  orc8r/cloud/test/go.sum
  wifi/cloud/go/go.sum
Labels: component: agw, component: cwag, size/S

#8242 fix(mme): sentry_config was not set in OAI dockerfiles
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/M

#8265 Revert "feat(pipelined): Pipelined side for polling shards"
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_cookie_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_deny_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_pull_stats.PullStatsTest.test_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
  lte/gateway/python/scripts/pipelined_cli.py
  lte/protos/pipelined.proto
Labels: component: agw, size/XL

#8269 fix: backport #7847+#7850 to fix 1.6 branch build
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  lte/cloud/go/go.sum
  lte/gateway/c/core/oai/common/log.c
  lte/gateway/c/core/oai/common/log.h
  lte/gateway/c/core/oai/include/service303.h
  lte/gateway/c/core/oai/include/service303_messages_types.h
  lte/gateway/c/core/oai/lib/message_utils/service303_message_utils.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/service303/service303.cpp
  lte/gateway/c/core/oai/tasks/service303/service303_mme_stats.c
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/includes/MetricsSingleton.h
  wifi/cloud/go/go.sum
Labels: component: agw, component: cwag, size/M

#8202 chore: [ci] Complete migration from semantic bot to github action workflow w…
  .github/semantic.yml
  docs/readmes/contributing/contribute_workflow.md
Labels: size/M

#8161 refactor: add descriptive tags to amis
  .circleci/config.yml
  experimental/cloudstrapper/playbooks/roles/ami-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/devops-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw/tasks/agw-setup.yaml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
Labels: workstream: Hybrid Cloud/Edge

#7729 feat(orc8r): Add converged core config flags
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/defaults.go
  lte/cloud/go/services/lte/obsidian/models/network_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/mme.yml
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/api/v1/go/models/network_epc_configs.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, product: 5g sa, size/L

#8155 feat(orc8r): Support Orc8r-directed full resync for AGWs
  lte/cloud/configs/subscriberdb.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/subscriberdb/config.go
  lte/cloud/go/services/subscriberdb/const.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/storage/last_resync.go
  lte/cloud/go/services/subscriberdb/storage/last_resync_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  orc8r/cloud/go/orc8r/math/math.go
Labels: component: agw, component: orc8r, size/L

#8120 test(sessiond): Use shard class and write unit test
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/ShardTracker.cpp
  lte/gateway/c/session_manager/ShardTracker.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_polling_pipelined.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: component: agw, size/L

#8264 fix(mme): procps-ng is no more in latest RHEL UBI8 base image
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: agw, size/XS

#8230 docs: Change fully-qualified URL to relative url
  docs/docusaurus/versioned_docs/version-1.0.0/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.0.0/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.0.1/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.0.1/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.1.0/faq/magma_faq.md
  docs/docusaurus/versioned_docs/version-1.1.0/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.1.0/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.2.0/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.2.0/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.3.0/feg/federated_FWA_setup_guide.md
  docs/docusaurus/versioned_docs/version-1.4.0/faq/faq_magma.md
  docs/docusaurus/versioned_docs/version-1.4.0/feg/federated_FWA_setup_guide.md
  docs/docusaurus/versioned_docs/version-1.4.0/lte/config_agw.md
  docs/docusaurus/versioned_docs/version-1.4.0/lte/enodebd.md
  docs/docusaurus/versioned_docs/version-1.5.0/faq/faq_magma.md
  docs/docusaurus/versioned_docs/version-1.5.0/feg/deploy_configure.md
  docs/docusaurus/versioned_docs/version-1.5.0/howtos/troubleshooting/agw_unable_to_checkin.md
  docs/docusaurus/versioned_docs/version-1.5.0/lte/deploy_config_agw.md
  docs/docusaurus/versioned_docs/version-1.5.0/lte/deploy_config_enodebd.md
  docs/docusaurus/versioned_docs/version-1.5.0/lte/deploy_install.md
  docs/docusaurus/versioned_docs/version-1.6.0/feg/deploy_configure.md
  docs/docusaurus/versioned_docs/version-1.6.0/lte/upgrade_1_6.md
  docs/readmes/faq/faq_magma.md
  docs/readmes/feg/deploy_configure.md
  docs/readmes/howtos/troubleshooting/agw_unable_to_checkin.md
  docs/readmes/lte/deploy_config_agw.md
  docs/readmes/lte/deploy_config_enodebd.md
  docs/readmes/lte/upgrade_1_6.md
Labels: ready2merge, size/L

#8287 Revert "fix(xwf): fix docker gw0 mms size and CI"
  feg/radius/lib/go/radius/go.mod
  feg/radius/lib/go/radius/go.sum
  feg/radius/lib/go/radius/server-packet.go
  feg/radius/src/go.mod
  feg/radius/src/go.sum
  feg/radius/src/modules/ofpanalytics/ofpanalytics.go
  feg/radius/src/server/server.go
  feg/radius/src/server/udp_listener.go
  xwf/docker/docker-compose.yml
  xwf/gateway/integ_tests/gw/entrypoint.sh
Labels: size/M

#8240 chore(agw): add script to generate protos used by mme
  scripts/generate_cpp_protos.bash
Labels: ready2merge, size/M

#8042 chore(agw): remove CLion/CMake gitignore
  .gitignore
Labels: ready2merge

#8274 chore: [ci] Rename semantic PR check to be identifiable in required check lists
  .github/workflows/semantic-pr.yml
Labels: size/XS

#8253 refactor(subscriberdb): Reformatting subscriberdb code from changes to 5G auth vectors
  lte/gateway/python/magma/subscriberdb/crypto/lte.py
  lte/gateway/python/magma/subscriberdb/crypto/milenage.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/processor.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/tests/crypto/milenage_tests.py
  lte/gateway/python/magma/subscriberdb/tests/processor_tests.py
Labels: component: agw, size/L

#7882 feat(nms): Equipmentdashboard - Federation Gateways Cluster Status
  nms/app/packages/magmalte/app/views/equipment/FEGClusterStatus.js
  nms/app/packages/magmalte/app/views/equipment/FEGEquipmentGateway.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/FEGEquipmentGatewayTest.js
Labels: size/L
