Repository magma/magma, pull requests merged in 2021-06, with the labels that each got.

#6409 WIP [AGW][DEV]Build ubuntu box
  orc8r/tools/packer/http/preseed.cfg
  orc8r/tools/packer/magma-focal-virtualbox.json
  orc8r/tools/packer/scripts/ubuntu_setup.sh
Labels: size/L

#7068 [5G-SA][lte][agw][SMF]UPF Node message Handling
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/SessionManagerServer.cpp
  lte/gateway/c/session_manager/SessionManagerServer.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
  lte/gateway/c/session_manager/UpfMsgManageHandler.cpp
  lte/gateway/c/session_manager/UpfMsgManageHandler.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_upf_node_state.cpp
  lte/protos/session_manager.proto
Labels: component: agw, product: 5g sa, ready2merge, size/L

#7130 Add basic syntax check for codeowners changes
  .github/workflows/codeowners-syntax.yml
Labels: size/S

#7169 fix: configure the flake8 command in precommit.py to always return 0
  lte/gateway/python/precommit.py
Labels: component: agw, size/XS

#7207 Corrected code to send correct msisdn in create session request for roaming UEs
  lte/gateway/c/oai/lib/s8_proxy/s8_client_api.cpp
Labels: apply-v1.5, component: agw, size/S

#7109 [oai] use random number to generate tmsi
  lte/gateway/c/oai/oai_mme/oai_mme.c
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
Labels: component: agw, component: cwag, size/S

#7248 [MME] Drop build over-ride to Debug type for ngap sub-task
  lte/gateway/c/oai/tasks/ngap/CMakeLists.txt
Labels: component: agw, size/XS

#7247 AGW: datapath: add dp_probe_cli to the magma package
  lte/gateway/python/setup.py
Labels: apply-v1.5, component: agw, size/XS

#7246 AGW: GTP: add support for SEQ number handling.
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0001-of-match-expand-NXM_NX_TUN_FLAGS-to-include-all-tunn.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0002-userspace-IPFIX-Add-tunnel-type-GTP.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0003-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0004-ovs-Add-support-to-set-GTP-header-fields.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0005-OVS-gtp-echo-handling.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0006-ovs-test-add-gtp-marker-test.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0007-datapath-Fixes-for-4.9-kernel.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0008-ovs-datapath-enable-kernel-5.6.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0009-AGW-OVS-handle-gtp-tunnel-type.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0010-native-tnl-routing-tunnel-lookup-with-pkt-mark.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0011-fixes-for-2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0012-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0013-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0014-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0015-GTP-Extension-header-support-in-ovs2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0016-ODP-action-Fix-L3-port-to-L3-port-traffic.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0017-datapath-GTP-cleanup.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0018-GTP-handle-seq-number-in-HDR.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0018-datapath-gtp-add-segmentation-offloads.patch
Labels: size/L

#7253 Add debug logs to pipelined stress test
  lte/gateway/python/scripts/pipelined_cli.py
Labels: component: agw, size/S

#7251 [feg] s6a_proxy add Extended-Max-Requested-BW
  feg/gateway/services/s6a_proxy/servicers/s6a_definitions.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy_test.go
  feg/gateway/services/s6a_proxy/servicers/test/test_s6a_server.go
  feg/gateway/services/s6a_proxy/servicers/ul.go
Labels: size/M

#7242 bump up setup success message from debug to info
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
Labels: component: agw, size/XS

#7245 Add pipelined logic to query stats per cookie
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_cookie_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
Labels: component: agw, size/M

#7107 [orc8r] Add certificate lifespan metric and alert
  nms/app/packages/magmalte/alerts/cwfAlerts.js
  nms/app/packages/magmalte/alerts/fegAlerts.js
  nms/app/packages/magmalte/alerts/lteAlerts.js
  orc8r/cloud/configs/certifier.yml
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/go/services/analytics/analyzer.go
  orc8r/cloud/go/services/certifier/analytics/analytics.go
  orc8r/cloud/go/services/certifier/analytics/calculations/lifespan.go
  orc8r/cloud/go/services/certifier/certifier/main.go
  orc8r/cloud/go/services/certifier/config.go
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/lib/go/metrics/metrics_export.go
Labels: size/L

#7256 Apply formatting script to orc8r/gateway/python/magma
  orc8r/gateway/python/magma/configuration/mconfig_managers.py
  orc8r/gateway/python/magma/directoryd/rpc_servicer.py
  orc8r/gateway/python/magma/magmad/check/network_check/ping.py
  orc8r/gateway/python/magma/magmad/check/subprocess_workflow.py
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
  orc8r/gateway/python/magma/magmad/service_poller.py
  orc8r/gateway/python/magma/state/state_replicator.py
Labels: component: agw, component: cwag, size/L

#7263 [DOC]Bump main doc to v1.5
  docs/readmes/basics/prerequisites.md
Labels: size/XS

#7249 add mme unit test for both types of build type
  .circleci/config.yml
Labels: size/S

#7212 [lte][agw] Congestion control
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/lib/itti/intertask_interface.h
  lte/gateway/c/oai/lib/itti/intertask_interface_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/emm/Authentication.c
  lte/gateway/c/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/oai/tasks/nas/emm/SecurityModeControl.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/configs/mme.yml
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/L

#7268 switch to a different gnutil source
  .devcontainer/Dockerfile
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, size/S

#7271 [component:agw] Handling of the UEContextRequest present information …
  lte/gateway/c/oai/include/ngap_messages_types.h
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf_itti_messaging.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_itti_messaging.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c
Labels: component: agw, size/M

#7272 [component:agw] Handling AUTH Failure with Reason #71(ngKSI is alread…
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GMMCause.h
Labels: component: agw, size/L

#7273 Backport gnutls host change to unblock CI
  .devcontainer/Dockerfile
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, size/S

#7274 Fix Ryu postinstall patch cp
  lte/gateway/release/magma-postinst
Labels: apply-v1.5, component: agw, size/XS

#7275 [lte][agw] Backport PR7274
  lte/gateway/release/magma-postinst
Labels: size/XS

#7257 Adding missing header function definitions
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_s11_handlers.h
Labels: component: agw, size/S

#7259 Fix clearing of PCO attributes to preserve const correctness
  lte/gateway/c/oai/tasks/nas/esm/esm_information.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c
Labels: component: agw, size/XS

#7258 Remove an unused function
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw, size/M

#7265 [MobilityD] Remove unused imports
  lte/gateway/python/magma/mobilityd/ip_allocator_base.py
  lte/gateway/python/magma/mobilityd/ip_allocator_multi_apn.py
  lte/gateway/python/magma/mobilityd/ip_allocator_static.py
  lte/gateway/python/magma/mobilityd/tests/ip_allocator_dhcp_mac_addr_test.py
  lte/gateway/python/magma/mobilityd/tests/test_multi_apn_ip_alloc.py
  lte/gateway/python/magma/mobilityd/tests/test_static_ip_alloc.py
Labels: component: agw, ready2merge, size/L

#6979 [MME][DOCKER][RHEL8] Only using cmake3
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: agw, ready2merge, size/S

#7277 [sessiond[[feg] Add extended bitrates
  feg/gateway/services/session_proxy/credit_control/gx/definitions.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client.go
  feg/gateway/services/session_proxy/credit_control/gx/handlers.go
  feg/gateway/services/session_proxy/credit_control/gx/model_conversion.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/protos/session_manager.proto
  lte/protos/subscriberdb.proto
Labels: component: agw

#7269 [AGW] Fix parsing errors caused from scraping node exporter metrics.
  orc8r/gateway/python/magma/magmad/metrics_collector.py
Labels: size/L

#7134 [agw][lte] Logging enhancement
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/Authentication.c
  lte/gateway/c/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/oai/tasks/nas/emm/SecurityModeControl.c
  lte/gateway/c/oai/tasks/nas/emm/ServiceRequestHdl.c
  lte/gateway/c/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/oai/tasks/nas/emm/sap/EmmDeregistered.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_as.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_send.c
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/oai/tasks/nas/esm/PdnDisconnect.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c
  lte/gateway/c/oai/tasks/nas/nas_proc.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: component: agw, size/XL

#7280 [lte][agw] Add missing commit for PR7212
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/nas/emm/Authentication.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/configs/mme.yml
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/S

#7046 Modified sgw_s8 code to generate random control plane teid
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/gateway/c/oai/include/sgw_context_manager.h
  lte/gateway/c/oai/include/spgw_types.h
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/oai/test/spgw_task/state_creators.cpp
  lte/gateway/c/oai/test/spgw_task/state_creators.h
  lte/gateway/c/oai/test/spgw_task/test_spgw_state_converter.cpp
  lte/protos/oai/spgw_state.proto
Labels: component: agw, size/L

#7294 [Non_Sanity_Testing] Ankit fixed failing test case for wrong argument in function call
  lte/gateway/python/integ_tests/s1aptests/test_send_error_ind_for_erab_setup_req.py
Labels: component: agw, size/XS

#5840 Added all non-sanity test cases to defs.mk file
  lte/gateway/python/integ_tests/Makefile
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/M

#7286 Loosen formatting to be less aggressive
  lte/gateway/python/precommit.py
Labels: component: agw, size/XS

#7301 [backport 1.5] AGW: Fix flow create for non-nat bootup.
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: component: agw, component: cwag, size/XS

#6896 [cloudstrapper][agw] Build AGW & Cloudstrapper AWS AMI
  .circleci/config.yml
  experimental/cloudstrapper/README.md
  experimental/cloudstrapper/playbooks/ami-configure.yaml
  experimental/cloudstrapper/playbooks/devops-configure.yaml
  experimental/cloudstrapper/playbooks/roles/ami-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/keys.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-cloudwatch.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-ec2-asg.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-efs.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-elb.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-eni-subnet-route.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-es.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-igw.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-natgw.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-rds-snapshots.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-rds.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-secgroup.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-secrets.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-vpc.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r.yaml
  experimental/cloudstrapper/playbooks/roles/aws-essentials/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/build-platform/tasks/build-tools-packages.yaml
  experimental/cloudstrapper/playbooks/roles/build-platform/tasks/magma-repo.yaml
  experimental/cloudstrapper/playbooks/roles/build-platform/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/clean-authorized-keys/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/devops-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/key-manager/tasks/main.yaml
Labels: component: agw, component: ci, size/L

#7211 [Docs][S1APTester] Add doc on how to connect s1aptester to physical AGW
  docs/readmes/lte/dev_notes.md
Labels: ready2merge, size/M

#7299 add a Github Action to check for any leftover python formatting
  .github/workflows/python-formatting-check.yml
  lte/gateway/docker/python-precommit/Dockerfile
  lte/gateway/python/precommit.py
Labels: component: agw, size/M

#7276 [AGW] Bump v1.5 to 1.5.1
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, component: cwag, size/M

#7284 [Cloud] Support for community deployment
  experimental/cloudstrapper/README.md
  experimental/cloudstrapper/playbooks/roles/control/tasks/configure-terraform.yaml
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.v1.5
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.v1.5.community
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.v1.5.custom
Labels: size/L

#7308 [feg] Add CreateBearerRequest handler for s8_proxy
  cwf/gateway/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/s8_proxy/client_api_test.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/gw_s8_client_api.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_feg_relay/mock_feg_relay.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cb.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mb.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/tft_proto_conversion.go
Labels: component: agw, component: cwag, size/XL

#7312 [Bug form] Updated bug form
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size/XS

#7148 Fix loading all subscriber state
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/state/client_api.go
Labels: component: agw, component: orc8r, size/L

#7311 add step in agw package to copy out c executables for sentry
  lte/gateway/fabfile.py
Labels: component: agw, size/S

#7313 [AGW]Backport fix for agw install on debian
  lte/gateway/deploy/agw_install.sh
Labels: component: agw, component: cwag, size/S

#7310 [orc8r] annotate unused params with __attribute__
  orc8r/gateway/c/common/logging/magma_logging_init.h
  orc8r/gateway/c/common/service303/MagmaService.cpp
Labels: ready2merge, size/S

#7315 Fix IPFIX OVS Install Failure Bug on Disabled Config
  lte/gateway/python/magma/pipelined/app/ipfix.py
Labels: apply-v1.5, component: agw, size/XS

#7187 [orc8r] Refactor swagger spec filepath handling
  orc8r/cloud/go/obsidian/swagger/handlers/handlers.go
  orc8r/cloud/go/obsidian/swagger/poll.go
  orc8r/cloud/go/obsidian/swagger/poll_test.go
  orc8r/cloud/go/obsidian/swagger/spec/gen.go
  orc8r/cloud/go/obsidian/swagger/spec/loader.go
  orc8r/cloud/go/obsidian/swagger/spec/loader_internal_test.go
  orc8r/cloud/go/obsidian/swagger/spec/loader_test.go
  orc8r/cloud/go/obsidian/swagger/spec/mocks/Loader.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer_test.go
Labels: size/L

#7000 [orc8r][nprobe] add li agent x1 mconfig
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/cloud/go/services/nprobe/obsidian/models/conversion.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_task_details_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/swagger.v1.yml
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/go/obsidian/swagger/v1/models/network_probe_task_details.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, size/XL

#7319 AGW: non-nat: handle UE and management network in same subnet.
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
Labels: component: agw, size/XS

#7320 [backport 1.5] AGW: non-nat: handle UE and management network in same subnet.
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
Labels: component: agw, component: cwag, size/XS

#7307 commit enodebd python formatting changes
  lte/gateway/python/load_tests/loadtest_pipelined.py
  lte/gateway/python/magma/enodebd/data_models/data_model.py
  lte/gateway/python/magma/enodebd/data_models/data_model_parameters.py
  lte/gateway/python/magma/enodebd/data_models/transform_for_enb.py
  lte/gateway/python/magma/enodebd/data_models/transform_for_magma.py
  lte/gateway/python/magma/enodebd/device_config/configuration_init.py
  lte/gateway/python/magma/enodebd/device_config/configuration_util.py
  lte/gateway/python/magma/enodebd/device_config/enodeb_configuration.py
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/devices/device_utils.py
  lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/enodebd_iptables_rules.py
  lte/gateway/python/magma/enodebd/exceptions.py
  lte/gateway/python/magma/enodebd/logger.py
  lte/gateway/python/magma/enodebd/lte_utils.py
  lte/gateway/python/magma/enodebd/metrics.py
  lte/gateway/python/magma/enodebd/rpc_servicer.py
  lte/gateway/python/magma/enodebd/s1ap_client.py
  lte/gateway/python/magma/enodebd/state_machines/acs_state_utils.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_impl.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_manager.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_pointer.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/stats_manager.py
  lte/gateway/python/magma/enodebd/tests/baicells_old_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_qafb_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_tests.py
  lte/gateway/python/magma/enodebd/tests/cavium_tests.py
  lte/gateway/python/magma/enodebd/tests/configuration_init_tests.py
  lte/gateway/python/magma/enodebd/tests/data_model_tests.py
  lte/gateway/python/magma/enodebd/tests/device_utils_tests.py
  lte/gateway/python/magma/enodebd/tests/enb_acs_manager_tests.py
  lte/gateway/python/magma/enodebd/tests/enodeb_configuration_tests.py
  lte/gateway/python/magma/enodebd/tests/enodeb_status_tests.py
  lte/gateway/python/magma/enodebd/tests/stats_manager_tests.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enodeb_handler.py
  lte/gateway/python/magma/enodebd/tests/test_utils/tr069_msg_builder.py
  lte/gateway/python/magma/enodebd/tests/tr069_tests.py
  lte/gateway/python/magma/enodebd/tr069/models.py
  lte/gateway/python/magma/enodebd/tr069/rpc_methods.py
  lte/gateway/python/magma/enodebd/tr069/server.py
  lte/gateway/python/magma/enodebd/tr069/spyne_mods.py
  lte/gateway/python/magma/enodebd/tr069/tests/models_tests.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/message_tests.py
  lte/gateway/python/setup.py
Labels: component: agw, size/XXL

#7330 [LTE][AGW] EMM data context _ms_network_capability attribute copy: wrong sizeof()
  lte/gateway/c/oai/tasks/nas/emm/emm_data_ctx.c
Labels: apply-v1.4, apply-v1.5, component: agw, size/XS

#7318 Add generic exeption capture for enf poll
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
Labels: component: agw, size/XS

#7306 Add unit test to current enforcement stats accounting
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/python/magma/pipelined/openflow/flows.py
Labels: component: agw, size/L

#7262 Create orc8r go library code to take deterministic digest of slice of unordered protobufs
  orc8r/cloud/go/mproto/mproto.go
  orc8r/cloud/go/mproto/mproto_test.go
  orc8r/cloud/go/mproto/protos/gen.go
  orc8r/cloud/go/mproto/protos/mproto.pb.go
  orc8r/cloud/go/mproto/protos/mproto.proto
  orc8r/cloud/go/mproto/test/gen.go
  orc8r/cloud/go/mproto/test/test.pb.go
  orc8r/cloud/go/mproto/test/test.proto
  orc8r/cloud/go/mproto/testdata/determinisic-digest.b64.golden
  orc8r/gateway/go/services/configurator/service/configurator.go
Labels: component: orc8r, size/XL

#7331 update python-precommit README to give more details / updated informa…
  lte/gateway/docker/python-precommit/README.md
  lte/gateway/docker/python-precommit/requirements.txt
Labels: component: agw, size/M

#7339 [mme] Remove AssertFatal NULL checks after itti_alloc_new_message calls
  lte/gateway/c/oai/lib/message_utils/service303_message_utils.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s6a/s6a_peer.c
Labels: component: agw, size/S

#7342 Add W391 to the formatting script to strip empty space at the end of …
  lte/gateway/python/precommit.py
Labels: component: agw, size/XS

#7327 [feg][agw] Add regional subscription proto definition in ULR message
  feg/cloud/go/protos/s6a_proxy.pb.go
  feg/protos/s6a_proxy.proto
Labels: size/L

#7344 [feg_relay] fix wrong teid
  feg/cloud/go/services/feg_relay/servicers/create_bearer_pgw.go
Labels: size/XS

#7358 Fix Enforcement Poll datapath select
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
Labels: component: agw, size/M

#7360 DOCKER: fix after core inversion typo
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: agw, size/XS

#7365 fix provision error in magma_test VM
  lte/gateway/deploy/magma_test.yml
Labels: component: agw, size/XS

#7357 Fix conntrackd zone verification
  lte/gateway/c/connection_tracker/EventTracker.cpp
  lte/gateway/c/connection_tracker/EventTracker.h
  lte/gateway/c/connection_tracker/main.cpp
  lte/gateway/configs/connectiond.yml
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/conntrack.py
  lte/gateway/python/magma/pipelined/tests/test_conntrack.py
Labels: apply-v1.5, component: agw, size/M

#7001 Execute integ_testcases enabling pipelined_managed_tbl0 #6947
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py
  lte/gateway/python/magma/pipelined/tests/test_paging.py
Labels: component: agw, product: 5g sa, size/L

#7332 Addresses deadStore warnings by using/removing stores
  lte/gateway/c/core/oai/common/async_system.c
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/common/shared_ts_log.c
Labels: component: agw, ready2merge, size/S

#7371 Update the build directory for clang_tidy_oai target
  lte/gateway/Makefile
Labels: component: agw, size/S

#7333 Auth failure changes
  lte/gateway/c/oai/include/ngap_messages_types.h
  lte/gateway/c/oai/lib/3gpp/3gpp_24.501.h
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf_handlers.c
Labels: component: agw, size/L

#7361 Add approvers-agw-c to connection_tracker directory
  CODEOWNERS
Labels: size/XS

#7345 [s6a_proxy] add feature list id 1
  feg/cloud/go/protos/s6a_proxy.pb.go
  feg/gateway/go.mod
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy_test.go
  feg/gateway/services/s6a_proxy/servicers/test/test_s6a_server.go
  feg/gateway/services/s6a_proxy/servicers/ul.go
  feg/protos/s6a_proxy.proto
Labels: size/L

#7281 [agw][ami] Clean agw ami and add optional ssh key
  .circleci/config.yml
  experimental/cloudstrapper/README.md
  experimental/cloudstrapper/playbooks/agw-configure.yaml
  experimental/cloudstrapper/playbooks/ami-configure.yaml
  experimental/cloudstrapper/playbooks/devops-configure.yaml
  experimental/cloudstrapper/playbooks/roles/add-aws-ssh-key/tasks/kms-key.yaml
  experimental/cloudstrapper/playbooks/roles/add-aws-ssh-key/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/add-aws-ssh-key/tasks/ssh-key.yaml
  experimental/cloudstrapper/playbooks/roles/add-aws-ssh-key/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/clean-ami/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/clean-authorized-keys/tasks/main.yaml
Labels: size/L

#7380 [feg] Config/flags fixes related to base accounting service & client
  feg/cloud/go/services/basic_acct/base_acct/main.go
  feg/cloud/go/services/basic_acct/servicers/config.go
  feg/cloud/go/services/basic_acct/servicers/service.go
  feg/gateway/utils/configs.go
Labels: size/L

#7322 Modified code to remove GUTI state entries
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
Labels: component: agw, size/L

#7386 Update codeowners to use the updated directory structure
  CODEOWNERS
Labels: size/XS

#7364 Provided fix for issue 6365
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
Labels: component: agw, size/S

#7363 Add a circleci job to build connection tracker
  .circleci/config.yml
Labels: size/M

#7390 Add hunter as a CODEOWNER file code owner in CODEOWNER file
  CODEOWNERS
Labels: size/XS

#7396 Force build step in superbuilds
  lte/gateway/c/core/CMakeLists.txt
Labels: size/XS

#7393 fix bug where policy versions are overwritten when processing policy
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: size/M

#7370 update `session_terminated` event definition to have all recently updated fields
  lte/swagger/session_manager_events.v1.yml
Labels: component: agw, size/M

#7378 [feg][backport v1.5] s8 proxy add apn op suffix
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/cloud/go/services/feg/obsidian/models/s8_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/s8_proxy/servicers/config.go
  feg/gateway/services/s8_proxy/servicers/config_test.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/protos/mconfig/mconfigs.proto
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, component: cwag, size/L

#7407 [lte][agw] Revert "Modified code to remove GUTI state entries"
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/ServiceRequestHdl.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
Labels: size/L

#7410 [lte][agw] Fix log messages
  lte/gateway/c/core/oai/common/async_system.c
  lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/core/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
  lte/gateway/c/core/oai/tasks/sgs/sgs_task.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c
  lte/gateway/c/core/oai/tasks/sms_orc8r/sms_orc8r_task.c
  lte/gateway/c/core/oai/tasks/udp/udp_primitives_server.c
Labels: size/S

#7141 [agw][liagentd] liagentd service implementation
  lte/gateway/c/li_agent/CMakeLists.txt
  lte/gateway/c/li_agent/DirectorydClient.cpp
  lte/gateway/c/li_agent/DirectorydClient.h
  lte/gateway/c/li_agent/InterfaceMonitor.cpp
  lte/gateway/c/li_agent/InterfaceMonitor.h
  lte/gateway/c/li_agent/MobilitydClient.cpp
  lte/gateway/c/li_agent/MobilitydClient.h
  lte/gateway/c/li_agent/PDUGenerator.cpp
  lte/gateway/c/li_agent/PDUGenerator.h
  lte/gateway/c/li_agent/ProxyConnector.cpp
  lte/gateway/c/li_agent/ProxyConnector.h
  lte/gateway/c/li_agent/Utilities.cpp
  lte/gateway/c/li_agent/Utilities.h
  lte/gateway/c/li_agent/main.cpp
  lte/gateway/c/li_agent/test/CMakeLists.txt
  lte/gateway/c/li_agent/test/LIAgentdMocks.h
  lte/gateway/c/li_agent/test/test_pdu_generator.cpp
  lte/gateway/configs/liagentd.yml
  lte/gateway/configs/magmad.yml
  lte/gateway/configs/pipelined.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/release/build-magma.sh
Labels: component: agw, ready2merge, size/XXL

#7384 [MME][ZMQ] protect against using a destroyed zmq context
  lte/gateway/c/core/oai/lib/itti/intertask_interface.c
  lte/gateway/c/core/oai/lib/itti/intertask_interface.h
Labels: component: agw, ready2merge, size/M

#7366 [lte][orc8r] deprecates field relay_enabled in lte mconfigs
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_upf_node_state.cpp
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, ready2merge, size/L

#7031 AGW: pipelined: pipelined-cli broken #6963
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/pg_set_session_msg.py
  lte/gateway/python/magma/pipelined/tests/test_ng_servicer_session.py
  lte/gateway/python/scripts/pipelined_cli.py
Labels: component: agw, product: 5g sa

#7314 [NMS]Made Gateways register only unregistered enodeB's
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
Labels: size/M

#6994 Move sentry release from GH action to CircleCI (temporarily)
  .circleci/config.yml
  .github/workflows/sentry-release.yml
Labels: size/M

#7191 [docs] Add APN refactoring proposal
  docs/docusaurus/sidebars.json
  docs/readmes/assets/proposals/p017/apn_new.png
  docs/readmes/assets/proposals/p017/apn_old.png
  docs/readmes/proposals/p017_apn_refactoring.md
Labels: type: proposal

#7368 [docker] links session_manager config files
  .devcontainer/devcontainer.json
Labels: size/XS

#7316 [orc8r] DB Alerts
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-aws/db.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
Labels: size/L

#7346 [orc8r] Upgrade to latest version of terraform(0.15.5)
  orc8r/cloud/deploy/orc8r_deployer/docker/Dockerfile
  orc8r/cloud/deploy/terraform/orc8r-aws/eks.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/providers.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/providers.tf
Labels: size/M

#7422 [feg] AAA Server & base acct fixes & log improvements
  feg/cloud/go/services/basic_acct/base_acct/main.go
  feg/cloud/go/services/basic_acct/servicers/participants.go
  feg/gateway/services/aaa/servicers/accounting.go
  feg/gateway/services/aaa/store/in_memory.go
Labels: size/S

#7451 [feg_relay] add logs to get hwid from teid
  feg/cloud/go/services/feg_relay/servicers/feg_to_gw_relay.go
Labels: size/XS

#7450 [mme] Remove dead code mcc_mnc_itu.c
  lte/gateway/c/core/oai/common/CMakeLists.txt
  lte/gateway/c/core/oai/common/mcc_mnc_itu.c
  lte/gateway/c/core/oai/common/mcc_mnc_itu.h
Labels: size/XL

#7448 [orc8r] Upgrade prometheus version and add an option to not lockfile.
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/templates/prometheus.deployment.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/values.yaml
Labels: size/S

#7392 [agw][cloudstrapper] clean ami root ssh keys
  experimental/cloudstrapper/playbooks/roles/clean-ami/tasks/main.yaml
Labels: ready2merge, size/XS, workstream: Hybrid Cloud/Edge

#7462 fix sentry release circle ci job
  .circleci/config.yml
Labels: size/S

#7456 [Non_Sanity_Testing] Updated the s1ap_tests document with non-sanity testing step
  docs/readmes/lte/s1ap_tests.md
Labels: size/XS

#7372 [lte][agw] Add cloud configuration for MME congestion control
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c
  lte/gateway/c/core/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/mme.yml
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/go/obsidian/swagger/v1/models/gateway_epc_configs.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, size/XL

#7461 [orc8r][helm] Fix dependency conflict for orc8r metric chart
  orc8r/cloud/helm/orc8r/Chart.lock
  orc8r/cloud/helm/orc8r/Chart.yaml
Labels: size/XS

#7469 [lte][agw] Fixing clang-format path for core build
  lte/gateway/Makefile
  lte/gateway/c/core/oai/lib/itti/intertask_interface.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
Labels: size/S

#7449 [cloud] Cloudstrapper Securitygroups Cleanup
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r-secgroup.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/vars/main.yaml
Labels: size/M

#7373 [mme] Remove additional unnecessary AssertFatal calls
  lte/gateway/c/core/oai/common/async_system.c
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
Labels: component: agw, size/XS

#7413 [mme] S6a_client refactor to grab the proper client
  lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
  lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.h
Labels: size/M

#7485 [orc8r] Default value for SNS emails
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
Labels: size/XS

#7481 [helm][ci] Check helm dependencies github action job
  .github/workflows/helm-chart-dependency-check.yml
Labels: size/M

#7470 AGW: gtp: add support for segmentation offload.
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0001-of-match-expand-NXM_NX_TUN_FLAGS-to-include-all-tunn.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0002-userspace-IPFIX-Add-tunnel-type-GTP.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0003-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0004-ovs-Add-support-to-set-GTP-header-fields.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0005-OVS-gtp-echo-handling.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0006-ovs-test-add-gtp-marker-test.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0007-datapath-Fixes-for-4.9-kernel.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0008-ovs-datapath-enable-kernel-5.6.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0009-AGW-OVS-handle-gtp-tunnel-type.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0010-native-tnl-routing-tunnel-lookup-with-pkt-mark.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0011-fixes-for-2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0012-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0013-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0014-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0015-GTP-Extension-header-support-in-ovs2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0016-ODP-action-Fix-L3-port-to-L3-port-traffic.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0017-datapath-GTP-cleanup.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0018-GTP-handle-seq-number-in-HDR.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0019-datapath-gtp-add-segmentation-offloads.patch
Labels: size/L

#7477 orc8r: Fix hanging Swagger UI
  orc8r/cloud/go/obsidian/swagger/poll.go
  orc8r/cloud/go/obsidian/swagger/remote_spec.go
  orc8r/lib/go/registry/global_registry.go
  orc8r/lib/go/registry/registry.go
Labels: size/S

#7494 commit leftover i18n file
  docs/docusaurus/i18n/en.json
Labels: size/XS

#7474 [feg] Add NH support to FeG 2 GW relay (issue #7473)
  feg/cloud/go/services/feg_relay/servicers/feg_to_gw_relay.go
Labels: size/S

#7490 AGW: add IRQ CPU affinity configuration
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/deploy/roles/magma/files/set_irq_affinity
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/datapath_setup.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/release/build-magma.sh
Labels: size/L

#7499 AGW: add script to upgrade OVS kmod.
  lte/gateway/deploy/roles/magma/files/ovs-kmod-upgrade.sh
  lte/gateway/release/build-magma.sh
Labels: size/M

#7376 [AGW]Ubuntu ci testing
  .circleci/config.yml
  lte/gateway/Vagrantfile
  lte/gateway/deploy/hosts
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  orc8r/tools/packer/magma-focal-virtualbox.json
Labels: component: agw, size/L

#7503 [AGW] Bump upgrade script + force apt
  lte/gateway/release/upgrade_magma.sh
Labels: size/XS

#7338 [mme] Change various AssertFatal calls to Fatal
  lte/gateway/c/core/oai/common/common_defs.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_common_ies.c
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_gmm_ies.c
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_mm_ies.c
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_sm_ies.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include/NwGtpv2cPrivate.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/core/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/core/oai/tasks/nas/ies/TrafficFlowAggregateDescription.c
  lte/gateway/c/core/oai/tasks/nas/nas_procedures.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_config.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_pcef_emulation.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_config.c
Labels: component: agw, size/L

#7302 Update Orc8r’s subscriberdb servicer to support flat subscriber digests
  lte/cloud/configs/subscriberdb.yml
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/config.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/protos/subscriberdb.proto
  orc8r/cloud/go/mproto/mproto.go
  orc8r/cloud/go/mproto/mproto_test.go
  orc8r/cloud/go/mproto/testdata/determinisic-digest.b64.golden
Labels: component: agw, component: orc8r, size/XL

#7406 [docker] change patches path after core superbuild
  .devcontainer/Dockerfile
Labels: ready2merge, size/XS

#7482 Fix ctests for OAI and SCTPD
  lte/gateway/Makefile
  lte/gateway/c/sctpd/CMakeLists.txt
Labels: size/M

#7505 [AGW] Set up force in upgrade script
  lte/gateway/release/upgrade_magma.sh
Labels: size/XS

#7511 [cloud] Fixing Cloudstrapper Build module
  experimental/cloudstrapper/README.md
  experimental/cloudstrapper/playbooks/build-configure.yaml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
  experimental/cloudstrapper/playbooks/roles/vars/defaults.yaml
Labels: size/XS

#7483 [Agw][MME][refactor] New enum explicitly for RETURNok and RETURNerror
  lte/gateway/c/core/oai/common/async_system.c
  lte/gateway/c/core/oai/common/async_system.h
  lte/gateway/c/core/oai/common/common_defs.h
  lte/gateway/c/core/oai/common/digest.c
  lte/gateway/c/core/oai/common/digest.h
  lte/gateway/c/core/oai/common/redis_utils/redis_client.cpp
  lte/gateway/c/core/oai/common/redis_utils/redis_client.h
  lte/gateway/c/core/oai/include/state_manager.h
  lte/gateway/c/core/oai/lib/itti/intertask_interface.c
  lte/gateway/c/core/oai/lib/itti/intertask_interface.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_manager.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.h
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.h
Labels: size/L

#7431 Fix metrics collection chunks
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/magmad/metrics_collector.py
  orc8r/gateway/python/magma/magmad/tests/collector_tests.py
Labels: size/M

#7377 [mme][refactor] Remove AssertFatal from mme_api_get_emm_config
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_main.c
Labels: component: agw, size/M

#7434 [orc8r] remove usage of `$MAGMA_ROOT`
  orc8r/cloud/go/tools/combine_swagger/combine/combine_test.go
  orc8r/cloud/go/tools/combine_swagger/generate/generate.go
  orc8r/cloud/go/tools/combine_swagger/generate/generate_test.go
  orc8r/cloud/go/tools/combine_swagger/main.go
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/base.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/cycle1.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/cycle2.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/importer.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/configs/importer2.yml
  orc8r/cloud/go/tools/swaggergen/generate/generate.go
  orc8r/cloud/go/tools/swaggergen/generate/generate_test.go
  orc8r/cloud/go/tools/swaggergen/generate/rewrite_test.go
  orc8r/cloud/go/tools/swaggergen/testdata/base.yml
  orc8r/cloud/go/tools/swaggergen/testdata/cycle1.yml
  orc8r/cloud/go/tools/swaggergen/testdata/cycle2.yml
  orc8r/cloud/go/tools/swaggergen/testdata/importer.yml
  orc8r/cloud/go/tools/swaggergen/testdata/importer2.yml
Labels: ready2merge, size/L

#7507 address pylint in ubuntu
  orc8r/gateway/python/magma/magmad/check/subprocess_workflow.py
  orc8r/gateway/python/magma/magmad/check/tests/subprocess_workflow_tests.py
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/magmad/metrics.py
  orc8r/gateway/python/magma/magmad/upgrade/upgrader.py
Labels: size/S

#7514 AGW: OVS: add dmks install to upgrade script.
  lte/gateway/deploy/roles/magma/files/ovs-kmod-upgrade.sh
Labels: size/XS

#7492 Enforcement functionality support on magma-5g
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/ng_manager/session_state_manager.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
Labels: size/XL

#7519 Fix dependency on datastore and policydb
  lte/gateway/c/session_manager/CMakeLists.txt
Labels: size/XS

#7521 Remove proto dependencies from datastore
  lte/gateway/c/session_manager/datastore/CMakeLists.txt
Labels: size/XS

#7523 [lte][agw] Fix segfault in issue 7128
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
Labels: size/XS

#7285 [CI] disable integ-test
  .circleci/config.yml
Labels: component: agw, size/XS

#7532 fix(ci): extend mme job timeout to 20m
  .circleci/config.yml
Labels: size/XS

#7529 fix(build): update magma AGW dependency versions
  lte/gateway/release/build-magma.sh
  lte/gateway/release/mirrored_packages
Labels: component: agw, size/XS

#7527 AGW: pipelined: fix typo in datapath tuning.
  lte/gateway/python/magma/pipelined/datapath_setup.py
Labels: component: agw, size/S

#7534 commit leftover oai formatting changes
  lte/gateway/c/core/oai/common/common_defs.h
  lte/gateway/c/core/oai/common/redis_utils/redis_client.cpp
  lte/gateway/c/core/oai/common/redis_utils/redis_client.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_main.c
Labels: component: agw, size/M

#7526 fix(pipelined): Use correct ip-addr value to get hash entry
  lte/gateway/python/magma/pipelined/rule_mappers.py
Labels: apply-v1.5, component: agw, size/XS

#7528 fix(pipelined): update imports of AggregatedMaximumBitrate
  lte/gateway/python/load_tests/loadtest_pipelined.py
  lte/gateway/python/scripts/pipelined_cli.py
Labels: component: agw, size/XS

#7398 [agw][lte][new feature] Support for Service area restriction
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/gateway/c/core/oai/common/common_types.c
  lte/gateway/c/core/oai/common/common_types.h
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/lib/s6a_proxy/itti_msg_to_proto_msg.cpp
  lte/gateway/c/core/oai/lib/s6a_proxy/proto_msg_to_itti_msg.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_proc.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.h
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/oai/mme_nas_state.proto
Labels: component: agw, ready2merge, size/XL

#7439 [component: agw] Changes to support Sync Failure
  lte/cloud/go/protos/subscriberauth.pb.go
  lte/gateway/c/oai/include/amf_app_messages_def.h
  lte/gateway/c/oai/include/amf_app_messages_types.h
  lte/gateway/c/oai/include/n11_messages_types.h
  lte/gateway/c/oai/lib/n11/CMakeLists.txt
  lte/gateway/c/oai/lib/n11/M5GAuthenticationServiceClient.cpp
  lte/gateway/c/oai/lib/n11/M5GAuthenticationServiceClient.h
  lte/gateway/c/oai/lib/n11/amf_client_proto_msg_to_itti_msg.cpp
  lte/gateway/c/oai/lib/n11/amf_client_proto_msg_to_itti_msg.h
  lte/gateway/c/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_asDefs.h
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/oai/tasks/amf/amf_cn.cpp
  lte/gateway/c/oai/tasks/amf/amf_cn.h
  lte/gateway/c/oai/tasks/amf/amf_data.cpp
  lte/gateway/c/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/oai/tasks/amf/amf_sap.cpp
  lte/gateway/c/oai/tasks/amf/amf_sap.h
  lte/gateway/c/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/oai/tasks/nas/nas_procedures.c
  lte/gateway/c/oai/tasks/nas5g/CMakeLists.txt
  lte/gateway/c/oai/tasks/nas5g/include/M5GAuthenticationFailure.h
  lte/gateway/c/oai/tasks/nas5g/include/M5GPDUSessionEstablishmentRequest.h
  lte/gateway/c/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GAuthenticationFailureIE.h
  lte/gateway/c/oai/tasks/nas5g/src/M5GAuthenticationFailure.cpp
  lte/gateway/c/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentRequest.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GAuthenticationFailureIE.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GPDUSessionType.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GSSCMode.cpp
  lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.h
  lte/gateway/c/oai/test/CMakeLists.txt
  lte/gateway/c/oai/test/amf/CMakeLists.txt
  lte/gateway/c/oai/test/amf/test_amf.cpp
  lte/gateway/c/oai/test/amf/util_nas5g_auth_fail_pkt.cpp
  lte/gateway/c/oai/test/amf/util_nas5g_pdu_sess_est_req_pkt.cpp
  lte/gateway/c/oai/test/amf/util_nas5g_pkt.h
  lte/gateway/c/oai/test/amf/util_nas5g_registration_pkt.cpp
  lte/gateway/c/oai/test/ngap/test_ngap.cpp
  lte/gateway/c/oai/test/ngap/util_ngap_initiate_ue.cpp
  lte/gateway/c/oai/test/ngap/util_ngap_pkt.h
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/metrics.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
  lte/protos/subscriberauth.proto
  orc8r/gateway/c/common/async_grpc/CMakeLists.txt
Labels: component: agw, size/XXL

#7539 perf(pipeilined): Remove rule map entry in rule Deactivate call
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/tests/test_rule_mappers.py
Labels: component: agw, size/S

#7543 [lte][agw] Change the utility function location for service area verification
  lte/gateway/c/core/oai/common/common_types.c
  lte/gateway/c/core/oai/common/common_types.h
  lte/gateway/c/core/oai/common/common_utility_funs.cpp
  lte/gateway/c/core/oai/common/common_utility_funs.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
Labels: component: agw, size/M

#7545 [orc8r] add service indicator to PolicyRules on swagger
  feg/gateway/go.mod
  lte/cloud/go/services/policydb/obsidian/models/conversion.go
  lte/cloud/go/services/policydb/obsidian/models/policy_rule_config_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/policy_rule_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/obsidian/swagger/v1/models/policy_rule.go
  orc8r/cloud/go/obsidian/swagger/v1/models/policy_rule_config.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, size/M

#7536 Fix SessionManager ninja cyclic dependency
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/datastore/CMakeLists.txt
  lte/gateway/c/session_manager/policydb/CMakeLists.txt
Labels: component: agw, size/S

#7550 [component:agw] Fix for NAS Decode failure on GUTI
  lte/gateway/c/oai/tasks/nas5g/src/M5GRegistrationRequest.cpp
  lte/gateway/c/oai/test/amf/test_amf.cpp
  lte/gateway/c/oai/test/amf/util_nas5g_pkt.h
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_ipv6_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_two_policies.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_deny_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.EnforcementTableHeTest.test_subscriber_policy_with_he.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_url_redirect.snapshot
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
  orc8r/lib/go/protos/metricsd.pb.go
  orc8r/protos/metricsd.proto
Labels: component: agw, size/XL
