Repository magma/magma, pull requests merged in 2021-12, with the labels that each got.

#10587 fix(sessiond): Enable ASAN for SessionD unit tests
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/SessionManagerServer.cpp
Labels: component: agw, size/S

#10563 chore(sessiond): fix BUILD files for session_manager
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/c/session_manager/test/BUILD.bazel
Labels: component: agw, size/XS

#10588 test(pipelined): fix inout non-nat test
  lte/gateway/python/magma/mobilityd/scripts/setup-uplink-vlan-srv.sh
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout_non_nat.InOutNonNatTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout_non_nat.InOutNonNatTest.testFlowVlanSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout_non_nat.InOutNonNatTest.testFlowVlanSnapshotMatch2.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout_non_nat.InOutNonNatTest.testFlowVlanSnapshotMatch_static1.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout_non_nat.InOutNonNatTest.testFlowVlanSnapshotMatch_static2.snapshot
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
Labels: component: agw, size/L

#10595 test(pipelined): skip stats check in ipv6 solicitation
  lte/gateway/python/magma/pipelined/tests/snapshots/test_ipv6_solicitation.IPV6RouterSolicitationTableTest.test_ipv6_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_ipv6_solicitation.py
Labels: component: agw, size/S

#10585 fix(magmad): Skip upgrade if no sensible target version is set
  orc8r/gateway/python/magma/magmad/upgrade/upgrader.py
Labels: component: orc8r, size/M, ready2merge

#10310 chore(nms): upgrade axios from 0.21.1 to 0.21.2
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/S, ready2merge

#10344 fix(pipelined): Check that QosManager is not None before use
  lte/gateway/python/magma/pipelined/app/gy.py
Labels: component: agw, size/XS, ready2merge

#6413 feat(orc8r): adding auto-generated certs on pods.
  cwf/cloud/helm/cwf-orc8r/Chart.lock
  cwf/cloud/helm/cwf-orc8r/Chart.yaml
  cwf/cloud/helm/cwf-orc8r/values.yaml
  experimental/cloudstrapper/playbooks/roles/control/files/v1.4/orc8r-helm-aws/variables.tf
  fbinternal/cloud/helm/fbinternal-orc8r/Chart.lock
  fbinternal/cloud/helm/fbinternal-orc8r/Chart.yaml
  fbinternal/cloud/helm/fbinternal-orc8r/values.yaml
  feg/cloud/helm/feg-orc8r/Chart.lock
  feg/cloud/helm/feg-orc8r/Chart.yaml
  feg/cloud/helm/feg-orc8r/values.yaml
  lte/cloud/helm/lte-orc8r/Chart.lock
  lte/cloud/helm/lte-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/values.yaml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/docker/nginx/generate_nginx_configs.py
  orc8r/cloud/docker/nginx/templates/nginx.conf.j2
  orc8r/cloud/helm/orc8r/Chart.lock
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/configmap-nginx-etc.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/etc/_certs_nginx_proxy_ssl.conf.tpl
  orc8r/cloud/helm/orc8r/charts/nms/templates/magmalte-deployment.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/nginx-proxy-deployment.yaml
  orc8r/cloud/helm/orc8r/charts/nms/values.yaml
  orc8r/cloud/helm/orc8r/templates/bootstrapper.deployment.yaml
  orc8r/cloud/helm/orc8r/templates/certifier.deployment.yaml
  orc8r/cloud/helm/orc8r/templates/nginx.deployment.yaml
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/cloud/helm/orc8rlib/Chart.yaml
  orc8r/cloud/helm/orc8rlib/templates/_container.yaml
  orc8r/cloud/helm/orc8rlib/templates/_deployment.yaml
  wifi/cloud/helm/wifi-orc8r/Chart.lock
  wifi/cloud/helm/wifi-orc8r/Chart.yaml
  wifi/cloud/helm/wifi-orc8r/values.yaml
Labels: component: orc8r, component: feg, size/L, component: cwf

#10604 chore(pipelined): remove tunnel-id-map
  lte/gateway/python/magma/pipelined/app/ipv6_solicitation.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/start_pipelined.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
Labels: component: agw, size/S

#10584 fix(amf): AMF is crashing when a PDU-Establishment Request came with missing DNN in the IE.
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
Labels: component: agw, size/M

#10611 fix(ci): integ tests not running on correct commit
  .github/workflows/cwf-integ-test.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/S

#10311 chore(nms): upgrade pug from 2.0.3 to 3.0.1
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/L, ready2merge

#10602 fix(orc8r): bump RDS to 12.8 and add var to upgrade RDS immediately
  orc8r/cloud/deploy/terraform/orc8r-aws/db.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
Labels: component: orc8r, size/S

#10617 fix(ci): update firebase used sha
  .github/workflows/cwf-integ-test.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/S

#10474 fix(amf): ambr values of profile not being sent to sessiond.
  lte/gateway/c/core/oai/common/common_types.h
  lte/gateway/c/core/oai/lib/n11/M5GMobilityServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/M5GMobilityServiceClient.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_defs.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_client_servicer.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GNasEnums.h
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf_common_utils.cpp
Labels: component: agw, size/L, product: 5g sa, ready2merge

#10616 test(mme): Add unit test for IPCP PCO
  lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/spgw_task/test_pgw_pco.cpp
Labels: component: agw, size/L

#10345 chore(ci): fix vulnerability gorilla websocket version
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
Labels: size/XS, component: cwf

#10636 fix(ci): `magma/` is already included in `$MAGMA_ROOT`
  .devcontainer/Dockerfile
Labels: size/XS, ready2merge

#10168 fix(nms): Fix policy tracking type
  nms/packages/magmalte/app/views/traffic/PolicyTracking.js
Labels: component: nms, size/XS

#10564 feat(ci): Migrate release pipeline to GHA
  .github/workflows/build_all.yml
Labels: component: ci, size/L

#10085 feat(orc8r): K8s Include labels and annotations based on the image/chart being deployed
  orc8r/cloud/helm/orc8r/charts/metrics/templates/storeconfig-job.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/helpers/labels.tpl
  orc8r/cloud/helm/orc8r/charts/nms/templates/magmalte-deployment.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/magmalte-service.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/nginx-proxy-deployment.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/nginx-proxy-service.yaml
  orc8r/cloud/helm/orc8r/templates/_helpers.tpl
  orc8r/cloud/helm/orc8r/templates/accessd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/analytics.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/certifier.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/configurator.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/ctraced.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/device.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/directoryd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/dispatcher.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/eventd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/ingress.service.yaml
  orc8r/cloud/helm/orc8r/templates/metricsd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/nginx.deployment.yaml
  orc8r/cloud/helm/orc8r/templates/obsidian.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/orchestrator.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/service_registry.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/state.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/streamer.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/tenants.pdb.yaml
  orc8r/cloud/helm/orc8rlib/templates/_deployment.yaml
  orc8r/cloud/helm/orc8rlib/templates/_helpers.tpl
  orc8r/cloud/helm/orc8rlib/templates/_pdb.yaml
  orc8r/cloud/helm/orc8rlib/templates/_service.yaml
Labels: component: orc8r, size/L

#10627 fix(pipelined): fix typo in IPv6 solicitation handling.
  lte/gateway/python/magma/pipelined/app/ipv6_solicitation.py
Labels: component: agw, size/XS

#10635 fix(amf): PDU Session faiulre due to incorrect duplication PDU count
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/M

#10518 feat(agw): Add ghz docker files and playbooks
  experimental/cloudstrapper/playbooks/ghz-provision.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/setup-tests.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
  lte/gateway/docker/ghz/.env
  lte/gateway/docker/ghz/Dockerfile
  lte/gateway/docker/ghz/docker-compose.override.yaml
  lte/gateway/docker/ghz/docker-compose.yaml
  lte/gateway/docker/ghz/publish.sh
Labels: component: ci, size/L

#10577 test(agw): Adding S1AP unit tests for X2 handover and E-RAB related handlers
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.h
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
Labels: component: agw, size/L

#10649 fix(ci): typo in create release tag
  .github/workflows/build_all.yml
Labels: component: ci, size/S

#10623 chore(sessiond): add DISABLE_ASAN flag to cmake
  lte/gateway/c/session_manager/CMakeLists.txt
Labels: component: agw, size/S

#10625 test(mme): Add SPGW unit test for DNS, MTU and PCSCF request PCOs
  lte/gateway/c/core/oai/test/spgw_task/test_pgw_pco.cpp
Labels: component: agw, size/L

#10621 chore: add utility script to dev_tools/
  dev_tools/iwyu.imp
  dev_tools/minidump-2-core
Labels: size/XS

#10608 feat: migrate containerzed sessiond for AGW to be built with Bazel
  lte/gateway/docker/services/c/Dockerfile
Labels: component: ci, size/M

#10631 fix(magmad): Copy keys before iterating over service dictionary
  orc8r/gateway/python/magma/magmad/service_poller.py
Labels: component: orc8r, size/XS

#10656 chore(mme): Clean up unused code on emm_data_ctx
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
Labels: component: agw, size/XL

#10653 feat(agw): Add gHZ role to ansible for running load tests
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/run-tests.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
Labels: size/M

#10655 test(mme): Add SPGW unit tests for force push pco and nas signalling
  lte/gateway/c/core/oai/test/spgw_task/test_pgw_pco.cpp
Labels: component: agw, size/L

#10600 test(mme): Add new esm message encode and decode unit tests
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_sm_ies.c
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_esm_encode_decode.cpp
Labels: component: agw, size/XL

#10522 feat(agw): Added ipv6 paging support
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/S

#10243 feat: Add mme app latency metric
  lte/gateway/c/core/oai/include/service303_messages_types.h
  lte/gateway/c/core/oai/lib/message_utils/service303_message_utils.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/service303/service303_mme_stats.c
Labels: component: agw, size/S

#9757 chore: add bazel repository dependency for liblfds
  bazel/cpp_repositories.bzl
  bazel/external/liblfds.BUILD
  third_party/build/patches/liblfds/BUILD.bazel
Labels: component: ci, size/M

#10583 feat: Add Bazel configurations to build with LSAN
  .bazelrc
Labels: component: agw, size/M

#10668 test(mme): Add full encoding and decoding of esm msg with header
  lte/gateway/c/core/oai/tasks/nas/esm/msg/esm_msgDef.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_esm_encode_decode.cpp
Labels: component: agw, size/XL

#10665 test(mme): Add unit test for TAU procedure
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/XL

#10674 test(mme): Add SPGW unit test for suspend notification
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
Labels: component: agw, size/L

#10685 chore(agw): Dont opt-in logs that are filtered by Sentry
  orc8r/gateway/python/magma/magmad/metrics_collector.py
  orc8r/gateway/python/magma/state/state_replicator.py
Labels: component: orc8r, size/XS, ready2merge

#10698 fix(orc8r): Fix nginx container not starting due to bad env var
  orc8r/cloud/docker/docker-compose.yml
Labels: component: orc8r, size/S

#10539 feat(sessiond): Adding UE IPv6 and IPv4v6 address support in sessiond
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/test/Consts.h
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
  lte/gateway/python/scripts/smf_upf_integration_cli.py
Labels: component: agw, size/L

#10671 fix(sessiond): prevent to un-suspend if we receive several transient errors
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/ChargingGrant.h
  lte/gateway/c/session_manager/EnumToString.h
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: component: agw, size/M

#10686 chore: remove unused boost dependency
  WORKSPACE.bazel
  bazel/cpp_repositories.bzl
  cwf/gateway/docker/c/Dockerfile
  lte/gateway/docker/services/c/Dockerfile
  orc8r/gateway/c/common/config/BUILD.bazel
Labels: component: agw, component: ci, size/S, component: cwf

#10695 fix(agw): migrate orc8r/gateway/c to clang-11 google style
  .github/workflows/agw-workflow.yml
  lte/gateway/Makefile
  orc8r/gateway/c/common/async_grpc/includes/GRPCReceiver.h
  orc8r/gateway/c/common/config/MConfigLoader.cpp
  orc8r/gateway/c/common/config/ServiceConfigLoader.cpp
  orc8r/gateway/c/common/config/YAMLUtils.cpp
  orc8r/gateway/c/common/config/YAMLUtils.h
  orc8r/gateway/c/common/config/includes/MConfigLoader.h
  orc8r/gateway/c/common/config/includes/ServiceConfigLoader.h
  orc8r/gateway/c/common/config/test/test_mconfig_loader.cpp
  orc8r/gateway/c/common/config/test/test_yaml_utils.cpp
  orc8r/gateway/c/common/eventd/includes/EventdClient.h
  orc8r/gateway/c/common/logging/magma_logging.h
  orc8r/gateway/c/common/logging/magma_logging_init.h
  orc8r/gateway/c/common/sentry/SentryWrapper.cpp
  orc8r/gateway/c/common/sentry/includes/SentryWrapper.h
  orc8r/gateway/c/common/service303/MagmaService.cpp
  orc8r/gateway/c/common/service303/MetricsHelpers.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/ProcFileUtils.cpp
  orc8r/gateway/c/common/service303/ProcFileUtils.h
  orc8r/gateway/c/common/service303/includes/MagmaService.h
  orc8r/gateway/c/common/service303/includes/MetricsHelpers.h
  orc8r/gateway/c/common/service303/includes/MetricsRegistry.h
  orc8r/gateway/c/common/service303/includes/MetricsSingleton.h
  orc8r/gateway/c/common/service303/test/test_magma_service.cpp
  orc8r/gateway/c/common/service303/test/test_service303.cpp
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.cpp
  orc8r/gateway/c/common/service_registry/includes/ServiceRegistrySingleton.h
Labels: component: agw, component: ci, size/XL

#8929 fix(agw): Solve bug parsing result from ovsdb-client on GTPStatsCollector
  lte/gateway/python/magma/pipelined/gtp_stats_collector.py
Labels: component: agw, size/XS

#10703 fix(mme): Add unit test for paging
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/mock_tasks/s1ap_mock.cpp
Labels: component: agw, size/L

#10717 fix(orc8r): Fix mconfig sync panic due to nil NGC ptr
  lte/cloud/go/services/lte/servicers/builder_servicer.go
Labels: component: orc8r, size/S

#10495 feat(orc8r): setup for registration servicers
  orc8r/cloud/go/services/bootstrapper/const.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/storage.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/storage_test.go
  orc8r/lib/go/protos/bootstrapper.pb.go
  orc8r/protos/bootstrapper.proto
Labels: component: orc8r, size/XXL

#10723 fix(agw): fix dependency issue python3-websocket-client
  lte/gateway/python/setup.py
Labels: component: agw, size/XS

#10720 test(mme): Make option to run subset of OAI tests
  lte/gateway/Makefile
Labels: component: agw, size/XS

#10721 test(mme): Cut the execution time for test_mme_app by half
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/M

#10722 chore: Turn off codecov annotations
  codecov.yml
Labels: size/XS

#10641 chore(ci): Clean unused circle ci jobs
  .circleci/config.yml
Labels: component: ci, size/M

#10728 feat(orc8r): `CloudRegistration` and `client_api.go`
  orc8r/cloud/go/services/bootstrapper/client_api.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/cloud_registration.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/cloud_registration_test.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/nonce.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/nonce_test.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/time.go
Labels: component: orc8r, size/L, ready2merge

#10469 fix(subscriberdb): Handling of SUCI Extensions
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/gateway/python/magma/subscriberdb/crypto/EC.py
  lte/gateway/python/magma/subscriberdb/crypto/ECIES.py
  lte/gateway/python/magma/subscriberdb/crypto/utils.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
  lte/gateway/python/magma/subscriberdb/store/base.py
  lte/gateway/python/magma/subscriberdb/tests/crypto/test_ECIES.py
  lte/gateway/python/magma/subscriberdb/tests/rpc_tests.py
  lte/gateway/python/scripts/test_supi_decrypt_imsi_cli.py
  lte/gateway/python/scripts/test_supi_profile_cli.py
  lte/protos/subscriberdb.proto
Labels: component: orc8r, component: agw, size/XXL, ready2merge

#10557 chore(agw): implement shared mconfig and use it for Sentry config
  docs/readmes/contributing/contribute_id_mappings.md
  docs/readmes/lte/configure_sentry.md
  lte/gateway/configs/gateway.mconfig
  lte/gateway/python/magma/enodebd/main.py
  lte/gateway/python/magma/health/main.py
  lte/gateway/python/magma/kernsnoopd/main.py
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/monitord/main.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/policydb/main.py
  lte/gateway/python/magma/redirectd/main.py
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/subscriberdb/main.py
  orc8r/gateway/python/magma/common/sentry.py
  orc8r/gateway/python/magma/common/service.py
  orc8r/gateway/python/magma/common/tests/sentry_tests.py
  orc8r/gateway/python/magma/configuration/mconfig_managers.py
  orc8r/gateway/python/magma/configuration/mconfigs.py
  orc8r/gateway/python/magma/configuration/tests/mconfigs_tests.py
  orc8r/gateway/python/magma/ctraced/main.py
  orc8r/gateway/python/magma/directoryd/main.py
  orc8r/gateway/python/magma/eventd/main.py
  orc8r/gateway/python/magma/magmad/config_manager.py
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/state/main.py
Labels: component: orc8r, component: agw, component: docs, size/L, ready2merge

#10690 chore: Add dev registry to VMs
  orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
Labels: component: orc8r, size/XS

#10691 chore: Skip build on CI while integ testing
  circleci/fabfile.py
  lte/gateway/deploy/agw_install_specific.sh
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/M

#10706 fix(amf): Changing the hashtable implementation of amf_state_ue_id into map
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/test/amf/test_amf_map.cpp
Labels: component: agw, size/M

#10731 test(mme): Add set of enc/decoding tests for EMM module (information, uplink_nas, tau req, attach req)
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_cc_ies.c
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AttachRequest.c
  lte/gateway/c/core/oai/tasks/nas/emm/msg/TrackingAreaUpdateRequest.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/core/oai/tasks/nas/ies/Nonce.c
  lte/gateway/c/core/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_emm_decode.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_emm_encode_decode.cpp
Labels: component: agw, size/XL

#10740 fix: Typo in CI Fabfile
  circleci/fabfile.py
Labels: component: ci, size/XS

#10209 feat(orc8r): orc8r support for SUCI Extensions
  feg/cloud/go/services/feg/obsidian/models/suci_profile_swaggergen.go
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  lte/cloud/go/services/lte/obsidian/models/network_cellular_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/network_ngc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/suci_profile_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/validate.go
  lte/cloud/go/services/subscriberdb/load.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/protos/subscriberdb.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: agw, component: nms, component: feg, size/XXL, ready2merge

#10683 feat(mme): Send context release command on successful handover
  lte/gateway/c/core/oai/include/s1ap_messages_types.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover.py
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover_ping_pong.py
Labels: component: agw, size/L

#10744 Revert "chore: Add dev registry to VMs (#10690)"
  orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
Labels: size/XS

#10689 feat(agw): Support orchestration for containerised agw
  lte/gateway/deploy/agw_install_docker.sh
  lte/gateway/deploy/roles/agw_docker/tasks/main.yml
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
Labels: component: agw, size/M

#9985 fix(agw): Agw containerization fixes2
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
  lte/gateway/docker/docker-compose.yaml
Labels: component: agw, component: ci, size/M

#10742 test(mme): Include packet filter count in unit test NW initiated bearer activation
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
Labels: component: agw, size/S

#10642 feat: Add wrapper Make commands to run Bazel
  .bazelrc
  bazel/external/sentry_native.BUILD
  lte/gateway/Makefile
Labels: component: agw, size/L

#10747 test(mme): Reduce flakes due to late ITTI messages
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
Labels: component: agw, size/XS

#10750 fix(agw): Fix websocket-client pydep version mismatch
  lte/gateway/python/setup.py
Labels: component: agw, size/XS

#10748 test(mme): remove redundant calls and waits, add missing steps
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/M

#10711 feat(ci): more tags on images makes destinction easier
  .github/workflows/composite/docker-builder/action.yml
Labels: component: ci, size/XS, ready2merge

#10299 feat(feg): N7 Proxy SM Policy Delete implementation
  feg/gateway/services/n7_n40_proxy/n7/model_conversion.go
  feg/gateway/services/n7_n40_proxy/n7/model_conversion_test.go
  feg/gateway/services/n7_n40_proxy/servicers/session_controller.go
  feg/gateway/services/n7_n40_proxy/servicers/terminate_session.go
  feg/gateway/services/n7_n40_proxy/servicers/terminate_session_test.go
Labels: component: feg, size/L, ready2merge

#10755 chore(ci): Add Python Dependencies in Dockerfile
  .devcontainer/Dockerfile
Labels: size/XS, ready2merge

#10745 test(mme): Add further enc/decoding tests for emm messages
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/msg/ExtendedServiceRequest.c
  lte/gateway/c/core/oai/tasks/nas/emm/msg/TrackingAreaUpdateAccept.c
  lte/gateway/c/core/oai/tasks/nas/ies/TrackingAreaIdentityList.c
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_emm_encode_decode.cpp
Labels: component: agw, size/L

#10677 docs(agw): Sentry Documentation
  docs/docusaurus/versioned_docs/version-1.6.0/lte/configure_sentry.md
  docs/readmes/lte/configure_sentry.md
Labels: component: docs, size/M, ready2merge

#10726 chore(ci): Temporary on demand job for helm chart push with official …
  .github/workflows/helm-deploy-on-demand.yml
Labels: component: ci, size/S

#10749 chore: cleanup bazel build of sentry
  .bazelignore
  bazel/cpp_repositories.bzl
Labels: size/S

#10696 feat(session_proxy): add Requested Units to gy_cli
  feg/gateway/tools/gy_client_cli/main.go
Labels: component: feg, size/L

#10765 fix(feg): fix destroyConnection log nil pointer exception
  feg/gateway/diameter/connection.go
Labels: component: feg, size/S

#10453 fix(amf): AMF is sending UE Context Release command when there is a unsuccessful PDU session setup
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_client_servicer.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/XL, ready2merge

#10669 feat(ci): Add build of new agw container
  .github/workflows/build_all.yml
  .github/workflows/deploy-build-from-pr.yml
Labels: component: ci, size/L

#10769 chore: Update ghz API params on ansible
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
Labels: size/XS

#10308 feat(feg): N7 Proxy handle PCF initiated updated and terminate
  feg/gateway/sbi/gen.go
  feg/gateway/sbi/sbi.go
  feg/gateway/sbi/sbi_test.go
  feg/gateway/services/n7_n40_proxy/n7/model_conversion.go
  feg/gateway/services/n7_n40_proxy/n7/model_conversion_test.go
  feg/gateway/services/n7_n40_proxy/n7_n40_proxy/main.go
  feg/gateway/services/n7_n40_proxy/notify/notify_handler.go
  feg/gateway/services/n7_n40_proxy/notify/notify_handler_test.go
  feg/gateway/services/n7_n40_proxy/servicers/create_session_test.go
  feg/gateway/services/n7_n40_proxy/servicers/session_controller.go
  feg/gateway/services/n7_n40_proxy/servicers/terminate_session_test.go
Labels: component: feg, size/XL

#10684 fix(orc8r): fixed helm if condition for replicas
  orc8r/cloud/helm/orc8r/templates/accessd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/analytics.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/certifier.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/configurator.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/ctraced.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/device.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/directoryd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/dispatcher.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/eventd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/metricsd.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/obsidian.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/orchestrator.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/service_registry.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/state.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/streamer.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/tenants.pdb.yaml
  orc8r/cloud/helm/orc8rlib/templates/_pdb.yaml
Labels: component: orc8r, size/M

#10770 feat(orc8r): add `registration` servicer + have `registration` & `cloudRegistration` RPC serviced
  orc8r/cloud/configs/bootstrapper.yml
  orc8r/cloud/go/services/bootstrapper/bootstrapper/main.go
  orc8r/cloud/go/services/bootstrapper/config/keys.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/cloud_registration_test.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/registration.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/registration_test.go
Labels: component: orc8r, size/L, ready2merge

#10773 test(mme): Add MME_APP unit test for Auth and ICS failures
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/L

#10667 feat: build libfluid with Bazel
  bazel/cpp_repositories.bzl
  bazel/external/libfluid_base.BUILD
  bazel/external/libfluid_msg.BUILD
  third_party/build/patches/libfluid/libfluid_base_patches/BUILD.bazel
  third_party/build/patches/libfluid/libfluid_msg_patches/BUILD.bazel
Labels: component: ci, size/L

#10610 fix(ci): Fix for issue 10258, rename NR and RPR file names
  .github/workflows/build_all.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/python-workflow.yml
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/M

#10553 chore(orc8r): add feature to remove verbose protos from orc8r service…
  orc8r/lib/go/service/logcodec.go
  orc8r/lib/go/service/service.go
Labels: component: orc8r, size/L

#10558 feat(mme): Use control plane TEID coming from feg_relay
  lte/gateway/c/core/oai/include/s8_messages_types.h
  lte/gateway/c/core/oai/include/spgw_types.h
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_pdn_context.c
  lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_s11_handlers.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_csr.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_recv_grpc_messages.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
Labels: component: agw, size/XL

#10764 test(cwg): some improvements to cwf_integ_test (GenULTrafficBasedOnPolicyUsage)
  cwf/gateway/docker/docker-compose.integ-test.yml
  cwf/gateway/docker/docker-compose.override.yml
  cwf/gateway/integ_tests/assertions.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/gy_reauth_test.go
  cwf/gateway/integ_tests/test_runner.go
  cwf/gateway/registry/local_registry.go
  cwf/gateway/services/uesim/client_api.go
  cwf/gateway/services/uesim/servicers/uesim.go
  feg/cloud/go/protos/mock_core.pb.go
  feg/gateway/services/testcore/ocs/mock_ocs/ccr_handler.go
  feg/gateway/services/testcore/ocs/mock_ocs/ocs.go
  feg/protos/mock_core.proto
Labels: component: feg, size/XL, component: cwf

#10775 fix(orc8r): Updated Helm and Docker repo links for artifactory
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.custom
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
Labels: component: orc8r, size/XS

#10802 refactor: remove or rename TODO(reginawang3495)s
  orc8r/cloud/configs/state.yml
  orc8r/cloud/go/services/orc8r_worker/orc8r_worker/main.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton.go
  orc8r/cloud/go/services/state/indexer/reindex/versioner.go
Labels: component: orc8r, size/S

#10806 chore: address compilation warnings in orc8r/gateway/c
  orc8r/gateway/c/common/service303/MetricsHelpers.cpp
  orc8r/gateway/c/common/service303/test/test_service303.cpp
Labels: component: agw, size/XS

#10804 test(mme): add unit test for paging failure for dedicated bearer
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/L

#10789 feat(orc8r): optional agw device on register from northbound endpoints
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  cwf/cloud/go/services/cwf/obsidian/models/conversion.go
  cwf/cloud/go/services/cwf/obsidian/models/cwf_gateway_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/mutable_cwf_gateway_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/swagger.v1.yml
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  feg/cloud/go/services/feg/obsidian/models/conversion.go
  feg/cloud/go/services/feg/obsidian/models/federation_gateway_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/mutable_federation_gateway_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  lte/cloud/go/services/lte/obsidian/models/lte_gateway_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/mutable_lte_gateway_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/models/registration_info_swaggergen.go
  orc8r/cloud/go/models/swagger-common.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/bootstrapper/bootstrapper/main.go
  orc8r/cloud/go/services/bootstrapper/client_api.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/cloud_registration.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/cloud_registration_test.go
  orc8r/cloud/go/services/bootstrapper/test_init/test_service_init.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/conversion.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/magmad_gateway_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers_test.go
  wifi/cloud/go/services/wifi/obsidian/models/conversion.go
  wifi/cloud/go/services/wifi/obsidian/models/mutable_wifi_gateway_swaggergen.go
  wifi/cloud/go/services/wifi/obsidian/models/swagger.v1.yml
  wifi/cloud/go/services/wifi/obsidian/models/wifi_gateway_swaggergen.go
Labels: component: orc8r, component: nms, component: feg, size/XL, component: cwf

#10811 docs: RDS Upgrade Documentation Fix
  docs/docusaurus/i18n/en.json
  docs/docusaurus/versioned_docs/version-1.6.0/orc8r/RDS_upgrade.md
Labels: component: docs, size/S

#10062 feat(orc8r): Add verbosity control to orc8r for lte/{network_id}/subscribers (fixes #3421)
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/obsidian/models/paginated_subscriber_ids_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/L

#10779 fix(orc8r): Upgraded docker images to 1.6.1
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: component: orc8r, size/XS

#10816 test(mme): Extend MME config unit tests with display
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_config.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_sgw_config.cpp
Labels: component: agw, size/S

#10817 test(mme): Add mobile reachability and implicit detach timer test
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/L

#10634 feat(feg_relay): replace c_agw_teid for feg_relay generated teid
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
  feg/protos/s8_proxy.proto
Labels: component: feg, size/L

#10736 chore(ci): update devcontainer image in CI
  .devcontainer/devcontainer.json
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel-cache-push.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/S, ready2merge

#10826 feat(ci): upload logs for lte-integ-test on failure
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/S

#10512 feat(orc8r): Periodic_Update_Changes_for_Orc8r
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
Labels: component: agw, size/L, ready2merge

#10823 fix(amf): criticality of different IE's changed for spirent related optimization.
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
Labels: component: agw, priority: high, size/XS, product: 5g sa

#10830 docs(agw): Added how to change MME IP address in docs
  docs/readmes/faq/faq_magma.md
Labels: component: docs, size/XS

#10812 test(mme): Add MME_APP unit tests for path switch request
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/mock_tasks/s1ap_mock.cpp
Labels: component: agw, size/L

#10818 feat(orc8r): Updated NMS domain name for certificate generation
  orc8r/cloud/helm/orc8r/charts/certs/templates/nms-certificate.yaml
Labels: component: orc8r, size/XS

#10778 fix(orc8r): Upgraded EKS version to 1.21
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.community
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.custom
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.poc
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.production
  orc8r/cloud/deploy/terraform/orc8r-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
Labels: component: orc8r, size/XS

#10197 fix(amf): Handling of SUPI Registration
  lte/gateway/c/core/oai/include/amf_app_messages_def.h
  lte/gateway/c/core/oai/include/amf_app_messages_types.h
  lte/gateway/c/core/oai/lib/n11/CMakeLists.txt
  lte/gateway/c/core/oai/lib/n11/M5GSUCIRegistrationServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/M5GSUCIRegistrationServiceClient.h
  lte/gateway/c/core/oai/lib/n11/amf_client_proto_msg_to_itti_msg.cpp
  lte/gateway/c/core/oai/lib/n11/amf_client_proto_msg_to_itti_msg.h
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/core/oai/tasks/amf/amf_client_servicer.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.h
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GSMobileIdentity.h
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
  lte/gateway/c/core/oai/test/n11/CMakeLists.txt
  lte/gateway/c/core/oai/test/n11/test_auth_service_client.cpp
Labels: component: agw, size/XXL

#10837 fix: Typo in CI Fabfile - REVERT
  circleci/fabfile.py
  lte/gateway/deploy/agw_install_specific.sh
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/M

#10666 feat(orc8r): Create playbook to update control_proxy targets for new orc8r
  experimental/cloudstrapper/playbooks/agw-config-update.yaml
  experimental/cloudstrapper/playbooks/roles/agw-config-update/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/agw-config-update/vars/main.yaml
Labels: size/L

#10250 feat(orc8r): Added token-based REST API auth
  cwf/cloud/go/go.sum
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  feg/gateway/go.sum
  lte/cloud/go/go.sum
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/configs/certifier.yml
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/docker/controller/supervisord.conf
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/models/swagger-common.yml
  orc8r/cloud/go/obsidian/access/rest_middleware.go
  orc8r/cloud/go/obsidian/access/tests/rest_middleware_test.go
  orc8r/cloud/go/obsidian/access/tests/utils.go
  orc8r/cloud/go/obsidian/reverse_proxy/reverse_proxy.go
  orc8r/cloud/go/obsidian/reverse_proxy/reverse_proxy_test.go
  orc8r/cloud/go/obsidian/server/server.go
  orc8r/cloud/go/obsidian/swagger/spec/combine.go
  orc8r/cloud/go/obsidian/swagger/spec/testdata/out.yml.golden
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/certifier/certifier/main.go
  orc8r/cloud/go/services/certifier/client_api.go
  orc8r/cloud/go/services/certifier/config.go
  orc8r/cloud/go/services/certifier/constants/constants.go
  orc8r/cloud/go/services/certifier/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/certifier/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/certifier/obsidian/models/gen.go
  orc8r/cloud/go/services/certifier/obsidian/models/policy_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/resource_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/resources_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/certifier/obsidian/models/user_swaggergen.go
  orc8r/cloud/go/services/certifier/protos/certifier.pb.go
  orc8r/cloud/go/services/certifier/protos/certifier.proto
  orc8r/cloud/go/services/certifier/protos/helpers.go
  orc8r/cloud/go/services/certifier/servicers/certifier.go
  orc8r/cloud/go/services/certifier/storage/storage.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/certifier/test_utils/test_utils.go
  orc8r/cloud/go/services/certifier/tokens.go
  orc8r/cloud/go/swagger/spec.go
  orc8r/cloud/go/tools/accessc/handlers/add_admin_token.go
  orc8r/cloud/go/tools/combine_swagger/testdata/common/common.yml
  orc8r/cloud/go/tools/combine_swagger/testdata/monolithic.yml.golden
  orc8r/cloud/go/tools/combine_swagger/testdata/standalone.yml.golden
  orc8r/cloud/go/tools/swaggergen/generate/generate.go
  orc8r/cloud/helm/orc8r/templates/certifier.deployment.yaml
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/cloud/test/go.sum
  orc8r/lib/go/registry/registry.go
  wifi/cloud/go/go.sum
Labels: component: orc8r, component: nms, component: feg, size/XXL, component: cwf

#10842 chore(mme): Move proto to GUTI and ECGI converters to base class
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/include/state_converter.h
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.h
Labels: component: agw, size/M

#10815 test(mme): Add final set of EMM encoding decoding messages unit tests
  lte/gateway/c/core/oai/tasks/nas/ies/ShortMac.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_emm_encode_decode.cpp
Labels: component: agw, size/L

#10327 fix(agw): Remove cyclic dependency between Logging and ITTI
  lte/gateway/c/core/oai/lib/itti/intertask_interface.c
  lte/gateway/c/core/oai/lib/itti/signals.c
Labels: component: agw, size/S

#10845 docs: Document TSC norms
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_tsc_norms.md
Labels: component: docs, size/M

#10851 chore(ci): modify build command in bazel cache push job
  .github/workflows/bazel-cache-push.yml
Labels: component: ci, size/XS

#10840 feat(agw): restart services on shared config changes
  .github/workflows/agw-workflow.yml
  feg/gateway/go.mod
  feg/gateway/go.sum
  orc8r/gateway/python/magma/magmad/config_manager.py
  orc8r/gateway/python/magma/magmad/tests/config_manager_tests.py
Labels: component: orc8r, component: ci, component: feg, size/M

#10551 feat(orc8r): Disable logging and metrics in orc8r helm chart if staging is enabled
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/efs.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/blue-green/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/helm.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/k8s.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/logging.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/storage.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/yace.tf
Labels: component: orc8r, size/M

#10847 chore(mobilityd): Reduce loglevel for client errors releasing IP
  lte/gateway/python/magma/mobilityd/ip_address_man.py
Labels: component: agw, size/XS, ready2merge

#10189 test(agw): Adding new TCs for testing EPS bearer context IE in TAU
  lte/gateway/python/integ_tests/s1aptests/test_eps_bearer_context_status_ded_bearer_deact.py
  lte/gateway/python/integ_tests/s1aptests/test_eps_bearer_context_status_def_bearer_deact.py
Labels: component: agw, size/XL

#10821 fix(amf): fixed ambr calculations for different ambr related parameters.
  lte/gateway/c/core/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_session_context.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_pdu_session_configs.h
  lte/gateway/c/core/oai/tasks/amf/include/amf_smf_session_context.h
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_common_utils.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
Labels: component: agw, priority: high, size/L, product: 5g sa

#10758 feat(orc8r): Added UT for nil NGC ptr fix and updated example values in swagger
  lte/cloud/go/services/lte/obsidian/models/gateway_ngc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, size/L

#10399 test(agw): Add state converter test for SPGW UE context
  lte/gateway/c/core/oai/test/spgw_task/state_creators.cpp
  lte/gateway/c/core/oai/test/spgw_task/state_creators.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
Labels: component: agw, size/L

#10605 feat(amf): amf_app_state_converter to support Stateless feature
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/include/map.h
  lte/gateway/c/core/oai/include/state_converter.h
  lte/gateway/c/core/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf_app_state_converter.cpp
Labels: component: agw, size/XL

#10848 test(mme): Add S1 Handover MME unit tests
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/mock_tasks/s1ap_mock.cpp
Labels: component: agw, size/L

#10831 chore(agw): use version scheme that is understood by sentry
  .github/workflows/build_all.yml
  circleci/fabfile.py
  docs/readmes/lte/build_install_magma_pkg_in_agw.md
  lte/gateway/fabfile.py
  lte/gateway/release/build-magma.sh
  orc8r/tools/fab/pkg.py
Labels: component: orc8r, component: agw, component: docs, component: ci, size/M, ready2merge

#10781 fix(sessiond): remove hard coding for SSC_MODE_3 in sessiond and fill…
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: component: agw, size/L, product: 5g sa, ready2merge

#10766 feat(ci): Check if PR is rebased on top of Master
  .github/workflows/check-rebase.yml
Labels: component: ci, size/M

#10881 fix(mobilityd): Less strict APN parsing in GetSubscriberIPTable
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
Labels: component: agw, size/XS

#10838 feat(feg_hello): counters for agw-orc8r-feg latency
  cwf/cloud/go/go.mod
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.mod
  fbinternal/cloud/go/go.sum
  fbinternal/cloud/go/services/testcontroller/storage/sql_nodes.go
  fbinternal/cloud/go/services/testcontroller/storage/sql_test.go
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  feg/cloud/go/protos/hello.pb.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/hello_relay.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/relay_test.go
  feg/gateway/go.mod
  feg/gateway/services/feg_hello/servicers/hello.go
  feg/protos/hello.proto
  lte/cloud/go/go.mod
  lte/cloud/go/go.sum
  lte/gateway/python/scripts/feg_hello_cli.py
Labels: component: orc8r, component: agw, component: feg, size/L, component: cwf

#9951 feat(agw): Added handling of EPS bearer context status IE in TAU request
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/include/s11_messages_types.h
  lte/gateway/c/core/oai/include/sgw_ie_defs.h
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/core/oai/tasks/s11/s11_ie_formatter.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
  lte/protos/oai/mme_nas_state.proto
Labels: component: orc8r, component: agw, size/XXL

#10866 feat(agw): Mock out the gateway.mconfig dependency while running update test for ConfigManager
  .github/workflows/agw-workflow.yml
  orc8r/gateway/python/magma/magmad/tests/config_manager_tests.py
Labels: component: orc8r, component: ci, size/S

#10897 test(mme): unit test for duplicate attach in idle mode
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/L

#10792 feat(orc8r): Terraform Integration with cert-manager
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/cert-manager.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/charts/certs/templates/nms-certificate.yaml
Labels: component: orc8r, size/L

#10301 feat(feg): N7 Proxy SM Policy Update request implementation
  feg/gateway/services/n7_n40_proxy/n7/model_conversion.go
  feg/gateway/services/n7_n40_proxy/n7/model_conversion_test.go
  feg/gateway/services/n7_n40_proxy/servicers/session_controller.go
  feg/gateway/services/n7_n40_proxy/servicers/update_session.go
  feg/gateway/services/n7_n40_proxy/servicers/update_session_test.go
Labels: component: feg, size/XL, ready2merge

#10895 chore: add update multiple fegs to TeraVM fabfile
  ci-scripts/teravm/fabfile.py
  ci-scripts/teravm/fabfile_teravm_conf.json
Labels: component: ci, size/M

#10920 docs: Sentry Documentation
  docs/docusaurus/i18n/en.json
  docs/docusaurus/versioned_docs/version-1.5.0/lte/configure_sentry.md
  docs/docusaurus/versioned_docs/version-1.5.0/lte/integrate_sentry.md
  docs/docusaurus/versioned_sidebars/version-1.6.0-sidebars.json
Labels: component: docs, size/L

#10752 fix(sessiond): Default AMBR value support in Sessiond and Pipelined.
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
  lte/gateway/python/scripts/smf_upf_integration_cli.py
Labels: component: agw, size/S, product: 5g sa

#10901 docs: magma gtp gateway
  docs/readmes/proposals/p023_magma_gtp_gateway.md
Labels: component: docs, size/L

#10867 test(mme): Expand unit test for Nas state converter
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/include/state_converter.h
  lte/gateway/c/core/oai/lib/bstr/bstrlib.c
  lte/gateway/c/core/oai/tasks/nas/nas_procedures.c
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/core/oai/test/nas/test_nas_converter.cpp
Labels: component: agw, size/M

#10889 chore: update bazel version to 4.2.2
  .bazelversion
Labels: size/XS

#10941 fix(s8_proxy): add fields to protos to inject control plane teid
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/protos/s8_proxy.proto
Labels: component: feg, size/L
