Repository magma/magma, pull requests merged in 2021-11, with the labels that each got.

#9869 feat(agw): fix mme config for containerized agw
  lte/gateway/deploy/roles/agw_docker/tasks/main.yml
  lte/gateway/deploy/roles/agw_docker/templates/env.j2
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/docker/.env
  lte/gateway/docker/docker-compose.yaml
  lte/gateway/docker/mme/configs/mme.conf
  lte/gateway/docker/mme/configs/spgw.conf
  lte/gateway/docker/readme.md
  lte/gateway/docker/services/c/Dockerfile
Labels: component: agw, component: ci

#9992 fix(feg_relay): fix wrong context on getUniqueSgwCTeid
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
Labels: component: feg

#9953 feat(ci): Group all builds in on workflow
  .github/workflows/agw-workflow.yml
  .github/workflows/build_all.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
Labels: component: ci

#9925 chore(agw): migrate non-core/session_manager includes to full paths
  lte/gateway/c/connection_tracker/src/CMakeLists.txt
  lte/gateway/c/connection_tracker/src/EventTracker.cpp
  lte/gateway/c/connection_tracker/src/EventTracker.h
  lte/gateway/c/connection_tracker/src/PacketGenerator.cpp
  lte/gateway/c/connection_tracker/src/PacketGenerator.h
  lte/gateway/c/connection_tracker/src/main.cpp
  lte/gateway/c/li_agent/src/CMakeLists.txt
  lte/gateway/c/li_agent/src/InterfaceMonitor.cpp
  lte/gateway/c/li_agent/src/InterfaceMonitor.h
  lte/gateway/c/li_agent/src/MobilitydClient.cpp
  lte/gateway/c/li_agent/src/MobilitydClient.h
  lte/gateway/c/li_agent/src/PDUGenerator.cpp
  lte/gateway/c/li_agent/src/PDUGenerator.h
  lte/gateway/c/li_agent/src/ProxyConnector.cpp
  lte/gateway/c/li_agent/src/Utilities.cpp
  lte/gateway/c/li_agent/src/main.cpp
  lte/gateway/c/li_agent/src/test/LIAgentdMocks.h
  lte/gateway/c/li_agent/src/test/test_pdu_generator.cpp
  lte/gateway/c/sctpd/src/CMakeLists.txt
  lte/gateway/c/sctpd/src/sctp_assoc.cpp
  lte/gateway/c/sctpd/src/sctp_connection.cpp
  lte/gateway/c/sctpd/src/sctp_connection.h
  lte/gateway/c/sctpd/src/sctp_desc.cpp
  lte/gateway/c/sctpd/src/sctp_desc.h
  lte/gateway/c/sctpd/src/sctpd.cpp
  lte/gateway/c/sctpd/src/sctpd_downlink_impl.cpp
  lte/gateway/c/sctpd/src/sctpd_downlink_impl.h
  lte/gateway/c/sctpd/src/sctpd_event_handler.cpp
  lte/gateway/c/sctpd/src/sctpd_event_handler.h
  lte/gateway/c/sctpd/src/sctpd_uplink_client.cpp
  lte/gateway/c/sctpd/src/test/test_event_handler.cpp
  lte/gateway/c/sctpd/src/test/test_sctp_desc.cpp
  lte/gateway/c/sctpd/src/util.cpp
  lte/gateway/c/sctpd/src/util.h
Labels: component: agw, size/L

#9777 feat(agw): harden access to agw local IP
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/access_control.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_access_control.AccessControlTestLocalIpBlockLTE.test_blocking_ip_match.snapshot
  lte/gateway/python/magma/pipelined/tests/test_access_control.py
Labels: component: agw

#10004 feat(mobilityd): Add support for static IPv6 address
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ip_allocator_pool.py
  lte/gateway/python/magma/mobilityd/ip_allocator_static.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  lte/gateway/python/magma/mobilityd/tests/test_static_ipv6_alloc.py
Labels: component: agw

#10009 fix(ci): Name collision in image archives
  .github/workflows/build_all.yml
  .github/workflows/deploy-build-from-pr.yml
Labels: size/XS

#9781 feat(mme): Add ipv6 msg updates
  lte/gateway/c/core/oai/common/conversions.c
  lte/gateway/c/core/oai/include/gtpv1u_types.h
  lte/gateway/c/core/oai/include/sgw_config.h
  lte/gateway/c/core/oai/include/spgw_types.h
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_sgw_config.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_dedicated_bearer.cpp
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
  lte/protos/oai/sgw_state.proto
  lte/protos/oai/spgw_state.proto
Labels: component: agw

#9986 fix(pipelined): Set tunnel out id in reg
  lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_multi_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows_ipv6.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_add_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_discard_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_mme_flow_dl.ClassifierMmeTest.test_resume_tunnel_ip_flow_dl.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_traffic.GTPTrafficTest.test_traffic_flows.snapshot
Labels: component: agw

#9775 feat(mme): SubscriberDB-Ext, Handling of Subscriber validation based on forbidden network type
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/gateway/python/magma/subscriberdb/metrics.py
  lte/gateway/python/magma/subscriberdb/processor.py
  lte/gateway/python/magma/subscriberdb/protocols/diameter/application/s6a.py
  lte/gateway/python/magma/subscriberdb/protocols/diameter/avp.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
  lte/gateway/python/magma/subscriberdb/subscription/__init__.py
  lte/gateway/python/magma/subscriberdb/subscription/utils.py
  lte/gateway/python/magma/subscriberdb/tests/processor_tests.py
  lte/protos/subscriberdb.proto
Labels: component: agw

#10007 fix(mme): Disabling S1 handover integ test from sanity list
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw

#10011 chore(mme): Update TEIDs on LTE calls only during session creation
  lte/gateway/c/core/oai/lib/3gpp/3gpp_23.401.h
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
Labels: component: agw

#10016 chore(mme): Backport PR 10011
  lte/gateway/c/core/oai/lib/3gpp/3gpp_23.401.h
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
Labels: size/S

#9767 refactor(orc8r): Add obsidian middleware to properly log and report non-2xx responses
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/node_handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/rating_groups_handlers.go
  lte/cloud/go/services/smsd/servicers/smsd_rest.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  orc8r/cloud/go/obsidian/handler.go
  orc8r/cloud/go/obsidian/server/server.go
  orc8r/cloud/go/obsidian/swagger/handlers/handlers.go
  orc8r/cloud/go/obsidian/tests/unit_test_utils.go
  orc8r/cloud/go/service/service.go
  orc8r/cloud/go/service/service_test.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/eventd/log/handlers/log_handlers.go
  orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/metricsd/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_receiver_handlers.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_silencing_handlers.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/promo_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/about_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/common.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/entity_handler_factory.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_command_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handler_factory.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/network_handler_factory.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/network_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/upgrade_handlers.go
  orc8r/cloud/go/services/tenants/obsidian/handlers/handlers.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers.go
Labels: component: orc8r, component: feg, component: cwf

#9882 docs: edited pyenv set up
  docs/readmes/basics/prerequisites.md
Labels: component: docs

#10010 chore: add logic to also upload cache for devcontainer
  .github/workflows/bazel-cache-push.yml
Labels: component: ci

#9999 feat(ci): Cancel old jobs when new commits lands on PR
  .github/workflows/agw-workflow.yml
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/bazel.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dco-check.yml
  .github/workflows/dockerfile-health.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/lint-clang-format.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/publish-helmcharts-to-artifactory.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/semantic-pr.yml
Labels: component: ci

#10020 chore(agw): Update Vscode c++ preferences
  .vscode/c_cpp_properties.json
Labels: size/XS

#9930 chore: apply iwyu to orc8r/gateway/c/common
  orc8r/gateway/c/common/config/MConfigLoader.cpp
  orc8r/gateway/c/common/config/ServiceConfigLoader.cpp
  orc8r/gateway/c/common/config/YAMLUtils.cpp
  orc8r/gateway/c/common/config/YAMLUtils.h
  orc8r/gateway/c/common/config/includes/MConfigLoader.h
  orc8r/gateway/c/common/config/includes/ServiceConfigLoader.h
  orc8r/gateway/c/common/config/test/BUILD.bazel
  orc8r/gateway/c/common/config/test/test_mconfig_loader.cpp
  orc8r/gateway/c/common/eventd/EventdClient.cpp
  orc8r/gateway/c/common/logging/magma_logging_init.h
  orc8r/gateway/c/common/sentry/SentryWrapper.cpp
  orc8r/gateway/c/common/service303/MagmaService.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/includes/MagmaService.h
  orc8r/gateway/c/common/service303/includes/MetricsRegistry.h
  orc8r/gateway/c/common/service303/includes/MetricsSingleton.h
  orc8r/gateway/c/common/service303/test/test_service303.cpp
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.cpp
  orc8r/gateway/c/common/service_registry/includes/ServiceRegistrySingleton.h
  orc8r/gateway/c/common/service_registry/test/test_service_registry.cpp
  tools/iwyu.imp
Labels: component: agw

#10024 chore(sessiond): reorder includes, self-generate all protos
  lte/gateway/c/session_manager/CMakeLists.txt
Labels: component: agw, size/S

#10008 chore(mobilityd): Add support to list IPv6 blocks
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  lte/gateway/python/scripts/mobility_cli.py
  lte/protos/mobilityd.proto
Labels: component: agw

#10030 fix: try out bazel cache deletion in GHA
  .github/workflows/bazel.yml
Labels: component: ci

#9942 test(mme): Adding S1ap integration tests for T3460 and T3470
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_identity_timer_3470_expiry.py
  lte/gateway/python/integ_tests/s1aptests/test_smc_timer_3460_expiry.py
Labels: component: agw

#10040 docs: update doc on VSCode workflow
  docs/readmes/contributing/contribute_vscode.md
Labels: size/M

#10022 feat(ci): test worker agent for integrating test infra with CI
  ci-scripts/test_agent/FirebaseClient.py
  ci-scripts/test_agent/FirebaseConfig.json
  ci-scripts/test_agent/Tester.py
  ci-scripts/test_agent/main.py
Labels: component: ci

#10041 chore: add clangd-12 to magma vm and activate extension on startup
  .vscode/tasks.json
  lte/gateway/deploy/roles/magma/tasks/main.yml
  vscode-workspaces/workspace.magma-vm-workspace.code-workspace
Labels: component: agw

#9978 fix(amf): Changing the default parameter for amfName in gate
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_config.cpp
  lte/gateway/configs/gateway.mconfig
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/XS

#10043 fix(ci): Fix GCC warnings job not handling filenames with spaces
  .github/workflows/gcc-problems.yml
Labels: component: ci

#10049 fix(ci): Further fix GCC warnings job errs
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/XS

#10053 chore(orc8r): Add build.py --tidy
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  feg/gateway/Makefile
  lte/cloud/go/go.sum
  orc8r/cloud/docker/build.py
  orc8r/cloud/go/Makefile
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/tools.go
  wifi/cloud/go/go.sum
Labels: component: orc8r, component: feg, size/S, component: cwf

#10060 chore(orc8r): Remove dead code for old nghttpx proxy
  orc8r/cloud/docker/proxy/0001-Fix-get_x509_serial-for-long-serial-numbers.patch
  orc8r/cloud/docker/proxy/Dockerfile
  orc8r/cloud/docker/proxy/create_test_proxy_certs
  orc8r/cloud/docker/proxy/magma_headers.rb
  orc8r/cloud/docker/proxy/run_nghttpx.py
  orc8r/cloud/docker/proxy/squid.conf
  orc8r/cloud/docker/proxy/supervisord.conf
  orc8r/cloud/docker/proxy/templates/nghttpx_clientcert.conf.j2
  orc8r/cloud/docker/proxy/templates/nghttpx_common.conf.j2
  orc8r/cloud/docker/proxy/templates/nghttpx_open.conf.j2
Labels: component: orc8r

#10054 docs(orc8r): Document controller.crt SAN requirement
  docs/readmes/orc8r/deploy_install.md
Labels: component: docs

#9899 fix(nms): Adjust alert rule for S1 setup failure #9896
  nms/app/packages/magmalte/alerts/lteAlerts.js
Labels: size/XS

#10067 fix: GHA error on scheduled bazel build runs
  .github/workflows/bazel.yml
Labels: component: ci

#10065 fix: update vscode doc and clean up tasks/launch config
  .vscode/launch.json
  .vscode/tasks.json
  docs/readmes/contributing/contribute_vscode.md
Labels: component: docs

#10068 ci: update devcontainer to contain xo binary
  .devcontainer/Dockerfile
Labels: size/XS

#9872 feat(agw): Add service level memory and cpu metrics
  orc8r/gateway/python/magma/magmad/metrics.py
  orc8r/lib/go/protos/metricsd.pb.go
  orc8r/protos/metricsd.proto
Labels: component: orc8r

#9947 fix(agw): Corrected IMEISV conversion
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp
Labels: component: agw

#10055 docs: Fix broken Slack invite link
  README.md
Labels: size/XS

#9865 test(mme): Initial framework for SPGW procedure unit tests
  lte/gateway/c/core/oai/include/sgw_context_manager.h
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_config.c
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/spgw_task/spgw_test.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
Labels: component: agw

#9983 fix(cloud): Adding staging domain SANs to self-signed certificates
  orc8r/cloud/deploy/scripts/self_sign_certs.sh
Labels: component: orc8r

#9234 chore(ci): Delete migrated agw jobs
  .circleci/config.yml
Labels: component: ci, size/L, devops-migration

#9406 chore(ci): Complete migration of nms job
  .circleci/config.yml
Labels: component: ci

#9883 fix(mme): PDUSessionResourceSetupReq and PDUSessionEstablishmentAccept clubbed into Single NGAP Message
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
Labels: component: agw

#10036 fix(orc8r): fixed fab command to connect gateway
  orc8r/tools/fab/dev_utils.py
Labels: component: orc8r

#10061 chore(orc8r): Fix stutter in config.ConfigMap
  cwf/gateway/services/uesim/servicers/config.go
  cwf/gateway/tools/uesim_cli/main.go
  feg/gateway/policydb/policydb_test.go
  feg/gateway/registry/registry_test.go
  feg/gateway/services/testcore/hss/servicers/config.go
  orc8r/cloud/go/services/metricsd/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/state/state/main.go
  orc8r/cloud/go/services/streamer/integ_test.go
  orc8r/gateway/go/service_registry/registry.go
  orc8r/lib/go/registry/cloud_connection.go
  orc8r/lib/go/registry/service_registry.go
  orc8r/lib/go/registry/shared_cloud_conn.go
  orc8r/lib/go/service/config/config_map.go
  orc8r/lib/go/service/config/service_config.go
  orc8r/lib/go/service/service.go
Labels: component: orc8r, component: feg, component: cwf

#10051 fix(orc8r): Set correct default image tag for v1.6 branch
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: size/XS

#9778 fix(nms): Added environment variables on Helm charts to be displayed on NMS
  cwf/cloud/helm/cwf-orc8r/Chart.lock
  cwf/cloud/helm/cwf-orc8r/Chart.yaml
  fbinternal/cloud/helm/fbinternal-orc8r/Chart.lock
  fbinternal/cloud/helm/fbinternal-orc8r/Chart.yaml
  feg/cloud/helm/feg-orc8r/Chart.lock
  feg/cloud/helm/feg-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/Chart.lock
  lte/cloud/helm/lte-orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/Chart.lock
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8rlib/Chart.yaml
  orc8r/cloud/helm/orc8rlib/templates/_container.yaml
  wifi/cloud/helm/wifi-orc8r/Chart.lock
  wifi/cloud/helm/wifi-orc8r/Chart.yaml
Labels: component: orc8r, component: feg, component: cwf

#10048 fix(mme): Memory leak in SPGW state converter and cleanup
  lte/gateway/c/core/oai/lib/pcef/PCEFClient.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
Labels: component: agw

#10046 feat(feg): base accounting heartbeat feature
  feg/cloud/go/services/basic_acct/servicers/participants.go
  feg/cloud/go/services/basic_acct/servicers/service.go
  feg/gateway/services/aaa/base_acct/client_api.go
  feg/gateway/services/aaa/base_acct/heartbeat.go
  feg/gateway/services/aaa/base_acct/heartbeat_reset_go1_15.go
  feg/gateway/services/aaa/base_acct/heartbeat_reset_prego1_15.go
  feg/gateway/services/aaa/servicers/accounting.go
  feg/gateway/services/aaa/servicers/accounting_test.go
Labels: component: feg

#10070 chore: mark service303 test as flaky
  orc8r/gateway/c/common/service303/test/BUILD.bazel
Labels: component: agw

#10063 fix(mme): fix the Ubuntu18 OAI build
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: ci

#10088 chore(pipelined): ipv6-solicitation: remove dependency on tun-id map.
  lte/gateway/python/magma/pipelined/app/ipv6_solicitation.py
Labels: component: agw

#10119 fix(agw): Allow wider network range for host-only interfaces
  .github/workflows/build_all.yml
Labels: component: ci

#9892 feat(orc8r): add bootstrap metrics to determine which networks are active
  cwf/cloud/go/go.mod
  cwf/cloud/go/go.sum
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
  fbinternal/cloud/go/go.mod
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  lte/cloud/go/go.mod
  lte/cloud/go/go.sum
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper.go
  orc8r/cloud/test/go.sum
  wifi/cloud/go/go.mod
  wifi/cloud/go/go.sum
Labels: component: orc8r, component: feg, component: cwf

#9926 chore(agw): fully specify orc8r/gw/c/common included paths
  orc8r/gateway/c/common/async_grpc/CMakeLists.txt
  orc8r/gateway/c/common/async_grpc/GRPCReceiver.cpp
  orc8r/gateway/c/common/config/CMakeLists.txt
  orc8r/gateway/c/common/config/MConfigLoader.cpp
  orc8r/gateway/c/common/config/ServiceConfigLoader.cpp
  orc8r/gateway/c/common/config/YAMLUtils.cpp
  orc8r/gateway/c/common/config/test/test_mconfig_loader.cpp
  orc8r/gateway/c/common/config/test/test_yaml_utils.cpp
  orc8r/gateway/c/common/eventd/CMakeLists.txt
  orc8r/gateway/c/common/eventd/EventdClient.cpp
  orc8r/gateway/c/common/eventd/includes/EventdClient.h
  orc8r/gateway/c/common/logging/CMakeLists.txt
  orc8r/gateway/c/common/logging/magma_logging_init.h
  orc8r/gateway/c/common/sentry/CMakeLists.txt
  orc8r/gateway/c/common/sentry/SentryWrapper.cpp
  orc8r/gateway/c/common/service303/CMakeLists.txt
  orc8r/gateway/c/common/service303/MagmaService.cpp
  orc8r/gateway/c/common/service303/MetricsHelpers.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/ProcFileUtils.cpp
  orc8r/gateway/c/common/service303/includes/MetricsSingleton.h
  orc8r/gateway/c/common/service303/test/test_magma_service.cpp
  orc8r/gateway/c/common/service303/test/test_metrics.cpp
  orc8r/gateway/c/common/service303/test/test_service303.cpp
  orc8r/gateway/c/common/service_registry/CMakeLists.txt
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.cpp
  orc8r/gateway/c/common/service_registry/includes/ServiceRegistrySingleton.h
  orc8r/gateway/c/common/service_registry/test/test_service_registry.cpp
Labels: component: agw

#10127 fix(ci): fix virtualization in macos runner
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci

#9936 feat(orc8r): add a reindexer singleton
  cwf/cloud/go/go.sum
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  feg/gateway/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/services/state/indexer/reindex/reindexer.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_queue.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_queue_test.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go
  orc8r/cloud/go/services/state/state/main.go
  orc8r/cloud/go/services/state/test_init/test_service_init.go
  orc8r/cloud/test/go.sum
  wifi/cloud/go/go.sum
Labels: component: orc8r, component: feg, component: cwf

#10057 ci: Add help comment for Markdown lint check failure
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/docs-workflow.yml
Labels: component: ci

#9979 feat(mme): Update slice descriptor in ics message
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
Labels: component: agw

#10130 chore(nms): Mark NMS bindings as generated
  .gitattributes
  .gitignore
Labels: size/XS

#10111 chore: fix bazel schedule job
  .github/workflows/bazel.yml
Labels: component: ci, size/S

#10115 ci: migrate CI devcontainer hash forward
  .devcontainer/devcontainer.json
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel-cache-push.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci

#10031 feat(ci): Cleanup of github actions workflows (group jobs in same gha runner)
  .github/workflows/agw-workflow.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/feg-workflow.yml
Labels: component: ci, size/L

#10128 fix: Fix continous deletion of default drop flow
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/tests/test_rule_mappers.py
Labels: size/L

#9580 feat(agw): Added code to support deletion of dedicated bearer for roaming UE
  lte/gateway/c/core/oai/include/grpc_service.h
  lte/gateway/c/core/oai/include/s11_messages_types.h
  lte/gateway/c/core/oai/include/s8_messages_def.h
  lte/gateway/c/core/oai/include/s8_messages_types.h
  lte/gateway/c/core/oai/lib/s8_proxy/S8Client.cpp
  lte/gateway/c/core/oai/lib/s8_proxy/S8Client.h
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.h
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/grpc_service/S8ServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/S8ServiceImpl.h
  lte/gateway/c/core/oai/tasks/grpc_service/grpc_service.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_s11_handlers.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/mock_tasks/CMakeLists.txt
  lte/gateway/c/core/oai/test/mock_tasks/grpc_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/mock_tasks/sgw_s8_mock.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_recv_grpc_messages.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
Labels: component: agw

#10097 fix(agw): Persistent IPv6 config
  lte/gateway/Vagrantfile
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, component: ci

#10145 chore(pipelined): Add support for IPv6 IP solicitation over IPv6 GTP …
  lte/gateway/python/magma/pipelined/app/ipv6_solicitation.py
Labels: component: agw

#10155 fix(pipelined): Add grpc error code for timeouts
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: size/S

#10154 fix(pipelined): Add grpc error code for timeouts
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw

#10157 fix(agw): prevent crash.Wrap from swallowing panics
  src/go/crash/crash.go
  src/go/crash/crash_test.go
Labels: size/S, ready2merge

#10152 chore(ci): Add lab instance for testing
  .circleci/config.yml
Labels: component: ci

#10029 chore(agw): Enable pylint test for kernsnoopd
  lte/gateway/python/magma/kernsnoopd/handlers.py
  lte/gateway/python/magma/kernsnoopd/snooper.py
  lte/gateway/python/magma/kernsnoopd/tests/byte_counter_tests.py
  lte/gateway/python/magma/tests/pylint_tests.py
Labels: component: agw

#9956 fix(amf): fix for the regression failure testcases
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
Labels: component: agw

#10162 chore: Only deploy AGW if integ-test passes
  .circleci/config.yml
Labels: component: ci

#9964 feat(orc8r): create new shared mconfig with Sentry info
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/api/v1/go/models/network_sentry_config.go
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer_test.go
  orc8r/lib/go/protos/mconfig/mconfigs.pb.go
  orc8r/protos/mconfig/mconfigs.proto
Labels: component: orc8r, component: agw

#10129 ci(agw): Hil PoC
  ci-scripts/test_agent/FirebaseClient.py
  ci-scripts/test_agent/Tester.py
  ci-scripts/test_agent/main.py
Labels: component: ci, size/L

#10167 fix(mme): add return type to the inline function
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_statistics.c
Labels: component: agw

#9645 feat(amf): DNN from subscriberdb being matched with the one requested by UE.
  lte/gateway/c/core/oai/include/amf_config.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/c/core/oai/tasks/amf/amf_recv.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GULNASTransport.h
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GULNASTransport.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/util_s6a_update_location.cpp
  lte/gateway/c/core/oai/test/amf/util_s6a_update_location.h
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw

#10176 fix(agw): fixed shared mconfig renaming issue
  feg/gateway/go.sum
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, component: feg

#10114 feat: add an agw-workflow job to run c_cpp unit tests with bazel
  .bazelrc
  .github/workflows/agw-workflow.yml
  .github/workflows/lint-clang-format.yml
  codecov.yml
  lte/gateway/Makefile
Labels: component: agw, component: ci, size/L

#10159 chore(mme): New unit tests for mme_app and code clean up
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_proc.h
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw

#10153 fix(agw): packaging of python dep
  lte/gateway/python/setup.py
Labels: component: agw

#10161 fix(monitord): Register operational states callback correctly
  lte/gateway/python/magma/monitord/main.py
Labels: component: agw, ready2merge

#10033 chore(smsd-relay): Don't log an error in happy path
  lte/gateway/python/magma/smsd/relay.py
Labels: component: agw, ready2merge

#9456 fix: Fix show-tech tool checksum errors
  show-tech/constants.yml
  show-tech/roles/commands/tasks/main.yml
  show-tech/roles/commands/tasks/ubuntu.yml
  show-tech/roles/files/tasks/main.yml
Labels: ready2merge, component: show-tech

#9965 feat(ci): PR push to CI registry
  .github/workflows/deploy-build-from-pr.yml
Labels: component: ci

#10142 chore: print out diff on error for isort and autopep8 for python format check
  .github/workflows/python-workflow.yml
Labels: component: ci, size/S

#10165 chore(ci): Add a check to make sure all buildifier lint warnings are …
  .github/workflows/bazel.yml
  BUILD.bazel
  cpp_repositories.bzl
  feg/gateway/services/aaa/protos/BUILD.bazel
  orc8r/protos/BUILD.bazel
  third_party_repositories.bzl
Labels: component: orc8r, component: ci, component: feg

#10171 fix(ci): fix concurency group for comment job on PR
  .github/workflows/comment-pr-on-check-failure.yml
Labels: component: ci

#9876 test(mobilityd): add new makefile target to exectute specific unit tests
  lte/gateway/Makefile
  lte/gateway/python/Makefile
Labels: component: agw

#10013 feat(ci): Add firebase integration to build workflow
  .github/workflows/build_all.yml
  ci-scripts/firebase_publish.py
Labels: component: ci

#10183 fix(ci): Fix for issue 9474 Avoid posting test results if tests are skipped
  .github/workflows/agw-workflow.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/python-workflow.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci

#10200 fix(ci): delete old publish helm chart workflow
  .github/workflows/build_all.yml
  .github/workflows/publish-helmcharts-to-artifactory.yml
Labels: component: ci

#10201 fix(ci): do not trigger comment on PR job when trigger is push
  .github/workflows/comment-pr-on-check-failure.yml
Labels: component: ci

#10194 fix(ci): Propagate PR number to comment lint failure
  .github/workflows/docs-workflow.yml
Labels: component: ci

#10047 test(mme): Add further s1ap mme handlers tests
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.h
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
Labels: component: agw

#10192 chore(ci): bundle c cpp codecov into a single job
  .github/workflows/agw-workflow.yml
  codecov.yml
Labels: component: ci

#10179 chore(pipelined): Remove old tests, cleanup test lib
  docs/readmes/lte/pipelined_tests.md
  lte/gateway/python/magma/pipelined/tests/app/flow_query.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/app/table_isolation.py
  lte/gateway/python/magma/pipelined/tests/old_tests/test_controller.py
  lte/gateway/python/magma/pipelined/tests/old_tests/test_inout.py
  lte/gateway/python/magma/pipelined/tests/test_arp.py
Labels: component: agw, component: docs

#10206 chore(ci): Disable build on PR of agw
  .github/workflows/build_all.yml
  .github/workflows/deploy-build-from-pr.yml
Labels: component: ci

#10186 fix(mme): Bug fix in nw initiated bearer deactivation
  lte/gateway/c/core/oai/tasks/grpc_service/SpgwServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
Labels: component: agw

#10202 fix(mme): Backport PR 10186
  lte/gateway/c/core/oai/tasks/grpc_service/SpgwServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.c
Labels: size/XS

#10177 test(mme): Add SPGW unit tests for modify bearer and delete session
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
Labels: component: agw

#10146 feat(orc8r): reindexer singleton getBatches on new getJobs to reindex
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_queue_test.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go
Labels: component: orc8r

#9989 feat(orc8r): Support registering dev VM with remote controller
  lte/gateway/dev_tools.py
  orc8r/tools/fab/dev_utils.py
Labels: component: orc8r, component: agw

#10203 fix(orc8r): Fix the file run.py to able to execute run.py -- metrics
  orc8r/cloud/docker/run.py
Labels: component: orc8r

#10210 Quentin fix agw build
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#10213 fix(sessiond): fix race condition on handle_activate_ue_flows_callback
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
Labels: size/L

#10224 chore(ci): increase timeout for sessiond tests to 20 min
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS

#10233 feat(orc8r): Support Minikube Orc8r with local container registry
  docs/readmes/orc8r/dev_minikube.md
  orc8r/tools/docker/publish.sh
Labels: component: orc8r, component: docs

#10225 docs(agw): add instructions for testing individual Python services
  docs/readmes/lte/dev_unit_testing.md
Labels: component: docs

#10228 fix(agw): Update s1ap_utils restart_services cmd to exec_command
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw

#10231 fix(ci): agw build ninja sentry flake
  lte/gateway/Vagrantfile
Labels: component: ci, size/XS

#10073 feat(agw): Config Service for src/go
  src/go/agwd/config/BUILD.bazel
  src/go/agwd/config/config.go
  src/go/agwd/config/config_test.go
  src/go/agwd/config/mock_config/BUILD.bazel
  src/go/agwd/config/mock_config/mock_config.go
  src/go/agwd/config/testdata/accessd_config.json
  src/go/agwd/main.go
  src/go/agwd/server/BUILD.bazel
  src/go/agwd/server/server.go
  src/go/protos/magma/config/BUILD.bazel
  src/go/protos/magma/config/config.pb.go
  src/go/protos/magma/config/config.proto
  src/go/protos/magma/config/config_grpc.pb.go
  src/go/protos/magma/config/mock_config/BUILD.bazel
  src/go/protos/magma/config/mock_config/mock_config_grpc.pb.go
  src/go/protos/protos.go
  src/go/service/BUILD.bazel
  src/go/service/config/BUILD.bazel
  src/go/service/config/config.go
  src/go/service/config/config_server.go
  src/go/service/config/config_server_integ_test.go
  src/go/service/router_test.go
Labels: size/XXL, ready2merge

#10208 refactor(pipelined): arp control simplification.
  lte/gateway/python/magma/pipelined/app/arp.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp.ArpTableTest.test_stray_arp_drop.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp.ArpTableTest.test_ue_to_uplink_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp.ArpTableTest.test_uplink_to_ue_arp.snapshot
Labels: component: agw

#10100 chore(eventd): Log unexpected errors in eventd server in opt-in mode
  orc8r/gateway/python/magma/eventd/rpc_servicer.py
Labels: component: orc8r, size/XS, ready2merge

#10241 chore(ci): disable cwf integ test notifications
  .circleci/config.yml
  .github/workflows/cwf-integ-test.yml
Labels: component: ci

#10256 fix(ci): typo in path filter for cloud workflows
  .github/workflows/cloud-workflow.yml
Labels: component: ci

#10251 docs: update quick_start_guide.md with chrome security bypass
  docs/readmes/basics/quick_start_guide.md
Labels: component: docs, ready2merge

#10255 fix(ci/firebase) Always push to firebase. Even on failure
  .github/workflows/build_all.yml
Labels: component: ci

#10240 docs: slight improvements to minikube deploy docs
  docs/readmes/orc8r/dev_minikube.md
Labels: component: docs, ready2merge

#10216 fix(ci/firebase) Use build_id as key to report
  ci-scripts/test_agent/FirebaseClient.py
Labels: component: ci

#10242 fix(pipelined): Flush IPv6 route on bridge reset.
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: component: agw

#10248 fix(ci): Re-run failed tests up to 3 times on failure on CI
  .github/workflows/cwf-integ-test.yml
  cwf/gateway/fabfile.py
  cwf/gateway/go.sum
Labels: component: ci, component: cwf

#10244 fix(amf): fix for the issue #10185
  lte/gateway/c/core/oai/lib/3gpp/3gpp_38.413.h
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
Labels: component: agw

#10249 chore: mark set_session_manager_handler_test as flaky
  lte/gateway/c/session_manager/test/BUILD.bazel
Labels: component: agw

#10265 feat: Add a workspace file to cover all go directories
  orc8r/lib/go/go.sum
  vscode-workspaces/multiroot-go.code-workspace
Labels: component: orc8r

#10275 fix(mme): correct S8a proto generation for grpc_service
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
Labels: component: agw

#10270 chore(mme): migrate non-system includes to use of quotes
  lte/gateway/c/core/oai/include/state_manager.h
  lte/gateway/c/core/oai/lib/itti/intertask_interface_init.h
  lte/gateway/c/core/oai/lib/itti/intertask_interface_types.h
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/spgw_service_handler.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_hss_reset.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_reset.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.h
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GPayloadContainer.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/core/oai/tasks/s6a/s6a_cancel_loc.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.h
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/itti/test_itti.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/ngap/mock_utils.h
Labels: component: agw, size/M

#10184 chore(mme): Remove unused function from SPGW context manager
  lte/gateway/c/core/oai/include/sgw_context_manager.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
Labels: component: agw

#10261 refactor(pipelined): Remove egres flows from ARP controller.
  lte/gateway/python/magma/pipelined/app/arp.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp.ArpTableTest.test_stray_arp_drop.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp.ArpTableTest.test_ue_to_uplink_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp.ArpTableTest.test_uplink_to_ue_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_mtr_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_stray_arp_drop.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_ue_to_uplink_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTest.test_uplink_to_ue_arp.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_arp_non_nat.ArpTableTestRouterIP.test_uplink_to_ue_arp_router_mode.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout.InOutTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_inout.InOutTestLTE.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_ue_passthrough.UEMacAddressTest.test_passthrough_rules.snapshot
  lte/gateway/python/magma/pipelined/tests/test_inout.py
  lte/gateway/python/magma/pipelined/tests/test_ue_passthrough.py
  lte/gateway/python/magma/pipelined/utils.py
Labels: component: agw

#10113 chore(directoryd): enable selective opt-in logging to Sentry for directoryd
  orc8r/gateway/python/magma/directoryd/rpc_servicer.py
Labels: component: orc8r

#10110 chore(ctraced): Log unexpected errors in ctraced server in opt-in mode
  orc8r/gateway/python/magma/ctraced/rpc_servicer.py
Labels: component: orc8r

#10211 fix(sessiond): fix race condition on handle_activate_ue_flows_callback
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
Labels: component: agw

#10264 fix(agw): Updating import path for load test protos
  lte/gateway/python/load_tests/common.py
  lte/gateway/python/load_tests/loadtest_mobilityd.py
  lte/gateway/python/load_tests/loadtest_pipelined.py
  lte/gateway/python/load_tests/loadtest_sessiond.py
Labels: component: agw

#10278 fix(feg): Incorrect conversion between integer types
  feg/gateway/tools/hello_cli/main.go
  feg/gateway/tools/s6a_cli/main.go
  feg/gateway/tools/swx_cli/main.go
Labels: component: feg, ready2merge

#10274 fix(feg): Incorrect conversion between integer types
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/tgpp/utils.go
  feg/gateway/tools/gw_csfb_service_cli/main.go
Labels: component: feg, ready2merge

#10245 ci(agw): Python3 is required in Bazel builds
  .devcontainer/Dockerfile
  experimental/bazel-base/Dockerfile
Labels: component: ci, size/S, ready2merge

#10125 chore(state): enable selective opt-in logging to Sentry for state service
  orc8r/gateway/python/magma/state/garbage_collector.py
  orc8r/gateway/python/magma/state/state_replicator.py
Labels: component: orc8r, ready2merge

#10315 chore(ci): Always push test results and logs even with failure
  .github/workflows/cwf-integ-test.yml
Labels: component: ci

#10321 chore: remove code review for generated files
  .gitattributes
  CODEOWNERS
Labels: size/XS

#10290 test(mme): network initiated detach timer expirations
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw

#10095 fix(agw): Fixing service request metrics count on Grafana
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  nms/packages/magmalte/grafana/dashboards/Dashboards.js
Labels: component: agw, component: nms

#10324 chore(mme): clean up oai-mme cmake files
  lte/gateway/c/core/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/service303/CMakeLists.txt
  lte/gateway/c/core/oai/test/sgw_s8_task/CMakeLists.txt
Labels: component: agw, size/S

#10296 refactor: rename storeImpl to store
  orc8r/cloud/go/services/state/indexer/reindex/store.go
Labels: component: orc8r

#10288 fix:(CI/Firebase) Clean AGW artifacts pushed to firebase
  .github/workflows/build_all.yml
  ci-scripts/firebase_publish.py
Labels: component: ci, size/M

#10335 chore(mme): Remove unused dump functions
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
Labels: component: agw

#10292 chore(mme): remove possible redundancy at grpc_service cmake
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
Labels: component: agw

#10317 fix(cwg): guard cwf-integ-test assertions from out of index
  cwf/gateway/integ_tests/assertions.go
Labels: component: cwf

#10334 feat(ci): Add FEG build artifacts to build info
  .github/workflows/build_all.yml
  ci-scripts/firebase_publish.py
Labels: component: ci, size/S
