Repository magma/magma, pull requests merged in 2021-09, with the labels that each got.

#8853 docs(orc8r): Proposal Doc for eSIM API Integration
  docs/readmes/proposals/p019_esim_mgmt_integration.md
Labels: component: docs, size/L

#8745 chore(nms): Remove circular imports of magmalte package
  nms/package.json
  nms/packages/magmalte/app/components/cwf/CWFEditGatewayDialog.js
  nms/packages/magmalte/app/components/cwf/CWFSections.js
  nms/packages/magmalte/app/components/feg/FEGGatewayDialog.js
  nms/packages/magmalte/app/components/feg/FEGSections.js
  nms/packages/magmalte/app/components/layout/useSections.js
  nms/packages/magmalte/app/components/master/Index.js
  nms/packages/magmalte/app/components/rhino/RhinoSections.js
  nms/packages/magmalte/app/components/wifi/WifiConfig.js
  nms/packages/magmalte/app/components/wifi/WifiDeviceDialog.js
  nms/packages/magmalte/app/components/wifi/WifiDeviceFields.js
  nms/packages/magmalte/app/components/wifi/WifiMeshDialog.js
  nms/packages/magmalte/app/components/wifi/WifiNetworkConfig.js
  nms/packages/magmalte/app/components/wifi/WifiSections.js
  nms/packages/magmalte/app/master.js
  nms/yarn.lock
Labels: component: nms, size/L

#8584 feat(amf): Paging 3513 timer support
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
Labels: component: agw, size/M, product: 5g sa

#8737 feat(amf): T3592 Timer support
  lte/gateway/c/core/oai/tasks/amf/amf_app_timer_management.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_timer_management.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
Labels: component: agw, size/L, product: 5g sa

#8913 chore(mme): Migrate remaining NAS timers to ZMQ
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_timer_management.h
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_data.h
  lte/gateway/c/core/oai/tasks/nas/esm/esm_data_context.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.cpp
Labels: component: agw, size/L

#8907 chore: Commit all formatting changes one last time before making it m…
  .github/workflows/python-formatting-check.yml
  lte/gateway/deploy/roles/magma/files/service.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
  lte/gateway/python/magma/enodebd/tests/baicells_qafb_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_tests.py
  lte/gateway/python/magma/enodebd/tests/enodeb_status_tests.py
  lte/gateway/python/magma/kernsnoopd/snooper.py
  lte/gateway/python/magma/monitord/icmp_job.py
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/ng_manager/node_state_manager.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/test_arp.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_internal_pkt_ipfix_export.py
  lte/gateway/python/magma/subscriberdb/crypto/milenage.py
  lte/gateway/python/magma/subscriberdb/metrics.py
  lte/gateway/python/precommit.py
  lte/gateway/python/scripts/state_cli.py
  orc8r/gateway/python/magma/magmad/metrics_collector.py
  orc8r/gateway/python/scripts/health_cli.py
Labels: component: orc8r, component: agw, component: ci, size/L

#8893 chore: upgrade sentry-native version to 0.4.12
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  third_party/build/bin/sentry-native-build.sh
Labels: component: agw, component: ci, size/XS

#8889 chore: clean up debian/ubuntu references from ansible
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  orc8r/tools/ansible/roles/python_dev/tasks/main.yml
Labels: component: orc8r, component: agw, size/L

#8723 docs: Design proposal for AGW L3 transport
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/assets/agw_ipsec_tun1.png
  docs/readmes/assets/agw_wg_tun1.png
  docs/readmes/proposals/p020_sgi_tunnel_transport.md
Labels: component: docs, size/L

#8616 feat(agw): bazel-ify SessionD
  .bazel-cache-repo/.gitignore
  .bazel-cache/.gitignore
  .bazelrc
  .gitignore
  WORKSPACE.bazel
  experimental/bazel-base/Dockerfile
  experimental/bazel-base/README.md
  experimental/bazel-base/docker-compose.yml
  feg/gateway/services/aaa/protos/BUILD.bazel
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/c/session_manager/SpgwServiceClient.cpp
  lte/gateway/c/session_manager/test/BUILD.bazel
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/protos/BUILD.bazel
  orc8r/gateway/c/common/BUILD.bazel
  orc8r/protos/BUILD.bazel
  third_party/cpp_redis.BUILD
  third_party/system_libraries.BUILD
  third_party/zlib.BUILD
  third_party_repositories.bzl
Labels: component: orc8r, component: agw, component: feg, size/XXL

#8736 feat(amf): Registration Reject with cause: UEIllegal
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.501.h
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
Labels: component: agw, type: feature, size/S, product: 5g sa

#8726 feat(agw): introduce AGW L3 transport
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/deploy/roles/magma/files/magma-setup-wg.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/datapath_setup.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: ci, size/L

#8849 feat(mme): Support for PCO with DNS option in amf
  lte/gateway/c/core/oai/common/rfc_1332.h
  lte/gateway/c/core/oai/include/amf_config.h
  lte/gateway/c/core/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/c/core/oai/tasks/amf/amf_session_manager_pco.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_session_manager_pco.h
  lte/gateway/c/core/oai/tasks/nas5g/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GPDUSessionEstablishmentAccept.h
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GPDUSessionEstablishmentRequest.h
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GProtocolConfigurationOptions.h
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentAccept.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentRequest.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GProtocolConfigurationOptions.cpp
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
  lte/gateway/c/core/oai/test/amf/util_nas5g_registration_pkt.cpp
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/XL, product: 5g sa

#8703 docs: P010 vendor neutral DP proposal update
  docs/readmes/proposals/media/p010_vendor_neutral_dp_image3.png
  docs/readmes/proposals/media/p010_vendor_neutral_dp_image5.png
  docs/readmes/proposals/p010_vendor_neutral_dp.md
Labels: size/L

#8916 fix: Modify python formatting job to run on all PRs
  .github/workflows/python-workflow.yml
Labels: component: ci, size/S

#8542 docs: clarify non-debug build option
  docs/readmes/lte/build_install_magma_pkg_in_agw.md
Labels: size/XS

#8930 fix(pipelined): Handle ovs poll multi reply
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
Labels: component: agw, size/S

#8897 fix(orc8r): Simplify CountEntities
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/configurator/client_api.go
  orc8r/cloud/go/services/configurator/servicers/northbound.go
  orc8r/cloud/go/services/configurator/storage/sql.go
  orc8r/cloud/go/services/configurator/storage/sql_entity_load_helpers.go
  orc8r/cloud/go/services/configurator/storage/storage.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
Labels: component: orc8r, component: agw, component: nms, size/M, ready2merge

#8933 fix(mme): Add residual T3422
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
  lte/gateway/c/core/oai/tasks/nas/nas_procedures.c
Labels: component: agw, size/S

#8918 fix(ci): add sctpd scope for semantic pr
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/XS

#8493 feat(amf): Authentication Reject
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.501.h
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.h
Labels: component: agw, type: feature, size/M, product: 5g sa, ready2merge

#8522 feat(amf): Support for Invalid/unsupported ue security capabilities
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GUESecurityCapability.h
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GUESecurityCapability.cpp
Labels: component: agw, size/M, product: 5g sa

#8944 feat(agw): create wireguard tunnel for PGW.
  lte/gateway/c/core/oai/include/sgw_config.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/deploy/roles/magma/files/magma-create-gtp-port.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: ci, size/M

#8949 chore(mme): Migrate bearer activation and deactivation timers to zmq
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_location_update.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_timer.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_timer_management.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_timer_management.h
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Authentication.c
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_data_context.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.h
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr_context.h
  lte/gateway/c/core/oai/tasks/nas/esm/esm_information.c
  lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/core/oai/tasks/nas/nas_procedures.c
  lte/gateway/c/core/oai/tasks/nas/nas_procedures.h
  lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c
  lte/gateway/c/core/oai/tasks/nas/util/nas_timer.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_nw_triggered_delete_last_pdn.py
Labels: component: agw, size/XL

#8941 docs: correct hanging URL text on p014
  docs/readmes/proposals/p014_proposal_process.md
Labels: component: docs, size/XS

#8967 fix(ci): https://liblfds.org website certificate expired on Sep 5th 2021
  .devcontainer/Dockerfile
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, component: ci, size/S

#8746 feat(orc8r): orc8r cost reduction
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.poc
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.production
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
Labels: component: orc8r, size/L

#6859 docs(agw): Add KB AGW health check
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/howtos/troubleshooting/agw_healthcheck.md
Labels: component: docs, size/L, ready2merge

#8974 fix(pipelined): fix vlan match
  lte/gateway/python/magma/pipelined/app/inout.py
Labels: component: agw, size/XS, apply-v1.7

#8976 fix(pipelined): backport-1.5 (#8974): fix vlan match
  lte/gateway/python/magma/pipelined/app/inout.py
Labels: component: agw, component: cwag, size/XS

#8975 fix(pipelined): backport-1.6 (#8974): fix vlan match
  lte/gateway/python/magma/pipelined/app/inout.py
Labels: component: agw, component: cwag, size/XS, apply-v1.6

#8939 feat(amf): service reject handling changes
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.501.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/core/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/core/oai/tasks/nas5g/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/nas5g/include/AmfMessage.h
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GServiceReject.h
  lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GGprsTimer2.h
  lte/gateway/c/core/oai/tasks/nas5g/src/AmfMessage.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GServiceReject.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GGprsTimer2.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
Labels: component: agw, size/XL, product: 5g sa

#8957 fix(mme): gTEID changed from octet string to uint32 in AMF and NGAP
  lte/gateway/c/core/oai/common/common_defs.h
  lte/gateway/c/core/oai/include/amf_app_messages_types.h
  lte/gateway/c/core/oai/lib/n11/M5GMobilityServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/M5GMobilityServiceClient.h
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_smfDefs.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/test/n11/test_smf_service_client.cpp
Labels: component: agw, size/L, product: 5g sa

#8993 fix(ci): website certificate expired on Sep 5th 2021
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: agw, component: ci, size/XS

#8995 revert(agw): Inject state sync interval from orc8r into agw (#8…
  cwf/gateway/integ_tests/gateway.mconfig
  cwf/gateway/integ_tests/gateway.mconfig.idle_timer
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/state.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/orc8r/const.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/network_handlers_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/conversion.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/conversion_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/defaults.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/network_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/serdes.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/state_config_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/orchestrator/obsidian/models/validate.go
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer_test.go
  orc8r/gateway/python/magma/state/state_replicator.py
  orc8r/lib/go/protos/mconfig/mconfigs.pb.go
  orc8r/protos/mconfig/mconfigs.proto
Labels: component: orc8r, component: agw, component: cwag, size/XL, component: cwf

#8968 fix: Fix space in feedback request form
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/XS

#8979 fix(agw): Misc minor eNB fixes
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/logger.py
  lte/gateway/python/magma/enodebd/stats_manager.py
Labels: component: agw, size/S

#8958 fix(amf): fix to free the memory allocated for the ue context
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
Labels: component: agw, size/M, product: 5g sa, ready2merge

#9007 fix(mme): add integ test for failed nw initiated detach and fix stats
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_nw_initiated_detach_fail.py
Labels: component: agw, size/L

#9002 fix(mme): Fixing SEGV on implicit detach of unknown GUTI attach
  lte/gateway/c/core/oai/tasks/nas/emm/Identification.c
Labels: component: agw, size/XS

#9019 feat(ci): Turn up clang-format linter Github Action
  .github/workflows/lint-clang-format.yml
Labels: component: ci, size/S

#9001 revert(agw): Inject state sync interval from orc8r into agw (#8…
  cwf/gateway/integ_tests/gateway.mconfig
  cwf/gateway/integ_tests/gateway.mconfig.idle_timer
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/state.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/orc8r/const.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/network_handlers_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/conversion.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/conversion_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/defaults.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/network_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/serdes.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/state_config_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/orchestrator/obsidian/models/validate.go
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer_test.go
  orc8r/gateway/python/magma/state/state_replicator.py
  orc8r/lib/go/protos/mconfig/mconfigs.pb.go
  orc8r/protos/mconfig/mconfigs.proto
Labels: component: orc8r, component: agw, component: cwag, size/XL, component: cwf

#8928 feat(agw): Golang experiment initial commit
  src/go/README.md
  src/go/accessd/main.go
  src/go/accessd/server/server.go
  src/go/go.mod
  src/go/go.sum
  src/go/log/log.go
  src/go/log/log_test.go
  src/go/log/mock_logger_test.go
  src/go/log/zap/zap.go
  src/go/log/zap/zap_integ_test.go
  src/go/log/zap/zap_test.go
  src/go/protos/magma/sctpd/sctpd.pb.go
  src/go/protos/magma/sctpd/sctpd_grpc.pb.go
  src/go/protos/protos.go
  src/go/service/sctpd/proxy_uplink_server.go
  src/go/tools.go
Labels: size/XXL

#8942 feat(ci): Add golangci-lint GH Action for review annotations
  .github/workflows/golangci-lint.yml
Labels: component: ci, size/S

#9021 chore: Address Python Formatting check from PR9007
  lte/gateway/python/integ_tests/s1aptests/test_attach_nw_initiated_detach_fail.py
Labels: component: agw, size/XS

#9023 chore: update python formatting doc and PR failure comment
  .github/workflows/comment-pr-on-check-failure.yml
  lte/gateway/docker/python-precommit/README.md
Labels: component: agw, component: ci, size/S

#9024 fix: apply Magma's clang-format spec to two outliers
  lte/gateway/c/core/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/session_manager/RedisMap.hpp
Labels: component: agw, size/M

#9032 chore: cleanup reviewdog github workflows
  .github/workflows/cpplint.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/hadolint.yml
  .github/workflows/misspell.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/shellcheck.yml
  .github/workflows/wemake-python-styleguide.yml
  .github/workflows/yamlint.yml
Labels: component: ci, size/L

#9017 fix(mme): Fix for downlink traffic issue
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
Labels: type: bug, component: agw, priority: high, size/S, product: 5g sa

#9041 chore: default all reviewdog annotations to be github-pr-check except…
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/S

#9027 chore(agw): add configuration for controlling GTP-U checksum
  lte/gateway/c/core/oai/include/sgw_config.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/deploy/roles/magma/files/magma-create-gtp-port.sh
Labels: component: agw, size/M

#9003 feat(agw): Add support for new managed eNB: FreedomFiOne
  lte/gateway/configs/enodebd.yml
  lte/gateway/python/magma/enodebd/data_models/data_model.py
  lte/gateway/python/magma/enodebd/device_config/configuration_init.py
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/devices/device_map.py
  lte/gateway/python/magma/enodebd/devices/device_utils.py
  lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_impl.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/tests/enodeb_acs_states_tests.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enb_acs_builder.py
Labels: component: agw, size/XXL

#9045 fix: fix bad yaml commit in reviewdog workflow
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/S

#9033 fix(ci): lint-clang-format always runs
  .github/workflows/lint-clang-format.yml
Labels: component: ci, size/S

#9050 docs: Add a section in bazel setup guide on setting Magma root
  experimental/bazel-base/README.md
Labels: size/S

#9046 chore(feg): add lte_auth_next_seq to HSS and add some logs to feg and…
  feg/gateway/configs/hss.yml
  feg/gateway/go.mod
  feg/gateway/services/s6a_proxy/servicers/ai.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy.go
  feg/gateway/services/testcore/hss/servicers/config.go
  feg/gateway/services/testcore/hss/servicers/message.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  src/go/go.mod
Labels: component: agw, component: feg, size/M

#8750 docs(nms): Improve NMS development READMEs
  nms/README.md
  nms/packages/magmalte/README.md
Labels: component: nms, size/L

#9030 ci: turn up go test / build coverage for src/go
  .github/workflows/golang-build-test.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/M

#9043 chore(td-agent-bit): change local port for td-agent-bit client
  orc8r/gateway/configs/templates/td-agent-bit.conf.template
Labels: component: orc8r, size/XS

#9063 fix(agw): Fix freedomfiOne unit tests
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
Labels: component: agw, size/XS

#9059 fix(feg): fix to feg_LteAuthNewxtSeq_on_hss
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy.go
  feg/gateway/services/testcore/hss/servicers/config.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
Labels: component: agw, component: feg, size/S

#9018 fix(mme): removed a few compilation warnings
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_session_manager_pco.cpp
  lte/gateway/c/core/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_itti_messaging.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_common.h
Labels: component: agw, size/M

#9070 docs: fixed semantic-pr.yml link on magma documentation
  docs/docusaurus/versioned_docs/version-1.6.0/contributing/contribute_workflow.md
Labels: component: docs, size/XS

#8988 fix(agw): Bad encoding of naskeysetidentifierasme in NAS/AUTHENTICATION_REQUEST
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AuthenticationRequest.c
Labels: component: agw, size/XS

#9044 chore(feg): add new docker-compose for federated lte integ test
  feg/gateway/Vagrantfile
  lte/gateway/python/integ_tests/federated_tests/configs/control_proxy.yml
  lte/gateway/python/integ_tests/federated_tests/configs/ctraced.yml
  lte/gateway/python/integ_tests/federated_tests/configs/directoryd.yml
  lte/gateway/python/integ_tests/federated_tests/configs/eventd.yml
  lte/gateway/python/integ_tests/federated_tests/configs/gateway.mconfig
  lte/gateway/python/integ_tests/federated_tests/configs/hss.yml
  lte/gateway/python/integ_tests/federated_tests/configs/logfiles.txt
  lte/gateway/python/integ_tests/federated_tests/configs/magmad.yml
  lte/gateway/python/integ_tests/federated_tests/configs/redis.yml
  lte/gateway/python/integ_tests/federated_tests/configs/service_registry.yml
  lte/gateway/python/integ_tests/federated_tests/configs/streamer.yml
  lte/gateway/python/integ_tests/federated_tests/docker/.env
  lte/gateway/python/integ_tests/federated_tests/docker/docker-compose.cache.yml
  lte/gateway/python/integ_tests/federated_tests/docker/docker-compose.override.yml
  lte/gateway/python/integ_tests/federated_tests/docker/docker-compose.yml
Labels: component: agw, component: feg, size/XL

#9056 feat(agw): Cherry pick FreedomFiOne enodebd changes
  lte/gateway/configs/enodebd.yml
  lte/gateway/python/magma/enodebd/data_models/data_model.py
  lte/gateway/python/magma/enodebd/device_config/configuration_init.py
  lte/gateway/python/magma/enodebd/device_config/enodeb_config_postprocessor.py
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/devices/device_map.py
  lte/gateway/python/magma/enodebd/devices/device_utils.py
  lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/logger.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_impl.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/stats_manager.py
  lte/gateway/python/magma/enodebd/tests/enodeb_acs_states_tests.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enb_acs_builder.py
  lte/gateway/python/magma/enodebd/tests/tr069_tests.py
  lte/gateway/python/magma/enodebd/tr069/models.py
  lte/gateway/python/magma/enodebd/tr069/spyne_mods.py
Labels: component: agw, component: cwag, size/XXL

#9068 chore(state): add print grpc to state service on gateways
  cwf/gateway/configs/state.yml
  docs/readmes/lte/dev_notes.md
  lte/gateway/configs/state.yml
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  orc8r/gateway/python/magma/common/rpc_utils.py
  orc8r/gateway/python/magma/state/garbage_collector.py
  orc8r/gateway/python/magma/state/main.py
  orc8r/gateway/python/magma/state/state_replicator.py
Labels: component: orc8r, component: agw, component: docs, component: cwag, size/M, component: cwf

#9052 feat(orc8r): Add FreedomFi One as a supported eNB
  lte/cloud/go/services/lte/obsidian/models/enodeb_configuration_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/app/components/lte/EnodebUtils.js
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: agw, component: nms, size/S

#9060 fix(nms): Fix org creation and editing
  nms/packages/magmalte/server/main/routes.js
Labels: component: nms, size/S

#9078 chore(agw): fixup mal-formatted AuthenticationRequest.c regression
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AuthenticationRequest.c
Labels: component: agw, size/XS

#9038 feat(agw): SctpdDownlink proxy
  src/go/accessd/main.go
  src/go/accessd/server/server.go
  src/go/internal/testutil/fs.go
  src/go/internal/testutil/mock_zapcore/mock_clock.go
  src/go/log/zap/zap_integ_test.go
  src/go/service/mock_service/mock_router.go
  src/go/service/router.go
  src/go/service/sctpd/proxy_downlink_server.go
  src/go/service/sctpd/proxy_downlink_server_integ_test.go
  src/go/service/sctpd/proxy_uplink_server.go
  src/go/service/sctpd/proxy_uplink_server_integ_test.go
Labels: size/XL

#8796 fix(mme): malformed packet(Authentication request) in scale test
  lte/gateway/c/core/oai/common/common_types.h
  lte/gateway/c/core/oai/include/amf_config.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_38.401.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_38.413.h
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_timer_management.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_timer_management.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_data.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/ngap/messages/asn1/r16/r16.asn1
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/test/ngap/util_ngap_amf_nas_procedures.cpp
Labels: type: bug, component: agw, priority: medium, size/L, product: 5g sa

#9086 chore: remove unused magma_dev.yml
  lte/gateway/deploy/magma_dev.yml
  lte/gateway/deploy/magma_test.yml
Labels: component: agw, size/M

#9062 fix(ci): Changes to take care of the issue 8699
  .github/workflows/agw-workflow.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/L

#9093 fix(mme): fix compilation warnings related to UE ID and constness
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_timer_management.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_cn.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_location_update.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_service_abort.c
  lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_send.c
  lte/gateway/c/core/oai/tasks/nas/nas_proc.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_itti_messaging.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_common.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
Labels: component: agw, size/L

#9091 chore: Add golangci.yml to make precommit at feg
  feg/gateway/Makefile
Labels: component: feg, size/XS

#9089 refactor(agw): improves clang-format by adding format_all
  lte/gateway/Makefile
Labels: component: agw, size/M

#9083 chore(mme): Migrate S11 timers to zmq
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include/NwGtpv2c.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/src/NwGtpv2c.c
  lte/gateway/c/core/oai/tasks/s11/s11_tasks.c
Labels: component: agw, size/L, ready2merge

#9109 chore(orc8r): Reorder gateway & lib modules imports to comply with std Go format/lint tools & conventions
  orc8r/gateway/go/eventd/client_api.go
  orc8r/gateway/go/mconfig/mconfig.go
  orc8r/gateway/go/redis/client.go
  orc8r/gateway/go/services/bootstrapper/gateway_info/get_info.go
  orc8r/gateway/go/services/magmad/service/ping/ping_test.go
  orc8r/gateway/go/status/status_test.go
  orc8r/gateway/go/streamer/listener.go
  orc8r/lib/go/profile/profiler_disabled.go
  orc8r/lib/go/protos/fill_in_test.go
  orc8r/lib/go/protos/tests/identity_test.go
  orc8r/lib/go/registry/registry.go
  orc8r/lib/go/registry/service_registry.go
  orc8r/lib/go/security/csr/csr_test.go
  orc8r/lib/go/service/service.go
Labels: component: orc8r, size/M

#8986 fix(mme): Adding write of MME UE state for NAS uplink data ind handlers
  lte/gateway/c/core/oai/include/mme_app_state.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmInformation.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_proc.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_data_context.c
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.h
  lte/gateway/c/core/oai/test/CMakeLists.txt
  lte/gateway/c/core/oai/test/nas/CMakeLists.txt
  lte/gateway/c/core/oai/test/nas/test_nas_converter.cpp
Labels: component: agw, size/L

#9094 feat(agw): Cherry pick FreedomFiOne changes
  lte/cloud/go/services/lte/obsidian/models/enodeb_configuration_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/lte/EnodebUtils.js
  orc8r/cloud/go/obsidian/swagger/v1/models/enodeb_configuration.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, component: cwag, size/S

#8118 chore: [ci] Complete migration of feg testing jobs to github actions
  .circleci/config.yml
  .github/workflows/feg-workflow.yml
Labels: component: ci, size/M, devops-migration

#9079 docs(nms): Update NMS dev README with more troubleshooting help
  nms/README.md
Labels: component: nms, size/M

#9138 chore: clean up bazelrc and use output base instead of output user
  .bazelrc
Labels: size/XS

#9144 fix: reviewdog linters
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/M

#9120 fix(mme): handling of dedicated bearer for inbound roaming.
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerEvents.cpp
  lte/gateway/c/core/oai/test/openflow/test_gtp_app.cpp
Labels: component: agw, size/L

#9069 feat(agw): protobuf/json file based config and loader
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/protos/mconfig/mconfigs.proto
  src/go/agwd/config/config.go
  src/go/agwd/config/config_test.go
  src/go/agwd/config/internal/grpcutil/target.go
  src/go/agwd/config/internal/grpcutil/target_test.go
  src/go/agwd/config/testdata/accessd_mconfig.json
  src/go/agwd/config/testdata/bad_syntax.json
  src/go/agwd/config/testdata/override_some.json
  src/go/agwd/main.go
  src/go/agwd/server/server.go
  src/go/protos/magma/mconfig/mconfigs.pb.go
  src/go/protos/magma/orc8r/common.pb.go
  src/go/protos/protos.go
Labels: component: agw, size/XXL

#9077 chore(pipelined): Add configuration for default GBR.
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: component: agw, size/M

#9145 fix(mme): Updating S1AP UE state IMSI write on connection_establishment_cnf
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.h
Labels: component: agw, size/S

#9110 ci: turns up GH Action validating all Bazel {build|test} targets
  .github/workflows/bazel.yml
Labels: component: ci, size/L

#9143 docs: fix docs lint on master
  docs/docusaurus/package.json
  docs/docusaurus/yarn.lock
  docs/readmes/howtos/troubleshooting/agw_healthcheck.md
  docs/readmes/proposals/p019_esim_mgmt_integration.md
  docs/readmes/proposals/p020_sgi_tunnel_transport.md
Labels: component: docs, size/L

#9135 feat: add exclusive flags to SessionD unit tests that cannot be run i…
  lte/gateway/c/session_manager/test/BUILD.bazel
Labels: component: agw, size/XS

#9057 refactor(agw): refactor MConfigLoader to enable test, add tests
  lte/gateway/c/connection_tracker/src/main.cpp
  lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
  lte/gateway/c/core/oai/lib/sgs_client/itti_msg_to_proto_msg.cpp
  lte/gateway/c/core/oai/tasks/sctp/sctpd_downlink_client.cpp
  lte/gateway/c/li_agent/src/Utilities.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
  orc8r/gateway/c/common/config/MConfigLoader.cpp
  orc8r/gateway/c/common/config/includes/MConfigLoader.h
  orc8r/gateway/c/common/config/test/BUILD.bazel
  orc8r/gateway/c/common/config/test/CMakeLists.txt
  orc8r/gateway/c/common/config/test/test_mconfig_loader.cpp
Labels: component: agw, component: ci, size/L

#9115 chore(subscriberdb): replace print_grpc to use rpc utils function
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
Labels: component: agw, size/L

#9114 chore(mme): Add s1ap test for simple attach detach with IPv6 primary PDN
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_ipv6.py
Labels: component: agw, size/M

#9164 fix: move clangd-12 installation from dev common to magma role
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, size/S

#9149 style: Add check for correct Go imports order to build.py -g
  cwf/cloud/go/services/cwf/analytics/analytics.go
  cwf/cloud/go/services/cwf/analytics/analytics_test.go
  cwf/cloud/go/services/cwf/analytics/calculations/ap_throughput.go
  cwf/cloud/go/services/cwf/analytics/calculations/authentications.go
  cwf/cloud/go/services/cwf/analytics/calculations/cwf_calculations_test.go
  cwf/cloud/go/services/cwf/analytics/calculations/user_consumption.go
  cwf/cloud/go/services/cwf/analytics/calculations/user_throughput.go
  cwf/cloud/go/services/cwf/analytics/calculations/xap.go
  cwf/cloud/go/services/cwf/cwf/main.go
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers_test.go
  cwf/cloud/go/services/cwf/obsidian/models/conversion.go
  cwf/cloud/go/services/cwf/servicers/builder_servicer.go
  cwf/cloud/go/services/cwf/servicers/builder_servicer_test.go
  fbinternal/cloud/go/services/download/client_test.go
  fbinternal/cloud/go/services/download/servicers/server_lib.go
  fbinternal/cloud/go/services/fbinternal/fbinternal/main.go
  fbinternal/cloud/go/services/fbinternal/servicers/exporter_servicer.go
  fbinternal/cloud/go/services/fbinternal/servicers/exporter_servicer_test.go
  fbinternal/cloud/go/services/testcontroller/e2e_client_api.go
  fbinternal/cloud/go/services/testcontroller/node_client_api.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/node_handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/node_handlers_test.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers.go
  fbinternal/cloud/go/services/testcontroller/obsidian/handlers/testcontroller_handlers_test.go
  fbinternal/cloud/go/services/testcontroller/servicers/e2e.go
  fbinternal/cloud/go/services/testcontroller/servicers/nodes.go
  fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
  fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
  fbinternal/cloud/go/services/testcontroller/storage/sql.go
  fbinternal/cloud/go/services/testcontroller/storage/sql_integ_test.go
  fbinternal/cloud/go/services/testcontroller/storage/sql_nodes.go
  fbinternal/cloud/go/services/testcontroller/storage/sql_nodes_integ_test.go
  fbinternal/cloud/go/services/testcontroller/storage/sql_nodes_test.go
  fbinternal/cloud/go/services/testcontroller/storage/sql_test.go
  fbinternal/cloud/go/services/testcontroller/store/store_test.go
  fbinternal/cloud/go/services/testcontroller/store/testcontroller_store.go
  fbinternal/cloud/go/services/testcontroller/test_init/test_controller_test_service_init.go
  fbinternal/cloud/go/services/testcontroller/testcontroller/main.go
  fbinternal/cloud/go/services/vpnservice/client_api.go
  fbinternal/cloud/go/services/vpnservice/servicers/vpn_servicer.go
  fbinternal/cloud/go/services/vpnservice/servicers/vpn_servicer_test.go
  orc8r/cloud/Makefile
  orc8r/cloud/docker/controller/Dockerfile
  orc8r/cloud/go/Makefile
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/services/configurator/mconfig/mocks/Builder.go
  orc8r/cloud/go/services/dispatcher/broker/mocks/GatewayRPCBroker.go
  orc8r/cloud/order_go_imports.sh
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers_test.go
  wifi/cloud/go/services/wifi/obsidian/models/conversion.go
  wifi/cloud/go/services/wifi/obsidian/models/defaults.go
  wifi/cloud/go/services/wifi/servicers/builder_servicer.go
  wifi/cloud/go/services/wifi/servicers/builder_servicer_test.go
  wifi/cloud/go/services/wifi/wifi/main.go
Labels: component: orc8r, component: cwag, size/L, component: cwf

#9048 feat(mme): AMF Support for default slice type
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/c/core/oai/include/amf_config.h
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_ta.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_ta.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_types.h
  lte/gateway/c/core/oai/test/ngap/test_ngap.cpp
  lte/gateway/c/core/oai/test/ngap/util_ngap_initiate_ue.cpp
  lte/gateway/c/core/oai/test/ngap/util_ngap_pkt.h
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, priority: medium, size/XXL, product: 5g sa

#9163 fix(amf): fix for the issue 9151
  lte/gateway/c/core/oai/tasks/amf/amf_fsm.cpp
Labels: component: agw, size/XS

#8936 feat(agw): Support for handling normal TAU
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.h
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_proc.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_asDef.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_send.c
  lte/gateway/configs/mme.yml
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/integ_tests/s1aptests/test_attach_active_tau_with_combined_tala_update_reattach.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_inactive_tau_with_combined_tala_update_reattach.py
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/XL, ready2merge

#8937 test(agw): New testcases to test normal TAU
  lte/gateway/python/integ_tests/s1aptests/test_tau_ta_updating.py
  lte/gateway/python/integ_tests/s1aptests/test_tau_ta_updating_reject.py
Labels: component: agw, size/L

#9168 chore: commit leftover formatting changes from PR8936
  lte/gateway/python/integ_tests/s1aptests/test_attach_active_tau_with_combined_tala_update_reattach.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_ipv6.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_inactive_tau_with_combined_tala_update_reattach.py
Labels: component: agw, size/XS

#9095 feat(agw): Add support for IPv6 Non-NAT router mode.
  lte/gateway/python/magma/mobilityd/scripts/setup-uplink-vlan-srv.sh
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTestVlan.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Static_IP_Test.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
Labels: component: agw, size/L

#9146 chore(agw): remove OVS 2.8 build script.
  lte/gateway/release/build-ovs.sh
Labels: component: agw, component: ci, size/L

#9177 ci: migrates vscode devcontainer to registry
  .devcontainer/devcontainer.json
Labels: size/XS

#9183 chore: commit formatting for leftover C++ files
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.c
Labels: component: agw, size/XS

#9186 fix(ci): Swaggerhub api cli update
  .github/workflows/cloud-workflow.yml
Labels: component: ci, size/XS

#9167 feat: modify devcontainer to support bazel builds
  .bazelrc
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  WORKSPACE.bazel
Labels: size/M

#8022 chore: [ci] Complete migration of cloud tests to github actions
  .circleci/config.yml
Labels: component: ci, size/L, devops-migration

#9188 chore(agw): remove debian AGW deployment script.
  lte/gateway/deploy/agw_install.sh
  lte/gateway/deploy/agw_post_install.sh
  lte/gateway/deploy/agw_post_install_ubuntu.sh
  lte/gateway/deploy/agw_pre_check.sh
Labels: component: agw, size/L

#9219 ci: update hash on devcontainer ghcr use
  .devcontainer/devcontainer.json
Labels: size/XS

#9185 ci: adds 386/arm/arm64 unit test validation for src/go
  .github/workflows/golang-build-test.yml
Labels: component: ci, size/M

#9184 chore: update docs for CI checks
  docs/readmes/contributing/contribute_ci_checks.md
  docs/readmes/lte/dev_unit_testing.md
Labels: component: docs, size/XS

#9179 test(agw): New testcase to test multiple partial TAI lists and automate adding of TAIs in mme.conf.template
  lte/gateway/deploy/roles/magma/files/update_mme_config_for_sanity.sh
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_tau_mixed_partial_lists.py
  lte/gateway/python/integ_tests/s1aptests/test_tau_ta_updating_reject.py
Labels: component: agw, size/L

#9217 fix(mme): Removing unused files.
  lte/gateway/c/core/oai/tasks/nas/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/nas/nas_if.h
  lte/gateway/c/core/oai/tasks/nas/nas_if_s1.c
  lte/gateway/c/core/oai/tasks/nas/nas_if_s6a.c
Labels: component: agw, size/M, ready2merge

#8200 feat(mme): AMBR Extended-2 field addition in EPS QoS IE and in APN-AMBR.
  lte/gateway/c/core/oai/include/EpsQualityOfService.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_sap.c
  lte/gateway/c/core/oai/tasks/nas/esm/sap/esm_send.c
  lte/gateway/c/core/oai/tasks/nas/ies/ApnAggregateMaximumBitRate.c
  lte/gateway/c/core/oai/tasks/nas/ies/ApnAggregateMaximumBitRate.h
  lte/gateway/c/core/oai/tasks/nas/ies/EpsQualityOfService.c
  lte/gateway/c/core/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/test_ApnAggregateMaximumBitRate.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_EPSQualityOfService.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_nas_encode_decode.cpp
Labels: component: agw, size/XXL, ready2merge

#9215 chore(mme): Add unit test for GUTI based attach and refactor
  lte/gateway/c/core/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/XL

#9106 feat(sessiond): unified name for enable5gFeatures flag across AGW com…
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/sessiond.yml
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, size/L, product: 5g sa

#9223 ci: adds connectiond semantic PR scope
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/XS

#9228 fix(ci): corrects argument ordering to cpplint to allow for filters
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/XS

#9222 fix(connectiond): fixes namespace import pollution
  lte/gateway/c/connection_tracker/src/PacketGenerator.cpp
Labels: component: agw, size/XS

#9181 refactor(mme): refactors service config loading and adds a test
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_config.cpp
Labels: component: agw, size/L

#9232 fix(orc8r): Fix broken modules proto make to terminate on erroneous protos (issue #9231)
  orc8r/cloud/go/module.mk
Labels: component: orc8r, size/XS, ready2merge

#9216 chore(mme): remove unused timer signals and functions
  lte/gateway/c/core/oai/include/messages_def.h
  lte/gateway/c/core/oai/include/messages_types.h
  lte/gateway/c/core/oai/lib/itti/CMakeLists.txt
  lte/gateway/c/core/oai/lib/itti/example_messages_def.h
  lte/gateway/c/core/oai/lib/itti/intertask_interface.c
  lte/gateway/c/core/oai/lib/itti/messages_types.h
  lte/gateway/c/core/oai/lib/itti/signals.c
  lte/gateway/c/core/oai/lib/itti/timer.c
  lte/gateway/c/core/oai/lib/itti/timer.h
  lte/gateway/c/core/oai/lib/itti/timer_messages_def.h
  lte/gateway/c/core/oai/lib/itti/timer_messages_types.h
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/ha/ha_task.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_location_update.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.h
  lte/gateway/c/core/oai/tasks/nas/util/nas_timer.c
  lte/gateway/c/core/oai/tasks/nas/util/nas_timer.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/s11/s11_tasks.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/test/mock_tasks/s1ap_mock.cpp
Labels: component: agw, size/XL

#8119 chore(ci): Complete migration of cwf test job to github action
  .circleci/config.yml
Labels: component: ci, size/S, devops-migration

#9174 chore: bump swagger ui to 3.52.2
  orc8r/cloud/docker/controller/Dockerfile
  orc8r/cloud/docker/controller/setup_swagger_ui
Labels: component: orc8r, size/XS

#9182 ci: adds scheduled GH Action docker builds for dev / CI
  .github/workflows/docker-push.yml
Labels: component: ci, size/M

#9218 ci: accelerates gcc-problems by use of devcontainer from ghcr
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/L

#9226 fix(amf): bugfix for the issue 9225
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
Labels: component: agw, size/M, product: 5g sa

#9229 ci: accelerates the bazel workflows by pulling from GHCR
  .bazelrc
  .github/workflows/bazel.yml
Labels: component: ci, size/L

#9236 chore(mme): fix compilation warnings for gtp ops
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.c
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.h
Labels: component: agw, size/M

#9220 chore: clean up VSCode workspace settings for bazel
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .vscode/launch.json
  .vscode/tasks.json
  experimental/bazel-base/VSCodeBazel.md
  experimental/bazel-base/VSCodeSetup.md
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/protos/BUILD.bazel
  scripts/gen_compilation_database.py
  vscode-workspaces/workspace.magma-vm-workspace.code-workspace
Labels: component: agw, size/L

#9247 fix(pipelined): fix ipfix sampling port
  cwf/gateway/deploy/roles/ovs/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions_3.5.py
  lte/gateway/python/magma/pipelined/app/ipfix.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_internal_pkt_ipfix_export.InternalPktIpfixExportTest.test_subscriber_policy.snapshot
  xwf/gateway/deploy/roles/ovs/files/nx_actions.py
Labels: component: agw, size/S, apply-v1.5, apply-v1.6, apply-v1.7, component: cwf, component: xwf

#9250 fix(pipelined): fix ipfix sampling port (#9247)
  cwf/gateway/deploy/roles/ovs/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions_3.5.py
  lte/gateway/python/magma/pipelined/app/ipfix.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_internal_pkt_ipfix_export.InternalPktIpfixExportTest.test_subscriber_policy.snapshot
  xwf/gateway/deploy/roles/ovs/files/nx_actions.py
Labels: size/S

#9248 chore(pipelined): add flag to control TSO
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/datapath_setup.py
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, size/M, apply-v1.7

#9254 Backport ipfix 1.5 ubuntu
  cwf/gateway/deploy/roles/ovs/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions_3.5.py
  lte/gateway/python/magma/pipelined/app/ipfix.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_internal_pkt_ipfix_export.InternalPktIpfixExportTest.test_subscriber_policy.snapshot
  xwf/gateway/deploy/roles/ovs/files/nx_actions.py
Labels: size/S

#9252 fix(pipelined): fix ipfix sampling port (#9247)
  cwf/gateway/deploy/roles/ovs/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions_3.5.py
  lte/gateway/python/magma/pipelined/app/ipfix.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_internal_pkt_ipfix_export.InternalPktIpfixExportTest.test_subscriber_policy.snapshot
  xwf/gateway/deploy/roles/ovs/files/nx_actions.py
Labels: size/S

#9227 feat: bazelify src/go
  BUILD.bazel
  WORKSPACE.bazel
  experimental/bazel-base/Dockerfile
  experimental/bazel-base/README.md
  go_repositories.bzl
  src/go/agwd/BUILD.bazel
  src/go/agwd/config/BUILD.bazel
  src/go/agwd/config/internal/grpcutil/BUILD.bazel
  src/go/agwd/server/BUILD.bazel
  src/go/internal/testutil/BUILD.bazel
  src/go/log/BUILD.bazel
  src/go/log/mock_log/BUILD.bazel
  src/go/log/zap/BUILD.bazel
  src/go/log/zap/zap_test.go
  src/go/protos/BUILD.bazel
  src/go/protos/magma/mconfig/BUILD.bazel
  src/go/protos/magma/orc8r/BUILD.bazel
  src/go/protos/magma/sctpd/BUILD.bazel
  src/go/protos/magma/sctpd/mock_sctpd/BUILD.bazel
  src/go/service/BUILD.bazel
  src/go/service/mock_service/BUILD.bazel
  src/go/service/sctpd/BUILD.bazel
Labels: component: agw, size/XL

#9251 feat(cloud): support dynamic instance types for teravm and s1ap testing
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/provision-instances.yaml
  experimental/cloudstrapper/playbooks/roles/vars/cluster.yaml
Labels: size/XS

#9260 ci: updates bazel build cache keys
  .github/workflows/bazel.yml
Labels: component: ci, size/XS

#9261 ci: remove docker buildx caches
  .github/workflows/docker-push.yml
  .github/workflows/dockerfile-health.yml
Labels: component: ci, size/M

#9265 fix(mme): Free bstring field for ICS response
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
Labels: size/S

#9253 chore: Prep for new Go build constraints syntax transition
  cwf/gateway/integ_tests/auth_test.go
  cwf/gateway/integ_tests/feg_failure_test.go
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_restart_test.go
  cwf/gateway/integ_tests/gx_reauth_test.go
  cwf/gateway/integ_tests/gy_reauth_test.go
  cwf/gateway/integ_tests/hssless_test.go
  cwf/gateway/integ_tests/idle_timer_test.go
  cwf/gateway/integ_tests/ipfix_test.go
  cwf/gateway/integ_tests/multi_sessioneproxy_test.go
  cwf/gateway/integ_tests/omni_rules_test.go
  cwf/gateway/integ_tests/service_state_dumper.go
  cwf/gateway/integ_tests/stateless_test.go
  cwf/k8s/cwf_operator/pkg/apis/magma/v1alpha1/zz_generated.deepcopy.go
  feg/gateway/go.sum
  feg/gateway/services/aaa/aaa_server/aaa_aka_linked_auth_test.go
  feg/gateway/services/aaa/aaa_server/builtin_radius.go
  feg/gateway/services/aaa/radius/dae/dae_builtin.go
  feg/gateway/services/aaa/radius/dae/dae_external.go
  feg/gateway/services/eap/providers/aka/provider/linked_client_api.go
  feg/gateway/services/eap/providers/sim/provider/linked_client_api.go
  feg/gateway/tools/s8_cli/main_test.go
  feg/radius/lib/go/radius/debug/generate_main.go
  orc8r/cloud/api/v1/go/tools.go
  orc8r/cloud/go/tools.go
  orc8r/lib/go/initflag/parse_flag_debug.go
  orc8r/lib/go/profile/profiler_enabled.go
  src/go/tools.go
Labels: component: orc8r, component: feg, size/M, ready2merge, component: cwf

#9221 feat(connectiond): add support for Bazel build
  WORKSPACE.bazel
  lte/gateway/c/connection_tracker/src/BUILD.bazel
  third_party/system_libraries.BUILD
Labels: component: agw, size/M

#8597 feat(amf): Handling security mode reject
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.h
  lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
  lte/gateway/c/core/oai/test/amf/util_nas5g_security_mode_reject_pkt.cpp
Labels: component: agw, type: feature, size/L, product: 5g sa

#9243 feat(mme): mme.yml configuration for amf
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/L, product: 5g sa

#9256 fix(ci): path filter
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/lint-clang-format.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/L

#9258 fix(sessiond): Sending Paging notification to AMF only when session i…
  lte/gateway/c/session_manager/UpfMsgManageHandler.cpp
Labels: component: agw, size/S, product: 5g sa

#9286 chore: add src/go as a path trigger for bazel jobs
  .github/workflows/bazel.yml
Labels: component: ci, size/XS

#9285 chore: refactor src/go so that project source is magma root
  src/go/README.md
  src/go/agwd/BUILD.bazel
  src/go/agwd/config/BUILD.bazel
  src/go/agwd/config/config.go
  src/go/agwd/config/config_test.go
  src/go/agwd/config/internal/grpcutil/BUILD.bazel
  src/go/agwd/main.go
  src/go/agwd/server/BUILD.bazel
  src/go/agwd/server/server.go
  src/go/go.mod
  src/go/internal/testutil/BUILD.bazel
  src/go/internal/testutil/log.go
  src/go/log/BUILD.bazel
  src/go/log/mock_log/BUILD.bazel
  src/go/log/mock_log/mock_logger.go
  src/go/log/mock_logger_test.go
  src/go/log/zap/BUILD.bazel
  src/go/log/zap/zap.go
  src/go/log/zap/zap_integ_test.go
  src/go/log/zap/zap_test.go
  src/go/protos/BUILD.bazel
  src/go/protos/magma/mconfig/BUILD.bazel
  src/go/protos/magma/mconfig/mconfigs.pb.go
  src/go/protos/magma/orc8r/BUILD.bazel
  src/go/protos/magma/sctpd/BUILD.bazel
  src/go/protos/magma/sctpd/mock_sctpd/BUILD.bazel
  src/go/protos/magma/sctpd/mock_sctpd/mock_sctpd_grpc.pb.go
  src/go/protos/protos.go
  src/go/service/BUILD.bazel
  src/go/service/mock_service/BUILD.bazel
  src/go/service/mock_service/mock_router.go
  src/go/service/router.go
  src/go/service/sctpd/BUILD.bazel
  src/go/service/sctpd/proxy_downlink_server.go
  src/go/service/sctpd/proxy_downlink_server_integ_test.go
  src/go/service/sctpd/proxy_uplink_server.go
  src/go/service/sctpd/proxy_uplink_server_integ_test.go
Labels: size/L
