Repository magma/magma, pull requests merged in 2021-02, with the labels that each got.

#4582 [lte][agw] Updating IP allocator pool to not do full look-up of IPs in free state
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ip_allocator_pool.py
  lte/gateway/python/magma/mobilityd/ip_descriptor_map.py
Labels: apply-v1.4, component: agw, component: cwag

#4675 AGW: pipelined: Fix QoS init for stateless
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
Labels: apply-v1.4, component: agw, component: cwag

#4639 Increase pipelined enforcement poll time
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
Labels: apply-v1.4, component: agw, component: cwag

#4277 [agw][stateless AGW] Make Pipelined GTP app stateless #3554
  lte/gateway/python/magma/pipelined/app/classifier.py
Labels: component: agw, component: cwag

#4660 AGW: sctp: unbind socket on error.
  lte/gateway/c/sctpd/util.cpp
Labels: apply-v1.4, component: agw, component: cwag

#4474 [Stateless_Testing] [New_Test_Case] Added stateless test cases for ICS failure and Drop scenarios with Reattach request
  lte/gateway/python/integ_tests/s1aptests/test_attach_ics_drop_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ics_failure_with_mme_restart.py
Labels: component: agw, component: cwag

#4648 [orc8r][service_registry] Add cache to service registry service
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/go/orc8r/const.go
  orc8r/cloud/go/services/service_registry/service_registry/main.go
  orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/kubernetes_servicer_test.go
Labels: apply-v1.4, component: agw, component: cwag

#4673 [circleci] Add tag of latest to orc8r dockers
  .circleci/config.yml
Labels: component: agw, component: cwag

#4449 [Orc8r][AWS/Terraform/Helm] Fix elastic search curator config
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/logging.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: apply-v1.4, component: agw, component: cwag

#3496 [5G-MVC:pipelined] Setting of REG-8 in ovs for 5G GTP Tunnel #3365
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_traffic.GTPTrafficTest.test_traffic_flows.snapshot
Labels: component: agw, component: cwag

#4680 [orc8r] Remove Warning log when there are no errors
  orc8r/cloud/go/swagger/combine.go
Labels: component: agw, component: cwag

#4657 [orc8r][tf] Fix tf orc8r install issues for v1.4
  docs/readmes/orc8r/upgrade_1_4.md
  orc8r/cloud/deploy/terraform/orc8r-aws/eks.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: apply-v1.4, component: agw, component: cwag

#4665 [orc8r] Implement Spec Servicer
  .gitignore
  cwf/cloud/configs/service_registry.yml
  cwf/cloud/go/services/cwf/cwf/main.go
  cwf/cloud/helm/cwf-orc8r/values.yaml
  fbinternal/cloud/configs/service_registry.yml
  fbinternal/cloud/go/services/fbinternal/fbinternal/main.go
  fbinternal/cloud/helm/fbinternal-orc8r/values.yaml
  feg/cloud/configs/service_registry.yml
  feg/cloud/go/services/feg/feg/main.go
  feg/cloud/helm/feg-orc8r/values.yaml
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/policydb/policydb/main.go
  lte/cloud/go/services/smsd/smsd/main.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/helm/lte-orc8r/values.yaml
  orc8r/cloud/Makefile
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/obsidian/swagger/spec_servicer.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer_test.go
  orc8r/cloud/go/orc8r/const.go
  orc8r/cloud/go/services/ctraced/ctraced/main.go
  orc8r/cloud/go/services/metricsd/metricsd/main.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/tenants/tenants/main.go
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/lib/go/service/config/service_config.go
  wifi/cloud/configs/service_registry.yml
  wifi/cloud/go/services/wifi/wifi/main.go
  wifi/cloud/helm/wifi-orc8r/values.yaml
Labels: component: agw, component: cwag

#4697 Temporarily disable pipelined QOS for stability
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
Labels: apply-v1.4, component: agw, component: cwag

#4696 AGW: pipelined: Increase OVS inactivity_probe
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
Labels: apply-v1.4, component: agw, component: cwag

#4691 [lte][agw] Fixing IPCP req options length counters on pgw_pco.c
  lte/gateway/c/oai/tasks/sgw/pgw_pco.c
Labels: apply-v1.4, component: agw, component: cwag

#4700 [s1ap] Add logging messages to show content of directoryd
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, component: cwag

#4682 [AGW] [S1ap tests] Enhance S1aptest redis state and Redis key cleaning
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: apply-v1.4, component: agw, component: cwag

#4710 [circleci] tag-latest will tag and push latest as well as current hash
  .circleci/config.yml
Labels: component: agw, component: cwag

#4731 [MME] Fix 'set but unused' build error with RelWithDebInfo in OAI
  lte/gateway/c/oai/tasks/sgw/pgw_pco.c
Labels: apply-v1.4, component: agw, component: cwag

#4591 [DOCKER][MME] Optimization when building MME image from scratch
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw, component: cwag

#4741 [CI] Upload v1.4 packages to a specific folder
  orc8r/tools/fab/pkg.py
Labels: component: agw, component: cwag

#4740 [CI][REGISTRY] Open Source aptly script
  ci-scripts/registry/aptly/deploy_image.sh
Labels: component: agw, component: cwag

#4707 [s1ap] Add longer delay on test_attach_detach_rar_tcp_data
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_data.py
Labels: component: agw, component: cwag

#4744 [s1ap] Remove loop on ReAuthRequest
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, component: cwag

#4746 [NMS] Enable alerts on dashboard table to auto refresh.
  nms/app/packages/magmalte/app/components/DashboardAlertTable.js
Labels: apply-v1.4, component: agw, component: cwag

#4456 [docs] Add call tracing howto doc page
  docs/docusaurus/sidebars.json
  docs/readmes/assets/nms/calltracing_actions.png
  docs/readmes/assets/nms/calltracing_dialog.png
  docs/readmes/assets/nms/calltracing_page.png
  docs/readmes/assets/nms/calltracing_wireshark.png
  docs/readmes/howtos/call_tracing.md
Labels: apply-v1.4, component: agw, component: cwag

#4705 [orc8r] [fix] Remove Temp Directories made in Spec Servicer Test
  orc8r/cloud/go/obsidian/swagger/spec_servicer_test.go
Labels: component: agw, component: cwag

#4751 [CI] Upload v1.4 packages to a specific folder
  circleci/fabfile.py
  orc8r/tools/fab/pkg.py
Labels: component: agw, component: cwag

#4755 [s1ap] added pprint to s1ap_utils
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, component: cwag

#4759 [show-tech] Minor fixes to show tech tool
  show-tech/constants.yml
  show-tech/show-tech.yml
Labels: apply-v1.4, component: agw, component: cwag

#4764 [ci][cwag_xwfm] change tag to use-latest param
  .circleci/config.yml
Labels: component: agw, component: cwag

#4676 [magmad][py 3.8] patch aio2
  orc8r/gateway/python/python.mk
Labels: component: agw, component: cwag

#4774 Reduce pipelined interval to 2 s
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
Labels: component: agw, component: cwag

#4742 [helm][tf] Backport alert fixes1.4
  docs/readmes/orc8r/upgrade_1_4.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/templates/alertmanager-configurer.deployment.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/values.yaml
Labels: apply-v1.4, component: agw, component: cwag

#4747 [S1APTest] Add continuous random attach test
  lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py
Labels: component: agw, component: cwag

#4780 commented _python_coverage and _run_unit_tests on lte/gatewaqy/fabfile
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, component: cwag

#4781 Two failing test OFF, 10 s poll interval
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
Labels: component: agw

#4782 [AGW][ENVOY] Reboot loop fix
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag

#4784 AGW: pipelined: add missing match fields in diff generator.
  lte/gateway/python/magma/pipelined/policy_converters.py
Labels: apply-v1.4, component: agw, component: cwag

#4758 [lte][agw] Adding logrotate conf for syslog for hourly rotation with max size
  lte/gateway/deploy/roles/magma/files/logrotate_rsyslog.conf
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/release/build-magma.sh
Labels: apply-v1.4, component: agw, component: cwag

#4790 Temporarily roll back pipelined polling time for CI
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
Labels: component: agw, component: cwag

#4749 [docs] Add show tech to readmes
  docs/docusaurus/sidebars.json
  docs/readmes/debugging_tools/show-tech/developer_guide.md
  docs/readmes/debugging_tools/show_tech.md
  docs/readmes/lte/setup_deb.md
Labels: component: agw, component: cwag

#4783 [lte][agw] Removing state conversion for static PCC rules on SPGW
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/oai/tasks/sgw/spgw_state_converter.h
  lte/protos/oai/spgw_state.proto
Labels: apply-v1.4, component: agw, component: cwag

#4776 AGW: pipelineD: qos: Fix scale test issues
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: apply-v1.4, component: agw, component: cwag

#4794 Rebased to master
  lte/gateway/python/magma/pipelined/app/classifier.py
Labels: component: agw, component: cwag

#4686 [magmad][metrics] Update metrics reporting to sync once per gw service
  cwf/gateway/configs/magmad.yml
  example/gateway/configs/magmad.yml
  feg/gateway/configs/magmad.yml
  feg/gateway/configs/magmad_legacy.yml
  lte/gateway/configs/magmad.yml
  openwrt/gateway/configs/etc/magma/configs/magmad.yml
  orc8r/gateway/configs/magmad.yml
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/magmad/metrics_collector.py
  orc8r/gateway/python/magma/magmad/tests/collector_tests.py
  xwf/gateway/configs/magmad.yml
Labels: apply-v1.4, component: agw, component: cwag

#4800 [ci][xwfm_tests] removing un-needed aws env vars related to xwf
  .circleci/config.yml
Labels: component: agw, component: cwag

#4711 [docs] Add Metrics documentation to NMS
  docs/docusaurus/sidebars.json
  docs/readmes/assets/nms/userguide/alerts/alerts_api.png
  docs/readmes/assets/nms/userguide/metrics/metric_explorer1.png
  docs/readmes/assets/nms/userguide/metrics/metric_explorer2.png
  docs/readmes/assets/nms/userguide/metrics/metrics_api.png
  docs/readmes/nms/alert.md
  docs/readmes/nms/legacy/grafana.md
  docs/readmes/nms/metrics.md
Labels: apply-v1.4, component: agw, component: cwag

#4808 [CI] Fix integration tests with pip upgrade
  .circleci/config.yml
Labels: component: agw, component: cwag

#4810 [LTEIntegTest] Add DEBIAN_FRONTEND=noninteractive flag to dist-upgrade command
  lte/gateway/fabfile.py
Labels: component: agw, component: cwag

#4701 [docs] Add a deployment FAQ section to Orc8r docs
  docs/docusaurus/sidebars.json
  docs/readmes/orc8r/deploy_faq.md
  docs/readmes/orc8r/deploy_intro.md
Labels: apply-v1.4, component: agw, component: cwag

#4797 [NMS] Fix multiple NMS bugs
  nms/app/packages/magmalte/alerts/lteAlerts.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/GatewayConfigTest.js
  nms/app/packages/magmalte/app/views/events/EventsTable.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberOverview.js
  nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js
  nms/app/packages/magmalte/app/views/traffic/PolicyTracking.js
  nms/app/packages/magmalte/app/views/traffic/ProfileEdit.js
Labels: apply-v1.4, component: agw, component: cwag, component: nms

#4698 [lte][agw]Mitigate GRPC timeouts in S6a requests
  lte/gateway/c/oai/lib/s6a_proxy/S6aClient.h
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/store/sqlite.py
  lte/gateway/python/magma/subscriberdb/tests/processor_tests.py
  lte/gateway/python/magma/subscriberdb/tests/rpc_tests.py
  lte/gateway/python/magma/subscriberdb/tests/store/cached_store_tests.py
  lte/gateway/python/magma/subscriberdb/tests/store/onready_test.py
  lte/gateway/python/magma/subscriberdb/tests/store/store_tests.py
  lte/gateway/python/magma/subscriberdb/tests/streamer_callback_tests.py
  orc8r/gateway/python/magma/common/service.py
Labels: apply-v1.4, component: agw, component: cwag, component: cwf

#4837 [pipelined]Add Redis Connection Error Handling
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
Labels: component: agw, component: cwag

#4756 [NMS] Add APN resources config view
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
Labels: component: agw, component: cwag

#4850 [SessionD] Refactor EventBase usages to be more consistent
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: component: agw, component: cwag

#4677 [AGW][MME] Remove stale eNB state with stateless MME
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_sctp_shutdown_while_mme_is_stopped.py
Labels: apply-v1.4, component: agw, component: cwag

#4643 [Orc8r] workaround for handling increased number of subscribers
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  orc8r/cloud/go/service/service.go
  orc8r/cloud/go/services/configurator/client_api.go
  orc8r/cloud/go/services/configurator/configurator/main.go
  orc8r/cloud/go/services/state/client_api.go
  orc8r/cloud/go/services/state/state/main.go
  orc8r/cloud/go/services/streamer/providers/remote_provider.go
  orc8r/cloud/go/services/streamer/servicers/servicer.go
  orc8r/cloud/go/services/streamer/streamer/main.go
  orc8r/lib/go/registry/global_registry.go
  orc8r/lib/go/registry/registry.go
Labels: component: agw, component: cwag

#4796 [lte][agw] Updating health.yml to 3 mins for checking num of restarts
  lte/gateway/configs/health.yml
Labels: apply-v1.4, component: agw, component: cwag

#4848 [xwf][xwfm][fluentbit] revert "we will log also locally on mount bind…
  xwf/gateway/deploy/roles/containers/files/clean_fluentbit_logs
  xwf/gateway/deploy/roles/containers/tasks/main.yml
  xwf/gateway/docker/docker-compose.yml
Labels: component: agw, component: cwag

#4858 [feg] s6a add Regional-Subscription-Zone-Code AVP
  feg/cloud/go/protos/s6a_proxy.pb.go
  feg/gateway/services/s6a_proxy/servicers/s6a_definitions.go
  feg/gateway/services/s6a_proxy/servicers/test/test_s6a_server.go
  feg/gateway/services/s6a_proxy/servicers/ul.go
  feg/protos/s6a_proxy.proto
Labels: component: agw, component: cwag

#4877 [lte][agw] fix package management issues for magma .deb
  lte/gateway/deploy/roles/ovs_deploy/tasks/main.yml
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag

#4857 Fix envoy_controller init logic
  feg/gateway/services/envoy_controller/control_plane/control_plane.go
Labels: apply-v1.4, component: agw, component: cwag

#4880 [AGW] Bump to 1.3.3
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
Labels: component: agw, component: cwag

#4771 [bare-metal][orc8r] Add missing smsd port config to bare metal deploy template
  orc8r/cloud/deploy/bare-metal/charts/orc8r.yaml.tpl
Labels: component: agw, component: cwag

#4750 [orc8r] Poll Spec Servicers
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/go/obsidian/swagger/combine.go
  orc8r/cloud/go/obsidian/swagger/combine_test.go
  orc8r/cloud/go/obsidian/swagger/doc.go
  orc8r/cloud/go/obsidian/swagger/registry.go
  orc8r/cloud/go/obsidian/swagger/registry_test.go
  orc8r/cloud/go/obsidian/swagger/remote_spec.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer_test.go
  orc8r/cloud/go/orc8r/const.go
  wifi/cloud/go/go.sum
Labels: component: agw, component: cwag

#4851 AGW: pipelined: qos: initialize single instance of QoS manager
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_meter_impl.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: apply-v1.4, component: agw, component: cwag

#4862 Modified the test case to initiate detach to clear contexts at MME
  lte/gateway/python/integ_tests/s1aptests/test_outoforder_attach_complete_ICSR.py
Labels: component: agw, component: cwag

#4861 [AGW][Stateless MME ]Sctp reset enb state
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/protos/oai/s1ap_state.proto
Labels: apply-v1.4, component: agw, component: cwag

#3834 [orc8r] Clean up github.com/facebookincubator/magma
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/logging/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/metrics/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/README.md
  orc8r/cloud/helm/orc8r/charts/secrets/Chart.yaml
  orc8r/gateway/docker/.prod_env
  orc8r/gateway/go/services/magmad/README.md
  orc8r/tools/docker/install_gateway.sh
Labels: component: agw, component: cwag

#3005 AGW: run OVS datapath in userspace.
  lte/gateway/deploy/agw_ovs_user_space.sh
Labels: DevOps/PE, component: agw, component: cwag

#4769 Added code to handle duplicate attach requests
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/gateway/c/oai/include/mme_app_ue_context.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/oai/tasks/nas/emm/emm_data_ctx.c
  lte/gateway/c/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/oai/tasks/nas/esm/PdnConnectivity.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.c
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/nas_state_converter.h
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/protos/oai/nas_state.proto
Labels: apply-v1.4, component: agw, component: cwag

#4898 [orc8r] Fix the default search field for searching orc8r logs
  orc8r/cloud/go/services/analytics/calculations/log_calculations.go
Labels: apply-v1.4, component: agw, component: cwag

#4903 [lte][agw] Disabling magma@health service while integ_test step
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_modify_mme_config_for_sanity.py
  lte/gateway/python/integ_tests/s1aptests/test_restore_mme_config_after_sanity.py
Labels: component: agw, component: cwag

#4904 Modified code to properly convert GUTI in UE context
  lte/gateway/c/oai/tasks/nas/nas_state_converter.cpp
Labels: apply-v1.4, component: agw, component: cwag

#4626 [orc8r][dev] Fix most LGTM cloud lints
  lte/cloud/go/sms_ll/sms_cp.go
  orc8r/cloud/go/services/state/indexer/indexer.go
  orc8r/cloud/go/services/state/indexer/registry.go
  orc8r/cloud/go/tools/migrations/m004_gateway_device/main.go
  orc8r/cloud/go/tools/service303_cli/log_verbosity.go
  orc8r/lib/go/protos/metricsd_helper.go
Labels: component: agw, component: cwag

#4906 [AGW][Stateless] Restart Open vSwitch service on Sctpd restart
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: apply-v1.4, component: agw, component: cwag

#4884 [NMS] Remove duplicated dialog styles
  nms/app/packages/magmalte/app/theme/default.js
Labels: component: agw, component: cwag

#4899 [AGW][Stateless MME] Assert whenever eNB state is corrupted and Sctp reset is received
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: apply-v1.4, component: agw, component: cwag

#4834 [ci][xwfm] reordering deployments
  .circleci/config.yml
Labels: component: agw, component: cwag

#4493 OAI: ubuntu: Fix compiler warning.
  lte/gateway/Makefile
  lte/gateway/c/oai/common/TLVDecoder.c
  lte/gateway/c/oai/common/TLVDecoder.h
  lte/gateway/c/oai/common/glogwrapper/glog_logging.h
  lte/gateway/c/oai/include/mme_app_ue_context.h
  lte/gateway/c/oai/include/nas/as_message.h
  lte/gateway/c/oai/lib/3gpp/3gpp_24.008_sm_ies.c
  lte/gateway/c/oai/lib/itti/intertask_interface.c
  lte/gateway/c/oai/lib/itti/intertask_interface_types.h
  lte/gateway/c/oai/lib/openflow/controller/ControllerMain.cpp
  lte/gateway/c/oai/lib/openflow/controller/OpenflowMessenger.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_capabilities.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/oai/tasks/nas/emm/emm_data_ctx.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.h
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
  orc8r/gateway/c/common/config/MConfigLoader.cpp
Labels: component: agw, component: cwag

#4881 [NMS] Fix edit tabs
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/network/NetworkEdit.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
  nms/app/packages/magmalte/app/views/traffic/PolicyEdit.js
Labels: component: agw, component: cwag

#4192 [AGW] [Stateless] Deprecate unused shell scripts for configuring stateless AGW
  lte/gateway/deploy/roles/magma/files/config_stateless_agw.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_mme.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_mobilityd.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_pipelined.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_sctpd.sh
  lte/gateway/deploy/roles/magma/files/config_stateless_sessiond.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/release/build-magma.sh
Labels: apply-v1.4, component: agw, component: cwag

#4909 AGW: ubuntu: fix test-oai compilation.
  lte/gateway/c/oai/test/CMakeLists.txt
  lte/gateway/c/oai/test/openflow/CMakeLists.txt
Labels: component: agw, component: cwag

#4901 [NMS] Add remediation for few predefined alerts
  nms/app/packages/magmalte/alerts/lteAlerts.js
  nms/app/packages/magmalte/app/components/DashboardAlertTable.js
Labels: apply-v1.4, component: agw, component: cwag

#4912 [docs] Add events monitoring docs
  docs/docusaurus/sidebars.json
  docs/readmes/assets/lte/events_architecture.png
  docs/readmes/assets/lte/events_table.png
  docs/readmes/howtos/events_monitoring.md
  docs/readmes/lte/eventd.md
Labels: component: agw, component: cwag

#4920 Fix Envoy Service yaml for build script
  lte/gateway/release/build-magma.sh
Labels: apply-v1.4, component: agw

#4919 [Orc8r] Revert "Set grpc max message size to 50MB for subscriberdb, streamer,…
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  orc8r/cloud/go/service/service.go
  orc8r/cloud/go/services/configurator/client_api.go
  orc8r/cloud/go/services/configurator/configurator/main.go
  orc8r/cloud/go/services/state/client_api.go
  orc8r/cloud/go/services/state/state/main.go
  orc8r/cloud/go/services/streamer/providers/remote_provider.go
  orc8r/cloud/go/services/streamer/servicers/servicer.go
  orc8r/cloud/go/services/streamer/streamer/main.go
  orc8r/lib/go/registry/global_registry.go
  orc8r/lib/go/registry/registry.go
Labels: component: agw

#4819 [Redis] Add a timeout + renewal logic to Redis Lock, and some test refactor
  lte/gateway/python/magma/mobilityd/tests/test_ipv6_allocator.py
  lte/gateway/python/magma/mobilityd/tests/test_static_ip_alloc.py
  orc8r/gateway/python/magma/common/redis/containers.py
  orc8r/gateway/python/magma/common/redis/mocks/mock_redis.py
  orc8r/gateway/python/magma/common/redis/tests/dict_tests.py
  orc8r/gateway/python/magma/directoryd/rpc_servicer.py
  orc8r/gateway/python/magma/directoryd/tests/rpc_servicer_tests.py
  orc8r/gateway/python/magma/state/tests/garbage_collector_test.py
  orc8r/gateway/python/magma/state/tests/state_replicator_test.py
  orc8r/gateway/python/setup.py
Labels: apply-v1.4, component: agw, component: cwag

#4855 [NMS] Run prod version of NMS instead of dev
  orc8r/cloud/helm/orc8r/charts/nms/templates/magmalte-deployment.yaml
Labels: component: agw, component: cwag

#4923 [lte][agw] Adding null check for ht keys on UEs context on stale eNB state
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: apply-v1.4, component: agw

#4933 AGW: envoy: delay envoy to let the controller boot up
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
Labels: apply-v1.4

#4738 [NMS] Add Header Enrichment Config
  nms/app/packages/magmalte/app/components/GatewayUtils.js
  nms/app/packages/magmalte/app/state/lte/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/GatewayConfigTest.js
  nms/app/packages/magmalte/app/views/traffic/PolicyEdit.js
  nms/app/packages/magmalte/app/views/traffic/PolicyHeaderEnrichment.js
  nms/app/packages/magmalte/app/views/traffic/__tests__/PolicyAddEditTest.js
Labels: component: agw, component: cwag

#4649 [ci] Add Codecov code coverage for cloud Go files
  .circleci/config.yml
  .gitignore
  cwf/cloud/go/go.sum
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/Makefile
  orc8r/cloud/docker/build.py
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
  orc8r/cloud/go/Makefile
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/tools.go
  wifi/cloud/go/go.sum
Labels: component: agw, component: cwag

#4952 [lte][agw] Change eNB ID initialization from 0 to 0xFFFFFFFF
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: apply-v1.4, component: agw

#4946 [lte][agw] Remove redundant mme_app_handle_modify_bearer_rsp
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
Labels: apply-v1.4, component: agw

#3474 [docs] Add note for tcpdump requirement for DHCP_BROADCAST IP allocation
  docs/readmes/howtos/ue_ip_address_management.md
Labels: component: agw, component: cwag

#4936 [orc8r][docs]Add introduction documentation for orc8r
  docs/docusaurus/sidebars.json
  docs/readmes/assets/orc8r/orc8r_configuration.png
  docs/readmes/assets/orc8r/orc8r_metrics.png
  docs/readmes/assets/orc8r/orc8r_overview.png
  docs/readmes/assets/orc8r/orc8r_plugin.png
  docs/readmes/assets/orc8r/orc8r_service_mesh.png
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/intro.md
Labels: apply-v1.4

#4961 [feg] s6a handle more than one Regional-Subscription-Zone-Code AVP
  feg/cloud/go/protos/s6a_proxy.pb.go
  feg/gateway/services/s6a_proxy/servicers/s6a_definitions.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy_test.go
  feg/gateway/services/s6a_proxy/servicers/test/test_s6a_server.go
  feg/gateway/services/s6a_proxy/servicers/ul.go
  feg/protos/s6a_proxy.proto
Labels: component: agw, component: feg

#3642 [CI][Doc] Add design proposal for make master stable task
  docs/readmes/proposals/p008_mandatory_integration_tests_for_each_PR.md
Labels: component: docs

#4708 [s1sim testcase][lte][plmn restriction] Adding testcase to test restricted plmn
  lte/gateway/deploy/roles/magma/files/update_mme_config_for_sanity.sh
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_restricted_plmn.py
Labels: component: agw, component: cwag

#4448 [agw][lte] PLMN restriction
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, component: cwag

#4982 [NMS] Fix the nginx proxy config to ensure that https protocol information is included in the header
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/etc/_nginx_proxy_ssl.conf.tpl
Labels: apply-v1.4

#4975 AGW: pipelineD: qos: handle parsing qos parsing.
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
Labels: apply-v1.4

#3808 [5G: MVC][component: agw][type: enhancement] sctp and sctpd modifications to support eNB and gNB sctp connections #2035
  lte/cloud/go/protos/sctpd.pb.go
  lte/gateway/c/oai/common/amf_default_values.h
  lte/gateway/c/oai/common/common_types.h
  lte/gateway/c/oai/include/sctp_messages_def.h
  lte/gateway/c/oai/include/sctp_messages_types.h
  lte/gateway/c/oai/include/tasks_def.h
  lte/gateway/c/oai/lib/3gpp/3gpp_23.003.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/sctp/sctp_itti_messaging.c
  lte/gateway/c/oai/tasks/sctp/sctp_itti_messaging.h
  lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.h
  lte/gateway/c/oai/tasks/sctp/sctpd_uplink_server.cpp
  lte/gateway/c/sctpd/sctp_connection.cpp
  lte/gateway/c/sctpd/sctp_connection.h
  lte/gateway/c/sctpd/sctpd_downlink_impl.cpp
  lte/gateway/c/sctpd/sctpd_downlink_impl.h
  lte/gateway/c/sctpd/sctpd_event_handler.cpp
  lte/gateway/c/sctpd/sctpd_event_handler.h
  lte/protos/sctpd.proto
Labels: 5G: MVC, component: agw, component: cwag, type: enhancement

#4788 [feg] Add on docs on how to build feg and how to get magma releases
  docs/readmes/basics/prerequisites.md
  docs/readmes/feg/deploy_build.md
  docs/readmes/feg/federated_FWA_setup_guide.md
Labels: apply-v1.4, component: agw, component: cwag

#4761 [directoryd][mobilityd] Add GRPC messages to service log
  lte/gateway/configs/directoryd.yml
  lte/gateway/configs/mobilityd.yml
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  lte/gateway/python/magma/mobilityd/tests/rpc_servicer_tests.py
  orc8r/gateway/python/magma/directoryd/main.py
  orc8r/gateway/python/magma/directoryd/rpc_servicer.py
  orc8r/gateway/python/magma/directoryd/tests/rpc_servicer_tests.py
Labels: apply-v1.4, component: agw, component: cwag

#4988 [docs] Change helm chart version mentioned in orc8r upgrade documentation
  docs/readmes/orc8r/upgrade_1_4.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: apply-v1.4

#4992 Rewrite pipelined stateless stats recovery
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
Labels: apply-v1.4

#4991 [lte][agw] Fix null pointer access in delete session response
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
Labels: apply-v1.4, component: agw

#5003 [lte][agw] Fixing inverse GTP throughput stats, increasing polling interval to 3 mins
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/gtp_stats_collector.py
Labels: apply-v1.4, component: agw, component: cwag

#5002 [NMS] Fixing the dashboard title
  nms/app/packages/magmalte/grafana/dashboards/Dashboards.js
Labels: apply-v1.4

#4571 magma: Header Enrichment: Add How To doc.
  docs/docusaurus/sidebars.json
  docs/readmes/howtos/header_enrichment.md
Labels: component: agw, component: cwag

#4905 [orc8r][docs] More 1.4 upgrade feedback
  docs/readmes/orc8r/upgrade_1_4.md
Labels: component: agw, component: cwag

#4974 [CI] Upload test results to CircleCI for LTE tests and LTE-IntegTests
  .circleci/config.yml
  circleci/fabfile.py
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/Makefile
  orc8r/gateway/python/python.mk
Labels: component: agw, component: ci

#5017 [SessionD] Reduce GRPC calls from SessionD to PipelineD
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: apply-v1.4, component: agw

#5008 [orc8r] make s8 proxy optional in swagger api
  feg/cloud/go/services/feg/obsidian/models/network_federation_configs_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
Labels: apply-v1.4, component: feg

#5027 AGW: pipelined: Fix QoS setup
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: apply-v1.4, component: agw

#5028 AGW: pipelined: qos: make id allocator atomic
  lte/gateway/python/magma/pipelined/qos/utils.py
Labels: apply-v1.4, component: agw

#5036 Fix Pipelined Restart Recovery Reply
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: apply-v1.4, component: agw

#5038 AGW: envoy-dp: set default logging
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
Labels: apply-v1.4, component: agw

#5018 [SessionD] Terminate session after pipelined GRPC failure
  lte/gateway/c/session_manager/LocalEnforcer.cpp
Labels: component: agw, component: cwag

#5041 [agw][s1ap test] Fix to ignore paging ind message and wait for ICS Req
  lte/gateway/python/integ_tests/s1aptests/test_service_req_ul_udp_data_with_mme_restart.py
Labels: component: agw

#5046 Fix stale chart lock in 1.4
  orc8r/cloud/helm/orc8r/Chart.lock
Labels: component: agw, component: cwag

#5052 [FeG][Orc8r] Add directoryd configs
  cwf/gateway/configs/directoryd.yml
  feg/gateway/configs/directoryd.yml
  orc8r/gateway/configs/directoryd.yml
Labels: component: cwag

#5031 [LTE][CI] set per-test 900s timeout for LTE integration tests
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw

#5035 AGW: pipelined: qos: fix recovery of APN AMBR config
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/qos/types.py
  lte/gateway/python/magma/pipelined/qos/utils.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: apply-v1.4, component: agw

#4895 [orc8r] Expose the combine Swagger spec process to the obsidian service
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  lte/cloud/go/go.sum
  orc8r/cloud/configs/obsidian.yml
  orc8r/cloud/go/obsidian/config.go
  orc8r/cloud/go/obsidian/obsidian/main.go
  orc8r/cloud/go/obsidian/server/server.go
  orc8r/cloud/go/obsidian/swagger/handlers/handlers.go
  orc8r/cloud/go/obsidian/swagger/handlers/handlers_test.go
  orc8r/cloud/go/obsidian/swagger/spec_servicer.go
  orc8r/cloud/go/obsidian/tests/unit_test_utils.go
  orc8r/cloud/go/swagger/spec.go
  wifi/cloud/go/go.sum
Labels: component: agw, component: cwag

#5050 [NMS] Minor change to title IP address -> Session IP address
  nms/app/packages/magmalte/app/views/subscriber/SubscriberOverview.js
Labels: apply-v1.4

#5055 [SessionD][v1.4] Deactivate flows for dead sessions on usage reporting
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
Labels: component: agw, component: cwag

#5056 [sessiond] Add teids to deactivate request
  lte/gateway/c/session_manager/PipelinedClient.cpp
Labels: component: agw

#5061 [LTE][CI] use timeout instead of unreliable nose timeout
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw

#5030 [lte][agw] Fixing null ptr access for PDN context sgw teid on handling create session response
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
Labels: apply-v1.4, component: agw

#5029 AGW: gtp-ovs: Fix for GTP Header extn in downlink
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier_traffic.GTPTrafficTest.test_traffic_flows.snapshot
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/Makefile
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/gtp.c
Labels: component: agw

#3272 [5G: MVC][component: agw][type: enhancement] [AMF] Set interface client for AMF towards SMF
  lte/gateway/c/oai/lib/CMakeLists.txt
  lte/gateway/c/oai/lib/n11/CMakeLists.txt
  lte/gateway/c/oai/lib/n11/SmfServiceClient.cpp
  lte/gateway/c/oai/lib/n11/SmfServiceClient.h
Labels: 5G: MVC, component: agw, type: enhancement

#5069 AGW: envoy-dp: Fix service dependency.
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
Labels: apply-v1.4, component: agw

#5070 [MME] Fix MME compile errors from compiling with GCC/G++8
  lte/gateway/c/oai/include/mme_events.h
  lte/gateway/c/oai/include/state_converter.h
  lte/gateway/c/oai/lib/event_client/EventClientAPI.cpp
  lte/gateway/c/oai/lib/event_client/EventClientAPI.h
  lte/gateway/c/oai/lib/s6a_proxy/s6a_client_api.cpp
  lte/gateway/c/oai/tasks/mme_app/mme_events.cpp
  lte/gateway/c/oai/test/mobility_client/test_mobility_client.cpp
Labels: component: agw

#5062 [mme] Fixup missing includes in various headers
  lte/gateway/c/oai/include/async_system_messages_types.h
  lte/gateway/c/oai/include/gx_messages_types.h
  lte/gateway/c/oai/include/mme_app_messages_types.h
  lte/gateway/c/oai/include/pgw_types.h
  lte/gateway/c/oai/lib/3gpp/3gpp_23.003.h
  lte/gateway/c/oai/lib/3gpp/3gpp_36.401.h
  lte/gateway/c/oai/lib/3gpp/3gpp_36.413.h
  lte/gateway/c/oai/lib/message_utils/bytes_to_ie.c
  lte/gateway/c/oai/lib/openflow/controller/ControllerMain.h
  lte/gateway/c/oai/lib/openflow/controller/IMSIEncoder.h
  lte/gateway/c/oai/lib/openflow/controller/OpenflowController.h
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_asDef.h
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr_context.h
  lte/gateway/c/oai/tasks/nas/esm/esm_proc.h
  orc8r/gateway/c/common/config/MConfigLoader.h
Labels: component: agw

#5085 [MME] Reduce mobilityd client in MME's GRPC timeout from 30->10 sec
  lte/gateway/c/oai/lib/mobility_client/MobilityServiceClient.h
Labels: component: agw

#5084 [lte][agw] Handle null eNB context
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: apply-v1.4, component: agw

#5094 [pipelined]Fix Null Rule Removal Error
  lte/gateway/python/magma/pipelined/app/enforcement.py
Labels: apply-v1.4

#5091 [AGW] [MME] Clean up eNB state at restart to remove UEs without S1ap state
  lte/gateway/c/oai/include/s1ap_state.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp
Labels: apply-v1.4, component: agw

#5104 [pipelined]Fix Early Rule Removal error
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
Labels: apply-v1.4, component: agw

#4859 [fwa][ha] Add documentation for AWS HA AGW
  docs/docusaurus/sidebars.json
  docs/readmes/lte/ha_setup.md
  lte/gateway/deploy/agw_install.sh
Labels: apply-v1.4, component: agw, component: cwag

#4596 [5G][component: agw][type: enhancement][pipelined] Multi-Tunnel Functionality Support For 5G in pipelined.
  lte/gateway/configs/pipelined.yml
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/bridge_util.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_multi_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_attach_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_classifier.ClassifierTest.test_detach_multi_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_classifier.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_traffic.py
  lte/gateway/python/magma/pipelined/utils.py
Labels: component: agw, component: cwag

#5106 [helm] update default service_regsitry.mode to k8s
  cwf/cloud/helm/cwf-orc8r/Chart.yaml
  cwf/cloud/helm/cwf-orc8r/values.yaml
  docs/readmes/orc8r/upgrade_1_4.md
  fbinternal/cloud/helm/fbinternal-orc8r/Chart.yaml
  fbinternal/cloud/helm/fbinternal-orc8r/values.yaml
  feg/cloud/helm/feg-orc8r/Chart.yaml
  feg/cloud/helm/feg-orc8r/values.yaml
  lte/cloud/helm/lte-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/values.yaml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/values.yaml
  wifi/cloud/helm/wifi-orc8r/Chart.yaml
  wifi/cloud/helm/wifi-orc8r/values.yaml
Labels: apply-v1.4, component: agw, component: cwag

#5108 [lte][agw] Reset hash table size to 0 upon destroy
  lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c
Labels: apply-v1.4, component: agw

#5122 [AGW][MME} Fix pointer dereferencing in get_mme_ue_ids_no_imsi
  lte/gateway/c/oai/tasks/s1ap/s1ap_state.cpp
Labels: apply-v1.4, component: agw

#4907 [Docs] A Design Doc for the Public Proposal Process
  docs/readmes/proposals/README.md
  docs/readmes/proposals/TEMPLATE.md
Labels: component: agw, component: cwag
