Repository magma/magma, pull requests merged in 2021-01, with the labels that each got.

#4195 [CI][orc8r] Bump bare metal deploy to 1.3.2
  orc8r/cloud/deploy/bare-metal/charts/mariadb-galera.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/mariadb.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/orc8r.yaml.tpl
  orc8r/cloud/deploy/bare-metal/deploy.sh
  orc8r/cloud/deploy/bare-metal/deploy_charts.sh
  orc8r/cloud/deploy/bare-metal/orc8r_settings
Labels: component: agw, component: cwag

#4178 [docker] use `--no-cache-dir` flag to `pip` in dockerfiles to save space
  cwf/gateway/docker/python/Dockerfile
  feg/gateway/docker/python/Dockerfile
  lte/gateway/docker/deploy/Dockerfile
  orc8r/cloud/docker/nginx/Dockerfile
  orc8r/gateway/docker/Dockerfile
Labels: component: agw, component: cwag

#4218 [pipelined]Fix Stateless flow comparison edge case
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/openflow/messages.py
Labels: component: agw, component: cwag

#4174 Provided fix for memory leak
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: component: agw, component: cwag

#3994 [agw][stateless][new tc] New TCs to test mme restart in unregistered state
  lte/gateway/python/integ_tests/s1aptests/test_no_auth_response_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_auth_response_with_mme_restart_reattach.py
  lte/gateway/python/integ_tests/s1aptests/test_no_esm_information_rsp_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_smc_with_mme_restart_reattach.py
Labels: component: agw, component: cwag

#4120 [lte][stateless][s1sm tc] Add s1 sim testcase to test multiple services restart with multiple p…
  lte/gateway/python/integ_tests/s1aptests/test_secondary_pdn_with_dedicated_bearer_multiple_services_restart.py
Labels: component: agw, component: cwag

#4138 [orc8r][dev_setup] Improve dev_setup to recreate certs if any admin_operator cert is missing
  orc8r/cloud/docker/controller/create_test_controller_certs
Labels: accept2ship, component: orc8r

#4205 [cwag integ test} Some fixes for integ test
  cwf/gateway/integ_tests/auth_test.go
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_reauth_test.go
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/services/uesim/servicers/iperf_server_restarter.go
  cwf/gateway/services/uesim/servicers/uesim.go
Labels: component: agw, component: cwag

#4228 [Orc8r] Fix appID and appSecret order set in exporter
  orc8r/cloud/go/services/analytics/exporter.go
Labels: component: agw, component: cwag

#4219 [agw][stateless] Use python Redis client instead of shell CLI
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: component: agw, component: cwag

#4215 [NMS] Minor EventTable refactoring
  nms/app/packages/magmalte/app/components/ActionTable.js
  nms/app/packages/magmalte/app/views/dashboard/lte/LteDashboard.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/GatewayLogs.js
  nms/app/packages/magmalte/app/views/events/EventsTable.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberDetail.js
Labels: component: agw, component: cwag

#4173 [agw][cli] Fix state_cli.py to properly parse policydb rules
  lte/gateway/python/scripts/state_cli.py
Labels: component: agw

#4133 [orc8r][test] Support running all unit tests from host
  docs/docusaurus/create_docusaurus_website.sh
  docs/docusaurus/sidebars.json
  docs/readmes/assets/orc8r/intellij_multirun.png
  docs/readmes/assets/orc8r/intellij_subproject_configs.png
  docs/readmes/orc8r/development/testing_tips.md
  orc8r/cloud/go/services/bootstrapper/servicers/bootstrapper_test.go
  orc8r/gateway/go/services/bootstrapper/service/bootstrapper.go
Labels: component: agw, component: cwag, component: orc8r

#4194 [NMS] Minor Alarms component refactoring
  nms/app/packages/magmalte/app/components/admin/AddNetworkDialog.js
  nms/app/packages/magmalte/app/components/admin/Admin.js
  nms/app/packages/magmalte/app/components/admin/Alerts.js
  nms/app/packages/magmalte/app/components/lte/LteSections.js
  nms/app/packages/magmalte/app/state/AlarmsApiUtil.js
  nms/app/packages/magmalte/app/state/SyncAlerts.js
  nms/app/packages/magmalte/app/views/alarms/Alarms.js
  nms/app/packages/magmalte/app/views/alarms/AlertRules.js
Labels: component: agw, component: cwag

#4240 [agw][mme] Replace ctime_r with strftime
  lte/gateway/c/oai/common/log.c
Labels: apply-v1.3, component: agw, component: cwag

#4224 [xwfm][ci] make CI use XWF-OpenFlow AWS setup instead of building local
  .circleci/config.yml
  xwf/docker/docker-compose.override.yml
  xwf/docker/docker-compose.yml
  xwf/gateway/integ_tests/gw/entrypoint.sh
Labels: component: agw, component: cwag

#4137 [orc8r][tools] Clean up combine_swagger
  .gitignore
  cwf/cloud/go/Makefile
  fbinternal/cloud/go/Makefile
  feg/cloud/go/Makefile
  feg/gateway/services/testcore/mock_driver/mock_driver.go
  lte/cloud/go/Makefile
  lte/cloud/go/services/smsd/obsidian/models/conversion.go
  lte/cloud/go/services/smsd/obsidian/models/gen.go
  lte/cloud/go/services/smsd/obsidian/models/mutable_sms_message_swaggergen.go
  lte/cloud/go/services/smsd/obsidian/models/sms_message_swaggergen.go
  lte/cloud/go/services/smsd/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/smsd/servicers/smsd_rest.go
  orc8r/cloud/Makefile
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
  orc8r/cloud/go/Makefile
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/tools/combine_swagger/main.go
  orc8r/cloud/go/tools/combine_swagger/spec/combine.go
  orc8r/cloud/go/tools/combine_swagger/spec/combine_test.go
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/common/common.yml
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/configs/base.yml
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/configs/cycle1.yml
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/configs/cycle2.yml
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/configs/importer.yml
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/configs/importer2.yml
  orc8r/cloud/go/tools/combine_swagger/spec/testdata/out.yml.golden
  orc8r/cloud/go/tools/swaggergen/generate/generate.go
  wifi/cloud/go/Makefile
Labels: component: agw, component: cwag, component: orc8r

#4139 Added test cases to validate timers, 3450 and 3470 timers while mme restarts
  lte/gateway/python/integ_tests/s1aptests/test_no_attach_complete_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_identity_rsp_with_mme_restart.py
Labels: component: agw, component: cwag

#4241 [feg][nh] Enable Neutral Host Routing for FeG Hello Service
  feg/cloud/configs/service_registry.yml
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/hello_relay.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/relay_test.go
Labels: component: cwag, component: feg

#4115 [lte][agw] Extending enbConnected to enbState on s1ap_service
  lte/cloud/go/protos/s1ap_service.pb.go
  lte/cloud/go/services/lte/obsidian/models/defaults.go
  lte/gateway/c/oai/tasks/grpc_service/S1apServiceImpl.cpp
  lte/gateway/c/oai/tasks/grpc_service/S1apServiceImpl.h
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/s1ap_client.py
  lte/protos/s1ap_service.proto
Labels: component: agw, component: cwag

#3677 Add Envoy Install to Build Script
  feg/gateway/Makefile
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/release/build-magma.sh
  orc8r/gateway/python/setup.py
Labels: component: agw, component: cwag

#4169 [magma][lib] Default timeout for all Go GRPC client connections (local & cloud)
  orc8r/lib/go/registry/cloud_connection.go
  orc8r/lib/go/registry/interceptors.go
  orc8r/lib/go/registry/registry.go
  orc8r/lib/go/service/middleware/unary/client_identity.go
Labels: accept2ship, component: agw, component: cwag, component: feg, component: lib, type: enhancement

#4253 [orc8r][dev] Share default run configurations
  .run/README.md
  .run/go test all.run.xml
  .run/go test cwf.run.xml
  .run/go test fbinternal.run.xml
  .run/go test feg.run.xml
  .run/go test lte.run.xml
  .run/go test orc8r.run.xml
  .run/go test wifi.run.xml
  docs/readmes/orc8r/development/testing_tips.md
Labels: component: agw, component: cwag

#4245 [orc8r][gen] Clean up swaggergen tool
  cwf/cloud/go/services/cwf/obsidian/models/feg_network_id_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/gen.go
  cwf/cloud/go/services/cwf/obsidian/models/health_configs_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/li_imsis_swaggergen.go
  cwf/cloud/go/services/cwf/obsidian/models/swagger.v1.yml
  fbinternal/cloud/go/serdes/serdes.go
  fbinternal/cloud/go/services/testcontroller/obsidian/models/gen.go
  fbinternal/cloud/go/services/testcontroller/obsidian/models/serdes.go
  fbinternal/cloud/go/services/testcontroller/obsidian/models/swagger.v1.yml
  fbinternal/cloud/go/services/testcontroller/obsidian/models/test_config_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/gateway_ran_configs_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/gen.go
  lte/cloud/go/services/lte/obsidian/models/gen.go
  lte/cloud/go/services/lte/obsidian/models/rating_group_id_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/subscriber_state_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/untyped_mme_state_swaggergen.go
  lte/cloud/go/services/policydb/obsidian/models/gen.go
  lte/cloud/go/services/smsd/obsidian/models/gen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/gen.go
  orc8r/cloud/Makefile
  orc8r/cloud/docker/controller/apidocs/v1/goswagger-config.yml
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
  orc8r/cloud/go/models/gen.go
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/services/ctraced/obsidian/models/gen.go
  orc8r/cloud/go/services/eventd/obsidian/models/gen.go
  orc8r/cloud/go/services/metricsd/obsidian/models/gen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/fluent_bit_configs_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/gen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/tenants/obsidian/models/gen.go
  orc8r/cloud/go/tools/swaggergen/generate/generate.go
  orc8r/cloud/go/tools/swaggergen/generate/generate_test.go
  orc8r/cloud/go/tools/swaggergen/generate/rewrite.go
  orc8r/cloud/go/tools/swaggergen/generate/rewrite_test.go
  orc8r/cloud/go/tools/swaggergen/main.go
  orc8r/cloud/go/tools/swaggergen/testdata/config.yml
  wifi/cloud/go/services/wifi/obsidian/models/gen.go
Labels: component: agw, component: cwag

#4155 [lte][gateway][focal] add ubuntu focal fossa vagrant vm
  lte/gateway/Vagrantfile
  lte/gateway/deploy/hosts
  lte/gateway/deploy/magma_dev_focal.yml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/focal_hacks/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  orc8r/tools/ansible/roles/fluent_bit/tasks/main.yml
  orc8r/tools/ansible/roles/python_dev/tasks/main.yml
  third_party/build/bin/folly_build.sh
  third_party/build/bin/freediameter_build.sh
  third_party/build/bin/libfluid_build.sh
  third_party/build/patches/libfluid/libfluid_base_patches/EVLOOP_NO_EXIT_ON_EMPTY_compat.patch
Labels: component: agw, component: cwag

#4047 [orc8r][ctraced] Implement basic handlers for call tracing
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/docker/controller/supervisord.conf
  orc8r/cloud/go/orc8r/const.go
  orc8r/cloud/go/serdes/serdes.go
  orc8r/cloud/go/services/ctraced/ctraced/main.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/ctraced/obsidian/models/conversion.go
  orc8r/cloud/go/services/ctraced/obsidian/models/serdes.go
  orc8r/cloud/go/services/ctraced/obsidian/models/validate.go
Labels: component: agw, component: cwag

#4188 [ctraced][orc8r] Add delete function to ctraced blobstore
  orc8r/cloud/go/services/ctraced/storage/storage.go
  orc8r/cloud/go/services/ctraced/storage/storage_blobstore.go
  orc8r/cloud/go/services/ctraced/storage/storage_blobstore_test.go
Labels: component: agw, component: cwag

#2318 Add Connection Tracking Service
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/Makefile
  lte/gateway/c/connection_tracker/CMakeLists.txt
  lte/gateway/c/connection_tracker/EventTracker.cpp
  lte/gateway/c/connection_tracker/EventTracker.h
  lte/gateway/c/connection_tracker/PacketGenerator.cpp
  lte/gateway/c/connection_tracker/PacketGenerator.h
  lte/gateway/c/connection_tracker/main.cpp
  lte/gateway/configs/connectiond.yml
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/service_registry.yml
  lte/gateway/deploy/roles/magma/files/systemd/magma_connectiond.service
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/app/conntrack.py
  lte/gateway/python/magma/pipelined/tests/test_conntrack.py
  lte/gateway/release/build-magma.sh
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, component: cwag

#3641 [Stateless_Testing] [New_Test_Cases] Added new multi UE stateless test cases
  lte/gateway/python/integ_tests/s1aptests/test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_mme_restart_detach_multi_ue.py
Labels: component: agw

#4266 [lte][helm] Fix HA k8s service typo
  lte/cloud/helm/lte-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/templates/ha.service.yaml
Labels: component: agw, component: cwag

#4264 Add Envoy Build to LTE Integ Test
  lte/gateway/Makefile
Labels: component: agw, component: cwag

#2378 [5G:MVC pipelined] Node Association Manager
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/magma/pipelined/app/ng_services.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/ng_manager/__init__.py
  lte/gateway/python/magma/pipelined/ng_manager/node_state_manager.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/set_interface_client.py
  lte/gateway/python/magma/pipelined/tests/app/start_pipelined.py
  lte/gateway/python/magma/pipelined/tests/ng_node_rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/test_ng_servicer_node.py
Labels: 5G: MVC, component: agw, component: cwag, type: enhancement

#4274 [AGW] Typo in build-magma.sh for libmnl-dev
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag

#4213 [Orc8r] Add analytics.yml in values file
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/secrets/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/secrets/values.yaml
Labels: component: agw, component: cwag

#4272 [agw][lte][bug fix] Fixed malformed ue radio capability msg embedded in ICS req
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: apply-v1.3, component: agw, component: cwag

#4276 Corrected test case, test_attach_asr.py to receive Detach Request and send Detach Accept
  lte/gateway/python/integ_tests/s1aptests/test_attach_asr.py
Labels: component: agw, component: cwag

#4275 Modified code to update mme_s11_teid to UE context for non-zero mme_s11_teid
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw, component: cwag

#3749 [AGW] [Stateless] [Sanity_Testing] Disabled stateless mode after execution of sanity test
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_restore_mme_config_after_sanity.py
Labels: component: agw, component: cwag

#4261 Update Codeowners for Connection Tracker Service
  CODEOWNERS
Labels: component: agw, component: cwag

#4247 [lte][agw] support `make build_oai` on ubuntu 20.04
  lte/gateway/Makefile
  lte/gateway/c/oai/include/state_converter.h
Labels: component: agw, component: cwag

#4267 [docs] Add a step telling the user to install Go on setup
  docs/readmes/basics/prerequisites.md
Labels: accept2ship, component: agw, component: cwag, component: docs

#4163 [ctraced][orc8r] REST API handlers will start/stop tracing in gateways
  orc8r/cloud/go/obsidian/tests/unit_test_utils.go
  orc8r/cloud/go/services/ctraced/client_api.go
  orc8r/cloud/go/services/ctraced/ctraced/main.go
  orc8r/cloud/go/services/ctraced/doc.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/gateway_api.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/ctraced/obsidian/models/conversion.go
  orc8r/cloud/go/services/dispatcher/gateway_registry/gw_registry.go
Labels: component: agw, component: cwag

#4269 [agw][stateless] Move Sctpd restart logic from MME service to config_stateless_agw.py
  lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.h
  lte/gateway/deploy/roles/magma/files/systemd/magma_mme.service
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: breaking change, component: agw

#4282 Revert "[lte][agw] changes need for `make build_oai` and `make build_…
  lte/gateway/Makefile
  lte/gateway/c/oai/include/state_converter.h
Labels: component: agw, component: cwag

#4203 [orc8r][ctraced] Added REST endpoint and handler for downloading traces
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/ctraced/obsidian/models/swagger.v1.yml
Labels: component: agw, component: cwag

#4283 AGW: pipelined: Fix ng_manager packaging.
  lte/gateway/python/setup.py
Labels: component: agw, component: cwag

#4271 [lte][agw] Adding SGW IPv4 S1U endpoint address as EPC config
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/obsidian/models/gateway_epc_configs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/gateway/python/scripts/generate_oai_config.py
  lte/protos/mconfig/mconfigs.proto
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
Labels: component: agw, component: cwag, component: orc8r

#4284 [lte] [gen] Remove redundant swagger_gen code
  lte/cloud/go/services/lte/obsidian/models/apn_list_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/conversion.go
  orc8r/cloud/docker/build.py
Labels: component: agw, component: cwag

#4263 [DOC] OAI EPC is also under BSD-3-Clause license
  README.md
Labels: component: agw, component: cwag

#3568 [CI][Jenkins] add LTE and CWAG Jenkins pipelines converted from CircleCI
  ci-scripts/JenkinsFile-CWAG-integ-test
  ci-scripts/JenkinsFile-CWAG-integ-test-libvirt
  ci-scripts/JenkinsFile-LTE-integ-test
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, component: cwag

#4295 [orc8r][1.4] Update orc8r installation for version 1.4
  .circleci/config.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/README.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/docker/Dockerfile
  orc8r/cloud/docker/controller/Dockerfile
  orc8r/cloud/docker/docker-compose.override.yml
  orc8r/tools/helm/package.sh
Labels: component: agw, component: cwag

#4297 Added code to remove SPGW's UE context from Redis DB
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.h
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/oai/tasks/sgw/sgw_task.c
Labels: component: agw, component: cwag

#4301 [agw] [stateless] Add explicit override for stateful config
  lte/gateway/python/scripts/config_stateless_agw.py
  orc8r/gateway/python/magma/common/stateless_agw.py
Labels: component: agw, component: cwag

#4235 [ctraced][nms] Add page and tab for controlling call tracing
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/ActionTable.js
  nms/app/packages/magmalte/app/components/context/TraceContext.js
  nms/app/packages/magmalte/app/components/lte/LteContext.js
  nms/app/packages/magmalte/app/components/lte/LteSections.js
  nms/app/packages/magmalte/app/state/TraceState.js
  nms/app/packages/magmalte/app/views/tracing/TraceStartDialog.js
  nms/app/packages/magmalte/app/views/tracing/TracingDashboard.js
  nms/app/packages/magmalte/scripts/mockServer.js
Labels: component: agw, component: cwag

#4303 [lte][agw] Fix broken build due to mistake in resolving merge conflict
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
Labels: backported-v1.3, component: agw, component: cwag

#4302 [lte][agw] Remove paging timer when ue context is removed
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: apply-v1.3, component: agw, component: cwag

#4262 [NMS] Add monitord to the list of dynamic services supported by the gateway
  nms/app/packages/magmalte/app/components/GatewayUtils.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/GatewayConfigTest.js
Labels: component: agw, component: cwag

#4309 Revert "[lte][agw] Fix broken build due to mistake in resolving merge conflict"
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/sctp/sctpd_downlink_client.cpp
Labels: component: agw, component: cwag

#4311 [orc8r][insync] Fix failing orc8r insync checkin by updating orc8r test image
  orc8r/cloud/docker/docker-compose.override.yml
Labels: component: agw, component: cwag

#4312 [lte][agw] Backport v1 3 ab61537
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw, component: cwag

#4310 Revert "[lte][agw]Bug fix for missing ue context at spgw (#4141)"
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: component: agw, component: cwag

#4313 [lte][agw] Backport v1 3 c575e3d1
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: component: agw, component: cwag

#4273 [agw][lte][bug fix] Bug fix and add TCs to sanity suite
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
Labels: component: agw, component: cwag

#4265 [NMS] Minor cleanup in eNodeB component
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/state/lte/EquipmentState.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js
  nms/app/packages/magmalte/app/views/equipment/EquipmentEnodeb.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailEnodebs.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebDetailMainTest.js
Labels: component: agw, component: cwag

#4314 [lte][agw] Backport PR 4273
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
Labels: component: agw, component: cwag

#4296 [NMS] Adding gateway dialog to troubleshoot aggregation issues
  nms/app/packages/magmalte/app/components/DataGrid.js
  nms/app/packages/magmalte/app/components/GatewayCommandFields.js
  nms/app/packages/magmalte/app/components/__tests__/GatewayCommandTest.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailMain.js
Labels: component: agw, component: cwag

#4316 [lte][agw] Backport PR4302 to mme_testing branch
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw, component: cwag

#4317 [lte][agw] Removed residuals in the merge of c92e8d676
  lte/gateway/c/oai/common/log.c
Labels: component: agw, component: cwag

#4305 [agw][stateless] Set default AGW mode to stateless
  lte/gateway/configs/mme.yml
  lte/gateway/configs/mobilityd.yml
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/configs/sessiond.yml
  lte/gateway/configs/sessiond.yml_prod
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_restore_mme_config_after_sanity.py
Labels: component: agw, component: cwag

#4318 [lte][agw] Remove paging timer when ue context is removed
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
Labels: component: agw, component: cwag

#4319 [lte][agw] Backport v1 3 c575e3d1 (#4313)
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
Labels: component: agw, component: cwag

#4320 [lte][agw] Backport v1 3 test e736aef7
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_standalone_act_dflt_ber_ctxt_rej_ded_bearer_activation.py
Labels: component: agw, component: cwag

#4308 [AGW][S1APTests] Clean UE interfaces from previous unsuccessful runs
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
Labels: component: agw, component: cwag

#4315 [Orc8r] Minor fixes in Analytics Service
  cwf/cloud/configs/cwf.yml
  lte/cloud/configs/lte.yml
  lte/cloud/go/services/lte/analytics/analytics.go
  lte/cloud/go/services/lte/analytics/calculations/state.go
  orc8r/cloud/configs/orchestrator.yml
  orc8r/cloud/go/services/analytics/collector_servicer.go
Labels: component: agw, component: cwag

#4307 [NMS] Minor cleanup in log component and alerts dashboard
  nms/app/packages/magmalte/app/components/DashboardAlertTable.js
  nms/app/packages/magmalte/app/components/__tests__/DashboardAlertTableTest.js
  nms/app/packages/magmalte/app/theme/default.js
  nms/app/packages/magmalte/app/views/equipment/GatewayLogs.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/GatewayLogsTest.js
Labels: component: agw, component: cwag

#4328 [AGW]Bump lxml to 4.6.2
  lte/gateway/python/setup.py
Labels: component: agw, component: cwag

#4329 [NMS] Add axios as nms dependency and bump to ^0.21.1
  nms/app/package.json
  nms/app/yarn.lock
Labels: component: agw, component: cwag

#4337 [backport v1.3] [pipelined]Fix NIL Delete in QOS Restart Recovery
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, component: cwag

#4324 fix artifacts archive command placement in LTE pipeline
  ci-scripts/JenkinsFile-LTE-integ-test
Labels: component: agw, component: cwag

#4327 [CODEOWNER] Add tim to lte/gateway/release
  CODEOWNERS
Labels: component: agw, component: cwag

#4325 [s1 sim][new testcases] Verified the stability of idle mode multi pdn testcases and added them to sanity suite
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, component: cwag

#4351 [orc8r]helm] Fix orc8r helm lock file
  orc8r/cloud/helm/orc8r/Chart.lock
Labels: apply-v1.4, component: agw, component: cwag

#4350 [orc8r][service reg] Update k8s client qps and burst configuration
  orc8r/cloud/go/services/service_registry/service_registry/main.go
Labels: apply-v1.4, component: agw, component: cwag

#4344 [orc8r] [refactor] Refactor instances of []Blob to Blobs (blobstorage)
  cwf/gateway/services/uesim/servicers/ue_store_utils.go
  fbinternal/cloud/go/services/testcontroller/store/testcontroller_store.go
  feg/cloud/go/services/health/servicers/health_test.go
  feg/cloud/go/services/health/storage/health_blobstore.go
  lte/cloud/go/services/subscriberdb/servicers/lookup.go
  orc8r/cloud/go/blobstore/ent.go
  orc8r/cloud/go/blobstore/ent_test.go
  orc8r/cloud/go/blobstore/integration_test.go
  orc8r/cloud/go/blobstore/memory.go
  orc8r/cloud/go/blobstore/memory_test.go
  orc8r/cloud/go/blobstore/mocks/TransactionalBlobStorage.go
  orc8r/cloud/go/blobstore/sql.go
  orc8r/cloud/go/blobstore/sql_test.go
  orc8r/cloud/go/blobstore/storage.go
  orc8r/cloud/go/services/accessd/storage/storage_blobstore.go
  orc8r/cloud/go/services/accessd/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/ctraced/storage/storage_blobstore.go
  orc8r/cloud/go/services/ctraced/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/device/protos/device_helper.go
  orc8r/cloud/go/services/device/servicers/device.go
  orc8r/cloud/go/services/directoryd/storage/storage_blobstore.go
  orc8r/cloud/go/services/directoryd/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/state/indexer/reindex/store.go
  orc8r/cloud/go/services/state/indexer/reindex/store_test.go
  orc8r/cloud/go/services/state/servicers/servicer.go
  orc8r/cloud/go/services/state/servicers/servicer_test.go
  orc8r/cloud/go/services/tenants/servicers/storage/storage.go
  orc8r/cloud/go/services/tenants/servicers/storage/storage_test.go
Labels: component: agw, component: cwag

#4298 [agw][lte] fix compiler warning flags needed for ubuntu focal…
  lte/gateway/Makefile
  lte/gateway/c/oai/include/state_converter.h
Labels: component: agw, component: cwag

#4380 [NMS] Refresh equipment and subscriber state
  nms/app/packages/magmalte/app/components/DateTimeMetricChart.js
  nms/app/packages/magmalte/app/components/context/EnodebContext.js
  nms/app/packages/magmalte/app/components/context/GatewayContext.js
  nms/app/packages/magmalte/app/components/context/RefreshContext.js
  nms/app/packages/magmalte/app/components/context/SubscriberContext.js
  nms/app/packages/magmalte/app/components/lte/LteContext.js
  nms/app/packages/magmalte/app/state/lte/EquipmentState.js
  nms/app/packages/magmalte/app/state/lte/SubscriberState.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js
  nms/app/packages/magmalte/app/views/equipment/EquipmentEnodeb.js
  nms/app/packages/magmalte/app/views/equipment/EquipmentGateway.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EnodebDetailMainTest.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/EquipmentEnodebTest.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberDetail.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberOverview.js
  nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js
  nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberTest.js
Labels: component: agw, component: cwag

#3802 [lte][agw] change install script to enable install of prebuilt openvswitch…
  lte/gateway/deploy/agw_install.sh
  lte/gateway/deploy/roles/ovs_deploy/tasks/main.yml
  lte/gateway/deploy/roles/ovs_deploy/vars/all.yaml
  lte/gateway/fabfile.py
Labels: component: agw, component: cwag

#4294 [ctraced][orc8r] Add Content-Disposition header to trace download API
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/obsidian/models/swagger.v1.yml
Labels: apply-v1.4, component: agw, component: cwag

#4410 [ctraced][orc8r] Add and amend ctraced deployment files
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/templates/ctraced.deployment.yaml
  orc8r/cloud/helm/orc8r/templates/ctraced.pdb.yaml
  orc8r/cloud/helm/orc8r/templates/ctraced.service.yaml
Labels: apply-v1.4, component: agw, component: cwag

#4345 [AGW][SubscriberDb] Limit subscriberdb grpc server to 1 worker
  lte/gateway/python/magma/subscriberdb/main.py
  orc8r/gateway/python/magma/common/service.py
Labels: component: agw, component: cwag

#4409 [Orc8r] Minor changes in Analytics service
  lte/cloud/configs/lte.yml
  lte/cloud/go/services/lte/analytics/analytics.go
  lte/cloud/go/services/lte/analytics/calculations/state.go
  lte/cloud/go/services/lte/analytics/calculations/state_test.go
  orc8r/cloud/configs/orchestrator.yml
  orc8r/cloud/go/services/analytics/collector_servicer.go
  orc8r/cloud/go/services/orchestrator/analytics/analytics.go
  orc8r/cloud/go/services/orchestrator/analytics/calculations/state.go
  orc8r/cloud/go/services/orchestrator/analytics/calculations/state_test.go
Labels: component: agw, component: cwag

#4426 Modified test case such that TC would wait for Attach Reject and receive UE context release request
  lte/gateway/python/integ_tests/s1aptests/test_attach_act_dflt_ber_ctxt_rej.py
Labels: component: agw, component: cwag

#4406 [lte][agw] break COMMON_FLAGS definition into Makefile conditional
  lte/gateway/Makefile
Labels: component: agw, component: cwag

#4184 [EventD] Cleanup RPC Servicer and separate validation logic for better clarity
  orc8r/gateway/python/magma/eventd/event_validator.py
  orc8r/gateway/python/magma/eventd/main.py
  orc8r/gateway/python/magma/eventd/rpc_servicer.py
  orc8r/gateway/python/magma/eventd/tests/event_validation_tests.py
Labels: component: agw, component: cwag

#4227 [sessiond] split CreateSession
  cwf/gateway/services/uesim/servicers/uesim_hssless.go
  feg/gateway/services/aaa/servicers/accounting.go
  feg/gateway/services/aaa/session_manager/client_api.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/test/Consts.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
  lte/gateway/c/session_manager/test/test_store_client.cpp
Labels: SessionD, component: agw, component: cwag, component: feg

#4408 [orc8r] Resolve Warnings from Combining Swagger Specs
  cwf/cloud/go/services/cwf/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/arp_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/gbr_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/qos_class_id_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
Labels: component: agw, component: cwag

#4383 [orc8r] add S8_proxy swagger endpoints
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/cloud/go/services/feg/obsidian/models/defaults.go
  feg/cloud/go/services/feg/obsidian/models/gateway_federation_configs_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/network_federation_configs_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/s8_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  feg/cloud/go/services/feg/servicers/builder_servicer.go
  feg/cloud/go/services/feg/servicers/builder_servicer_test.go
  feg/gateway/mconfig_test/mconfig_test.go
  feg/gateway/services/s8_proxy/client_api_test.go
  feg/gateway/services/s8_proxy/servicers/config.go
  feg/gateway/services/s8_proxy/servicers/config_test.go
  feg/gateway/services/s8_proxy/test_init/test_service_init.go
  feg/gateway/services/swx_proxy/servicers/conf_test.go
  feg/protos/mconfig/mconfigs.proto
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
Labels: component: agw, component: cwag, component: feg

#4413 [teravm] add a check for state of ng40
  ci-scripts/teravm/fabfile.py
Labels: component: agw, component: cwag

#4384 [orc8r] Remove MemoryBlobStorage
  cwf/gateway/integ_tests/hssless_test.go
  cwf/gateway/services/uesim/servicers/eap_aka_test.go
  cwf/gateway/services/uesim/servicers/eap_test.go
  cwf/gateway/services/uesim/servicers/radius_test.go
  cwf/gateway/services/uesim/servicers/start_auth_test.go
  cwf/gateway/services/uesim/servicers/uesim_test.go
  cwf/gateway/services/uesim/test_init/test_service_init.go
  cwf/gateway/services/uesim/uesim/main.go
  feg/cloud/go/services/health/client_api_test.go
  feg/cloud/go/services/health/test_init/test_service_init.go
  orc8r/cloud/go/service/middleware/unary/test_utils/util.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/device/test_init/test_service_init.go
  orc8r/cloud/go/services/tenants/servicers/servicer_test.go
  orc8r/cloud/go/test_utils/test_db.go
Labels: component: agw, component: cwag

#4435 Update the build artifacts for 1.4
  .circleci/config.yml
  README.md
  lte/gateway/deploy/agw_install.sh
Labels: component: agw, component: cwag

#4436 Bump the magma build on master to 1.5.0
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag

#4439 [SessionD] Add GRPC logging for LocalCreateSessionResponse
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
Labels: component: agw, component: cwag

#4340 [lte][agw]Magma Installation Pre and Post checks
  lte/gateway/deploy/agw_post_install.sh
  lte/gateway/deploy/agw_pre_check.sh
Labels: component: agw, component: cwag

#4440 [lte][agw] Using set instead of incrementing for gtp stats UL/DL bytes metrics
  lte/gateway/python/magma/pipelined/gtp_stats_collector.py
  lte/gateway/python/magma/pipelined/metrics.py
Labels: apply-v1.4, component: agw, component: cwag

#4442 [go] bypass initflag in case of test with debugger
  orc8r/lib/go/initflag/initflag.go
Labels: component: agw, component: cwag

#4446 [CI][LTE] raise libvirt disk from 10G to 40G
  orc8r/tools/packer/magma-dev-libvirt.json
  orc8r/tools/packer/magma-test-libvirt.json
  orc8r/tools/packer/magma-trfserver-libvirt.json
Labels: component: agw, component: cwag

#4450 [feg/lte/xwf] upgrade dockers to focal with py3.8
  cwf/gateway/configs/gateway.mconfig
  cwf/gateway/deploy/roles/ovs/files/0004-ovsdb-idlc.in-dict-changes.patch
  cwf/gateway/docker/docker-compose.yml
  cwf/gateway/docker/python/Dockerfile
  feg/gateway/docker/docker-compose.override.yml
  feg/gateway/docker/docker-compose.yml
  feg/gateway/docker/python/Dockerfile
  orc8r/gateway/docker/Dockerfile
  orc8r/gateway/docker/docker-compose.yml
  orc8r/gateway/python/setup.py
Labels: component: agw, component: cwag

#4360 [feg] s8 modify CreateSession protos
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/gateway/services/s8_proxy/client_api_test.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/tools/s8_cli/main.go
  feg/protos/s8_proxy.proto
Labels: component: agw, component: cwag

#4445 [AGW][Stateless] Sessiond state cleanup
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: apply-v1.4, component: agw, component: cwag

#4437 [orc8r] Remove MemoryBlobStorage Files
  orc8r/cloud/go/blobstore/memory.go
  orc8r/cloud/go/blobstore/memory_test.go
Labels: component: agw, component: cwag

#4468 [feg][NH] S8 NH proxy router initial implementation
  feg/cloud/go/services/feg_relay/feg_relay/main.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
Labels: component: agw, component: cwag

#4454 Modified s1ap sanity test suite
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, component: cwag

#4476 [feg/xwf/cwf] update dockers to support focal with py3.8
  cwf/gateway/docker/python/Dockerfile
  orc8r/gateway/docker/Dockerfile
  xwf/docker/docker-compose.yml
  xwf/gateway/docker/docker-compose.yml
Labels: component: agw, component: cwag

#4480 [cwf/feg/xwf] upgrade to focal with py3.8
  cwf/gateway/docker/python/Dockerfile
  feg/gateway/docker/python/Dockerfile
  orc8r/gateway/docker/Dockerfile
Labels: component: agw, component: cwag

#4451 [CI][LTE] fix lte tests
  lte/gateway/Vagrantfile
Labels: component: agw, component: cwag

#3727 [FeG][PolicyDB][SessionD] Migrate come context to CommonContext in CreditUpdate and TerminateRequest
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/session_proxy_relay.go
  feg/gateway/services/session_proxy/credit_control/gy/model_conversion.go
  feg/gateway/services/session_proxy/servicers/credits.go
  feg/gateway/services/session_proxy/servicers/policy.go
  feg/gateway/services/session_proxy/servicers/session_controller.go
  feg/gateway/services/session_proxy/servicers/session_controller_test.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/RestartHandler.cpp
  lte/gateway/c/session_manager/SessionReporter.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/python/magma/policydb/servicers/session_servicer.py
  lte/gateway/python/magma/policydb/tests/test_session_servicer.py
  lte/protos/session_manager.proto
Labels: component: agw, component: cwag, component: feg

#4424 [NMS] Refresh equipment and subscriber detail
  nms/app/packages/magmalte/app/components/context/RefreshContext.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/EnodebDetailSummaryStatus.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailEnodebs.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailStatus.js
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailSubscribers.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberDetail.js
  nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js
Labels: component: agw, component: cwag

#4425 Fixed the issues found during execution of sanity test suite in stateless mode
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_recv.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_sap.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: apply-v1.4, component: agw, component: cwag

#4479 Modified test case such that TC would wait for Attach Reject and receive UE context release request
  lte/gateway/python/integ_tests/s1aptests/test_attach_act_dflt_ber_ctxt_rej.py
Labels: component: agw, component: cwag

#4491 [feg][nh] Enable NH feg_hello mesh service
  feg/cloud/helm/feg-orc8r/templates/feg_hello.service.yaml
Labels: component: agw, component: cwag

#4472 [feg] add missing ports for s8_proxy
  feg/cloud/configs/service_registry.yml
  feg/gateway/configs/service_registry.yml
  feg/gateway/registry/local_registry.go
Labels: component: agw, component: cwag

#4359 [orc8r][docs] Update orc8r docs for version 1.4
  docs/docusaurus/sidebars.json
  docs/readmes/orc8r/deploy_build.md
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/upgrade_1_4.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/README.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/tools/helm/package.sh
Labels: apply-v1.4, component: agw, component: cwag

#4490 [feg] add Helm template for s8_proxy on feg relay
  feg/cloud/helm/feg-orc8r/Chart.yaml
  feg/cloud/helm/feg-orc8r/templates/s8_proxy.service.yml
  feg/cloud/helm/feg-orc8r/values.yaml
  feg/gateway/gtp/gtp_client.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/gateway/tools/s8_cli/main.go
Labels: component: agw, component: cwag, component: feg

#4509 [AGW][Package] Update dnsmasq version due to security vulnerability in 2.83
  lte/gateway/release/build-magma.sh
Labels: apply-v1.4, component: agw, component: cwag

#4503 [Orc8r] Fix the subscriber policy setting bug
  lte/cloud/go/services/policydb/obsidian/models/conversion.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/obsidian/models/conversion.go
  lte/cloud/go/services/subscriberdb/obsidian/models/mutable_subscriber_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/subscriber_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
Labels: component: agw, component: cwag

#4338 AGW: mobilityD: set default GW for DHCP ip allocation.
  lte/gateway/python/magma/mobilityd/main.py
Labels: apply-v1.4, component: agw, component: cwag

#4514 [orc8r][grpc msg size] Increase max msg size for orchestrator and fbinternal services
  fbinternal/cloud/go/services/fbinternal/fbinternal/main.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
Labels: apply-v1.3, apply-v1.4, component: agw, component: cwag

#4488 [docs] Add user guide to manage alerts in NMS
  docs/docusaurus/sidebars.json
  docs/readmes/assets/nms/userguide/alerts/advanced_alert.png
  docs/readmes/assets/nms/userguide/alerts/alert_recv1.png
  docs/readmes/assets/nms/userguide/alerts/alert_recv2.png
  docs/readmes/assets/nms/userguide/alerts/alert_recv3.png
  docs/readmes/assets/nms/userguide/alerts/alert_recv4.png
  docs/readmes/assets/nms/userguide/alerts/alert_recv5.png
  docs/readmes/assets/nms/userguide/alerts/alert_recv6.png
  docs/readmes/assets/nms/userguide/alerts/alerts1.png
  docs/readmes/assets/nms/userguide/alerts/alerts2.png
  docs/readmes/assets/nms/userguide/alerts/alerts3.png
  docs/readmes/assets/nms/userguide/alerts/alerts4.png
  docs/readmes/assets/nms/userguide/alerts/alerts5.png
  docs/readmes/assets/nms/userguide/alerts/alerts6.png
  docs/readmes/assets/nms/userguide/alerts/simple_alert.png
  docs/readmes/assets/nms/userguide/alerts/viewing_alerts1.png
  docs/readmes/assets/nms/userguide/alerts/viewing_alerts2.png
  docs/readmes/assets/nms/userguide/alerts/viewing_alerts3.png
  docs/readmes/assets/nms/userguide/app_sidebar.png
  docs/readmes/nms/alert.md
  docs/readmes/nms/dashboard.md
  docs/readmes/nms/developer.md
  docs/readmes/nms/equipment.md
  docs/readmes/nms/grafana.md
  docs/readmes/nms/json_editing.md
  docs/readmes/nms/network.md
  docs/readmes/nms/overview.md
  docs/readmes/nms/setup.md
  docs/readmes/nms/subscriber.md
  docs/readmes/nms/tips.md
  docs/readmes/nms/traffic.md
Labels: apply-v1.4, component: agw, component: cwag

#4526 [sessiond] add session id to UpdateTunnelIds call
  lte/cloud/go/protos/session_manager.pb.go
  lte/protos/session_manager.proto
Labels: component: agw, component: cwag

#4527 [sessiond] temporal fix for searches with bearerid
  lte/gateway/c/session_manager/SessionStore.cpp
Labels: component: agw, component: cwag

#4511 AGW: mobilityD: Do not allocate IP in case of static IP allocation error
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  lte/gateway/python/magma/mobilityd/subscriberdb_client.py
  lte/gateway/python/magma/mobilityd/tests/test_multi_apn_ip_alloc.py
  lte/gateway/python/magma/mobilityd/tests/test_static_ip_alloc.py
Labels: apply-v1.4, component: agw, component: cwag

#4521 Add envoy controller to magmad.yml
  lte/gateway/configs/magmad.yml
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_envoy_controller.service
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: apply-v1.4, component: agw, component: cwag

#4553 [AGW] Set store to false for AsyncSniffer
  lte/gateway/python/magma/mobilityd/dhcp_client.py
  lte/gateway/python/magma/mobilityd/tests/test_dhcp_client.py
Labels: apply-v1.3, apply-v1.4, component: agw, component: cwag

#4368 [lte][agw] Adding mtr_interface config value to pipelined.yml_prod
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, component: cwag

#4569 AGW: mobilityD: disable static IP for dev tests
  lte/gateway/configs/gateway.mconfig
  lte/gateway/python/magma/mobilityd/subscriberdb_client.py
Labels: component: agw, component: cwag

#4524 AGW: remove deprecated field from mconfig.
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/protos/mconfig/mconfigs.proto
Labels: component: agw, component: cwag

#4486 [orc8r] Refactor Blobstore.Listkeys() to use Search()
  orc8r/cloud/go/blobstore/ent.go
  orc8r/cloud/go/blobstore/ent_test.go
  orc8r/cloud/go/blobstore/integration_test.go
  orc8r/cloud/go/blobstore/mocks/TransactionalBlobStorage.go
  orc8r/cloud/go/blobstore/sql.go
  orc8r/cloud/go/blobstore/sql_test.go
  orc8r/cloud/go/blobstore/storage.go
  orc8r/cloud/go/services/accessd/storage/storage_blobstore.go
  orc8r/cloud/go/services/accessd/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore_test.go
  orc8r/cloud/go/services/tenants/servicers/storage/storage.go
  orc8r/cloud/go/services/tenants/servicers/storage/storage_test.go
Labels: component: agw, component: cwag

#4577 [lte][agw] Adding mtr_ip to service config only if mtr_interface is present
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, component: cwag

#4581 [ctraced] Add obsidian labels for ctraced REST endpoints
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/values.yaml
Labels: component: agw, component: cwag

#4478 [orc8r][docs] Replace CNTLR_POD with ORC_POD
  docs/readmes/orc8r/deploy_install.md
  orc8r/cloud/deploy/bare-metal/deploy_charts.sh
Labels: apply-v1.4, component: agw, component: cwag

#4567 [EventD] Load all swagger/bravado specs on startup
  orc8r/gateway/python/magma/eventd/event_validator.py
Labels: apply-v1.3, apply-v1.4, component: agw, component: cwag

#4342 CI: initial commit for new pipeline (Container and DsTester)
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  ci-scripts/generateHtmlReport-OAI-pipeline.py
Labels: component: agw, component: ci, component: cwag, type: enhancement

#4510 AGW: GTP: add support to handle extension headers
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/Makefile
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/gtp.c
Labels: component: agw, component: cwag

#4565 Add missing fluentd configuration to docs
  docs/readmes/lte/config_agw.md
Labels: apply-v1.3, apply-v1.4, component: agw, component: cwag, component: docs

#4583 Fix Envoy error handling
  lte/gateway/python/magma/pipelined/app/he.py
Labels: apply-v1.4, component: agw, component: cwag

#4587 Update pipelined rpc req with tunnel
  lte/cloud/go/protos/pipelined.pb.go
  lte/protos/pipelined.proto
Labels: component: agw, component: cwag

#4584 [feg] s8 create session response and delete session implementation
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
  feg/gateway/gtp/gtp_client.go
  feg/gateway/services/s8_proxy/client_api.go
  feg/gateway/services/s8_proxy/client_api_test.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/ds.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mb.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/gateway/services/s8_proxy/test_init/test_service_init.go
  feg/gateway/tools/s8_cli/main.go
  feg/protos/s8_proxy.proto
Labels: component: agw, component: cwag, component: feg

#4586 Update Envoy Config Swagger defs
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/gateway_he_config_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/lte/obsidian/models/validate.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  orc8r/cloud/docker/controller/apidocs/v1/swagger.yml
Labels: component: agw, component: cwag

#4467 [dev] Add shared copyright for IntelliJ users
  .idea.shared/copyright/magma.xml
  .idea.shared/copyright/profiles_settings.xml
Labels: component: agw, component: cwag

#4589 [Backport][V1.3] [MME] fix incorrect formatting of time/timezone in EMM-information pa…
  lte/gateway/c/oai/include/state_converter.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_send.c
  lte/gateway/docker/mme/Dockerfile
Labels: component: agw, component: cwag
