Repository magma/magma, pull requests merged in 2021-08, with the labels that each got.

#8414 fix(agw): Fixed memory leaks on branch v1.6
  lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c
Labels: component: agw, component: cwag, size/M

#8356 docs(orc8r): Document Magma modules pattern
  docs/readmes/assets/orc8r/magma_modules.png
  docs/readmes/orc8r/architecture_modularity.md
Labels: size/XS

#8419 docs: Add parameter docs for cwf/gateway/fabfile
  cwf/gateway/fabfile.py
Labels: component: cwag, size/S

#8018 feat(nms): Gateway Detail Page Displaying Managed Subscribers
  nms/app/packages/magmalte/app/components/FEGServicingAccessGatewayKPIs.js
  nms/app/packages/magmalte/app/components/context/FEGSubscriberContext.js
  nms/app/packages/magmalte/app/components/context/RefreshContext.js
  nms/app/packages/magmalte/app/components/feg/FEGContext.js
  nms/app/packages/magmalte/app/state/feg/SubscriberState.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailSubscribers.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/FEGGatewayDetailSubscribersTest.js
Labels: size/XL

#8129 feat(nms): Gateway Config Page
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/FEGGatewayDetailConfigTest.js
Labels: size/L

#8421 refactor: add caching to expensive functions in ByteCount front-end
  lte/gateway/python/magma/kernsnoopd/handlers.py
  lte/gateway/python/magma/kernsnoopd/tests/byte_counter_tests.py
Labels: component: agw, size/M

#8415 feat(pipelined): enable NAT traffic for eNB traffic in Non-NAT setup
  lte/gateway/python/magma/pipelined/datapath_setup.py
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, component: cwag, size/M

#8423 docs: add evaluation results from `net_dev_start_xmit` instrumentation
  docs/readmes/proposals/p018_control_network_metrics.md
Labels: size/M

#8422 feat: add IPv6 support to byte_count.bpf.c
  lte/gateway/python/magma/kernsnoopd/ebpf/byte_count.bpf.c
  lte/gateway/python/magma/kernsnoopd/ebpf/common.bpf.h
  lte/gateway/python/magma/kernsnoopd/handlers.py
  lte/gateway/python/magma/kernsnoopd/tests/byte_counter_tests.py
Labels: component: agw, size/M

#8433 chore(orc8r): Add build failure msg for missing $PWD env var
  orc8r/cloud/docker/build.py
Labels: size/S

#8429 chore(orc8r): Add note that monolithic swagger is generated
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/tools/combine_swagger/combine/combine.go
  orc8r/cloud/go/tools/combine_swagger/testdata/monolithic.yml.golden
Labels: size/S

#8310 fix: Avoid using retry module
  .github/workflows/cwag-workflow.yml
Labels: size/M

#8443 chore: Add deps as a valid PR title scope
  .github/workflows/semantic-pr.yml
Labels: size/XS

#7741 fix(pipelined): add recovery for ovs restarts
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/protos/session_manager.proto
Labels: component: agw, size/XXL

#8340 fix(ci): Replace regex to get commit title in github actions job
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/publish-helmcharts-to-artifactory.yml
Labels: size/L

#8432 docs: Clarify underspecified path to proposal acceptance
  docs/readmes/contributing/contribute_proposals.md
Labels: size/S

#8420 refactor(nms): Changed subscriber detail KPIs to display data usage as MB/s and changed histogram to line chart
  nms/app/packages/magmalte/app/views/subscriber/SubscriberChart.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberUtils.js
  nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberChartTest.js
Labels: size/L

#8451 fix(pipelined): Fix ovs pid redis error for unit tests
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/start_pipelined.py
Labels: component: agw, size/M

#8125 feat(nms): Gateway Detail Page Displaying Connection Status and Cluster Status
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/GatewayUtils.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayConnectionStatus.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailMain.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/FEGGatewayConnectionStatusTest.js
Labels: size/L

#8131 feat(nms): Gateway Config Page Editing Federation Gateway
  nms/app/packages/magmalte/app/components/feg/FEGGatewayDialog.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailConfig.js
  nms/app/packages/magmalte/app/views/equipment/FEGGatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/FEGGatewayDetailConfigTest.js
Labels: size/L

#8455 fix(mme): assert on single thread exits
  lte/gateway/c/core/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/s11/s11_tasks.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
  lte/gateway/c/core/oai/tasks/sgs/sgs_task.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c
  lte/gateway/c/core/oai/tasks/sms_orc8r/sms_orc8r_task.c
  lte/gateway/c/core/oai/tasks/udp/udp_primitives_server.c
Labels: apply-v1.5, apply-v1.6, component: agw, size/M

#8461 fix(mme): Backport PR 7985 for s1 handover fixes
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw, component: cwag, size/M

#8462 fix(mme): Backport PR 8046 for additional S1 handover fixes
  lte/gateway/c/core/oai/include/s1ap_types.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw, component: cwag, size/M

#8468 fix(mme): Backport PR 8455
  lte/gateway/c/core/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/s11/s11_tasks.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/core/oai/tasks/service303/service303_task.c
  lte/gateway/c/core/oai/tasks/sgs/sgs_task.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c
  lte/gateway/c/core/oai/tasks/sms_orc8r/sms_orc8r_task.c
  lte/gateway/c/core/oai/tasks/udp/udp_primitives_server.c
Labels: component: agw, component: cwag, size/M

#8447 fix(s8_proxy): fix tft components and add sequence number to create b…
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cb.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/tft_proto_conversion.go
Labels: size/L

#8477 fix(agw): remove auto interface bring-up.
  lte/gateway/deploy/roles/magma/files/magma_ifaces_gtp
Labels: apply-v1.5, apply-v1.6, component: agw, size/XS

#8454 fix: add `_total` suffix to metric names
  nms/app/packages/magmalte/data/LteMetrics.json
Labels: size/XS

#8472 fix(mme): Backport s1 handover fixes by PRs 7985 and 8046
  lte/gateway/c/oai/include/s1ap_types.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw, component: cwag, size/L

#8146 fix(agw): restore SGi bridge flows to keep connectivity.
  lte/gateway/deploy/roles/magma/files/magma-bridge-reset.sh
  lte/gateway/deploy/roles/magma/files/ovs-kmod-upgrade.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/tests/snapshots/ovs-restart-test1.txt
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeTestFlowRestore.test_flow_snapshot_match.snapshot
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
  lte/gateway/python/scripts/config_stateless_agw.py
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/L

#8480 fix(mme): assert on single thread exits (#8455)
  lte/gateway/c/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/oai/tasks/s11/s11_tasks.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/oai/tasks/sctp/sctp_primitives_server.c
  lte/gateway/c/oai/tasks/service303/service303_task.c
  lte/gateway/c/oai/tasks/sgs/sgs_task.c
  lte/gateway/c/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_task.c
  lte/gateway/c/oai/tasks/sms_orc8r/sms_orc8r_task.c
  lte/gateway/c/oai/tasks/udp/udp_primitives_server.c
Labels: component: agw, component: cwag, size/M

#8328 fix(agw): enable GTP echo
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/configs/spgw.yml
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/S

#2783 feat(pipelined): [5G: MVC][component: agw][type: enhancement][pipelined] Support Enforcement functionality for 5G
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/set_interface_client.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_ipv6_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_two_policies.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_5g.EnforcementTableTest.test_enforcemnet_rule_multiple_sessions.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_5g.EnforcementTableTest.test_enforcemnet_rules.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_cookie_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_deny_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.nuke_ue.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.EnforcementTableHeTest.test_subscriber_policy_with_he.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_pull_stats.PullStatsTest.test_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_5g.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
Labels: component: agw, component: cwag, product: 5g mvc, product: 5g sa, size/XXL, type: enhancement

#8417 fix(mme): Fixed memory leaks observed during network initiated dedicated bearer deactivation procedure
  lte/gateway/c/core/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/core/oai/tasks/nas/esm/esm_ebr.c
Labels: component: agw, size/M

#8452 fix: handle int128 as couple of int64 and make hashable
  lte/gateway/python/magma/kernsnoopd/handlers.py
  lte/gateway/python/magma/kernsnoopd/metrics.py
  lte/gateway/python/magma/kernsnoopd/tests/byte_counter_tests.py
Labels: component: agw, ready2merge, size/M

#8481 fix(mme): Free bstring field for ICS response
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/test/itti/test_itti.cpp
Labels: component: agw, size/L

#8496 fix(mme): Fixed mme crash occurring while updating stats
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
Labels: component: agw, size/XS

#7401 refactor: Add agw GitHub Actions Workflow
  .github/workflows/agw-workflow.yml
  .github/workflows/unit-test-workflow.yml
Labels: size/L, devops-migration

#8512 docs: Fix Python version
  docs/readmes/basics/prerequisites.md
Labels: size/XS

#8511 fix(mme): Fixed memory leaks observed during network initiated dedica…
  lte/gateway/c/oai/tasks/nas/esm/DedicatedEpsBearerContextActivation.c
  lte/gateway/c/oai/tasks/nas/esm/EpsBearerContextDeactivation.c
  lte/gateway/c/oai/tasks/nas/esm/esm_ebr.c
Labels: component: agw, component: cwag, size/M

#8515 fix(agw): Revert "feat(pipelined): [5G: MVC][component: agw][type: enhancement][pipelined] Support Enforcement functionality for 5G"
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/set_interface_client.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_ipv6_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_two_policies.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_5g.EnforcementTableTest.test_enforcemnet_rule_multiple_sessions.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_5g.EnforcementTableTest.test_enforcemnet_rules.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_cookie_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_deny_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.nuke_ue.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.EnforcementTableHeTest.test_subscriber_policy_with_he.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_pull_stats.PullStatsTest.test_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_5g.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
Labels: component: agw, size/XXL

#8495 fix(mme): Closing latest OF connection on OpenFlowController
  lte/gateway/c/core/oai/lib/openflow/controller/OpenflowController.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/OpenflowController.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/test/openflow/test_openflow_controller.cpp
Labels: component: agw, size/M

#8278 feat(orc8r): Generic SyncStore interface for propagating digest pattern
  orc8r/cloud/go/syncstore/cache.go
  orc8r/cloud/go/syncstore/config.go
  orc8r/cloud/go/syncstore/store.go
  orc8r/cloud/go/syncstore/store_reader.go
  orc8r/cloud/go/syncstore/store_test.go
  orc8r/cloud/go/syncstore/store_writer.go
  orc8r/lib/go/protos/digest.pb.go
  orc8r/protos/digest.proto
Labels: component: orc8r, size/XXL

#8519 fix(mme): Closing latest OF connection on OpenFlowController
  lte/gateway/c/oai/lib/openflow/controller/OpenflowController.cpp
  lte/gateway/c/oai/lib/openflow/controller/OpenflowController.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/oai/test/openflow/test_openflow_controller.cpp
Labels: component: agw, component: cwag, size/M

#8517 fix(mme): Free bstring field for ICS response
  lte/gateway/c/oai/common/itti_free_defined_msg.c
Labels: component: agw, component: cwag, size/S

#8528 fix: Remove timeout from new agw gha pipeline
  .github/workflows/agw-workflow.yml
Labels: size/XS

#8527 docs: fix build and install doc to use test build flag not dev
  docs/docusaurus/versioned_docs/version-1.5.0/lte/build_install_magma_pkg_in_agw.md
  docs/readmes/lte/build_install_magma_pkg_in_agw.md
Labels: size/M

#8521 build(mme): adding missing patch to MME dockerfiles
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, size/XS

#8529 chore: add a new 'release' tag to packaging fab command
  circleci/fabfile.py
  docs/readmes/howtos/package.md
  docs/readmes/lte/build_install_magma_pkg_in_agw.md
  lte/gateway/fabfile.py
Labels: component: agw, size/S

#8523 feat(pipelined): Enforcement functionality for 5G changes back.
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/set_interface_client.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_ipv6_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_two_policies.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_5g.EnforcementTableTest.test_enforcemnet_rule_multiple_sessions.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_5g.EnforcementTableTest.test_enforcemnet_rules.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_cookie_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_deny_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_ipv6_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.nuke_ue.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_deactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_install.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_rule_reactivation.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement_stats.EnforcementStatsTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.EnforcementTableHeTest.test_subscriber_policy_with_he.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_pull_stats.PullStatsTest.test_poll.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_stats_restart.initial_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement_5g.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
Labels: component: agw, size/XXL

#8561 Revert "feat(pipelined): Use future for poll stats retrieval (#8205)"
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/tests/test_pull_stats.py
Labels: component: agw, size/M

#8197 docs: Design proposal for enodeb -> Domain proxy communication
  docs/readmes/proposals/p019_enodeb_cbrs_support.md
Labels: type: proposal, size/L

#8530 fix(pipelined): Fix Verbose ofctl logging
  lte/gateway/deploy/roles/magma/files/patches/0001-Set-unknown-dpid-ofctl-log-to-debug.patch
  orc8r/gateway/python/python.mk
Labels: component: agw, size/M

#8562 fix(s8_proxy): add cause to bearer context on Create Bearer Response
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/gateway/go.mod
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/protos/s8_proxy.proto
Labels: size/L

#8524 chore: remove unused function from SessionD
  lte/gateway/c/session_manager/SessionState.cpp
Labels: component: agw, component: cwag, size/S

#8564 fix(session_proxy): add service identifier to terminate request to
  feg/gateway/services/session_proxy/credit_control/gy/model_conversion.go
Labels: size/XS, backported-v1.5, backported-v1.6

#8513 refactor(nms): Hooked feg gateway context provider to existing gateway page
  nms/app/packages/magmalte/app/components/feg/FEGGateways.js
  nms/app/packages/magmalte/app/components/feg/__tests__/FEGGatewaysTest.js
Labels: size/L

#8280 feat(orc8r): Show deployed version through API and NMS
  nms/app/packages/fbcnms-magma-api/__generated__/MagmaAPIBindings.js
  nms/app/packages/magmalte/app/components/TopBar.js
  nms/app/packages/magmalte/app/components/context/VersionContext.js
  nms/app/packages/magmalte/app/components/main/Index.js
  nms/app/packages/magmalte/docker-compose-e2e.yml
  nms/app/packages/magmalte/docker-compose.yml
  nms/app/packages/magmalte/server/apicontroller/routes.js
  nms/app/packages/magmalte/server/main/routes.js
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/about_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/orchestrator/obsidian/models/version_info_swaggergen.go
  orc8r/cloud/helm/orc8r/values.yaml
Labels: size/L

#8256 style: Apply formatting scripts to PipelineD
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/ipfix.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/bridge_util.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/policy_converters.py
  lte/gateway/python/magma/pipelined/redirect.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/app/table_isolation.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_5g.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
  lte/gateway/python/magma/pipelined/tests/test_service_manager.py
Labels: component: agw, component: cwag, size/XL

#8578 chore: remove PipelineD from being excluded in the formatting check
  .github/workflows/python-formatting-check.yml
Labels: size/XS

#8582 fix(s6a_proxy): remove origin-state-id avp
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy.go
  feg/gateway/services/s6a_proxy/servicers/util.go
Labels: size/XS, apply-v1.5, apply-v1.6

#8586 fix(orc8r): Fix Orc8r bug causing subscriber sync to fail
  lte/cloud/go/services/nprobe/storage/storage_blobstore.go
  lte/cloud/go/services/subscriberdb/storage/last_resync.go
  lte/cloud/go/services/subscriberdb/storage/per_sub_digest.go
  orc8r/cloud/go/services/accessd/storage/storage_blobstore.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore.go
  orc8r/cloud/go/services/ctraced/storage/storage_blobstore.go
  orc8r/cloud/go/services/directoryd/storage/storage_blobstore.go
  orc8r/cloud/go/syncstore/store_writer.go
Labels: component: agw, size/S

#8585 docs: update Python formatting check to be required
  docs/readmes/contributing/contribute_ci_checks.md
Labels: size/XS

#8514 refactor: migrate subscriberdb to generic digests pattern
  lte/cloud/configs/subscriberdb_cache.yml
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/subscriberdb/config.go
  lte/cloud/go/services/subscriberdb/const.go
  lte/cloud/go/services/subscriberdb/digest.go
  lte/cloud/go/services/subscriberdb/digest_test.go
  lte/cloud/go/services/subscriberdb/load.go
  lte/cloud/go/services/subscriberdb/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/protos/subscriberdb.proto
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/storage/digest.go
  lte/cloud/go/services/subscriberdb/storage/digest_test.go
  lte/cloud/go/services/subscriberdb/storage/last_resync.go
  lte/cloud/go/services/subscriberdb/storage/last_resync_test.go
  lte/cloud/go/services/subscriberdb/storage/per_sub_digest.go
  lte/cloud/go/services/subscriberdb/storage/per_sub_digest_test.go
  lte/cloud/go/services/subscriberdb/storage/subscribers.go
  lte/cloud/go/services/subscriberdb/storage/subscribers_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/config.go
  lte/cloud/go/services/subscriberdb_cache/subscriberdb_cache/main.go
  lte/cloud/go/services/subscriberdb_cache/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb_cache/worker.go
  lte/cloud/go/services/subscriberdb_cache/worker_test.go
  lte/gateway/c/core/oai/lib/mobility_client/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/li_agent/src/CMakeLists.txt
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/store/onready.py
  lte/gateway/python/magma/subscriberdb/store/sqlite.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
  lte/gateway/python/magma/subscriberdb/tests/store/onready_test.py
  lte/gateway/python/magma/subscriberdb/tests/store/store_tests.py
  lte/protos/subscriberdb.proto
  orc8r/cloud/go/blobstore/ent.go
  orc8r/cloud/go/blobstore/sql.go
  orc8r/cloud/go/orc8r/math/math.go
  orc8r/cloud/go/syncstore/digest.go
  orc8r/cloud/go/syncstore/digest_test.go
  orc8r/cloud/go/syncstore/store.go
  orc8r/cloud/go/syncstore/store_reader.go
  orc8r/cloud/go/syncstore/store_test.go
  orc8r/cloud/go/syncstore/store_writer.go
  orc8r/lib/go/protos/digest.pb.go
  orc8r/lib/go/service/config/service_config.go
  orc8r/protos/digest.proto
Labels: component: agw, size/XXL

#7914 fix(sessiond): save new session state in redis while waiting for a response from PolicyDB/FeG
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
  lte/gateway/c/session_manager/LocalSessionManagerHandler.cpp
  lte/gateway/c/session_manager/LocalSessionManagerHandler.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_local_enforcer_wallet_exhaust.cpp
  lte/gateway/c/session_manager/test/test_polling_pipelined.cpp
  lte/gateway/c/session_manager/test/test_proxy_responder_handler.cpp
  lte/gateway/c/session_manager/test/test_session_manager_handler.cpp
  lte/gateway/c/session_manager/test/test_session_store.cpp
  lte/gateway/c/session_manager/test/test_store_client.cpp
Labels: component: agw, component: cwag, size/XL

#8591 fix: stop trying to start kernsnoopd
  lte/gateway/configs/magmad.yml
Labels: component: agw, size/XS

#8580 fix(mme): Modified the proto structure, PacketFilter defined in file, ../protos/oai/spgw_state.proto to take care of multiple occurrences of packet filter contents within each packet filter
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/protos/oai/spgw_state.proto
Labels: component: agw, size/L

#8598 fix(pipelined): patch ryu ofctl verbose log
  lte/gateway/deploy/roles/magma/files/service.py
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/L

#8596 fix(s8_proxy): fix tft filter proto to include repeated field
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cb.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/tft_proto_conversion.go
Labels: size/L

#8602 fix(pipelined): v1.7: Increase stats poll-interval
  lte/gateway/configs/pipelined.yml_prod
Labels: component: agw, size/XS

#8587 docs: fix doc lint on master
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/proposals/p019_enodeb_cbrs_support.md
Labels: size/L

#8594 fix(mme): Frees esmmessagecontainer on attach reject proc
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
Labels: component: agw, size/XS, apply-v1.5, apply-v1.6

#8605 fix(mme): Stop double free of state_cache_p in S1apStateManager
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/test/s1ap_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_test.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_handle_new_association.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_manager.cpp
Labels: component: agw, size/M, ready2merge

#8593 refactor(nms): changed subscriber event table to display events from other streams like mme
  nms/app/packages/magmalte/app/views/events/EventsTable.js
  nms/app/packages/magmalte/app/views/events/__tests__/EventsTableTest.js
Labels: size/L

#8623 fix(feg): Add Gigawords support to builtin radius update RPC payload
  feg/gateway/services/aaa/radius/acct.go
Labels: size/S

#8545 chore: remove unused imports
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_asr.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_he_policy.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_with_multiple_mme_restarts.py
  lte/gateway/python/integ_tests/s1aptests/test_enb_partial_reset_con_dereg.py
  lte/gateway/python/integ_tests/s1aptests/test_multi_enb_partial_reset.py
  lte/gateway/python/integ_tests/s1aptests/test_no_esm_information_rsp_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_standalone_pdn_conn_req.py
  lte/gateway/python/integ_tests/s1aptests/test_standalone_pdn_conn_req_with_apn_correction.py
  lte/gateway/python/integ_tests/s1aptests/test_stateless_multi_ue_mixedstate_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_messages.py
Labels: component: agw, size/S

#8624 feat(agw): back-port-v1.5: enable GTP-U echo response. (#7885)
  lte/gateway/c/oai/include/sgw_config.h
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/oai/tasks/sgw/sgw_config.c
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag, size/M

#8464 fix(mme): PDUSessionResourceSetupRequest failure randomly
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_asDefs.h
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
Labels: component: agw, size/L, product: 5g sa

#8544 fix(mme): log cleanup & alignment amf and ngap tasks
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_msg.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_common.h
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/c/core/oai/tasks/amf/amf_data.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_fsm.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_fsm.h
  lte/gateway/c/core/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_itti_messaging.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_common.h
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
Labels: component: agw, size/XL, product: 5g sa

#8627 docs: Update Link for Semantics
  docs/readmes/contributing/contribute_workflow.md
Labels: size/XS, ready2merge

#8632 chore: Set default build type of magma-build.sh to be RelWithDebInfo
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/XS

#8635 fix(mme): Frees esmmessagecontainer on attach reject proc
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_recv.c
Labels: component: agw, component: cwag, size/XS

#8538 docs: PDFs Update
  docs/pdfs/Magma_Deployment_Guide_Installing_Magma_V2.pdf
  docs/pdfs/Magma_Network_Management_System.pdf
Labels: size/XS, ready2merge

#8649 fix(agw): backport-v1.6: enable GTP echo (#8328)
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/configs/spgw.yml
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: cwag, size/S

#8642 fix: missing variable for or8r template file
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
Labels: size/XS

#8637 feat(agw): Add support for OVS 2.15
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0007-datapath-Fixes-for-4.9-kernel.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0008-ovs-datapath-enable-kernel-5.6.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0009-AGW-OVS-handle-gtp-tunnel-type.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0001-of-match-expand-NXM_NX_TUN_FLAGS-to-include-all-tunn.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0002-userspace-IPFIX-Add-tunnel-type-GTP.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0003-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0004-ovs-Add-support-to-set-GTP-header-fields.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0005-OVS-gtp-echo-handling.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0006-ovs-test-add-gtp-marker-test.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0007-native-tnl-routing-tunnel-lookup-with-pkt-mark.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0008-fixes-for-2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0009-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0010-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0011-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0012-GTP-Extension-header-support-in-ovs2.14.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0013-ODP-action-Fix-L3-port-to-L3-port-traffic.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0014-datapath-GTP-cleanup.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0015-GTP-handle-seq-number-in-HDR.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0016-datapath-gtp-add-segmentation-offloads.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0017-net-Fix-zero-copy-head-len-calculation.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/README.md
  third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh
Labels: size/L

#8428 perf(pipelined): backport-v1.6: Avoid service reatart on bridge reconfigure (#7851)
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, component: cwag, size/S

#8484 feat: Modify feature request form
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/S, ready2merge

#8648 fix(mme): Mitigate timer expiration handler with invalid UE context causes MME app thread exit
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
Labels: component: agw, size/S

#8655 fix(agw): handle DEBUG level setting.
  orc8r/gateway/python/magma/common/service.py
Labels: size/XS, apply-v1.6, apply-v1.7

#8615 chore(magmad): bump psutil to 5.8
  orc8r/gateway/python/setup.py
Labels: size/XS

#8659 fix(session_proxy): add missing code to parse service indicator from …
  feg/gateway/services/session_proxy/credit_control/gx/model_conversion.go
Labels: size/S, apply-v1.6, apply-v1.7

#8641 feat(s8_proxy): add delete bearer request support
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
  feg/cloud/go/services/feg_relay/servicers/s8_bearer_pgw.go
  feg/gateway/services/s8_proxy/servicers/gtp_handlers.go
  feg/gateway/services/s8_proxy/servicers/gw_s8_client_api.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_feg_relay/mock_feg_relay.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cb.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/db.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/protos/s8_proxy.proto
Labels: size/XL

#8210 chore: Complete migration of cwag jobs already present in GHA
  .circleci/config.yml
Labels: size/L

#8671 fix(sessiond): increase default_requested_units to 10Mb
  cwf/gateway/configs/sessiond.yml
  cwf/gateway/integ_tests/sessiond.yml
  lte/gateway/c/session_manager/SessionCredit.cpp
  lte/gateway/configs/sessiond.yml
Labels: component: agw, apply-v1.3, component: cwag, apply-v1.4, size/S, apply-v1.5, apply-v1.6, apply-v1.7

#8674 fix(mme): Incorrect S-NSSAI sST value set,
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_ta.h
Labels: component: agw, size/S

#8672 fix(mme): Solve AttributeError when accessing copy function from RepeatedScalar…
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/XS

#8658 test(amf): 5G SA Unit Tests for service accept message
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_asDefs.h
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
Labels: component: agw, size/M, product: 5g sa

#8483 feat(orc8r): EKS Fargate via Cloudformation
  experimental/cloudstrapper/playbooks/roles/cfn/cfnMagmaEksFargate.json
Labels: size/L

#8682 chore(nms): Trigger cwag Github actions on NMS changes
  .github/workflows/cwag-workflow.yml
Labels: size/XS

#8697 feat(session_proxy): add a flag to disable Service Requested Unit AVP
  feg/gateway/docker/docker-compose.yml
  feg/gateway/services/session_proxy/credit_control/gy/config.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
Labels: size/M, apply-v1.5, apply-v1.6, apply-v1.7

#8704 fix(session_proxy): correct lint issue on gy config.go that breaks CI
  feg/gateway/services/session_proxy/credit_control/gy/config.go
Labels: size/XS

#8707 fix(agw): ryu: ofctl: log level
  lte/gateway/deploy/roles/magma/files/service.py
Labels: component: agw, size/XS

#8583 feat(mme): 5G Traffic test related fixes
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/core/oai/include/n11_messages_types.h
  lte/gateway/c/core/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_pdu_session_configs.h
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
  lte/protos/session_manager.proto
Labels: component: agw, size/XXL, product: 5g sa

#8724 fix(orc8r): Fix sub sync compatibility issue with v1.6
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/protos/subscriberdb.proto
Labels: component: agw, size/L, apply-v1.7

#8720 fix(agw): Fixing pylint tests for open function missing encoding param
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/health/health_service.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/avp_tests.py
  lte/gateway/python/magma/tests/pylint_tests.py
  orc8r/gateway/python/magma/common/health/health_service.py
  orc8r/gateway/python/magma/common/service_registry.py
  orc8r/gateway/python/magma/configuration/mconfig_managers.py
  orc8r/gateway/python/magma/configuration/service_configs.py
  orc8r/gateway/python/magma/magmad/metrics.py
  orc8r/gateway/python/magma/magmad/upgrade/docker_upgrader.py
  orc8r/gateway/python/magma/tests/pylint_tests.py
Labels: component: agw, size/M

#8728 fix(mme): Fix enable_converged_core flag for headless ops
  lte/gateway/configs/mme.yml
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/S, product: 5g sa

#8665 fix(ci): Autolabel pull requests with the component names. Fix for the issue# 8531
  .github/workflows/autolabel-pullrequests.yml
Labels: size/L

#8712 chore(magmad): pretty print gateway.mconfig file
  orc8r/gateway/python/magma/configuration/mconfig_managers.py
Labels: size/XS

#8718 fix: Remove as_dict override for spyne
  lte/gateway/python/magma/enodebd/tr069/models.py
Labels: component: agw, size/S

#8735 chore(mme): Adding service303 log level config
  lte/gateway/c/core/oai/common/log.c
  lte/gateway/c/core/oai/common/log.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/S

#8739 fix(agw): Handle empty ctx descriptor for soap messages
  lte/gateway/python/magma/enodebd/tr069/spyne_mods.py
Labels: component: agw, size/XS

#8743 fix(agw): handle conflicts due to ryu lib patching
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma-postinst
Labels: component: agw, component: ci, size/S

#8740 fix(agw): Rename Reboot state to be generic
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/tr069/models.py
Labels: component: agw, size/S

#8709 feat(agw): Fix for GTPU header sequence num length
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0018-GTP-seq-number-length-correction.patch
Labels: component: agw, size/M, product: 5g sa

#8747 chore(pipelined): update ryu lib
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile.ubuntu
Labels: component: agw, component: ci, size/M

#8588 chore(orc8r): Fix lint warning for unhandled multierror err
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/models/validate.go
  lte/cloud/go/services/subscriberdb_cache/config.go
  lte/cloud/go/services/subscriberdb_cache/worker.go
  orc8r/cloud/go/obsidian/swagger/spec/combine.go
  orc8r/cloud/go/parallel/map.go
  orc8r/cloud/go/syncstore/config.go
  orc8r/cloud/go/syncstore/digest_test.go
  orc8r/cloud/go/syncstore/store_test.go
  orc8r/cloud/go/syncstore/store_writer.go
Labels: component: orc8r, component: agw, size/M

#8754 fix(agw): Fix bootstrap failure due to bad Python open args
  orc8r/gateway/python/magma/common/service_registry.py
Labels: component: orc8r, size/XS

#8760 chore: Fix docs readme phony targets
  docs/Makefile
Labels: component: docs, size/XS

#8850 fix(agw): Handle WaitSetParameterValue correctly
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/tests/enodeb_acs_states_tests.py
Labels: component: agw, size/L

#8715 chore: add E122,E123,E126,E127,E131 to Python formatting script/check
  .github/workflows/python-formatting-check.yml
  lte/gateway/python/load_tests/loadtest_pipelined.py
  lte/gateway/python/precommit.py
  lte/gateway/python/scripts/config_stateless_agw.py
  lte/gateway/python/scripts/cpe_monitoring_cli.py
  lte/gateway/python/scripts/create_oai_certs.py
  lte/gateway/python/scripts/generate_oai_config.py
  lte/gateway/python/scripts/ha_cli.py
  lte/gateway/python/scripts/pipelined_cli.py
  lte/gateway/python/scripts/sms_cli.py
  setup.cfg
Labels: component: agw, component: ci, size/L

#8710 chore: address all dependabot complaints for docusaurus
  docs/docusaurus/yarn.lock
Labels: component: docs, size/XXL

#8809 docs: Document controller-gateway upgrade invariants
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/general/upgrade_intro.md
Labels: component: docs, size/M

#8706 chore(agw): update OVS binaries to 2.15
  lte/gateway/deploy/roles/magma/files/magma_ifaces_gtp
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/S

#8875 chore(policydb): added SubscriberPolicySet to state_cli.py
  lte/gateway/python/scripts/state_cli.py
Labels: component: agw, size/XS

#8855 fix(agw): Flaky test case for partial reset
  lte/gateway/python/integ_tests/s1aptests/test_multi_enb_partial_reset.py
Labels: component: agw, size/XS

#8876 test(orc8r): Feg_relay add GwS6aAsyncService to support new mme async grpc server for Cancel Location
  feg/cloud/go/services/feg_relay/servicers/cancel_location.go
  lte/gateway/configs/service_registry.yml
  orc8r/cloud/go/services/dispatcher/gateway_registry/gw_registry.go
Labels: component: orc8r, component: agw, component: feg, size/XS

#8848 fix(mme): Default Allow all Packet Filters & QOS Rule seems not adding in right QF-id 5 on DL 5G NAS
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
Labels: component: agw, size/S, product: 5g sa

#8794 [CI] Filter what types of pull requests get yamllint (#6306)
  .github/workflows/config/yamllint_config.yml
  .github/workflows/yamlint.yml
Labels: component: agw, component: cwag, size/S, ready2merge

#8640 feat(agw): paginate enodeb northbound api
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/obsidian/models/page_token_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/paginated_enodebs_swaggergen.go
  lte/cloud/go/services/lte/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/models/page_token_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/paginated_subscribers_swaggergen.go
  lte/cloud/go/services/subscriberdb/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/app/components/lte/Enodebs.js
  nms/packages/magmalte/app/state/lte/EquipmentState.js
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/models/page_token_swaggergen.go
  orc8r/cloud/go/models/swagger-common.yml
  orc8r/cloud/go/obsidian/handler.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: agw, component: nms, size/L

#8807 docs(orc8r): Update subscriber sync technical doc with newer terms
  docs/readmes/assets/orc8r/subscriber_digests_architecture.png
  docs/readmes/orc8r/dev_sub_digests.md
Labels: component: docs, size/S

#8860 feat(orc8r): Context propagation in mutating configurator entity functions
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers_test.go
  fbinternal/cloud/go/services/testcontroller/statemachines/enodebd.go
  fbinternal/cloud/go/services/testcontroller/statemachines/enodebd_test.go
  feg/cloud/go/services/basic_acct/tests/setup.go
  feg/cloud/go/services/feg/obsidian/handlers/handlers_test.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/relay_test.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/test_setup.go
  lte/cloud/go/services/ha/servicers/servicer_test.go
  lte/cloud/go/services/lte/analytics/calculations/state_test.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/lte/servicers/indexer_servicer_test.go
  lte/cloud/go/services/lte/servicers/provider_servicer_test.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go
  lte/cloud/go/services/policydb/obsidian/handlers/rating_groups_handlers.go
  lte/cloud/go/services/policydb/servicers/assignments.go
  lte/cloud/go/services/policydb/servicers/assignments_test.go
  lte/cloud/go/services/policydb/streamer/providers_test.go
  lte/cloud/go/services/subscriberdb/digest_test.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/streamer/providers_test.go
  lte/cloud/go/services/subscriberdb_cache/worker_test.go
  orc8r/cloud/go/service/middleware/unary/identity_decorator_test.go
  orc8r/cloud/go/services/configurator/client_api.go
  orc8r/cloud/go/services/configurator/client_api_test.go
  orc8r/cloud/go/services/configurator/test_utils/utils.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/servicers/trace_servicer.go
  orc8r/cloud/go/services/ctraced/servicers/trace_servicer_test.go
  orc8r/cloud/go/services/orchestrator/analytics/calculations/state_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/entity_handler_factory.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handler_factory.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handler_factory_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/upgrade_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/upgrade_handlers_test.go
  orc8r/cloud/go/services/streamer/providers/providers_test.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers.go
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers_test.go
Labels: component: orc8r, component: agw, component: feg, component: cwag, size/XXL, component: cwf

#8862 fix(mme): amf is not accepting if RAN-UE-NGAP-ID is big values
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_types.h
  lte/gateway/c/core/oai/test/ngap/util_ngap_initiate_ue.cpp
Labels: component: agw, size/S, product: 5g sa

#8688 feat(agw): Multiple partial TAI lists creation
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.c
  lte/gateway/c/core/oai/tasks/nas/emm/EmmCommon.h
  lte/gateway/c/core/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_config_partial_tai_list.cpp
  lte/gateway/deploy/roles/magma/files/update_mme_config_for_non_sanity.sh
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_modify_config_for_non_sanity.py
  lte/gateway/python/integ_tests/s1aptests/test_restore_config_after_non_sanity.py
Labels: component: agw, size/XXL

#8908 feat: Add Bazel to Magma VM
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/S

#8489 feat(amf): adding support for registration reject
  lte/gateway/c/core/oai/include/amf_as_message.h
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.h
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GMMCause.h
  lte/gateway/c/core/oai/test/amf/test_amf.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.h
  lte/gateway/c/core/oai/test/amf/util_nas5g_registration_pkt.cpp
Labels: component: agw, size/L, product: 5g sa

#8857 fix(agw): Update WaitEmptyMessageState logic
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/tests/enodeb_acs_states_tests.py
Labels: component: agw, size/M

#8664 feat(agw): Paginate list gateways api.
  nms/packages/magmalte/app/components/network/UpgradeConfig.js
  nms/packages/magmalte/app/components/rhino/MultiMetrics.js
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_handlers_test.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/page_token_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/paginated_gateways_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
Labels: component: orc8r, component: agw, component: nms, size/L, ready2merge
