Repository magma/magma, pull requests merged in 2021-04, with the labels that each got.

#5863 [AGW] Add newline to end of td-agent-bit.conf
  orc8r/gateway/configs/templates/td-agent-bit.conf.template
Labels: size/XS

#5869 [nms] Add mariadb dependency with yarn
  nms/app/packages/magmalte/package.json
  nms/app/yarn.lock
Labels: size/M

#5867 [docs] Add guidelines for force-merge PRs
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_codeowners.md
Labels: size/M

#5851 [CI] Fail gcc-problems checker if builds fail
  .github/workflows/gcc-problems.yml
Labels: size/XS

#4552 [orc8r] Minor CMakeLists.txt cleanups
  orc8r/gateway/c/common/CMakeLists.txt
  orc8r/gateway/c/common/async_grpc/CMakeLists.txt
  orc8r/gateway/c/common/config/CMakeLists.txt
  orc8r/gateway/c/common/datastore/CMakeLists.txt
  orc8r/gateway/c/common/eventd/CMakeLists.txt
  orc8r/gateway/c/common/logging/CMakeLists.txt
  orc8r/gateway/c/common/policydb/CMakeLists.txt
  orc8r/gateway/c/common/protobuf/CMakeLists.txt
  orc8r/gateway/c/common/service303/CMakeLists.txt
  orc8r/gateway/c/common/service_registry/CMakeLists.txt
Labels: component: agw, component: cwag, size/M

#5874 [Pipelined]Report Policy Rule Version to SessionD
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/protos/session_manager.proto
Labels: component: agw

#5000 [AGW] fix agw_install.sh problem due to precheck
  lte/gateway/deploy/agw_install.sh
Labels: component: agw, deployment, size/S

#5882 [DOC]Update doc following agw changes
  docs/readmes/lte/deploy_install.md
Labels: size/S

#5883 [GITIGNORE] Ignore python build directories generated during packaging
  .gitignore
Labels: size/XS

#5880 [MME] Add OVS Flow teid save to register
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.h
Labels: component: agw, size/M

#5877 [MME] Commit uncommitted format changes
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas5g/include/M5GCommonDefs.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GDNN.h
  lte/gateway/c/oai/tasks/nas5g/src/M5GDLNASTransport.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GDNN.cpp
Labels: component: agw, size/S

#5885 [pipelined]Add Tun ID Register
  lte/gateway/python/magma/pipelined/openflow/registers.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.EnforcementTableHeTest.test_subscriber_policy_with_he.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_add.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_add2.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_del.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_del2.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.HeTableTest.test_ue_flows_multi_rule.snapshot
Labels: component: agw, size/L

#5700 [subscriberdb][magmad] add print GRPC to other RPC servicers
  lte/gateway/configs/magmad.yml
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/protocols/s6a_proxy_servicer.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
  orc8r/gateway/python/magma/magmad/main.py
  orc8r/gateway/python/magma/magmad/sync_rpc_client.py
Labels: component: agw, size/M

#5862 [1.5] Update NMS DB Migration script download reference
  docs/readmes/orc8r/upgrade_1_5.md
  nms/app/packages/magmalte/scripts/fuji-upgrade/README.md
  nms/app/packages/magmalte/scripts/fuji-upgrade/pre-upgrade-migration.sh
Labels: size/XS

#5683 [MME][RHEL][OAI] Better work on building for RHEL8
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  lte/gateway/c/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/oai/patches/CMake-warnings-not-errors.patch
  lte/gateway/docker/mme/.dockerignore
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/README.md
Labels: component: agw, size/M

#4515 [Orc8r] 5G WS#2-MVC1 User Guide
  cn/deploy/docs/MVC1_5G_Orc8r_deployment_script_README.docx
  cn/deploy/helm/templates/efkchart.yaml
  cn/deploy/scripts/mvc1_5g_orc8r_deployment_script.py
Labels: component: agw, component: cwag

#5601 [proposal] proposal to add resource tagging
  docs/readmes/proposals/p012_resource-tagging.md
Labels: size/L, v1.6

#4016 Added testcase to validate 3495 timer for both default and dedicated bearer while mme restarts
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_dedicated_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_default_bearer_with_mme_restart.py
Labels: component: agw, component: cwag, size/L

#5886 [lte][agw] Remove hardwired APN APMBR over S1
  lte/gateway/c/oai/tasks/mme_app/mme_app_pdn_context.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_cn.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_send.c
  lte/gateway/c/oai/tasks/nas/esm/sap/esm_send.h
  lte/gateway/c/oai/tasks/nas/ies/ApnAggregateMaximumBitRate.c
  lte/gateway/c/oai/tasks/nas/ies/ApnAggregateMaximumBitRate.h
  lte/gateway/c/oai/tasks/nas/ies/EpsQualityOfService.c
Labels: component: agw, size/L

#5878 [AGW] Modify postinst script to append or replace the COMMIT_HASH env var
  lte/gateway/release/magma-postinst
  lte/gateway/release/magma.lockfile
Labels: component: agw, size/S

#5894 [GITIGNORE] Ignore .venv in git
  .gitignore
Labels: size/XS

#5858 [nms] NMS will use same DB as orc8r for 1.5
  orc8r/cloud/deploy/terraform/orc8r-aws/README.md
  orc8r/cloud/deploy/terraform/orc8r-aws/db.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/outputs.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/README.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/online-upgrade/README.md
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/online-upgrade/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/online-upgrade/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: size/L

#5868 [lte][agw] Add hash-based validation to reduce redis writes operations on MME
  lte/gateway/c/oai/common/redis_utils/redis_client.cpp
  lte/gateway/c/oai/common/redis_utils/redis_client.h
  lte/gateway/c/oai/include/state_manager.h
  lte/gateway/c/oai/tasks/ngap/ngap_state_manager.cpp
  lte/gateway/c/oai/tasks/ngap/ngap_state_manager.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/oai/tasks/s1ap/s1ap_state_manager.h
Labels: component: agw, size/L

#5890 AGW: GTP driver: improve debuggability of datapath.
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/gtp.c
Labels: size/M

#5908 [5G: MVC][component: agw][type: enhancement] changes related to AMF-P…
  lte/gateway/c/oai/tasks/nas5g/CMakeLists.txt
  lte/gateway/c/oai/tasks/nas5g/include/M5GCommonDefs.h
  lte/gateway/c/oai/tasks/nas5g/include/M5GDLNASTransport.h
  lte/gateway/c/oai/tasks/nas5g/include/M5GPDUSessionEstablishmentAccept.h
  lte/gateway/c/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GAuthenticationParameterAUTN.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GAuthenticationParameterRAND.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GDNN.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GPDUAddress.h
  lte/gateway/c/oai/tasks/nas5g/include/ies/M5GPDUSessionIdentity.h
  lte/gateway/c/oai/tasks/nas5g/src/M5GDLNASTransport.cpp
  lte/gateway/c/oai/tasks/nas5g/src/M5GPDUSessionEstablishmentAccept.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GDNN.cpp
  lte/gateway/c/oai/tasks/nas5g/src/ies/M5GPDUAddress.cpp
Labels: component: agw, size/L

#3898 Sessiond module MVC phase converged core changes
  lte/cloud/go/protos/pipelined.pb.go
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/session_manager/AmfServiceClient.cpp
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/PipelinedClient.h
  lte/gateway/c/session_manager/SessionManagerServer.cpp
  lte/gateway/c/session_manager/SessionManagerServer.h
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.h
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.h
  lte/gateway/c/session_manager/StoredState.cpp
  lte/gateway/c/session_manager/StoredState.h
  lte/gateway/c/session_manager/UpfMsgManageHandler.cpp
  lte/gateway/c/session_manager/UpfMsgManageHandler.h
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/c/session_manager/test/SessiondMocks.h
  lte/gateway/configs/sessiond.yml
  lte/protos/pipelined.proto
  lte/protos/policydb.proto
  lte/protos/session_manager.proto
  orc8r/cloud/deploy/bare-metal-ansible/deploy.sh
Labels: component: agw, component: cwag, component: sessiond, product: 5g mvc, size/XXL, type: enhancement

#5895 [IWYU] Non-functional fixup of or8r c includes
  lte/gateway/c/oai/common/redis_utils/redis_client.cpp
  lte/gateway/c/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/session_manager/GrpcMagmaUtils.cpp
  lte/gateway/c/session_manager/GrpcMagmaUtils.h
  lte/gateway/c/session_manager/RedisStoreClient.cpp
  lte/gateway/c/session_manager/RedisStoreClient.h
  lte/gateway/c/session_manager/SpgwServiceClient.cpp
  lte/gateway/c/session_manager/SpgwServiceClient.h
  orc8r/gateway/c/common/async_grpc/GRPCReceiver.cpp
  orc8r/gateway/c/common/async_grpc/GRPCReceiver.h
  orc8r/gateway/c/common/config/MConfigLoader.cpp
  orc8r/gateway/c/common/config/MConfigLoader.h
  orc8r/gateway/c/common/config/ServiceConfigLoader.cpp
  orc8r/gateway/c/common/config/ServiceConfigLoader.h
  orc8r/gateway/c/common/config/YAMLUtils.cpp
  orc8r/gateway/c/common/config/YAMLUtils.h
  orc8r/gateway/c/common/datastore/Serializers.cpp
  orc8r/gateway/c/common/datastore/Serializers.h
  orc8r/gateway/c/common/eventd/EventdClient.cpp
  orc8r/gateway/c/common/eventd/EventdClient.h
  orc8r/gateway/c/common/policydb/PolicyLoader.cpp
  orc8r/gateway/c/common/policydb/PolicyLoader.h
  orc8r/gateway/c/common/service303/MagmaService.cpp
  orc8r/gateway/c/common/service303/MagmaService.h
  orc8r/gateway/c/common/service303/MetricsHelpers.cpp
  orc8r/gateway/c/common/service303/MetricsHelpers.h
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.h
  orc8r/gateway/c/common/service303/ProcFileUtils.cpp
  orc8r/gateway/c/common/service303/ProcFileUtils.h
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.cpp
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.h
Labels: component: agw, size/L

#5911 [CI][AGW]Force setuptools version
  .circleci/config.yml
  orc8r/tools/ansible/roles/python_dev/tasks/main.yml
Labels: size/XS

#5905 [lte][agw] Bug fix in handling ULA message
  lte/gateway/c/oai/tasks/mme_app/mme_app_location.c
Labels: apply-v1.4, component: agw, size/S

#5888 [lte][agw] Eliminate some of the unnecessary state syncs on s1ap
  lte/gateway/c/oai/lib/hashtable/hashtable.h
  lte/gateway/c/oai/lib/hashtable/hashtable_uint64.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.h
Labels: component: agw, size/M

#5889 AGW: OVS: handle L3 port to L3 port packet transfer.
  lte/gateway/release/build-ovs.sh
  third_party/gtp_ovs/kernel-4.9/2.8.10/0001-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0002-userspace-Add-L3-tunnel-type-GTP.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0003-Build-symbols-for-gtp-vport-linux-4.9-module-require.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0004-ovs-datapath-fix-stretch-kernel-update.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0005-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0006-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0007-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0008-odp-act.patch
Labels: component: agw

#5915 [CI][ARTIFACTORY]Revert changes to push to new docker registry
  .circleci/config.yml
Labels: size/M

#5787 [SessionD] Update rule versions on install/uninstalling rules
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.h
  lte/gateway/c/session_manager/Types.h
  lte/gateway/c/session_manager/test/Matchers.h
  lte/gateway/c/session_manager/test/SessionStateTester.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_session_state.cpp
Labels: component: agw, component: cwag, size/XL

#5677 [feg] Add ability to use orc8r with S6a_cli
  feg/gateway/services/s8_proxy/client_api.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/tools/s6a_cli/main.go
  feg/gateway/tools/s8_cli/main.go
Labels: size/M

#5920 [AGW] Commit leftover formatting changes on master
  lte/gateway/c/oai/common/redis_utils/redis_client.cpp
  lte/gateway/c/session_manager/GrpcMagmaUtils.h
  lte/gateway/c/session_manager/RedisStoreClient.cpp
  lte/gateway/c/session_manager/RedisStoreClient.h
  lte/gateway/c/session_manager/SpgwServiceClient.cpp
  lte/gateway/c/session_manager/SpgwServiceClient.h
  orc8r/gateway/c/common/async_grpc/GRPCReceiver.h
  orc8r/gateway/c/common/config/MConfigLoader.cpp
  orc8r/gateway/c/common/config/MConfigLoader.h
  orc8r/gateway/c/common/datastore/Serializers.h
  orc8r/gateway/c/common/eventd/EventdClient.cpp
  orc8r/gateway/c/common/eventd/EventdClient.h
  orc8r/gateway/c/common/policydb/PolicyLoader.h
  orc8r/gateway/c/common/service303/MagmaService.cpp
  orc8r/gateway/c/common/service303/MagmaService.h
  orc8r/gateway/c/common/service303/MetricsSingleton.h
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.cpp
  orc8r/gateway/c/common/service_registry/ServiceRegistrySingleton.h
Labels: component: agw, size/L

#5921 [lte][agw] Bug fix in parsing cause type
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: apply-v1.4, component: agw, size/XS

#4962 [orc8r][NetworkProbe] Support NetworkProbe APIs in swagger
  lte/cloud/configs/nprobe.yml
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/lte/const.go
  lte/cloud/go/serdes/serdes.go
  lte/cloud/go/services/nprobe/doc.go
  lte/cloud/go/services/nprobe/nprobe/main.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/nprobe/obsidian/models/conversion.go
  lte/cloud/go/services/nprobe/obsidian/models/gen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_destination_details_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_destination_id_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_destination_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_task_details_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_task_id_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/network_probe_task_swaggergen.go
  lte/cloud/go/services/nprobe/obsidian/models/serdes.go
  lte/cloud/go/services/nprobe/obsidian/models/swagger.v1.yml
  lte/cloud/go/services/nprobe/obsidian/models/validate.go
  orc8r/cloud/docker/controller/supervisord.conf
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: agw, size/XXL

#5927 [lte][agw] Fix bug on referenced value assignment
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: component: agw, size/XS

#5857 [codeowners] Bare-metal proposal
  CODEOWNERS
Labels: DONOTLAND, size/XS

#5943 [CI]Revert changes to push to new registry
  .circleci/config.yml
Labels: size/M

#5923 [nginx][conf] Fix bootstrapping for on-prem orc8r deployments
  orc8r/cloud/docker/nginx/templates/nginx.conf.j2
Labels: apply-v1.4, size/XS

#5856 [codeowners] Fix script to pull codeowners
  scripts/codeowners.bash
Labels: size/M

#5689 [pipelined]Use Rule Version Provided by SessionD
  feg/gateway/services/aaa/test/pipelined/main.go
  lte/cloud/go/protos/pipelined.pb.go
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/rule_mappers.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/subscriber.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_ipv6_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_enforcement.EnforcementTableTest.test_subscriber_two_policies.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_redirect_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_gy.GYTableTest.test_subscriber_restrict_policy.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_he.EnforcementTableHeTest.test_subscriber_policy_with_he.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_redirect.RedirectTest.test_ipv4_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_redirect.RedirectTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_url_redirect.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_gy.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_redirect.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
  lte/gateway/python/magma/pipelined/tests/test_rule_mappers.py
  lte/protos/pipelined.proto
Labels: component: agw, size/XXL

#5931 [Non_Sanity_Testing] Generate failure instead of getting stuck for AGW offload test cases
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_idle_active_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_mixed_idle_active_multiue.py
Labels: component: agw, size/L

#5549 [ctraced] Fix timeouts, failures and completions update orc8r
  nms/app/packages/magmalte/app/views/tracing/TraceStartDialog.js
  orc8r/cloud/go/services/ctraced/ctraced/main.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/servicers/trace_servicer.go
  orc8r/cloud/go/services/ctraced/servicers/trace_servicer_test.go
  orc8r/gateway/python/magma/ctraced/command_builder.py
  orc8r/gateway/python/magma/ctraced/main.py
  orc8r/gateway/python/magma/ctraced/rpc_servicer.py
  orc8r/gateway/python/magma/ctraced/trace_manager.py
  orc8r/lib/go/protos/ctraced.pb.go
  orc8r/protos/ctraced.proto
Labels: size/XL

#5973 [docs] Add contributing guidelines to PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/docusaurus/i18n/en.json
  docs/docusaurus/static/img/magma-logo-purple.svg
  docs/readmes/contributing/contribute_conventions.md
  docs/readmes/contributing/contribute_onboarding.md
  docs/readmes/proposals/README.md
Labels: size/L

#5975 Specify orc8r db dialect and port through helm and terraform
  orc8r/cloud/deploy/terraform/orc8r-aws/outputs.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/online-upgrade/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.lock
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/magmalte-deployment.yaml
  orc8r/cloud/helm/orc8r/charts/nms/values.yaml
Labels: size/M

#5956 [lte][agw] Error indication handling
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.h
Labels: component: agw, size/L

#5903 [lte][orc8r][subscriberdb] Add southbound implementation for paginated subscriber streaming
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  lte/protos/subscriberdb.proto
Labels: component: agw, size/XL

#5922 [Ubuntu20.04][SentryNative] Build and install sentry native SDK in ubuntu VM
  lte/gateway/deploy/roles/dev_common/defaults/main.yml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/M

#5994 Fixing 2nd TEID onwards missmatch to AMF
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
Labels: component: agw, component: sessiond, product: 5g mvc, size/XS, type: enhancement

#5979 [docs] Make base README pretty
  README.md
Labels: size/M

#5986 [Non_Sanity_Testing] Fixed invalid function call for non-sanity dedicated bearer test cases
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_secondary_pdn_with_ded_bearer_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_secondary_pdn_with_ded_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_outoforder_erab_setup_rsp_dedicated_bearer.py
Labels: component: agw, size/M

#6003 [DevExp] Fixup shellcheck configuration
  .github/workflows/shellcheck.yml
Labels: size/XS

#5939 [DevExp] Migrate container to clang-format 7 for backwards compatibility
  .devcontainer/Dockerfile
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: component: agw, size/XS

#5962 [AGW][Python] Add reviewdog annotations for Python diffs
  .github/workflows/wemake-python-styleguide.yml
Labels: size/S

#6004 [DevExp] Add reviewdog yamllint linter for PR annotations
  .github/workflows/yamlint.yml
Labels: size/S

#5942 [AGW][PyFormat] Apply isort to all smaller lte python services
  lte/gateway/python/magma/health/health_service.py
  lte/gateway/python/magma/health/main.py
  lte/gateway/python/magma/health/state_recovery.py
  lte/gateway/python/magma/monitord/cpe_monitoring.py
  lte/gateway/python/magma/monitord/icmp_monitoring.py
  lte/gateway/python/magma/monitord/main.py
  lte/gateway/python/magma/monitord/tests/test_icmp_monitor.py
  lte/gateway/python/magma/pkt_tester/tests/test_ovs_gtp.py
  lte/gateway/python/magma/pkt_tester/tests/test_topology_builder.py
  lte/gateway/python/magma/pkt_tester/topology_builder.py
  lte/gateway/python/magma/redirectd/main.py
  lte/gateway/python/magma/redirectd/redirect_server.py
  lte/gateway/python/magma/redirectd/redirect_store.py
  lte/gateway/python/magma/redirectd/tests/test_redirect.py
  lte/gateway/python/magma/smsd/main.py
  lte/gateway/python/magma/smsd/relay.py
Labels: component: agw, size/M

#6007 Revert "[DevExp] Migrate container to clang-format 7 for backwards compatibility"
  .devcontainer/Dockerfile
  lte/gateway/docker/mme/Dockerfile.ubuntu20.04
Labels: size/XS

#5936 [AGW][PyFormat] Apply isort to EnodeBD
  lte/gateway/python/magma/enodebd/data_models/data_model.py
  lte/gateway/python/magma/enodebd/data_models/transform_for_magma.py
  lte/gateway/python/magma/enodebd/device_config/configuration_init.py
  lte/gateway/python/magma/enodebd/device_config/enodeb_config_postprocessor.py
  lte/gateway/python/magma/enodebd/device_config/enodeb_configuration.py
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/devices/device_map.py
  lte/gateway/python/magma/enodebd/devices/device_utils.py
  lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/enodebd_iptables_rules.py
  lte/gateway/python/magma/enodebd/logger.py
  lte/gateway/python/magma/enodebd/main.py
  lte/gateway/python/magma/enodebd/metrics.py
  lte/gateway/python/magma/enodebd/rpc_servicer.py
  lte/gateway/python/magma/enodebd/s1ap_client.py
  lte/gateway/python/magma/enodebd/state_machines/acs_state_utils.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_impl.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/stats_manager.py
  lte/gateway/python/magma/enodebd/tests/baicells_old_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_qafb_tests.py
  lte/gateway/python/magma/enodebd/tests/cavium_tests.py
  lte/gateway/python/magma/enodebd/tests/configuration_init_tests.py
  lte/gateway/python/magma/enodebd/tests/data_model_tests.py
  lte/gateway/python/magma/enodebd/tests/device_utils_tests.py
  lte/gateway/python/magma/enodebd/tests/enodeb_configuration_tests.py
  lte/gateway/python/magma/enodebd/tests/enodeb_status_tests.py
  lte/gateway/python/magma/enodebd/tests/stats_manager_tests.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enb_acs_builder.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enodeb_handler.py
  lte/gateway/python/magma/enodebd/tests/test_utils/mock_functions.py
  lte/gateway/python/magma/enodebd/tests/test_utils/spyne_builder.py
  lte/gateway/python/magma/enodebd/tests/test_utils/tr069_msg_builder.py
  lte/gateway/python/magma/enodebd/tests/timer_tests.py
  lte/gateway/python/magma/enodebd/tests/transform_for_enb_tests.py
  lte/gateway/python/magma/enodebd/tests/transform_for_magma_tests.py
  lte/gateway/python/magma/enodebd/tr069/models.py
  lte/gateway/python/magma/enodebd/tr069/server.py
  lte/gateway/python/magma/enodebd/tr069/spyne_mods.py
  lte/gateway/python/magma/enodebd/tr069/tests/models_tests.py
Labels: component: agw, size/L

#5374 [Terraform] Replace hardcoded unique names with optional configurable variables
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/efs.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/k8s.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/logging.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/storage.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: deployment, size/M, type: enhancement

#5952 [AGW][PyFormat] Apply isort to all python scripts in lte/gateway/pyth…
  lte/gateway/python/scripts/agw_health_cli.py
  lte/gateway/python/scripts/config_stateless_agw.py
  lte/gateway/python/scripts/cpe_monitoring_cli.py
  lte/gateway/python/scripts/create_oai_certs.py
  lte/gateway/python/scripts/dp_probe_cli.py
  lte/gateway/python/scripts/enodebd_cli.py
  lte/gateway/python/scripts/fake_user.py
  lte/gateway/python/scripts/feg_hello_cli.py
  lte/gateway/python/scripts/generate_dnsd_config.py
  lte/gateway/python/scripts/ha_cli.py
  lte/gateway/python/scripts/hello_cli.py
  lte/gateway/python/scripts/mobility_cli.py
  lte/gateway/python/scripts/mobility_dhcp_cli.py
  lte/gateway/python/scripts/ocs_cli.py
  lte/gateway/python/scripts/packet_ryu_cli.py
  lte/gateway/python/scripts/packet_tracer_cli.py
  lte/gateway/python/scripts/pcrf_cli.py
  lte/gateway/python/scripts/pipelined_cli.py
  lte/gateway/python/scripts/policydb_cli.py
  lte/gateway/python/scripts/s6a_proxy_cli.py
  lte/gateway/python/scripts/s6a_service_cli.py
  lte/gateway/python/scripts/session_manager_cli.py
  lte/gateway/python/scripts/sgs_cli.py
  lte/gateway/python/scripts/sms_cli.py
  lte/gateway/python/scripts/spgw_service_cli.py
  lte/gateway/python/scripts/state_cli.py
  lte/gateway/python/scripts/subscriber_cli.py
  setup.cfg
Labels: component: agw, size/L

#5983 [lte][agw] Datapath Probe Cli Script - Add Egress Option
  docs/readmes/lte/debug_dp_probe.md
  lte/gateway/python/scripts/dp_probe_cli.py
Labels: component: agw, size/L

#6000 [SessionD] Optionally enable sentry reporting for SessionD
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, component: cwag, size/M

#5628 [CI] Turn up Dockerfile Linting in GH PR
  .github/workflows/hadolint.yml
Labels: component: agw, size/S

#5977 [codeowners] Removing scott smith from NMS codeowner list
  CODEOWNERS
Labels: size/XS

#5965 [DevExp] Add ReviewDog misspell for PR spellcheck
  .github/workflows/misspell.yml
Labels: component: agw, size/S

#5548 [Orc8r] Add orcl to manage orc8r deployments
  .gitignore
  orc8r/cloud/deploy/orc8r_deployer/docker/Dockerfile
  orc8r/cloud/deploy/orc8r_deployer/docker/README.md
  orc8r/cloud/deploy/orc8r_deployer/docker/root/config.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/__init__.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/certs.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/cleanup.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/common.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/configlib.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/configlib_test.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/configure.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/install.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/orcl.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/upgrade.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/verify.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/certs.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/cleanup.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/main.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/deploy/tasks/main.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/deploy/tasks/secrets.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/deploy/tasks/tf.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/deploy/vars/all.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/az.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/efs.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/eks.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/elb.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/main.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/route53.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/secrets.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/infra/aws/tasks/vpc.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/platform/tasks/cloudwatch.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/platform/tasks/elastic.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/platform/tasks/main.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/platform/tasks/rds.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/services/orc8r/tasks/main.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/services/tasks/docker.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/services/tasks/helm.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/services/tasks/main.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/services/vars/all.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/setup.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/tf/main.tf.j2
  orc8r/cloud/deploy/orc8r_deployer/docker/root/tf/vars.tf.j2
  orc8r/cloud/deploy/orc8r_deployer/docker/run_deployer.bash
Labels: size/XXL

#6037 [Pipelined] Remove outdated rule_ids proto field processing
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw, size/XS

#6041 [bare-metal] Update readme for bare-metal-ansible deployment
  orc8r/cloud/deploy/bare-metal-ansible/README.md
Labels: size/S

#5497 AGW: Ubuntu upgrade proposal.
  docs/readmes/proposals/p013_Ubuntu_upgrade.md
Labels: size/M

#6043 [DevExp] Fixup hadolint YML and change filter mode
  .github/workflows/hadolint.yml
Labels: size/XS

#5925 [feg] Add feature to send multiple AIR request through s6a_cli
  feg/gateway/tools/s6a_cli/main.go
Labels: size/M

#6047 [SessionD][Sentry] Add commit hash as release version when initializing sentry
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, sentry, size/S

#5865 [docs][feg] Add Readmes to feg documentation
  docs/readmes/feg/docker.md
  docs/readmes/feg/session_proxy.md
  feg/gateway/docker/README.md
  feg/gateway/services/session_proxy/README.md
Labels: size/L

#6035 [SessionD] Remove non-versioned policies from Activate/Deactivate req…
  lte/gateway/c/session_manager/PipelinedClient.cpp
  lte/gateway/c/session_manager/test/Matchers.h
Labels: component: agw, size/S

#6050 [Orc8r]Was missing upgrade_precheck tags for reading service configs
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/playbooks/roles/services/tasks/main.yml
Labels: size/S

#5978 [feg] S8_proxy add QOS to CreateSessionResponse
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/mock_pgw.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
  feg/protos/s8_proxy.proto
Labels: component: cwag, size/L

#6028 AGW: BUILD: separate out lockfile for debian and ubuntu
  lte/gateway/fabfile.py
  lte/gateway/release/Makefile
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma.lockfile.debian
  lte/gateway/release/magma.lockfile.ubuntu
  lte/gateway/release/pydep
Labels: component: agw

#6026 AGW: reset OVS bridges on sctpd restart.
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: component: agw, size/S

#6058 [fuji] NMS DB data migration uses sequelize-models ^0.1.6
  nms/app/packages/magmalte/scripts/fuji-upgrade/runs-on-nms.sh
Labels: size/XS

#6046 AGW: MME: GTP: add S8 TEID args
  lte/gateway/c/oai/lib/openflow/controller/ControllerEvents.cpp
  lte/gateway/c/oai/lib/openflow/controller/ControllerEvents.h
  lte/gateway/c/oai/lib/openflow/controller/ControllerMain.cpp
  lte/gateway/c/oai/lib/openflow/controller/ControllerMain.h
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.h
  lte/gateway/c/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u.h
  lte/gateway/c/oai/tasks/gtpv1-u/gtpv1u_task.c
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/oai/test/openflow/test_gtp_app.cpp
Labels: component: agw, size/L

#6032 [backport v1.3] [AGW] mobilityd: delete map entry after releasing IP.
  lte/gateway/python/magma/mobilityd/dhcp_client.py
Labels: component: agw, component: cwag, size/XS

#6060 Contains NGAP handlers for following messages
  lte/gateway/c/oai/common/conversions.h
  lte/gateway/c/oai/include/amf_app_messages_def.h
  lte/gateway/c/oai/include/amf_app_messages_types.h
  lte/gateway/c/oai/include/n11_messages_types.h
  lte/gateway/c/oai/include/ngap_messages_def.h
  lte/gateway/c/oai/include/ngap_messages_types.h
  lte/gateway/c/oai/lib/3gpp/3gpp_38.413.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_handlers.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf_itti_messaging.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_itti_messaging.h
  lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/oai/tasks/ngap/ngap_amf_nas_procedures.h
Labels: component: agw, size/XXL

#6071 AGW: build: Fix magma lockfile ref.
  circleci/fabfile.py
  orc8r/tools/fab/pkg.py
Labels: size/XS

#5929 [lte][agw] Adding role in ansible to install and build ghz load test
  docs/docusaurus/i18n/en.json
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/S

#5331 [agw][new feature] IMEI restriction support
  lte/gateway/c/oai/common/common_ies.h
  lte/gateway/c/oai/common/common_types.h
  lte/gateway/c/oai/common/conversions.h
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/Identification.c
  lte/gateway/c/oai/tasks/nas/emm/SecurityModeControl.c
  lte/gateway/c/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/oai/tasks/nas/emm/msg/emm_msg.c
  lte/gateway/c/oai/tasks/nas/emm/sap/emm_send.c
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/deploy/roles/magma/files/update_mme_config_for_sanity.sh
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_imei_restriction_no_imeisv_in_smc.py
  lte/gateway/python/integ_tests/s1aptests/test_imei_restriction_smc.py
  lte/gateway/python/integ_tests/s1aptests/test_imei_restriction_wildcard_snr.py
Labels: component: agw, size/XL

#6016 [Pipelined]Fix IPv6 Restart Flow Recovery
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_enforcement_ipv6_restart.default_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_redirect.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
Labels: component: agw, size/L

#5707 [Bug_Fix] [MME] Fixed MME crash for stale ENB cleanup issue
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
Labels: component: agw, size/S

#6075 [lte][agw] Some optimizations and log level changes for blocked IMEI
  lte/gateway/c/oai/common/conversions.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/oai/tasks/nas/emm/SecurityModeControl.c
Labels: component: agw, size/M

#6048 [Sentry][AGW] Handle env var lookup error better in sentry init
  orc8r/gateway/python/magma/common/sentry.py
Labels: sentry, size/M

#6072 [nms] Update @fbcnms/sequelize-models to ^0.1.6
  nms/app/packages/magmalte/package.json
  nms/app/yarn.lock
Labels: size/M

#6078 [lte][agw] Generate final config file
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/deploy/roles/magma/files/update_mme_config_for_sanity.sh
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/M

#5876 Added code to handle delete session procedure
  lte/gateway/c/oai/common/CMakeLists.txt
  lte/gateway/c/oai/common/common_utility_funs.cpp
  lte/gateway/c/oai/common/common_utility_funs.h
  lte/gateway/c/oai/include/ip_forward_messages_types.h
  lte/gateway/c/oai/include/mme_app_ue_context.h
  lte/gateway/c/oai/include/s8_messages_def.h
  lte/gateway/c/oai/include/s8_messages_types.h
  lte/gateway/c/oai/include/sgw_context_manager.h
  lte/gateway/c/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/oai/lib/pcef/pcef_handlers.h
  lte/gateway/c/oai/lib/s6a_proxy/S6aClient.cpp
  lte/gateway/c/oai/lib/s8_proxy/S8Client.cpp
  lte/gateway/c/oai/lib/s8_proxy/S8Client.h
  lte/gateway/c/oai/lib/s8_proxy/s8_client_api.cpp
  lte/gateway/c/oai/lib/s8_proxy/s8_client_api.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_itti_messaging.h
  lte/gateway/c/oai/tasks/sgw/sgw_context_manager.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_s11_handlers.h
  lte/gateway/c/oai/tasks/sgw_s8/sgw_s8_task.c
Labels: component: agw, size/XXL

#6084 [lte][agw] Bug fix for missing IE in attach accept
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
Labels: apply-v1.4, component: agw, size/S

#6089 AGW: build: add sentry-native package.
  third_party/build/bin/sentry-native-build.sh
Labels: size/M

#5984 [5G: MVC][component: agw][type: enhancement] AMF-Core
  lte/gateway/c/oai/include/amf_as_message.h
  lte/gateway/c/oai/lib/3gpp/3gpp_24.501.h
  lte/gateway/c/oai/lib/3gpp/3gpp_38.413.h
  lte/gateway/c/oai/tasks/CMakeLists.txt
  lte/gateway/c/oai/tasks/amf/CMakeLists.txt
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_defs.h
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_msg.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_state_manager.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_state_manager.h
  lte/gateway/c/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_as.h
  lte/gateway/c/oai/tasks/amf/amf_asDefs.h
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/oai/tasks/amf/amf_config.c
  lte/gateway/c/oai/tasks/amf/amf_data.cpp
  lte/gateway/c/oai/tasks/amf/amf_data.h
  lte/gateway/c/oai/tasks/amf/amf_fsm.h
  lte/gateway/c/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/oai/tasks/amf/amf_identity.h
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.h
  lte/gateway/c/oai/tasks/amf/amf_sap.cpp
  lte/gateway/c/oai/tasks/amf/amf_sap.h
  lte/gateway/c/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/oai/tasks/amf/amf_smfDefs.h
  lte/gateway/c/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/oai/tasks/amf/ngap_cause.h
  lte/gateway/c/oai/tasks/amf/prepare_request_for_smf.cpp
Labels: backported-magma-5G, component: agw, size/XXL, type: enhancement

#6079 Ignore more lint warnings
  setup.cfg
Labels: size/XS

#6098 [PyLint] Add missing directories to pylint test
  lte/gateway/python/magma/tests/pylint_tests.py
  orc8r/gateway/python/magma/tests/pylint_tests.py
Labels: component: agw, size/XS

#5745 AGW: deploy envoy from magma repo.
  lte/gateway/deploy/magma_dev.yml
  lte/gateway/deploy/magma_dev_focal.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, size/XS

#6045 [lte][agw] Reformatting config_stateless_agw.py
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: component: agw, size/XS

#6010 [MME][Sentry] Enable sentry error collection on ubuntu 20.04
  lte/gateway/c/oai/CMakeLists.txt
  lte/gateway/c/oai/common/CMakeLists.txt
  lte/gateway/c/oai/common/common_utility_funs.cpp
  lte/gateway/c/oai/common/sentry_wrapper.cpp
  lte/gateway/c/oai/common/sentry_wrapper.h
  lte/gateway/c/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/oai/oai_mme/oai_mme.c
Labels: component: agw, sentry, size/L

#6095 [5G: MVC][component: agw][type: enhancement] NGAP module development #2036 Parsing config file
  lte/gateway/c/oai/include/mme_config.h
  lte/gateway/c/oai/oai_mme/oai_mme.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_embedded_spgw.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_embedded_spgw.h
  lte/gateway/c/oai/tasks/mme_app/mme_config.c
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/L

#6112 [lte][agw] Updating repo url for envoy on ansible role
  lte/gateway/deploy/roles/envoy/tasks/main.yml
Labels: component: agw, size/XS

#6115 [teravm] Add restart of sctpd after update AGW
  ci-scripts/teravm/fabfile.py
Labels: size/XS

#6080 [feg] S8_proxy add more logs to TestS8proxyManyCreateAndDeleteSession
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/ds.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
Labels: size/L

#5990 [orc8r] missing obsidian_handlers plugin for eventd
  orc8r/cloud/configs/service_registry.yml
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/values.yaml
Labels: size/XS

#6113 [swagger] Fix styling for swagger page
  orc8r/cloud/go/obsidian/swagger/v1/css/sidebar.css
Labels: size/XS

#6114 [lte][agw] Fixing attach type update on guti identity attach proc
  lte/gateway/c/oai/tasks/nas/emm/Attach.c
Labels: apply-v1.4, component: agw, size/XS

#5875 [NMS] Add subscriber paging support
  nms/app/packages/magmalte/app/components/ActionTable.js
  nms/app/packages/magmalte/app/components/context/SubscriberContext.js
  nms/app/packages/magmalte/app/state/lte/SubscriberState.js
  nms/app/packages/magmalte/app/views/subscriber/SubscriberOverview.js
  nms/app/packages/magmalte/app/views/subscriber/__tests__/SubscriberTest.js
  nms/app/packages/magmalte/mock/db.json
  nms/app/packages/magmalte/scripts/mockServer.js
Labels: size/XL

#5976 [ctraced] Change call tracing interface to 'any'
  cwf/gateway/configs/ctraced.yml
  feg/gateway/configs/ctraced.yml
  lte/gateway/configs/ctraced.yml
  orc8r/gateway/python/magma/ctraced/command_builder.py
Labels: apply-v1.4, component: agw, size/XS

#4664 [helm][tf] backport alertmanager fixes to 1.3
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: component: agw, component: cwag, size/S

#6011 [DevExp] Add dockerfile health tester
  .github/workflows/dockerfile-health.yml
Labels: component: agw, size/M

#6117 Update flake8 config to remove low pri warnings
  setup.cfg
Labels: size/S

#6093 AGW: build: aioeventlet package
  third_party/build/bin/aioeventlet-build.sh
Labels: size/M

#6094 AGW: build: package script for building aioh2
  third_party/build/bin/aioh2-build.sh
Labels: size/M

#5996 [5G: MVC][component: agw][type: enhancement] AMF-CORE with gTEID support
  lte/cloud/go/protos/session_manager.pb.go
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_smfDefs.h
  lte/gateway/c/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/protos/session_manager.proto
Labels: component: agw

#6049 [bare-metal] Fix elasticsearch deployment and update fluentd/orc8r config
  orc8r/cloud/deploy/bare-metal-ansible/README.md
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/defaults/main.yml
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/tasks/main.yml
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/templates/elasticsearch-curator-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/templates/elasticsearch-data-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/templates/elasticsearch-data2-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/templates/elasticsearch-master-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/elasticsearch/templates/elasticsearch-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/fluentd/templates/fluentd-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/kibana/defaults/main.yml
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/kibana/templates/kibana-values.yaml.j2
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/orc8r/defaults/main.yml
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/orc8r/files/orc8r-configs.yaml
  orc8r/cloud/deploy/bare-metal-ansible/roles/magma/orc8r/tasks/certs.yml
  orc8r/cloud/deploy/bare-metal/charts/elasticsearch-data.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/elasticsearch-data2.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/elasticsearch-master.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/elasticsearch.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/fluentd.yaml.tpl
  orc8r/cloud/deploy/bare-metal/charts/kibana.yaml
  orc8r/cloud/deploy/bare-metal/deploy_charts.sh
  orc8r/cloud/deploy/bare-metal/secrets/orc8r-configs.yaml
Labels: size/L

#6085 [feg] s8_proxy add ULI to Delete Request and Protocol Configuration Options to Create Session
  feg/cloud/go/protos/s8_proxy.pb.go
  feg/gateway/services/s8_proxy/client_api_test.go
  feg/gateway/services/s8_proxy/servicers/ie_conversions.go
  feg/gateway/services/s8_proxy/servicers/mock_pgw/cs.go
  feg/gateway/services/s8_proxy/servicers/proto_conversions.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/tools/s8_cli/main.go
  feg/protos/s8_proxy.proto
Labels: size/XL

#6124 Fixed compilation issue
  lte/gateway/c/oai/lib/s8_proxy/s8_client_api.cpp
Labels: component: agw, size/XS

#6073 [Orc8r] Add scripts to verify if tf variables and helm chart versions are in sync
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/README.md
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/cleanup.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/configlib_test.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/cli/install.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/test_helm_charts_sync.py
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/test_vars_sync.py
  orc8r/cloud/deploy/orc8r_deployer/docker/run_deployer.bash
Labels: size/XXL

#6127 [docusaurus] Add help message to delete node_modules in case of error
  docs/docusaurus/create_docusaurus_website.sh
  docs/docusaurus/docker-compose.yml
Labels: size/XS

#6125 Disable Pipelined Conntrack pkt counter check
  lte/gateway/python/magma/pipelined/tests/snapshots/test_conntrack.ConntrackTest.test_conntrack.snapshot
  lte/gateway/python/magma/pipelined/tests/test_conntrack.py
Labels: component: agw, size/S

#6091 AGW: build: update magma build script to handle ubuntu.
  lte/gateway/release/build-magma.sh
Labels: component: agw, size/M

#6090 AGW: deploy: add ubuntu post install script.
  lte/gateway/deploy/agw_post_install_ubuntu.sh
Labels: component: agw, size/L

#6092 AGW: build: python: Add support for ubuntu package dependency
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile.ubuntu
  orc8r/gateway/python/setup.py
Labels: component: agw, size/L

#6131 AGW: pipelined: avoid reconfiguring SGi
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
Labels: component: agw, size/XS

#6014 [lte][agw] Add load_test step to AGW fabfile (mobilityd part)
  lte/gateway/fabfile.py
  lte/gateway/python/load_tests/Makefile
  lte/gateway/python/load_tests/README.md
  lte/gateway/python/load_tests/__init__.py
  lte/gateway/python/load_tests/defs.mk
  lte/gateway/python/load_tests/loadtest_mobilityd.py
Labels: component: agw

#6134 [NMS] Ensure registered eNodeBs is active when dhcp server is disabled
  nms/app/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/packages/magmalte/app/views/equipment/__tests__/GatewayConfigTest.js
Labels: size/S

#5584 [orc8r][helm] Refactor orc8r chart with cert-manager
  orc8r/cloud/helm/orc8r/charts/certs/.helmignore
  orc8r/cloud/helm/orc8r/charts/certs/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/certs/README.md
  orc8r/cloud/helm/orc8r/charts/certs/templates/NOTES.txt
  orc8r/cloud/helm/orc8r/charts/certs/templates/admin-operator-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/admin-operator-pkcs12-password.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/bootstrapper-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/certifier-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/certifier-issuer.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/controller-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/fluentd-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/nms-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/pre-install-checks.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/root-certificate.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/root-issuer.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/selfsigned-issuer.yaml
  orc8r/cloud/helm/orc8r/charts/certs/values.yaml
  orc8r/cloud/helm/orc8r/values.yaml
Labels: size/XL

#6002 [NMS] Fix gateway HA pool config
  nms/app/packages/magmalte/app/views/equipment/EquipmentGatewayPools.js
  nms/app/packages/magmalte/app/views/equipment/GatewayPoolGatewaysEdit.js
Labels: size/L

#5928 [orc8r][configurator] Fix non-scalable entity get-all
  docs/docusaurus/create_docusaurus_website.sh
  docs/readmes/orc8r/dev_security.md
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  orc8r/cloud/docker/docker-compose.override.yml
  orc8r/cloud/docker/docker-compose.yml
  orc8r/cloud/go/services/configurator/storage/sql.go
  orc8r/cloud/go/services/configurator/storage/sql_entity_graph_helpers.go
  orc8r/cloud/go/services/configurator/storage/sql_entity_load_helpers.go
  orc8r/cloud/go/services/configurator/storage/sql_entity_write_helpers.go
  orc8r/cloud/go/services/configurator/storage/sql_integ_test.go
  orc8r/cloud/go/services/configurator/storage/sql_test.go
  orc8r/cloud/go/services/configurator/storage/storage.go
  orc8r/cloud/go/services/configurator/storage/storage.pb.go
  orc8r/cloud/go/services/configurator/storage/storage.proto
  orc8r/cloud/go/storage/storage.go
  orc8r/tools/scripts/bootstrap.bash
  orc8r/tools/scripts/consolidate_protos.bash
  orc8r/tools/scripts/consolidate_protos.sh
  wifi/cloud/go/services/wifi/obsidian/handlers/handlers_test.go
Labels: component: agw, size/XXL

#5907 [Docs] Document CI checks, purposes, points of contact
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_ci_checks.md
Labels: size/M

#6141 [flake8][config] Remove noisy lint flags from flake8 check
  setup.cfg
Labels: size/S

#6142 Fix per-file lint suppression config
  setup.cfg
Labels: component: agw, size/XS

#6143 [Doc][AGW] Add instructions for running unit tests on the dev VM
  docs/docusaurus/sidebars.json
  docs/readmes/lte/dev_unit_testing.md
Labels: size/M

#6144 [lte][agw] Fixing closing parentheses on load_test Makefile
  lte/gateway/python/load_tests/Makefile
Labels: component: agw, size/XS

#6024 [5G: MVC][component: agw][type: enhancement] Paging feature
  lte/gateway/c/oai/include/amf_service_handler.h
  lte/gateway/c/oai/include/n11_messages_def.h
  lte/gateway/c/oai/include/n11_messages_types.h
  lte/gateway/c/oai/tasks/amf/amf_app_defs.h
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_smfDefs.h
  lte/gateway/c/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/oai/tasks/grpc_service/amf_service_handler.c
Labels: component: agw, size/L

#6025 [5G: MVC][component: agw][type: enhancement] Periodic registration
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_smfDefs.h
Labels: component: agw, size/L

#5854 Add HOPrep and HOResAlloc step one
  lte/gateway/c/oai/common/itti_free_defined_msg.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_encoder.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_handlers.h
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.c
  lte/gateway/c/oai/tasks/s1ap/s1ap_mme_itti_messaging.h
Labels: component: agw, size/XL

#5501 [doc] proposal 011: Add S1 intra-AGW mobility
  docs/readmes/proposals/p011_intra_agw_mobility.md
Labels: size/M

#6129 [orc8r][nprobe] expose an eventd client package for nprobe
  orc8r/cloud/go/services/eventd/eventd_client/eventd_client.go
  orc8r/cloud/go/services/eventd/eventd_client/eventd_client_test.go
  orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/eventd/obsidian/handlers/handlers_test.go
Labels: size/XL

#6088 [orc8r][nprobe] Implement X2 records encoding/decoding
  cwf/cloud/go/go.sum
  fbinternal/cloud/go/go.sum
  feg/cloud/go/go.sum
  lte/cloud/go/go.mod
  lte/cloud/go/go.sum
  lte/cloud/go/services/nprobe/encoding/asn1.go
  lte/cloud/go/services/nprobe/encoding/asn1_test.go
  lte/cloud/go/services/nprobe/encoding/const.go
  lte/cloud/go/services/nprobe/encoding/header.go
  lte/cloud/go/services/nprobe/encoding/header_test.go
Labels: component: agw, component: cwag, size/XL

#5988 [Non_Sanity_Testing] Fixed non-sanity test case for ESM info timer expiration
  lte/gateway/python/integ_tests/s1aptests/test_attach_esm_info_timerexpiration_max_retries.py
Labels: component: agw, size/M

#6140 AGW: OVS-2.14: GTP: Fix datapath header calculations
  third_party/gtp_ovs/ovs-gtp-patches/2.14/0015-GTP-Extension-header-support-in-ovs2.14.patch
Labels: size/M

#6008 [lte][subscriberdb] Add subscriberdb client to to gateway for paginated streaming support
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/enodebd/tests/metrics_tests.py
  lte/gateway/python/magma/mobilityd/tests/metrics_tests.py
  lte/gateway/python/magma/monitord/tests/test_metrics.py
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/metrics.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
Labels: component: agw, size/XL

#6030 [5G: MVC][component: agw][type: enhancement] IDLE Mode Feature Extension
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_recv.h
  lte/gateway/c/oai/tasks/amf/amf_smf_send.cpp
Labels: component: agw, size/M

#6033 [5G: MVC][component: agw][type: enhancement] Multiple UE and multiple PDU session Support
  lte/gateway/c/oai/tasks/amf/Registration.cpp
  lte/gateway/c/oai/tasks/amf/amf_Security_Mode.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_defs.h
  lte/gateway/c/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/oai/tasks/amf/amf_identity.cpp
  lte/gateway/c/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/oai/tasks/amf/amf_security_mode_control.cpp
  lte/gateway/c/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/oai/tasks/amf/prepare_request_for_smf.cpp
Labels: component: agw, size/XL

#6022 [MME][CI][OAI] adding RHEL8 build stage
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/generateHtmlReport-OAI-pipeline.py
Labels: size/XXL

#6064 [5G: MVC][component: agw][type: enhancement] Initial Context Setup Request Implementation in AMF
  lte/gateway/c/oai/include/amf_securityDef.h
  lte/gateway/c/oai/include/ngap_messages_def.h
  lte/gateway/c/oai/lib/secu/key_nas_deriver.c
  lte/gateway/c/oai/lib/secu/secu_defs.h
  lte/gateway/c/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/oai/tasks/amf/amf_data.h
Labels: component: agw, product: 5g mvc, size/L, type: enhancement
