Repository magma/magma, pull requests merged in 2022-03, with the labels that each got.

#10888 fix(agw): fixed containerized agw docker build over macOS
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/XS

#11848 chore(agw): remove --development flag from Makefile
  lte/gateway/Makefile
Labels: component: agw, size/XS

#11838 refactor: Dependency structure of target service is more granular
  lte/gateway/python/magma/monitord/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/protocols/diameter/application/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/BUILD.bazel
  orc8r/gateway/python/magma/common/BUILD.bazel
  orc8r/gateway/python/magma/configuration/BUILD.bazel
  orc8r/gateway/python/magma/magmad/BUILD.bazel
  orc8r/gateway/python/magma/magmad/tests/BUILD.bazel
Labels: component: orc8r, component: agw, size/M, bazel

#11858 fix(subscriberdb): Update error code import
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
Labels: component: agw, size/XS

#11856 docs: Add new codeowners to list
  docs/docusaurus/versioned_docs/version-1.6.X/contributing/contribute_id_mappings.md
Labels: component: docs, size/XS

#11837 chore(mme): unused test mobility client is removed
  lte/gateway/c/core/oai/test/CMakeLists.txt
  lte/gateway/c/core/oai/test/mobility_client/CMakeLists.txt
  lte/gateway/c/core/oai/test/mobility_client/test_mobility_client.cpp
Labels: component: agw, size/L, ready2merge

#11868 fix(dp): Use mutable cbsd in post and put
  dp/cloud/go/services/dp/obsidian/handlers/handlers_test.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/S

#11847 chore(ci): Run C/C++ unit tests with ASAN and LSAN enabled
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/M

#11871 chore: remove unused import in session_manager.proto
  lte/cloud/go/protos/session_manager.pb.go
  lte/protos/session_manager.proto
Labels: component: orc8r, component: agw, size/XXL

#11874 build(mme): bazel test compiles mme with unit test flag
  .bazelrc
Labels: size/XS, bazel

#11817 chore(agw): add E1 to s1ap autopep8 python formatting
  lte/gateway/python/integ_tests/common/mobility_service_client.py
  lte/gateway/python/integ_tests/common/service303_utils.py
  lte/gateway/python/integ_tests/gxgy_tests/session_manager.py
  lte/gateway/python/integ_tests/gxgy_tests/test_usage_monitors.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_no_ueContext_release_comp.py
  lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py
  lte/gateway/python/integ_tests/s1aptests/test_no_attach_complete_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_stateless_multi_ue_mixedstate_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_messages.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
Labels: component: agw, size/L

#11875 chore: commit leftover doc file
  docs/docusaurus/i18n/en.json
Labels: component: docs, size/S

#11819 chore(pipelined): add E1 to autopep8 python formatting
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/app/inout.py
  lte/gateway/python/magma/pipelined/app/ue_mac.py
  lte/gateway/python/magma/pipelined/ng_manager/node_state_manager.py
  lte/gateway/python/magma/pipelined/ng_manager/session_state_manager.py
  lte/gateway/python/magma/pipelined/ng_manager/session_state_manager_util.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/openflow/flows.py
  lte/gateway/python/magma/pipelined/openflow/messages.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/set_interface_client.py
  lte/gateway/python/magma/pipelined/tests/ng_node_rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/test_access_control.py
  lte/gateway/python/magma/pipelined/tests/test_classifier_mme_flow_dl.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_stats.py
Labels: component: agw, size/L

#11880 chore: disable W504 and WPS348 from py lint
  setup.cfg
Labels: size/XS

#11887 fix(orc8r): Enable EPS Auth unit tests & fix affected components
  lte/cloud/go/services/eps_authentication/servicers/ai_test.go
  lte/cloud/go/services/eps_authentication/servicers/eps_auth_suite_test.go
  lte/cloud/go/services/eps_authentication/servicers/pur_test.go
  lte/cloud/go/services/eps_authentication/servicers/server.go
  lte/cloud/go/services/eps_authentication/servicers/ul_test.go
  lte/cloud/go/services/eps_authentication/storage/storage.go
Labels: component: orc8r, size/M

#11889 chore(mme): Enables Bazel build of mme core in bazel-base container
  experimental/bazel-base/Dockerfile
Labels: size/M

#11863 chore(orc8r): Upgrade nginx to latest version
  orc8r/cloud/docker/nginx/Dockerfile
Labels: component: orc8r, size/XS

#11746 chore(agw): upload journal log to sentry
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/protected/builder_servicer.go
  lte/gateway/configs/gateway.mconfig
  lte/protos/mconfig/mconfigs.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/orchestrator/obsidian/models/network_sentry_config_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/orchestrator/servicers/protected/builder_servicer.go
  orc8r/gateway/c/common/sentry/SentryWrapper.cpp
  orc8r/gateway/c/common/sentry/includes/SentryWrapper.h
  orc8r/lib/go/protos/mconfig/mconfigs.pb.go
  orc8r/protos/mconfig/mconfigs.proto
Labels: component: orc8r, component: agw, component: nms, size/XL, ready2merge

#11864 feat: avoid high resource consumption
  .devcontainer/devcontainer.json
Labels: size/XS, ready2merge

#11877 chore: add E1 to Python formatting script and CI check
  .github/workflows/python-workflow.yml
  lte/gateway/python/precommit.py
Labels: component: agw, component: ci, size/XS

#11891 fix(mme): Updating state converter's plmn_bytes array to be null-terminated
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
Labels: component: agw, size/XS

#11885 chore(ci): modify Bazel build and test job so that we only start from…
  .github/workflows/bazel.yml
Labels: component: ci, size/M

#11811 chore(mme): remove folly dependencies from cmake and docker for mme
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/c/core/oai/patches/folly-gflagslib-fix.patch
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: agw, component: ci, size/M, ready2merge

#11899 chore(mme): Moves libnettle and libgnutls installation directories
  .devcontainer/Dockerfile
  experimental/bazel-base/Dockerfile
Labels: size/XS

#11873 chore(pipelined): avoid setting result if task is already finished
  lte/gateway/python/magma/pipelined/app/base.py
Labels: component: agw, size/XS

#11911 chore(mme): Cleanup irrelevant logs and unused variable
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_pgw_pco.cpp
Labels: component: agw, size/XS

#11831 feat(ci): refine image tagging for docker images
  .devcontainer/devcontainer.json
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel-cache-push.yml
  .github/workflows/bazel.yml
  .github/workflows/docker-builder-bazel-base.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/S, ready2merge

#11862 chore(mme): Adds Bazel build target for oai/mme
  bazel/external/system_libraries.BUILD
  lte/gateway/c/core/BUILD.bazel
Labels: component: agw, size/XXL

#11923 fix(agw): fix the MAGMA-MME build in OAI variant
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: ci, size/M

#11924 feat(dp): Add total count to cbsd list
  dp/cloud/go/protos/cbsd.pb.go
  dp/cloud/go/services/dp/obsidian/handlers/handlers.go
  dp/cloud/go/services/dp/obsidian/handlers/handlers_test.go
  dp/cloud/go/services/dp/obsidian/models/paginated_cbsds_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  dp/cloud/go/services/dp/servicers/cbsd_manager.go
  dp/cloud/go/services/dp/servicers/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/db/finishing.go
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
  dp/protos/cbsd.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/L

#11912 chore(agw): Fix S1ap test names to match file names
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_activation_reject.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_activation_timer_expiry.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_activation_invalid_imsi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_activation_invalid_lbi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_deactivation_invalid_ebi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_deactivation_invalid_imsi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_bearer_deactivation_invalid_lbi.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_deactivation_timer_expiry.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_looped.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_dedicated_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_dedicated.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_sctpd_restart.py
Labels: component: agw, size/S

#11938 chore(ci): remove Bazel based test coverage for OAI
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS

#11876 chore(ci): Add a doc check to ensure all files are committed
  .github/workflows/docs-workflow.yml
Labels: component: ci, size/S

#11934 chore: remove folly from bazel oai build
  lte/gateway/c/core/BUILD.bazel
Labels: component: agw, size/XS

#11939 chore: try separating out build and test for bazel
  .github/workflows/bazel.yml
Labels: component: ci, size/L

#11908 feat(orc8r): Cache network configs in EPS Authentication implementation.
  lte/cloud/go/services/eps_authentication/servicers/config.go
Labels: component: orc8r, size/M

#11944 chore(ci): Enlarges bazel cache generation to include test scenarios
  .github/workflows/bazel-cache-push.yml
Labels: component: ci, size/XS

#11946 chore(mme): remove unused import in sgw_state.proto
  lte/cloud/go/protos/oai/sgw_state.pb.go
  lte/protos/oai/sgw_state.proto
Labels: component: orc8r, component: agw, size/M

#11954 chore(mme): fix up more relative includes
  lte/gateway/c/core/oai/lib/gtpv2-c/gtpv2c_ie_formatter/src/gtpv2c_ie_formatter.c
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_security_mode_reject_pkt.cpp
  lte/gateway/c/core/oai/test/s6a_task/s6a_recv_async_grpc_messages.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
Labels: component: agw, size/S

#11956 chore(ci): Fix bazel build and test job bug
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/check-bazel-cache-dir-size.sh
Labels: component: ci, size/M

#11949 chore: remove libfluid from bazelbase
  experimental/bazel-base/Dockerfile
Labels: size/S

#11900 chore: -fsanitize=undefined option is added to .bazelrc
  .bazelrc
Labels: size/XS, ready2merge, bazel

#11962 fix(mme): fix asan error in test_3gpp
  lte/gateway/c/core/oai/test/lib/test_3gpp.cpp
Labels: component: agw, size/XS, ready2merge, bazel-cleanup

#11940 docs: 5G-NSA documentation.
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/assets/feg/pcaps/nsa_connection.pcap
  docs/readmes/assets/lte/NSA-IE-Addition.png
  docs/readmes/howtos/5g_nsa_support.md
  docs/readmes/resources/ref_pcap.md
Labels: component: docs, size/M

#11963 chore(mobilityd): Fix type errors shown by mypy
  lte/gateway/python/magma/mobilityd/dhcp_desc.py
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ip_allocator_base.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/ip_allocator_multi_apn.py
  lte/gateway/python/magma/mobilityd/ip_allocator_pool.py
  lte/gateway/python/magma/mobilityd/ip_allocator_static.py
  lte/gateway/python/magma/mobilityd/ip_descriptor.py
  lte/gateway/python/magma/mobilityd/ip_descriptor_map.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/mac.py
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/mobilityd/uplink_gw.py
  lte/gateway/python/magma/mobilityd/utils.py
Labels: component: agw, size/L, ready2merge

#11973 fix(ci): fix typo for wildcards
  .github/workflows/agw-docker-load-test.yaml
  .github/workflows/agw-workflow.yml
  .github/workflows/build_all.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/python-workflow.yml
Labels: component: ci, size/M

#11969 fix(agw): Creating unique port number for all dedicated bearers
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_maxbearers_twopdns.py
Labels: component: agw, size/XS

#11925 fix(mme): Null terminates string to stop buffer overflow
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/include/state_converter.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
Labels: component: agw, size/S

#11975 fix(agw): Fixed wrong LTE integ test status in CI dashboard
  ci-scripts/firebase_publish_report.py
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, component: ci, size/S

#11653 chore(agw): update ovs dependency
  lte/gateway/release/build-magma.sh
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0021-datapath-update-version.patch
Labels: component: agw, component: ci, size/S

#11990 chore(agw): Add OVS test automation.
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0016-datapath-gtp-add-segmentation-offloads.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0023-Set-Default-QFI-Value.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/README.md
  third_party/gtp_ovs/ovs-gtp-patches/2.15/dev.sh
Labels: component: agw, size/L

#11966 fix(mme): fix asan error in mme_app_ip_imsi
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
Labels: component: agw, size/XS, bazel-cleanup

#11953 chore: add lte/gateway/c/core:oai_mme to VScode configs
  .devcontainer/devcontainer.json
  vscode-workspaces/workspace.magma-vm-workspace.code-workspace
Labels: size/XS

#11909 fix(mme): Expired timer recovery on service restart
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_timer_management.cpp
  lte/gateway/python/integ_tests/s1aptests/test_ics_timer_expiry_with_mme_restart.py
Labels: component: agw, size/M

#11921 fix(nms): Fix failing test for Policies
  nms/packages/magmalte/app/views/traffic/__tests__/PolicyAddEditTest.js
Labels: component: nms, size/L

#11998 fix(mme): Fix gtp_app_test with ASAN enabled
  lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/PagingApplication.cpp
Labels: component: agw, size/XS

#11600 chore(docs): Clarify Orc8r build target
  docs/readmes/orc8r/dev_build.md
Labels: component: docs, size/XS

#12000 chore(deps): bump color-string to 1.5.5 or greater
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/S

#12001 chore(ci): remove lsan from agw-workflow
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/S

#11997 fix(mme): Fix bytes_to_hex stack-buffer-overflow on log.c
  lte/gateway/c/core/oai/common/conversions.c
  lte/gateway/c/core/oai/common/conversions.h
  lte/gateway/c/core/oai/common/log.c
  lte/gateway/c/core/oai/common/log.h
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
Labels: component: agw, size/S

#11999 fix(mme): Fix smf_service_client test with ASAN
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.cpp
  lte/gateway/c/core/oai/test/n11/test_smf_service_client.cpp
Labels: component: agw, size/M

#12002 chore(mme): remove seemingly unused nwgtpv2c test-app
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwEgtPingMain.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwEvt.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniLogMgrEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniLogMgrEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniTmrMgrEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniTmrMgrEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniUdpEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniUdpEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniUlpEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-egtping/NwMiniUlpEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwEvt.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniLogMgrEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniLogMgrEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniTmrMgrEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniTmrMgrEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniUdpEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniUdpEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniUlpEntity.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/NwMiniUlpEntity.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/test-app/nw-helloworld/helloworld.c
Labels: component: agw, size/XXL

#11839 feat(dp): Add library for frequency selection
  dp/cloud/go/active_mode_controller/internal/containers/min_queue.go
  dp/cloud/go/active_mode_controller/internal/containers/min_queue_test.go
  dp/cloud/go/active_mode_controller/internal/containers/priority_queue.go
  dp/cloud/go/active_mode_controller/internal/containers/priority_queue_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/checker.go
  dp/cloud/go/active_mode_controller/internal/ranges/checker_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/decomposer.go
  dp/cloud/go/active_mode_controller/internal/ranges/decomposer_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/finder.go
  dp/cloud/go/active_mode_controller/internal/ranges/finder_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/selector.go
  dp/cloud/go/active_mode_controller/internal/ranges/selector_test.go
Labels: size/XL

#12007 chore(dp): add gnu make version to list of prerequsites
  dp/README.md
Labels: size/XS

#11933 docs: Add stale.yml file for stalebot
  .github/stale.yml
Labels: size/S, ready2merge

#11888 chore: update security policy
  SECURITY.md
Labels: size/M, ready2merge

#10918 feat(ci): add a gcc problem matcher for bazel builds
  .github/workflows/gcc-problems.yml
  .github/workflows/generate-gcc-warnings.sh
Labels: component: ci, size/L

#12015 style: Removed dead code around handle_activate_ue_flows_callback()
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/LocalEnforcer.h
Labels: component: agw, size/M

#11046 feat(orc8r): FEG_RELAY update to redirect session request to N7_N40 Proxy
  feg/cloud/configs/service_registry.yml
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/southbound/relay_router.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/southbound/session_proxy_relay.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/relay_test.go
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/tests/test_setup.go
Labels: component: feg, size/L

#12017 chore(ci): Fix GHA cache pulling logic
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/S

#12028 feat(dp): Do not send amc config for cbsds with pending requests
  dp/cloud/go/active_mode_controller/internal/app/app_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/filter.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/filter_test.go
  dp/cloud/go/active_mode_controller/protos/active_mode/active_mode.pb.go
  dp/cloud/python/magma/mappings/cbsd_states.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/active_mode_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
  dp/protos/active_mode.proto
Labels: size/L

#11971 feat(dp): Remove grant channel relationship
  dp/cloud/go/services/dp/servicers/cbsd_manager.go
  dp/cloud/go/services/dp/servicers/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/configuration_controller/response_processor/strategies/response_processing.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
  dp/cloud/python/magma/db_service/migrations/versions/1e4ead2eabe6_.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/radio_controller/services/dp/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/db_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_dp_service.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_radio_controller_service.py
Labels: size/L

#11896 fix(orc8r): lowercase orc8r service names
  feg/cloud/go/services/basic_acct/definitions.go
  feg/cloud/go/services/feg_relay/feg_relay.go
  feg/gateway/services/aaa/base_acct/client_api.go
  lte/cloud/go/services/policydb/client_api.go
  lte/cloud/go/services/smsd/const.go
  orc8r/cloud/go/services/accessd/client_api.go
  orc8r/cloud/go/services/bootstrapper/const.go
  orc8r/cloud/go/services/certifier/client_api.go
  orc8r/cloud/go/services/directoryd/client_api.go
  orc8r/cloud/go/services/dispatcher/client_api.go
  orc8r/gateway/go/directoryd/client_api.go
Labels: component: orc8r, component: feg, size/S, ready2merge

#11652 refactor(orc8r): Separate split-concern service protos
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
  feg/cloud/go/protos/health.pb.go
  feg/cloud/go/services/health/client_api.go
  feg/cloud/go/services/health/servicers/health.go
  feg/cloud/go/services/health/servicers/health_test.go
  feg/cloud/go/services/health/servicers/health_test_service.go
  feg/cloud/go/services/health/test_init/test_service_init.go
  feg/protos/health.proto
  orc8r/cloud/go/services/directoryd/servicers/protected/update_servicer.go
  orc8r/cloud/go/services/metricsd/client_api.go
  orc8r/cloud/go/services/metricsd/servicers/servicer.go
  orc8r/cloud/go/services/metricsd/servicers/servicer_test.go
  orc8r/cloud/go/services/state/client_api.go
  orc8r/cloud/go/services/state/servicers/servicer.go
  orc8r/cloud/go/services/state/servicers/servicer_test.go
  orc8r/cloud/go/services/state/state/main.go
  orc8r/cloud/go/services/state/test_init/test_service_init.go
  orc8r/lib/go/protos/metricsd.pb.go
  orc8r/lib/go/protos/state.pb.go
  orc8r/protos/metricsd.proto
  orc8r/protos/state.proto
Labels: component: orc8r, size/XL, component: cwf

#12018 chore(mme): Remove unused log_config from SGW config
  lte/gateway/c/core/oai/include/sgw_config.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
Labels: component: agw, size/L

#12034 fix: configure and enable systemd-timesyncd
  lte/gateway/deploy/roles/dev_common/files/timesyncd.conf
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/M

#12023 fix(sessiond): Send grpc status code to AMF when duplicate session re…
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.h
  lte/gateway/c/session_manager/test/test_set_session_manager_handler.cpp
Labels: component: agw, size/M, product: 5g sa

#12039 fix(mme): Fix mme_app_remove_ue_ipv6_addr and get_msisdn_from_session…
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
Labels: component: agw, size/S

#11774 fix(agw): Added cleanups for data test cases on getting failure/stuck
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
Labels: component: agw, size/L

#12014 chore(mme): address -Wunused-variable and -Wunused-function
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerEvents.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerEvents.h
  lte/gateway/c/core/oai/lib/openflow/controller/PagingApplication.cpp
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
  orc8r/gateway/c/common/ebpf/EbpfMapUtils.h
Labels: component: agw, size/M

#12026 fix(mme): enable sgw_s8_task tests with asan
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test_attach_proc.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
Labels: size/S, ready2merge, bazel-cleanup

#12027 chore(cwg): Upgrade helm.sh/helm/v3 to v3.2.4
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
Labels: size/XS, ready2merge, component: cwf

#11982 fix(orc8r): Formatted terraform files
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-aws/db.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/eks.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/providers.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/artifactory.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/remote/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/providers.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/yace.tf
Labels: component: orc8r, size/L

#12047 feat(dp): Select random channel for grant
  dp/cloud/go/active_mode_controller/cmd/main.go
  dp/cloud/go/active_mode_controller/internal/app/app.go
  dp/cloud/go/active_mode_controller/internal/app/app_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/grant.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/grant_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/selector.go
Labels: size/L

#11927 chore(mme): Adds passing OAI Core tests to Bazel configuration
  lte/gateway/c/core/oai/test/gtpv2-c/BUILD.bazel
  lte/gateway/c/core/oai/test/itti/BUILD.bazel
  lte/gateway/c/core/oai/test/mock_tasks/BUILD.bazel
  lte/gateway/c/core/oai/test/ngap/BUILD.bazel
  lte/gateway/c/core/oai/test/pipelined_client/BUILD.bazel
  lte/gateway/c/core/oai/test/s1ap_task/BUILD.bazel
Labels: component: agw, size/L

#12006 docs(agw): documentation for C++ log file upload to sentry
  docs/readmes/lte/configure_sentry.md
Labels: component: docs, size/S, ready2merge

#11795 fix(agw): Modified code to handle TAU Req for connected UEs
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/include/s1ap_types.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/nas/emm/TrackingAreaUpdate.c
  lte/gateway/c/core/oai/tasks/nas/esm/DefaultEpsBearerContextActivation.c
  lte/gateway/c/core/oai/tasks/nas/nas_procedures.c
  lte/gateway/c/core/oai/tasks/s1ap/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/python/magma/enodebd/BUILD.bazel
Labels: component: agw, size/XL

#12065 chore(mme): Adds newly passing OAI Core test to Bazel configuration
  lte/gateway/c/core/oai/test/nas/BUILD.bazel
Labels: component: agw, size/S

#12010 chore: upgrade elliptic package
  nms/yarn.lock
Labels: component: nms, size/M

#12011 chore: prismjs to 1.27.0
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/S

#12070 fix(mme): Fix pointer misalignment on handle_paging_message
  lte/gateway/c/core/oai/lib/openflow/controller/PagingApplication.cpp
Labels: component: agw, size/S

#12038 fix(mme): Fix network address in create bearer packet filter
  lte/gateway/c/core/oai/tasks/grpc_service/SpgwServiceImpl.cpp
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_maxbearers_twopdns.py
Labels: component: agw, size/S, backport-v1.7-mme

#12048 feat(dp): Remove last used max eirp
  dp/cloud/go/active_mode_controller/protos/active_mode/active_mode.pb.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
  dp/cloud/python/magma/db_service/migrations/versions/dd356a8d729e_.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/active_mode_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/db_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
  dp/protos/active_mode.proto
Labels: size/L

#12012 chore: Fix type errors and mypy.ini
  lte/gateway/python/magma/mobilityd/dhcp_client.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/ip_descriptor.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/mobility_store.py
  lte/gateway/python/magma/mobilityd/tests/test_multi_apn_ip_alloc.py
  lte/gateway/python/magma/policydb/tests/test_streamer_callback.py
  lte/gateway/python/magma/redirectd/__init__.py
  lte/gateway/python/magma/redirectd/tests/__init__.py
  lte/gateway/python/magma/subscriberdb/crypto/ECIES.py
  lte/gateway/python/magma/subscriberdb/protocols/diameter/application/abc.py
  lte/gateway/python/magma/subscriberdb/protocols/diameter/avp.py
  lte/gateway/python/magma/tests/pylint_wrapper.py
  mypy.ini
Labels: component: agw, size/M, ready2merge

#12046 chore(mme): Remove ASN1_MINIMUM_VERSION
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/tasks/ngap/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s1ap/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
Labels: component: agw, size/S

#12087 chore(ci): Add cache log for agw-workflow
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS

#12089 chore(ci): remove clang tidy/warning job
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/M

#11859 fix(pipelined): Catch error and log warning if mtr setup fails
  lte/gateway/python/magma/pipelined/main.py
Labels: component: agw, size/XS

#12062 fix(agw): Modified code to stop completion queue and clear the messages from it when mme service is stopped
  lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp
  lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h
Labels: component: agw, size/S, backport-v1.7-mme

#12092 fix(orc8r): remove old server parameter from mconfig at GX/GY/SWX
  feg/cloud/go/services/feg/servicers/protected/builder_servicer.go
  feg/cloud/go/services/feg/servicers/protected/builder_servicer_test.go
  feg/gateway/services/session_proxy/credit_control/gx/config.go
  feg/gateway/services/session_proxy/credit_control/gy/config.go
  feg/gateway/services/swx_proxy/servicers/conf_test.go
  feg/gateway/services/swx_proxy/servicers/config.go
Labels: component: feg, size/L

#12035 chore: bump jspdf
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/S, ready2merge

#11883 chore(mme): Enable ASAN and LSAN for MME C++
  lte/gateway/c/core/oai/CMakeLists.txt
Labels: component: agw, size/S, backport-v1.7-mme

#12095 fix(agw): Add typing-extensions as Python dependency
  lte/gateway/python/setup.py
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: agw, size/XS

#11456 test(mme): Add injection of state loaded in S1AP state manager
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/test/s1ap_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/s1ap_task/data/IMSI001010000000001_S1AP_ATTACHED
  lte/gateway/c/core/oai/test/s1ap_task/data/IMSI001010000000002_S1AP_ATTACHED
  lte/gateway/c/core/oai/test/s1ap_task/data/data_list.txt
  lte/gateway/c/core/oai/test/s1ap_task/data/s1ap_state_ATTACHED_encoded
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers_with_injected_state.cpp
Labels: component: agw, size/L

#12098 fix(feg): fix incorrect conversion between integer types
  feg/gateway/policydb/flow_parser.go
  feg/gateway/tgpp/utils.go
  feg/gateway/tools/gw_csfb_service_cli/main.go
  feg/gateway/tools/hello_cli/main.go
  feg/gateway/tools/s6a_cli/main.go
Labels: component: feg, size/M

#12069 chore: bump minimist
  nms/packages/magmalte/package.json
  nms/yarn.lock
Labels: component: nms, size/M

#12107 Revert "fix(agw): Fixed wrong LTE integ test status in CI dashboard (…
  ci-scripts/firebase_publish_report.py
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, component: ci, size/S

#12108 Revert "fix(agw): Added cleanups for data test cases on getting failu…
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
Labels: component: agw, size/L

#12111 chore: docker build fix
  nms/yarn.lock
Labels: component: nms, size/XS

#12110 fix(mme): Fix typing_extensions version dependency on magma_test
  lte/gateway/python/setup.py
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: agw, size/XS

#12101 feat(dp): Add grant attempt count
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/grant.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/grant_test.go
  dp/cloud/go/active_mode_controller/protos/active_mode/active_mode.pb.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/configuration_controller/response_processor/strategies/response_processing.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
  dp/cloud/python/magma/db_service/migrations/versions/d5f1e6f26fd4_.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/active_mode_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/db_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
  dp/protos/active_mode.proto
Labels: size/XL

#12032 chore: bump ssri
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/S, ready2merge

#12121 Revert "test(mme): Add injection of state loaded in S1AP state manage…
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/test/s1ap_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/s1ap_task/data/IMSI001010000000001_S1AP_ATTACHED
  lte/gateway/c/core/oai/test/s1ap_task/data/IMSI001010000000002_S1AP_ATTACHED
  lte/gateway/c/core/oai/test/s1ap_task/data/data_list.txt
  lte/gateway/c/core/oai/test/s1ap_task/data/s1ap_state_ATTACHED_encoded
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers_with_injected_state.cpp
Labels: component: agw, size/L

#12055 chore(mme): Remove unused trace defines
  lte/gateway/c/core/oai/CMakeLists.txt
  lte/gateway/c/core/oai/lib/3gpp/3gpp_requirements.h
  lte/gateway/c/core/oai/lib/hashtable/hashtable.c
  lte/gateway/c/core/oai/lib/hashtable/hashtable_uint64.c
  lte/gateway/c/core/oai/lib/hashtable/obj_hashtable.c
  lte/gateway/c/core/oai/lib/hashtable/obj_hashtable_uint64.c
  lte/gateway/c/core/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.c
Labels: component: agw, size/L

#12045 fix(agw): Update DNS resolvers for ec2 instance
  lte/gateway/deploy/agw_install_docker.sh
Labels: component: agw, size/XS

#12129 chore(mme): address GH11898
  lte/gateway/c/core/BUILD.bazel
Labels: component: agw, size/XS

#12130 chore: Mark nas_converter_test as manual until flakiness is addressed
  lte/gateway/c/core/oai/test/nas/BUILD.bazel
Labels: component: agw, size/XS

#12132 fix(mme): Fix ASAN error in SPGW unit test for IP Alloc Failure
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
Labels: component: agw, size/XS

#12013 chore: bump node-forge
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/XS, ready2merge

#12124 chore(mme): Adds newly passing OAI Core tests to Bazel configuration
  lte/gateway/c/core/oai/test/amf/BUILD.bazel
  lte/gateway/c/core/oai/test/mme_app_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/data/BUILD.bazel
Labels: component: agw, size/L

#12133 fix(mme): Fix ASAN errors in EMM context conversion unit test
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/Detach.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data.h
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
  lte/gateway/c/core/oai/test/nas/test_nas_converter.cpp
Labels: component: agw, size/S

#12138 fix(mobilityd): Update vlan param type on ip_allocator_dhcp
  lte/gateway/python/magma/mobilityd/dhcp_client.py
  lte/gateway/python/magma/mobilityd/dhcp_desc.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
Labels: component: agw, size/XS

#12122 chore: bazel dependencies are cleaned up
  WORKSPACE.bazel
  bazel/cpp_repositories.bzl
  bazel/third_party_repositories.bzl
  cwf/gateway/docker/c/Dockerfile
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/docker/services/c/Dockerfile
  lte/protos/BUILD.bazel
  lte/protos/oai/BUILD.bazel
  orc8r/gateway/c/common/config/BUILD.bazel
  orc8r/gateway/c/common/config/test/BUILD.bazel
  orc8r/protos/BUILD.bazel
Labels: component: orc8r, component: agw, component: ci, size/M, component: cwf, bazel

#12116 feat(agw): Enable Redis integration in Sentry
  orc8r/gateway/python/magma/common/sentry.py
Labels: component: orc8r, size/XS, ready2merge

#12136 fix(mme): Corrects bazel dependencies for amf_app_test_util
  lte/gateway/c/core/oai/test/amf/BUILD.bazel
  lte/gateway/c/core/oai/test/mme_app_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
Labels: component: agw, size/XS

#12141 fix(mme): Fix flaky unit tests
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/M

#12100 chore(mme): add unit test for fillIpv4
  lte/gateway/c/core/oai/tasks/grpc_service/SpgwServiceImpl.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_service_impl.cpp
Labels: component: agw, size/M, ready2merge

#12117 fix(feg): fix incorrect conversion between integer types
  feg/gateway/tools/swx_cli/main.go
  orc8r/cloud/go/services/state/indexer/registry.go
Labels: component: orc8r, component: feg, size/S, ready2merge

#11442 feat(ci): Set token permissions to read only
  .github/workflows/agw-docker-load-test.yaml
  .github/workflows/agw-workflow.yml
  .github/workflows/amis-workflow.yml
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/backport.yml
  .github/workflows/bazel-cache-push.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/docker-builder-bazel-base.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/pr_bot.yml
  .github/workflows/python-workflow.yml
  .github/workflows/rebase.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/testim-workflow.yml
  .github/workflows/unit-test-workflow.yml
  src/go/capture/gen/main.go
Labels: component: ci, size/L, ready2merge

#12152 chore(mme): remove maybe unused python mme tests
  lte/gateway/c/core/oai/test/mme_app_driver.py
  lte/gateway/c/core/oai/test/test_e2e_mme_startup.py
Labels: size/L

#12139 chore(cwg): removing vulnerable github.com/moby/moby package version
  cwf/k8s/cwf_operator/go.mod
Labels: size/XS, component: cwf

#12161 fix(mobilityd): Update vlan param for get_redis_key
  lte/gateway/python/magma/mobilityd/dhcp_client.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
Labels: size/XS

#12160 fix(orc8r): Fix missing cloud health servicer init
  feg/cloud/go/services/health/health/main.go
Labels: size/XS

#12142 chore(mme): Commits failing Bazel core oai tests with manual tag
  lte/gateway/c/core/oai/test/amf/BUILD.bazel
  lte/gateway/c/core/oai/test/mme_app_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
Labels: component: agw, size/M

#12148 chore(mme): clean up MME unit tests to remove unused main function
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/amf_app_test.cpp
  lte/gateway/c/core/oai/test/gtpv2-c/test_fteid.cpp
  lte/gateway/c/core/oai/test/itti/test_itti.cpp
  lte/gateway/c/core/oai/test/lib/test_3gpp.cpp
  lte/gateway/c/core/oai/test/lib/test_bstr.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_ApnAggregateMaximumBitRate.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_nas_encode_decode.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_ue_context.cpp
  lte/gateway/c/core/oai/test/n11/test_auth_service_client.cpp
  lte/gateway/c/core/oai/test/n11/test_smf_service_client.cpp
  lte/gateway/c/core/oai/test/nas/test_nas_converter.cpp
  lte/gateway/c/core/oai/test/ngap/ngap_test.cpp
  lte/gateway/c/core/oai/test/ngap/test_ngap_encode_decode.cpp
  lte/gateway/c/core/oai/test/openflow/test_gtp_app.cpp
  lte/gateway/c/core/oai/test/openflow/test_imsi_encoder.cpp
  lte/gateway/c/core/oai/test/openflow/test_openflow_controller.cpp
  lte/gateway/c/core/oai/test/pipelined_client/test_pipelined_client.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_test.cpp
  lte/gateway/c/core/oai/test/s6a_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/s6a_task/s6a_test.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_service_impl.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
Labels: component: agw, size/L

#12175 feat(ci): remove top level permissions
  .github/workflows/semantic-pr.yml
Labels: size/XS

#12154 refactor: Refactor bazel binaries to only include main.py
  bazel/external/requirements.in
  bazel/external/requirements.txt
  lte/gateway/python/magma/mobilityd/BUILD.bazel
  lte/gateway/python/magma/mobilityd/tests/BUILD.bazel
  lte/gateway/python/magma/policydb/BUILD.bazel
  lte/gateway/python/magma/policydb/tests/BUILD.bazel
  lte/gateway/python/magma/redirectd/BUILD.bazel
  lte/gateway/python/magma/redirectd/tests/BUILD.bazel
  orc8r/gateway/python/magma/common/BUILD.bazel
  orc8r/gateway/python/magma/eventd/BUILD.bazel
  orc8r/gateway/python/magma/eventd/tests/BUILD.bazel
Labels: size/L, ready2merge, bazel

#12162 chore: add OAI Bazel target for remaining test files
  lte/gateway/c/core/oai/test/amf/BUILD.bazel
  lte/gateway/c/core/oai/test/mme_app_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
Labels: size/M

#12143 chore: bazel file linter is applied in ci
  .github/workflows/bazel.yml
  BUILD.bazel
  bazel/cpp_repositories.bzl
  bazel/go_repositories.bzl
  orc8r/gateway/c/common/config/BUILD.bazel
Labels: component: agw, component: ci, size/M, bazel

#12177 chore(mme): Bazelify s6a_recv_async_grpc_messages.cpp test
  lte/gateway/c/core/oai/test/s6a_task/BUILD.bazel
  lte/gateway/c/core/oai/test/s6a_task/s6a_recv_async_grpc_messages.cpp
Labels: size/S, bazel

#12178 chore(mme): Preparation work to split mme_procedure_test into multiple files
  lte/gateway/c/core/oai/test/mme_app_task/BUILD.bazel
  lte/gateway/c/core/oai/test/mme_app_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/mme_procedure_test_fixture.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
Labels: size/XL

#12165 fix(pipelined): handle IPv6 node solicitation msg.
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTestVlan.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Static_IP_Test.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Test.testFlowSnapshotMatch.snapshot
Labels: size/S, apply-v1.7

#11454 fix(amf): Re-Attempt Authentication during subscriberdb lock
  lte/gateway/c/core/oai/include/amf_config.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.h
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/configs/templates/mme.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/L, product: 5g sa, ready2merge

#12180 fix(dp): Use only channels which centers are multiplies of 5MHz
  dp/cloud/go/active_mode_controller/cmd/main.go
  dp/cloud/go/active_mode_controller/internal/app/app.go
  dp/cloud/go/active_mode_controller/internal/app/app_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/grant.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/grant_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/checker.go
  dp/cloud/go/active_mode_controller/internal/ranges/checker_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/composer.go
  dp/cloud/go/active_mode_controller/internal/ranges/composer_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/decomposer.go
  dp/cloud/go/active_mode_controller/internal/ranges/decomposer_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/selector.go
  dp/cloud/go/active_mode_controller/internal/ranges/selector_test.go
  dp/cloud/go/active_mode_controller/internal/ranges/spliter.go
  dp/cloud/go/active_mode_controller/internal/ranges/spliter_test.go
Labels: size/XL

#12199 fix(dp): Make reqest order deterministic
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas/request.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/builder.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/builder_test.go
Labels: size/M

#12196 chore: all python tests are (mandatory) categorized by size
  bazel/python_test.bzl
  lte/gateway/python/magma/enodebd/tests/BUILD.bazel
  lte/gateway/python/magma/mobilityd/tests/BUILD.bazel
  lte/gateway/python/magma/monitord/tests/BUILD.bazel
  lte/gateway/python/magma/policydb/tests/BUILD.bazel
  lte/gateway/python/magma/redirectd/tests/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/tests/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/tests/crypto/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/tests/protocols/diameter/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/tests/store/BUILD.bazel
  orc8r/gateway/python/magma/directoryd/tests/BUILD.bazel
  orc8r/gateway/python/magma/eventd/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/check/kernel_check/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/check/machine_check/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/check/network_check/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/check/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/generic_command/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/upgrade/tests/BUILD.bazel
  orc8r/gateway/python/magma/state/tests/BUILD.bazel
Labels: size/M, bazel

#12192 fix(feg): Diameter closed connection recovery
  feg/gateway/diameter/connection.go
  feg/gateway/diameter/connection_manager.go
Labels: size/M, apply-v1.7

#12190 docs: update postgres upgrade instructions
  docs/docusaurus/versioned_docs/version-1.6.X/orc8r/upgrade_1_6.md
  docs/readmes/orc8r/upgrade_1_6.md
Labels: size/XS

#12188 fix(mme): Update handle_ue_context_rel_timer_expiry to return gracefully
  lte/gateway/c/core/oai/tasks/grpc_service/grpc_service_task.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/s11/s11_tasks.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.c
  lte/gateway/c/core/oai/tasks/s6a/s6a_task.c
  lte/gateway/c/core/oai/tasks/sgs/sgs_task.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c
Labels: size/M

#11686 docs: Magma extensions for inbound roaming
  docs/readmes/proposals/p026_magma_inbound_roaming_extentions.md
Labels: component: docs, size/M
