Repository magma/magma, pull requests merged in 2022-02, with the labels that each got.

#11332 fix(pipelined): Fix EBPF Unit Test Variable Type
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dl_dp.py
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dp.py
Labels: component: agw, size/S

#11334 chore: shared mconfig refactoring for sessiond and sctpd
  lte/gateway/c/sctpd/src/sctpd.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
Labels: component: agw, size/M, ready2merge

#11327 chore(mobilityd): Exclude invalid IP block error from monitoring
  lte/gateway/python/magma/mobilityd/main.py
Labels: component: agw, size/XS, ready2merge

#11355 fix(agw): Don't exclude everything from Sentry in edge case
  orc8r/gateway/python/magma/common/sentry.py
  orc8r/gateway/python/magma/common/tests/sentry_tests.py
Labels: component: orc8r, size/S, ready2merge

#11349 chore(eventd): eventd is bazelified
  bazel/external/requirements.in
  bazel/external/requirements.txt
  bazel/python_swagger_specs.bzl
  lte/swagger/BUILD.bazel
  orc8r/gateway/python/magma/common/BUILD.bazel
  orc8r/gateway/python/magma/configuration/BUILD.bazel
  orc8r/gateway/python/magma/eventd/BUILD.bazel
  orc8r/gateway/python/magma/eventd/tests/BUILD.bazel
  orc8r/swagger/BUILD.bazel
Labels: component: orc8r, size/L, ready2merge, bazel

#11336 chore(agw): move lock to object scope
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, size/S, ready2merge

#11335 chore(mme): Remove deprecated DEBUG_IS_ON defines
  lte/gateway/c/core/oai/CMakeLists.txt
  lte/gateway/c/core/oai/common/assertions.h
  lte/gateway/c/core/oai/common/log.h
  lte/gateway/c/core/oai/lib/openflow/controller/CMakeLists.txt
  lte/gateway/c/core/oai/lib/pcef/CMakeLists.txt
  lte/gateway/c/core/oai/lib/s6a_proxy/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.c
Labels: component: agw, size/M

#11364 chore: Update CODEOWNERS file to include dp ownership
  CODEOWNERS
Labels: size/XS

#11358 chore(ci): update the Bazel build job to run for Python changes as well
  .github/workflows/bazel.yml
Labels: component: ci, size/XS

#11365 fix(pipelined): Fix Unit Test arg init for qos, add ebpf guards
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, size/S

#11112 fix(ci): reduce polling load, remove processed workload
  ci-scripts/test_agent/FirebaseClient.py
  ci-scripts/test_agent/Tester.py
  ci-scripts/test_agent/magma_ci_agent.service
  ci-scripts/test_agent/main.py
Labels: component: ci, size/S

#11258 fix(agw): Fixed issue for timers not restored after mme restart
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_timer_management.cpp
Labels: component: agw, size/M

#10403 fix(orc8r): Change alsologtostderr to logtostderr in tests
  lte/cloud/go/services/ha/servicers/servicer_test.go
  lte/cloud/go/services/lte/obsidian/handlers/handlers_test.go
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/obsidian/swagger/spec/combine_test.go
  orc8r/cloud/go/service/service_test.go
  orc8r/cloud/go/services/state/client_api_test.go
  orc8r/cloud/go/services/state/indexer/index/index_test.go
  orc8r/cloud/go/services/state/indexer/integ_test.go
  orc8r/cloud/go/services/state/indexer/reindex/queue_sql_integ_test.go
  orc8r/cloud/go/services/state/indexer/reindex/queue_sql_test.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_queue_test.go
  orc8r/cloud/go/tools/combine_swagger/combine/combine_test.go
  orc8r/cloud/test/scale/basic_test.go
Labels: component: orc8r, size/S

#11369 fix(agw): Replace master with main for S1apTester repo
  lte/gateway/deploy/roles/magma_test/files/update_package.sh
Labels: component: agw, size/XS

#11177 refactor(orc8r): Segregation of Certifier service as internal
  orc8r/cloud/go/services/certifier/certifier/main.go
  orc8r/cloud/go/services/certifier/client_api_test.go
  orc8r/cloud/go/services/certifier/servicers/protected/certifier.go
  orc8r/cloud/go/services/certifier/servicers/protected/certifier_test.go
  orc8r/cloud/go/services/certifier/test_init/test_service_init.go
Labels: component: orc8r, size/S

#11372 docs: Sentry Documentation on Master Fix
  docs/docusaurus/i18n/en.json
  docs/readmes/lte/configure_sentry.md
Labels: component: docs, size/XS

#11375 fix(pipelined): Fixes qos unit test
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/utils.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: component: agw, size/S

#11328 chore(pipelined): opt-out ActivateFlows request timed out from Sentry
  lte/gateway/python/magma/pipelined/rpc_servicer.py
Labels: component: agw, size/XS, ready2merge

#11274 feat(agw): do AGW and orc8r version comparison
  orc8r/gateway/python/magma/magmad/config_manager.py
  orc8r/gateway/python/magma/magmad/tests/config_manager_tests.py
Labels: component: orc8r, size/M, ready2merge

#11373 chore(orc8r): Fix typo in subscriberdb config comment
  lte/cloud/configs/subscriberdb.yml
Labels: component: orc8r, size/XS

#11376 docs: update documentation for rootCA and SSL certs
  docs/readmes/howtos/troubleshooting/update_certificates.md
Labels: component: docs, size/XS

#11368 refactor(orc8r): NorthboundConfigurator service security changes
  orc8r/cloud/go/services/configurator/configurator/main.go
  orc8r/cloud/go/services/configurator/servicers/protected/northbound.go
  orc8r/cloud/go/services/configurator/test_init/test_service_init.go
Labels: component: orc8r, size/S

#10954 refactor(smsd): Segregation of SmsD servicer as external
  lte/cloud/go/services/smsd/servicers/southbound/smsd.go
  lte/cloud/go/services/smsd/servicers/southbound/smsd_test.go
  lte/cloud/go/services/smsd/smsd/main.go
Labels: component: orc8r, size/XS

#10950 refactor(orc8r): Segregation of Bootstrapper servicer as external
  orc8r/cloud/go/services/bootstrapper/bootstrapper/main.go
  orc8r/cloud/go/services/bootstrapper/servicers/southbound/bootstrapper.go
  orc8r/cloud/go/services/bootstrapper/servicers/southbound/bootstrapper_test.go
Labels: component: orc8r, size/S

#10997 refactor(policydb): Segregation of PolicyAssignmentController servicer
  lte/cloud/go/services/policydb/policydb/main.go
  lte/cloud/go/services/policydb/servicers/southbound/assignments.go
  lte/cloud/go/services/policydb/servicers/southbound/assignments_test.go
Labels: component: orc8r, size/XS

#10923 refactor(orc8r): Indexer service security changes
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/lte/servicers/protected/indexer_servicer.go
  lte/cloud/go/services/lte/servicers/protected/indexer_servicer_test.go
  lte/cloud/go/services/lte/test_init/test_service_init.go
  lte/cloud/go/services/subscriberdb/servicers/protected/indexer_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/protected/indexer_servicer_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/indexer_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/indexer_servicer_test.go
  orc8r/cloud/go/services/orchestrator/test_init/test_service_init.go
Labels: component: orc8r, size/S

#11391 docs: admin cert doc fix
  docs/readmes/howtos/troubleshooting/generate_admin_operator_certificates.md
Labels: component: docs, size/XS

#11292 chore: install lte and orc8r python packages in devcontainer
  .devcontainer/Dockerfile
Labels: size/M, ready2merge

#11385 fix(pipelined): Only destroy qos classes after initialization
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
Labels: component: agw, size/XS

#11034 test(amf): Additional Unit Test Cases for Stateless Feature
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/include/map.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
Labels: component: agw, size/XXL, ready2merge

#11389 fix(agw): Gracefully handle died process
  orc8r/gateway/python/magma/magmad/metrics.py
Labels: component: orc8r, size/S, ready2merge

#11397 docs: AGW eBPF based datapath
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/assets/epbf-dp1.png
  docs/readmes/lte/ebpf_datapath.md
Labels: component: docs, size/L

#11359 chore(policydb): policydb is bazelified
  lte/gateway/python/magma/policydb/BUILD.bazel
  lte/gateway/python/magma/policydb/main.py
  lte/gateway/python/magma/policydb/servicers/BUILD.bazel
  lte/gateway/python/magma/policydb/tests/BUILD.bazel
  lte/protos/BUILD.bazel
  orc8r/gateway/python/magma/common/BUILD.bazel
  orc8r/protos/BUILD.bazel
Labels: component: orc8r, component: agw, size/L, ready2merge, bazel

#11408 chore: update devcontainer image sha to latest available version
  .devcontainer/devcontainer.json
Labels: size/XS, ready2merge

#11416 fix: move the diagram png file to lte folder
  docs/readmes/lte/ebpf-dp1.png
  docs/readmes/lte/ebpf_datapath.md
Labels: component: docs, size/XS

#11324 fix(amf): Maximum number of Paging requests are getting triggered fro…
  lte/gateway/c/core/oai/include/mme_app_ue_context.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
Labels: component: agw, size/S

#11218 chore: update validator to >= 13.7.0
  nms/packages/magmalte/package.json
  nms/yarn.lock
Labels: component: nms, size/L

#11379 chore(nms): Log the actual error in case the DB migrations fail
  nms/packages/magmalte/scripts/migrate.js
Labels: component: nms, size/XS

#11409 chore(subscriberdb): Handle unknown ID in request gracefully
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
Labels: component: agw, size/S, ready2merge

#11398 chore(mme): Remove unused functions emm_attach_security and emm_attach_security_a
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/emm_proc.h
Labels: component: agw, size/L

#10856 chore(orc8r): Merge combine_swagger and swaggergen executables #5425
  orc8r/cloud/Makefile
  orc8r/cloud/go/module.mk
  orc8r/cloud/go/tools/swaggergen/combine_swagger/combine/combine.go
  orc8r/cloud/go/tools/swaggergen/combine_swagger/combine/combine_test.go
  orc8r/cloud/go/tools/swaggergen/combine_swagger/combine_swagger.go
  orc8r/cloud/go/tools/swaggergen/combine_swagger/generate/generate.go
  orc8r/cloud/go/tools/swaggergen/combine_swagger/generate/generate_test.go
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/common/common.yml
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/configs/base.yml
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/configs/cycle1.yml
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/configs/cycle2.yml
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/configs/importer.yml
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/configs/importer2.yml
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/monolithic.yml.golden
  orc8r/cloud/go/tools/swaggergen/combine_swagger/testdata/standalone.yml.golden
  orc8r/cloud/go/tools/swaggergen/main.go
  orc8r/cloud/go/tools/swaggergen/swaggergen/generate/generate.go
  orc8r/cloud/go/tools/swaggergen/swaggergen/generate/generate_test.go
  orc8r/cloud/go/tools/swaggergen/swaggergen/generate/rewrite.go
  orc8r/cloud/go/tools/swaggergen/swaggergen/generate/rewrite_test.go
  orc8r/cloud/go/tools/swaggergen/swaggergen/swaggergen.go
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/base.yml
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/base/models/bar_def_swaggergen.actual.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/base/models/bar_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/base/models/foo_def_swaggergen.actual.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/base/models/foo_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/config.yml
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/cycle1.yml
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/cycle2.yml
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer.yml
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer/models/bar_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer/models/foo_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer/models/importing_def_swaggergen.actual.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer/models/importing_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2.yml
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/bar_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/baz_array_swaggergen.actual.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/baz_array_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/foo_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/importing_chain_def_swaggergen.actual.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/importing_chain_def_swaggergen.go.golden
  orc8r/cloud/go/tools/swaggergen/swaggergen/testdata/importer2/models/importing_def_swaggergen.go.golden
Labels: component: orc8r, size/L

#11370 fix(agw): Bump mysqlclient to 1.3.13
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, size/XS

#10962 refactor(orc8r): Segregation of Swagger servicer as internal
  cwf/cloud/go/services/cwf/cwf/main.go
  fbinternal/cloud/go/services/fbinternal/fbinternal/main.go
  fbinternal/cloud/go/services/testcontroller/testcontroller/main.go
  feg/cloud/go/services/feg/feg/main.go
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/nprobe/nprobe/main.go
  lte/cloud/go/services/policydb/policydb/main.go
  lte/cloud/go/services/smsd/smsd/main.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  orc8r/cloud/go/obsidian/swagger/handlers/handlers_test.go
  orc8r/cloud/go/obsidian/swagger/poll_test.go
  orc8r/cloud/go/obsidian/swagger/servicers/protected/spec_servicer.go
  orc8r/cloud/go/obsidian/swagger/servicers/protected/spec_servicer_test.go
  orc8r/cloud/go/services/certifier/certifier/main.go
  orc8r/cloud/go/services/ctraced/ctraced/main.go
  orc8r/cloud/go/services/eventd/eventd/main.go
  orc8r/cloud/go/services/metricsd/metricsd/main.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/tenants/tenants/main.go
Labels: component: orc8r, component: feg, size/M, component: cwf

#11405 fix(dp): single DB queries in RC active mode service
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
Labels: size/M

#11415 refactor(orc8r): Builder servicer endpoint as internal
  cwf/cloud/go/services/cwf/cwf/main.go
  cwf/cloud/go/services/cwf/servicers/protected/builder_servicer.go
  cwf/cloud/go/services/cwf/servicers/protected/builder_servicer_test.go
  cwf/cloud/go/services/cwf/test_init/test_service_init.go
  feg/cloud/go/services/feg/feg/main.go
  feg/cloud/go/services/feg/servicers/protected/builder_servicer.go
  feg/cloud/go/services/feg/servicers/protected/builder_servicer_test.go
  feg/cloud/go/services/feg/test_init/test_service_init.go
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/lte/servicers/protected/builder_servicer.go
  lte/cloud/go/services/lte/servicers/protected/builder_servicer_test.go
  lte/cloud/go/services/lte/test_init/test_service_init.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/builder_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/builder_servicer_test.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/export_test.go
  orc8r/cloud/go/services/orchestrator/test_init/test_service_init.go
Labels: component: orc8r, component: feg, size/S, component: cwf

#11378 chore(agw): Update installed Magma version from 1.6.0 to 1.6.1
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
Labels: size/XS, ready2merge

#11426 fix: Add missing docs links.
  docs/docusaurus/sidebars.json
Labels: component: docs, size/XS

#11424 fix(pipelined): qos object creation on activate flows.
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
Labels: component: agw, size/S

#10497 feat(amf): Add support for IPv6 pdu session procedures
  lte/gateway/c/core/oai/include/amf_app_messages_types.h
  lte/gateway/c/core/oai/include/n11_messages_types.h
  lte/gateway/c/core/oai/lib/n11/M5GMobilityServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/M5GMobilityServiceClient.h
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_client_servicer.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_fsm.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smfDefs.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GPDUAddress.h
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GPDUAddress.cpp
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.h
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
  lte/gateway/c/core/oai/test/n11/test_smf_service_client.cpp
Labels: component: agw, size/XXL, ready2merge

#11340 chore: update SBOM
  sbom/README.md
  sbom/npm-bom.json
  sbom/sbom-json.tgz
Labels: size/XXL, ready2merge

#11392 chore: upgrade shelljs to >= 0.8.5
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/XL

#11354 fix(dp): relinquish grant on UNSYNC_OP_PARAM heartbeat
  dp/cloud/go/active_mode_controller/internal/message_generator/heartbeat.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/protos/active_mode/active_mode.pb.go
  dp/cloud/python/magma/configuration_controller/response_processor/response_db_processor.py
  dp/cloud/python/magma/configuration_controller/response_processor/strategies/response_processing.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
  dp/cloud/python/magma/mappings/cbsd_states.py
  dp/cloud/python/magma/mappings/types.py
  dp/protos/active_mode.proto
Labels: size/L

#11090 feat(amf): Stateless feature integration for AMF
  lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.cpp
Labels: component: agw, size/M

#11451 fix(pipelined): qos tc class setup.
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, size/XS

#11383 docs(orc8r): Removed install orc8r managed page
  docs/docusaurus/sidebars.json
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/deploy_orcl.md
Labels: component: docs, size/L

#11175 refactor(orc8r): Segregation of AnalyticsController servicer as internal
  cwf/cloud/go/services/cwf/cwf/main.go
  lte/cloud/go/services/lte/lte/main.go
  orc8r/cloud/go/services/analytics/servicers/protected/collector_servicer.go
  orc8r/cloud/go/services/analytics/servicers/protected/collector_servicer_test.go
  orc8r/cloud/go/services/certifier/certifier/main.go
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
Labels: component: orc8r, size/S, component: cwf

#11452 chore: commit leftover go.mod and go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
Labels: component: feg, size/XS

#11259 fix(agw): Reenabled timer test cases that were not restored after mme restart
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_implicit_detach_timer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_mobile_reachability_tmr_with_mme_restart.py
Labels: component: agw, size/M

#11448 chore(agw): print version mismatch message only once for magmad process update
  orc8r/gateway/python/magma/magmad/config_manager.py
Labels: component: orc8r, size/S, ready2merge

#11410 chore: add python formatter and accompanying vscode settings to devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: size/S, ready2merge

#11396 fix(orc8r): Updated default variable value for cert-manager iam role
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: component: orc8r, size/XS

#11404 chore(agw): remove unused asn1 message files
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-CommonDataTypes.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-Constants.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-Containers.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-IEs.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-PDU-Contents.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-PDU-Descriptions.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r10.5/S1AP-PDU.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r8.10/S1AP-CommonDataTypes.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r8.10/S1AP-Constants.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r8.10/S1AP-IEs.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r8.10/S1AP-PDU-Contents.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r8.10/S1AP-PDU.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-CommonDataTypes.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-Constants.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-Containers.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-IEs.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-PDU-Contents.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-PDU-Descriptions.asn
  lte/gateway/c/core/oai/tasks/s1ap/messages/asn1/r9.8/S1AP-PDU.asn
Labels: component: agw, size/XXL

#10965 refactor(orc8r): Segregation of ha_orc8r.proto servicers to southbound
  lte/cloud/go/services/ha/ha/main.go
  lte/cloud/go/services/ha/servicers/southbound/servicer.go
  lte/cloud/go/services/ha/servicers/southbound/servicer_test.go
Labels: component: orc8r, size/XS

#11450 fix: modify poll interval to check for new version in magmad
  orc8r/gateway/python/magma/magmad/metrics.py
Labels: component: orc8r, size/XS

#11470 chore(mme): Remove unused memory pool code
  lte/gateway/c/core/oai/lib/itti/memory_pools.c
  lte/gateway/c/core/oai/lib/itti/memory_pools.h
Labels: component: agw, size/XL

#11412 refactor(orc8r): Directoryd service security changes
  orc8r/cloud/go/services/directoryd/client_api.go
  orc8r/cloud/go/services/directoryd/directoryd/main.go
  orc8r/cloud/go/services/directoryd/protos/directoryd.pb.go
  orc8r/cloud/go/services/directoryd/protos/directoryd.proto
  orc8r/cloud/go/services/directoryd/protos/directoryd_helper.go
  orc8r/cloud/go/services/directoryd/servicers/protected/id_gen.go
  orc8r/cloud/go/services/directoryd/servicers/protected/id_gen_test.go
  orc8r/cloud/go/services/directoryd/servicers/protected/servicer.go
  orc8r/cloud/go/services/directoryd/servicers/protected/servicer_test.go
  orc8r/cloud/go/services/directoryd/servicers/protected/update_servicer.go
  orc8r/cloud/go/services/directoryd/test_init/test_service_init.go
  orc8r/lib/go/protos/directoryd.pb.go
  orc8r/protos/directoryd.proto
Labels: component: orc8r, size/XXL

#11015 refactor(subscriberdb): Segregation of SubscriberDBCloud servicer
  lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
Labels: component: orc8r, size/S

#11430 refactor(orc8r): Ctraced servicer endpoint as external
  orc8r/cloud/go/services/ctraced/ctraced/main.go
  orc8r/cloud/go/services/ctraced/servicers/southbound/trace_servicer.go
  orc8r/cloud/go/services/ctraced/servicers/southbound/trace_servicer_test.go
Labels: component: orc8r, size/XS

#10952 refactor(orc8r): Segregation of Streamer servicer as external
  orc8r/cloud/go/services/orchestrator/test_init/test_service_init.go
  orc8r/cloud/go/services/streamer/servicers/southbound/servicer.go
  orc8r/cloud/go/services/streamer/servicers/southbound/servicer_test.go
  orc8r/cloud/go/services/streamer/streamer/main.go
  orc8r/cloud/go/services/streamer/test_init/test_service_init.go
Labels: component: orc8r, size/S

#11306 docs(agw): add CUPS to AGW deploy config
  docs/docusaurus/versioned_docs/version-1.6.X/lte/deploy_install.md
  docs/readmes/howtos/package.md
  docs/readmes/lte/deploy_install.md
  docs/readmes/orc8r/upgrade_1_5.md
Labels: component: docs, size/M

#11471 docs: TEID allocation documentation
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/howtos/inbound_roaming.md
  docs/readmes/lte/teid_allocation.md
Labels: component: docs, size/M

#11435 chore: pick up platform-server 0.3.1
  nms/packages/magmalte/package.json
  nms/yarn.lock
Labels: component: nms, size/L

#11467 chore(pipelined): qos: Improve debug logging
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py
Labels: component: agw, size/S

#11464 fix(sctpd): Use correct tag for service in Sentry
  lte/gateway/c/sctpd/src/sctpd.cpp
Labels: component: agw, size/XS

#11102 fix(pipelined): ip_solicitation: Use link local address for RA
  cwf/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/python/magma/pipelined/app/ipv6_solicitation.py
  orc8r/gateway/python/magma/common/misc_utils.py
  xwf/gateway/configs/pipelined.yml
Labels: component: orc8r, component: agw, size/M, component: cwf, component: xwf

#11478 fix(pipelined): Catch Redis ConnectionError
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, size/XS

#11403 chore(pipelined): Change loglevel for request validation errors
  lte/gateway/python/magma/pipelined/ng_manager/session_state_manager.py
Labels: component: agw, size/XS

#11422 feat(agw): Add initial UE stats tracking to eBPF
  lte/gateway/c/core/oai/tasks/gtpv1-u/ebpf_dl_map.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/python/magma/pipelined/ebpf/ebpf_dl_handler.c
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/ebpf/ebpf_ul_handler.c
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dl_dp.py
Labels: component: agw, size/M

#11460 chore(connectiond): enable sentry for connectiond
  .github/workflows/build_all.yml
  lte/gateway/c/connection_tracker/CMakeLists.txt
  lte/gateway/c/connection_tracker/src/BUILD.bazel
  lte/gateway/c/connection_tracker/src/CMakeLists.txt
  lte/gateway/c/connection_tracker/src/main.cpp
  orc8r/gateway/c/common/sentry/includes/SentryWrapper.h
Labels: component: agw, component: ci, size/S, ready2merge

#11446 feat: migrate filter list to opt-out
  lte/gateway/configs/gateway.mconfig
  lte/gateway/python/magma/subscriberdb/client.py
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/orchestrator/obsidian/models/network_sentry_config_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/gateway/python/magma/common/streamer.py
  orc8r/gateway/python/magma/eventd/rpc_servicer.py
  orc8r/gateway/python/magma/magmad/bootstrap_manager.py
  orc8r/gateway/python/magma/magmad/metrics_collector.py
  orc8r/gateway/python/magma/magmad/proxy_client.py
  orc8r/gateway/python/magma/magmad/service_poller.py
  orc8r/gateway/python/magma/magmad/state_reporter.py
  orc8r/gateway/python/magma/magmad/sync_rpc_client.py
  orc8r/gateway/python/magma/state/state_replicator.py
Labels: component: orc8r, component: agw, size/L, ready2merge

#11488 fix(pipelined): Fix eBPF pkt length comparison
  lte/gateway/python/magma/pipelined/ebpf/ebpf_dl_handler.c
Labels: component: agw, size/S

#11219 fix(agw): Increase unlimited rate from 200Mbps/100Mbps for DL/UL to 4Gbps/2Gbps for DL/UL
  lte/gateway/configs/subscriberdb.yml
  nms/packages/magmalte/app/components/network/DataPlanConst.js
Labels: component: agw, component: nms, size/XS

#11490 chore: Update pipelined doc.
  docs/readmes/lte/pipelined.md
Labels: component: docs, size/XS

#11491 fix(pipelined): Load eBPF only when enabled
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dl_dp.py
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dp.py
Labels: component: agw, size/M

#11489 fix(mme): Remove incorrect free and add ITTI initialization in unit test
  lte/gateway/c/core/oai/test/itti/test_itti.cpp
Labels: component: agw, size/M

#11453 fix(agw): Fix brigde reset -n option
  lte/gateway/deploy/roles/magma/files/magma-bridge-reset.sh
Labels: component: agw, size/XS

#11438 fix(subscriberdb): Handling sqlite lock failure
  lte/gateway/c/core/oai/lib/n11/M5GAuthenticationServiceClient.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/python/magma/subscriberdb/metrics.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/store/base.py
  lte/gateway/python/magma/subscriberdb/store/sqlite.py
Labels: component: agw, size/M, ready2merge

#11311 fix(agw): Added response timeout for stuck test cases
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/M

#11498 fix(magmad): sentry bazel dependency is added to magmad
  orc8r/gateway/python/magma/magmad/BUILD.bazel
Labels: component: orc8r, size/XS, ready2merge, bazel

#11479 chore: bazel codeowners/approvers are configured
  CODEOWNERS
Labels: size/S, bazel

#11474 chore(magmad): Fix metrics naming filling during collection
  orc8r/gateway/python/magma/common/metrics_export.py
  orc8r/gateway/python/magma/common/tests/metrics_tests.py
  orc8r/gateway/python/magma/magmad/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/tests/metrics_tests.py
Labels: component: orc8r, size/L

#10850 refactor(orc8r): ServiceRegistry service security changes
  orc8r/cloud/go/services/service_registry/service_registry/main.go
  orc8r/cloud/go/services/service_registry/servicers/protected/docker_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/protected/docker_servicer_test.go
  orc8r/cloud/go/services/service_registry/servicers/protected/kubernetes_servicer.go
  orc8r/cloud/go/services/service_registry/servicers/protected/kubernetes_servicer_test.go
Labels: component: orc8r, size/XS

#8982 fix(agw): Added asynchronous grpc server to handle grpc messages over s6a interface
  lte/gateway/c/core/oai/include/grpc_service.h
  lte/gateway/c/core/oai/include/tasks_def.h
  lte/gateway/c/core/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/async_grpc_service/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.cpp
  lte/gateway/c/core/oai/tasks/async_grpc_service/grpc_async_service_task.h
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/grpc_service/S6aGatewayImpl.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/S6aGatewayImpl.h
  lte/gateway/c/core/oai/tasks/grpc_service/grpc_service.cpp
  lte/gateway/c/core/oai/test/CMakeLists.txt
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.h
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mme_app_mock.cpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.h
  lte/gateway/c/core/oai/test/mock_tasks/s6a_mock.cpp
  lte/gateway/c/core/oai/test/s6a_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/s6a_task/s6a_recv_async_grpc_messages.cpp
  lte/gateway/c/core/oai/test/s6a_task/s6a_test.cpp
Labels: component: agw, size/XXL

#11461 fix(agw): Added code to send event for attach failure
  lte/gateway/c/core/oai/include/mme_events.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_events.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/configs/eventd.yml
  lte/swagger/mme_events.v1.yml
Labels: component: agw, size/S

#11502 feat(dp): performance tests framework and indexes for domain proxy logs
  dp/Makefile
  dp/cloud/python/magma/db_service/migrations/versions/6234f59dd8e4_.py
  dp/cloud/python/magma/db_service/models.py
  dp/tools/performance_tests/README.md
  dp/tools/performance_tests/config.py
  dp/tools/performance_tests/insert_data.sql
  dp/tools/performance_tests/performance_test_setup.py
  dp/tools/performance_tests/run_performance_tests.py
  dp/tools/performance_tests/selects.sql
Labels: size/L

#11524 fix(nms): Fix 11172 with allow register eNB to multiple AGW
  nms/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/packages/magmalte/app/views/equipment/GatewayDetailSubscribers.js
Labels: component: nms, size/M

#9620 feat(nms): subscriber bulk remove
  nms/packages/magmalte/app/components/ActionTable.js
  nms/packages/magmalte/app/state/lte/SubscriberState.js
  nms/packages/magmalte/app/theme/default.js
  nms/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
  nms/packages/magmalte/app/views/subscriber/SubscriberTable.js
  nms/packages/magmalte/app/views/subscriber/SubscriberUtils.js
Labels: component: nms, size/XXL

#11496 fix(amf): Convert std logs to OAI Logs
  lte/gateway/c/core/oai/lib/n11/amf_client_proto_msg_to_itti_msg.cpp
Labels: component: agw, size/M

#11533 Revert "chore(agw): Update metrics naming on exporting (#11474)"
  orc8r/gateway/python/magma/common/metrics_export.py
  orc8r/gateway/python/magma/common/tests/metrics_tests.py
  orc8r/gateway/python/magma/magmad/tests/BUILD.bazel
  orc8r/gateway/python/magma/magmad/tests/metrics_tests.py
Labels: component: orc8r, size/L

#9708 fix(agw): fix time and ip address encoding for nprobe
  lte/cloud/go/services/nprobe/encoding/const.go
  lte/cloud/go/services/nprobe/encoding/testdata/gen_time_encoded.golden
  lte/cloud/go/services/nprobe/encoding/utils.go
Labels: component: orc8r, size/M

#11305 fix(amf): Fix for multisession service request
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/include/amf_as_message.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_38.331.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.h
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/L

#11546 chore(mme): Add bazel build targets for mme's protos/grpcs
  feg/protos/BUILD.bazel
  lte/protos/BUILD.bazel
  lte/protos/oai/BUILD.bazel
  orc8r/protos/BUILD.bazel
Labels: component: orc8r, component: agw, component: feg, size/L

#11530 fix(dp): introducing mutable_cbsd entity in swagger definitions
  dp/cloud/go/services/dp/obsidian/handlers/handlers.go
  dp/cloud/go/services/dp/obsidian/handlers/handlers_test.go
  dp/cloud/go/services/dp/obsidian/models/cbsd_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/conversion.go
  dp/cloud/go/services/dp/obsidian/models/conversion_test.go
  dp/cloud/go/services/dp/obsidian/models/mutable_cbsd_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/L

#11551 fix(mme): Corrects test_mme_procedures.cpp include of bstrlib.c
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_procedures.cpp
Labels: component: agw, size/XS

#11557 fix(mme): Removes duplicate macro implementations
  lte/gateway/c/core/oai/tasks/amf/amf_smfDefs.h
Labels: component: agw, size/XS

#11559 fix(mme): Add missing include for use of true/false
  lte/gateway/c/core/oai/tasks/nas/util/socket.c
Labels: component: agw, size/XS

#11582 chore(mme): Drop Bazel sub-modules which will conflict with c/core
  lte/gateway/c/core/oai/common/BUILD.bazel
  lte/gateway/c/core/oai/common/redis_utils/BUILD.bazel
  lte/gateway/c/core/oai/lib/hashtable/BUILD.bazel
  lte/gateway/c/core/oai/tasks/ngap/BUILD.bazel
  lte/gateway/c/core/oai/tasks/s1ap/BUILD.bazel
Labels: component: agw, size/L

#11590 chore(mme): Delete dead code in nas/ies/GprsTimer.*
  lte/gateway/c/core/oai/tasks/nas/ies/GprsTimer.c
  lte/gateway/c/core/oai/tasks/nas/ies/GprsTimer.h
Labels: component: agw, size/L

#11531 feat: lldb is used for C minidump debugging
  .devcontainer/Dockerfile
Labels: size/XS, ready2merge

#11573 fix(pipelined): Changing the default QFI value to 9 instead of 5
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0023-Set-Default-QFI-Value.patch
Labels: component: agw, size/M, product: 5g sa

#11555 fix(mme): Add missing common_defs.h include for status_code_e use
  lte/gateway/c/core/oai/tasks/nas/api/network/network_api.h
Labels: component: agw, size/XS

#11598 chore: Add Shubham to codeowners
  CODEOWNERS
Labels: size/XS

#11565 chore(mme): Delete dead code in MsNetworkCapability
  lte/gateway/c/core/oai/tasks/nas/ies/MsNetworkCapability.c
  lte/gateway/c/core/oai/tasks/nas/ies/MsNetworkCapability.h
Labels: component: agw, size/L

#11561 fix(mme): Adds missing include to sgs_defs.h
  lte/gateway/c/core/oai/tasks/sgs/sgs_defs.h
Labels: component: agw, size/XS

#11553 chore(mme): Removes un-necessary HAS_SCTPD check
  lte/gateway/c/core/oai/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.h
Labels: component: agw, size/XS

#11575 chore(mme): Delete dead code in mem_app_sgsap.c
  lte/gateway/c/core/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap.c
Labels: component: agw, size/L

#11567 chore(mme): Deletes dead code as_messages.c and defns in as_message.h
  lte/gateway/c/core/oai/include/nas/as_message.h
  lte/gateway/c/core/oai/tasks/nas/api/network/as_message.c
Labels: component: agw, size/L

#11579 chore(mme): Fix up newly-added non-full-path include statements
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.h
  lte/gateway/c/core/oai/tasks/amf/amf_client_servicer.cpp
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_recv.c
  lte/gateway/c/core/oai/tasks/s11/s11_mme_session_manager.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_algorithm_selection.cpp
  lte/gateway/c/core/oai/test/amf/util_s6a_update_location.cpp
  lte/gateway/c/core/oai/test/amf/util_s6a_update_location.h
  lte/gateway/c/core/oai/test/mock_tasks/grpc_mock.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_recv_grpc_messages.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
Labels: component: agw, size/M

#11601 chore(mme): Delete dead code of ies/AuthenticationFailureParameter.*
  lte/gateway/c/core/oai/tasks/nas/ies/AuthenticationFailureParameter.c
  lte/gateway/c/core/oai/tasks/nas/ies/AuthenticationFailureParameter.h
Labels: component: agw, size/L

#11563 chore(mme): Delete dead code ProtocolConfigurationptions
  lte/gateway/c/core/oai/tasks/nas/ies/ProtocolConfigurationOptions.c
  lte/gateway/c/core/oai/tasks/nas/ies/ProtocolConfigurationOptions.h
Labels: component: agw, size/L

#11602 chore: remove dead code (sgs_send_service_request) in sgs task
  lte/gateway/c/core/oai/tasks/sgs/sgs_messages.h
  lte/gateway/c/core/oai/tasks/sgs/sgs_paging.c
  lte/gateway/c/core/oai/tasks/sgs/sgs_service_request.c
Labels: component: agw, size/L

#11203 fix(policydb): Re-enable BaseNamesStreamerCallback
  lte/gateway/python/magma/policydb/basename_store.py
  lte/gateway/python/magma/policydb/main.py
  lte/gateway/python/magma/policydb/rating_group_store.py
  lte/gateway/python/magma/policydb/rule_store.py
  lte/gateway/python/magma/policydb/streamer_callback.py
  lte/gateway/python/magma/policydb/tests/mock_stubs.py
Labels: component: agw, size/M

#10313 feat(nms): Add support to configure IPv6 address and IPv6 GW IP for SGi
  nms/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/packages/magmalte/app/views/equipment/__tests__/GatewayConfigTest.js
Labels: component: nms, size/M

#11165 chore(deps): Upgrade aiohttp from 3.6.2 to 3.8.0
  lte/gateway/python/setup.py
Labels: component: agw, size/XS

#11342 fix(nms): Add back base name editing function
  nms/packages/magmalte/app/components/context/LteNetworkContext.js
  nms/packages/magmalte/app/components/context/PolicyContext.js
  nms/packages/magmalte/app/components/lte/LteContext.js
  nms/packages/magmalte/app/components/lte/LteSections.js
  nms/packages/magmalte/app/state/PolicyState.js
  nms/packages/magmalte/app/state/lte/NetworkState.js
  nms/packages/magmalte/app/views/network/__tests__/NetworkTest.js
  nms/packages/magmalte/app/views/subscriber/__tests__/SubscriberAddEditTest.js
  nms/packages/magmalte/app/views/traffic/BaseNameEdit.js
  nms/packages/magmalte/app/views/traffic/DataPlanEdit.js
  nms/packages/magmalte/app/views/traffic/DataPlanOverview.js
  nms/packages/magmalte/app/views/traffic/PolicyOverview.js
  nms/packages/magmalte/app/views/traffic/TrafficOverview.js
  nms/packages/magmalte/app/views/traffic/__tests__/TrafficOverviewTest.js
Labels: component: nms, size/XXL

#11194 feat(agw): Handle Release Access Bearer Responses from multiple tasks
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
Labels: component: agw, size/M

#11607 chore(mme): remove as_message_send from as_message.h
  lte/gateway/c/core/oai/include/nas/as_message.h
  lte/gateway/c/core/oai/tasks/nas/api/network/network_api.c
Labels: component: agw, size/M

#11500 chore: use virtualenv to install external python dependencies and make generated proto files available there
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: size/M, ready2merge

#11535 chore(orc8r): Removed thanos acl variable from terraform
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/thanos.tf
Labels: component: orc8r, size/XS

#9696 feat(nms): Add subscriber bulk edit new workflow
  nms/packages/magmalte/app/views/subscriber/SubscriberAddDialog.js
  nms/packages/magmalte/app/views/subscriber/SubscriberApnStaticIpsEdit.js
  nms/packages/magmalte/app/views/subscriber/SubscriberDetailConfig.js
  nms/packages/magmalte/app/views/subscriber/SubscriberEditDialog.js
  nms/packages/magmalte/app/views/subscriber/SubscriberTable.js
  nms/packages/magmalte/app/views/subscriber/SubscriberTrafficPolicyEdit.js
  nms/packages/magmalte/app/views/subscriber/SubscriberUpload.js
  nms/packages/magmalte/app/views/subscriber/SubscriberUtils.js
Labels: component: nms, size/XXL

#11605 fix(pipelined): rebuild ipv6 ue address for stats report
  lte/gateway/python/magma/pipelined/app/enforcement_stats.py
  lte/gateway/python/magma/pipelined/ipv6_prefix_store.py
Labels: component: agw, size/M

#11463 chore: commit magma.lockfile.ubuntu
  lte/gateway/release/magma.lockfile.ubuntu
Labels: component: ci, size/S

#11520 chore(ctraced): ctraced is bazelified
  orc8r/gateway/python/magma/ctraced/BUILD.bazel
  orc8r/protos/BUILD.bazel
Labels: component: orc8r, size/M

#11434 chore(orc8r): Added query params tests for REST API auth
  orc8r/cloud/go/obsidian/access/tests/rest_middleware_test.go
  orc8r/cloud/go/services/certifier/test_utils/test_utils.go
Labels: component: orc8r, size/L

#11619 fix(sessiond): sessiond searches session based on IPv4 and IPv6
  lte/gateway/c/session_manager/LocalEnforcer.cpp
  lte/gateway/c/session_manager/SessionStore.cpp
  lte/gateway/c/session_manager/SessionStore.h
  lte/gateway/c/session_manager/test/ProtobufCreators.cpp
  lte/gateway/c/session_manager/test/ProtobufCreators.h
  lte/gateway/c/session_manager/test/test_local_enforcer.cpp
  lte/gateway/c/session_manager/test/test_sessiond_integ.cpp
Labels: component: agw, size/M

#11616 fix(dp): Do not do any operations for a cbsd when state change is pending
  dp/cloud/go/active_mode_controller/internal/app/app_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/filter.go
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/filter_test.go
  dp/cloud/go/active_mode_controller/protos/active_mode/active_mode.pb.go
  dp/cloud/python/magma/configuration_controller/request_consumer/request_db_consumer.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_request_consumer.py
  dp/cloud/python/magma/mappings/cbsd_states.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/active_mode_config_builder.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/db_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
  dp/protos/active_mode.proto
Labels: size/XL

#11572 chore(mme): Provides unique function name for convert_itti_sgsap_...
  lte/gateway/c/core/oai/lib/sms_orc8r_client/SMSOrc8rClient.cpp
  lte/gateway/c/core/oai/lib/sms_orc8r_client/itti_msg_to_proto_msg.cpp
  lte/gateway/c/core/oai/lib/sms_orc8r_client/itti_msg_to_proto_msg.h
Labels: component: agw, size/XS

#11597 chore(agw): Include LiAgentD in release
  lte/gateway/fabfile.py
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: ci, size/XS, ready2merge

#11629 chore(mme): Delete dead code dupliate of time encode / decode
  lte/gateway/c/core/oai/tasks/nas/emm/msg/EmmInformation.c
  lte/gateway/c/core/oai/tasks/nas/ies/TimeZone.c
  lte/gateway/c/core/oai/tasks/nas/ies/TimeZone.h
  lte/gateway/c/core/oai/tasks/nas/ies/TimeZoneAndTime.c
  lte/gateway/c/core/oai/tasks/nas/ies/TimeZoneAndTime.h
Labels: component: agw, size/L

#11632 chore(mme): Deletes dead code dupe of voice domain encoder / decoder
  lte/gateway/c/core/oai/tasks/nas/ies/VoiceDomainPreferenceAndUeUsageSetting.c
  lte/gateway/c/core/oai/tasks/nas/ies/VoiceDomainPreferenceAndUeUsageSetting.h
Labels: component: agw, size/L

#11625 chore(ci): Disable publish of helm charts temporarily
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#11634 docs: Migration of contributers guide to Github Wiki
  docs/readmes/contributing/contribute_onboarding.md
Labels: component: docs, size/L, ready2merge

#11630 chore(mme): Deletes dead code duplicate of {en/de}code_tmsi_status
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AttachRequest.c
  lte/gateway/c/core/oai/tasks/nas/emm/msg/TrackingAreaUpdateRequest.c
  lte/gateway/c/core/oai/tasks/nas/ies/TmsiStatus.c
  lte/gateway/c/core/oai/tasks/nas/ies/TmsiStatus.h
Labels: component: agw, size/L

#11459 feat(agw): Enable Sentry monitoring for LiAgentD
  .github/workflows/build_all.yml
  lte/gateway/c/li_agent/src/BUILD.bazel
  lte/gateway/c/li_agent/src/CMakeLists.txt
  lte/gateway/c/li_agent/src/main.cpp
  orc8r/gateway/c/common/sentry/includes/SentryWrapper.h
Labels: component: agw, component: ci, size/S, ready2merge

#11622 fix(sctpd): Fix sock-addr array memory allocation
  lte/gateway/c/sctpd/src/util.cpp
Labels: component: agw, size/S

#11620 fix(orc8r): fix orc8r docker build on M1 Macs
  orc8r/cloud/docker/controller/Dockerfile
Labels: component: orc8r, size/XS

#11645 chore(mme): get rid of FD_CONF_FILE_NO_CONNECT_PEERS_CONFIGURED which…
  lte/gateway/c/core/oai/tasks/s6a/s6a_peer.c
Labels: component: agw, size/M

#11486 feat(agw): Move eBPF code to shared space
  lte/gateway/c/core/oai/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/gtpv1-u/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/gtpv1-u/ebpf_dl_map.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/ebpf/ebpf_dl_handler.c
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/ebpf/ebpf_ul_handler.c
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dl_dp.py
  lte/gateway/python/magma/pipelined/tests/test_ebpf_ul_dp.py
  orc8r/gateway/c/common/CMakeLists.txt
  orc8r/gateway/c/common/ebpf/BUILD.bazel
  orc8r/gateway/c/common/ebpf/CMakeLists.txt
  orc8r/gateway/c/common/ebpf/EbpfMap.h
  orc8r/gateway/c/common/ebpf/EbpfMapUtils.h
Labels: component: agw, size/L

#11604 chore: cleanup asn1c.bzl
  bazel/asn1c.bzl
Labels: size/M

#11641 fix(dp): fix migrations
  dp/cloud/python/magma/db_service/migrations/versions/eb8b458ab3bf_.py
Labels: size/S
