Repository magma/magma, pull requests merged in 2022-10, with the labels that each got.

#14041 chore: cache key of bazel base and image tag are updated
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/S

#14076 chore(ci): enable manual execution of the integ test magma_deb in ci
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
Labels: component: agw, size/XS

#14077 docs(agw): start-up procedure for containerized AGW is improved
  lte/gateway/docker/README.md
Labels: component: ci, size/XS

#14081 chore: delete non-existing directories from dockerignore file
  .dockerignore
Labels: size/XS

#14020 chore: deprecated debian stretch specific files and scripts are removed
  cwf/gateway/deploy/roles/cwag/tasks/main.yml
  cwf/gateway/deploy/roles/ovs/tasks/main.yml
  cwf/gateway/docker/c/Dockerfile
  lte/gateway/Vagrantfile
  lte/gateway/deploy/magma_dev.yml
  lte/gateway/deploy/magma_trfserver.yml
  lte/gateway/deploy/roles/envoy/tasks/main.yml
  lte/gateway/deploy/roles/stretch_snapshot/defaults/main.yml
  lte/gateway/deploy/roles/stretch_snapshot/tasks/main.yml
  lte/gateway/deploy/roles/uselocalpkgrepo/defaults/main.yml
  lte/gateway/deploy/roles/uselocalpkgrepo/tasks/main.yml
  lte/gateway/deploy/roles/uselocalpkgrepo/templates/99httpsrepo.j2
  lte/gateway/deploy/roles/uselocalpkgrepo/templates/repospec.list.j2
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/build-magma.sh
  orc8r/tools/ansible/roles/docker/tasks/install.yml
  orc8r/tools/ansible/roles/gateway_services/tasks/main.yml
  orc8r/tools/packer/debian-stretch-aws.json
  orc8r/tools/packer/debian-stretch-virtualbox.json
  orc8r/tools/packer/feg-ubuntu-virtualbox.json
  orc8r/tools/packer/focal-vm.json
  orc8r/tools/packer/magma-dev-aws.json
  orc8r/tools/packer/magma-dev-libvirt.json
  orc8r/tools/packer/magma-dev-virtualbox.json
  orc8r/tools/packer/magma-focal-virtualbox-patch-upgrade-ovs-1.1.20210618.json
  orc8r/tools/packer/magma-focal-virtualbox.json
  orc8r/tools/packer/magma-libvirt.seed
  orc8r/tools/packer/magma-test-aws.json
  orc8r/tools/packer/magma-test-libvirt.json
  orc8r/tools/packer/magma-test-virtualbox.json
  orc8r/tools/packer/magma-trfserver-aws.json
  orc8r/tools/packer/magma-trfserver-libvirt.json
  orc8r/tools/packer/magma.seed
  orc8r/tools/packer/scripts/ansible_debian.sh
  orc8r/tools/packer/scripts/provision-stretch.sh
  orc8r/tools/packer/scripts/setup.sh
  orc8r/tools/packer/scripts/upgrade-ovs-patch-1.1.20210618.sh
  orc8r/tools/packer/ubuntu-xenial-aws.json
Labels: component: orc8r, component: agw, component: ci, size/XXL, component: cwf

#14034 fix(lte): Fixed `detect_init_system`
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/M

#14082 fix(agw): Do not check for health of "shared_mconfig"
  orc8r/gateway/python/magma/common/health/health_service.py
Labels: component: orc8r, size/XS

#13857 chore: bump node-fetch
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/XS

#14079 fix(nms): statistics not showing for non super users
  nms/app/components/insights/GatewayMetrics.tsx
Labels: component: nms, size/XS

#14085 chore(agw): reduce python container build context
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/M, ready2merge

#14001 docs: Fix double stop of magmad in Quick Start Guide
  docs/readmes/basics/quick_start_guide.md
Labels: component: docs, size/XS

#14088 docs: Fix typo in FeG build section
  docs/readmes/feg/deploy_build.md
Labels: component: docs, size/XS

#13884 chore(ci): s1ap integ tests against dockerized agw
  .github/workflows/lte-integ-test-containerized.yml
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/L

#14092 fix: vagrant box cache location is pointing to correct folder
  .github/workflows/lte-integ-test-magma-deb.yml
Labels: component: ci, size/XS

#14091 fix(agw): fix always-true-asserts in s1ap integ tests
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_idle_active_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_mixed_idle_active_multiue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_rar_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_he.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_setsessionrules_tcp_data.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_ovs.py
Labels: component: agw, size/L, ready2merge

#14032 chore: Clean up boolean arguments in fabfiles
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/federated_tests/fabfile.py
  orc8r/tools/fab/BUILD.bazel
  orc8r/tools/fab/python_utils.py
  orc8r/tools/fab/tests/BUILD.bazel
  orc8r/tools/fab/tests/test_python_utils.py
Labels: component: orc8r, component: agw, size/L

#14097 chore: integ test workflows are reproducible
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#14072 fix(agw): Modified code to port s1ap_state_t structure to protobuf structure
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/s1ap_types.hpp
  lte/gateway/c/core/oai/tasks/grpc_service/S1apServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_common.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.hpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_handle_new_association.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers_with_injected_state.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
Labels: component: agw, size/XXL

#14112 fix(agw): Updated Magma version to 1.8.0 for upgrade script
  lte/gateway/release/upgrade_magma.sh
Labels: component: ci, size/XS

#14008 feat(agw): AGW container restart check their health status
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_multiple_service_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_secondary_pdn_with_dedicated_bearer_multiple_services_restart.py
Labels: component: agw, size/L

#13188 chore(agw): activate mypy code scanning for lte integ tests
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_non_nat_dp_ul_tcp.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_messages.py
  lte/gateway/python/magma/pipelined/pg_set_session_msg.py
Labels: component: agw, size/M

#14090 feat(ci): better startup test for the integration test against containerized AGW
  lte/gateway/docker/docker-compose.yaml
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/M

#14129 chore(ci): upgrade Github checkout action (everywhere)
  .github/workflows/agw-docker-load-test.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/amis-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/composite/docker-builder/action.yml
  .github/workflows/composite/dp-integ-tests/action.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/L

#14117 chore(ci): remove deprecated fabfile test option
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#13843 fix(agw): Modified code to replace state_teid_hash list to protobuf map in spgw task
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.hpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_context_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_config.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.cpp
  lte/gateway/c/core/oai/test/spgw_task/state_creators.cpp
Labels: component: agw, size/L

#14131 chore(ci): Add upload test results for containerized agw integ tests
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/S

#14138 fix(ci): Containerized AGW integ test
  lte/gateway/docker/docker-compose.yaml
Labels: component: ci, size/XS

#14139 feat(agw): Kill hanging containers immediatly for dockerized agw integ tests
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/XS

#14143 fix(ci): there was a bit too much deleted in #14050
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#14130 chore(ci): Clean up dead code in ci-scripts folder
  ci-scripts/JenkinsFile-CWAG-integ-test
  ci-scripts/JenkinsFile-CWAG-integ-test-libvirt
  ci-scripts/JenkinsFile-GitLab
  ci-scripts/JenkinsFile-LTE-integ-test
  ci-scripts/JenkinsFile-autolabel-pull-request
  ci-scripts/JenkinsFile-build-vagrant-boxes
  ci-scripts/adapt-mme-yaml.sed
  ci-scripts/adapt-spgwc-pool-ip.sed
  ci-scripts/adapt-spgwu-pool-ip.sed
  ci-scripts/checkCodingFormattingRules.sh
  ci-scripts/doGitLabMerge.sh
  ci-scripts/generateHtmlReport.py
  ci-scripts/post_testim_report.py
  ci-scripts/registry/aptly/deploy_image.sh
  ci-scripts/removeLastUlTestCases.sed
  ci-scripts/test_agent/FirebaseClient.py
  ci-scripts/test_agent/FirebaseConfig.json
  ci-scripts/test_agent/Tester.py
  ci-scripts/test_agent/magma_ci_agent.service
  ci-scripts/test_agent/main.py
Labels: component: ci, size/XXL, bazel-cleanup

#14093 chore: a workflow that runs integ tests vs a magma debian package build with bazel
  .github/workflows/bazel.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  lte/gateway/Vagrantfile
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/L

#14163 fix: correct action for macos slack notification is used
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
Labels: component: ci, size/S

#14070 chore(ci): Improvements for RHEL8 Docker Image Builds
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/flatten_image.py
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: ci, size/L

#14165 chore(ci): upgrade Github action setup-python
  .github/workflows/agw-docker-load-test.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/amis-workflow.yml
  .github/workflows/build_all.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/M

#14158 chore(ci): allow more granular AGW integration test execution
  lte/gateway/fabfile.py
Labels: component: agw, size/M

#14169 chore(ci): directory not used at all in federated integration tests
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/XS

#14173 refactor(ci): increase readability and resiliance for fabfile load test
  lte/gateway/fabfile.py
Labels: component: agw, size/S

#14172 fix(nms): Fix fetching of subscriber config for paginated subscribers
  nms/app/views/subscriber/SubscriberDetailConfig.tsx
Labels: component: nms, size/M

#14151 chore(ci): abstract environment preparation
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, size/S

#14166 chore: the bazel vm setup is more comfortable and documented
  docs/readmes/lte/s1ap_tests.md
  lte/gateway/deploy/magma_dev.yml
  lte/gateway/deploy/roles/bazel_aliases/tasks/main.yml
Labels: component: agw, component: docs, size/M

#14170 refactor(ci): modularize the federated integration test make command
  docs/readmes/feg/s1ap_federated_tests.md
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, component: docs, size/S

#14016 fix(pipelined): Handling for GTPU end-marker
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0025-fix-ovs-kernel-panic-on-receiving-end-marker.patch
  third_party/gtp_ovs/ovs-gtp-patches/2.15/dev.sh
Labels: type: bug, component: agw, priority: medium, size/M

#14126 chore: magma debian package meta info is enhanced
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/build-magma.sh
Labels: component: ci, DONOTLAND, size/M

#14150 chore(ci): refactor AGW integration test makefile to handle multiple manual tests correctly
  docs/readmes/feg/s1ap_federated_tests.md
  docs/readmes/lte/s1ap_tests.md
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, component: docs, size/M

#14171 fix(amf): Added t3512 configuration and registration failure handling
  lte/gateway/c/core/oai/include/amf_config.hpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GNasEnums.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_client_servicer.cpp
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/M

#13727 fix(amf): AMF support SuciProfile Encryption in Identity procedure
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
Labels: type: bug, component: agw, size/L, product: 5g sa

#14198 fix(agw): fix bug in latest `magma_dev.yml`
  lte/gateway/deploy/magma_test.yml
Labels: component: agw, size/XS

#14199 chore(agw): valid printing and cleanup for fabfile AGW
  lte/gateway/fabfile.py
Labels: component: agw, size/M

#14152 chore(ci): consistently allow for flaky retries
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, size/M

#14175 fix(ci): MME RHEL8 build from scratch was broken
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: ci, size/S

#14201 refactor(ci): multilining execution command for better readability
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, size/XS

#14188 chore(ci): attempt mitigation of flaky integration test against containerized AGW
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#14145 chore(ci): Publish unit-test results for the bazel-workflow
  .bazelrc
  .github/workflows/bazel.yml
  lte/gateway/python/scripts/runtime_report.py
Labels: component: agw, component: ci, size/M, bazel

#14183 chore(agw): cleanup agw nonsanity tests
  lte/gateway/python/integ_tests/s1aptests/test_agw_offload_idle_active_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ics_drop_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ics_failure_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py
  lte/gateway/python/integ_tests/s1aptests/test_no_auth_resp_with_mme_restart_reattach.py
  lte/gateway/python/integ_tests/s1aptests/test_no_esm_information_rsp_with_mme_restart.py
Labels: component: agw, size/M

#14204 chore(ci): upgrade Github action dorny/paths-filter (everywhere)
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/S

#14202 feat(ci): prepare integration test CI for special containerized test set
  .github/workflows/lte-integ-test-containerized.yml
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/XS

#14203 feat(ci): increase granularity of AGW integration test execution
  lte/gateway/python/integ_tests/Makefile
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/M

#14217 chore: Upgrade labstack/echo Go dependency
  cwf/cloud/go/go.mod
  cwf/cloud/go/go.sum
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
  dp/cloud/go/go.mod
  dp/cloud/go/go.sum
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  lte/cloud/go/go.mod
  lte/cloud/go/go.sum
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
Labels: component: orc8r, component: feg, size/XS, component: cwf

#14221 feat(ci): bump and pin github action in federated integ test
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/S

#14218 docs(agw): Documentation for systemd configuation
  docs/readmes/lte/dev_notes.md
Labels: component: docs, size/M

#14148 fix(agw): Converted ha task files to cpp
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/ha_messages_def.hpp
  lte/gateway/c/core/oai/include/ha_messages_types.hpp
  lte/gateway/c/core/oai/include/messages_def.h
  lte/gateway/c/core/oai/include/messages_types.h
  lte/gateway/c/core/oai/tasks/ha/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/ha/ha_defs.hpp
  lte/gateway/c/core/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/core/oai/tasks/ha/ha_task.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ha.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ha.hpp
Labels: component: agw, size/M

#14083 fix(orc8r): Stabilize cloud tests
  orc8r/cloud/go/services/state/indexer/reindex/reindexer.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_queue_test.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton.go
  orc8r/cloud/go/services/state/indexer/reindex/reindexer_singleton_test.go
Labels: component: orc8r, size/L

#14210 fix(agw): Remove speed check for GTP-U
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
Labels: component: agw, size/S, ready2merge, sentry-cleanup-python

#14224 docs: Fix warning rendering re building the AGW with Bazel
  docs/readmes/lte/s1ap_tests.md
Labels: component: docs, size/XS

#14214 feat(ci): Run most integration tests against containerized AGW on CI
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/S

#14232 fix: Do not set HOME in Dockerfile
  .devcontainer/Dockerfile
Labels: size/XS

#14230 fix(ci): fix test interdependency in test attach detach rar tcp data
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_data.py
Labels: component: agw, size/L

#14226 chore(ci): Add option to store bazel profile data to bazel.yml workflow
  .github/workflows/bazel.yml
Labels: component: ci, size/S, bazel

#14105 fix(agw): pipelined initialization dependence
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
Labels: component: agw, size/XS

#14245 fix(feg): Pin Go tools package
  feg/gateway/go.mod
  feg/gateway/go.sum
Labels: component: feg, size/XS

#14223 feat(ci): publish python sudo test results to firebase
  .github/workflows/sudo-python-tests.yml
  ci-scripts/firebase_publish_report.py
Labels: component: ci, size/S

#14240 docs: Tidy up containerized AGW instructions
  lte/gateway/docker/README.md
Labels: component: ci, size/S

#14243 feat(nms): Show NGC AMF config for gateways
  nms/app/views/equipment/GatewayDetailConfig.tsx
  nms/app/views/equipment/__tests__/GatewayConfigTest.tsx
Labels: component: nms, size/M

#14239 chore(ci): Update FEG integ test job dependency on docker build jobs
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/XS

#14177 chore(agw): Add systemd notification to mme so we can detect when the mme has restarted
  bazel/external/system_libraries.BUILD
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/deploy/roles/magma/files/systemd/magma_mme.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/magma@mme.service
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_default_bearer_with_mme_restart.py
  lte/gateway/release/deb_dependencies.bzl
Labels: component: agw, component: ci, size/M

#14251 fix(agw): copy ryu patch files to agw python container
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/XS

#14242 fix(ci): test interdependency in test_attach_detach_multiple_rar_tcp_data
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_rar_tcp_data.py
Labels: component: agw, size/XS

#14252 chore(ci): bump `actions/setup-go` version to remove deprecation warning
  .github/workflows/cloud-workflow.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/golang-build-test.yml
Labels: component: ci, size/S

#14254 chore(ci): bump `actions/cache` version to remove deprecation warning
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/M

#14256 chore(ci): bump `docker/login-action` version to remove deprecation w…
  .github/workflows/composite/docker-builder/action.yml
  .github/workflows/docker-promote.yml
Labels: component: ci, size/XS

#14255 chore(ci): bump `EnricoMi/publish-unit-test-result-action/composite` …
  .github/workflows/bazel.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/S

#14253 chore(ci): bump `actions/checkout` version to remove deprecation warning
  .github/workflows/agw-docker-load-test.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/amis-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/build_magma_dep.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/composite/docker-builder/action.yml
  .github/workflows/composite/dp-integ-tests/action.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/L

#14247 fix(ci): remove the always failing amis workflow
  .github/workflows/amis-workflow.yml
Labels: component: ci, size/L

#14260 chore(ci): bump `reviewdog/action-golangci-lint` version to remove precation warning
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/XS

#14262 chore(ci): bump `nick-invision/retry` version to remove deprecation w…
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/feg-workflow.yml
Labels: component: ci, size/XS

#14263 chore(ci): bump `peter-evans/find_comment` version to remove deprecat…
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/XS

#14261 chore(ci): bump `tspascoal/get-user-teams-membership` version to remoprecation warning
  .github/workflows/docker-promote.yml
  .github/workflows/helm-promote.yml
Labels: component: ci, size/XS

#14227 chore(ci): Reconfigure workflow triggers to push on master instead of waiting for the build-all workflow to complete
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/M

#14179 chore(agw): Fix LTE snowflake issue
  lte/gateway/docker/docker-compose.yaml
  lte/gateway/fabfile.py
  lte/gateway/python/Makefile
Labels: component: agw, component: ci, size/S

#14267 fix(ci): fix test interdependency in test_attach_detach_rar_tcp_he (#…
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_tcp_he.py
Labels: component: agw, size/XS

#14269 chore(ci): bump `action/setup-node` version to remove deprecation war…
  .github/workflows/nms-workflow.yml
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/XS

#14270 chore(ci): bump `docker/setup-qemu-action` version to remove deprecat…
  .github/workflows/golang-build-test.yml
Labels: component: ci, size/XS

#14271 chore(ci): bump `amannn/action-semantic-pull-request` version to remo…
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/XS

#14268 chore(ci): bump `docker/build-push-action` version to remove deprecat…
  .github/workflows/composite/docker-builder/action.yml
  .github/workflows/python-workflow.yml
Labels: component: ci, size/XS

#14220 feat(agw): publish LTE integ test results to firebase
  .github/workflows/lte-integ-test-magma-deb.yml
  ci-scripts/firebase_publish_report.py
Labels: component: ci, size/L

#14259 feat(nms): New edit dialog for NGC AMF config
  nms/app/views/equipment/GatewayDetailConfig.tsx
  nms/app/views/equipment/GatewayDetailConfigEdit.tsx
  nms/app/views/equipment/__tests__/GatewayConfigTest.tsx
Labels: component: nms, size/L

#14276 chore(ci): bump `geekyeggo/delete-artifact` version to remove deprecation warning
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/XS

#14277 chore(ci): bump `actions/download-artifact` version to remove deprecation warning
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/XS

#14127 chore(ci): Consolidate C/C++ coverage generation in new CI workflow
  .github/workflows/agw-coverage.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/golang-build-test.yml
Labels: component: ci, size/L, bazel

#14273 chore(ci): bump `github/codeql-action` version to remove deprecation warning
  .github/workflows/codeql-analysis.yml
Labels: component: ci, size/XS

#14275 chore(ci): remove debug-only `hmarr/debug-action`
  .github/workflows/deploy-build-from-pr.yml
Labels: component: ci, size/XS

#14281 fix(ci): use correct syntax for push event in sudo python tests
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/XS

#14280 chore: Reduce devcontainer size
  .devcontainer/Dockerfile
Labels: size/M

#14288 fix(ci): fix bug in dict iteration
  ci-scripts/firebase_publish_report.py
Labels: component: ci, size/XS

#14241 chore(ci): remove flaky integration tests from containerized AGW tests
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/S

#14289 fix(ci): install missing firebase_admin python module
  .github/workflows/lte-integ-test-magma-deb.yml
Labels: component: ci, size/XS

#14238 fix(ci): Add debug output to in order to make it easier to investiga…
  lte/gateway/deploy/roles/magma/files/systemd/magma_eventd.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/magma@eventd.service
  lte/gateway/python/integ_tests/s1aptests/test_services_are_running.py
Labels: component: agw, size/S

#14287 fix: Restore import path logic in load tests
  lte/gateway/python/load_tests/common.py
Labels: component: agw, size/S

#14301 chore(ci): Remove dead env variables in agw-workflow
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS

#14309 fix(amf): Handled Registration and Periodic Registration Failure Issues
  lte/gateway/c/core/oai/tasks/amf/amf_app_transport.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GSMobileIdentity.hpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
Labels: type: bug, component: agw, priority: medium, size/S, product: 5g sa

#14116 fix(agw): Modified code at s1ap to remove dependency on common state manager class
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/state_utility.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.hpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_manager.cpp
Labels: component: agw, size/L

#14278 fix(ci): ignore exit status from single test sets
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, size/S

#14215 chore: Introduce "util_script" and "service" Bazel tags
  .github/workflows/lte-integ-test-bazel.yml
  bazel/scripts/link_scripts_for_bazel_integ_tests.sh
  bazel/scripts/test_python_service_imports.sh
  bazel/test_constants.bzl
  feg/gateway/services/envoy_controller/BUILD.bazel
  lte/gateway/c/connection_tracker/src/BUILD.bazel
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/li_agent/src/BUILD.bazel
  lte/gateway/c/sctpd/src/BUILD.bazel
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/deploy/roles/bazel_aliases/tasks/main.yml
  lte/gateway/python/magma/enodebd/BUILD.bazel
  lte/gateway/python/magma/health/BUILD.bazel
  lte/gateway/python/magma/kernsnoopd/BUILD.bazel
  lte/gateway/python/magma/mobilityd/BUILD.bazel
  lte/gateway/python/magma/monitord/BUILD.bazel
  lte/gateway/python/magma/pipelined/BUILD.bazel
  lte/gateway/python/magma/policydb/BUILD.bazel
  lte/gateway/python/magma/redirectd/BUILD.bazel
  lte/gateway/python/magma/smsd/BUILD.bazel
  lte/gateway/python/magma/subscriberdb/BUILD.bazel
  lte/gateway/python/scripts/BUILD.bazel
  orc8r/gateway/python/magma/ctraced/BUILD.bazel
  orc8r/gateway/python/magma/directoryd/BUILD.bazel
  orc8r/gateway/python/magma/eventd/BUILD.bazel
  orc8r/gateway/python/magma/magmad/BUILD.bazel
  orc8r/gateway/python/magma/state/BUILD.bazel
  orc8r/gateway/python/scripts/BUILD.bazel
Labels: component: orc8r, component: agw, component: ci, component: feg, size/L, bazel

#14229 chore(ci): Unify workflow names
  .github/workflows/agw-docker-load-test.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/backport-pull-request.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/build_magma_dep.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docker-promote.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/helm-promote.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/pr_bot.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/sudo-python-tests.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, DONOTLAND, size/L

#14303 refactor(pipelined): Use netifaces to get mac addresses
  lte/gateway/python/magma/pipelined/BUILD.bazel
  lte/gateway/python/magma/pipelined/gw_mac_address.py
  lte/gateway/python/magma/pipelined/ifaces.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/tests/BUILD.bazel
  lte/gateway/python/magma/pipelined/tests/test_ifaces.py
Labels: component: agw, size/M

#14315 fix(ci): ntpdate makes eventd startup fail which in turn makes the integ test fail.
  lte/gateway/deploy/roles/magma/files/systemd/magma_eventd.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/magma@eventd.service
Labels: component: agw, size/XS

#14317 chore(agw): Bazelify the load_tests
  bazel/scripts/check_py_bazel.sh
  bazel/scripts/run_load_tests.sh
  lte/gateway/fabfile.py
  lte/gateway/python/load_tests/BUILD.bazel
  lte/gateway/python/load_tests/Makefile
  lte/gateway/python/load_tests/README.md
  lte/gateway/python/load_tests/defs.mk
  lte/gateway/python/load_tests/loadtest_directoryd.py
  lte/gateway/python/load_tests/loadtest_mobilityd.py
  lte/gateway/python/load_tests/loadtest_pipelined.py
  lte/gateway/python/load_tests/loadtest_policydb.py
  lte/gateway/python/load_tests/loadtest_sessiond.py
  lte/gateway/python/load_tests/loadtest_subscriberdb.py
  lte/gateway/release/BUILD.bazel
Labels: component: agw, component: ci, size/L, bazel

#14233 chore(ci): Remove sudo tests from make LTE integ test workflow
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#14266 chore(agw): Create Python environment with bazel
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  WORKSPACE.bazel
  bazel/external/requirements_README.md
  dev_tools/BUILD.bazel
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/L, bazel

#14331 test(agw): Fix broken integration test
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_non_nat_dp_ul_tcp.py
Labels: component: agw, size/XS
