Repository magma/magma, pull requests merged in 2022-11, with the labels that each got.

#14336 fix: bazel build and test verbs use same parameter order
  .github/workflows/bazel.yml
Labels: component: ci, size/XS

#14332 fix(ci): Fix upload error in agw-coverage workflow
  .github/workflows/agw-coverage.yml
Labels: component: ci, size/XS

#14327 fix(agw): Modified code to fix the issue 14244
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
Labels: component: agw, size/XS

#14337 fix(amf): Added logs for context release handling
  lte/gateway/c/core/oai/tasks/amf/amf_app_msg.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
Labels: component: agw, size/S

#14333 chore(ci): Replace to-be-deprecated set-output statement in GitHub workflow
  .github/workflows/bazel.yml
Labels: component: ci, size/XS

#14343 fix(ci): node is pinned to version 17 that can be used on xenial
  orc8r/cloud/Makefile
Labels: component: orc8r, size/XS

#14326 feat(ci): enable build Debian packages of external Magma dependencies
  third_party/build/bin/aioeventlet_build.sh
  third_party/build/bin/aioh2-build.sh
  third_party/build/bin/aioh2_build.sh
  third_party/build/bin/bcc_build.sh
  third_party/build/bin/gnutls_build.sh
  third_party/build/bin/grpc_build.sh
  third_party/build/bin/sentry-native_build.sh
Labels: component: ci, size/L

#14292 fix(agw): Create empty config before running integ tests
  orc8r/tools/fab/vagrant.py
Labels: component: orc8r, size/XS

#14328 chore(ci): reduce boilerplate code in `firebase_publish.py`
  ci-scripts/firebase_publish.py
Labels: component: ci, size/M

#14235 docs: migrate Documentation Overview from Docusaurus to Contributor Guide
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_ci_checks.md
  docs/readmes/contributing/contribute_conventions.md
  docs/readmes/contributing/contribute_github.md
  docs/readmes/contributing/contribute_id_mappings.md
  docs/readmes/contributing/contribute_vscode.md
Labels: component: docs, size/M

#14351 chore(ci): remove flaky integration tests from containerized AGW tests
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/XS

#14319 fix: ryu (and all other magma dependencies) are upgraded with magma
  lte/gateway/release/upgrade_magma.sh
Labels: component: agw, component: ci, size/XS, release-1.8-improvements

#14357 fix(amf): Periodic Registration failure
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
Labels: component: agw, size/XS

#14320 chore(ci): Remove Make jobs from AGW Lint & Test workflow that are already covered by bazel jobs
  .github/workflows/agw-workflow.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, DONOTLAND, size/L, bazel-cleanup

#14329 chore(agw): Remove Make targets that are covered by Bazel
  lte/gateway/Makefile
Labels: component: agw, size/S

#14367 fix: bazel debian handling is fixed
  .github/workflows/bazel.yml
  .github/workflows/build_magma_dep.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
Labels: component: ci, size/S

#14368 chore: Link folly dynamically in bazel by default
  .bazelrc
  bazel/bazelrcs/cwag.bazelrc
  bazel/external/system_libraries.BUILD
  lte/gateway/docker/services/c/Dockerfile
Labels: component: ci, size/M

#14360 chore: the devcontainer uses the same grpc setup as the vm
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
  lte/gateway/deploy/roles/dev_common/defaults/main.yml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/M

#14342 fix(agw): Modifed code to port hash list of ue contexts to protobuf map
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/include/sgw_context_manager.hpp
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_context_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state.cpp
  lte/gateway/c/core/oai/test/spgw_task/mock_spgw_op.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
Labels: component: agw, size/L

#14372 fix: bazel debian handling is fixed II
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
  lte/gateway/release/BUILD.bazel
Labels: component: agw, component: ci, size/XS

#14354 chore(agw): cleanup agw integtests after dockerization
  lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py
  lte/gateway/python/integ_tests/s1aptests/test_no_identity_rsp_with_mme_restart.py
Labels: component: agw, size/S

#14375 fix: missing sctpd min version file is added to magma artifact
  lte/gateway/release/BUILD.bazel
Labels: component: ci, size/S

#14376 chore: bazel magma deb content is compressed
  lte/gateway/release/BUILD.bazel
Labels: component: ci, size/S

#14321 chore(agw): Remove unused Make unit test targets from lte/gateway/Makefile
  lte/gateway/Makefile
Labels: component: agw, size/S

#14361 chore: Bazel Bash completion
  .devcontainer/post-create-commands.sh
  bazel/scripts/setup_bazel_bash_completion.sh
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/M, bazel

#14384 fix(ci): add typing import to `firebase_publish.py`
  ci-scripts/firebase_publish.py
Labels: component: ci, size/XS

#14385 fix(ci): restrict docker push to Github push event
  .github/workflows/build_all.yml
  .github/workflows/composite/docker-builder-agw/action.yml
Labels: component: ci, size/XS

#14155 fix(agw): Modified code to port s1ap_imsi_map to protobuf structure
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/s1ap_types.hpp
  lte/gateway/c/core/oai/tasks/s1ap/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.hpp
  lte/gateway/c/core/oai/test/s1ap_task/BUILD.bazel
  lte/gateway/c/core/oai/test/s1ap_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
Labels: component: agw, size/L

#14394 chore: deb integ test uses artifact from bazel workflow
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
Labels: component: ci, size/M

#14388 fix(ci): Remove dev dependencies before building release
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#14322 docs: Update docs on removed Make targets
  docs/readmes/lte/dev_notes.md
  docs/readmes/lte/dev_unit_testing.md
Labels: component: docs, size/L

#14387 docs: Switch documentation from Make to Bazel. Part I
  docs/readmes/lte/s1ap_tests.md
  docs/readmes/lte/setup.md
Labels: component: docs, size/M, bazel

#14400 chore: the module not found check is robust regarding non daemon processes
  bazel/scripts/test_python_service_imports.sh
Labels: size/XS, bazel

#14401 fix: Pass command through shell
  bazel/scripts/setup_bazel_bash_completion.sh
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, size/XS

#14397 chore(ci): improve readability in `magma_deb/tasks/main.yml`
  lte/gateway/deploy/roles/magma_deb/tasks/main.yml
Labels: component: agw, size/S

#14005 fix(agw): Modified code port hash list, temporary_create_session_procedure_id to protobuf map
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/include/sgw_s8_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.hpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test_attach_proc.cpp
Labels: component: agw, size/L

#14407 chore(agw): Remove commented out code from Vagrantfile
  lte/gateway/Vagrantfile
Labels: component: ci, size/XS

#14370 fix(magmad): Revert service restart metrics to use a Gauge
  orc8r/gateway/python/magma/magmad/metrics.py
Labels: component: orc8r, size/M

#14365 feat(ci): Build and Publish 3rd party dependencies
  .github/workflows/build_magma_dep.yml
  .github/workflows/magma-build-3rd-party.yml
  third_party/build/bin/freediameter_build.sh
  third_party/build/bin/ryu_build.sh
Labels: component: ci, size/L

#14411 refactor(ci): use filenames instead titles for dependencies
  .github/workflows/comment-pr-on-check-failure.yml
Labels: component: ci, size/XS

#14413 chore: Remove small code owner groups
  CODEOWNERS
Labels: size/XS

#14383 chore: remote cache traffic is reduced by not caching large artifacts
  lte/gateway/python/BUILD.bazel
  lte/gateway/python/scripts/BUILD.bazel
  lte/gateway/release/BUILD.bazel
  orc8r/gateway/python/BUILD.bazel
  orc8r/gateway/python/scripts/BUILD.bazel
Labels: component: orc8r, component: agw, component: ci, size/S

#14410 chore: unify indentation in Dockerfiles
  .devcontainer/Dockerfile
  feg/gateway/docker/python/Dockerfile
Labels: component: feg, size/M

#14369 chore(deps): upgrade python protobuf to latest 3.20 version
  bazel/external/requirements.in
  bazel/external/requirements.txt
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma.lockfile.ubuntu
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: ci, size/XL

#14412 chore(ci): increase consistency for Slack messages
  .github/workflows/agw-coverage.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/L

#14422 fix: metrics test is independent from execution of unrelated tests
  lte/gateway/python/integ_tests/s1aptests/test_gateway_metrics_attach_detach.py
Labels: component: agw, LTE-Integration-Test, size/XS

#14141 chore(agw): multiple magma services can be enabled/disabled at the same time
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_sctp_shutdown_while_mme_is_stopped.py
Labels: component: agw, size/L

#14424 docs: remove resolved warning in Vagrant installation
  docs/readmes/basics/prerequisites.md
Labels: component: docs, size/XS

#14425 chore: Persist bazel artifacts after VM restart
  .bazelrc
  .devcontainer/bazel-base/docker-compose.yml
  dev_tools/BUILD.bazel
Labels: component: ci, size/S, bazel

#14427 fix: class variable syntax is fixed
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, LTE-Integration-Test, size/S

#14356 fix(agw): Converted sctp task files to cpp
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/include/messages_def.h
  lte/gateway/c/core/oai/include/messages_types.h
  lte/gateway/c/core/oai/include/sctp_messages_def.hpp
  lte/gateway/c/core/oai/include/sctp_messages_types.hpp
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_itti_messaging.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.cpp
  lte/gateway/c/core/oai/tasks/sctp/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/sctp/sctp_itti_messaging.cpp
  lte/gateway/c/core/oai/tasks/sctp/sctp_itti_messaging.hpp
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.cpp
  lte/gateway/c/core/oai/tasks/sctp/sctp_primitives_server.hpp
  lte/gateway/c/core/oai/tasks/sctp/sctpd_downlink_client.cpp
  lte/gateway/c/core/oai/tasks/sctp/sctpd_downlink_client.hpp
  lte/gateway/c/core/oai/tasks/sctp/sctpd_uplink_server.cpp
Labels: component: agw, size/L

#14378 fix(amf): added n11 unit test cases
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.hpp
  lte/gateway/c/core/oai/test/n11/CMakeLists.txt
  lte/gateway/c/core/oai/test/n11/test_smf_service_client.cpp
Labels: component: agw, size/L

#14389 feat(ci): restructure the AGW docker image hash propagation to allow for forked PRs
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/build_all.yml
  .github/workflows/composite/docker-builder-agw/action.yml
Labels: component: ci, size/L

#14430 fix: cwf go files formatted with gofmt
  cwf/gateway/integ_tests/gx_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_enforcement_test.go
  cwf/gateway/integ_tests/gx_qos_restart_test.go
Labels: size/M, component: cwf

#14429 fix: feg go files formatted with gofmt
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/cloud/go/services/controller/protos/feg_config.pb.go
  feg/cloud/go/services/controller/protos/feg_config.proto
  feg/gateway/diameter/diameter_client.go
  feg/gateway/diameter/msg_definitions.go
  feg/gateway/services/aaa/aaa_server/aaa_aka_linked_auth_test.go
  feg/gateway/services/eap/providers/aka/provider/identity.go
  feg/gateway/services/eap/providers/sim/mac.go
  feg/gateway/services/eap/providers/sim/provider/identity.go
  feg/gateway/services/n7_n40_proxy/n7/notifier_handler.go
  feg/gateway/services/s6a_proxy/servicers/s6a_definitions.go
  feg/gateway/services/session_proxy/credit_control/gx/definitions.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/services/testcore/hss/servicers/auth.go
  feg/gateway/services/testcore/hss/servicers/hss_diameter_integration_test.go
  feg/gateway/services/testcore/ocs/mock_ocs/ocs.go
  feg/gateway/services/testcore/pcrf/mock_pcrf/pcrf.go
  feg/protos/mconfig/mconfigs.proto
Labels: component: feg, size/XL

#14428 fix: orc8r go files formatted with gofmt
  lte/cloud/go/protos/policydb.pb.go
  lte/cloud/go/services/eps_authentication/servicers/auth.go
  lte/cloud/go/sms_ll/sms_ll.go
  lte/protos/policydb.proto
  orc8r/cloud/go/clock/doc.go
  orc8r/cloud/go/services/accessd/protos/access_helper.go
  orc8r/cloud/go/services/accessd/servicers/protected/accessd.go
  orc8r/cloud/go/services/configurator/doc.go
  orc8r/cloud/go/services/directoryd/storage/storage_blobstore.go
  orc8r/cloud/go/services/magmad/gateway_api.go
  orc8r/cloud/go/services/obsidian/access/identity_finder.go
  orc8r/cloud/go/services/state/indexer/indexer.go
  orc8r/cloud/go/services/state/indexer/mocks/test_utils.go
  orc8r/cloud/go/services/state/indexer/reindex/queue_sql.go
  orc8r/cloud/go/tools/migrations/datastore_to_blobstore.go
  orc8r/cloud/go/tools/migrations/doc.go
  orc8r/lib/go/protos/mconfig.pb.go
  orc8r/lib/go/registry/cloud_connection.go
  orc8r/lib/go/registry/shared_cloud_conn.go
  orc8r/protos/mconfig.proto
Labels: component: orc8r, component: agw, size/L

#14353 feat(ci): Propagate AGW docker images hashes to the integration test job - receivers
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/M

#14142 feat(agw): add service function to get all magma services
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_services_are_running.py
Labels: component: agw, size/L

#14437 docs: Fixed broken link to devcontainer setup
  docs/readmes/basics/prerequisites.md
Labels: component: docs, size/XS

#14436 fix(agw): Converted service303 task files to cpp
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/messages_def.h
  lte/gateway/c/core/oai/include/messages_types.h
  lte/gateway/c/core/oai/include/service303.hpp
  lte/gateway/c/core/oai/include/service303_messages_def.hpp
  lte/gateway/c/core/oai/include/service303_messages_types.hpp
  lte/gateway/c/core/oai/tasks/service303/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/service303/service303_mme_stats.cpp
  lte/gateway/c/core/oai/tasks/service303/service303_spgw_stats.cpp
  lte/gateway/c/core/oai/tasks/service303/service303_task.cpp
Labels: component: agw, size/M

#14393 chore(mme): Build MME for the OAI-MME variant with Bazel
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: ci, size/M

#14431 docs: remove inactive HIL lab
  README.md
Labels: size/XS

#14451 chore: bazel debian artifacts are pushed to lf artifactory
  .github/workflows/bazel.yml
Labels: component: ci, size/M

#14457 Revert "chore: bazel debian artifacts are pushed to lf artifactory (#14451)"
  .github/workflows/bazel.yml
Labels: component: ci, size/M

#14461 chore(ci): Rename Bazel Debian integ test workflow
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
Labels: component: ci, size/XS

#14463 fix(ci): only workflow names work as trigger specifications
  .github/workflows/agw-docker-load-test.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/S

#14464 chore(ci): Mark spgw_procedures_with_injected_state_test as flaky in Bazel
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
Labels: component: agw, size/XS, bazel

#14006 fix(agw): Modified code to port teid has list to protobuf in sgw_s8 task
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/include/sgw_s8_state.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.hpp
Labels: component: agw, size/L

#14476 ci: upgrade nick-fields/retry
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/feg-workflow.yml
Labels: component: ci, size/XS

#14477 ci: upgrade actions/github-script
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/pr_bot.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/S

#14478 ci: upgrade docker/metadata-action
  .github/workflows/composite/docker-builder/action.yml
Labels: component: ci, size/XS

#14479 ci: upgrade docker/setup-buildx-action
  .github/workflows/composite/docker-builder/action.yml
Labels: component: ci, size/XS

#14482 fix(orc8r): pin postgres image version to 14
  orc8r/cloud/docker/docker-compose.yml
Labels: component: orc8r, size/XS

#14485 Revert "ci: upgrade actions/github-script"
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/pr_bot.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/unit-test-workflow.yml
Labels: size/S

#14480 chore(ci): Fix permission issue for bazel-base cache
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
Labels: component: ci, size/XS, bazel

#14434 chore: install only llvm version 12 in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
Labels: size/S

#14493 fix(mme): Increased TimeToLive sctp_sendmsg
  lte/gateway/c/sctpd/src/sctp_connection.cpp
  lte/gateway/c/sctpd/src/sctp_connection.hpp
Labels: component: agw, size/S

#14231 fix(orc8r): Handle absent NGC config correctly
  lte/cloud/go/services/lte/obsidian/models/conversion.go
Labels: component: orc8r, size/XS

#14496 chore(ci): Create separate buildifier and python import check jobs for Bazel
  .github/workflows/bazel.yml
Labels: component: ci, size/L, bazel

#14486 chore: bazel debian artifacts are also pushed to the LF artifactory
  .github/workflows/bazel.yml
Labels: component: ci, size/S

#14355 refactor(agw): Use netifaces to get mac addresses consistently
  bazel/external/requirements.in
  lte/gateway/python/magma/pipelined/BUILD.bazel
  lte/gateway/python/magma/pipelined/app/arp.py
  lte/gateway/python/magma/pipelined/app/check_quota.py
  lte/gateway/python/magma/pipelined/app/egress.py
  lte/gateway/python/magma/pipelined/app/middle.py
  lte/gateway/python/magma/pipelined/bridge_util.py
  lte/gateway/python/magma/pipelined/ebpf/BUILD.bazel
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/gw_mac_address.py
  lte/gateway/python/magma/pipelined/ifaces.py
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/magma/pipelined/redirect.py
  lte/gateway/python/magma/pipelined/tests/BUILD.bazel
  lte/gateway/python/magma/pipelined/tests/test_arp.py
  lte/gateway/python/magma/pipelined/tests/test_arp_non_nat.py
  lte/gateway/python/magma/pipelined/tests/test_check_quota.py
  lte/gateway/python/magma/pipelined/tests/test_cwf_restart_resilience.py
  lte/gateway/python/magma/pipelined/tests/test_gy.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_ifaces.py
  lte/gateway/python/magma/pipelined/tests/test_inout.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
  lte/gateway/python/magma/pipelined/tests/test_ue_passthrough.py
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
  lte/gateway/python/magma/pipelined/utils.py
Labels: component: agw, size/L

#14503 chore: Remove some unused Ansible vars
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
Labels: component: agw, size/S

#14504 chore: Change bazel target structure in bazel workflow
  .github/workflows/bazel.yml
  bazel/test/BUILD.bazel
  bazel/test/runfiles_test.bzl
Labels: component: ci, size/S, bazel

#14487 ci: upgrade actions/github-script
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/pr_bot.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/M

#14506 fix: update property call for github_action/github-script
  .github/workflows/autolabel-pullrequests.yml
Labels: size/XS

#14511 docs: resolve several reviewdog remarks
  cwf/gateway/integ_tests/README.md
  nms/README.md
Labels: component: nms, size/L, component: cwf

#14449 fix(agw): Converted s11 task files to cpp
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/include/messages_def.h
  lte/gateway/c/core/oai/include/messages_types.h
  lte/gateway/c/core/oai/include/s11_messages_def.hpp
  lte/gateway/c/core/oai/include/s11_messages_types.hpp
  lte/gateway/c/core/oai/include/s11_mme.hpp
  lte/gateway/c/core/oai/lib/3gpp/3gpp_23.401.h
  lte/gateway/c/core/oai/lib/gtpv2-c/gtpv2c_ie_formatter/src/gtpv2c_ie_formatter.c
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/include/NwGtpv2c.h
  lte/gateway/c/core/oai/lib/gtpv2-c/nwgtpv2c-0.11/src/NwGtpv2c.c
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_detach.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_procedures.cpp
  lte/gateway/c/core/oai/tasks/s11/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s11/s11_common.cpp
  lte/gateway/c/core/oai/tasks/s11/s11_common.hpp
  lte/gateway/c/core/oai/tasks/s11/s11_ie_formatter.cpp
  lte/gateway/c/core/oai/tasks/s11/s11_ie_formatter.hpp
  lte/gateway/c/core/oai/tasks/s11/s11_mme_bearer_manager.cpp
  lte/gateway/c/core/oai/tasks/s11/s11_mme_bearer_manager.hpp
  lte/gateway/c/core/oai/tasks/s11/s11_mme_session_manager.cpp
  lte/gateway/c/core/oai/tasks/s11/s11_mme_session_manager.hpp
  lte/gateway/c/core/oai/tasks/s11/s11_tasks.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_s11_handlers.hpp
  lte/gateway/c/core/oai/test/mock_tasks/mock_tasks.hpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.hpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_session.cpp
Labels: component: agw, size/L

#14507 chore: Do not publish build results from PRs
  .github/workflows/deploy-build-from-pr.yml
Labels: size/L

#14491 chore(ci): optimizing the OAI Ubuntu18 build pipeline stage
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/mme/docker-compose-build-ubuntu18.04.yaml
Labels: component: ci, size/L

#14249 fix(ci): Add systemd notification to all mme related services.
  bazel/external/requirements.in
  bazel/external/requirements.txt
  cwf/gateway/docker/c/Dockerfile
  lte/gateway/c/sctpd/src/BUILD.bazel
  lte/gateway/c/sctpd/src/CMakeLists.txt
  lte/gateway/c/sctpd/src/sctpd.cpp
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/deploy/roles/magma/files/systemd/magma_mobilityd.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_pipelined.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_sessiond.service
  lte/gateway/deploy/roles/magma/files/systemd/sctpd.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/magma@mobilityd.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/magma@pipelined.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/magma@sessiond.service
  lte/gateway/deploy/roles/magma/files/systemd_bazel/sctpd.service
  lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_default_bearer_with_mme_restart.py
  lte/gateway/python/magma/mobilityd/BUILD.bazel
  lte/gateway/python/magma/mobilityd/main.py
  lte/gateway/python/magma/pipelined/BUILD.bazel
  lte/gateway/python/magma/pipelined/main.py
  lte/gateway/python/setup.py
Labels: component: agw, DONOTLAND, size/M, component: cwf

#14510 fix(orc8r): pin postgres image version to 14
  orc8r/cloud/docker/docker-compose.yml
Labels: component: orc8r, size/XS

#14518 fix(amf): Increased timetolive sctp_sendmsg
  lte/gateway/c/sctpd/src/sctp_connection.cpp
Labels: component: agw, size/XS

#14520 fix(agw): Fix type hints of restart_services function
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/XS

#14517 fix(ci): typo in handling the target magma-mme image
  ci-scripts/JenkinsFile-OAI-Container-GitHub
Labels: component: ci, size/S

#14521 fix(dp): radio controller test is deleted as endpoint was removed in #13925
  dp/cloud/helm/dp/charts/domain-proxy/templates/tests/radio_controller-test.yaml
Labels: component: orc8r, size/S

#14523 chore: Check for empty input in filter_test_targets.sh
  bazel/scripts/filter_test_targets.sh
Labels: size/XS, bazel

#14530 fix(ci): Double naming for id in build job
  .github/workflows/build_all.yml
Labels: size/XS

#14532 fix(ci): Unbreak build all - Feg-build test
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#14526 chore: Remove BUILD.bazel files from src folder
  src/go/agwd/BUILD.bazel
  src/go/agwd/config/BUILD.bazel
  src/go/agwd/config/internal/grpcutil/BUILD.bazel
  src/go/agwd/config/mock_config/BUILD.bazel
  src/go/agwd/server/BUILD.bazel
  src/go/capture/BUILD.bazel
  src/go/capture/gen/BUILD.bazel
  src/go/crash/BUILD.bazel
  src/go/crash/mock_crash/BUILD.bazel
  src/go/crash/sentry/BUILD.bazel
  src/go/crash/sentry/mock_sentry/BUILD.bazel
  src/go/internal/testutil/BUILD.bazel
  src/go/log/BUILD.bazel
  src/go/log/mock_log/BUILD.bazel
  src/go/log/zap/BUILD.bazel
  src/go/protos/BUILD.bazel
  src/go/protos/magma/apn/BUILD.bazel
  src/go/protos/magma/capture/BUILD.bazel
  src/go/protos/magma/config/BUILD.bazel
  src/go/protos/magma/config/mock_config/BUILD.bazel
  src/go/protos/magma/mobilityd/BUILD.bazel
  src/go/protos/magma/orc8r/BUILD.bazel
  src/go/protos/magma/pipelined/BUILD.bazel
  src/go/protos/magma/pipelined/mock_pipelined/BUILD.bazel
  src/go/protos/magma/policydb/BUILD.bazel
  src/go/protos/magma/sctpd/BUILD.bazel
  src/go/protos/magma/sctpd/mock_sctpd/BUILD.bazel
  src/go/protos/magma/session_manager/BUILD.bazel
  src/go/protos/magma/subscriberdb/BUILD.bazel
  src/go/scripts/grpc-dialer/BUILD.bazel
  src/go/service/BUILD.bazel
  src/go/service/capture/BUILD.bazel
  src/go/service/config/BUILD.bazel
  src/go/service/mock_service/BUILD.bazel
  src/go/service/pipelined/BUILD.bazel
  src/go/service/sctpd/BUILD.bazel
Labels: size/XL, bazel

#14533 fix(ci): Avoid error creating folder twice
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#14516 fix(ci): Use internal networks for VMs
  lte/gateway/Vagrantfile
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, component: ci, size/M

#14537 chore: Make name of restart function clearer
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_modify_config_for_non_sanity.py
  lte/gateway/python/integ_tests/s1aptests/test_modify_mme_config_for_sanity.py
  lte/gateway/python/integ_tests/s1aptests/test_restore_config_after_non_sanity.py
Labels: component: agw, size/S

#14522 chore(ci): Use bazel-diff in bazel.yml
  .github/workflows/bazel.yml
Labels: component: ci, size/M, bazel

#14515 docs: Fix outdated footer #13746
  docs/docusaurus/core/Footer.js
Labels: component: docs, size/M

#14540 chore(ci): Deactivate Git advice for detached HEAD in Bazel workflow
  bazel/scripts/bazel_diff.sh
Labels: component: ci, size/XS, bazel

#14534 chore: Revert to old tagging scheme; Run on PRs
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/composite/docker-builder-agw/action.yml
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/L

#14447 feat(ci): pin devcontainer version by hash
  .devcontainer/devcontainer.json
  .github/workflows/magma-build-3rd-party.yml
Labels: component: ci, size/XS

#14543 fix(agw): Memory leak and corresponding corruption fix when restoring…
  lte/gateway/c/core/oai/tasks/nas/nas_state_converter.cpp
Labels: component: agw, size/S

#14545 chore(ci): Use new artifactory URL for third-party build
  .github/workflows/magma-build-3rd-party.yml
Labels: component: ci, size/S

#14544 fix(ci): Use internal networks for CWF dev VMs
  cwf/gateway/Vagrantfile
Labels: component: ci, size/XS

#14547 chore(cwg): Remove commented out code from Vagrantfile
  cwf/gateway/Vagrantfile
Labels: component: ci, size/XS

#14548 fix(ci): Use correct URL for new artifactory
  .github/workflows/magma-build-3rd-party.yml
Labels: component: ci, size/XS

#14418 chore(agw): add dhcp cli helper
  lte/gateway/python/magma/mobilityd/tests/BUILD.bazel
  lte/gateway/python/magma/mobilityd/tests/test_dhcp_helper_cli.py
  lte/gateway/python/scripts/BUILD.bazel
  lte/gateway/python/scripts/dhcp_helper_cli.py
  lte/gateway/python/setup.py
Labels: component: agw, size/XL

#14546 chore: Upload agwc containers to LF artifactory
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/S

#14550 fix(ci): Push third party packages to pool
  .github/workflows/magma-build-3rd-party.yml
Labels: component: ci, size/XS

#14499 chore(ci): bump `manusa/actions-setup-minikube` to use Node 16 as def…
  .github/workflows/composite/dp-integ-tests/action.yml
  .github/workflows/dp-workflow.yml
Labels: component: ci, size/XS

#14406 fix(agw): Modified code in sgw_s8 task to port ue context hash table to protobuf map
  lte/gateway/c/core/oai/include/s8_messages_types.h
  lte/gateway/c/core/oai/include/sgw_context_manager.hpp
  lte/gateway/c/core/oai/include/sgw_s8_state.hpp
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/tasks/sgw/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_context_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.hpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_converter.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.hpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/spgw_task/state_creators.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
Labels: component: agw, size/L

#14498 feat(ci): lte-integ-test-magma-deb no longer publishes results to fir…
  .github/workflows/lte-integ-test-magma-deb.yml
  ci-scripts/firebase_publish_report.py
Labels: component: ci, size/S

#14405 refactor(agw): replace scapy in gw mac address
  bazel/external/requirements.in
  bazel/external/requirements.txt
  lte/gateway/python/magma/pipelined/BUILD.bazel
  lte/gateway/python/magma/pipelined/app/BUILD.bazel
  lte/gateway/python/magma/pipelined/app/packet_parser.py
  lte/gateway/python/magma/pipelined/ebpf/BUILD.bazel
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/gw_mac_address.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
  lte/gateway/python/setup.py
Labels: component: agw, size/L

#14564 fix(ci): New job to push dummy package to trigger GPG signing
  .github/workflows/magma-push-dummy-package.yml
Labels: component: ci, size/M

#14492 chore(ci): Block cache usage for large Bazel targets
  .bazelrc
  feg/gateway/services/envoy_controller/BUILD.bazel
  lte/gateway/c/connection_tracker/src/BUILD.bazel
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/li_agent/src/BUILD.bazel
  lte/gateway/c/session_manager/BUILD.bazel
Labels: component: agw, component: feg, size/S, bazel

#14568 fix(ci): Fix working directory for dummy package
  .github/workflows/magma-push-dummy-package.yml
Labels: component: ci, size/XS

#14508 chore: all artifactory endpoints on master are switched to lf
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
  .github/workflows/dp-workflow.yml
  cwf/gateway/deploy/roles/ovs/files/magma-preferences
  cwf/gateway/docker/.prod_env
  cwf/gateway/docker/c/Dockerfile
  cwf/gateway/docker/go/Dockerfile
  cwf/gateway/docker/python/Dockerfile
  cwf/k8s/cwf_operator/docker/Dockerfile
  docs/readmes/basics/prerequisites.md
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/dev_minikube.md
  dp/cloud/helm/dp/charts/domain-proxy/values.yaml
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.community
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.custom
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.poc
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.production
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
  feg/gateway/docker/.prod_env
  feg/gateway/docker/go/Dockerfile
  feg/gateway/docker/python/Dockerfile
  hil_testing/Magma_Ansible/project/roles/upgrade-prep/tasks/main.yaml
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/files/magma-preferences
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/magma_deb/files/magma-preferences
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
  lte/gateway/deploy/roles/magma_deploy/vars/all_master.yaml
  lte/gateway/docker/ghz/Dockerfile
  lte/gateway/docker/services/c/Dockerfile
  lte/gateway/docker/services/python/Dockerfile
  lte/gateway/release/upgrade_magma.sh
  orc8r/cloud/deploy/orc8r_deployer/docker/Dockerfile
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/roles/golang/tasks/main.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/docker/controller/Dockerfile
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/gateway/docker/Dockerfile
  orc8r/gateway/go/services/magmad/service_manager/docker_controller_test.go
  orc8r/tools/ansible/roles/golang/tasks/main.yml
  orc8r/tools/ansible/roles/pkgrepo/files/jfrog.pub
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, component: agw, component: docs, component: ci, component: feg, DONOTLAND, size/L, component: cwf, artifactory

#14565 fix(ci): Fix package build if-conditions for skipped builds
  .github/workflows/bazel.yml
Labels: component: ci, size/S, bazel

#14524 fix(agw): Migrate imsi_mme_ue_id_htbl in mme_app to protobuf map
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/gateway/c/core/oai/include/mme_app_ue_context.hpp
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/emm_data_ctx.cpp
  lte/protos/oai/mme_nas_state.proto
Labels: component: orc8r, component: agw, size/L

#14582 chore: Fix if condition that determines dry-run
  .github/workflows/bazel.yml
Labels: component: ci, size/S

#14587 fix(ci): ubuntu runners are pinned to 20.04
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/agw-coverage.yml
  .github/workflows/agw-docker-load-test.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/backport-pull-request.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dco-check.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docker-promote.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/helm-promote.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/magma-build-3rd-party.yml
  .github/workflows/magma-push-dummy-package.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/pr_bot.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/L
