Repository magma/magma, pull requests merged in 2022-04, with the labels that each got.

#12298 chore(policydb): Adding load test script for policydb
  lte/gateway/python/load_tests/defs.mk
  lte/gateway/python/load_tests/loadtest_policydb.py
Labels: component: agw, size/L

#12370 chore(mme): redundant EMBEDDED_SGW precompiler statements are cleaned up
  lte/gateway/c/core/oai/tasks/sgw/pgw_config.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/spgw_config.c
Labels: component: agw, size/M, bazel-cleanup

#12376 fix(agw): Added python version requirement infromation
  lte/gateway/docker/python-precommit/README.md
  lte/gateway/python/precommit.py
Labels: component: agw, component: ci, size/XS

#12345 fix: add list Subscribers call to mock HSS
  feg/cloud/go/protos/hss_service.pb.go
  feg/gateway/go.mod
  feg/gateway/services/testcore/hss/client_api.go
  feg/gateway/services/testcore/hss/servicers/hss.go
  feg/gateway/services/testcore/hss/servicers/hss_swx_proxy_integration_test.go
  feg/gateway/services/testcore/hss/servicers/hss_test.go
  feg/gateway/services/testcore/hss/servicers/ma_test.go
  feg/gateway/services/testcore/hss/servicers/test_utils/hss_test_server.go
  feg/gateway/services/testcore/hss/storage/memory_storage.go
  feg/gateway/services/testcore/hss/storage/storage.go
  feg/gateway/tools/hss_cli/main.go
  feg/protos/hss_service.proto
Labels: component: feg, size/L

#11101 fix(mme): fixing Pipelined managed tbl0 error when mme send UE info t…
  lte/gateway/c/core/oai/lib/pipelined_client/PipelinedClientAPI.cpp
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/sessiond.yml
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_attach_dl_tcp_data_pipelined_tbl0.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_attach_ul_tcp_data_pipelined_tbl0.py
Labels: component: agw, size/L, ready2merge

#12281 feat(mme): SCTP Shutdown for NGAP
  lte/gateway/c/core/oai/tasks/ngap/include/ngap_client_servicer.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_client_servicer.cpp
  lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
Labels: component: agw, size/L, product: 5g sa

#12359 fix(dp): Configure database connection pool
  dp/cloud/helm/dp/charts/domain-proxy/README.md
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/cm.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/db_service/cm.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/cm.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/values.yaml
  dp/cloud/python/magma/configuration_controller/config.py
  dp/cloud/python/magma/configuration_controller/run.py
  dp/cloud/python/magma/db_service/config.py
  dp/cloud/python/magma/db_service/db_initialize.py
  dp/cloud/python/magma/radio_controller/config.py
  dp/cloud/python/magma/radio_controller/run.py
Labels: size/L

#12334 feat(dp): Add orc8r API for frequency preferences
  cwf/k8s/cwf_operator/go.sum
  dp/cloud/go/protos/cbsd.pb.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers_test.go
  dp/cloud/go/services/dp/obsidian/models/capabilities_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/cbsd_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/conversion.go
  dp/cloud/go/services/dp/obsidian/models/conversion_test.go
  dp/cloud/go/services/dp/obsidian/models/frequency_preferences_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/grant_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/mutable_cbsd_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/paginated_cbsds_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  dp/cloud/go/services/dp/obsidian/models/validation_test.go
  dp/cloud/go/services/dp/obsidian/to_pointer/to_pointer.go
  dp/cloud/go/services/dp/servicers/cbsd_manager.go
  dp/cloud/go/services/dp/servicers/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
  dp/protos/cbsd.proto
  dp/skaffold.yaml
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/XXL, component: cwf

#12386 fix: pin genproto to specific version to avoid envoyproxy/go-control-…
  feg/gateway/go.mod
  feg/gateway/go.sum
Labels: component: feg, size/XS

#12390 Revert "fix(mme): fixing Pipelined managed tbl0 error when mme send U…
  lte/gateway/c/core/oai/lib/pipelined_client/PipelinedClientAPI.cpp
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/sessiond.yml
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_attach_dl_tcp_data_pipelined_tbl0.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_attach_ul_tcp_data_pipelined_tbl0.py
Labels: component: agw, size/L

#12385 chore(ci): github runners have more space available
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel-cache-push.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/M, bazel

#12384 fix(nms): Downgrade material-ui/labs to fix policy edit flows tab
  nms/packages/magmalte/package.json
  nms/yarn.lock
Labels: component: nms, size/M, ready2merge

#12393 fix(dp): Fix domain-proxy image building after regression from PR #12311
  dp/skaffold.yaml
Labels: size/XS

#12375 fix(agw): Fixed CI dashboard reporting and cleanups for flaky retry support
  ci-scripts/firebase_publish_report.py
  lte/gateway/python/integ_tests/Makefile
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
Labels: component: agw, component: ci, size/L

#12374 fix(dp): Unregister CBSD on SAS reponse 103
  dp/cloud/python/magma/configuration_controller/response_processor/strategies/response_processing.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
Labels: size/L

#12286 feat(feg): support Gx/Gy interfaces request timeout configuration from mconfig
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/cloud/go/services/feg/obsidian/models/diameter_client_configs_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  feg/gateway/diameter/config.go
  feg/gateway/services/s6a_proxy/servicers/config.go
  feg/gateway/services/s6a_proxy/servicers/config_test.go
  feg/gateway/services/s6a_proxy/servicers/s6a_proxy.go
  feg/gateway/services/session_proxy/credit_control/gx/config.go
  feg/gateway/services/session_proxy/credit_control/gx/config_test.go
  feg/gateway/services/session_proxy/credit_control/gy/config.go
  feg/gateway/services/session_proxy/credit_control/gy/config_test.go
  feg/gateway/services/session_proxy/servicers/credits.go
  feg/gateway/services/session_proxy/servicers/policy.go
  feg/gateway/services/session_proxy/servicers/session_controller.go
  feg/gateway/services/session_proxy/servicers/session_controller_test.go
  feg/gateway/services/session_proxy/session_proxy/main.go
  feg/protos/mconfig/mconfigs.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  vscode-workspaces/multiroot-go.code-workspace
Labels: component: orc8r, component: nms, component: feg, size/L

#12387 fix: add partial update to mock HSS
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/testcore/hss/servicers/ai.go
  feg/gateway/services/testcore/hss/servicers/hss.go
  feg/gateway/services/testcore/hss/servicers/hss_test.go
  feg/gateway/services/testcore/hss/servicers/ma.go
  feg/gateway/services/testcore/hss/servicers/rt.go
  feg/gateway/services/testcore/hss/servicers/sa.go
  feg/gateway/services/testcore/hss/storage/memory_storage.go
  feg/gateway/services/testcore/hss/storage/storage.go
  feg/gateway/services/testcore/hss/storage/storage_integ_test.go
  feg/gateway/services/testcore/hss/storage/storage_test.go
  feg/gateway/services/testcore/hss/storage/streamer.go
Labels: component: feg, size/L

#12377 fix(ci): operator docker image artifactory push fix
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#12411 fix(dp): Fix requests migration
  dp/cloud/python/magma/db_service/migrations/versions/973291f230c3_.py
Labels: size/XS

#12033 fix(agw): Added cleanups for flaky retry support
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_security_algo_eea0_eia0.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_security_algo_eea1_eia1.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_security_algo_eea2_eia2.py
  lte/gateway/python/integ_tests/s1aptests/test_s1setup_failure_incorrect_plmn.py
  lte/gateway/python/integ_tests/s1aptests/test_s1setup_failure_incorrect_tac.py
Labels: component: agw, size/XL

#12319 fix(feg): config_test.go in session_proxy
  feg/gateway/services/session_proxy/credit_control/gx/config_test.go
  feg/gateway/services/session_proxy/credit_control/gy/config_test.go
Labels: component: feg, size/L

#12227 chore(feg): Bump go-control-plane version
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/gateway/services/envoy_controller/LICENSE.Apache-2.0
  feg/gateway/services/envoy_controller/README.md
  feg/gateway/services/envoy_controller/control_plane/control_plane.go
  feg/gateway/services/envoy_controller/servicers/envoy_controller_test.go
Labels: component: feg, size/L, component: cwf

#12415 fix: update fieldmask-utils to 0.5.0 and go-gtp to 0.8.1
  feg/gateway/go.mod
  feg/gateway/go.sum
Labels: component: feg, size/XS

#12391 fix: run FEG on Vagrant VM on federated integ test
  docs/readmes/feg/s1ap_federated_test.md
  lte/gateway/python/integ_tests/federated_tests/docker/docker-compose.override.yml
  lte/gateway/python/integ_tests/federated_tests/fabfile.py
  orc8r/tools/fab/vagrant.py
Labels: component: orc8r, component: agw, component: docs, size/L

#12077 fix(agw): Enabled flaky retry in CI
  docs/docusaurus/i18n/en.json
  docs/readmes/lte/s1ap_tests.md
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, component: docs, size/XL

#12421 chore(dp): Remove unused models
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
Labels: size/L

#12425 chore(dp): Remove outdated comments
  dp/cloud/go/active_mode_controller/internal/message_generator/sas_helpers/builder.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers.go
Labels: size/XS

#12408 fix(dp): Fix domain-proxy image build job notifications
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#12399 feat(nms): Remove Material-table and use material-table/core instead
  nms/packages/magmalte/app/components/ActionTable.js
  nms/packages/magmalte/app/components/__tests__/DashboardAlertTableTest.js
  nms/packages/magmalte/package.json
  nms/yarn.lock
Labels: component: nms, size/L

#12372 fix(dp): change response from 500 to 409 when existing serial number modified
  dp/cloud/go/services/dp/dp/main.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers_test.go
  dp/cloud/go/services/dp/servicers/cbsd_manager.go
  dp/cloud/go/services/dp/servicers/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/db/fields.go
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/go/services/dp/storage/db/table.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
  orc8r/cloud/go/sqorc/builder.go
  orc8r/cloud/go/sqorc/error_checker.go
  orc8r/cloud/go/sqorc/error_checker_test.go
Labels: component: orc8r, size/L

#12352 chore: update golang-linter to version 1.45.0
  .github/workflows/dp-workflow.yml
  feg/gateway/Makefile
  lte/cloud/go/services/subscriberdb/digest.go
  orc8r/cloud/Makefile
  orc8r/cloud/go/obsidian/access/tests/rest_middleware_test.go
Labels: component: orc8r, component: ci, component: feg, size/S, ready2merge

#12419 Revert "chore: rules python is upgraded (#12325)"
  WORKSPACE.bazel
  bazel/BUILD.bazel
  bazel/python_dependencies.bzl
  bazel/python_toolchain.bzl
  experimental/bazel-base/Dockerfile
Labels: size/M, bazel

#12366 chore: update disclosure address from security@magmacore.org to security@lists.magmacore.org
  SECURITY.md
Labels: size/XS, ready2merge

#12436 fix(dp): Use paginated logs in GET logs
  dp/cloud/go/services/dp/obsidian/models/paginated_logs_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/L

#12409 chore: Shared code ownership for orc8r Python files
  CODEOWNERS
Labels: size/XS, ready2merge

#12428 ci(dp): Test alembic migration downgrade in database migration check
  .github/workflows/dp-workflow.yml
  dp/cloud/python/magma/db_service/migrations/versions/973291f230c3_.py
Labels: component: orc8r, component: ci, size/XS

#12305 fix(ci): Fix codecov_src_go by specifying go version
  .github/workflows/golang-build-test.yml
Labels: component: ci, size/XS

#12438 fix(agw): support agwc over arm64
  lte/gateway/deploy/agw_install_docker.sh
  lte/gateway/deploy/roles/agw_docker/files/agw_upgrade.sh
  lte/gateway/deploy/roles/agw_docker/tasks/main.yml
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/deploy/roles/magma_deploy/files/magma-bridge-reset.sh
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
  lte/gateway/docker/docker-compose.yaml
Labels: component: agw, component: ci, size/L

#12445 chore(dp): Unify null and non null types behavior on insert
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/db/fields.go
  dp/cloud/go/services/dp/storage/db/types.go
  dp/cloud/go/services/dp/storage/models.go
Labels: size/M

#12444 fix(enodebd): Set device cfg serial from Inform
  lte/gateway/python/magma/enodebd/state_machines/acs_state_utils.py
Labels: component: agw, size/XS

#12443 feat(enodebd): Add new Baicells models to QRTB
  lte/gateway/python/magma/enodebd/devices/device_utils.py
Labels: component: agw, size/XS

#12418 chore(smsd): smsd is bazelified
  lte/gateway/python/magma/smsd/BUILD.bazel
  lte/protos/BUILD.bazel
Labels: component: agw, size/M, bazel

#12452 chore(dp): Move sql types out of value types
  dp/cloud/go/services/dp/storage/db/fields.go
  dp/cloud/go/services/dp/storage/db/finishing.go
  dp/cloud/go/services/dp/storage/db/join.go
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/go/services/dp/storage/db/table.go
  dp/cloud/go/services/dp/storage/db/types.go
  dp/cloud/go/services/dp/storage/models.go
Labels: size/L

#12454 feat(enodebd): Baicells QRTB firmware upgrade
  lte/gateway/configs/enodebd.yml
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb.py
  lte/gateway/python/magma/enodebd/state_machines/acs_state_utils.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/tests/BUILD.bazel
  lte/gateway/python/magma/enodebd/tests/baicells_qrtb_tests.py
  lte/gateway/python/magma/enodebd/tr069/models.py
Labels: component: agw, size/L

#12468 chore(dp): Rename "is_updated" flag to "should_deregister"
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator.go
  dp/cloud/go/active_mode_controller/internal/message_generator/message_generator_test.go
  dp/cloud/go/active_mode_controller/protos/active_mode/active_mode.pb.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/db_service/migrations/versions/9cd338f28663_.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/active_mode_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/db_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
  dp/protos/active_mode.proto
Labels: size/L

#12473 refactor: all bazel testonly variables are set to True
  lte/gateway/c/core/oai/test/spgw_task/data/BUILD.bazel
Labels: component: agw, size/XS, ready2merge, bazel

#12469 feat(dp): Filtering cbsd by serial number
  dp/cloud/go/protos/cbsd.pb.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers.go
  dp/cloud/go/services/dp/obsidian/cbsd/handlers_test.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  dp/cloud/go/services/dp/servicers/cbsd_manager.go
  dp/cloud/go/services/dp/servicers/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
  dp/protos/cbsd.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/L

#12475 docs(agw): Deprecate approvers-agw-(c,python), approvers-showtech and approvers-openwrt teams
  CODEOWNERS
Labels: size/S

#12467 refactor(dp): Separate field values from metadata
  dp/cloud/go/services/dp/storage/db/fields.go
  dp/cloud/go/services/dp/storage/db/finishing.go
  dp/cloud/go/services/dp/storage/db/join.go
  dp/cloud/go/services/dp/storage/db/models.go
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/go/services/dp/storage/db/table.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
Labels: size/XL

#12479 chore(dp): Require explicit join
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/db/join.go
  dp/cloud/go/services/dp/storage/db/query.go
  dp/cloud/go/services/dp/storage/db/query_test.go
Labels: size/M

#12489 docs: fix link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, ready2merge

#11849 refactor(orc8r): Split health to protected and southbound
  feg/cloud/go/services/health/health/main.go
  feg/cloud/go/services/health/reporter/network_health_reporter.go
  feg/cloud/go/services/health/servicers/health_test_service.go
  feg/cloud/go/services/health/servicers/protected/health.go
  feg/cloud/go/services/health/servicers/southbound/config.go
  feg/cloud/go/services/health/servicers/southbound/health.go
Labels: component: feg, size/L

#12491 ci(orc8r): Removed spirent and teravm from CI
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#10613 chore(agw): enable IPv6 for UE and S1 networking
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/configs/mme.yml
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/M

#11852 refactor(orc8r): Split Metricsd to protected and southbound
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  feg/gateway/go.sum
  orc8r/cloud/go/services/metricsd/metricsd/main.go
  orc8r/cloud/go/services/metricsd/servicers/protected/servicer.go
  orc8r/cloud/go/services/metricsd/servicers/protected/servicer_protected_test.go
  orc8r/cloud/go/services/metricsd/servicers/servicer_internal_test.go
  orc8r/cloud/go/services/metricsd/servicers/southbound/servicer.go
  orc8r/cloud/go/services/metricsd/servicers/southbound/servicer_southbound_test.go
  orc8r/cloud/go/services/metricsd/test_common/utils.go
  orc8r/cloud/test/go.sum
Labels: component: orc8r, component: feg, size/XL, component: cwf

#12471 chore: kernsnoopd tests are refactored and executed
  lte/gateway/python/defs.mk
  lte/gateway/python/magma/kernsnoopd/handlers.py
  lte/gateway/python/magma/kernsnoopd/tests/byte_counter_tests.py
Labels: component: agw, size/L, ready2merge, bazel-cleanup

#12503 chore: bazelified python services are tested for missing modules
  .github/workflows/bazel.yml
  bazel/scripts/test_python_service_imports.sh
Labels: component: ci, size/L

#12513 chore(dp): Allow using table alias in dp orc8r db framework
  dp/cloud/go/services/dp/storage/db/fields.go
  dp/cloud/go/services/dp/storage/db/finishing.go
  dp/cloud/go/services/dp/storage/db/join.go
  dp/cloud/go/services/dp/storage/db/models.go
  dp/cloud/go/services/dp/storage/db/query.go
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/go/services/dp/storage/db/table.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
Labels: size/XL

#12501 Adapt LTE Integ Test VM resources to macOS runners
  .github/workflows/lte-integ-test.yml
  lte/gateway/Vagrantfile
Labels: component: ci, size/XS

#12518 chore(dp): Make relation property level instead of table level
  dp/cloud/go/services/dp/storage/db/fields.go
  dp/cloud/go/services/dp/storage/db/models.go
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/go/services/dp/storage/db/table.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
Labels: size/M

#12520 Revert "Adapt LTE Integ Test VM resources to macOS runners (#12501)"
  .github/workflows/lte-integ-test.yml
  lte/gateway/Vagrantfile
Labels: component: ci, size/XS

#12431 chore(orc8r): upgrade orc8r ansible files to use Go 1.18
  orc8r/cloud/deploy/roles/golang/defaults/main.yml
  orc8r/tools/ansible/roles/golang/defaults/main.yml
Labels: component: orc8r, DONOTLAND, size/XS

#12515 feat(orc8r): Added terraform locals block for specifying region
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
Labels: component: orc8r, size/XS

#12523 Revert "chore(orc8r): upgrade orc8r ansible files to use Go 1.18"
  orc8r/cloud/deploy/roles/golang/defaults/main.yml
  orc8r/tools/ansible/roles/golang/defaults/main.yml
Labels: component: orc8r, size/XS

#12510 chore: update envoy config file to use API v3
  lte/gateway/deploy/roles/magma/files/envoy.yaml
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
  lte/gateway/python/magma/pipelined/tests/envoy-tests/envoy-cntr-prod.yaml
Labels: component: agw, size/M

#12525 chore: add a utility script to generate compilation db with Bazel
  dev_tools/apply-iwyu.sh
  dev_tools/gen_compilation_database.py
Labels: size/L

#12527 fix(agw): Specify import path on run-tests ghz ansible playbook
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/run-tests.yaml
Labels: size/XS

#12517 chore: kernsnoopd is bazelified
  lte/gateway/python/magma/kernsnoopd/BUILD.bazel
  lte/gateway/python/magma/kernsnoopd/tests/BUILD.bazel
Labels: component: agw, size/M, bazel

#12534 chore(mme): renames MetricsRegistry cpp header to hpp
  orc8r/gateway/c/common/service303/BUILD.bazel
  orc8r/gateway/c/common/service303/CMakeLists.txt
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
  orc8r/gateway/c/common/service303/includes/MetricsRegistry.hpp
  orc8r/gateway/c/common/service303/includes/MetricsSingleton.hpp
  orc8r/gateway/c/common/service303/test/test_metrics.cpp
Labels: component: agw, size/S

#12535 chore(mme): renames spgw_procedures_test_fixture -> hpp
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.hpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_session.cpp
Labels: component: agw, size/S

#12254 ci: add mypy reviewdog linter
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/M

#12403 docs(agw): update network probe documentation
  docs/docusaurus/sidebars.json
  docs/readmes/howtos/network_probe.md
Labels: component: docs, size/L

#12508 chore(mme): Removes include of bits/stdc++.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ueip_imsi_map.h
Labels: component: agw, size/XS

#12264 fix(orc8r): Fixed simple gateway registration cli
  orc8r/cloud/go/services/bootstrapper/servicers/registration/registration.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/registration_test.go
  orc8r/gateway/python/scripts/register.py
Labels: component: orc8r, size/M

#12542 chore: apply IWYU to liagent
  dev_tools/iwyu.imp
  lte/gateway/c/li_agent/src/InterfaceMonitor.cpp
  lte/gateway/c/li_agent/src/InterfaceMonitor.hpp
  lte/gateway/c/li_agent/src/MobilitydClient.cpp
  lte/gateway/c/li_agent/src/MobilitydClient.hpp
  lte/gateway/c/li_agent/src/PDUGenerator.cpp
  lte/gateway/c/li_agent/src/PDUGenerator.hpp
  lte/gateway/c/li_agent/src/ProxyConnector.hpp
  lte/gateway/c/li_agent/src/main.cpp
  lte/gateway/c/li_agent/src/test/BUILD.bazel
  lte/gateway/c/li_agent/src/test/CMakeLists.txt
  lte/gateway/c/li_agent/src/test/Consts.hpp
  lte/gateway/c/li_agent/src/test/LIAgentdMocks.hpp
  lte/gateway/c/li_agent/src/test/test_pdu_generator.cpp
  orc8r/gateway/c/common/service303/MetricsSingleton.cpp
Labels: component: agw, size/L

#12524 ci: Adapt LTE Integ Test VM resources to macOS runners
  .github/workflows/lte-integ-test.yml
  lte/gateway/Vagrantfile
Labels: component: ci, size/XS

#12506 chore(mme): fixup non full path inlcudes in ebpf
  lte/gateway/python/magma/pipelined/ebpf/ebpf_dl_handler.c
  lte/gateway/python/magma/pipelined/ebpf/ebpf_ul_handler.c
Labels: component: agw, size/XS

#12291 chore(ci): remove unstable bash code in favour of Github actions
  .github/workflows/python-workflow.yml
Labels: component: ci, size/S

#12543 chore: Generate compile_commands.json on devcontainer creation
  .devcontainer/post-create-commands.sh
Labels: size/XS

#12539 chore(ci): bazel workflows use the bazel base image
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/M, bazel

#12484 docs: correct link to community page in README
  README.md
Labels: size/XS

#12538 chore(dp): Move desired state from active mode config to cbsd
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/configuration_controller/tests/unit/test_dp_logs.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_request_consumer.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
  dp/cloud/python/magma/db_service/migrations/versions/e793671a19a6_.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/services/dp/service.py
  dp/cloud/python/magma/radio_controller/services/radio_controller/service.py
  dp/cloud/python/magma/radio_controller/tests/test_utils/db_cbsd_builder.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_active_mode_controller_service.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_dp_logs.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_dp_service.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_radio_controller_service.py
Labels: size/L

#12492 fix(mme): check entire supported TA list
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_ta.c
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_s1setup_success_secondary_plmn.py
Labels: component: agw, size/L

#12488 fix(amf): PDU-Reject message is not proper for UnsupportedDNN cause s…
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
Labels: component: agw, priority: medium, size/S, product: 5g sa, ready2merge

#12548 fix(ci): bazel-cache-push.yml has enough memory for build
  .bazelrc
  .github/workflows/bazel-cache-push.yml
Labels: component: ci, size/S, bazel

#12556 fix(ci): iwyu build in devcontainer is fixed
  .devcontainer/Dockerfile
Labels: size/XS

#12394 feat(nms): Add Organization edit and detail page
  nms/packages/magmalte/app/components/DataGrid.js
  nms/packages/magmalte/app/components/FormField.js
  nms/packages/magmalte/fbc_js_core/ui/components/ActionTable.js
  nms/packages/magmalte/fbc_js_core/ui/components/design-system/FormField/FormField.js
  nms/packages/magmalte/fbc_js_core/ui/host/OrganizationDialog.js
  nms/packages/magmalte/fbc_js_core/ui/host/OrganizationEdit.js
  nms/packages/magmalte/fbc_js_core/ui/host/OrganizationInfoDialog.js
  nms/packages/magmalte/fbc_js_core/ui/host/OrganizationSummary.js
  nms/packages/magmalte/fbc_js_core/ui/host/OrganizationUserDialog.js
  nms/packages/magmalte/fbc_js_core/ui/host/OrganizationUsersTable.js
  nms/packages/magmalte/fbc_js_core/ui/host/Organizations.js
  nms/packages/magmalte/fbc_js_core/ui/theme/colors.js
  nms/packages/magmalte/fbc_js_core/ui/theme/default.js
Labels: component: nms, size/XXL

#12430 feat(nms): Redesign popover and account settings
  nms/packages/magmalte/app/components/AccountSettings.js
  nms/packages/magmalte/app/components/FormField.js
  nms/packages/magmalte/app/components/NetworkSelector.js
  nms/packages/magmalte/app/components/__tests__/AccountSettings-test.js
  nms/packages/magmalte/app/e2e/__tests__/FegLte-test.js
  nms/packages/magmalte/fbc_js_core/ui/components/NavListItem.js
  nms/packages/magmalte/fbc_js_core/ui/components/Popout.js
  nms/packages/magmalte/fbc_js_core/ui/components/ProfileButton.js
  nms/packages/magmalte/fbc_js_core/ui/components/layout/AppSideBar.js
  nms/packages/magmalte/fbc_js_core/ui/context/AppContext.js
Labels: component: nms, size/L

#12530 chore(cwg): removing vulnerable github.com/moby/moby package version
  cwf/k8s/cwf_operator/go.mod
Labels: size/XS, ready2merge, component: cwf

#12511 docs: add DCO.md, with content from https://developercertificate.org/
  CONTRIBUTING.md
  DCO.md
Labels: size/M, ready2merge

#12560 fix(agw): Update pylint to 2.12.2
  lte/gateway/python/Makefile
Labels: component: agw, size/XS, ready2merge

#12558 fix(agw): Get rid of old registries (#12549)
  orc8r/tools/ansible/roles/pkgrepo/files/jfrog.pub
  orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
  orc8r/tools/ansible/roles/pkgrepo/tasks/redhat.yml
Labels: component: orc8r, size/L

#12561 chore(mobilityd): remove unused dependency in bazel
  bazel/external/requirements.in
  bazel/external/requirements.txt
  lte/gateway/python/magma/mobilityd/BUILD.bazel
Labels: component: agw, size/S, ready2merge, bazel

#12551 docs: fix failing command in CI
  docs/docusaurus/create_docusaurus_website.sh
Labels: component: docs, size/XS

#12382 ci: stale bot is far to agressive
  .github/stale.yml
Labels: size/M

#12568 Revert "fix(agw): Get rid of old registries (#12549) (#12558)"
  orc8r/tools/ansible/roles/pkgrepo/files/jfrog.pub
  orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
  orc8r/tools/ansible/roles/pkgrepo/tasks/redhat.yml
Labels: component: orc8r, size/L

#12562 fix(nms): Fix SubscriberStateTable details are always empty
  nms/app/views/subscriber/SubscriberStateTable.js
Labels: component: nms, size/XS

#12537 feat(nms): Expand sidebar on hover
  nms/app/components/IndexWithoutNetwork.js
  nms/app/components/NetworkSelector.js
  nms/app/components/cwf/CWFSections.js
  nms/app/components/feg/FEGSections.js
  nms/app/components/host/Index.js
  nms/app/components/layout/SectionLinks.js
  nms/app/components/layout/SectionRoutes.js
  nms/app/components/layout/__tests__/useSections-test.js
  nms/app/components/lte/LteSections.js
  nms/app/components/main/ErrorLayout.js
  nms/app/components/main/Index.js
  nms/fbc_js_core/ui/components/NavListItem.js
  nms/fbc_js_core/ui/components/Popout.js
  nms/fbc_js_core/ui/components/ProfileButton.js
  nms/fbc_js_core/ui/components/SidebarItem.js
  nms/fbc_js_core/ui/components/__tests__/ProfileButton-test.js
  nms/fbc_js_core/ui/components/layout/AppSideBar.js
  nms/fbc_js_core/ui/components/layout/ExpandButton.js
  nms/fbc_js_core/ui/components/layout/__tests__/AppSideBar-test.js
  nms/fbc_js_core/ui/hooks/useRouter.js
  nms/fbc_js_core/ui/stories/mui-components/appSideBar.stories.js
  nms/fbc_js_core/ui/stories/mui-components/layout.stories.js
Labels: component: nms, size/XXL

#12293 ci: reviewdog filter consolidation
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/L

#12516 fix(orc8r): make polling for service specs parallel
  orc8r/cloud/go/obsidian/swagger/poll.go
  orc8r/cloud/go/obsidian/swagger/spec/testdata/configs/empty.yml
  orc8r/cloud/go/parallel/map.go
Labels: component: orc8r, size/M

#12446 refactor(nms): Remove remaining usages of @fbcnms
  nms/.flowconfig
  nms/.sequelizerc
  nms/README.md
  nms/fbc_js_core/alarms/README.md
  nms/fbc_js_core/sequelize_models/README.md
  nms/jest.config.js
  nms/nodemon.json
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/L

#12383 fix(nms): Initially load count of subscribers correctly
  nms/app/components/context/SubscriberContext.js
  nms/app/components/lte/LteContext.js
  nms/app/state/lte/SubscriberState.js
  nms/app/views/network/NetworkKPIs.js
  nms/app/views/network/__tests__/NetworkTest.js
  nms/app/views/subscriber/__tests__/SubscriberAddEditTest.js
  nms/app/views/subscriber/__tests__/SubscriberTest.js
Labels: component: nms, size/S, ready2merge

#12586 docs: Fix typos in Test Access Gateway
  docs/readmes/lte/dev_unit_testing.md
Labels: component: docs, size/XS

#12584 fix(ci): py linter only runs on added or modified files (not on deleted)
  .github/workflows/python-workflow.yml
Labels: component: ci, size/XS

#12502 refactor(nms): Consolidate text components
  nms/app/components/GatewayCellularFields.js
  nms/app/components/GatewaySummaryFields.js
  nms/app/components/Gateways.js
  nms/app/components/Subscribers.js
  nms/app/components/UsersSettings.js
  nms/app/components/VersionTooltip.js
  nms/app/components/admin/userManagement/UsersSettings.js
  nms/app/components/cwf/CWFGatewayConfigFields.js
  nms/app/components/insights/AsyncMetric.js
  nms/app/components/insights/Metrics.js
  nms/app/components/insights/NetworkMetrics.js
  nms/app/components/lte/Enodebs.js
  nms/app/components/network/PoliciesConfig.js
  nms/app/components/network/PolicyFlowFields.js
  nms/app/components/network/UpgradeConfig.js
  nms/app/components/rhino/MultiMetrics.js
  nms/app/views/equipment/GatewayDetailConfigEdit.js
  nms/app/views/equipment/UpgradeTiersDialog.js
  nms/app/views/metrics/CloudMetrics.js
  nms/app/views/subscriber/SubscriberApnStaticIpsEdit.js
  nms/fbc_js_core/ui/components/ActionTable.js
  nms/fbc_js_core/ui/components/Alert/Alert.js
  nms/fbc_js_core/ui/components/SnackbarItem.js
  nms/fbc_js_core/ui/components/auth/LoginForm.js
  nms/fbc_js_core/ui/components/design-system/Button.js
  nms/fbc_js_core/ui/components/design-system/FormField/FormField.js
  nms/fbc_js_core/ui/components/design-system/Input/InputAffix.js
  nms/fbc_js_core/ui/components/design-system/Input/TextInput.js
  nms/fbc_js_core/ui/components/design-system/Select/Select.js
  nms/fbc_js_core/ui/components/design-system/Select/SelectMenuItem.js
  nms/fbc_js_core/ui/components/design-system/Text.js
  nms/fbc_js_core/ui/components/design-system/helpers/TextPairingContainer.js
  nms/fbc_js_core/ui/host/OrganizationEdit.js
  nms/fbc_js_core/ui/host/OrganizationUsersTable.js
  nms/fbc_js_core/ui/host/Organizations.js
Labels: component: nms, size/L

#12574 fix(orc8r): Allow updating QoS profiles
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers_test.go
  lte/cloud/go/services/policydb/obsidian/models/conversion.go
Labels: component: orc8r, size/M, ready2merge

#12570 fix(ci): Latest fixes from Eurecom Infrastructure changes
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  ci-scripts/flatten_image.py
  ci-scripts/generateHtmlReport-OAI-pipeline.py
Labels: component: ci, size/L

#12504 fix(orc8r): Upgrade docker tags on helm charts
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/values.yaml
Labels: component: orc8r, size/S, backport-v1.7

#12594 chore: Address or remove all sessiond TODOs assigned to themarwhal
  lte/gateway/c/session_manager/ChargingGrant.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionState.hpp
Labels: component: agw, size/XS

#12592 chore: clean out TODOs owned by themarwhal
  bazel/cpp_repositories.bzl
  bazel/external/cpp_redis.BUILD
  bazel/third_party_repositories.bzl
  feg/gateway/services/aaa/protos/BUILD.bazel
  lte/gateway/c/core/oai/lib/bstr/BUILD.bazel
  lte/gateway/c/core/oai/lib/directoryd/BUILD.bazel
  lte/gateway/c/core/oai/lib/event_client/BUILD.bazel
  orc8r/gateway/c/common/async_grpc/BUILD.bazel
  orc8r/gateway/c/common/config/BUILD.bazel
  orc8r/gateway/c/common/ebpf/BUILD.bazel
  orc8r/gateway/c/common/eventd/BUILD.bazel
  orc8r/gateway/c/common/logging/BUILD.bazel
  orc8r/gateway/c/common/sentry/BUILD.bazel
  orc8r/gateway/c/common/service303/BUILD.bazel
  orc8r/gateway/c/common/service_registry/BUILD.bazel
Labels: component: agw, component: feg, size/M, bazel

#12597 fix(orc8r): Orc8r version fix for CI Job
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
Labels: component: orc8r, size/XS

#12477 fix(agw): fix secondary interface config for agwc
  lte/gateway/deploy/agw_install_docker.sh
  lte/gateway/docker/docker-compose.yaml
Labels: component: agw, component: ci, size/S

#12602 fix(ci): ovs is pinned to be less than 2.17.0
  lte/gateway/python/setup.py
Labels: component: agw, size/XS

#12505 refactor(nms): Consolidate themes
  nms/app/components/__tests__/AccountSettings-test.js
  nms/app/components/__tests__/Gateways-test.js
  nms/app/components/cwf/__tests__/CWFGateways-test.js
  nms/app/components/feg/__tests__/FEGGatewaysTest.js
  nms/app/components/insights/alarms/__tests__/Alarms-test.js
  nms/app/components/insights/logs/Logs.js
  nms/app/theme/default.js
  nms/app/views/equipment/__tests__/EnodebDetailMainTest.js
  nms/app/views/equipment/__tests__/EquipmentEnodebTest.js
  nms/app/views/equipment/__tests__/EquipmentGatewayPoolTest.js
  nms/app/views/equipment/__tests__/EquipmentGatewayTest.js
  nms/app/views/equipment/__tests__/FEGEquipmentGatewayTest.js
  nms/app/views/equipment/__tests__/FEGGatewayConnectionStatusTest.js
  nms/app/views/equipment/__tests__/FEGGatewayDetailConfigTest.js
  nms/app/views/equipment/__tests__/FEGGatewayDetailStatusTest.js
  nms/app/views/equipment/__tests__/FEGGatewayDetailSubscribersTest.js
  nms/app/views/equipment/__tests__/FEGGatewaySummaryTest.js
  nms/app/views/equipment/__tests__/GatewayLogsTest.js
  nms/app/views/network/__tests__/FEGServicingAccessGatewayTableTest.js
  nms/app/views/traffic/__tests__/ApnAddTest.js
  nms/app/views/traffic/__tests__/PolicyAddEditTest.js
  nms/app/views/traffic/__tests__/TrafficOverviewTest.js
  nms/fbc_js_core/alarms/components/alertmanager/FiringAlerts.js
  nms/fbc_js_core/alarms/components/alertmanager/Receivers/ConfigEditor.js
  nms/fbc_js_core/alarms/components/table/SimpleTable.js
  nms/fbc_js_core/alarms/components/table/__tests__/SimpleTable-test.js
  nms/fbc_js_core/alarms/test/testHelpers.js
  nms/fbc_js_core/alarms/theme/alerts.js
  nms/fbc_js_core/alarms/theme/colors.js
  nms/fbc_js_core/alarms/theme/default.js
  nms/fbc_js_core/alarms/theme/symphony.js
  nms/fbc_js_core/ui/components/NoNetworksMessage.js
  nms/fbc_js_core/ui/components/SnackbarItem.js
  nms/fbc_js_core/ui/components/__tests__/ProfileButton-test.js
  nms/fbc_js_core/ui/components/design-system/Button.js
  nms/fbc_js_core/ui/components/design-system/Checkbox/Checkbox.js
  nms/fbc_js_core/ui/components/design-system/FormField/FormField.js
  nms/fbc_js_core/ui/components/design-system/Input/InputAffix.js
  nms/fbc_js_core/ui/components/design-system/Input/TextInput.js
  nms/fbc_js_core/ui/components/design-system/Select/MenuBase.js
  nms/fbc_js_core/ui/components/design-system/Select/Select.js
  nms/fbc_js_core/ui/components/design-system/Select/SelectMenuItem.js
  nms/fbc_js_core/ui/components/design-system/Select/SelectSearchInput.js
  nms/fbc_js_core/ui/components/layout/AppDrawerProjectNavigation.js
  nms/fbc_js_core/ui/host/OrganizationDialog.js
  nms/fbc_js_core/ui/host/Organizations.js
  nms/fbc_js_core/ui/theme/alerts.js
  nms/fbc_js_core/ui/theme/colors.js
  nms/fbc_js_core/ui/theme/default.js
  nms/fbc_js_core/ui/theme/symphony.js
Labels: component: nms, size/XXL

#12600 fix(dp): adjust total cbsd count to reflect filtered cbsds
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
Labels: size/S

#12591 feat(dp): migration tests framework + poc test
  dp/cloud/python/magma/configuration_controller/tests/unit/test_request_consumer.py
  dp/cloud/python/magma/db_service/migrations/alembic.ini
  dp/cloud/python/magma/db_service/migrations/env.py
  dp/cloud/python/magma/db_service/tests/alembic_testcase.py
  dp/cloud/python/magma/db_service/tests/db_testcase.py
  dp/cloud/python/magma/db_service/tests/local_db_test_case.py
  dp/cloud/python/magma/db_service/tests/unit/test_b0cad5321c88.py
  dp/cloud/python/magma/test_runner/tests/test_active_mode_controller.py
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
Labels: size/L

#12080 fix(orc8r): upgraded grafana version to 6.7.6
  orc8r/cloud/helm/orc8r/charts/metrics/values.yaml
Labels: component: orc8r, size/XS

#12412 fix(ci): operator docker image artifactory push fix master branch
  .github/workflows/build_all.yml
Labels: component: ci, size/XS
