Repository magma/magma, pull requests merged in 2022-09, with the labels that each got.

#13797 fix(agw): added missing the ansible tags for arm variable
  lte/gateway/deploy/roles/agw_docker/tasks/main.yml
Labels: component: agw, size/XS

#13798 fix(agw): updated debian repo for 1.8.0 release
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
Labels: component: agw, size/XS

#13756 fix(agw): updated focal-ci to focal-1.8.0
  lte/gateway/docker/services/c/Dockerfile
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/XS

#13581 refactor(enodebd): package code for enodebd devices
  dp/cloud/python/magma/__init__.py
  lte/gateway/python/magma/enodebd/devices/BUILD.bazel
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb/BUILD.bazel
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb/__init__.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb/data_model.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb/impl.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb/params.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb/states.py
  lte/gateway/python/magma/enodebd/devices/device_map.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one/BUILD.bazel
  lte/gateway/python/magma/enodebd/devices/freedomfi_one/__init__.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one/data_model.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one/impl.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one/params.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one/states.py
  lte/gateway/python/magma/enodebd/tests/BUILD.bazel
  lte/gateway/python/magma/enodebd/tests/baicells_qrtb_tests.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
  lte/gateway/python/magma/enodebd/tests/get_params_tests.py
Labels: component: orc8r, component: agw, size/XXL

#13742 fix(agw): updated env.j2 file on master branch
  docs/readmes/lte/deploy_install_docker.md
  lte/gateway/deploy/agw_install_docker.sh
  lte/gateway/deploy/roles/agw_docker/tasks/main.yml
  lte/gateway/deploy/roles/agw_docker/templates/env.j2
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
Labels: component: agw, component: docs, size/S

#13799 fix(agw): Fix reinstall logic and error handling in pydep
  lte/gateway/fabfile.py
  lte/gateway/release/pydep
Labels: component: agw, component: ci, size/XS

#13806 chore: magma vm is based on focal-1.8.0 dist
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, size/XS

#13782 chore(agw): Clean up unnecessary Make commands
  lte/gateway/Makefile
Labels: component: agw, size/L, bazel-cleanup

#13508 fix(agw): Migrate hash list of state_ue to protobuf_map
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/s1ap_types.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.hpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
Labels: component: agw, size/L

#13809 fix(agw): Fix spyne version in pydep lockfile
  lte/gateway/release/magma.lockfile.ubuntu
Labels: component: ci, size/XS

#13803 fix(ci): Build and set up the scripts needed to run services in the bazel LTE integ test workflow
  .github/workflows/lte-integ-test-bazel.yml
  bazel/scripts/link_scripts_for_bazel_integ_tests.sh
Labels: component: ci, LTE-Integration-Test, size/M, bazel

#13781 fix(ci): Fix broken feg integ tests.
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/XS

#13825 fix(ci): Trigger all bazel workflow jobs by pushing to master
  .github/workflows/bazel.yml
Labels: component: ci, size/S, bazel

#13669 fix(ci): fix ipv6 uplink test
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTestVlan.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Static_IP_Test.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Test.testFlowSnapshotMatch.snapshot
Labels: component: agw, size/S

#13833 fix(agw): Modified code to fix compilation error on inclusion of proto_map.h file and removed unused file, sgw.h and unused structure
  lte/gateway/c/core/oai/include/sgw_context_manager.hpp
  lte/gateway/c/core/oai/include/sgw_s8_state.hpp
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/lib/3gpp/3gpp_23.401.h
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.hpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u_sgw_defs.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u_task.c
  lte/gateway/c/core/oai/tasks/sgw/mobilityd_ue_ip_address_alloc.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pcef_emulation.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pcef_emulation.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pco.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_ue_ip_address_alloc.hpp
  lte/gateway/c/core/oai/tasks/sgw/s11_causes.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_defs.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_session.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
Labels: component: agw, size/L

#13600 fix(feg): fix snowflake issue in feg integ test
  .github/workflows/federated-integ-test.yml
  docs/readmes/feg/s1ap_federated_tests.md
  lte/gateway/python/.cache/feg/snowflake
  lte/gateway/python/integ_tests/federated_tests/docker/run.py
  lte/gateway/python/integ_tests/federated_tests/fabfile.py
Labels: component: agw, component: docs, component: ci, size/M, ready2merge

#13750 chore(agw): Increase disk size for agw vm
  .github/workflows/build_all.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test.yml
  docs/readmes/basics/prerequisites.md
  lte/gateway/Vagrantfile
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, component: docs, component: ci, size/M

#13792 refactor(nms): Migrate Alerts rules detail to new style
  nms/app/views/alarms/components/alertmanager/Receivers/SelectReceiver.tsx
  nms/app/views/alarms/components/rules/LabelsEditor.tsx
  nms/app/views/alarms/components/rules/PrometheusEditor/PrometheusEditor.tsx
  nms/app/views/alarms/components/rules/PrometheusEditor/ToggleableExpressionEditor.tsx
  nms/app/views/alarms/components/rules/RuleEditorBase.tsx
  nms/app/views/alarms/components/rules/__tests__/LabelsEditor-test.tsx
  nms/app/views/alarms/components/table/TableActionDialog.tsx
Labels: component: nms, size/XL

#13783 chore(agw): Clean up dead code in gxgy_tests/local integ tests
  bazel/scripts/check_py_bazel.sh
  ci-scripts/teravm/README.md
  ci-scripts/teravm/fabfile.py
  ci-scripts/teravm/fabfile_teravm_conf.json
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/Makefile
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/gxgy_tests/__init__.py
  lte/gateway/python/integ_tests/gxgy_tests/policies.py
  lte/gateway/python/integ_tests/gxgy_tests/session_manager.py
  lte/gateway/python/integ_tests/gxgy_tests/test_credit_tracking.py
  lte/gateway/python/integ_tests/gxgy_tests/test_failure_scenarios.py
  lte/gateway/python/integ_tests/gxgy_tests/test_gx_reauth.py
  lte/gateway/python/integ_tests/gxgy_tests/test_usage_monitors.py
  lte/gateway/python/integ_tests/gxgy_tests/utils.py
Labels: component: agw, component: ci, size/XXL, bazel-cleanup

#13823 fix(agw): Reload magma_deb when provisioning
  docs/readmes/basics/prerequisites.md
  lte/gateway/Vagrantfile
  lte/gateway/deploy/roles/magma_deb/tasks/main.yml
Labels: component: agw, component: docs, component: ci, size/S

#13637 fix(ci): refine backport title & allow dependent job exection
  .github/workflows/backport-pull-request.yml
Labels: component: ci, size/XS

#13840 docs: Document magma_deb VM
  docs/readmes/lte/s1ap_tests.md
Labels: component: docs, size/S

#13705 fix: ryu patching is cleaned up
  cwf/gateway/deploy/roles/ovs/files/nx_actions.py
  cwf/gateway/docker/python/Dockerfile
  lte/gateway/deploy/roles/magma/files/nx_actions.py
  lte/gateway/deploy/roles/magma/files/nx_actions_3.5.py
  lte/gateway/deploy/roles/magma/files/service.py
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma-postinst
  orc8r/gateway/python/python.mk
  third_party/build/bin/ryu_build.sh
Labels: component: orc8r, component: agw, component: ci, size/XXL, component: cwf

#13846 refactor(ci): never used successfully within its whole lifetime
  .github/workflows/rebase.yml
Labels: component: ci, size/M

#13849 fix(feg): Added vagrant-reload to workflows
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/S

#13858 chore(dp): Remove unused CPI related fields
  dp/cloud/go/services/dp/storage/diff.go
  dp/cloud/go/services/dp/storage/diff_test.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
  dp/cloud/python/magma/db_service/migrations/versions/020_remove_cpi_related_fields.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/db_service/tests/unit/test_020_remove_cpi_related_fields.py
Labels: component: orc8r, size/L

#13860 fix(cwg): Install necesssary vagrant plugin for test flow
  .github/workflows/cwf-integ-test.yml
Labels: component: ci, size/XS

#13863 feat(dp): Add support for json columns in db framework
  dp/cloud/go/services/dp/storage/db/query_test.go
  dp/cloud/go/services/dp/storage/db/types.go
Labels: component: orc8r, size/L

#13804 refactor(nms): replace moment.js with date-fns
  nms/app/components/AutorefreshCheckbox.tsx
  nms/app/components/CustomMetrics.tsx
  nms/app/components/DateTimeMetricChart.tsx
  nms/app/components/EventAlertChart.tsx
  nms/app/components/__tests__/EventAlertChartTest.tsx
  nms/app/components/insights/AsyncMetric.tsx
  nms/app/main.tsx
  nms/app/views/alarms/components/alertmanager/AlertDetails/AlertDetailsPane.tsx
  nms/app/views/alarms/components/alertmanager/FiringAlerts.tsx
  nms/app/views/dashboard/feg/FEGDashboard.tsx
  nms/app/views/dashboard/lte/LteDashboard.tsx
  nms/app/views/domain-proxy/LogsList.tsx
  nms/app/views/domain-proxy/__tests__/LogsList.tsx
  nms/app/views/equipment/EnodebDetailMain.tsx
  nms/app/views/equipment/FEGClusterStatus.tsx
  nms/app/views/equipment/GatewayLogChart.tsx
  nms/app/views/equipment/GatewayLogs.tsx
  nms/app/views/equipment/__tests__/EnodebDetailMainTest.tsx
  nms/app/views/equipment/__tests__/EquipmentEnodebTest.tsx
  nms/app/views/equipment/__tests__/FEGEquipmentGatewayTest.tsx
  nms/app/views/equipment/__tests__/GatewayLogsTest.tsx
  nms/app/views/events/EventChart.tsx
  nms/app/views/events/EventsTable.tsx
  nms/app/views/metrics/Explorer.tsx
  nms/app/views/subscriber/SubscriberChart.tsx
  nms/app/views/subscriber/__tests__/SubscriberChartTest.tsx
  nms/config/webpack.production.config.ts
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/XL

#13866 chore(ci): codecov should not fail the build pipeline
  .github/workflows/dp-workflow.yml
  .github/workflows/golang-build-test.yml
Labels: component: ci, size/XS

#13864 feat(dp): Add interface for radio controller replacement
  dp/cloud/go/services/dp/builders/builders.go
  dp/cloud/go/services/dp/servicers/cbsd_manager.go
  dp/cloud/go/services/dp/storage/amc_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
Labels: component: orc8r, size/XXL

#13824 fix(agw): updated debian repo for 1.8.0 release
  cwf/gateway/docker/c/Dockerfile
  cwf/gateway/docker/go/Dockerfile
  cwf/gateway/docker/python/Dockerfile
  feg/gateway/docker/go/Dockerfile
  feg/gateway/docker/python/Dockerfile
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
  lte/gateway/docker/services/c/Dockerfile
  lte/gateway/docker/services/python/Dockerfile
  orc8r/gateway/docker/Dockerfile
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, component: agw, component: ci, component: feg, size/M, component: cwf

#13470 feat(agw): Write per subscriber APN specific data into subscriberDB store when MME receives Update Location Answer
  bazel/external/system_libraries.BUILD
  lte/cloud/go/services/subscriberdb/servicers/southbound/subscriberdb_servicer.go
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/lib/CMakeLists.txt
  lte/gateway/c/core/oai/lib/s6a_proxy/CMakeLists.txt
  lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
  lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.hpp
  lte/gateway/c/core/oai/lib/s6a_proxy/s6a_client_api.cpp
  lte/gateway/c/core/oai/lib/store/CMakeLists.txt
  lte/gateway/c/core/oai/lib/store/sqlite.cpp
  lte/gateway/c/core/oai/lib/store/sqlite.hpp
  lte/gateway/c/core/oai/test/lib/BUILD.bazel
  lte/gateway/c/core/oai/test/lib/CMakeLists.txt
  lte/gateway/c/core/oai/test/lib/test_ula_subData.cpp
Labels: component: orc8r, component: agw, size/XL

#13829 chore: delete stale example dir
  example/gateway/Makefile
  example/gateway/Vagrantfile
  example/gateway/ansible.cfg
  example/gateway/configs/control_proxy.yml
  example/gateway/configs/gateway.mconfig
  example/gateway/configs/magmad.yml
  example/gateway/configs/service_registry.yml
  example/gateway/configs/streamer.yml
  example/gateway/deploy/example.dev.yml
  example/gateway/deploy/hosts
  example/gateway/deploy/roles/example_services/files/magma_hello.service
  example/gateway/deploy/roles/example_services/tasks/main.yml
  example/gateway/fabfile.py
  example/gateway/python/magmaexample/hello/main.py
  example/gateway/python/magmaexample/hello/metrics.py
  example/gateway/python/magmaexample/hello/rpc_servicer.py
  example/gateway/python/setup.py
Labels: size/L, ready2merge

#13561 fix(ci): Join the qfi test to resolve test interdependency issue
  lte/gateway/python/magma/pipelined/tests/snapshots/test_qfi_gtp.QfigtpTest.test_qfi_delete_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_qfi_gtp.QfigtpTest.test_qfi_set_tunnel_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_qfi_gtp.QfigtpTest.test_qfi_tunnel_flows.empty.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_qfi_gtp.QfigtpTest.test_qfi_tunnel_flows.with_qfi_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_qfi_gtp.py
Labels: component: agw, size/S

#13876 fix(dp): add 103 grantId handling
  dp/cloud/python/magma/configuration_controller/response_processor/strategies/response_processing.py
  dp/cloud/python/magma/configuration_controller/tests/unit/test_response_processor.py
Labels: component: orc8r, size/L

#13590 chore(nms): Upgrade chart-js-2 and react-chart-js
  nms/app/components/CustomMetrics.tsx
  nms/app/components/EventAlertChart.tsx
  nms/app/components/insights/AsyncMetric.tsx
  nms/app/host.tsx
  nms/app/main.tsx
  nms/app/util/chartjsSetup.ts
  nms/app/views/equipment/GatewayCheckinChart.tsx
  nms/app/views/equipment/GatewayLogChart.tsx
  nms/app/views/events/EventChart.tsx
  nms/app/views/subscriber/SubscriberChart.tsx
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/L

#13731 fix(orc8r): Updated helm chart version for 1.8.0 release
  cwf/cloud/helm/cwf-orc8r/Chart.yaml
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/deploy_intro.md
  dp/cloud/helm/dp/charts/domain-proxy/Chart.yaml
  feg/cloud/helm/feg-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/Chart.yaml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/scripts/test_helm_charts_sync.py
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
Labels: component: orc8r, component: docs, component: feg, size/M, component: cwf, backported-v1.8

#13879 fix(mobilityd): Set daemon flag for mobilityd timers
  lte/gateway/python/magma/mobilityd/uplink_gw.py
Labels: component: agw, size/XS

#13888 fix(nms): Show an error message if the user login fails
  nms/app/login.tsx
Labels: component: nms, size/XS

#13867 fix: bazel base uses same folly version as magma vm
  .devcontainer/bazel-base/Dockerfile
Labels: size/M, bazel

#13893 fix(dp): Adjust dp config to deployment names
  dp/cloud/go/services/dp/config.go
Labels: component: orc8r, size/XS

#13896 fix(ci): Add repository with grpc-dev version 1.43
  .devcontainer/bazel-base/Dockerfile
Labels: component: ci, size/XS

#13675 chore: bump postcss
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/XL

#13775 fix(nms): bump yarn timeout to avoid preventable build failures
  nms/Dockerfile
Labels: component: nms, size/XS

#13805 feat(ci): Add federated integ test for HSS
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/S

#13872 chore(agw): Tidy up fabfile
  lte/gateway/fabfile.py
Labels: component: agw, size/S

#13878 fix(ci): activate carryforward in CodeCov + apply best practise for flag management
  codecov.yml
Labels: component: ci, size/M

#13916 fix: ansible is pinned because of ansible-core 2.13.4 breaking change
  lte/gateway/deploy/agw_install_docker.sh
Labels: component: agw, size/XS, apply-v1.8

#13472 fix(amf): Adding Reject if Static ip configured is in subset of ip_pool
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
Labels: type: bug, component: agw, size/S

#13908 chore(dp): New AmcManager CreateRequest func
  dp/cloud/go/go.mod
  dp/cloud/go/go.sum
  dp/cloud/go/services/dp/storage/amc_manager.go
  dp/cloud/go/services/dp/storage/amc_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/dp_manager.go
  dp/cloud/go/services/dp/storage/models.go
Labels: component: orc8r, size/L

#13921 chore(dp): Implement AmcManager DeleteCbsd func
  dp/cloud/go/services/dp/storage/amc_manager.go
  dp/cloud/go/services/dp/storage/amc_manager_test.go
Labels: component: orc8r, size/M

#13923 fix: golangci is upgraded to 1.47.3 in order to support generics
  .github/workflows/cloud-workflow.yml
  orc8r/cloud/Makefile
Labels: component: orc8r, component: ci, size/S

#13927 chore(dp): Implement AmcManager UpdateCbsd func
  dp/cloud/go/services/dp/storage/amc_manager.go
  dp/cloud/go/services/dp/storage/amc_manager_test.go
Labels: component: orc8r, size/M

#13929 fix(agw): Fix wildcard expansion error in magma aliases
  lte/gateway/deploy/roles/service_aliases/tasks/main.yml
Labels: component: agw, size/XS

#13852 feat(agw): dockerize the agw envoy controller
  lte/gateway/deploy/roles/magma/files/systemd/magma_dp_envoy.service
  lte/gateway/deploy/roles/magma/files/systemd/magma_envoy_controller.service
  lte/gateway/docker/README.md
  lte/gateway/docker/docker-compose.dev.yaml
  lte/gateway/docker/docker-compose.override.yaml
  lte/gateway/docker/docker-compose.yaml
  lte/gateway/docker/services/envoy_controller/Dockerfile
  lte/gateway/docker/services/python/Dockerfile
Labels: component: agw, component: ci, size/M, ready2merge

#13853 feat(agw): LTE integration tests run on a containerized AGW
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_dedicated_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_3485_timer_for_default_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_dedicated_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_3495_timer_for_default_bearer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_multiple_ip_blocks_mobilityd_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_corrupt_stateless_mme.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_mobilityd_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_esm_info_with_apn_correction.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_mme_restart_detach_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_nw_initiated_detach_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_mobilityd_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_multiple_service_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_pipelined_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_ul_udp_data_with_sessiond_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_with_multiple_mme_restarts.py
  lte/gateway/python/integ_tests/s1aptests/test_enb_partial_reset_multi_ue_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_ics_timer_expiry_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_idle_mode_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_implicit_detach_timer_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_mobile_reachability_tmr_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_attach_complete_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_auth_resp_with_mme_restart_reattach.py
  lte/gateway/python/integ_tests/s1aptests/test_no_auth_response_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_esm_information_rsp_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_identity_rsp_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_no_smc_with_mme_restart_reattach.py
  lte/gateway/python/integ_tests/s1aptests/test_paging_after_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_paging_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_secondary_pdn_with_dedicated_bearer_multiple_services_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_service_req_ul_udp_data_with_mme_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_standalone_pdn_conn_req_with_apn_correction.py
  lte/gateway/python/integ_tests/s1aptests/test_stateless_multi_ue_mixedstate_mme_restart.py
Labels: component: agw, size/L, ready2merge

#13906 chore(dp): Get rid of legacy active-mode controller
  .github/workflows/dp-workflow.yml
  dp/cloud/docker/go/active_mode_controller/Dockerfile
  dp/cloud/go/active_mode_controller/main.go
  dp/cloud/helm/dp/charts/domain-proxy/README.md
  dp/cloud/helm/dp/charts/domain-proxy/examples/aws_nginx_values.yaml
  dp/cloud/helm/dp/charts/domain-proxy/examples/minikube_values.yaml
  dp/cloud/helm/dp/charts/domain-proxy/examples/minikube_values_nginx.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/_helpers.tpl
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/hpa.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/pdb.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/serviceaccount.yaml
  dp/cloud/helm/dp/charts/domain-proxy/values.yaml
  dp/skaffold.yaml
Labels: component: orc8r, component: ci, size/XL, component: dp

#13914 feat(dp): Implement GetState in DP orc8r service
  dp/cloud/go/services/dp/builders/builders.go
  dp/cloud/go/services/dp/storage/amc_manager.go
  dp/cloud/go/services/dp/storage/amc_manager_test.go
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/go/services/dp/storage/db/types.go
  dp/cloud/go/services/dp/storage/dp_manager.go
  dp/cloud/go/services/dp/storage/models.go
  dp/cloud/go/services/dp/storage/models_test.go
Labels: component: orc8r, size/XXL

#13920 docs(agw): Mark the AGWC Helm chart as experimental
  lte/gateway/deploy/agwc-helm-charts/README.md
Labels: component: agw, size/XS

#13937 chore(dp): Fix domain-proxy build job
  dp/skaffold.yaml
Labels: size/XS, component: dp

#13934 chore(orc8r): Add missing dp enabled parameter to orc8r terraform
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
Labels: component: orc8r, size/XS, candidate-for-backporting

#13890 chore(dp): Preallocate memory when collecting column pointers
  dp/cloud/go/services/dp/storage/db/join.go
Labels: component: orc8r, size/S

#13925 chore(dp): supressed radio controller operation
  dp/cloud/docker/python/radio_controller/Dockerfile
  dp/cloud/python/magma/radio_controller/run.py
Labels: component: orc8r, size/L

#13870 test(cwg): Stabilizing `TestGyCreditExhaustionRedirect`
  cwf/gateway/integ_tests/gy_enforcement_test.go
  cwf/gateway/integ_tests/test_runner.go
  cwf/gateway/services/uesim/servicers/uesim.go
Labels: size/L, component: cwf

#13932 chore(agw): cleanup apt installs in agw Dockerfiles
  lte/gateway/docker/services/c/Dockerfile
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/L

#13946 fix(agw): Downgrade grpcio to fix pylint
  bazel/external/requirements.in
  bazel/external/requirements.txt
  lte/gateway/python/setup.py
  orc8r/gateway/python/python.mk
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: agw, size/XL

#13959 fix(ci): Add missing paths to path filter
  .github/workflows/cloud-workflow.yml
Labels: component: ci, size/XS

#13842 chore(ci): run integ tests again deb installation in ci
  .github/workflows/lte-integ-test-magma-deb.yml
  lte/gateway/deploy/roles/magma_deb/tasks/main.yml
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/L

#13917 fix(nms): Improve sync of NMS organizations and orc8r tenants
  nms/app/views/organizations/OrganizationInfoDialog.tsx
  nms/generated/api.ts
  nms/scripts/setPassword.ts
  nms/server/grafana/handlers.ts
  nms/server/host/__tests__/organization-test.ts
  nms/server/host/routes.ts
  orc8r/cloud/go/services/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/tenants/obsidian/models/swagger.v1.yml
Labels: component: orc8r, component: nms, size/L

#13947 fix(agw): the envoy controller is in the feg image
  lte/gateway/docker/docker-compose.yaml
Labels: component: ci, size/XS

#13868 chore: #11633 is reverted manually
  bazel/scripts/check_c_cpp_bazel.sh
  lte/gateway/Makefile
  lte/gateway/c/core/oai/CMakeAgwOptions.txt
  lte/gateway/c/core/oai/CMakeMmeOptions.txt
  lte/gateway/c/core/oai/include/mme_app_messages_def.h
  lte/gateway/c/core/oai/include/mme_app_messages_types.h
  lte/gateway/c/core/oai/include/mme_config.h
  lte/gateway/c/core/oai/include/state_manager.hpp
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/mme_app/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/mme_app/experimental/mme_app_serialization.cpp
  lte/gateway/c/core/oai/tasks/mme_app/experimental/mme_app_serialization.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_embedded_spgw.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.c
Labels: component: agw, size/L

#13960 fix: py cryptography is pinned to a version that works with magma
  bazel/external/requirements.in
  bazel/external/requirements.txt
Labels: size/M

#13918 feat(agw): all AGW containeres have health checks
  lte/gateway/docker/docker-compose.yaml
Labels: component: ci, size/M

#13943 fix(agw): Modified code to remove unused files, pgw_pcef_emulation.cpp/hpp and also removed unused structure, deactivated_predefined_pcc_rules
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/pgw_types.h
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/tasks/sgw/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/sgw/pgw_config.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pcef_emulation.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pcef_emulation.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state_manager.hpp
Labels: component: agw, size/XL

#13768 feat(amf): Support for Protocol Configuration Options IE
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_session_manager_pco.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_session_qos.cpp
  lte/gateway/c/core/oai/tasks/nas5g/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GRegistrationAccept.hpp
  lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GNetworkFeatureSupport.hpp
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GRegistrationAccept.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GNetworkFeatureSupport.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
Labels: component: agw, size/L, product: 5g sa

#13957 fix(agw): Pin version of `grpcio_tool` in `python_dev` ansible role
  orc8r/tools/ansible/roles/python_dev/tasks/main.yml
Labels: component: orc8r, size/XS, ready2merge

#13972 docs: headlines in src/go/README.md are displayed correctly
  src/go/capture/README.md
Labels: size/S, ready2merge

#13678 fix(agw): Modified code to replace C structure ue_description_t to protobuf structure UeDescription
  lte/cloud/go/protos/oai/s1ap_state.pb.go
  lte/gateway/c/core/oai/common/itti_free_defined_msg.c
  lte/gateway/c/core/oai/include/mme_init.hpp
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/s1ap_types.hpp
  lte/gateway/c/core/oai/tasks/grpc_service/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.cpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers_with_injected_state.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
  lte/protos/oai/s1ap_state.proto
Labels: component: orc8r, component: agw, size/XXL

#13939 fix(nms): improve sync of orc8r tenants with NMS organizations in NMS scripts
  nms/scripts/createOrganization.ts
  nms/scripts/mockServer.ts
  nms/scripts/setPassword.ts
  nms/server/host/routes.ts
  nms/server/util/tenantsSync.ts
Labels: component: nms, size/L

#13413 fix(amf): Support for 5GS network feature support
  lte/gateway/c/core/oai/include/amf_config.hpp
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
  lte/gateway/configs/templates/mme.conf.template
Labels: component: agw, size/XS, product: 5g sa

#13977 chore: Publish environment logging for the Bazel integration tests
  .github/workflows/lte-integ-test-bazel.yml
Labels: component: ci, size/S, bazel

#13982 fix: magma_deb integ tests can use config_iface_for_ipv6.py script
  lte/gateway/deploy/roles/magma_deb/tasks/main.yml
Labels: component: agw, size/XS

#13926 docs(agw): Updated AGW Install docs for the 1.8.0 Release
  docs/readmes/lte/deploy_install.md
Labels: component: docs, size/S

#13985 chore(ci): putting the RHEL8 certificates/entitlements in cleaner way
  ci-scripts/JenkinsFile-OAI-Container-GitHub
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: ci, size/S

#13986 fix(nms): Display correct axios errors
  nms/app/util/ErrorUtils.ts
  nms/server/auth/express.ts
  nms/server/auth/expressOnboarding.ts
  nms/server/host/routes.ts
Labels: component: nms, size/S

#13940 fix(ci): Mitigate LSAN errors in LTE integ tests
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
Labels: component: agw, LTE-Integration-Test, size/S

#13991 chore: lte integ tests always publish logs
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/XS

#13978 chore: Fix scripts for Bazel integration tests
  bazel/scripts/check_py_bazel.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/scripts/BUILD.bazel
  lte/gateway/python/scripts/config_iface_for_ipv6.py
Labels: component: agw, size/L, bazel

#13996 fix(agw): Updated AGW Install script branch to v1.8
  lte/gateway/deploy/agw_install_ubuntu.sh
Labels: component: agw, size/XS, v1.8, apply-v1.8, backported-v1.8

#13990 fix: trf server logging is enabled again
  lte/gateway/fabfile.py
Labels: component: agw, size/M

#13992 chore(agw): indentation in Dockerfile is fixed
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/XS, ready2merge

#13973 fix(agw): fix envoy controller docker image name
  lte/gateway/docker/docker-compose.override.yaml
Labels: component: ci, size/XS

#13854 chore(agw): s1ap_utils.py is cleaned up
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/L, ready2merge

#14009 feat(agw): test-sctp-shutdown-while-mme-is-stopped.py is adapted to c…
  lte/gateway/python/integ_tests/s1aptests/test_sctp_shutdown_while_mme_is_stopped.py
Labels: component: agw, size/S, ready2merge

#14007 fix: missing enodebd folders are added to magma debian build
  lte/gateway/python/setup.py
Labels: component: agw, size/XS

#13980 chore: integ test magma restart waits for pipelined to be initialized
  lte/gateway/python/integ_tests/s1aptests/ovs/rest_api.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/M, bazel

#13993 fix(agw): Allow containerized magmad to restart services
  lte/gateway/docker/README.md
  lte/gateway/docker/docker-compose.yaml
  lte/gateway/docker/services/python/Dockerfile
  orc8r/gateway/python/magma/magmad/config_manager.py
  orc8r/gateway/python/magma/magmad/main.py
Labels: component: orc8r, component: ci, size/S

#13994 fix(agw): make redis save state after cleaning the db
  lte/gateway/python/scripts/config_stateless_agw.py
Labels: component: agw, size/XS, ready2merge

#14015 fix(agw): sctpd needs explicit restart for docker as it is restarted …
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_corrupt_stateless_mme.py
Labels: component: agw, size/M

#13984 chore: Publish test results for the Bazel integration and sudo tests
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/sudo-python-tests.yml
  bazel/scripts/run_integ_tests.sh
  bazel/scripts/run_sudo_tests.sh
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/L, bazel

#14013 chore: an integ test checks if all magma services are running
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/BUILD.bazel
  lte/gateway/python/integ_tests/s1aptests/test_services_are_running.py
Labels: component: agw, size/L

#14004 chore: the init system check is less chatty
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/M

#14000 chore(agw): restart of sctpd is adapted
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_enb_rlf_initial_ue_msg.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_sctpd_restart.py
  lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py
  lte/gateway/python/integ_tests/s1aptests/test_s1setup_failure_incorrect_plmn.py
  lte/gateway/python/integ_tests/s1aptests/test_s1setup_failure_incorrect_tac.py
  lte/gateway/python/integ_tests/s1aptests/test_sctp_shutdown_after_multi_ue_attach.py
Labels: component: agw, size/S

#13862 fix(agw): fix certificate issue for containerized AGW deployment
  lte/gateway/docker/.env
  lte/gateway/docker/README.md
  lte/gateway/docker/docker-compose.yaml
Labels: component: ci, size/XS, ready2merge

#14030 fix: boolean arguments in fabric calls are interpreted correctly
  lte/gateway/fabfile.py
Labels: component: agw, size/S

#14029 refactor(orc8r): Remove proto.Clone calls
  orc8r/cloud/go/services/configurator/storage/sql.go
  orc8r/cloud/go/services/configurator/storage/sql_entity_write_helpers.go
  orc8r/cloud/go/services/configurator/storage/sql_test.go
  orc8r/cloud/go/services/configurator/storage/storage.go
  orc8r/cloud/go/services/tenants/client_api.go
Labels: component: orc8r, size/L

#13983 chore(ci): Integ tests magma deb for specific magma package
  .github/workflows/build_all.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  lte/gateway/Vagrantfile
  lte/gateway/deploy/agw_install_ubuntu_vm.sh
  lte/gateway/deploy/roles/magma_deb/tasks/main.yml
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
Labels: component: agw, component: ci, size/M

#14014 chore(nms): Improve generic commands functionality
  nms/app/components/GatewayCommandFields.tsx
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_command_handlers.go
  orc8r/gateway/python/magma/magmad/generic_command/command_executor.py
  orc8r/gateway/python/magma/magmad/generic_command/shell_command_executor.py
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
Labels: component: orc8r, component: nms, size/M

#14037 fix(agw): all `ROOTCA_PATH` variables are deleted
  lte/gateway/docker/docker-compose.yaml
Labels: component: ci, size/XS

#14039 fix(amf): VoNR configuration support
  lte/gateway/c/core/oai/tasks/amf/amf_config.c
Labels: component: agw, size/S

#14011 feat(ci): Move and edit release scripts/workflows
  .github/workflows/docker-promote.yml
  .github/workflows/helm-promote.yml
  orc8r/tools/docker/promote.sh
  orc8r/tools/helm/promote.sh
Labels: component: orc8r, component: ci, size/L

#14024 fix(subscriberdb): Detach inactive subscribers when syncing
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
Labels: component: agw, size/M

#13728 fix(agw): Port enb context from C structure to protobuf structure in s1ap module
  lte/cloud/go/protos/oai/s1ap_state.pb.go
  lte/gateway/c/core/oai/common/common_types.h
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/s1ap_types.hpp
  lte/gateway/c/core/oai/include/state_converter.hpp
  lte/gateway/c/core/oai/tasks/grpc_service/S1apServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/core/oai/tasks/nas/api/mme/mme_api.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_ta.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_ta.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/test/s1ap_task/data/s1ap_state_ATTACHED
  lte/gateway/c/core/oai/test/s1ap_task/data/s1ap_state_ATTACHED_encoded
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.cpp
  lte/gateway/c/core/oai/test/s1ap_task/mock_s1ap_op.h
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_handle_new_association.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers_with_injected_state.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
  lte/protos/oai/s1ap_state.proto
Labels: component: orc8r, component: agw, size/XXL
