Repository magma/magma, pull requests merged in 2022-06, with the labels that each got.

#12889 docs: Update orc8r minikube deployment docs to account for Linux
  docs/readmes/orc8r/dev_minikube.md
Labels: component: docs, size/S

#12885 chore(pipelined): selection of mypy errors are fixed
  lte/gateway/python/magma/pipelined/gtp_stats_collector.py
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
Labels: component: agw, size/M, ready2merge

#11926 feat(agw): IPv6 data path support
  lte/gateway/Vagrantfile
  lte/gateway/configs/pipelined.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/trfserver/files/traffic_server.py
  lte/gateway/python/integ_tests/data/s1ap_tester_cfg/nbAppCfg.txt
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_disable_ipv6_iface.py
  lte/gateway/python/integ_tests/s1aptests/test_enable_ipv6_iface.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/scripts/config_iface_for_ipv6.py
Labels: component: agw, component: ci, size/L, ready2merge

#12897 Revert "feat(agw): IPv6 data path support (#11926)"
  lte/gateway/Vagrantfile
  lte/gateway/configs/pipelined.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/trfserver/files/traffic_server.py
  lte/gateway/python/integ_tests/data/s1ap_tester_cfg/nbAppCfg.txt
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_disable_ipv6_iface.py
  lte/gateway/python/integ_tests/s1aptests/test_enable_ipv6_iface.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/scripts/config_iface_for_ipv6.py
Labels: component: agw, component: ci, size/L

#12891 feat(dp): Use mutable installation params for mutable cbsd API
  dp/cloud/go/services/dp/builders/builders.go
  dp/cloud/go/services/dp/obsidian/models/cbsd_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/conversion.go
  dp/cloud/go/services/dp/obsidian/models/conversion_test.go
  dp/cloud/go/services/dp/obsidian/models/mutable_cbsd_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/mutable_installation_param_swaggergen.go
  dp/cloud/go/services/dp/obsidian/models/swagger.v1.yml
  dp/cloud/go/services/dp/obsidian/models/validation_test.go
  nms/generated-ts/api.ts
  nms/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: nms, size/L

#12900 fix(ci): obsolete project radtonics_lab_native is removed from sentry…
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#12909 fix(ci): the latest package version coincides with the version apt would choose
  lte/gateway/release/pydep
Labels: component: ci, size/S

#12902 chore: Publish bazel profile data in ci
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/generate-gcc-warnings.sh
Labels: component: ci, size/M, bazel

#12881 chore(dp): Show timestamps in integrations_tests
  .github/workflows/dp-workflow.yml
  dp/Makefile
  dp/cloud/python/magma/test_runner/requirements.txt
  dp/tools/deployment/tests/test_runner_deployment.yml
  dp/tools/deployment/tests/test_runner_deployment_orc8r.yml
Labels: component: orc8r, component: ci, size/S, component: dp

#12906 chore(orc8r): Cleanup metric naming to not use deprecated protobuf file
  orc8r/cloud/go/services/metricsd/servicers/protected/servicer.go
  orc8r/cloud/go/services/metricsd/servicers/protected/servicer_protected_test.go
  orc8r/cloud/go/services/metricsd/servicers/southbound/servicer.go
  orc8r/cloud/go/services/metricsd/servicers/southbound/servicer_southbound_test.go
  orc8r/lib/go/protos/metricsd_helper.go
Labels: component: orc8r, size/M

#12882 chore(dp): single-step integration tests
  dp/cloud/go/services/dp/storage/cbsd_manager.go
  dp/cloud/go/services/dp/storage/cbsd_manager_test.go
  dp/cloud/python/magma/test_runner/config.py
  dp/cloud/python/magma/test_runner/tests/api_data_builder.py
  dp/cloud/python/magma/test_runner/tests/integration_testcase.py
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
Labels: component: orc8r, size/XL, ready2merge

#12901 fix(ci): bump cwag images to focal and adapt package setup
  cwf/gateway/Vagrantfile
  cwf/gateway/deploy/roles/ovs/tasks/debian.yml
Labels: component: ci, size/S, component: cwf

#12788 refactor(orc8r): remove interceptor wrappers in middleware
  orc8r/cloud/go/service/middleware/unary/interceptors.go
Labels: component: orc8r, size/M

#12903 docs(feg): Tier is needed to setup an feg
  docs/readmes/feg/deploy_install.md
Labels: component: docs, size/XS

#12928 chore: create warning advisory
  README.md
  SECURITY.md
Labels: size/XS

#12850 feat(enodebd): Send CBSD parameters to Domain Proxy
  dp/protos/BUILD.bazel
  lte/gateway/python/magma/enodebd/BUILD.bazel
  lte/gateway/python/magma/enodebd/data_models/data_model_parameters.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/dp_client.py
  lte/gateway/python/magma/enodebd/tests/BUILD.bazel
  lte/gateway/python/magma/enodebd/tests/baicells_qrtb_tests.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
Labels: component: agw, size/L, ready2merge, component: dp

#12895 chore: Upgrade pylint to 2.14.0
  lte/gateway/python/Makefile
  lte/gateway/python/magma/pipelined/qos/tc_ops.py
  lte/gateway/python/magma/subscriberdb/protocols/diameter/avp.py
  lte/gateway/python/magma/subscriberdb/store/sqlite.py
  orc8r/gateway/python/magma/magmad/sync_rpc_client.py
  orc8r/gateway/python/magma/magmad/upgrade/upgrader2.py
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: agw, size/S, ready2merge

#12843 chore: all ansible files use same go installation from artifactory
  cwf/gateway/deploy/cwag_dev.yml
  cwf/gateway/deploy/cwag_dev_centos7.yml
  cwf/gateway/deploy/cwag_test.yml
  lte/gateway/deploy/roles/magma/vars/all.yaml
  orc8r/cloud/deploy/roles/golang/defaults/main.yml
  orc8r/cloud/deploy/roles/golang/tasks/main.yml
  orc8r/tools/ansible/roles/golang/defaults/main.yml
  orc8r/tools/ansible/roles/golang/tasks/main.yml
Labels: component: orc8r, component: agw, size/M, component: cwf

#12936 fix(ci): action updated for Python 3
  .github/workflows/nms-workflow.yml
Labels: component: ci, size/XS

#12937 chore(feg): The s8_proxy expects ips for the local_address and pgw_ad…
  feg/cloud/go/services/feg/obsidian/models/s8_swaggergen.go
  feg/cloud/go/services/feg/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
Labels: component: orc8r, component: feg, size/S

#12934 test(agw): magma_test VM is upgraded to Ubuntu focal
  lte/gateway/Vagrantfile
  lte/gateway/deploy/magma_test.yml
  lte/gateway/deploy/roles/magma_test/files/update_package.sh
  lte/gateway/deploy/roles/magma_test/tasks/main.yml
  lte/gateway/deploy/roles/magma_test_registry/files/jfrog.pub
  lte/gateway/deploy/roles/magma_test_registry/tasks/main.yml
  orc8r/tools/ansible/roles/python_dev/tasks/main.yml
  orc8r/tools/packer/magma-test-virtualbox.json
  orc8r/tools/packer/vagrant-box-upload.sh
Labels: component: orc8r, component: agw, component: ci, size/L, ready2merge

#12827 refactor(orc8r): move GetControlProxy to tenants
  orc8r/cloud/go/services/bootstrapper/servicers/registration/registration.go
  orc8r/cloud/go/services/bootstrapper/servicers/registration/registration_test.go
  orc8r/cloud/go/services/tenants/client_api.go
  orc8r/cloud/go/services/tenants/protos/tenants.pb.go
  orc8r/cloud/go/services/tenants/protos/tenants.proto
  orc8r/cloud/go/services/tenants/servicers/protected/servicer.go
  orc8r/cloud/go/services/tenants/servicers/protected/servicer_test.go
Labels: component: orc8r, size/L

#12919 docs: Changed admin_cert.* to admin_operator.* in onboarding docs
  docs/readmes/basics/quick_start_guide.md
Labels: component: docs, size/XS, ready2merge

#12733 fix(amf): Registration reject handling for mismatching plmn
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
Labels: component: agw, priority: high, size/M, product: 5g sa

#12545 test(agw): Hardware In the Loop - Initial Commit
  bazel/scripts/check_py_bazel.sh
  hil_testing/Magma_Ansible/README.md
  hil_testing/Magma_Ansible/inventory/hosts.yaml
  hil_testing/Magma_Ansible/project/roles/agw-health-checks/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/agw-health-checks/vars/main.yaml
  hil_testing/Magma_Ansible/project/roles/agw-state-check/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/build-upgrade/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/get-file/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/get-logs/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/get-sw-info/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/pcap/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/pcap/vars/main.yaml
  hil_testing/Magma_Ansible/project/roles/reboot/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/test-cleanup/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/upgrade-configure/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/upgrade-prep/tasks/main.yaml
  hil_testing/Magma_Ansible/project/roles/vars/main.yaml
  hil_testing/Magma_Ansible/project/upgrade.yaml
  hil_testing/Magma_Automations/scripts/base.py
  hil_testing/Magma_Automations/scripts/delete_tests.py
  hil_testing/Magma_Automations/scripts/get_ports.py
  hil_testing/Magma_Automations/scripts/systemd/README
  hil_testing/Magma_Automations/scripts/systemd/delete_spirent_scripts.service
  hil_testing/Magma_Automations/scripts/systemd/delete_spirent_scripts.timer
  hil_testing/Magma_Automations/scripts/tdf.py
  hil_testing/README.md
  hil_testing/requirements
  hil_testing/spirent_automation/TC/TC001_SANITY_control_50UE_3rate.py
  hil_testing/spirent_automation/TC/TC002_SANITY_data_30UE_3rate_active_idle.py
  hil_testing/spirent_automation/TC/TC003_SANITY_data_50UE_3rate_25M_attach_detach.py
  hil_testing/spirent_automation/TC/TC004_SANITY_control_200UE_3rate.py
  hil_testing/spirent_automation/TC/TC005_SANITY_data_200UE_3rate_100M_attach_detach.py
  hil_testing/spirent_automation/TC/TC006_SANITY_data_200UE_3rate_400M_attach_detach.py
  hil_testing/spirent_automation/TC/TC007_SANITY_control_400UE_3rate.py
  hil_testing/spirent_automation/TC/TC008_SANITY_data_400UE_3rate_200M_attach_detach.py
  hil_testing/spirent_automation/TC/TC009_SANITY_control_600UE_3rate.py
  hil_testing/spirent_automation/TC/TC010_SANITY_data_600UE_3rate_300M_attach_detach.py
  hil_testing/spirent_automation/TC/TC011_SANITY_data_3UE_600M_attach_detach.py
  hil_testing/spirent_automation/TC/TC012_SANITY_data_5rate_600UE_400M_attach_detach.py
  hil_testing/spirent_automation/TC/Testplan.md
  hil_testing/spirent_automation/TC/spirent_templates/TEMPLATE_CONTROL_REAL_WORLD
  hil_testing/spirent_automation/TC/spirent_templates/TEMPLATE_DATA_HTTP_NO_INVALID_UE
  hil_testing/spirent_automation/TC/spirent_templates/TEMPLATE_DATA_HTTP_SESSION_LOADING_SEQ
  hil_testing/spirent_automation/TC/spirent_templates/TEMPLATE_DATA_MIX_200M
  hil_testing/spirent_automation/TS/aaa.json
  hil_testing/spirent_automation/TS/agw.py
  hil_testing/spirent_automation/TS/aws_lib.py
  hil_testing/spirent_automation/TS/hil_lib.py
  hil_testing/spirent_automation/TS/kpi_lib.py
  hil_testing/spirent_automation/TS/magma.py
  hil_testing/spirent_automation/TS/slack.py
  hil_testing/spirent_automation/TS/ts_lib.py
  hil_testing/spirent_automation/ansible.cfg
  hil_testing/spirent_automation/config.py
  hil_testing/spirent_automation/main.py
  hil_testing/spirent_automation/templates/test_case_results.html
  hil_testing/state_check.sh
Labels: size/XXL, ready2merge

#12959 docs: Comment out TODOs
  docs/docusaurus/versioned_docs/version-1.1.X/lte/dev_notes.md
  docs/docusaurus/versioned_docs/version-1.1.X/lte/s1ap_tests.md
  docs/docusaurus/versioned_docs/version-1.2.X/lte/dev_notes.md
  docs/docusaurus/versioned_docs/version-1.4.X/lte/dev_notes.md
  docs/docusaurus/versioned_docs/version-1.5.X/lte/dev_notes.md
  docs/docusaurus/versioned_docs/version-1.6.X/lte/dev_notes.md
  docs/docusaurus/versioned_docs/version-1.6.X/lte/s1ap_tests.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/dev_notes.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/s1ap_tests.md
  docs/readmes/lte/dev_notes.md
  docs/readmes/lte/s1ap_tests.md
Labels: component: docs, size/S

#12958 feat(ci): exclude yarn.lock from misspell
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/XS

#12955 chore: Pin pylint to 2.14.0
  orc8r/gateway/python/setup.py
Labels: component: orc8r, size/XS

#12950 chore(pipelined): Make mypy green
  lte/gateway/python/magma/pipelined/app/BUILD.bazel
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/he.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/encoding.py
  lte/gateway/python/magma/pipelined/qos/qos_tc_impl.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
  lte/gateway/python/magma/pipelined/tests/test_uplink_bridge.py
Labels: component: agw, size/L

#12784 fix(agw): Re-enabled s1setup success secondary plmn test case
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/XS

#12924 fix(agw): Provided fixes for the issue, 12677
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
Labels: component: agw, size/S

#12929 chore: bazel is upgraded to version 5
  .bazelrc
  .bazelversion
  bazel/third_party_repositories.bzl
  lte/gateway/c/session_manager/OperationalStatesHandler.cpp
Labels: component: agw, size/S, bazel

#12921 chore(dp): One postgresql instance in dev/CI
  .github/workflows/dp-workflow.yml
  dp/Makefile
  dp/cloud/docker/postgresql/Dockerfile
  dp/cloud/docker/postgresql/create_magma_dbs.sh
  dp/cloud/helm/dp/charts/domain-proxy/examples/orc8r_minikube_values.yaml
  dp/cloud/python/magma/db_service/config.py
  dp/skaffold.yaml
  dp/tools/deployment/vendor/postgresql.yml
Labels: component: orc8r, component: ci, size/L, component: dp

#12956 chore(mobilityd): Make mypy green
  lte/gateway/python/magma/mobilityd/dhcp_client.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/subscriberdb_client.py
  lte/gateway/python/magma/mobilityd/tests/test_dhcp_client.py
  lte/gateway/python/magma/mobilityd/uplink_gw.py
Labels: component: agw, size/M, ready2merge

#12971 fix(ci): Fix bazel remote cache config for bazel version 5
  .bazelrc
  bazel/bazelrcs/docker.bazelrc
Labels: component: ci, size/XS, bazel

#12952 chore(agw): integrate new gateway subscriber state
  lte/gateway/c/session_manager/OperationalStatesHandler.cpp
  lte/gateway/c/session_manager/OperationalStatesHandler.hpp
  lte/gateway/c/session_manager/test/BUILD.bazel
  lte/gateway/c/session_manager/test/CMakeLists.txt
  lte/gateway/c/session_manager/test/Consts.hpp
  lte/gateway/c/session_manager/test/test_operational_states_handler.cpp
Labels: component: agw, size/L

#12960 fix(agw): Formatted config to remove residue after sanity
  lte/gateway/configs/gateway.mconfig
Labels: component: agw, size/XS

#12961 fix(agw): suppressed dual exception message
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/XS

#12737 chore(agw): MME retun type fix in mme_app
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_edns_emulation.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_hss_reset.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_location.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_alert.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_associated.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_detach.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_fsm.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_la_updated.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_null.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_paging.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_reset.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgsap_location_update.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_transport.c
Labels: component: agw, size/M

#12980 chore(agw): deprecated 'assert_()' is no longer used
  lte/gateway/python/magma/mobilityd/tests/test_dhcp_client.py
Labels: component: agw, size/XS, ready2merge

#12989 fix(agw): Deleted residual OVS flow rules after continuous random attach
  lte/gateway/python/integ_tests/s1aptests/test_continuous_random_attach.py
Labels: component: agw, size/XS

#12949 fix(orc8r): Add new table for reindexed subscriber state
  lte/cloud/go/services/subscriberdb/storage/subscriber_state.go
  lte/cloud/go/services/subscriberdb/storage/subscriber_state_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
Labels: component: orc8r, size/L

#12725 refactor(cwg): replace deprecated errors module
  cwf/cloud/go/go.mod
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
  cwf/cloud/go/services/cwf/obsidian/models/validate.go
  cwf/cloud/go/services/cwf/servicers/protected/builder_servicer.go
  cwf/gateway/go.mod
  cwf/gateway/integ_tests/service_wrappers.go
  cwf/gateway/integ_tests/test_runner.go
  cwf/gateway/services/uesim/servicers/config.go
  cwf/gateway/services/uesim/servicers/eap.go
  cwf/gateway/services/uesim/servicers/eap_aka.go
  cwf/gateway/services/uesim/servicers/radius.go
  cwf/gateway/services/uesim/servicers/ue_store_utils.go
  cwf/gateway/services/uesim/servicers/uesim.go
Labels: size/L, ready2merge, component: cwf

#12993 chore(orc8r): Remove temporary go.mod files
  orc8r/cloud/go/go.mod662499515.tmp
  orc8r/cloud/go/go.mod937360599.tmp
Labels: component: orc8r, size/XS

#12802 feat(nms): Add Organization unit tests
  nms/app/views/organizations/OrganizationDialog.js
  nms/app/views/organizations/OrganizationEdit.js
  nms/app/views/organizations/OrganizationInfoDialog.js
  nms/app/views/organizations/Organizations.js
  nms/app/views/organizations/__tests__/OrganizationEditTest.js
  nms/app/views/organizations/__tests__/OrganizationsTest.js
  nms/app/views/organizations/useAxiosTestHelper.js
Labels: component: nms, size/XL

#12997 chore(dp): Add SERVICE_HOSTAME variable to domain-proxy containers deployment
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/fluentd/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/deployment.yaml
Labels: component: orc8r, size/S

#12873 docs: typo in Security Debugging docs
  docs/docusaurus/versioned_docs/version-1.5.X/orc8r/dev_security.md
  docs/docusaurus/versioned_docs/version-1.7.0/orc8r/dev_security.md
  docs/readmes/orc8r/dev_security.md
Labels: component: docs, size/XS

#12981 fix(agw): `make check` lintering is improved
  lte/gateway/python/Makefile
Labels: component: agw, size/S, ready2merge

#12848 feat(feg): Added health metric for s8_proxy servicer
  feg/cloud/go/protos/mconfig/mconfigs.pb.go
  feg/gateway/configs/magmad.yml
  feg/gateway/services/s8_proxy/metrics/metrics.go
  feg/gateway/services/s8_proxy/s8_proxy/main.go
  feg/gateway/services/s8_proxy/servicers/s8_proxy.go
  feg/protos/mconfig/mconfigs.proto
Labels: component: feg, size/L, ready2merge

#13003 chore(ci): cache Vagrant boxes with Github Actions Cache
  .github/workflows/bazel-cache-push.yml
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/S

#12948 chore(ci): Bazel workflows send slack message
  .github/workflows/agw-workflow.yml
  .github/workflows/bazel-cache-push.yml
  .github/workflows/bazel.yml
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/L, bazel

#13005 fix(ci): Fix Bazel failure Slack message in agw-workflow
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS, bazel

#12996 fix(agw): Fixed integ test python syntx warning
  lte/gateway/python/integ_tests/s1aptests/util/traffic_messages.py
Labels: component: agw, size/XS

#12942 docs: fluentd for orc8r minikube deployment documentation
  docs/readmes/orc8r/dev_build.md
  docs/readmes/orc8r/dev_minikube.md
Labels: component: docs, size/L

#13007 fix(ci): base box caching is refactored
  .github/workflows/bazel-cache-push.yml
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/M

#12999 chore(dp): Add grafana templates to dp helm chart
  dp/Makefile
  dp/README.md
  dp/cloud/helm/dp/charts/domain-proxy/examples/metrics_overrides.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/_helpers.tpl
  dp/cloud/helm/dp/charts/domain-proxy/templates/grafana/configmap.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/grafana/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/grafana/secrets.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/grafana/service.yaml
  dp/cloud/helm/dp/charts/domain-proxy/values.yaml
  dp/skaffold.yaml
Labels: component: orc8r, size/L, component: dp

#12567 feat(amf): handling IMSI de-concealing failure cases
  lte/cloud/go/protos/subscriberdb.pb.go
  lte/gateway/c/core/oai/include/amf_app_messages_def.h
  lte/gateway/c/core/oai/include/amf_app_messages_types.h
  lte/gateway/c/core/oai/lib/n11/M5GSUCIRegistrationServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/M5GSUCIRegistrationServiceClient.hpp
  lte/gateway/c/core/oai/lib/n11/amf_client_proto_msg_to_itti_msg.cpp
  lte/gateway/c/core/oai/lib/n11/amf_client_proto_msg_to_itti_msg.hpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_main.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.hpp
  lte/gateway/c/core/oai/tasks/amf/amf_client_servicer.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.hpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/ies/M5GSMobileIdentity.hpp
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GSMobileIdentity.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
  lte/gateway/c/core/oai/test/amf/util_nas5g_pkt.hpp
  lte/gateway/c/core/oai/test/n11/test_auth_service_client.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/protocols/m5g_auth_servicer.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
  lte/protos/subscriberdb.proto
Labels: component: orc8r, component: agw, size/L, product: 5g sa

#13015 fix(ci): Work around unattended upgrades holding lock
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, size/XS

#13019 fix(dp): Fix typo in domain-proxy Makefile
  .github/workflows/dp-workflow.yml
  dp/Makefile
Labels: component: ci, size/XS, ready2merge, component: dp

#12987 chore: Modify bazel cache configuration setup
  .bazelrc
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
  bazel/bazelrcs/cache.bazelrc
  bazel/bazelrcs/devcontainer.bazelrc
  bazel/bazelrcs/docker.bazelrc
  bazel/bazelrcs/remote_caching_ro.bazelrc
  bazel/bazelrcs/remote_caching_rw.bazelrc
  bazel/bazelrcs/vm.bazelrc
  bazel/scripts/remote_cache_bazelrc_setup.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, size/M, bazel

#13027 fix(nms): Fix settings link on host portal
  nms/app/components/ProfileButton.js
Labels: component: nms, size/XS

#13018 fix(agw): Add Iptables rule for enodebd when other rules exist
  lte/gateway/python/magma/enodebd/enodebd_iptables_rules.py
Labels: component: agw, size/S

#13028 fix(ci): bazel coverage failures are mitigated by several flags (see #13026)
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS, bazel

#13025 fix(nms): Fix editing and deleting users from organisation portal
  nms/app/views/organizations/OrganizationUserDialog.js
  nms/server/auth/express.js
Labels: component: nms, size/XS

#12717 fix(amf): UE Registration failure
  lte/gateway/c/core/oai/tasks/amf/Registration.cpp
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.cpp
  lte/gateway/c/core/oai/test/amf/amf_app_test_util.h
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/L, ready2merge

#12863 docs: Fixing typo in docs
  docs/docusaurus/versioned_docs/version-1.7.0/general/cloudstrapper_install.md
  docs/readmes/general/cloudstrapper_install.md
Labels: component: docs, size/XS

#13040 fix(nms): fix and pin version of API generation tools (js-beautify)
  .gitignore
  nms/generated/MagmaAPIBindings.js
  orc8r/cloud/Makefile
  orc8r/cloud/package.json
  orc8r/cloud/yarn.lock
Labels: component: orc8r, component: nms, size/XXL

#12835 chore: replace facebookincubator/magma with self references
  .github/workflows/build_all.yml
  cn/deploy/scripts/fluentd_prerequisites.sh
  feg/gateway/docker/go/Dockerfile
  feg/gateway/helm/feg-virtlet/README.md
  feg/gateway/helm/feg-virtlet/charts/secrets/Chart.yaml
  feg/radius/src/Dockerfile
  feg/radius/src/go.mod
  feg/radius/src/go.sum
  lte/cloud/go/tools/migrations/m007_na_cleanup/main.go
  lte/gateway/docker/deploy/Dockerfile
  nms/grafana/GrafanaErrorMessage.js
Labels: component: orc8r, component: nms, component: ci, component: feg, size/L, ready2merge, component: cwf

#12918 fix(amf): Service-reject for request with invalid Session-id
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_asDefs.h
  lte/gateway/c/core/oai/tasks/amf/amf_fsm.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, priority: high, size/M, product: 5g sa

#13045 chore: Remove unnecessary usage of deadsnakes ppa
  cwf/gateway/docker/python/Dockerfile
  feg/gateway/docker/python/Dockerfile
  orc8r/gateway/docker/Dockerfile
Labels: component: orc8r, component: feg, size/S, component: cwf

#12781 fix(agw): Reduced response wait time to save overall execution time
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
Labels: component: agw, size/XS

#12976 chore(enodebd): fix type errors to make mypy green
  lte/gateway/python/magma/enodebd/data_models/data_model.py
  lte/gateway/python/magma/enodebd/data_models/transform_for_magma.py
  lte/gateway/python/magma/enodebd/device_config/configuration_init.py
  lte/gateway/python/magma/enodebd/device_config/enodeb_configuration.py
  lte/gateway/python/magma/enodebd/devices/baicells.py
  lte/gateway/python/magma/enodebd/devices/baicells_old.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafa.py
  lte/gateway/python/magma/enodebd/devices/baicells_qafb.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb.py
  lte/gateway/python/magma/enodebd/devices/baicells_rts.py
  lte/gateway/python/magma/enodebd/devices/experimental/cavium.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/enodebd_iptables_rules.py
  lte/gateway/python/magma/enodebd/state_machines/acs_state_utils.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_impl.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_manager.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/stats_manager.py
  lte/gateway/python/magma/enodebd/tests/baicells_old_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_qafb_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_qrtb_tests.py
  lte/gateway/python/magma/enodebd/tests/baicells_tests.py
  lte/gateway/python/magma/enodebd/tests/cavium_tests.py
  lte/gateway/python/magma/enodebd/tests/enodeb_acs_states_tests.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
  lte/gateway/python/magma/enodebd/tests/test_utils/config_builder.py
  lte/gateway/python/magma/enodebd/tests/transform_for_magma_tests.py
  lte/gateway/python/magma/enodebd/tr069/models.py
Labels: component: agw, size/L, ready2merge

#13032 fix(agw): protobuf py files for agw are created
  lte/gateway/python/magma/enodebd/dp_client.py
  lte/gateway/python/magma/pipelined/ng_manager/node_state_manager.py
  lte/gateway/python/magma/subscriberdb/tests/client_tests.py
  lte/gateway/python/scripts/session_manager_cli.py
  lte/gateway/release/build-magma.sh
  orc8r/gateway/python/magma/configuration/tests/mconfigs_tests.py
  orc8r/gateway/python/magma/magmad/bootstrap_manager.py
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
  orc8r/gateway/python/magma/magmad/tests/bootstrap_manager_tests.py
  orc8r/gateway/python/magma/magmad/tests/config_manager_tests.py
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: agw, component: ci, size/M

#12368 fix(nms): Remove old configure option in NMS panel
  nms/app/components/LteConfigure.js
  nms/app/components/layout/__tests__/useSections-test.js
  nms/app/components/lte/LteSections.js
  nms/app/components/network/Apn.js
  nms/app/components/network/ApnEditDialog.js
  nms/app/components/network/DataPlanConfig.js
  nms/app/components/network/DataPlanEditDialog.js
  nms/app/components/network/NetworkConfig.js
Labels: component: nms, size/XXL

#13030 chore(ci): Remove legacy support for docker.bazelrc import
  .devcontainer/bazel-base/Dockerfile
Labels: component: ci, size/XS, ready2merge, bazel

#13054 fix(agw): 'make test_python_service UT_PATH=...' works correctly
  lte/gateway/python/Makefile
Labels: component: agw, size/XS, ready2merge

#13056 feat(lte): Switch EPS Auth service to use S6a proxy proto
  lte/cloud/go/go.mod
  lte/cloud/go/protos/eps_authentication.pb.go
  lte/cloud/go/services/eps_authentication/eps_authentication/main.go
  lte/cloud/go/services/eps_authentication/servicers/ai.go
  lte/cloud/go/services/eps_authentication/servicers/ai_test.go
  lte/cloud/go/services/eps_authentication/servicers/eps_auth_suite_test.go
  lte/cloud/go/services/eps_authentication/servicers/pur.go
  lte/cloud/go/services/eps_authentication/servicers/pur_test.go
  lte/cloud/go/services/eps_authentication/servicers/server.go
  lte/cloud/go/services/eps_authentication/servicers/ul.go
  lte/cloud/go/services/eps_authentication/servicers/ul_test.go
  lte/protos/eps_authentication.proto
Labels: component: orc8r, component: agw, size/XXL

#13065 fix(subscriberdb): Handle nil check correctly
  lte/cloud/go/services/subscriberdb/load.go
Labels: component: orc8r, size/XS

#13064 chore(ci): Make the GCC Warnings & Errors workflow run on master merges only
  .github/workflows/gcc-problems.yml
Labels: component: ci, size/XS, ready2merge

#13067 chore(ci): Make the bazel steps in the agw-workflow run on master merges only
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/S, ready2merge

#13059 fix(ci): Resolve the dpkg lock issue
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, size/S

#13001 chore(agw): move oai config generation into magmad container.
  lte/gateway/docker/docker-compose.yaml
  lte/gateway/docker/services/c/Dockerfile
Labels: component: ci, size/S, ready2merge

#13013 feat(dp): domain proxy services metrics implementation
  .dockerignore
  dp/cloud/docker/python/configuration_controller/Dockerfile
  dp/cloud/docker/python/radio_controller/Dockerfile
  dp/cloud/helm/dp/charts/domain-proxy/examples/orc8r_minikube_values.yaml
  dp/cloud/python/magma/configuration_controller/config.py
  dp/cloud/python/magma/configuration_controller/metrics.py
  dp/cloud/python/magma/configuration_controller/request_consumer/request_db_consumer.py
  dp/cloud/python/magma/configuration_controller/request_router/request_router.py
  dp/cloud/python/magma/configuration_controller/requirements.txt
  dp/cloud/python/magma/configuration_controller/response_processor/response_db_processor.py
  dp/cloud/python/magma/configuration_controller/run.py
  dp/cloud/python/magma/fluentd_client/client.py
  dp/cloud/python/magma/metricsd_client/__init__.py
  dp/cloud/python/magma/metricsd_client/client.py
  dp/cloud/python/magma/metricsd_client/config.py
  dp/cloud/python/magma/radio_controller/config.py
  dp/cloud/python/magma/radio_controller/metrics.py
  dp/cloud/python/magma/radio_controller/requirements.txt
  dp/cloud/python/magma/radio_controller/run.py
  dp/cloud/python/magma/radio_controller/services/active_mode_controller/service.py
  dp/cloud/python/magma/radio_controller/services/dp/service.py
  dp/cloud/python/magma/radio_controller/services/radio_controller/service.py
  dp/cloud/python/magma/test_runner/config.py
  dp/cloud/python/magma/test_runner/requirements.txt
  dp/cloud/python/magma/test_runner/tests/test_dp_with_orc8r.py
  orc8r/cloud/go/services/metricsd/servicers/protected/servicer.go
  orc8r/cloud/go/services/metricsd/servicers/protected/servicer_protected_test.go
  orc8r/lib/go/protos/metricsd.pb.go
  orc8r/protos/metricsd.proto
Labels: component: orc8r, size/XXL, ready2merge

#11621 feat(nms): Enable S8 configuration on federation gateways
  nms/app/components/feg/FEGGatewayDialog.js
  nms/app/state/feg_lte/NetworkState.js
  nms/app/views/equipment/FEGGatewayDetailConfig.js
  nms/app/views/equipment/FEGGatewayTable.js
  nms/app/views/equipment/__tests__/FEGGatewayDetailConfigTest.js
Labels: component: nms, size/L

#13062 fix(amf): Fixed the syncing of ambr values in initial context setup request
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
Labels: type: bug, component: agw, priority: medium, size/XS, product: 5g sa

#13011 fix(feg): renamed shadowed function which kept the feg orc8r cleanup …
  lte/gateway/python/integ_tests/federated_tests/fabfile.py
Labels: component: agw, size/XS

#13063 fix(agw): Fix glog path to be compatible with arm builds
  bazel/external/system_libraries.BUILD
Labels: size/XS, bazel

#13023 chore(agw): Determine Ubuntu AMI ID dynamically
  .github/workflows/amis-workflow.yml
  experimental/cloudstrapper/README.md
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/provision-instances.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/agw-devops.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/orc8r-devops.yaml
  experimental/cloudstrapper/playbooks/roles/devops-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
Labels: component: ci, size/M

#11952 feat(nms): Enable federation mapping configuration capability on federated LTE networks
  nms/app/e2e/__tests__/FegLte-test.js
  nms/app/views/network/FederationStyles.js
  nms/app/views/network/NetworkEdit.js
  nms/app/views/network/NetworkFederationConfig.js
  nms/app/views/network/NetworkInfo.js
Labels: component: nms, size/XL

#13070 fix(lte): Use last resort default subscriber profile in EPS UpdateLoation
  lte/cloud/go/services/eps_authentication/servicers/ul.go
  lte/cloud/go/services/eps_authentication/servicers/ul_test.go
Labels: component: orc8r, size/S

#13077 fix(agw): clash of installed pip packages and to be installed apt packages is resolved
  lte/gateway/release/pydep
Labels: component: ci, size/XS

#13052 chore(agw): 'nose' is replaced by 'pytest' for unittests
  lte/gateway/pytest.ini
  lte/gateway/python/Makefile
  lte/gateway/python/setup.py
  orc8r/gateway/python/pytest.ini
  orc8r/gateway/python/python.mk
Labels: component: orc8r, component: agw, size/M, ready2merge

#13029 fix(amf): AMF is processing the Auth-Response send after Identity-Req
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, priority: medium, size/M, product: 5g sa

#12635 feat(nms): Add Domain Proxy UI
  nms/app/components/AutorefreshCheckbox.js
  nms/app/components/context/CbsdContext.js
  nms/app/components/lte/LteContext.js
  nms/app/components/lte/LteMetrics.js
  nms/app/state/lte/CbsdState.js
  nms/app/views/domain-proxy/CbsdEdit.js
  nms/app/views/domain-proxy/Cbsds.js
  nms/app/views/domain-proxy/CbsdsTable.js
  nms/app/views/domain-proxy/LogsList.js
  nms/app/views/domain-proxy/__tests__/CbsdEdit.js
  nms/app/views/domain-proxy/__tests__/CbsdsTable.js
  nms/app/views/domain-proxy/__tests__/LogsList.js
  nms/app/views/equipment/EquipmentDashboard.js
  nms/flow-typed/npm/@testing-library/react_v10.x.x.js
  nms/server/apicontroller/routes.js
Labels: component: nms, size/XXL

#12869 chore: minor improvements to cwf and feg Dockerfiles
  cwf/gateway/docker/go/Dockerfile
  feg/gateway/docker/go/Dockerfile
Labels: component: feg, size/S, component: cwf

#13071 chore: Consolidate the bazel build and test options
  .bazelrc
  .github/workflows/bazel.yml
Labels: component: ci, size/XS, bazel

#13090 ci(nms): fix flow errors caused by domain proxy
  nms/app/views/domain-proxy/CbsdEdit.js
  nms/app/views/domain-proxy/__tests__/CbsdEdit.js
  nms/app/views/domain-proxy/__tests__/CbsdsTable.js
Labels: component: nms, size/S

#13088 fix(enodebd): Fix Domain Proxy installation params for Sercomm
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/dp_client.py
Labels: component: agw, size/S, ready2merge

#13048 feat(agw): authentication done via eps_authentication instead of subscriberdb
  lte/cloud/configs/eps_authentication.yml
  lte/cloud/configs/service_registry.yml
  lte/gateway/c/core/oai/lib/s6a_proxy/S6aClient.cpp
  orc8r/cloud/docker/controller/supervisord.conf
Labels: component: orc8r, component: agw, size/M

#13010 feat(agw): IPv6 data path support
  .github/workflows/bazel-cache-push.yml
  .github/workflows/build_all.yml
  .github/workflows/lte-integ-test.yml
  lte/gateway/Vagrantfile
  lte/gateway/configs/pipelined.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/trfserver/files/traffic_server.py
  lte/gateway/python/integ_tests/data/s1ap_tester_cfg/nbAppCfg.txt
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_disable_ipv6_iface.py
  lte/gateway/python/integ_tests/s1aptests/test_enable_ipv6_iface.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_util.py
  lte/gateway/python/magma/pipelined/app/uplink_bridge.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_access_control.AccessControlTestLocalIpBlockLTE.test_blocking_ip_match.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_access_control.AccessControlTestLocalIpBlockLTEIpV6.test_blocking_ip_match.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTestVlan.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNATTest_IP_VLAN_GW.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Static_IP_Test.testFlowSnapshotMatch.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_uplink_bridge.UplinkBridgeWithNonNatUplinkConnect_Test.testFlowSnapshotMatch.snapshot
  lte/gateway/python/scripts/config_iface_for_ipv6.py
Labels: component: agw, component: ci, size/L

#13072 chore(ci): Change the remote cache download behaviour to minimize traffic
  .bazelrc
  bazel/scripts/test_python_service_imports.sh
Labels: component: ci, size/S, bazel

#13089 feat(dp): Add available frequencies column
  dp/cloud/python/magma/db_service/migrations/versions/530b18568ad9_.py
  dp/cloud/python/magma/db_service/models.py
  dp/cloud/python/magma/db_service/tests/unit/test_530b18568ad9.py
Labels: component: orc8r, size/M

#13076 chore(dp): modify get cbsd state
  dp/cloud/go/protos/enodebd_dp.pb.go
  dp/cloud/python/magma/radio_controller/services/dp/service.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_dp_logs.py
  dp/cloud/python/magma/radio_controller/tests/unit/test_dp_service.py
  dp/cloud/python/magma/test_runner/tests/api_data_builder.py
  dp/cloud/python/magma/test_runner/tests/test_active_mode_controller.py
  dp/protos/enodebd_dp.proto
Labels: component: orc8r, size/L, component: dp

#13041 fix(orc8r): add reindexing of gateway subscriber state to subscriberdb indexer
  lte/cloud/configs/service_registry.yml
  lte/cloud/go/lte/const.go
  lte/cloud/go/serdes/serdes.go
  lte/cloud/go/services/subscriberdb/servicers/protected/indexer_servicer.go
  lte/cloud/go/services/subscriberdb/servicers/protected/indexer_servicer_test.go
  lte/cloud/go/services/subscriberdb/storage/subscriber_state.go
  lte/cloud/go/services/subscriberdb/storage/subscriber_state_test.go
  lte/cloud/go/services/subscriberdb/storage/test_utils.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
Labels: component: orc8r, size/L

#12633 feat(ci): add federated integ test to ci
  .github/workflows/federated-integ-test.yml
  lte/gateway/Vagrantfile
  lte/gateway/dev_tools.py
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/federated_tests/docker/docker-compose.override.yml
  lte/gateway/python/integ_tests/federated_tests/fabfile.py
  orc8r/tools/fab/dev_utils.py
Labels: component: orc8r, component: agw, component: ci, DONOTLAND, size/L

#12965 fix(agw): Migrated ue_id_coll hashlist to protobuf map
  lte/cloud/go/protos/oai/s1ap_state.pb.go
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/common/state_converter.cpp
  lte/gateway/c/core/oai/include/mme_init.hpp
  lte/gateway/c/core/oai/include/s1ap_state.hpp
  lte/gateway/c/core/oai/include/s1ap_types.hpp
  lte/gateway/c/core/oai/include/state_converter.hpp
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/gateway/c/core/oai/tasks/grpc_service/S1apServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/ha/ha_service_handler.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_timer_management.hpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers_with_injected_state.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_state_converter.cpp
  lte/protos/oai/s1ap_state.proto
Labels: component: orc8r, component: agw, size/XL

#13087 fix(orc8r): add k8s annotations to trigger subscriberdb for gateway_subscriber_state
  lte/cloud/helm/lte-orc8r/examples/minikube.values.yaml
  lte/cloud/helm/lte-orc8r/values.yaml
Labels: component: orc8r, size/XS

#13108 chore(agw): Make publish.sh executable
  lte/gateway/docker/publish.sh
Labels: component: ci, size/XS

#13104 chore(agw): Add NET_ADMIN capability to enodebd container
  lte/gateway/docker/docker-compose.yaml
Labels: component: ci, size/XS

#13125 chore(feg): fix slack username for feg
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/XS

#12915 docs: SUCI Extensions Documentation
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/assets/lte/create_new_lte_network_with_suciprofile.png
  docs/readmes/assets/lte/suci_format.png
  docs/readmes/assets/lte/update_existing_lte_network_with_suciprofile.png
  docs/readmes/lte/suci_extensions.md
Labels: component: docs, size/L

#13035 chore(agw): Update containerized-agw readme
  experimental/cloudstrapper/README.md
  lte/gateway/docker/README.md
  lte/gateway/docker/readme.md
Labels: component: ci, size/L

#13100 docs(agw): Updated quick start guide to add ipv6 range in /etc/vbox/networks.conf
  docs/readmes/basics/quick_start_guide.md
Labels: component: docs, size/XS

#13130 chore(feg): integ test vms are pulled from cache in order to prevent vagrant rate limit aka 429
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/S

#13137 chore(agw): Add recipe for running AGW containers locally
  lte/gateway/docker/README.md
Labels: component: ci, size/S

#13109 chore(agw): Replace deprecated include with include_task
  experimental/cloudstrapper/playbooks/roles/add-aws-ssh-key/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/agw-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/gw.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/aws-cleanup/tasks/orc8r.yaml
  experimental/cloudstrapper/playbooks/roles/build-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/build-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/control/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/magma-agw/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/test-framework/tasks/main.yaml
Labels: size/L

#13111 docs: Expand CWF integ test instructions
  docs/readmes/cwf/dev_testing.md
Labels: component: docs, size/M

#13143 fix(ci): Remove failing publishing step from FeG integ workflow
  .github/workflows/federated-integ-test.yml
Labels: component: ci, size/S, ready2merge

#13145 fix(dp): fixed get cbsd state response
  dp/cloud/python/magma/radio_controller/services/dp/service.py
  dp/cloud/python/magma/test_runner/tests/api_data_builder.py
  dp/cloud/python/magma/test_runner/tests/test_active_mode_controller.py
Labels: component: orc8r, size/S

#13150 fix(dp): Radio Controller unit tests fix
  dp/cloud/python/magma/radio_controller/tests/unit/test_dp_service.py
Labels: component: orc8r, size/XS, component: dp

#13159 ci(dp): Fix paths in job path_filter
  .github/workflows/dp-workflow.yml
Labels: component: ci, size/XS, component: dp

#13158 fix(agw): Pin Ansible version to fix installation
  lte/gateway/deploy/agw_install_ubuntu.sh
Labels: component: agw, size/XS

#12938 chore(agw): python syntax is adapted
  lte/gateway/python/integ_tests/common/service303_utils.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_messages.py
Labels: component: agw, size/M
