Repository magma/magma, pull requests merged in 2022-12, with the labels that each got.

#14569 chore(ci): Build docker containers with bazel cache in CI
  .github/workflows/composite/docker-builder/action.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  bazel/docker/Dockerfile.bazel.cache
Labels: component: ci, size/L, bazel

#14585 chore: Backport artifactory endpoint changes to v1.7
  .github/workflows/amis-workflow.yml
  .github/workflows/build_all.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/helm-deploy-on-demand.yml
  cwf/gateway/docker/.prod_env
  docs/readmes/orc8r/deploy_intro.md
  docs/readmes/orc8r/dev_minikube.md
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.community
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.custom
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.poc
  experimental/cloudstrapper/playbooks/roles/control/templates/main.tf.j2.production
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/vars/build.yaml
  feg/gateway/docker/.prod_env
  lte/gateway/deploy/agw_install_docker.sh
  lte/gateway/deploy/magma_dev_focal.yml
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
  lte/gateway/docker/ghz/Dockerfile
  lte/gateway/release/upgrade_magma.sh
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/poc/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
  orc8r/tools/helm/promote.sh
  orc8r/tools/packer/scripts/provision-stretch.sh
  xwf/gateway/deploy/roles/pkgrepo/tasks/debian.yml
Labels: component: orc8r, component: agw, component: docs, component: ci, component: feg, size/L, backported-v1.7, component: cwf, component: xwf

#14586 chore: double push to magma artifactory is removed
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  orc8r/tools/helm/package_lf.sh
Labels: component: orc8r, component: ci, size/L

#14596 fix: packages are looked for in the correct folder
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#14594 fix: Set latest tag for agwc images
  .github/workflows/agw-build-publish-container.yml
Labels: component: ci, size/M

#14468 fix: https://github.com/magma/security/issues/140
  lte/gateway/c/core/oai/tasks/mme_app/mme_config.cpp
Labels: component: agw, size/S

#14592 chore(ci): Create separate workflow for Golang version check
  .github/workflows/golang-check-version.yml
Labels: component: ci, size/M

#14593 chore(ci): Add convenience script for bazel setup in the VM
  bazel/scripts/build_and_run_bazelified_agw.sh
Labels: size/M, bazel

#14595 docs(lte): Update gateway VM bazel setup with convenience script
  docs/readmes/lte/s1ap_tests.md
  docs/readmes/lte/setup.md
Labels: component: docs, size/S, bazel

#14606 chore: the lf artifactory is setup during vm full_provision-ing
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, size/XS

#14577 chore(ci): Use tinder/bazel-diff for module import checking job
  .github/workflows/bazel.yml
  bazel/scripts/filter_test_targets.sh
Labels: component: ci, size/M, bazel

#14465 chore(ci): Build MME for the OAI-MME variant with Bazel for RHEL
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  lte/gateway/docker/mme/Dockerfile.rhel8
Labels: component: ci, size/M, bazel

#14588 fix(ci): ubuntu runners are pinned to 20.04
  .github/workflows/agw-docker-load-test.yaml
  .github/workflows/agw-workflow.yml
  .github/workflows/amis-workflow.yml
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/backport.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dco-check.yml
  .github/workflows/deploy-build-from-pr.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/gcc-problems.yml
  .github/workflows/golang-build-test.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/pr_bot.yml
  .github/workflows/python-workflow.yml
  .github/workflows/rebase.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/testim-workflow.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/L

#14618 fix(ci): apply correct test target for extended integ tests in contai…
  .github/workflows/agw-build-publish-container.yml
Labels: component: ci, size/XS

#14621 chore: update devcontainer in devcontainer.json
  .devcontainer/devcontainer.json
Labels: size/XS, artifactory

#14625 chore(ci): Simplify FeG Lint & Test workflow
  .github/workflows/feg-workflow.yml
Labels: component: ci, size/S

#14622 feat(ci): Add workflow to upload Go package to artifactory
  .github/workflows/magma-publish-go.yml
Labels: component: ci, size/M

#14573 docs(eventd): Remove reference to Make commands
  docs/readmes/lte/eventd.md
Labels: component: docs, size/M, bazel

#14642 chore(agw): Fix deprecated attributes in bazel dependencies
  bazel/asn1c.bzl
  bazel/python_swagger.bzl
Labels: size/XS, bazel

#14644 chore: rules_pkg is upgraded to a proper release version
  WORKSPACE.bazel
Labels: size/XS, bazel

#14454 ci: replace deprecated GitHub action commands for `set-output`
  .github/workflows/build_all.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/nms-workflow.yml
Labels: component: ci, size/L

#14639 chore(ci): Use pre-built buildifier in CI
  .github/workflows/bazel.yml
  bazel/scripts/run_buildifier.sh
Labels: component: ci, size/M, bazel

#14656 fix(ci): remove typo in failure message to slack
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/XS

#14657 Revert "ci: replace deprecated GitHub action commands for `set-output` (#14454)"
  .github/workflows/build_all.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/nms-workflow.yml
Labels: component: ci, size/L

#14626 chore(ci): Centralize the bazel-diff call in a new job
  .github/workflows/bazel.yml
Labels: component: ci, size/L, bazel

#14661 chore: lockfile is updated by pydep
  lte/gateway/release/magma.lockfile.ubuntu
Labels: component: ci, DONOTLAND, size/S

#14290 fix(agw): Converted gtpv1 task files to cpp
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/core/oai/include/gtpv1_u_messages_def.hpp
  lte/gateway/c/core/oai/include/gtpv1_u_messages_types.hpp
  lte/gateway/c/core/oai/include/gtpv1u_types.hpp
  lte/gateway/c/core/oai/include/messages_def.h
  lte/gateway/c/core/oai/include/messages_types.h
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerEvents.hpp
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerMain.hpp
  lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.hpp
  lte/gateway/c/core/oai/lib/pipelined_client/PipelinedClientAPI.hpp
  lte/gateway/c/core/oai/lib/pipelined_client/proto_converters.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.cpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.cpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u_sgw_defs.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u_task.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_task.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/test/openflow/test_gtp_app.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.hpp
Labels: component: agw, size/L

#14658 fix(ci): set correct names to test result artifacts
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/XS

#14474 refactor(ci): change Github action due to deprecation warning
  .github/workflows/composite/comment-on-pr/action.yml
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/L

#14649 chore(agw): Clean up integrated buildifier setup and update docs
  .devcontainer/bazel-base/README.md
  .github/workflows/bazel.yml
  BUILD.bazel
  WORKSPACE.bazel
  bazel/scripts/run_buildifier.sh
  docs/readmes/lte/dev_unit_testing.md
  orc8r/tools/ansible/roles/golang/tasks/main.yml
Labels: component: orc8r, component: docs, component: ci, size/M, bazel

#14643 feat(ci): enable publishing of containerized LTE integ test results
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/lte-integ-test-containerized.yml
  ci-scripts/firebase_publish_report.py
Labels: component: ci, size/M

#14662 ci: remove test lte integration with bazel workflow
  .github/workflows/lte-integ-test-bazel.yml
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/L

#14675 chore(ci): Remove the bazel-diff build from the Bazel Docker cache
  bazel/docker/Dockerfile.bazel.cache
Labels: component: ci, size/XS, bazel

#14677 fix(ci): finish if-else block correctly
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/XS

#14637 refactor(agw): replace scapy in packet_ryu_cli
  lte/gateway/python/scripts/BUILD.bazel
  lte/gateway/python/scripts/packet_ryu_cli.py
Labels: component: agw, size/S

#14636 refactor(agw): replace scapy in icmpv6.py
  lte/gateway/python/scripts/BUILD.bazel
  lte/gateway/python/scripts/icmpv6.py
Labels: component: agw, size/M

#14655 feat(ci): Run FeG radius unit tests in CI
  .github/workflows/feg-workflow.yml
  feg/radius/lib/go/oc/exporters/ods_test.go
  feg/radius/src/modules/coadynamic/coa_dynamic_test.go
  feg/radius/src/modules/coafixedip/coa_fixed_ip_test.go
  feg/radius/src/modules/coanas/coa_nas_test.go
  feg/radius/src/modules/eap/authstate/manager.memory_test.go
  feg/radius/src/modules/lbserve/lb_serve_test.go
  feg/radius/src/modules/proxy/proxy_test.go
  feg/radius/src/monitoring/scuba/scuba_test.go
  feg/radius/src/run.sh
  feg/radius/src/server/server_test.go
  feg/radius/src/session/storage.redis_test.go
Labels: component: ci, size/M, component: cwf

#14673 chore: traffic tests are waiting for started iperf instances
  lte/gateway/deploy/roles/trfserver/files/traffic_server.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
Labels: component: agw, size/M

#14571 chore(ci): Use bazel docker caches instead of remote cache for the bazel workflow
  .github/workflows/bazel.yml
Labels: component: ci, size/M, bazel

#14630 chore: build_all.yml on 1.8 uses the lf artifactory
  .github/workflows/build_all.yml
  ci-scripts/tag-push-docker.sh
  orc8r/tools/helm/package.sh
Labels: component: orc8r, component: ci, DONOTLAND, size/L

#14601 feat(ci): Adapt handling of LF's artifactory GPG key
  .devcontainer/bazel-base/Dockerfile
  .dockerignore
  .github/workflows/dp-workflow.yml
  cwf/gateway/docker/c/Dockerfile
  cwf/gateway/docker/go/Dockerfile
  cwf/gateway/docker/python/Dockerfile
  feg/gateway/docker/go/Dockerfile
  feg/gateway/docker/python/Dockerfile
  hil_testing/Magma_Ansible/project/roles/upgrade-prep/files/linux_foundation_registry_key.asc
  hil_testing/Magma_Ansible/project/roles/upgrade-prep/tasks/main.yaml
  keys/linux_foundation_registry_key.asc
  lte/gateway/deploy/roles/magma_deploy/files/linux_foundation_registry_key.asc
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
  lte/gateway/deploy/roles/magma_deploy/vars/all_master.yaml
  lte/gateway/docker/services/c/Dockerfile
  lte/gateway/docker/services/python/Dockerfile
  orc8r/gateway/docker/Dockerfile
  orc8r/tools/ansible/roles/pkgrepo/files/linux_foundation_registry_key.asc
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
Labels: component: orc8r, component: agw, component: ci, component: feg, size/L, component: cwf

#14682 fix: flaky and harmful ipv6 test is disabled for now
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/XS

#14694 chore(ci): Switch-off bazel remote cache for codespaces
  .devcontainer/post-create-commands.sh
Labels: component: ci, size/S, bazel

#14700 fix(agw): fix arp traffic in pipelined
  lte/gateway/deploy/roles/trfserver/files/udhcpd.conf
  lte/gateway/python/magma/pipelined/gw_mac_address.py
Labels: component: agw, size/XS

#14452 feat(orc8r): upgrade orchestrator docker base image
  orc8r/cloud/Makefile
  orc8r/cloud/docker/controller/Dockerfile
  orc8r/cloud/docker/controller/supervisor_logger.py
  orc8r/cloud/docker/controller/supervisord.conf
  orc8r/cloud/docker/nginx/Dockerfile
Labels: component: orc8r, size/M

#14674 feat(ci): Lint FeG radius in CI
  .github/workflows/feg-workflow.yml
  feg/radius/lib/go/http/auth/mac.go
  feg/radius/lib/go/http/server/config.go
  feg/radius/lib/go/log/rate_limit_core.go
  feg/radius/lib/go/log/rate_limit_core_test.go
  feg/radius/lib/go/oc/exporters/ods.go
  feg/radius/src/filters/lballocate/lb_allocate.go
  feg/radius/src/main.go
  feg/radius/src/main_test_manual.go
  feg/radius/src/modules/analytics/analytics.go
  feg/radius/src/modules/analytics/radius_session.go
  feg/radius/src/modules/coanas/coa_nas_test.go
  feg/radius/src/modules/eap/eap.go
  feg/radius/src/modules/eap/methods/akamagma/aka_magma.go
  feg/radius/src/modules/eap/methods/akatataipx/aka_packet.go
  feg/radius/src/modules/magmaacct/magma_acct.go
  feg/radius/src/modules/module_test_utils.go
  feg/radius/src/modules/ofpanalytics/ofpanalytics_test.go
  feg/radius/src/monitoring/ods/ods.go
  feg/radius/src/monitoring/ods/ods_test.go
  feg/radius/src/monitoring/operation.go
  feg/radius/src/run.sh
  feg/radius/src/server/server.go
  feg/radius/src/server/session_id.go
  feg/radius/src/server/udp_listener.go
Labels: component: ci, size/L, component: cwf

#14692 fix(ci): Fix FeG radius redis tests
  feg/radius/src/session/storage.common_test.go
  feg/radius/src/session/storage.memory_test.go
  feg/radius/src/session/storage.redis_test.go
Labels: size/S, component: cwf

#14697 chore(feg): Fix typos in FeG radius
  feg/radius/lib/go/oc/exporters/ods_test.go
  feg/radius/src/modules/eap/authstate/manager.memory_test.go
  feg/radius/src/session/storage.common_test.go
  feg/radius/src/session/storage.memory_test.go
  feg/radius/src/session/storage.redis_test.go
  feg/radius/src/session/storage_test.go
Labels: size/S, component: cwf

#14698 fix(ci): Fix TestPostODS in FeG radius
  feg/radius/lib/go/oc/exporters/ods_test.go
Labels: size/XS, component: cwf

#14703 docs: Link docusaurus pages that are missing links
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/contributing/contribute_onboarding.md
  docs/readmes/contributing/contribute_workflow.md
  docs/readmes/cwf/troubleshooting.md
  docs/readmes/feg/session_proxy.md
  docs/readmes/lte/sessiond.md
  docs/readmes/lte/setup.md
Labels: component: docs, size/L

#14660 chore: Add bazel AGW build alias
  .devcontainer/bazel-base/Dockerfile
  BUILD.bazel
  bazel/test_constants.bzl
  feg/gateway/services/envoy_controller/BUILD.bazel
  lte/gateway/c/connection_tracker/src/BUILD.bazel
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/c/li_agent/src/BUILD.bazel
  lte/gateway/c/sctpd/src/BUILD.bazel
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/deploy/roles/bazel_aliases/tasks/main.yml
  lte/gateway/python/magma/health/BUILD.bazel
  lte/gateway/python/magma/kernsnoopd/BUILD.bazel
  lte/gateway/python/magma/mobilityd/BUILD.bazel
  lte/gateway/python/magma/monitord/BUILD.bazel
  lte/gateway/python/magma/policydb/BUILD.bazel
  lte/gateway/python/magma/redirectd/BUILD.bazel
  lte/gateway/python/magma/smsd/BUILD.bazel
  orc8r/gateway/python/magma/eventd/BUILD.bazel
Labels: component: orc8r, component: agw, component: feg, size/L, bazel

#14614 ci: github workflow builds and uploads ovs
  .github/workflows/magma-build-openvswitch.yml
  third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh
Labels: component: agw, component: ci, size/L

#14687 ci: remove lte dev integ test handling in publishing script
  ci-scripts/firebase_publish_report.py
Labels: component: ci, DONOTLAND, size/XS

#14708 docs: Replace make run with bazel steps in the quick start guide
  docs/readmes/basics/quick_start_guide.md
Labels: component: docs, size/XS, bazel

#14712 fix(agw): Revert "fix arp traffic in pipelined (#14700)"
  lte/gateway/deploy/roles/trfserver/files/udhcpd.conf
  lte/gateway/python/magma/pipelined/gw_mac_address.py
Labels: component: agw, size/XS

#14701 fix(ci): Fix flakiness of radius tests with sleep
  feg/radius/src/modules/coafixedip/coa_fixed_ip_test.go
  feg/radius/src/modules/coanas/coa_nas_test.go
  feg/radius/src/modules/lbserve/lb_serve_test.go
  feg/radius/src/modules/module_test_utils.go
Labels: size/S, component: cwf

#14654 chore: Migrate enb_ue_s1ap_id_ue_context_htbl in mme_app to protobuf map
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/gateway/c/core/oai/include/mme_app_ue_context.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/protos/oai/mme_nas_state.proto
Labels: component: orc8r, component: agw, size/L

#14686 chore(ci): Add release build and coverage to docker bazel cache
  .github/workflows/composite/docker-builder/action.yml
  .github/workflows/docker-builder-devcontainer.yml
  bazel/docker/Dockerfile.bazel.cache
Labels: component: ci, size/S, bazel

#14713 fix(ci): output test_status from containerized integ tests correctly
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/M

#14689 chore(ci): Use bazel Docker cache in the agw-coverage workflow
  .github/workflows/agw-coverage.yml
Labels: component: ci, DONOTLAND, size/S, bazel

#14704 ci: verify input and restrict publishing
  .github/workflows/magma-build-3rd-party.yml
Labels: component: ci, size/M

#14720 chore: magma and sctpd have a license set in deb meta data
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/update_deb_meta_info.sh.template
Labels: component: ci, size/S

#14693 chore(ci): Switch-off the bazel remote cache for the python sudo tests
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, DONOTLAND, size/XS, bazel

#14721 fix: clone repo from new location without redirection
  .devcontainer/Dockerfile
Labels: size/XS

#14723 fix(ci): upload correct GHz images
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/composite/docker-builder-agw/action.yml
Labels: component: ci, size/S

#14714 chore: Add bazel profile option for integration tests
  bazel/scripts/run_integ_tests.sh
Labels: size/M, bazel

#14711 chore: Add helpful logging for executing the manual tests
  bazel/python_test.bzl
  bazel/python_utils/BUILD.bazel
  bazel/python_utils/conftest.py
  bazel/scripts/run_load_tests.sh
  bazel/test_constants.bzl
  lte/gateway/python/load_tests/BUILD.bazel
Labels: component: agw, size/L, bazel

#14684 ci: switch to linux foundation artifactory in promotion workflows
  .github/workflows/docker-promote.yml
  .github/workflows/helm-promote.yml
  orc8r/tools/docker/promote.sh
Labels: component: orc8r, component: ci, size/M

#14635 refactor(agw): separate dhcp helper cli
  bazel/scripts/run_sudo_tests.sh
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/docker/services/python/Dockerfile
  lte/gateway/python/dhcp_helper_cli/BUILD.bazel
  lte/gateway/python/dhcp_helper_cli/LICENSE
  lte/gateway/python/dhcp_helper_cli/README.md
  lte/gateway/python/dhcp_helper_cli/dhcp_helper_cli.py
  lte/gateway/python/dhcp_helper_cli/tests/BUILD.bazel
  lte/gateway/python/dhcp_helper_cli/tests/test_dhcp_helper_cli.py
  lte/gateway/python/magma/mobilityd/BUILD.bazel
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/tests/BUILD.bazel
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp.py
  lte/gateway/python/scripts/BUILD.bazel
  lte/gateway/python/setup.py
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/build-magma.sh
  lte/gateway/release/deb_dependencies.bzl
  lte/gateway/release/magma.lockfile.ubuntu
  lte/gateway/release/update_deb_meta_info.sh.template
Labels: component: agw, component: ci, size/XL

#14733 fix(agw): Fix build-magma.sh after refactoring
  lte/gateway/release/build-magma.sh
Labels: component: ci, size/S

#14722 chore: magma deb artifacts package a license file
  BUILD.bazel
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/build-magma.sh
Labels: component: ci, size/S

#14735 fix(agw): Fix name of DHCP CLI helper in Bazel build
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/deb_dependencies.bzl
Labels: component: ci, size/XS

#14736 ci: simplify message handling sent to Slack
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/build_all.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/nms-workflow.yml
Labels: component: ci, size/L

#14683 chore(orc8r): Fix error handling for obsidian handlers
  lte/cloud/go/services/lte/obsidian/handlers/handlers.go
Labels: component: orc8r, size/M

#14732 refactor(agw): Add type hints
  lte/gateway/python/dhcp_helper_cli/dhcp_helper_cli.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp_with_vlan.py
Labels: component: agw, size/M

#14742 fix(agw): build-magma.sh adds license for magma and dhcp package
  lte/gateway/release/build-magma.sh
Labels: component: ci, size/XS

#14739 refactor(agw): Improve dhcp_helper_cli.py help
  lte/gateway/python/dhcp_helper_cli/dhcp_helper_cli.py
Labels: component: agw, size/S

#14755 fix(feg): fix error messages in go http endpoints in feg
  feg/cloud/go/services/feg/obsidian/handlers/handlers.go
  feg/gateway/services/n7_n40_proxy/n7/notifier_handler.go
Labels: component: feg, size/S

#14757 fix(cwg): fix error messages in go http endpoints in cwag
  cwf/cloud/go/services/cwf/obsidian/handlers/handlers.go
Labels: size/M, component: cwf

#14749 fix(agw): Reduce minimum version required for scapy
  lte/gateway/release/build-magma.sh
Labels: component: ci, size/XS

#14737 chore(agw): Declare conflicting packages
  lte/gateway/release/BUILD.bazel
  lte/gateway/release/deb_dependencies.bzl
Labels: component: ci, size/L, bazel

#14234 fix(pipelined): added changes for ovs flows of table 13
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/restart_mixin.py
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_with_stateless_enforcement_restart.after_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_with_stateless_enforcement_restart.before_restart.snapshot
  lte/gateway/python/magma/pipelined/tests/snapshots/test_restart_resilience.RestartResilienceTest.test_with_stateless_enforcement_restart.default_flows.snapshot
  lte/gateway/python/magma/pipelined/tests/test_enforcement.py
  lte/gateway/python/magma/pipelined/tests/test_enforcement_5g.py
  lte/gateway/python/magma/pipelined/tests/test_gy.py
  lte/gateway/python/magma/pipelined/tests/test_he.py
  lte/gateway/python/magma/pipelined/tests/test_redirect.py
  lte/gateway/python/magma/pipelined/tests/test_restart_resilience.py
Labels: component: agw, size/L, ready2merge

#14759 fix(pipelined): Set timeout for socket when getting mac address
  lte/gateway/python/magma/pipelined/gw_mac_address.py
Labels: component: agw, size/XS

#14756 fix(dp): fix error messages in go http endpoints in dp
  dp/cloud/go/services/dp/obsidian/cbsd/handlers.go
  dp/cloud/go/services/dp/obsidian/log/handlers.go
Labels: component: orc8r, size/M

#14670 fix(agw): Fixed display of flaky retry enabled flag
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, size/XS

#14731 feat(agw): Use json file to communicate with the DHCP helper cli
  lte/gateway/python/dhcp_helper_cli/dhcp_helper_cli.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp.py
Labels: component: agw, size/L

#14763 fix(agw): change remote location of liblfds
  bazel/cpp_repositories.bzl
Labels: size/XS

#14764 fix(agw): change remote location of liblfds in third party build
  third_party/build/bin/liblfds_build.sh
Labels: component: ci, size/XS

#14765 fix(agw): change remote location of liblfds in docker container
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: ci, size/XS

#14766 fix(agw): change remote location of libgtpnl in docker container
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  third_party/gtp_ovs/ovs-gtp-patches/2.15/dev.sh
Labels: component: agw, component: ci, size/XS

#14750 fix(ci): assign correct SHA to CI runs triggered by `repository_dispatch`
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-magma-deb.yml
Labels: component: ci, size/S

#14772 chore: NamedTuple looks nice (+ some f-string-ification)
  lte/gateway/python/integ_tests/common/service303_utils.py
  lte/gateway/python/integ_tests/s1aptests/util/traffic_messages.py
Labels: component: agw, size/M

#14775 chore(ci): remove unused firebase_admin installation
  .github/workflows/lte-integ-test-magma-deb.yml
Labels: component: ci, size/XS

#14776 fix(ci): use correct prefix for CWF images
  .github/workflows/cwf-integ-test.yml
Labels: component: ci, size/XS

#14779 fix(agw): add LTE_ROOT to icmpv6 imports
  lte/gateway/python/scripts/BUILD.bazel
Labels: component: agw, size/XS

#14778 fix(ci): adapt prefix for CWF images to the one expected in the fabfile
  .github/workflows/cwf-integ-test.yml
Labels: component: ci, size/S
