Repository magma/magma, pull requests merged in 2022-01, with the labels that each got.

#10995 fix(amf): As part of handling PDU session release complete, added logic to invoke PDU_Release gRPC handler towards SMF, when UE context is REGISTERED_CONNECTED and related PDU session state is INACTIVE
  lte/gateway/c/core/oai/tasks/amf/amf_fsm.cpp
Labels: component: agw, size/XS

#11038 test(agw): Add UE static IP integ test
  lte/gateway/configs/mobilityd.yml
  lte/gateway/python/integ_tests/common/subscriber_db_client.py
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_static_ip.py
Labels: component: agw, size/M

#10933 fix(amf): Send the concerned PDU sessions to be released info to SMF upon t3592…
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/M

#11053 chore(agw): consolidate eBPF code deployment dir
  lte/gateway/python/magma/kernsnoopd/snooper.py
  lte/gateway/release/build-magma.sh
Labels: component: agw, component: ci, size/XS

#10992 fix: bump orc8r helm chart
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
Labels: component: orc8r, size/XS

#10947 docs(agw): update sentry doc to reflect CI changes
  docs/readmes/lte/configure_sentry.md
Labels: component: docs, size/S

#10972 fix(amf): Correct SubscriberID set as "IMSI +number" in amf
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.cpp
  lte/gateway/c/core/oai/lib/n11/SmfServiceClient.h
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/prepare_request_for_smf.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/test/n11/test_smf_service_client.cpp
Labels: component: agw, size/M

#11060 fix(ci): Fix provisioning of magma_test vm
  orc8r/tools/ansible/roles/pkgrepo/tasks/debian.yml
Labels: component: orc8r, size/XS

#11063 fix(cwg): Add bcc-tools package dependency
  cwf/gateway/docker/python/Dockerfile
Labels: size/XS, component: cwf

#11066 fix(agw): move lld install step to magma vm only
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
Labels: component: agw, size/S

#10926 feat(agw): Added unit test case to validate the handling of modify bearer request
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/test/sgw_s8_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test_attach_proc.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
Labels: component: agw, size/M

#11042 fix(amf): fix for the issue 10925
  lte/gateway/c/core/oai/lib/n11/M5GAuthenticationServiceClient.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/M, ready2merge

#11008 fix(amf): Support for dotted dnn encoding and decoding
  lte/gateway/c/core/oai/tasks/nas5g/src/ies/M5GDNN.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
Labels: component: agw, size/M

#10751 fix(amf): Authentication reject for Security mode failure
  lte/gateway/c/core/oai/tasks/amf/amf_authentication.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: type: bug, component: agw, priority: medium, size/M, product: 5g sa

#11074 fix(agw): s1ap_test: handle missing static ip config.
  lte/gateway/python/integ_tests/common/subscriber_db_client.py
Labels: component: agw, size/XS

#11049 fix(agw): Added code to log emm cause in string format
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.301.h
  lte/gateway/c/core/oai/tasks/nas/emm/Attach.c
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_send.c
Labels: component: agw, size/M

#11013 chore: upgrade hosted-git-info
  nms/package.json
  nms/yarn.lock
Labels: component: nms, size/XL

#10528 feat: Magma Domain Domain Proxy - helm charts
  .github/workflows/config/yamllint_config.yml
  dp/cloud/helm/dp/charts/domain-proxy/.helmignore
  dp/cloud/helm/dp/charts/domain-proxy/Chart.yaml
  dp/cloud/helm/dp/charts/domain-proxy/README.md
  dp/cloud/helm/dp/charts/domain-proxy/certificates/.gitkeep
  dp/cloud/helm/dp/charts/domain-proxy/certificates/configuration_controller/.gitkeep
  dp/cloud/helm/dp/charts/domain-proxy/certificates/protocol_controller/.gitkeep
  dp/cloud/helm/dp/charts/domain-proxy/examples/aws_contour_values.yaml
  dp/cloud/helm/dp/charts/domain-proxy/examples/aws_nginx_values.yaml
  dp/cloud/helm/dp/charts/domain-proxy/examples/minikube_values.yaml
  dp/cloud/helm/dp/charts/domain-proxy/examples/minikube_values_nginx.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/NOTES.txt
  dp/cloud/helm/dp/charts/domain-proxy/templates/_helpers.tpl
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/hpa.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/pdb.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/active_mode_controller/serviceaccount.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/ca.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/ccm.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/cm.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/hpa.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/ingress.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/pdb.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/secret.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/service.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/serviceaccount.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/configuration_controller/tls.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/db_service/job.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/db_service/secret.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/db_service/serviceaccount.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/ca.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/cm.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/hpa.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/httpproxy.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/ingress.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/pdb.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/service.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/serviceaccount.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/tls.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/deployment.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/hpa.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/orc8r-service.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/pdb.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/secret.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/service.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/radio_controller/serviceaccount.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/tests/protocol_controller-test.yaml
  dp/cloud/helm/dp/charts/domain-proxy/templates/tests/radio_controller-test.yaml
  dp/cloud/helm/dp/charts/domain-proxy/values.yaml
  dp/skaffold.yaml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/helm/orc8r/values.yaml
  orc8r/tools/helm/package.sh
Labels: component: orc8r, component: ci, size/XXL

#11062 fix(cwg): Fix minor param parsing bug
  cwf/gateway/fabfile.py
  cwf/gateway/go.mod
  cwf/gateway/go.sum
Labels: size/S, component: cwf

#11069 fix(agw): logging is formatted for sentry usage
  lte/gateway/python/magma/mobilityd/subscriberdb_client.py
Labels: component: agw, size/S, ready2merge

#11078 fix(orc8r): Revert additonal labels from k8s services to avoid incompatibilities with deployed objects
  lte/gateway/deploy/agwc-helm-charts/templates/_helpers.tpl
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
  orc8r/cloud/helm/orc8r/charts/nms/templates/helpers/labels.tpl
  orc8r/cloud/helm/orc8r/templates/_helpers.tpl
  orc8r/cloud/helm/orc8rlib/templates/_helpers.tpl
Labels: component: orc8r, component: agw, size/S

#11098 docs: enhance the CI checks doc with guidelines on adding a new check
  docs/docusaurus/i18n/en.json
  docs/readmes/contributing/contribute_ci_checks.md
Labels: component: docs, size/S

#11095 fix(agw): Rendering strings is done by logging framework
  lte/gateway/python/magma/mobilityd/ip_address_man.py
  lte/gateway/python/magma/mobilityd/ip_allocator_static.py
  lte/gateway/python/magma/mobilityd/ipv6_allocator_pool.py
  lte/gateway/python/magma/mobilityd/subscriberdb_client.py
  lte/gateway/python/magma/mobilityd/utils.py
Labels: component: agw, size/M, ready2merge

#11052 test(agw): Add non-nat datapath integ test
  lte/gateway/configs/gateway.mconfig
  lte/gateway/configs/mobilityd.yml
  lte/gateway/configs/pipelined.yml
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_non_nat_dp_ul_tcp.py
Labels: component: agw, size/L

#10948 feat(agw): IPv6 paging support
  lte/gateway/c/core/oai/include/s11_messages_types.h
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerEvents.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerEvents.h
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerMain.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/ControllerMain.h
  lte/gateway/c/core/oai/lib/openflow/controller/PagingApplication.cpp
  lte/gateway/c/core/oai/lib/openflow/controller/PagingApplication.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u.h
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.c
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_ip_imsi.h
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/test/mme_app_task/mme_app_test_util.cpp
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_paging_with_dedicated_bearer.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_paging_with_dedicated_bearer.py
  lte/gateway/python/scripts/icmpv6.py
  lte/gateway/python/setup.py
Labels: component: agw, size/XXL, ready2merge

#10974 fix(feg): refactor sbi client and config
  feg/gateway/sbi/mocks/mock_pcf.go
  feg/gateway/sbi/sbi.go
  feg/gateway/sbi/sbi_test.go
  feg/gateway/sbi/specs/TS29512NpcfSMPolicyControl/TS29512NpcfSMPolicyControl.gen.go
  feg/gateway/services/n7_n40_proxy/n7/config.go
  feg/gateway/services/n7_n40_proxy/n7/config_test.go
  feg/gateway/services/n7_n40_proxy/n7/mocks/ClientWithResponsesInterface.go
  feg/gateway/services/n7_n40_proxy/n7/n7.go
  feg/gateway/services/n7_n40_proxy/n7/notifier_handler.go
  feg/gateway/services/n7_n40_proxy/n7/notifier_handler_test.go
  feg/gateway/services/n7_n40_proxy/n7_n40_proxy/main.go
  feg/gateway/services/n7_n40_proxy/servicers/create_session.go
  feg/gateway/services/n7_n40_proxy/servicers/create_session_test.go
  feg/gateway/services/n7_n40_proxy/servicers/health.go
  feg/gateway/services/n7_n40_proxy/servicers/session_controller.go
  feg/gateway/services/n7_n40_proxy/servicers/terminate_session.go
  feg/gateway/services/n7_n40_proxy/servicers/terminate_session_test.go
  feg/gateway/services/n7_n40_proxy/servicers/update_session.go
  feg/gateway/services/n7_n40_proxy/servicers/update_session_test.go
Labels: component: feg, size/XL

#10530 feat: Magma Domain Proxy - AGW LTE enodebd
  lte/gateway/configs/enodebd.yml
  lte/gateway/python/defs.mk
  lte/gateway/python/magma/enodebd/data_models/data_model_parameters.py
  lte/gateway/python/magma/enodebd/device_config/cbrs_consts.py
  lte/gateway/python/magma/enodebd/device_config/configuration_util.py
  lte/gateway/python/magma/enodebd/device_config/enodeb_configuration.py
  lte/gateway/python/magma/enodebd/devices/baicells_qrtb.py
  lte/gateway/python/magma/enodebd/devices/device_map.py
  lte/gateway/python/magma/enodebd/devices/device_utils.py
  lte/gateway/python/magma/enodebd/devices/freedomfi_one.py
  lte/gateway/python/magma/enodebd/dp_client.py
  lte/gateway/python/magma/enodebd/state_machines/acs_state_utils.py
  lte/gateway/python/magma/enodebd/state_machines/enb_acs_states.py
  lte/gateway/python/magma/enodebd/tests/baicells_qrtb_tests.py
  lte/gateway/python/magma/enodebd/tests/device_utils_tests.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
  lte/gateway/python/magma/enodebd/tests/get_params_tests.py
  lte/gateway/python/magma/enodebd/tests/spyne_mods_tests.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enb_acs_builder.py
  lte/gateway/python/magma/enodebd/tests/test_utils/tr069_msg_builder.py
  lte/gateway/python/magma/enodebd/tr069/rpc_methods.py
  lte/gateway/python/magma/enodebd/tr069/spyne_mods.py
  lte/gateway/python/setup.py
Labels: component: agw, size/XXL

#10843 feat(ci): New Docker AGW AMI And GHZ AGW load test
  .github/workflows/agw-docker-load-test.yaml
  .github/workflows/amis-workflow.yml
  experimental/cloudstrapper/playbooks/docker-ami-configure.yaml
  experimental/cloudstrapper/playbooks/docker-ami-init.yaml
  experimental/cloudstrapper/playbooks/docker-ami-provision.yaml
  experimental/cloudstrapper/playbooks/docker-cleanup.yaml
  experimental/cloudstrapper/playbooks/ghz-run-remote.yaml
  experimental/cloudstrapper/playbooks/ghz-run.yaml
  experimental/cloudstrapper/playbooks/roles/docker-cleanup/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-cleanup/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-infra/tasks/key.yaml
  experimental/cloudstrapper/playbooks/roles/docker-infra/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-infra/tasks/provision-instance.yaml
  experimental/cloudstrapper/playbooks/roles/docker-infra/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-platform/tasks/init-docker.yaml
  experimental/cloudstrapper/playbooks/roles/docker-platform/tasks/install-root-ca.yaml
  experimental/cloudstrapper/playbooks/roles/docker-platform/tasks/magma-repo.yaml
  experimental/cloudstrapper/playbooks/roles/docker-platform/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-platform/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-snapshot/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/docker-snapshot/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/run-tests.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/setup-tests.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-run/files/ansible.cfg
  experimental/cloudstrapper/playbooks/roles/ghz-run/tasks/main.yaml
  experimental/cloudstrapper/playbooks/roles/ghz-run/vars/main.yaml
  lte/gateway/deploy/agw_install_docker.sh
  lte/gateway/docker/ghz/docker-compose.yaml
Labels: component: agw, component: ci, size/L

#11073 fix(sessiond): Refactor sessiond code that manages session state enum Se...
  lte/gateway/c/session_manager/EnumToString.cpp
  lte/gateway/c/session_manager/SessionState.cpp
  lte/gateway/c/session_manager/SessionStateEnforcer.cpp
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/Types.h
Labels: component: agw, size/S

#11043 fix(sessiond): Fixing failure of paging with Multi PDU Session
  lte/gateway/c/session_manager/SetMessageManagerHandler.cpp
  lte/gateway/c/session_manager/UpfMsgManageHandler.cpp
  lte/gateway/c/session_manager/Utilities.cpp
  lte/gateway/c/session_manager/Utilities.h
Labels: component: agw, size/M

#11117 fix(ci): Queue AGW load tests
  .github/workflows/agw-docker-load-test.yaml
Labels: component: ci, size/XS

#11110 fix(ci): Missing space on deploy build from PR
  .github/workflows/deploy-build-from-pr.yml
Labels: component: ci, size/XS

#10531 feat: Magma Domain Proxy - Github workflows
  .github/workflows/dp-workflow.yml
Labels: component: ci, size/L

#11037 feat(agw): Add EBPF DL flow logic
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/python/magma/pipelined/ebpf/ebpf_dl_handler.c
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
  lte/gateway/python/magma/pipelined/tests/script/ip-packet.py
  lte/gateway/python/magma/pipelined/tests/test_ebpf_dl_dp.py
Labels: component: agw, size/L

#11084 fix(agw): openvswitch fab based packaging
  lte/gateway/fabfile.py
  third_party/gtp_ovs/ovs-gtp-patches/2.15/build.sh
Labels: component: agw, size/XS

#11103 chore(agw): drop support for kernel 4.9
  third_party/gtp_ovs/kernel-4.9/2.8.10/0001-datapath-add-vport-gtp-for-GPRS-Tunneling-Protocol.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0002-userspace-Add-L3-tunnel-type-GTP.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0003-Build-symbols-for-gtp-vport-linux-4.9-module-require.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0004-ovs-datapath-fix-stretch-kernel-update.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0005-Add-custom-IPDR-fields-for-IPFIX-export.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0006-ovs-Handle-spaces-in-ovs-arguments.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0007-Add-pdp_start_epoch-custom-field-to-IPFIX-export.patch
  third_party/gtp_ovs/kernel-4.9/2.8.10/0008-odp-act.patch
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/Makefile
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/README.md
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/gtp.c
  third_party/gtp_ovs/kernel-4.9/gtp-v4.9-backport/scripts/after-install.sh
Labels: component: agw, size/XXL

#10529 feat: Magma Domain Proxy - orc8r deploy
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/secrets.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: component: orc8r, size/L

#10970 feat(amf): Additional unit test support for NGAP
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_ta.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_common.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_common.h
  lte/gateway/c/core/oai/test/ngap/CMakeLists.txt
  lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
  lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp
Labels: component: agw, size/L

#11123 fix(agw): Adding fix for run time error seen after make run
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.c
Labels: component: agw, size/S

#11142 fix(ci): fix concurrency group in agw load test
  .github/workflows/agw-docker-load-test.yaml
Labels: component: ci, size/XS

#11036 feat(agw): Create Load tests for SubscriberDB.
  lte/gateway/python/load_tests/defs.mk
  lte/gateway/python/load_tests/loadtest_subscriberdb.py
  lte/gateway/python/setup.py
Labels: component: agw, size/L, ready2merge

#11127 fix(orc8r): orc8r-obsidian pod crash fix
  orc8r/cloud/helm/orc8r/values.yaml
Labels: component: orc8r, size/XS

#11111 fix(agw): Handle failed IP allocation
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
Labels: component: agw, size/S, ready2merge

#11145 fix(ci): deploy build on pr fix
  .github/workflows/deploy-build-from-pr.yml
Labels: component: ci, size/XS

#11144 feat(agw): Add subscriberdb loadtests to loadtest dashboard.
  experimental/cloudstrapper/playbooks/roles/ghz-platform/vars/main.yaml
Labels: size/S

#11138 test(agw): Additional s1sim test for TAU with eps bearer context status IE
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_eps_bearer_context_status_multiple_ded_bearer_deact.py
Labels: component: agw, size/L

#11048 test(mme): UT for delete bearer command
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
Labels: component: agw, size/L

#11130 fix(agw): Do not overwrite rootCA
  lte/gateway/release/build-magma.sh
Labels: component: ci, size/XS

#11147 fix(s8_proxy): inject u_agw_teid to create session response
  feg/gateway/services/s8_proxy/servicers/s8_proxy_test.go
  feg/gateway/services/s8_proxy/servicers/senders.go
Labels: component: feg, size/XS

#11109 fix(amf): Send proper imsi value from subscriberDB in gRPC towards AM…
  lte/gateway/c/core/oai/lib/n11/M5GAuthenticationServiceClient.cpp
Labels: component: agw, size/S, ready2merge

#11146 fix(feg_hello): remove timezone from timestamps
  lte/gateway/python/scripts/feg_hello_cli.py
Labels: component: agw, size/XS

#10957 fix: s6a_proxy fix bug on VisitedPLMNID type
  feg/gateway/services/s6a_proxy/servicers/s6a_definitions.go
  feg/gateway/services/s6a_proxy/servicers/test/test_s6a_server.go
  feg/gateway/services/testcore/hss/servicers/ai.go
  feg/gateway/services/testcore/hss/servicers/ai_test.go
  feg/gateway/services/testcore/hss/servicers/ul_test.go
Labels: component: feg, size/M

#11153 feat(feg_relay): inject sgwUteid on CreateSession and CreateBearer
  feg/cloud/go/services/feg_relay/gw_to_feg_relay/servicers/s8_relay.go
  feg/cloud/go/services/feg_relay/servicers/s8_bearer_pgw.go
  feg/cloud/go/services/feg_relay/utils/get_teids.go
  orc8r/cloud/go/services/orchestrator/servicers/indexer_servicer.go
Labels: component: orc8r, component: feg, size/L

#11154 fix(ci): add "dp" to allowed pr semantic scope
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/XS

#11156 fix: Magma domain proxy helm chart default version
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
Labels: component: orc8r, size/XS

#11108 chore(agw): add logs to indicate sentry config source for dsn and sample rate
  orc8r/gateway/python/magma/common/sentry.py
Labels: component: orc8r, size/S

#11187 docs: special networking setup required to run VM locally
  docs/readmes/basics/quick_start_guide.md
Labels: component: docs, size/XS

#11197 fix(ci): Timeout on pushing results to load test api
  experimental/cloudstrapper/playbooks/roles/ghz-platform/tasks/run-tests.yaml
Labels: size/S

#11181 chore(deps): Upgrade lxml from 4.6.3 to 4.7.1
  lte/gateway/python/setup.py
Labels: component: agw, size/XS

#11150 fix(agw): Fixed RAR activation reject
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_rar_activation_reject.py
Labels: component: agw, size/M

#10535 fix(agw): Re-enabled timer test cases
  lte/gateway/python/integ_tests/defs.mk
Labels: component: agw, size/S

#10509 fix(agw): Updated non sanity configuration
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_modify_config_for_non_sanity.py
  lte/gateway/python/integ_tests/s1aptests/test_restore_config_after_non_sanity.py
Labels: component: agw, size/M

#10904 feat(sctpd): Enable mconfig and Sentry monitoring
  .github/workflows/build_all.yml
  bazel/external/sentry_native.BUILD
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/cloud/go/services/lte/servicers/builder_servicer_test.go
  lte/gateway/c/sctpd/src/BUILD.bazel
  lte/gateway/c/sctpd/src/CMakeLists.txt
  lte/gateway/c/sctpd/src/sctpd.cpp
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/gateway/configs/sctpd.yml
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/protos/mconfig/mconfigs.proto
  orc8r/gateway/c/common/sentry/includes/SentryWrapper.h
  orc8r/protos/BUILD.bazel
Labels: component: orc8r, component: agw, component: ci, size/XL, ready2merge

#11198 docs: Add back sentry config document
  docs/readmes/lte/configure_sentry.md
Labels: component: docs, size/XS

#11210 docs(agw): Document Sentry client filters
  docs/readmes/lte/configure_sentry.md
Labels: component: docs, size/S

#10276 chore(agw): Exclude message patterns in Sentry client
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/cloud/go/services/lte/servicers/builder_servicer.go
  lte/gateway/configs/gateway.mconfig
  lte/protos/mconfig/mconfigs.proto
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/orchestrator/obsidian/models/network_sentry_config_swaggergen.go
  orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/orchestrator/servicers/builder_servicer.go
  orc8r/gateway/python/magma/common/sentry.py
  orc8r/gateway/python/magma/common/tests/sentry_tests.py
  orc8r/lib/go/protos/mconfig/mconfigs.pb.go
  orc8r/protos/mconfig/mconfigs.proto
Labels: component: orc8r, component: agw, component: nms, size/XL, ready2merge

#10543 test(mme): Add injection of state loaded in SPGW state manager (issue #9606)
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.c
  lte/gateway/c/core/oai/test/spgw_task/CMakeLists.txt
  lte/gateway/c/core/oai/test/spgw_task/data/IMSI001010000000001_SPGW_ATTACHED
  lte/gateway/c/core/oai/test/spgw_task/data/IMSI001010000000002_SPGW_ATTACHED
  lte/gateway/c/core/oai/test/spgw_task/data/IMSI001010000000008_SPGW_ATTACHED
  lte/gateway/c/core/oai/test/spgw_task/data/data_list.txt
  lte/gateway/c/core/oai/test/spgw_task/mock_spgw_op.cpp
  lte/gateway/c/core/oai/test/spgw_task/mock_spgw_op.h
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_with_injected_state.cpp
Labels: component: agw, size/XL

#11206 fix(agw): Fix OAILOG_DEBUG in spgw
  lte/gateway/c/core/oai/tasks/sgw/sgw_paging.c
Labels: component: agw, size/XS

#10985 feat(agw): Added code to support centralized user plane teid allocation
  lte/gateway/c/core/oai/include/s8_messages_types.h
  lte/gateway/c/core/oai/lib/s8_proxy/s8_client_api.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/S8ServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_s11_handlers.h
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test_attach_proc.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
Labels: component: agw, size/L

#10805 test(amf): stateless unit test
  lte/gateway/c/core/oai/include/map.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_manager.h
  lte/gateway/c/core/oai/tasks/amf/include/amf_client_servicer.h
  lte/gateway/c/core/oai/test/amf/CMakeLists.txt
  lte/gateway/c/core/oai/test/amf/test_amf_app_state_converter.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_map.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
Labels: component: agw, size/XL

#11171 feat(agw): changed cli to show ambr max bandwidth information
  lte/gateway/python/magma/subscriberdb/main.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
  lte/gateway/python/magma/subscriberdb/tests/rpc_tests.py
Labels: component: agw, size/S

#11222 fix(agw): Added missing test case to non-sanity list
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_non_nat_dp_ul_tcp.py
Labels: component: agw, size/S

#10981 feat(feg): N7 interface PCF stub
  feg/cloud/go/protos/mock_core.pb.go
  feg/gateway/registry/local_registry.go
  feg/gateway/services/testcore/pcf/pcf/main.go
  feg/gateway/services/testcore/pcf/servicers/expectation.go
  feg/gateway/services/testcore/pcf/servicers/mock_driven_test.go
  feg/gateway/services/testcore/pcf/servicers/n7_handlers.go
  feg/gateway/services/testcore/pcf/servicers/pcf.go
  feg/gateway/services/testcore/pcf/servicers/rpc_handlers.go
  feg/protos/mock_core.proto
Labels: component: feg, size/XXL, ready2merge

#11233 fix(agw): Update the control plane and user plane teids to directoryd for inbound user
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
Labels: component: agw, size/XS

#10903 feat(amf): Proto fields to support stateless feature
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/protos/oai/mme_nas_state.proto
  lte/protos/oai/nas_state.proto
Labels: component: orc8r, component: agw, size/XXL

#10355 fix(nms): JS allerts
  nms/packages/magmalte/alerts/sync.js
  nms/packages/magmalte/app/views/equipment/GatewayYMLConfig.js
  nms/packages/magmalte/scripts/setPassword.js
Labels: component: nms, size/S

#11246 fix(agw): Add missing comma to default mconfig
  lte/gateway/configs/gateway.mconfig
Labels: component: agw, size/XS, ready2merge

#11167 docs: Magma settlement proposal
  docs/readmes/proposals/p024_magma_settlement_service.md
Labels: component: docs, size/L

#11155 style(dp): alembic migration lint
  dp/cloud/python/magma/db_service/migrations/versions/b0cad5321c88_.py
Labels: size/L

#11249 fix(nms): Fix flow errors
  nms/packages/magmalte/app/components/cwf/CWFGateways.js
  nms/packages/magmalte/app/components/feg/FEGGateways.js
  nms/packages/magmalte/app/components/feg/__tests__/FEGGatewaysTest.js
  nms/packages/magmalte/app/components/network/UpgradeConfig.js
  nms/packages/magmalte/app/views/equipment/EquipmentGateway.js
  nms/packages/magmalte/app/views/equipment/FEGGatewayDetailConfig.js
  nms/packages/magmalte/app/views/equipment/FEGGatewayDetailMain.js
  nms/packages/magmalte/app/views/equipment/FEGGatewaySummary.js
  nms/packages/magmalte/app/views/equipment/GatewayDetailConfig.js
  nms/packages/magmalte/app/views/equipment/GatewayDetailConfigEdit.js
  nms/packages/magmalte/app/views/equipment/GatewayDetailMain.js
  nms/packages/magmalte/app/views/equipment/GatewayDetailSubscribers.js
  nms/packages/magmalte/app/views/equipment/GatewaySummary.js
Labels: component: nms, size/M

#11213 chore(sctpd): Remove signal mask for SEGV
  lte/gateway/c/sctpd/src/sctpd.cpp
Labels: component: agw, size/XS, ready2merge

#11212 chore(sessiond): move sentry config to shared_config
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/c/session_manager/BUILD.bazel
  lte/gateway/c/session_manager/CMakeLists.txt
  lte/gateway/c/session_manager/sessiond_main.cpp
  lte/protos/mconfig/mconfigs.proto
Labels: component: orc8r, component: agw, size/XL, ready2merge

#11151 fix(agw): Fixed S1 Handover test case failure issue
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover.py
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover_cancel.py
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover_failure.py
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover_ping_pong.py
  lte/gateway/python/integ_tests/s1aptests/test_s1_handover_timer_expiry.py
Labels: component: agw, size/L

#11251 fix(pipelined): Fix eBPF init logic and arg passing
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
Labels: component: agw, size/S

#11264 chore(ci): Update ami with added subscriberdb load test change
  .github/workflows/agw-docker-load-test.yaml
Labels: component: ci, size/XS

#10803 feat(feg): SBI print HTTP request and response logs
  feg/gateway/sbi/mocks/mock_pcf.go
  feg/gateway/sbi/sbi.go
  feg/gateway/sbi/sbi_log_middleware.go
  feg/gateway/sbi/sbi_logger.go
  feg/gateway/sbi/sbi_test.go
Labels: component: feg, size/L, product: 5g sa

#10853 refactor(amf): re-aligned smfcontext structure parameters
  lte/gateway/c/core/oai/tasks/amf/amf_app_defs.h
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_pdu_resource_setup_req_rel.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context_and_proc.h
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_smf_send.cpp
  lte/gateway/c/core/oai/tasks/amf/deregistration_request.cpp
  lte/gateway/c/core/oai/tasks/amf/nas5g_message.cpp
  lte/gateway/c/core/oai/tasks/nas5g/include/M5GNasEnums.h
  lte/gateway/c/core/oai/tasks/nas5g/include/M5gNasMessage.h
  lte/gateway/c/core/oai/tasks/nas5g/include/SmfMessage.h
  lte/gateway/c/core/oai/tasks/nas5g/src/AmfMessage.cpp
  lte/gateway/c/core/oai/tasks/nas5g/src/SmfMessage.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_common_utils.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_encode_decode.cpp
Labels: component: agw, size/XL, ready2merge

#11014 feat(mme): Serialization and Deserialization of ngap state
  lte/cloud/go/protos/oai/ngap_state.pb.go
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.h
  lte/gateway/c/core/oai/test/ngap/CMakeLists.txt
  lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp
  lte/protos/oai/ngap_state.proto
Labels: component: orc8r, component: agw, size/L, ready2merge

#11272 fix(pipelined): Revert Fix eBPF init logic and arg passing
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
Labels: component: agw, size/S

#10757 feat(orc8r): Added network- and tenant-scoped endpoint security
  cwf/k8s/cwf_operator/go.sum
  feg/gateway/go.mod
  nms/packages/magmalte/generated/MagmaAPIBindings.js
  orc8r/cloud/go/obsidian/access/rest_middleware.go
  orc8r/cloud/go/obsidian/access/tests/identity_finder_test.go
  orc8r/cloud/go/obsidian/access/tests/rest_middleware_test.go
  orc8r/cloud/go/obsidian/swagger/v1/swagger.yml
  orc8r/cloud/go/services/certifier/constants/constants.go
  orc8r/cloud/go/services/certifier/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/certifier/obsidian/handlers/handlers_test.go
  orc8r/cloud/go/services/certifier/obsidian/models/policies_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/policy_list_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/policy_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/resource_swaggergen.go
  orc8r/cloud/go/services/certifier/obsidian/models/swagger.v1.yml
  orc8r/cloud/go/services/certifier/protos/certifier.pb.go
  orc8r/cloud/go/services/certifier/protos/certifier.proto
  orc8r/cloud/go/services/certifier/protos/helpers.go
  orc8r/cloud/go/services/certifier/servicers/certifier.go
  orc8r/cloud/go/services/certifier/storage/storage.go
  orc8r/cloud/go/services/certifier/storage/storage_blobstore.go
  orc8r/cloud/go/services/certifier/test_utils/test_utils.go
  orc8r/cloud/go/tools/accessc/handlers/add_admin_token.go
Labels: component: orc8r, component: nms, component: feg, size/XXL, component: cwf

#11250 fix(agw): Handled Release Access Bearer for all pdns sent for an UE
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_itti_messaging.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.c
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_s11_handlers.h
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_task.c
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test_attach_proc.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_utility.h
Labels: component: agw, size/L

#11241 feat: Federated Integ Test automated fab script
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/feg/s1ap_federated_test.md
  lte/gateway/fabfile.py
  lte/gateway/python/integ_tests/federated_tests/README.md
  lte/gateway/python/integ_tests/federated_tests/fabfile.py
  lte/gateway/python/integ_tests/federated_tests/s1aptests/test_attach_detach.py
  orc8r/tools/fab/hosts.py
Labels: component: orc8r, component: agw, component: docs, size/L

#10885 fix(amf): Converting ue_m5gmm_context_t to ue_proto and ue_proto to ue_m5gmm_context_t
  lte/cloud/go/protos/oai/mme_nas_state.pb.go
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
  lte/protos/oai/mme_nas_state.proto
Labels: component: orc8r, component: agw, size/XL

#11005 feat(mme): Serialization and Deserialization of m5g_ue_description and ngap_imsi_map in NGAP
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_converter.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_manager.cpp
  lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp
Labels: component: agw, size/L

#10906 feat(amf): AMF context Basic parameters Serialize & Deserialize
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.h
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
Labels: component: agw, size/L, ready2merge

#11039 fix(orc8r): Setup IAM Role for cert-manager
  .gitignore
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-aws/cert-manager.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/eks.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/outputs.tf
  orc8r/cloud/deploy/terraform/orc8r-aws/variables.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/cert-manager.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/examples/basic/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/k8s.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/main.tf
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/templates/orc8r-values.tpl
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/charts/certs/templates/aws-route53-secret-access-key.yaml
  orc8r/cloud/helm/orc8r/charts/certs/templates/route53-issuer.yaml
  orc8r/cloud/helm/orc8r/charts/certs/values.yaml
Labels: component: orc8r, size/L

#10322 feat(nms): Add support to configure PDN type of APN
  nms/packages/magmalte/app/views/traffic/ApnEdit.js
  nms/packages/magmalte/app/views/traffic/__tests__/ApnAddTest.js
  nms/packages/magmalte/mock/db.json
Labels: component: nms, size/M

#11217 feat: vscode support for python in devcontainer
  .devcontainer/devcontainer.json
Labels: size/S, ready2merge

#10966 docs: commenting on untested OS will lead to frustration
  docs/readmes/basics/prerequisites.md
Labels: component: docs, size/XS, ready2merge

#11011 chore(agw): Backport consolidation of sentry-cli and sentry_sdk releases
  .circleci/config.yml
  orc8r/tools/fab/pkg.py
Labels: size/S, ready2merge

#11009 chore(agw): Backport use version scheme that is understood by sentry
  circleci/fabfile.py
  docs/readmes/howtos/README_package.md
  docs/readmes/lte/build_install_magma_pkg_in_agw.md
  lte/gateway/fabfile.py
  lte/gateway/release/build-magma.sh
  lte/gateway/release/magma-postinst
  orc8r/tools/fab/pkg.py
Labels: size/M, ready2merge

#10953 docs: migration from Docusaurus to GitHub wiki
  .github/workflows/pr_bot.yml
  docs/readmes/assets/contributing/github-codespace-open.png
  docs/readmes/assets/contributing/remote-containers.png
  docs/readmes/assets/contributing/sessiond-breakpoint-code.png
  docs/readmes/assets/contributing/sessiond-gdb-list.png
  docs/readmes/assets/contributing/sessiond-start-debug.png
  docs/readmes/assets/contributing/sessiond-unit-test-codelens.png
  docs/readmes/assets/intellij_initial_run_configs.png
  docs/readmes/contributing/contribute_ci_checks.md
  docs/readmes/contributing/contribute_conventions.md
  docs/readmes/contributing/contribute_id_mappings.md
  docs/readmes/contributing/contribute_onboarding.md
  docs/readmes/contributing/contribute_vscode.md
  docs/readmes/contributing/contribute_workflow.md
Labels: component: docs, component: ci, size/XL, ready2merge

#11202 feat(agw): Add eBPF map management code to MME
  lte/gateway/c/core/oai/include/sgw_config.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/ebpf.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/ebpf_dl_map.h
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.c
  lte/gateway/c/core/oai/tasks/sgw/sgw_config.c
  lte/gateway/c/core/oai/test/mme_app_task/test_sgw_config.cpp
  lte/gateway/configs/spgw.yml
  lte/gateway/configs/templates/spgw.conf.template
  lte/gateway/python/scripts/generate_oai_config.py
Labels: component: agw, size/L

#10908 feat(amf): AMF security context Serialize and Deserialize
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.h
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
Labels: component: agw, size/L, ready2merge

#11275 fix(pipelined): Fix eBPF init logic and arg passing
  lte/gateway/python/magma/pipelined/ebpf/ebpf_manager.py
Labels: component: agw, size/M

#11223 fix(agw): Fixed ue state for no auth response after mme restart
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_main.c
Labels: component: agw, size/XS

#11224 fix(agw): Fixed no auth response after mme restart
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_no_auth_resp_with_mme_restart_reattach.py
Labels: component: agw, size/M

#11285 fix(orc8r): Format policy action & effect enums
  orc8r/cloud/go/services/certifier/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/certifier/protos/helpers.go
Labels: component: orc8r, size/L

#11277 fix(nms): Fixed minikube deployment db host value
  orc8r/cloud/helm/orc8r/examples/minikube.values.yaml
Labels: component: orc8r, size/XS

#11070 feat(mme): Stateless feature integration for NGAP
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
Labels: component: agw, size/S

#11279 feat(agw): Implement opt-out for Sentry, remove other options
  lte/gateway/configs/ctraced.yml
  lte/gateway/configs/directoryd.yml
  lte/gateway/configs/enodebd.yml
  lte/gateway/configs/eventd.yml
  lte/gateway/configs/health.yml
  lte/gateway/configs/kernsnoopd.yml
  lte/gateway/configs/magmad.yml
  lte/gateway/configs/mobilityd.yml
  lte/gateway/configs/monitord.yml
  lte/gateway/configs/pipelined.yml
  lte/gateway/configs/pipelined.yml_prod
  lte/gateway/configs/policydb.yml
  lte/gateway/configs/redirectd.yml
  lte/gateway/configs/smsd.yml
  lte/gateway/configs/state.yml
  lte/gateway/configs/subscriberdb.yml
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
  lte/gateway/python/magma/mobilityd/rpc_servicer.py
  lte/gateway/python/magma/monitord/cpe_monitoring.py
  lte/gateway/python/magma/pipelined/rpc_servicer.py
  lte/gateway/python/magma/smsd/relay.py
  lte/gateway/python/magma/subscriberdb/client.py
  lte/gateway/python/magma/subscriberdb/rpc_servicer.py
  orc8r/gateway/python/magma/common/sentry.py
  orc8r/gateway/python/magma/common/tests/sentry_tests.py
  orc8r/gateway/python/magma/ctraced/rpc_servicer.py
  orc8r/gateway/python/magma/directoryd/rpc_servicer.py
  orc8r/gateway/python/magma/eventd/rpc_servicer.py
  orc8r/gateway/python/magma/magmad/proxy_client.py
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
  orc8r/gateway/python/magma/state/garbage_collector.py
  orc8r/gateway/python/magma/state/state_replicator.py
Labels: component: orc8r, component: agw, size/L, ready2merge

#11225 fix(agw): Fixed multi ue attach and detach with mme restarts
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/test_attach_and_mme_restart_loop_detach_and_mme_restart_loop_multi_ue.py
Labels: component: agw, size/M

#11290 docs(orc8r): Removed nms_db_password from deploy orc8r
  docs/readmes/orc8r/deploy_install.md
Labels: component: docs, size/XS

#10861 refactor(orc8r): Segregation of EnodebStateLookup servicer as internal
  lte/cloud/go/services/lte/lte/main.go
  lte/cloud/go/services/lte/servicers/protected/lookup.go
  lte/cloud/go/services/lte/servicers/protected/lookup_test.go
  lte/cloud/go/services/lte/test_init/test_service_init.go
Labels: component: orc8r, size/S

#10917 refactor(orc8r): Segregation of StreamerProvider servicer
  lte/cloud/go/services/lte/servicers/provider_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/provider_servicer.go
  orc8r/cloud/go/services/streamer/providers/registry.go
  orc8r/cloud/go/services/streamer/providers/servicers/protected/provider.go
  orc8r/cloud/go/services/streamer/providers/servicers/protected/providers.go
  orc8r/cloud/go/services/streamer/providers/servicers/protected/providers_test.go
  orc8r/cloud/go/services/streamer/providers/servicers/protected/remote_provider.go
  orc8r/cloud/go/services/streamer/test_init/test_provider_servicer.go
Labels: component: orc8r, size/S

#10784 refactor(orc8r): Segregation of SubscriberLookup servicer as internal
  lte/cloud/go/services/subscriberdb/servicers/protected/lookup.go
  lte/cloud/go/services/subscriberdb/servicers/protected/lookup_test.go
  lte/cloud/go/services/subscriberdb/subscriberdb/main.go
  lte/cloud/go/services/subscriberdb/test_init/test_service_init.go
Labels: component: orc8r, size/S

#10907 refactor(orc8r): Moved indexermgr to protected
  orc8r/cloud/go/services/orc8r_worker/orc8r_worker/main.go
  orc8r/cloud/go/services/state/servicers/protected/indexer_mgr_servicer.go
  orc8r/cloud/go/services/state/servicers/protected/indexer_mgr_servicer_test.go
  orc8r/cloud/go/services/state/state/main.go
  orc8r/cloud/go/services/state/test_init/test_service_init.go
Labels: component: orc8r, size/S

#10900 refactor(orc8r): MetricsExporter service security changes
  orc8r/cloud/go/services/orchestrator/orchestrator/main.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/exporter_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/exporter_servicer_test.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/gaugeconverter.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/gaugeconverter_test.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/grpc_exporter_servicer.go
  orc8r/cloud/go/services/orchestrator/servicers/protected/grpc_exporter_servicer_test.go
Labels: component: orc8r, size/XS

#10899 refactor(orc8r): Device service security changes
  orc8r/cloud/go/services/device/device/main.go
  orc8r/cloud/go/services/device/servicers/protected/device.go
  orc8r/cloud/go/services/device/test_init/test_service_init.go
Labels: component: orc8r, size/XS

#11252 feg(session_proxy): fix HOST-IP-ADDRESS on CER
  feg/gateway/diameter/diameter_client.go
  feg/gateway/services/session_proxy/credit_control/gx/gx_client.go
  feg/gateway/services/session_proxy/credit_control/gy/gy_client.go
  feg/gateway/services/session_proxy/session_proxy/main.go
Labels: component: feg, size/M

#11304 chore: fix CMake style in MME
  lte/gateway/c/core/oai/CMakeLists.txt
Labels: component: agw, size/XS

#11287 fix(agw): refactor QoSManager
  lte/gateway/python/magma/pipelined/app/enforcement.py
  lte/gateway/python/magma/pipelined/app/gy.py
  lte/gateway/python/magma/pipelined/qos/common.py
  lte/gateway/python/magma/pipelined/service_manager.py
  lte/gateway/python/magma/pipelined/tests/app/start_pipelined.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
Labels: component: agw, size/M, ready2merge

#11266 chore(nms): create SBOM in CycloneDX format
  sbom/README.md
  sbom/npm-bom.json
Labels: size/XXL, ready2merge

#11307 chore: fix typo in asn1c.bzl
  bazel/asn1c.bzl
Labels: size/XS

#11032 test(mme): Stateless feature Unit Test for NGAP
  lte/gateway/c/core/oai/include/map.h
  lte/gateway/c/core/oai/tasks/ngap/include/ngap_client_servicer.h
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_state_manager.h
  lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp
Labels: component: agw, size/XL, ready2merge

#11310 feat: enodebd add print grpc messages
  lte/gateway/configs/enodebd.yml
  lte/gateway/python/magma/enodebd/enodeb_status.py
  lte/gateway/python/magma/enodebd/main.py
  lte/gateway/python/magma/enodebd/rpc_servicer.py
  lte/gateway/python/magma/enodebd/s1ap_client.py
  lte/gateway/python/magma/enodebd/tests/freedomfi_one_tests.py
Labels: component: agw, size/M

#11256 chore(ci): add json linter for all gateway.mconfig files
  .github/workflows/agw-workflow.yml
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/S, ready2merge

#11216 chore(agw): bazel test and coverage is supported for mobilityd
  .bazelrc
  .gitattributes
  bazel/external/requirements.in
  bazel/external/requirements.txt
  bazel/python_test.bzl
  bazel/python_utils/BUILD.bazel
  bazel/python_utils/coverage_decorator.py
  bazel/test_constants.bzl
  bazel/testing.md
  lte/gateway/python/magma/mobilityd/tests/BUILD.bazel
  lte/gateway/python/magma/pipelined/BUILD.bazel
Labels: component: agw, size/XL, ready2merge, bazel

#11297 chore(pipelined): Exclude config errors from Sentry
  lte/gateway/python/magma/pipelined/app/ipfix.py
Labels: component: agw, size/XS, ready2merge

#10958 feat(amf): Serialization and Deserialization of Smf Context
  lte/cloud/go/protos/oai/nas_state.pb.go
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_state_converter.h
  lte/gateway/c/core/oai/test/amf/test_amf_stateless.cpp
  lte/protos/oai/nas_state.proto
Labels: component: orc8r, component: agw, size/XL

#11140 fix(dp): handle logging when cbsd does not exist
  dp/cloud/python/magma/configuration_controller/response_processor/response_db_processor.py
  dp/cloud/python/magma/configuration_controller/run.py
Labels: size/M

#11318 fix: bazel test can use dependency iproute2
  experimental/bazel-base/Dockerfile
Labels: size/XS, ready2merge, bazel

#11309 feat(orc8r): change proto definitions to add orc8r_version field
  orc8r/lib/go/protos/marshaler_test.go
  orc8r/lib/go/protos/mconfig/mconfigs.pb.go
  orc8r/protos/mconfig/mconfigs.proto
Labels: component: orc8r, size/L, ready2merge

#11317 chore(agw): remove impl initialized function and avoid multiple initialization
  lte/gateway/python/magma/pipelined/qos/common.py
Labels: component: agw, size/S, ready2merge

#11257 chore(mme): move sentry config to shared_config
  lte/cloud/go/protos/mconfig/mconfigs.pb.go
  lte/gateway/c/core/oai/oai_mme/CMakeLists.txt
  lte/gateway/c/core/oai/oai_mme/oai_mme.c
  lte/protos/mconfig/mconfigs.proto
  orc8r/gateway/c/common/sentry/BUILD.bazel
  orc8r/gateway/c/common/sentry/CMakeLists.txt
  orc8r/gateway/c/common/sentry/SentryWrapper.cpp
  orc8r/gateway/c/common/sentry/includes/SentryWrapper.h
Labels: component: orc8r, component: agw, size/XL, ready2merge
