Repository magma/magma, pull requests merged in 2023-10, with the labels that each got.

#15309 fix(mme): Handling missing Supported TAs, ENB_UE_S1AP_ID and MME_UE_S1AP_ID
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
Labels: component: agw, size/L

#15315 fix(ci): Fixes for liblsan0 packages in Bazell base image
  .github/workflows/docker-builder-devcontainer.yml
Labels: component: ci, size/S

#15323 fix(ci): Fixes for liblsan0 packages in devcontainer and bazel base image
  .github/workflows/docker-builder-devcontainer.yml
Labels: component: ci, size/XS
