Repository magma/magma, pull requests merged in 2023-11, with the labels that each got.

#15334 fix(ci): Fixes for liblsan0 packages
  .bazelrc
Labels: size/XS

#15321 fix(orc8r): Stop web-inject attack on N/W creation
  nms/server/network/routes.ts
Labels: component: nms, size/S

#15335 fix(ci): Fixes for liblsan0 packages
  .github/workflows/docker-builder-devcontainer.yml
Labels: component: ci, size/S

#15330 fix(amf): Added Service Accept handling in case of Service Request with uplink data status
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
Labels: component: agw, size/S

#15337 fix(mme): Fixing the criticality of the HandoverCancelAcknowledge …
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
Labels: component: agw, size/XS

#15336 fix(amf): Fix for NG setup failure on N1 link restoration
  lte/gateway/c/core/oai/tasks/amf/amf_app_handler.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, size/S

#15326 fix(mme): Handling missing support for MME_UE_S1AP_ID and eNB_UE_S1AP_ID in E-RAB Modification Indication
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
Labels: component: agw, size/M

#15344 fix(ci): federated tests docker-compose fix
  lte/gateway/python/integ_tests/federated_tests/docker/docker-compose.yml
Labels: component: agw, size/XS
