Repository magma/magma, pull requests merged in 2023-06, with the labels that each got.

#15215 fix(nms): nginx ssl issue
  nms/docker/docker_ssl_proxy/proxy_ssl.conf
Labels: component: nms, size/XS

#15219 fix(ci): drop version from referenced workflow
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#15224 fix(ci): try suggested solution to fix pyrebase in publish script
  .github/workflows/build_all.yml
Labels: component: ci, workstream: devops, size/XS

#15226 fix(ci): via Revert "fix: script does not try to publish removed agw meta data (#15158)"
  ci-scripts/firebase_publish.py
Labels: component: ci, size/XS

#15228 fix(ci): Passing secrets to nested workflow
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#15229 fix(ci): cwag-ci taking big disk space
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#15001 fix(orc8r): Fixing the missing folder for prometheus rule configuration
  orc8r/cloud/docker/metrics-configs/alert_rules/.gitkeep
Labels: component: orc8r, size/XS
