Repository magma/magma, pull requests merged in 2023-08, with the labels that each got.

#15236 fix(mme): Handling for big nas packets
  lte/gateway/c/core/oai/common/TLVDecoder.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_mm_ies.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_itti_messaging.hpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/test/mme_app_task/test_mme_app_emm_encode_decode.cpp
  lte/gateway/c/core/oai/test/s1ap_task/data/data_list.txt
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.cpp
  lte/gateway/c/core/oai/test/s1ap_task/s1ap_mme_test_utils.h
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
Labels: type: bug, component: agw, size/L

#15278 fix(mme): Handling of missing RAN_UE_ID
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_nas_procedures.cpp
  lte/gateway/c/core/oai/test/s1ap_task/test_s1ap_mme_handlers.cpp
Labels: component: agw, size/M

#15277 feat(feg): Add ulr command to s6a_cli
  feg/gateway/tools/s6a_cli/main.go
Labels: component: feg, size/L

#15291 fix(pipelined): QOS test cases pertaining to bitrate units
  lte/gateway/python/magma/pipelined/qos/qos_meter_impl.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py
  lte/gateway/python/magma/pipelined/tests/test_qos.py
  lte/gateway/python/magma/pipelined/tests/test_qos_pyroute2.py
Labels: component: agw, size/M
