Repository magma/magma, pull requests merged in 2023-01, with the labels that each got.

#14771 fix(ci): remove print typo in package.sh
  orc8r/tools/helm/package.sh
Labels: component: orc8r, size/XS

#14664 feat(ci): Remove useless pipelines
  .github/workflows/magma-push-dummy-package.yml
Labels: component: ci, size/M

#14758 fix(orc8r): fix error messages in go http endpoints in orc8r
  lte/cloud/go/services/nprobe/obsidian/handlers/handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/policy_handlers.go
  lte/cloud/go/services/policydb/obsidian/handlers/rating_groups_handlers.go
  lte/cloud/go/services/smsd/servicers/smsd_rest.go
  lte/cloud/go/services/subscriberdb/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/certifier/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/ctraced/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/eventd/log/handlers/log_handlers.go
  orc8r/cloud/go/services/eventd/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/metricsd/obsidian/handlers/handlers.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_config_handler_test.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_receiver_handlers.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_receiver_handlers_test.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/alert_silencing_handlers.go
  orc8r/cloud/go/services/metricsd/prometheus/handlers/promo_handlers.go
  orc8r/cloud/go/services/obsidian/handler.go
  orc8r/cloud/go/services/obsidian/swagger/handlers/handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/about_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/common.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/gateway_command_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/network_handlers.go
  orc8r/cloud/go/services/orchestrator/obsidian/handlers/upgrade_handlers.go
  orc8r/cloud/go/services/tenants/obsidian/handlers/handlers.go
Labels: component: orc8r, size/XL

#14774 docs: adapt Docs to docker compose V2
  docs/docusaurus/create_docusaurus_website.sh
  docs/readmes/Makefile
  docs/readmes/basics/prerequisites.md
  docs/readmes/basics/quick_start_guide.md
  docs/readmes/cwf/deploy_build.md
  docs/readmes/cwf/deploy_install.md
  docs/readmes/cwf/deploy_intro.md
  docs/readmes/cwf/healthchecker.md
  docs/readmes/feg/debug_cli.md
  docs/readmes/feg/deploy_build.md
  docs/readmes/feg/deploy_install.md
  docs/readmes/feg/deploy_intro.md
  docs/readmes/feg/docker.md
  docs/readmes/feg/s1ap_federated_tests.md
  docs/readmes/howtos/inbound_roaming.md
  docs/readmes/lte/deploy_install_docker.md
  docs/readmes/nms/deploy_setup.md
  docs/readmes/nms/organizations.md
  docs/readmes/orc8r/dev_build.md
  docs/readmes/orc8r/dev_minikube.md
  docs/readmes/orc8r/dev_testing.md
Labels: component: docs, size/L

#14769 chore: mme compile warnings are reduced
  .bazelrc
  lte/gateway/c/core/oai/common/log.c
  lte/gateway/c/core/oai/common/log.h
  lte/gateway/c/core/oai/include/map.h
  lte/gateway/c/core/oai/include/proto_map.hpp
  lte/gateway/c/core/oai/lib/directoryd/directoryd.cpp
  lte/gateway/c/core/oai/lib/directoryd/directoryd.hpp
  lte/gateway/c/core/oai/lib/openflow/controller/GTPApplication.cpp
  lte/gateway/c/core/oai/lib/store/sqlite.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/amf/amf_recv.cpp
  lte/gateway/c/core/oai/tasks/grpc_service/AmfServiceImpl.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_embedded_spgw.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AttachAccept.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AttachRequest.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AuthenticationFailure.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/EmmInformation.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/SecurityModeCommand.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/SecurityModeComplete.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/TrackingAreaUpdateAccept.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/TrackingAreaUpdateRequest.cpp
  lte/gateway/c/core/oai/tasks/nas/esm/msg/ActivateDedicatedEpsBearerContextRequest.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
Labels: component: agw, size/L

#14785 docs: Replace NH_Network by Orc8r in Neutral Host architecture figure
  docs/docusaurus/versioned_docs/version-1.7.0/howtos/inbound_roaming.md
  docs/docusaurus/versioned_docs/version-1.8.0/howtos/inbound_roaming.md
  docs/readmes/howtos/inbound_roaming.md
Labels: component: docs, size/M

#14760 fix(agw): Broken Python CLI scripts in containerized AGW
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/XS

#14799 feat(ci): execute long extended tests in CI run
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/lte-integ-test-containerized.yml
  lte/gateway/python/integ_tests/Makefile
Labels: component: agw, component: ci, size/M

#14807 fix: long running tests are added as a dependency to result job for correct test result summary
  .github/workflows/agw-build-publish-container.yml
Labels: component: ci, size/XS

#14797 chore(agw): Remove code related to the bazel remote cache
  .bazelrc
  bazel/bazelrcs/cache.bazelrc
  bazel/bazelrcs/remote_caching_ro.bazelrc
  bazel/bazelrcs/remote_caching_rw.bazelrc
  bazel/scripts/remote_cache_bazelrc_setup.sh
Labels: size/L, bazel

#14811 fix: duplicated test log upload step is removed
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
Labels: component: ci, LTE-Integration-Test, size/XS

#14767 fix(amf): fix decode error while parsing EPS NAS message in registrat…
  lte/gateway/c/core/oai/tasks/nas5g/src/M5GRegistrationRequest.cpp
Labels: component: agw, size/S

#14812 chore: containerized integ test results are published
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, LTE-Integration-Test, size/XS

#14716 fix(agw): Migrate state_imsi_htbl in mme_app to protobuf map
  lte/gateway/c/core/oai/include/mme_app_state.hpp
  lte/gateway/c/core/oai/include/mme_app_ue_context.hpp
  lte/gateway/c/core/oai/include/state_manager.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_bearer.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_defs.hpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_hss_reset.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_sgs_reset.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.cpp
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_state_manager.hpp
Labels: component: agw, size/L

#14816 docs: apply correct Markdown syntax for links
  docs/readmes/nms/metrics.md
Labels: component: docs, size/XS

#14814 feat(ci): add default values to containerized LTE integ tests
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/composite/docker-builder-agw/action.yml
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/M

#14817 chore(ci): Mitigate flakiness of inout_non_nat test
  lte/gateway/python/magma/pipelined/gw_mac_address.py
Labels: component: agw, size/XS

#14813 chore: integ tests always wait for pipelined
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_wrapper.py
Labels: component: agw, size/S

#14794 fix(ci): adapt syntax of messages sent to Slack
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/S

#14824 chore(ci): remmove non-functional docker load test
  .github/workflows/agw-docker-load-test.yml
Labels: component: ci, size/M

#14819 chore: Do not use MAGMA_ROOT in Starlark format script
  .devcontainer/bazel-base/README.md
  bazel/scripts/run_buildifier.sh
  docs/readmes/lte/dev_unit_testing.md
Labels: component: docs, size/S, bazel

#14823 chore: simplify codeowner structure
  CODEOWNERS
  docs/readmes/contributing/contribute_codeowners.md
Labels: component: docs, DONOTLAND, size/L

#14827 docs: Format Markdown files in Magma
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DCO.md
  README.md
  SECURITY.md
  bazel/external/requirements_README.md
  bazel/testing.md
  cwf/gateway/helm/cwf-kubevirt/README.md
  cwf/gateway/helm/cwf-kubevirt/charts/secrets/README.md
  cwf/gateway/helm/cwf-virtlet/README.md
  cwf/gateway/helm/cwf-virtlet/charts/secrets/README.md
  cwf/gateway/integ_tests/README.md
  cwf/k8s/cwf_operator/README.md
  dp/cloud/helm/dp/charts/domain-proxy/README.md
  dp/cloud/python/magma/configuration_controller/README.md
  dp/tools/performance_tests/README.md
  dp/tools/ssh_tunnel/README.md
  experimental/cloudstrapper/README.md
  feg/gateway/helm/feg-kubevirt/README.md
  feg/gateway/helm/feg-kubevirt/charts/secrets/README.md
  feg/gateway/helm/feg-virtlet/README.md
  feg/gateway/helm/feg-virtlet/charts/secrets/README.md
  hil_testing/Magma_Ansible/README.md
  hil_testing/README.md
  hil_testing/spirent_automation/TC/Testplan.md
  lte/gateway/c/core/oai/lib/bstr/README.md
  lte/gateway/deploy/agwc-helm-charts/README.md
  lte/gateway/docker/README.md
  lte/gateway/docker/mme/README.md
  lte/gateway/docker/python-precommit/README.md
  lte/gateway/python/magma/pipelined/tests/envoy-tests/README.md
  nms/README.md
  nms/app/context/README.md
  nms/mock/README.md
  nms/shared/sequelize_models/README.md
  orc8r/cloud/deploy/bare-metal-ansible/README.md
  orc8r/cloud/deploy/bare-metal-ansible/docs/advanced_notes.md
  orc8r/cloud/deploy/bare-metal/README.md
  orc8r/cloud/deploy/orc8r_deployer/docker/README.md
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/README.md
  orc8r/cloud/deploy/terraform/README.md
  orc8r/cloud/deploy/terraform/orc8r-aws/README.md
  orc8r/cloud/helm/README.md
  orc8r/cloud/helm/orc8r/charts/certs/README.md
  orc8r/cloud/helm/orc8r/charts/metrics/README.md
  orc8r/cloud/helm/orc8r/charts/nms/README.md
  orc8r/cloud/helm/orc8r/charts/secrets/README.md
  orc8r/gateway/go/services/magmad/README.md
  orc8r/tools/packer/scripts/third_party/chef_bento/NOTICE_Bento.md
  show-tech/README.md
  third_party/README.md
  third_party/gtp_ovs/ovs-gtp-patches/2.15/README.md
Labels: component: orc8r, component: agw, component: ci, component: feg, size/XXL, component: cwf, component: dp

#14809 docs: Add Bazel documentation page for the Magma AGW
  .bazelrc
  WORKSPACE.bazel
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/readmes/bazel/agw_with_bazel.md
Labels: component: docs, size/XL, bazel

#14845 fix(cwg): wait for radius server in TestProxy
  feg/radius/src/modules/module_test_utils.go
  feg/radius/src/modules/proxy/proxy_test.go
  feg/radius/src/monitoring/scuba/scuba_test.go
Labels: size/S, component: cwf

#14753 chore: python code is checked by pylint
  .github/workflows/agw-workflow.yml
  dev_tools/BUILD.bazel
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp.py
  lte/gateway/python/magma/pipelined/gw_mac_address.py
  lte/gateway/python/magma/tests/pylint_tests.py
  orc8r/gateway/python/magma/tests/pylint_tests.py
Labels: component: orc8r, component: agw, component: ci, size/L

#14787 chore(ci): Magma apt repository is validated
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
Labels: component: agw, size/S

#14864 chore(ci): Add logging for yarn failure in generateAPIFromSwagger.sh
  nms/scripts/generateAPIFromSwagger.sh
Labels: component: nms, size/S

#14851 chore(ci): Release Bazel services for Sentry
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
Labels: component: ci, size/L, bazel-cleanup, bazel

#14870 fix: old digest is compared with new digest of helm dependencies
  .github/workflows/helm-chart-dependency-check.yml
Labels: component: ci, size/XS

#14847 fix(agw): Updating priority of default rule in AGW
  lte/gateway/python/magma/policydb/default_rules.py
  lte/gateway/python/magma/policydb/tests/test_streamer_callback.py
Labels: component: agw, size/S

#14717 fix(agw): Modified code to port s_plus_p_gw_eps_bearer_context_information_t to protobuf structure in spgw task
  lte/cloud/go/protos/oai/spgw_state.pb.go
  lte/gateway/c/core/common/dynamic_memory_check.cpp
  lte/gateway/c/core/oai/include/sgw_context_manager.hpp
  lte/gateway/c/core/oai/include/sgw_ie_defs.h
  lte/gateway/c/core/oai/include/spgw_state.hpp
  lte/gateway/c/core/oai/include/spgw_types.hpp
  lte/gateway/c/core/oai/lib/directoryd/directoryd.cpp
  lte/gateway/c/core/oai/lib/directoryd/directoryd.hpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.hpp
  lte/gateway/c/core/oai/lib/pcef/CMakeLists.txt
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.cpp
  lte/gateway/c/core/oai/lib/pcef/pcef_handlers.hpp
  lte/gateway/c/core/oai/tasks/amf/amf_app_ue_context.cpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_openflow.cpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.cpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtp_tunnel_upf.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u.hpp
  lte/gateway/c/core/oai/tasks/gtpv1-u/gtpv1u_task.cpp
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/mobilityd_ue_ip_address_alloc.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pco.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_pco.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.cpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_procedures.hpp
  lte/gateway/c/core/oai/tasks/sgw/pgw_ue_ip_address_alloc.hpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_context_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw/sgw_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.cpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_converter.hpp
  lte/gateway/c/core/oai/tasks/sgw/spgw_state_manager.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_handlers.cpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_s11_handlers.hpp
  lte/gateway/c/core/oai/tasks/sgw_s8/sgw_s8_state.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/sgw_s8_task/sgw_s8_test_attach_proc.cpp
  lte/gateway/c/core/oai/test/spgw_task/BUILD.bazel
  lte/gateway/c/core/oai/test/spgw_task/data/IMSI001010000000001_SPGW_ATTACHED
  lte/gateway/c/core/oai/test/spgw_task/data/IMSI001010000000002_SPGW_ATTACHED
  lte/gateway/c/core/oai/test/spgw_task/data/IMSI001010000000008_SPGW_ATTACHED
  lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_procedures_test_fixture.hpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.cpp
  lte/gateway/c/core/oai/test/spgw_task/spgw_test_util.h
  lte/gateway/c/core/oai/test/spgw_task/state_creators.cpp
  lte/gateway/c/core/oai/test/spgw_task/state_creators.hpp
  lte/gateway/c/core/oai/test/spgw_task/test_pgw_pco.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_dedicated_bearer.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_session.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_procedures_with_injected_state.cpp
  lte/gateway/c/core/oai/test/spgw_task/test_spgw_state_converter.cpp
  lte/gateway/python/integ_tests/s1aptests/test_attach_service_with_multi_pdns_and_bearers_multi_ue.py
  lte/protos/oai/spgw_state.proto
Labels: component: orc8r, component: agw, size/XXL

#14872 chore: unnecessary ref and repository attributes are removed
  .github/workflows/agw-workflow.yml
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
Labels: component: agw, component: ci, size/XS

#14869 chore: meta info (owner, purpose, remediation) is added to magma workflows
  .github/workflows/agw-build-publish-container.yml
  .github/workflows/agw-coverage.yml
  .github/workflows/agw-workflow.yml
  .github/workflows/autolabel-pullrequests.yml
  .github/workflows/backport-pull-request.yml
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/check-rebase.yml
  .github/workflows/cloud-workflow.yml
  .github/workflows/codeowners-syntax.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/comment-pr-on-check-failure.yml
  .github/workflows/cwag-workflow.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/cwf-operator.yml
  .github/workflows/dco-check.yml
  .github/workflows/docker-builder-devcontainer.yml
  .github/workflows/docker-builder-python-precommit.yml
  .github/workflows/docker-promote.yml
  .github/workflows/docs-workflow.yml
  .github/workflows/docusaurus-workflow.yml
  .github/workflows/dp-workflow.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/feg-workflow.yml
  .github/workflows/fossa-workflow.yml
  .github/workflows/golang-check-version.yml
  .github/workflows/helm-chart-dependency-check.yml
  .github/workflows/helm-deploy-on-demand.yml
  .github/workflows/helm-promote.yml
  .github/workflows/insync-checkin.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/magma-build-3rd-party.yml
  .github/workflows/magma-build-openvswitch.yml
  .github/workflows/magma-publish-go.yml
  .github/workflows/nms-workflow.yml
  .github/workflows/pr_bot.yml
  .github/workflows/python-workflow.yml
  .github/workflows/reviewdog-workflow.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/sudo-python-tests.yml
  .github/workflows/unit-test-workflow.yml
Labels: component: ci, size/L

#14882 docs: switch artifactory location in 1.8 docs
  docs/docusaurus/versioned_docs/version-1.8.0/basics/prerequisites.md
  docs/docusaurus/versioned_docs/version-1.8.0/orc8r/deploy_intro.md
  docs/docusaurus/versioned_docs/version-1.8.0/orc8r/dev_minikube.md
Labels: component: docs, size/S

#14881 revert: "test(agw): Add scaling tests for dhcp mode (#14724)"
  lte/gateway/python/integ_tests/defs.mk
  lte/gateway/python/integ_tests/s1aptests/BUILD.bazel
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_non_nat_dhcp.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_non_nat_dhcp_multi_ue.py
  lte/gateway/python/integ_tests/s1aptests/test_attach_detach_with_non_nat_dhcp_multi_ue_looped.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
Labels: component: agw, LTE-Integration-Test, size/L

#14875 feat(ci): change default registry for containerized integ tests
  .github/workflows/lte-integ-test-containerized.yml
Labels: component: ci, size/XS

#14855 fix(agw): Modified code to fix the s1ap crash
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_state.cpp
Labels: component: agw, size/XS

#14893 docs: fix broken links on Magma Proposals page
  docs/readmes/proposals/p014_proposal_process.md
Labels: component: docs, size/XS

#14884 fix(agw): Address selection of mypy errors in orc8r/gateway/python/
  orc8r/gateway/python/magma/common/health/service_state_wrapper.py
  orc8r/gateway/python/magma/common/service_registry.py
  orc8r/gateway/python/magma/ctraced/rpc_servicer.py
  orc8r/gateway/python/magma/eventd/event_validator.py
  orc8r/gateway/python/magma/magmad/gateway_status.py
  orc8r/gateway/python/magma/magmad/metrics_collector.py
  orc8r/gateway/python/magma/magmad/service_manager.py
  orc8r/gateway/python/magma/magmad/service_poller.py
  orc8r/gateway/python/magma/magmad/sync_rpc_client.py
  orc8r/gateway/python/magma/magmad/tests/state_reporter_test.py
  orc8r/gateway/python/magma/magmad/upgrade/upgrader2.py
  orc8r/gateway/python/magma/state/state_replicator.py
  orc8r/gateway/python/scripts/register.py
Labels: component: orc8r, size/M

#14784 feat(ci): enable publishing to Vagrant Cloud without user interaction
  orc8r/tools/packer/vagrant-box-upload.sh
Labels: component: ci, size/S

#14859 chore(ci): Remove Make MME build from build-containers workflow
  lte/gateway/docker/services/c/Dockerfile
Labels: component: ci, size/S, bazel

#14874 chore: cwag c images are build based on cached bazel image
  .github/workflows/build_all.yml
  bazel/bazelrcs/cwag.bazelrc
  cwf/gateway/docker/c/Dockerfile
Labels: component: ci, size/L, component: cwf

#14901 fix(ci): Run apt update in pylint job
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS

#14897 chore(ci): Move magma-libfluid dependency into the bazel-base image
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
Labels: component: ci, size/XS, bazel

#14898 chore(agw): Use system libraries for libfluid and lfds710
  bazel/cpp_repositories.bzl
  bazel/external/libfluid_base.BUILD
  bazel/external/libfluid_msg.BUILD
  bazel/external/liblfds.BUILD
  bazel/external/system_libraries.BUILD
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/docker/services/c/Dockerfile
  third_party/build/patches/libfluid/libfluid_base_patches/BUILD.bazel
  third_party/build/patches/libfluid/libfluid_msg_patches/BUILD.bazel
Labels: component: agw, component: ci, size/L, bazel

#14880 test(cwg): Make radius test sequential
  feg/radius/src/modules/coadynamic/coa_dynamic_test.go
  feg/radius/src/run.sh
Labels: size/XS, component: cwf

#14905 fix(ci): adapt failing behavior of containerized integ tests
  .github/workflows/agw-build-publish-container.yml
Labels: component: ci, size/XS

#14780 feat(agw): create new base images `magma-dev`, `magma-test`, and `magma-trfserver`
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
  .github/workflows/sudo-python-tests.yml
  lte/gateway/Vagrantfile
  lte/gateway/deploy/roles/bazel/tasks/main.yml
  lte/gateway/deploy/roles/dev_common/tasks/main.yml
  lte/gateway/deploy/roles/magma/tasks/main.yml
  lte/gateway/deploy/roles/magma_test/tasks/main.yml
  lte/gateway/deploy/roles/pyvenv/tasks/main.yml
  lte/gateway/deploy/roles/service_aliases/tasks/main.yml
  lte/gateway/deploy/roles/trfserver/tasks/main.yml
  orc8r/tools/ansible/roles/docker/tasks/install.yml
  orc8r/tools/ansible/roles/docker/tasks/install_debian.yml
  orc8r/tools/ansible/roles/docker/tasks/install_redhat.yml
  orc8r/tools/ansible/roles/gateway_dev/tasks/main.yml
  orc8r/tools/ansible/roles/gateway_services/tasks/main.yml
  orc8r/tools/ansible/roles/pkgrepo/tasks/main.yml
  orc8r/tools/ansible/roles/python_dev/tasks/main.yml
  orc8r/tools/packer/magma-dev-virtualbox.json
  orc8r/tools/packer/magma-test-virtualbox.json
  orc8r/tools/packer/magma-trfserver-virtualbox.json
  orc8r/tools/packer/scripts/ubuntu_setup.sh
Labels: component: orc8r, component: agw, component: ci, DONOTLAND, size/XL

#14889 fix(agw): Address mypy errors in lte/gateway/python/
  lte/gateway/python/dhcp_helper_cli/dhcp_helper_cli.py
  lte/gateway/python/integ_tests/gateway/rpc.py
  lte/gateway/python/integ_tests/s1aptests/s1ap_utils.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_non_nat_ded_bearer_dl_tcp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_non_nat_ded_bearer_ul_tcp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv4v6_non_nat_ul_tcp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_non_nat_ded_bearer_dl_tcp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_non_nat_ded_bearer_ul_tcp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_non_nat_dp_dl_tcp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_non_nat_dp_dl_udp.py
  lte/gateway/python/integ_tests/s1aptests/test_ipv6_non_nat_dp_ul_tcp.py
  lte/gateway/python/load_tests/loadtest_sessiond.py
  lte/gateway/python/magma/enodebd/device_config/configuration_init.py
  lte/gateway/python/magma/enodebd/tests/test_utils/enb_acs_builder.py
  lte/gateway/python/magma/mobilityd/ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/ip_descriptor.py
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp.py
  lte/gateway/python/magma/mobilityd/tests/test_ip_allocator_dhcp_with_vlan.py
  lte/gateway/python/magma/mobilityd/tests/test_multi_apn_ip_alloc.py
  lte/gateway/python/magma/pipelined/app/classifier.py
  lte/gateway/python/magma/pipelined/app/policy_mixin.py
  lte/gateway/python/magma/pipelined/ng_manager/session_state_manager_util.py
  lte/gateway/python/magma/pipelined/ng_set_session_msg.py
  lte/gateway/python/magma/pipelined/openflow/magma_match.py
  lte/gateway/python/magma/pipelined/qos/tc_ops.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_cmd.py
  lte/gateway/python/magma/pipelined/qos/tc_ops_pyroute2.py
  lte/gateway/python/magma/pipelined/tests/pipelined_test_util.py
  lte/gateway/python/magma/pipelined/tests/test_inout_non_nat.py
Labels: component: agw, size/L

#14896 fix(ci): Modify mypy configuration
  .github/workflows/reviewdog-workflow.yml
  mypy.ini
Labels: component: ci, size/S

#14738 refactor(agw): Improve `make check` command
  lte/gateway/python/Makefile
Labels: component: agw, size/S

#14918 Revert "chore(agw): Use system libraries for libfluid and lfds710 in Bazel (#14898)"
  bazel/cpp_repositories.bzl
  bazel/external/libfluid_base.BUILD
  bazel/external/libfluid_msg.BUILD
  bazel/external/liblfds.BUILD
  bazel/external/system_libraries.BUILD
  lte/gateway/c/core/BUILD.bazel
  lte/gateway/docker/services/c/Dockerfile
  third_party/build/patches/libfluid/libfluid_base_patches/BUILD.bazel
  third_party/build/patches/libfluid/libfluid_msg_patches/BUILD.bazel
Labels: component: agw, component: ci, size/L, bazel

#14914 ci: debian packages can be promoted by a manual workflow
  .github/workflows/debian-packages-promote.yml
Labels: component: ci, DONOTLAND, size/M

#14926 docs(orc8r): Updating Juju deployment how-to guide
  docs/readmes/orc8r/deploy_using_juju.md
Labels: component: docs, size/S

#14929 fix(ci): Remove `fail_on_error: true` from mypy step in CI
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/XS

#14906 fix(cwg): fix radius udp listener
  feg/radius/src/filters/filterstest/filter_mock.go
  feg/radius/src/server/server_test.go
  feg/radius/src/server/udp_listener.go
Labels: size/L, component: cwf

#14917 test(cwg): Remove duplicate Radius test
  feg/radius/src/modules/lbserve/lb_serve_test.go
Labels: size/M, component: cwf
