Repository magma/magma, pull requests merged in 2023-03, with the labels that each got.

#15098 feat(ci): GitHub workflows run on release branches
  .github/workflows/bazel.yml
  .github/workflows/sudo-python-tests.yml
Labels: component: ci, size/S

#15102 docs: Delete duplicate AGW bare metal installation guide
  docs/docusaurus/i18n/en.json
  docs/docusaurus/versioned_docs/version-1.7.0/lte/setup_baremetal.md
  docs/readmes/lte/setup_baremetal.md
Labels: component: docs, size/L

#15107 docs: Reorganise HIL documentation
  docs/docusaurus/i18n/en.json
  docs/readmes/lte/hil_tests.md
  hil_testing/README.md
Labels: component: docs, size/M

#15108 docs: Add callflow page to sidebars
  docs/docusaurus/i18n/en.json
  docs/docusaurus/sidebars.json
  docs/docusaurus/versioned_docs/version-1.7.0/lte/README_callflow.md
  docs/docusaurus/versioned_sidebars/version-1.7.0-sidebars.json
  docs/docusaurus/versioned_sidebars/version-1.8.0-sidebars.json
  docs/readmes/lte/readme_callflow.md
Labels: component: docs, size/S

#15099 chore(deps): bump golang.org/x/net from 0.0.0-20220121210141-e204ce36a2ba to 0.7.0 consolidated
  cwf/cloud/go/go.mod
  cwf/cloud/go/go.sum
  cwf/gateway/go.mod
  cwf/gateway/go.sum
  cwf/k8s/cwf_operator/go.mod
  cwf/k8s/cwf_operator/go.sum
  dp/cloud/go/go.mod
  dp/cloud/go/go.sum
  feg/cloud/go/go.mod
  feg/cloud/go/go.sum
  feg/cloud/go/protos/go.mod
  feg/cloud/go/protos/go.sum
  feg/gateway/go.mod
  feg/gateway/go.sum
  feg/radius/src/go.mod
  feg/radius/src/go.sum
  lte/cloud/go/go.mod
  lte/cloud/go/go.sum
  orc8r/cloud/api/v1/go/go.mod
  orc8r/cloud/api/v1/go/go.sum
  orc8r/cloud/go/go.mod
  orc8r/cloud/go/go.sum
  orc8r/cloud/test/go.mod
  orc8r/cloud/test/go.sum
  orc8r/gateway/go/go.mod
  orc8r/gateway/go/go.sum
  orc8r/lib/go/go.mod
  orc8r/lib/go/go.sum
  orc8r/lib/go/protos/go.mod
  orc8r/lib/go/protos/go.sum
Labels: component: orc8r, component: feg, size/L, component: cwf

#15109 fix(ci): failure slack message will display commit message
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-magma-deb.yml
Labels: component: ci, size/S

#15072 chore: Build the Python services with Bazel for the Dockerized AGW
  .dockerignore
  lte/gateway/docker/services/python/Dockerfile
  lte/gateway/fabfile.py
  lte/gateway/release/BUILD.bazel
Labels: component: agw, component: ci, size/L, bazel

#15119 docs: Fix some doc links
  docs/docusaurus/versioned_docs/version-1.4.X/contributing/contribute_onboarding.md
  docs/docusaurus/versioned_docs/version-1.5.X/proposals/p014_proposal_process.md
  docs/docusaurus/versioned_docs/version-1.7.0/proposals/p014_proposal_process.md
  docs/docusaurus/versioned_docs/version-1.8.0/proposals/p014_proposal_process.md
Labels: component: docs, size/XS

#15120 fix(ci): add quotation marks to client payload
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
Labels: component: ci, size/XS

#15079 chore: remove libvirt specific settings from Vagrantfiles
  cwf/gateway/Vagrantfile
  lte/gateway/Vagrantfile
  orc8r/tools/packer/vagrant-box-upload.sh
Labels: component: ci, DONOTLAND, size/M

#15049 build: Pin versions to make it possible to build all dependencies
  lte/gateway/python/setup.py
  lte/gateway/release/magma.lockfile.ubuntu
  lte/gateway/release/pydep
  orc8r/gateway/python/setup.py
Labels: component: orc8r, component: agw, component: ci, size/L

#15103 chore: Build the Python services with Bazel for the FEG Docker images
  bazel/runfiles.bzl
  bazel/scripts/check_py_bazel.sh
  feg/gateway/docker/python/Dockerfile
  feg/swagger/BUILD.bazel
  lte/gateway/docker/services/python/Dockerfile
  lte/gateway/release/BUILD.bazel
  orc8r/gateway/python/BUILD.bazel
  orc8r/gateway/python/magma/eventd/BUILD.bazel
  orc8r/gateway/python/magma/magmad/BUILD.bazel
  orc8r/gateway/python/magma/magmad/upgrade/BUILD.bazel
Labels: component: orc8r, component: ci, component: feg, size/L, bazel

#15110 ci: Add check for dereferenced symlinks
  .github/workflows/docs-workflow.yml
Labels: component: ci, size/S

#15123 Revert "fix(ci): failure slack message will display commit message (#15109)"
  .github/workflows/bazel.yml
  .github/workflows/build_all.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-magma-deb.yml
Labels: component: ci, size/S

#15128 chore(ci): Unblock CI by skipping broken NMS tests
  nms/app/components/cwf/__tests__/CWFGateways-test.tsx
  nms/app/views/equipment/__tests__/FEGGatewayDetailStatusTest.tsx
  nms/app/views/equipment/__tests__/GatewayLogsTest.tsx
  nms/app/views/events/__tests__/EventsTableTest.tsx
Labels: component: nms, size/S

#15117 chore: Add license headers to Dockerfiles
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
  bazel/docker/Dockerfile.bazel.cache
  ci-scripts/docker/Dockerfile.mme.ci.rhel8
  ci-scripts/docker/Dockerfile.mme.ci.ubuntu18
  cwf/gateway/docker/go/Dockerfile
  cwf/gateway/docker/python/Dockerfile
  docs/docusaurus/Dockerfile
  docs/readmes/Dockerfile
  dp/cloud/docker/python/configuration_controller/Dockerfile
  dp/cloud/docker/python/db_service/Dockerfile
  dp/cloud/docker/python/radio_controller/Dockerfile
  dp/cloud/docker/python/test_runner/Dockerfile
  dp/tools/fake_crl/Dockerfile
  dp/tools/fake_sas/Dockerfile
  dp/tools/harness/Dockerfile
  dp/tools/ssh_tunnel/Dockerfile
  feg/gateway/docker/go/Dockerfile
  feg/gateway/docker/radius/Dockerfile
  feg/radius/src/Dockerfile
  lte/gateway/docker/deploy/Dockerfile
  lte/gateway/docker/ghz/Dockerfile
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  lte/gateway/docker/python-precommit/Dockerfile
  nms/Dockerfile
  nms/mock/Dockerfile
  orc8r/cloud/deploy/orc8r_deployer/docker/Dockerfile
  orc8r/cloud/docker/controller/Dockerfile
  orc8r/cloud/docker/fluentd/Dockerfile
  orc8r/cloud/docker/fluentd_daemon/Dockerfile
  orc8r/cloud/docker/fluentd_forward/Dockerfile
  orc8r/cloud/docker/nginx/Dockerfile
Labels: component: orc8r, component: nms, component: docs, component: ci, component: feg, size/L, component: cwf, component: dp

#15131 fix(ci): evaluate dry run condition correctly
  .github/workflows/bazel.yml
Labels: component: ci, size/XS

#15130 fix(ci): Fix out of space error for Bazel Docker cache build
  .github/workflows/docker-builder-devcontainer.yml
Labels: component: ci, size/M, bazel

#15105 chore(ci): improve wemake workflow logging
  .github/workflows/reviewdog-workflow.yml
Labels: component: ci, size/XS

#14831 chore: vagrant up magma* VMs failures in CI are mitigated by retry
  lte/gateway/fabfile.py
  orc8r/tools/fab/hosts.py
  orc8r/tools/fab/vagrant.py
Labels: component: orc8r, component: agw, size/L

#15056 docs: Added better instructions for deploying helm charts
  docs/readmes/orc8r/dev_minikube.md
Labels: component: docs, size/M

#15126 chore(deps): upgrade prometheus/client_golang to v1.12.2
  feg/radius/lib/go/oc/go.mod
  feg/radius/lib/go/oc/go.sum
  feg/radius/src/go.mod
  feg/radius/src/go.sum
  orc8r/gateway/go/go.mod
  orc8r/gateway/go/go.sum
  orc8r/lib/go/go.mod
  orc8r/lib/go/go.sum
Labels: component: orc8r, size/XXL, component: cwf

#15038 chore(agw): build python precommit container locally
  .github/workflows/docker-builder-python-precommit.yml
  docs/readmes/lte/dev_unit_testing.md
  lte/gateway/python/precommit.py
Labels: component: agw, component: docs, component: ci, size/M

#15027 refactor(agw): cleanup lte fabfile
  lte/gateway/fabfile.py
Labels: component: agw, size/L

#15106 chore: Build the Python services with Bazel for CWF Docker images
  .github/workflows/cwf-integ-test.yml
  bazel/runfiles.bzl
  cwf/gateway/docker/python/Dockerfile
  cwf/protos/BUILD.bazel
  cwf/swagger/BUILD.bazel
  lte/gateway/docker/services/python/Dockerfile
  lte/gateway/python/BUILD.bazel
  lte/gateway/release/BUILD.bazel
  orc8r/gateway/python/BUILD.bazel
  orc8r/gateway/python/magma/configuration/BUILD.bazel
  orc8r/gateway/python/magma/eventd/BUILD.bazel
Labels: component: orc8r, component: agw, component: ci, CWF-Integ-Test, size/L, bazel-cleanup, component: cwf, bazel

#15144 chore(ci): Remove AGW Make workflows for the AGW Bazel switchover
  .github/workflows/build_all.yml
  .github/workflows/lte-integ-test-magma-deb.yml
  .github/workflows/lte-integ-test.yml
Labels: component: ci, size/L

#15132 feat(agw): set up containerized agw with fabric
  lte/gateway/docker/README.md
  lte/gateway/fabfile.py
Labels: component: agw, component: ci, size/M

#15104 fix(mme): Tuning response timers for Moblityd
  lte/gateway/c/core/oai/lib/mobility_client/MobilityClientAPI.cpp
  lte/gateway/c/core/oai/lib/mobility_client/MobilityServiceClient.hpp
  lte/gateway/python/dhcp_helper_cli/dhcp_helper_cli.py
  lte/gateway/python/magma/pipelined/gw_mac_address.py
Labels: component: agw, size/S

#15143 chore(deps): Upgrade golang.org/x/sys to 0.5.0 in feg/radius/lib/go/oc
  feg/radius/lib/go/oc/go.mod
  feg/radius/lib/go/oc/go.sum
Labels: size/XS, component: cwf

#15148 fix(agw): Fixed integ_test_deb_installation
  lte/gateway/fabfile.py
Labels: component: agw, size/XS

#15149 fix(mme): Handled SCTP_SENDER_DRY_EVENT notification
  lte/gateway/c/sctpd/src/util.cpp
Labels: type: bug, component: agw, priority: high, size/XS, product: 5g sa

#15135 docs: Fix outdated links in docs
  docs/docusaurus/versioned_docs/version-1.0.0/feg/legacy/FAQ.md
  docs/docusaurus/versioned_docs/version-1.0.0/feg/legacy/README.md
  docs/docusaurus/versioned_docs/version-1.0.0/symphony/download_requirements.md
  docs/docusaurus/versioned_docs/version-1.0.X/feg/legacy/FAQ.md
  docs/docusaurus/versioned_docs/version-1.0.X/feg/legacy/README.md
  docs/docusaurus/versioned_docs/version-1.1.X/feg/legacy/README.md
  docs/docusaurus/versioned_docs/version-1.2.X/proposals/p002_scaled_prometheus_pipeline.md
  docs/docusaurus/versioned_docs/version-1.4.X/nms/metrics.md
  docs/docusaurus/versioned_docs/version-1.5.X/contributing/contribute_conventions.md
  docs/docusaurus/versioned_docs/version-1.5.X/howtos/troubleshooting/user_unable_to_attach.md
  docs/docusaurus/versioned_docs/version-1.5.X/lte/configure_sentry.md
  docs/docusaurus/versioned_docs/version-1.5.X/lte/deploy_install.md
  docs/docusaurus/versioned_docs/version-1.5.X/lte/upgrade_1_5.md
  docs/docusaurus/versioned_docs/version-1.5.X/nms/metrics.md
  docs/docusaurus/versioned_docs/version-1.5.X/proposals/p011_victoriametrics.md
  docs/docusaurus/versioned_docs/version-1.6.X/contributing/contribute_conventions.md
  docs/docusaurus/versioned_docs/version-1.6.X/lte/configure_sentry.md
  docs/docusaurus/versioned_docs/version-1.6.X/lte/upgrade_1_5.md
  docs/docusaurus/versioned_docs/version-1.6.X/nms/metrics.md
  docs/docusaurus/versioned_docs/version-1.6.X/orc8r/deploy_intro.md
  docs/docusaurus/versioned_docs/version-1.6.X/orc8r/dev_minikube.md
  docs/docusaurus/versioned_docs/version-1.6.X/proposals/p017_apn_refactoring.md
  docs/docusaurus/versioned_docs/version-1.7.0/cwf/deploy_install.md
  docs/docusaurus/versioned_docs/version-1.7.0/feg/architecture_overview.md
  docs/docusaurus/versioned_docs/version-1.7.0/howtos/troubleshooting/user_unable_to_attach.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/README_AGW.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/datapath.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/integrated_5g_sa.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/pipelined.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/tr069.md
  docs/docusaurus/versioned_docs/version-1.7.0/lte/upgrade_1_5.md
  docs/docusaurus/versioned_docs/version-1.7.0/nms/alert.md
  docs/docusaurus/versioned_docs/version-1.7.0/nms/metrics.md
  docs/docusaurus/versioned_docs/version-1.7.0/orc8r/deploy_intro.md
  docs/docusaurus/versioned_docs/version-1.7.0/orc8r/dev_minikube.md
  docs/docusaurus/versioned_docs/version-1.7.0/orc8r/upgrade_1_1.md
  docs/docusaurus/versioned_docs/version-1.7.0/proposals/p002_scaled_prometheus_pipeline.md
  docs/docusaurus/versioned_docs/version-1.7.0/proposals/p011_victoriametrics.md
  docs/docusaurus/versioned_docs/version-1.7.0/proposals/p020_sgi_tunnel_transport.md
  docs/docusaurus/versioned_docs/version-1.7.0/resources/ref_magma_metrics.md
  docs/docusaurus/versioned_docs/version-1.8.0/lte/pipelined.md
  docs/docusaurus/versioned_docs/version-1.8.0/nms/metrics.md
  docs/readmes/lte/upgrade_1_5.md
  docs/readmes/nms/metrics.md
  docs/readmes/proposals/p002_scaled_prometheus_pipeline.md
  docs/readmes/proposals/p011_victoriametrics.md
  docs/readmes/proposals/p020_sgi_tunnel_transport.md
  docs/readmes/resources/ref_magma_metrics.md
Labels: component: docs, size/L

#15151 docs: Fix missing sidebar items
  .github/workflows/docs-workflow.yml
  bazel/scripts/check_py_bazel.sh
  docs/Makefile
  docs/check_sidebars.py
  docs/docusaurus/i18n/en.json
  docs/docusaurus/versioned_docs/version-1.7.0/lte/setup.md
  docs/docusaurus/versioned_sidebars/version-1.7.0-sidebars.json
Labels: component: docs, component: ci, size/L

#15147 chore: add security considerations section to pull request template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS

#15158 fix: script does not try to publish removed agw meta data
  ci-scripts/firebase_publish.py
Labels: component: ci, size/XS
