Repository magma/magma, pull requests merged in 2024-10, with the labels that each got.

#15540 fix(ci): lint and liblfds fixes
  .github/workflows/agw-workflow.yml
  bazel/cpp_repositories.bzl
  lte/gateway/c/core/oai/tasks/mme_app/mme_app_context.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/SecurityModeControl.cpp
  lte/gateway/c/core/oai/tasks/nas/esm/PdnConnectivity.cpp
  lte/gateway/c/core/oai/tasks/ngap/messages/asn1/r16/r16.asn1
  lte/gateway/c/core/oai/test/ngap/test_ngap_flows.cpp
  lte/gateway/c/core/oai/test/ngap/test_ngap_state_converter.cpp
Labels: component: agw, component: ci, size/L

#15542 fix(orc8r): fix for new ssl directive
  orc8r/cloud/helm/orc8r/charts/nms/templates/etc/_certs_nginx_proxy_ssl.conf.tpl
  orc8r/cloud/helm/orc8r/charts/nms/templates/etc/_nginx_proxy_ssl.conf.tpl
Labels: component: orc8r, size/S

#15438 fix: #15390 governance
  CONTRIBUTING.md
  README.md
Labels: size/L

#15551 fix(subscriberdb): handle invalid curve point exceptions
  lte/gateway/python/magma/subscriberdb/crypto/EC.py
  lte/gateway/python/magma/subscriberdb/crypto/ECIES.py
Labels: component: agw, size/S

#15553 fix(mme): Fix TASK_NGAP crash when gNB_ref is NULL
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf.c
Labels: component: agw, size/S
