Repository magma/magma, pull requests merged in 2025-05, with the labels that each got.

#15689 fix(ci): Update helm chart versions
  .github/workflows/build_all.yml
  cwf/cloud/helm/cwf-orc8r/Chart.yaml
  docs/readmes/orc8r/deploy_install.md
  docs/readmes/orc8r/deploy_intro.md
  dp/cloud/helm/dp/charts/domain-proxy/Chart.yaml
  feg/cloud/helm/feg-orc8r/Chart.yaml
  lte/cloud/helm/lte-orc8r/Chart.yaml
  orc8r/cloud/deploy/orc8r_deployer/docker/root/data/vars.yml
  orc8r/cloud/deploy/terraform/orc8r-helm-aws/variables.tf
  orc8r/cloud/helm/orc8r/Chart.yaml
Labels: size/M

#15692 fix(ci): Update helm credentials
  .github/workflows/helm-promote.yml
  orc8r/tools/helm/promote.sh
Labels: size/XS

#15660 fix(agw): download valid signing key
  lte/gateway/deploy/roles/agw_docker/vars/all.yaml
  lte/gateway/deploy/roles/magma_deploy/tasks/main.yml
  lte/gateway/deploy/roles/magma_deploy/vars/all.yaml
Labels: component: agw, size/S
