Repository magma/magma, pull requests merged in 2025-03, with the labels that each got.

#15539 fix(deps): specify dotenv version in dockerfile
  .devcontainer/Dockerfile
Labels: size/XS

#15609 chore: update governance to reflect TSC consensus
  CONTRIBUTING.md
Labels: size/XS

#15568 fix(subscriberdb): handle invalid curve point exceptions
  lte/gateway/python/magma/subscriberdb/crypto/EC.py
  lte/gateway/python/magma/subscriberdb/crypto/ECIES.py
Labels: component: agw, size/S

#15586 fix(magmad): restart options
  lte/gateway/configs/magmad.yml
  lte/gateway/docker/docker-compose.yaml
  orc8r/gateway/python/magma/magmad/rpc_servicer.py
Labels: component: orc8r, component: agw, component: ci, size/M

#15555 chore: acknowledgements for security researchers
  README.md
Labels: size/XS

#15235 fix(ci): td-agent-bit version pinning (#15164)
  lte/gateway/docker/services/python/Dockerfile
Labels: component: ci, size/XS

#15564 fix(agw): Fix ansible installation of nghttp2-proxy
  orc8r/tools/ansible/roles/gateway_services/tasks/main.yml
Labels: component: orc8r, size/XS

#15582 fix(orc8r): fix for error introduced in PR #15542 new ssl
  orc8r/cloud/helm/orc8r/charts/nms/templates/etc/_nginx_proxy_ssl.conf.tpl
Labels: component: orc8r, size/XS

#15562 fix(ci): start devcontainer from directories other than 'magma'
  .devcontainer/post-create-commands.sh
Labels: size/S

#15587 fix(ci): Dockerfile 'as' and 'FROM' keywords' casing do not match
  .devcontainer/Dockerfile
  .devcontainer/bazel-base/Dockerfile
  cwf/gateway/docker/c/Dockerfile
  cwf/gateway/docker/go/Dockerfile
  cwf/k8s/cwf_operator/docker/Dockerfile
  dp/cloud/docker/python/configuration_controller/Dockerfile
  dp/cloud/docker/python/db_service/Dockerfile
  dp/cloud/docker/python/radio_controller/Dockerfile
  dp/cloud/docker/python/test_runner/Dockerfile
  dp/tools/fake_crl/Dockerfile
  dp/tools/fake_sas/Dockerfile
  dp/tools/harness/Dockerfile
  feg/gateway/docker/go/Dockerfile
  feg/gateway/docker/radius/Dockerfile
  feg/radius/src/Dockerfile
  lte/gateway/docker/ghz/Dockerfile
  nms/Dockerfile
  nms/mock/Dockerfile
  orc8r/cloud/docker/controller/Dockerfile
Labels: component: orc8r, component: nms, component: ci, component: feg, size/M, component: cwf, component: dp

#13834 fix(agw): Fix for the issue related to earlier kernels as reported in #13831
  third_party/gtp_ovs/ovs-gtp-patches/2.15/0025-IPv6-Kernel-before-ipv6_stub-change.patch
Labels: component: agw, size/M

#13961 feat(agw): Basic eDRX support
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008.h
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_gmm_ies.c
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AttachRequest.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/msg/AttachRequest.hpp
Labels: component: agw, size/M

#15620 fix(ci): Add `docussaurus` scope to semantic workflow
  .github/workflows/semantic-pr.yml
Labels: component: ci, size/XS

#15559 fix: ModuleNotFoundError: No module named 'distutils'
  .github/workflows/agw-workflow.yml
Labels: component: ci, size/XS

#15632 fix(ci): Update LF registry key
  keys/linux_foundation_registry_key.asc
Labels: size/M

#15637 fix(nms): code scanning alert no. 141: DOM text reinterpreted as HTML
  nms/app/components/admin/Networks.tsx
Labels: component: nms, status: in progress, size/XS

#15638 fix(ci): Fixing fatal error: detected dubious ownership
  .github/workflows/bazel.yml
Labels: component: ci, status: in progress, size/XS

#15401 fix(mme): Enforce stricter input validation for S1AP/NGAP/NAS payloads
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_mm_ies.c
  lte/gateway/c/core/oai/lib/3gpp/3gpp_24.008_sm_ies.c
  lte/gateway/c/core/oai/tasks/amf/amf_as.cpp
  lte/gateway/c/core/oai/tasks/nas/emm/sap/emm_as.cpp
  lte/gateway/c/core/oai/tasks/nas/ies/EsmMessageContainer.cpp
  lte/gateway/c/core/oai/tasks/nas/ies/PdnAddress.cpp
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_handlers.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_amf_nas_procedures.c
  lte/gateway/c/core/oai/tasks/ngap/ngap_common.h
  lte/gateway/c/core/oai/tasks/s1ap/s1ap_mme_handlers.cpp
Labels: component: agw, status: in progress, size/L

#15560 fix(deps): change liblfds reference to a working one. Copies content …
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
Labels: component: ci, status: in progress, size/XS

#15369 fix(agw): Upgrade ASN library to the new version
  bazel/asn1c.bzl
  lte/gateway/c/core/oai/tasks/ngap/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s1ap/CMakeLists.txt
  lte/gateway/c/core/oai/tasks/s1ap/generate_asn1
  lte/gateway/docker/mme/Dockerfile.rhel8
  lte/gateway/docker/mme/Dockerfile.ubuntu18.04
  third_party/build/bin/asn1c_build.sh
Labels: component: agw, component: ci, status: in progress, size/S

#15640 fix(ci): action cache update
  .github/workflows/build_all.yml
  .github/workflows/cwf-integ-test.yml
  .github/workflows/dco-check.yml
  .github/workflows/federated-integ-test.yml
  .github/workflows/lte-integ-test-bazel-magma-deb.yml
  .github/workflows/lte-integ-test-containerized.yml
  .github/workflows/sudo-python-tests.yml
  cwf/gateway/docker/go/Dockerfile
  cwf/gateway/docker/python/Dockerfile
Labels: component: ci, size/M, component: cwf
