Repository magma/magma, pull requests merged in 2025-04, with the labels that each got.

#15657 fix(ci): Fixing the ci jobs
  .github/workflows/cwf-integ-test.yml
  .github/workflows/python-workflow.yml
Labels: component: ci, size/XS

#15658 fix(ci): Fix the agw container build error
  .github/workflows/agw-build-publish-container.yml
Labels: component: ci, size/M

#15652 fix(nms): data plan bitrate information inverted
  nms/app/views/traffic/DataPlanOverview.tsx
Labels: component: nms, size/S

#15557 fix(amf): Correct MSIN decoding for BCD-encoded deconcealed IMSI (v1.9)
  lte/gateway/c/core/oai/lib/n11/M5GSUCIRegistrationServiceClient.cpp
  lte/gateway/c/core/oai/tasks/amf/nas_proc.cpp
  lte/gateway/c/core/oai/test/amf/test_amf_procedures.cpp
Labels: component: agw, status: planned, size/M
